### ISSUE TITLE
Displaying issue in the GUI

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1001]
"Width" is not displayed on the GUI in the MEncoder video engines section.
It's look chineese to me, but the culprit should be in these [2 first lines of code](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/14b5de126c35033df3a8c29a655770f2616129c0/src/main/java/net/pms/encoders/MEncoderVideo.java#L312L314) ?
```
builder.add(GuiUtil.getPreferredSizeComponent(scaler), FormLayoutUtil.flip(cc.xyw(3, 5, 7), colSpec, orientation));

		builder.addLabel(Messages.getString("MEncoderVideo.28"), FormLayoutUtil.flip(cc.xy(9, 5, CellConstraints.RIGHT, CellConstraints.CENTER), colSpec, orientation));
		scaleX = new JTextField("" + configuration.getMencoderScaleX());
		scaleX.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				try {
					configuration.setMencoderScaleX(Integer.parseInt(scaleX.getText()));
				} catch (NumberFormatException nfe) {
					LOGGER.debug("Could not parse scaleX from \"" + scaleX.getText() + "\"");
				}
			}
		});
```
![capture_09072016_181433](https://cloud.githubusercontent.com/assets/18471069/18321780/68f5b06c-7527-11e6-929a-f9cb6e037417.jpg)

**Comment by valib** [comment]
@Sami32 thanks for reporting.

**Comment by Sami32** [comment]
@valib Thanks for fixing it ;-)
Ironically i discovered this while updating some part of the wiki.
