### ISSUE TITLE
UMS doesnt start on Arch Linux

### ISSUE THREAD

**Issue by Silver360** [UniversalMediaServer/UniversalMediaServer#1005]
Hi, i have a problem. I am trying run UMS byt when i type ./UMS.sh i get

`
./UMS.sh: line 67: /usr/bin/java: Success
`

And nothing happend. I don't know what is going wrong.

**Comment by Sami32** [comment]
Hello @Silver360 
did you followed these step ?
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions
https://wiki.archlinux.org/index.php/PS3_Mediaserver

Hoping that will help you, if not don't hesitate to return feedback here.

**Comment by Silver360** [comment]
@Sami32 Yes, but i stucked on step 4 becasue UMS doesn't start.

**Comment by Sami32** [comment]
http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=8536&start=10#p27924

@Silver360 If you really don't miss the note below, you'll need help from a Linux skilled developper.
> Note: You cannot start the UMS GUI via a standard SSH connection and expect to access it on the desktop afterwards.

**Comment by Silver360** [comment]
Yea, i don't use SSH ok, thx for help

**Comment by Sami32** [comment]
@Silver360 Did you already solved this issue ?

**Comment by Silver360** [comment]
Sad but no, i reinstaled Debian and all was easy.

**Comment by Sami32** [comment]
@Silver360 Did you tried as told by @atamariya , as he have a good Linux skill, because it's not an UMS issue.
So if one day you really want use it on Arch, you can always post the result that @atamariya asked, in a text file or screen capture, as you like.

**Comment by Sami32** [comment]
Could be re-open when the @atamariya advice will be follow, as it's not an UMS issue, imo.
> Try running with "sh -x UMS.sh" and paste the output here
