### ISSUE TITLE
Avisynth true motion with specific subtitle selection?

### ISSUE THREAD

**Issue by willsheng** [UniversalMediaServer/UniversalMediaServer#1010]
I want to use UMS with true motion with anime, but many anime .mkvs come with multiple subs with the same language:
Subtitle: [S: English OP/ED + Signs/Titles [English]]
Subtitle: [S: English Subtitles [English]]
Subtitle: [S: English Cast Commentary Subtitles [English]]

True motion requires an Avisynth engine to be selected for transcoding, and from what I can tell, the Avisynth engines require DirectVobSub for subtitles.

Using DirectVobSub with Avisynth requires Haali Media Splitter, as far as I know, and I couldn't find a way to configure Haali to be able to choose the second english subtitle in an mkv.

I believe something like the "Forced tags" setting under Transcoding Settings -> Common Transcode Settings -> Subtitles Settings would work, but it seems that choosing an Avisynth engine in UMS disables the built in UMS subtitle system.

I also tried using LAV Splitter, as their advanced subtitle selection mode also allows me to choose a specific subtitle, but I couldn't find a way to make DirectVobSub work without Haali.

Is there a reason why choosing an Avisynth engine disables UMS's built in subtitle system? Does anyone know of a way I could get true motion working with a way to choose a specific embedded subtitle track?

**Comment by Sami32** [comment]
@willsheng Same question here:
http://www.universalmediaserver.com/forum/viewtopic.php?t=1688

About Haali subtitles configuration:
https://www.codecguide.com/faq_configuration.htm

Maybe you could find some other helpful elements there: (i never tried them though)
http://www.universalmediaserver.com/forum/viewtopic.php?t=501
https://darkimmortal.com/2010/12/how-to-watch-anime-properly-on-ps3-media-server/
http://avisynth.nl/index.php/External_filters#Subtitling   (other subtitles plugins)
http://www.thehtpc.net/htpc-tips-and-tweaks/media-center-lav-filters-and-external-subtitles/

You speak about internal/embedded subtitles only, right ?
More skilled developper as @SubJunk should be more more helpful on it than i can.

**Comment by willsheng** [comment]
@Sami32 Thanks for the help.

I saw the same question on the UMS forums, and the page on Haali configuration, but neither seem to have the answers I'm looking for.

Unfortunately, the other four links don't seem to have information that could help me either.

I am only talking specifically about .mkv files with multiple internal/embedded subtitles that have the same language tag, and I just want the ability to choose a specific subtitle track while using true motion through UMS.

**Comment by ExSport** [comment]
@willsheng AviSynth goes completely outside UMS logic as external filter is loaded.
In past I am sure I tested it with something like VobSub and I was able to define subtitle preference there but you can't expect with something similar like it is in UMS where you have huge possibilities.

**Comment by willsheng** [comment]
@ExSport Do you know if theres a way to have DirectVobSub hook into LAV Splitter instead of Haali Media Splitter? Or if theres any other way to get subtitles to work with Avisynth besides going through DirectVobSub/Haali?

Currently, my fallback is manually extracting specific subtitle tracks from my mkvs and forcing Avisynth to use the external subs, but its not very ideal.

**Comment by SubJunk** [comment]
Stale
