### ISSUE TITLE
FR: Serverside search

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#1011]
Hi

My upnp client says that the server does not support search if so it would be great to have file search and random playlist stuff.

thanks

**Comment by atamariya** [comment]
You can make a custom build with #987 or use the windows installable here https://drive.google.com/open?id=0B6j7CzDPrJO5VUNtOTNKTm5ra00

**Comment by Sami32** [comment]
@gerroon Or you can use this UMS option: (never tried though, as my renderer doesn't support search)
http://www.universalmediaserver.com/forum/viewtopic.php?t=2061

**Comment by gerroon** [comment]
@Sami32 
thanks I will try those options.

**Comment by Sami32** [comment]
@gerroon Can this issue be closed ?
