### ISSUE TITLE
FR: Easier Sorting ?

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#1012]
Hi

I do not know if this can be easy for the clients or not but it would be awesome if there was an easier way of changing the sorting method without logging to the server app. 

As a user I do nnot even mind if I have to open the server:9001 or something along those lines to chnage the sorting. 

Is there a web panel to manage the server?

**Comment by Sami32** [comment]
@gerroon Sorry, but i'm not sure to understand you.
Do you mean that you would like have "file sorting", "file order" access without using UMS interface ?

You would like be able to do that from the web interface ?
Maybe because you are running in headless mode or using it from a smartphone?

**Comment by gerroon** [comment]
@Sami32 

At the moment the sorting is set through the UI. I was asking more about a way to do this in a more flexible way, like doing it through the web interface. Because the user might not be able to open the UI at all times on the otherhand the web ui is more accessible. For instance I access the web ui over ssh.


thanks

**Comment by Sami32** [comment]
@gerroon Have a look [here](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Web-interface) and tell me if it's satisfy your need.

Making this setting available from the client would be possible, but would need to be implemented in "Video Settings" option.
That's said, i don't get the point of changing the sorting each time ?

**Comment by Nadahar** [comment]
@gerroon I think what you want is to use the "cache" or "media library" depending on which language you use for UMS when browsing instead of browsing per folder structure. When using cache/media library you can choose between different sortings every time you browse as they are different "folders".

**Comment by gerroon** [comment]
@Sami32 
Well sometimes it is easier to find videos by date another times by name etc.

**Comment by Sami32** [comment]
@gerroon Oh i see...so, having it in the "Server Settings" would have been more handy to you.
I never tried it, but perhaps this nice fork from @taconaut  is able to do what you are searching to do:
http://universalmediaserver-ci.hopto.org:9999/job/ums-mlx%20trunk/ws/packaging/target/

**Comment by Nadahar** [comment]
@gerroon @Sami32 To repeat myself - this can be acieved using the media library for browsing.

**Comment by Sami32** [comment]
@gerroon Hoping that you found what you was searching for.
Now that understand what @Nadahar was talking about, i guess it feed your needs ?

If not, you can get again more searches possibilities:
In the case you use only the web interface from you computer perhaps using "**Server side search in web interface**" parameters will be better (see the UMS wiki link i given before).

If you want do that from some remote devices, better to use the @atamariya alpha work.
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/981#issuecomment-246201849
As i did worked on a better sorting support over DLNA.

**P.S.** Feel free to reopen this issue if necessary
