### ISSUE TITLE
Web interface button

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1020]
@UniversalMediaServer/developers What do you guys think about adding a button next to "Restart" and "Quit" that launches the web interface?

**Comment by Nadahar** [comment]
I've been thinking thatvthere should be a link to the web interface (with correct IP and port) in the GUI somewhere for a long time. I'm not sure about making it look like a "normal button" though, it might be confusing to the users as it doesn't actually DO anything within UMS. It might just be me though..

**Comment by squadjot** [comment]
Hope it's ok to comment, I think it would be great to make better use of the top nav, maybe also add update button?
http://imgur.com/a/Hg4RZ

**Comment by Sami32** [comment]
@squadjot Or you can set `auto_update =true` in your _UMS.conf_ file ;-)

**Comment by valib** [comment]
@Sami32, @squadjot auto update is already set to true by default.

**Comment by Sami32** [comment]
@valib No, it is not ;-)
And it's good as it is.
```
# Check for updates
# -----------------
# Default: false.
auto_update =

```
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/UMS.conf#L103-L106
```
public boolean isAutoUpdate() {
		return Build.isUpdatable() && getBoolean(KEY_AUTO_UPDATE, false);
	}
```
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/86502e6a72005cf18055f8eb118f85d2d833a004/src/main/java/net/pms/configuration/PmsConfiguration.java#L2999-L3001

**Comment by squadjot** [comment]
I know the update functionality is there. My suggestion for an update button was merely a UI/UX enhancement.

**Comment by Nadahar** [comment]
I understood from the start that @squadjot meant to add a button like he had drawn in. I don't know if it's needed though, why have a button for something that can be done automatically? I do agree that the space on the top probably could be used better though.

**Comment by valib** [comment]
@squadjot why to put the update button there when is already at the General configuration tab?

**Comment by Sami32** [comment]
I was not fan of, but i saw some user asking or searching to access the web interface so maybe...
Right click on the icon in the TaskBar is perhaps not too obvious to every one.

**Comment by Nadahar** [comment]
This is running out in the sand it seems, so here is my stance once again: I definitly think the GUI should have something one can click to open the web interface (with the correct address and port) - I'm convinced that many don't even know it's there. The only thing I'm unsure of is where to put it/how it should look.

**Comment by Sami32** [comment]
And what about a button for "Report" in case of issues for an easy reporting way by users ?

**Comment by SubJunk** [comment]
I've added this button in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1270
It's a simple change in terms of code so I'll merge it if there aren't any objections in a while
