### ISSUE TITLE
Log encoding issue ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1032]
MB (StatusTab.12) is displayed in the log as `ÐœÐ‘`.
> INFO  2016-09-11 19:00:19.964 [main] OS: Mac OS X 64-bit 10.11.6
> INFO  2016-09-11 19:00:19.964 [main] Encoding: UTF-8
> INFO  2016-09-11 19:00:19.964 [main] Memory: 683 **ÐœÐ‘**
> INFO  2016-09-11 19:00:19.971 [main] Language: Russian

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/86502e6a72005cf18055f8eb118f85d2d833a004/src/main/resources/i18n/messages_ru.properties#L454-L455

**EDIT:** It's remind me my first post on the forum about log encoding issue with french accents. Maybe the codepage is not correctly handled ?
> TRACE 2016-09-11 19:00:23.925 [mplayer-0] Successfully initialized buffer to **52Â 428Â 800** bytes.
...
TRACE 2016-09-11 19:00:24.128 [main] Adding new child "Ð’ÑÐµ Ñ‚Ñ€ÐµÐºÐ¸ Ð°ÑƒÐ´Ð¸Ð¾" with class "net.pms.dlna.virtual.MediaLibraryFolder"

**Comment by Nadahar** [comment]
@Sami32 That's very strange given: https://crowdin.com/translate/universalmediaserver/1/enus-ru#q=statustab.12

**Comment by Nadahar** [comment]
@Sami32 It's more likely that whatever software you use to read the log file doesn't support Unicode. The log file is supposed to be UTF-8 AFAICR, but if you open it in a non-unicode capable software like ```Notepad.exe``` or similar it will be interpreted like a ANSI document.

Unless you are sure that your current editor supports UTF-8, try [Notepad++](https://notepad-plus-plus.org/). It is my favorite editor in general, handles syntax highlighting for a lot of programming languages, different encodings and a lot of other goodies, AND it is lightweight and can run on your computer. Try reading the same logfile and report the result back.

**Comment by Sami32** [comment]
@Nadahar Thanks, you was right, Word Pad did not displayed correctly.

And for one time we share something, Notepad++ is very usefull and light !
Since most often the users interface have european language, i opened directly from inside the ZIP without issue. So i just changed his default viewer.
