### ISSUE TITLE
"Select renderers" work only the first time ==> Exception in thread "AWT-EventQueue-0"

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1045]
After using "**Select renderers**" a first time, in _General configuration_ tab, the following tries only throw error in the log: (i'm using 6.5.0 but i get same issue with 6.5.1 version)

> 22:11:50 INFO  Exception in thread "AWT-EventQueue-0" org.apache.commons.configuration.ConversionException: 'selected_renderers' doesn't map to a String object
> 22:11:50 INFO  	at org.apache.commons.configuration.AbstractConfiguration.getString(AbstractConfiguration.java:1050)
> 22:11:50 INFO  	at org.apache.commons.configuration.AbstractConfiguration.getString(AbstractConfiguration.java:1021)
> 22:11:50 INFO  	at net.pms.configuration.ConfigurationReader.getNonBlankConfigurationString(ConfigurationReader.java:250)
> 22:11:50 INFO  	at net.pms.configuration.ConfigurationReader.getString(ConfigurationReader.java:202)
> 22:11:50 INFO  	at net.pms.configuration.ConfigurationReader.getStringList(ConfigurationReader.java:221)
> 22:11:50 INFO  	at net.pms.configuration.RendererConfiguration.getStringList(RendererConfiguration.java:322)
> 22:11:50 INFO  	at net.pms.configuration.PmsConfiguration.getSelectedRenderers(PmsConfiguration.java:1684)
> 22:11:50 INFO  	at net.pms.newgui.SelectRenderers.showDialog(SelectRenderers.java:110)
> 22:11:50 INFO  	at net.pms.newgui.GeneralTab$21.actionPerformed(GeneralTab.java:462)
> 22:11:50 INFO  	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
> 22:11:50 INFO  	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
> 22:11:50 INFO  	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
> 22:11:50 INFO  	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
> 22:11:50 INFO  	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
> 22:11:50 INFO  	at java.awt.Component.processMouseEvent(Unknown Source)
> 22:11:50 INFO  	at javax.swing.JComponent.processMouseEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.Component.processEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.Container.processEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.Component.dispatchEventImpl(Unknown Source)
> 22:11:50 INFO  	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 22:11:50 INFO  	at java.awt.Component.dispatchEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 22:11:50 INFO  	at java.awt.Window.dispatchEventImpl(Unknown Source)
> 22:11:50 INFO  	at java.awt.Component.dispatchEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue.access$300(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue$3.run(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue$3.run(Unknown Source)
> 22:11:50 INFO  	at java.security.AccessController.doPrivileged(Native Method)
> 22:11:50 INFO  	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 22:11:50 INFO  	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue$4.run(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue$4.run(Unknown Source)
> 22:11:50 INFO  	at java.security.AccessController.doPrivileged(Native Method)
> 22:11:50 INFO  	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 22:11:50 INFO  	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by SubJunk** [comment]
Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1050

**Comment by Nadahar** [comment]
@Sami32 My bad, should be fixed in #1050.
