### ISSUE TITLE
Add 2 web renderers: Vivaldi and Chromium

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1054]
Chromium and Vivaldi (their recent versions support ChromeCast)

**Comment by atamariya** [comment]
All the web renderers should just work as they only use HTML and HTTP. Did you notice any problem?

**Comment by Sami32** [comment]
No problem, i just saw an user using it and though that perhaps it will be nice to have there own icon.
It's just a cosmetic thing...but i confess that i like open sourced Chromium

**Comment by Nadahar** [comment]
@Sami32 Firefox is open source and highly configurable :wink:  Honestly I don't know why people bother to use alternatives, you can install almost any extra functionality you'd want in Firefox via plugins.

**Comment by Sami32** [comment]
@Nadahar Yes, i love Firefox too, but i did use an old Opera 12 sometimes, so when i saw Vivaldi in this user log i get curious.
Opera was for long on the top edge of new browser ideas, concepts, Vivaldi is one of their new "branch", now based on Chromium, but i guess it's a matter of "interface" taste in that particular case.
Alternatives is freedom, is a fool who don't try imo ;-), as Firefox is moving slowly to Chrome store as well better to keep eyes open.
