### ISSUE TITLE
Add minimum_watched_play_time to the advanced GUI

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1058]
Since some users already asked for that kind of information why not put it in the advanced GUI, and not only in UMS.conf (btw we forget to write that it's non-GUI feature).
The "Fully played action" line have inhalf place for that imo.

**Comment by SubJunk** [comment]
Thanks for the suggestion but I don't think it belongs in the GUI :) If enough users are unhappy with the default value then let's change the default value. It's not something that other similar products let users customize AFAIK so we are already offering more customization than normal right now

**Comment by Sami32** [comment]
No problem for me, i just make sure it was not an omission, so i'll change the configuration file accordingly.
