### ISSUE TITLE
Mark folder as fully played via GUI

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1059]
It would be cool to be able to right-click on a folder entry in the Shared Folders section and click "mark contents as fully played"

**Comment by Nadahar** [comment]
A contextmenu shouldn't be that hard to add to the table... recursing down that path shouldn't be a big deal either I would think, so yeah, that sounds like something that could be worth the implementation time.

**Comment by SubJunk** [comment]
This has been added in 7.0.0
