### ISSUE TITLE
Add {internal subtitle} displaying information on the renderer

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1060]
External subtitle are mentioned on the renderer displaying but not the internal one.
In the case user don't know if his file have internal subtitle he will need to try to get them from his renderer or check in the #- Transcode -# folder.

I'm not sure why only external subtitles are displayed, perhaps because most people use them and more rarely external one ? In my case it's just the opposite way, but i guess that will be same for user viewing foreign TV series.

Just an idea though...

**Comment by SubJunk** [comment]
That could be a good idea to add it but only when the file will be automatically transcoded with that subtitle. If we are just streaming the file to the TV then I don't think we need to display that

**Comment by Sami32** [comment]
As an example: I only use files with internal subtitle for testing purpose, and put them in a seperate folder because i never remember which ones have internal subtitles as it's not displayed.

**Comment by Nadahar** [comment]
@Sami32 As @SubJunk sais it could be done when transcoding. When streaming the subtitles it would make no sense as the file can have any number of internal subtitles and the renderer will decide which one, if any, should be displayed. It does only make sense as long as UMS picks the subtitle to use.

**Comment by Sami32** [comment]
@Nadahar As i told, i was more seeing that as an advertising that internal subtitle(s) are available.
It was just an idea though...so sharing any other view is welcome ;-)

Whatever, i only use external subtitles and their are well advertised so...

**Comment by Nadahar** [comment]
@Sami32 As I see it, it is advertising which subtitles will be displayed if that entry is played, and since that is unknown for renderer controlled subtitles. As @SubJunk said, displaying it for internal subtitles when transcoding would make sense since it's known which subtitles will be displayed and that there will be subtitles.
