### ISSUE TITLE
Merge folder display settings into Shared folders panel

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1064]
I think we should move all of the settings like `Show the "#--TRANSCODE--#" folder`, etc. into the `Shared folders` section.

That means we need a new feature of that section which would be visibility, so that a user can hide a folder as well as remove it.

For these dynamic folders, we would disable the removing functionality but the visibility toggle would be available.

It would save a lot of space in the GUI and it makes sense.

**Comment by Nadahar** [comment]
@SubJunk I didn't understand 100% the hide/remove description, but I'm all for organizing this in a better way. If it saves GUI space as well that's bonus. Are you thinking og putting them in a table with checkboxes?

**Comment by SubJunk** [comment]
Yeah checkboxes could make the most sense, so there could be an extra checkbox column in the table called something like "visible"

**Comment by Nadahar** [comment]
"visible" wouldn't make any sense on "real" folders though, are you sure that will be logical? Wouldn't it make more sense to put these folders in a separate table with two columns "name/function/whatever" and "visible"?

I'm just afraid that combining the two would be confusing, "monitor" wouldn't make any sense for the "special folders" and "visible" wouldn't make any sense for the "normal" ones. There's no way to give one columns two "roles" in a table, so you would have to create one column for each, meaning that 50% of the checkboxes are always irrelevant for each line.

**Comment by SubJunk** [comment]
We could make it so that you can toggle visibility for real folders too but yes the monitor one wouldn't make sense for the fake folders. I think it's okay to have the "monitor" checkboxes disabled for fake folders in that case

**Comment by Nadahar** [comment]
@SubJunk Visibility toggle for real folders might not be a bad idea, it would mean you could include things that only showed up in the media library and made no sense traversing by folder.

**Comment by SubJunk** [comment]
This would be a good improvement to our interface. Might work on it soon

**Comment by SubJunk** [comment]
We have this now
