### ISSUE TITLE
Library Scanner issues give incorrect datas in the Database

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1074]
- ADTS container is not correctly handled by MediaInfo, meaning that _bitrate_ and _duration_ are null.
  (FFmpeg is able to handle it more correctly)
~~- Some MIME-types are parsed based on codecs and not on containers types as it should by default.
  (For example a OGG file having a FLAC codec will be parsed with a Mime-type _audio/x-flac_)~~

Examples:

> TRACE 2016-10-30 16:32:44.718 [Library Scanner] Parsing results for file "nocturne.aac": **container: adts**, **bitrate: 0**, size: 480002, audio tracks: 1, video codec: und, **duration: 00:00:00.00**, width: 0, height: 0, frame rate: null, mime type: audio/x-m4a Audio track id: 0, lang: und, audio codec: AAC, sample frequency:44100, number of channels: 2, bits per sample: 16
> 
~~TRACE 2016-10-30 16:32:44.812 [Library Scanner] Parsing results for file "old_flac_in_ogg_flac_1_0_4.ogg": **container: ogg**, bitrate: 897704, size: 7621280, audio tracks: 1, video codec: und, duration: 00:01:07.00, width: 0, height: 0, frame rate: null, **mime type: audio/x-flac**  Audio track id: 0, lang: und, **audio codec: flac**, sample frequency:44100, number of channels: 2, bits per sample: 16~~

~~TRACE 2016-10-30 15:54:48.093 [pool-4-thread-25] Parsing results for file "test5_eAACPlus.3gp2": container: adts, bitrate: 0, size: 1812862, audio tracks: 1, video codec: und, duration: 00:00:00.00, width: 0, height: 0, frame rate: null, mime type: audio/x-m4a Audio track id: 0, lang: und, audio codec: AAC, sample frequency:16000, number of channels: 1, bits per sample: 16~~

**Comment by Nadahar** [comment]
@Sami32 The container, video and audio codec parsing is a terrible mess, I'm sure there are loads of bugs to find there if you just throw some non-typical files at it.

This parsing is done in [```LibMediaInfoParser.getFormat()```](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/f5b6982e12919a51aae97f672582cfb62ecbe8d3/src/main/java/net/pms/dlna/LibMediaInfoParser.java#L410). In addition to being coded "unsafely" in that every combination isn't taken care of and the outcome can be somewhat random if it's not fed exactly what the author had in mind, it's called multiple times with different source fields on the same object. I see it as a wonder that it actually gets most things right.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/f42b0925024bcf20b93abc017a631e74ff470ee1/src/main/java/net/pms/dlna/DLNAMediaInfo.java

**Comment by Nadahar** [comment]
@Sami32 What does the link mean?

**Comment by Sami32** [comment]
That the issue is there.

**Comment by Nadahar** [comment]
@Sami32 I don't know how you think that anybody is going to understand that. Are we supposed to read through DLNAMediaInfo to "find the error"? The same with the mime types link, such a link is meaningless to me as I don't know what to look for.

If you explain what you think is the problem and then provide links to back it up, it's much easier for anybody to understand.

**Comment by atamariya** [comment]
When @Sami32 is done testing, UMS would truly be UNIVERSAL supporting every media type under the sun!! On a serious note, he is helping bring out some major issues in UMS code.

**Comment by Sami32** [comment]
@atamariya :stuck_out_tongue_winking_eye:  It's the newbie power, as i need to poke at everything for try understand something ;-)

**Comment by SubJunk** [comment]
I think this has been fixed, please reopen if not
