### ISSUE TITLE
Not working thumbnails scaling

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#1082]
There is the dead code in the https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/RequestV2.java#L321 and https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/Request.java#L321 because it always returs the original input stream. That is because the https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/util/UMSUtils.java#L179 is always returning the original input stream when the getThumbSize() is deprecated and not used.

**Comment by Nadahar** [comment]
#1061 changes this completely, so if it is merged this won't be an issue anymore.
