### ISSUE TITLE
Adding a "TranscodeImage" parameter in  configuration file

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1084]
As some users could have the choice to keep the transparency (alpha channel) of their images while transcoding. Meaning that they could have the **choice of the image transcoding format**:
PNG, JP2, WEBP...

**Comment by Nadahar** [comment]
#1061 offers PNG first for images that have transparency. Ultimately, it's up to the renderer which format it picks though, but I would assume that most transparancy-capable renderers would pick the PNG in those cases.

**Comment by Sami32** [comment]
The point was why should transcoding occur when the renderer already support natively WEBP format ?
