### ISSUE TITLE
Web interface settings wheel button position issue

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1085]
While browsing images, the "**Settings**" wheel button are incorrectly positionned, making the wheel hardly visible, and they "blink" when we point on them.

![Settings_wheel_position](https://cloud.githubusercontent.com/assets/18471069/20032241/e3015102-a37d-11e6-8961-fffc37cc6e32.jpg "Settings wheel position")
![capture_11052016_143025](https://cloud.githubusercontent.com/assets/18471069/20032244/f5ced03e-a37d-11e6-8ae9-b6207fdb26f7.jpg)

**EDIT**: Desktop full screen size of 1024x768. That the web interface is used in full or reduced size didn't affect it.

**Comment by SubJunk** [comment]
This has been fixed
