### ISSUE TITLE
Last played being record incorrectly

### ISSUE THREAD

**Issue by Lybster** [UniversalMediaServer/UniversalMediaServer#1104]
This may be as designed but it feels like a bug to me.

UMS 6.5.1
Panasonic TX40CX680B Firefox OS

Open UMS on the TV, move down a list opening ONE film. Recently played shows every film on the list that was cursored over.

The files are on a 3TB USB drive on the server organised into folders. The structure is

H:\
H:\A
...
...
H:\J
H:\Jam & Jerusalem
H:\Jam & Jerusalem\01-01...
H:\Jam & Jerusalem\01-02 ...
...
...
H:\Jam & Jerusalem \03-03

Going down to H:\Jam & Jerusalem and then simply moving down the list causes each film traversed to be added to recently played. 

I've added the logs and I hope that's clear and you can understand it.

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/613430/ums_dbg.zip)

**Comment by SubJunk** [comment]
@Lybster I think what is happening there is that your TV is probably doing a preview of each video, but to do the preview it is actually just playing the video. There is no way we can know whether something is just a preview or really playing it, but you can probably disable the preview setting on your TV to fix this.
