### ISSUE TITLE
UMS fails to render png and some jpg files.

### ISSUE THREAD

**Issue by lobo85** [UniversalMediaServer/UniversalMediaServer#1106]
My Jriver media center can  display these files as it has a transcoding option for images. Perhaps a similar feature would help solve image rendering  problems for pictures in the future. Here are some example files.
![deathstroke 2014- 006-003](https://cloud.githubusercontent.com/assets/389820/20786641/0ab48718-b75c-11e6-8196-32aa5bdc896d.jpg)
![deathstroke 2014- 006-004](https://cloud.githubusercontent.com/assets/389820/20786642/0ab50b66-b75c-11e6-8e40-ef72401cd613.jpg)
![deathstroke 2014- 006-005](https://cloud.githubusercontent.com/assets/389820/20786643/0aba466c-b75c-11e6-9c03-8537bd84b7cc.jpg)

**Comment by Nadahar** [comment]
Image transcoding could be somewhat useful (although I thought @valib had already done something in that direction?). What I don't understand is why you post "example" jpegs. What does Jriver convert these into, and what does your renderer accept if not jpeg? Or is it something special about these jpegs? It's hard to know what we can do with this little information...

[Debug files](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556) captured while you try to play back back some of the non-working images might also help.

**Comment by valib** [comment]
@Nadahar those samples have Chroma subsampling 4:4:4 instead of the usualy used 4:2:2 or 4:2:0. The  Chroma subsampling 4:4:4 is also not supported by my Panasonic TV so transcoding could help.

**Comment by Nadahar** [comment]
@valib Ok, I have no idea about the color encoding schemes. How do we figure out what the different renderers support...?

**Comment by valib** [comment]
@Nadahar that is possible only by users testing and feedback. And the Chroma subsampling value should be added to the renderer.conf like `Supported = f:jpg     	m:image/jpeg	chs:4:2:2|4:2:0`

**Comment by Nadahar** [comment]
@valib If you make that, make sure to make it possible to transcode RAW images into JPG as well. As it is now, you get thumbnails for RAW images but you can't view them. I think dcRaw can be used to "transcode" them as well.

**Comment by valib** [comment]
@Nadahar the dcRaw is used for them and it works on my TV but I see that it is not working on the web interface and Kodi. There must be a bug. This worked some time ago but there must be something changed meantime which stopped it working.

**Comment by Nadahar** [comment]
@valib Yes, it hasn't worked when I've tested it. When it comes to Kodi, there is something strange as I can't even get it to show simple JPEGs. Maybe there is some chroma or other issues there as well..? Can you get Kodi to show "normal" JPEGs?

**Comment by valib** [comment]
@Nadahar I will try. It could be related to the Kodi changes and the DIDL implementation the UMS sends to renderer.

**Comment by Sami32** [comment]
@lobo85 Could you provide some PNG images that don't display with UMS ?

**Comment by lobo85** [comment]
Sorry I wasn't clear on this but there are no png images that work with UMS that I know of when rendered to a ps4 or ps3 but heck here is one or two examples
![music_german_metal_band_blind_guardian_098468_](https://cloud.githubusercontent.com/assets/389820/21216646/c40af3cc-c25c-11e6-85f5-eff41585c26b.png)
![00](https://cloud.githubusercontent.com/assets/389820/21216808/b12feb30-c25d-11e6-8d0e-c8e2eefca127.png)

**Comment by lobo85** [comment]
here are two i found though png images have never rendered to ps3/ps4 for me at all

![00](https://cloud.githubusercontent.com/assets/389820/21216832/d55cc974-c25d-11e6-9363-f6c9d913ced3.png)
![music_german_metal_band_blind_guardian_098468_](https://cloud.githubusercontent.com/assets/389820/21216857/f8b9d434-c25d-11e6-93f4-f500b9d63914.png)

**Comment by Sami32** [comment]
@lobo85 About your JPEG images, 2 issues are underlying.
The first one is the tag field APP13 support by the library used, it will be fine now with the latest update in the next UMS version.
The second one is the progressive caracteristic of your images, it is supported by _TwelveMonkey_ but not implemented in UMS yet, so this kind of JPEG are send as it to the renderers but very few of them support it. `IsProgressive` should be able to detect it at parsing time and convert such JPEG to standard JPEG, also if JPEG is considered as supported by the renderers.
You can test your modified images : (The only difference between these 2 images is the chroma subsampling, just in case your renderer doesn't support 4:4:4)
![444](https://cloud.githubusercontent.com/assets/18471069/21292779/616eae3c-c510-11e6-8b2f-73b15840f3fb.jpg)
![420](https://cloud.githubusercontent.com/assets/18471069/21292780/617130a8-c510-11e6-8aa1-1ff599a92570.jpg)

About PNG images, i'm perplex, as PS4 officially support it, the latest firmware could be need though.
So, **do you mean that you was never able to get it work with UMS only, or with JRiver as well ?**

**Comment by lobo85** [comment]
The png files show up in folders and as thumbnails but when I actually select them the ps4 says its not supported i will send a trace log

**Comment by lobo85** [comment]
the zip wont upload so here is a link  it seems to happen on large png files 
[https://mega.nz/#!gJhBXCBZ!b2cC4e17UtzKl0VBv9GYnM3Y1peKxiTJ2ZID7TYSd9c](url)

**Comment by Nadahar** [comment]
The DLNA standard requires PNG images to be no bigger than 4096 x 4096, so that's probably why they won't render on the PS4. We'll probably just have to scale them down.

**Comment by lobo85** [comment]
Ok if that will work i will close this thread.

**Comment by Nadahar** [comment]
@lobo85 I'm working on a solution to this and other image and thumbnail related issues in #1061. You can follow the progress there or use [UMSBuilder](http://www.universalmediaserver.com/forum/viewtopic.php?f=25&t=1782&sid=0062de1071a9338dc8631cc2217fbc2b) to test it yourself. As of now, I haven't done the downscaling though, so #1061 probably won't do anything for you yet, but I'll soon have the downscaling in place there.

**Comment by Sami32** [comment]
More the fact that @nadahar already mentionned, UMS seem to have some issue with your PNG image sample:

> TRACE 2016-12-19 02:50:06.767 [New I/O worker #5] net.pms.dlna.DLNAMediaInfo Creating (temporary) thumbnail: Metallica - Hardwired...To Self-Destruct [00602557156454]-Box.png
> DEBUG 2016-12-19 02:50:11.046 [New I/O worker #5] net.pms.network.RequestHandlerV2 Caught exception: Java heap space
> TRACE 2016-12-19 02:50:11.048 [New I/O worker #5] net.pms.network.RequestHandlerV2 
> java.lang.OutOfMemoryError: **Java heap space**
> 	at java.awt.image.DataBufferByte.<init>(Unknown Source)
> 	at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
> 	at java.awt.image.BufferedImage.<init>(Unknown Source)

**Comment by Nadahar** [comment]
@Sami32 I think #1061 will solve that as well, we'll see.

**Comment by Sami32** [comment]
@Nadahar  I didn't doubt about that, as i know your perfectionism :smile:
