### ISSUE TITLE
Can't play -some- MKV with included subtitles (mostly WEB-DL versions)

### ISSUE THREAD

**Issue by popaz** [UniversalMediaServer/UniversalMediaServer#1107]
Hello Everyone. I started to experience not so far ago, that my UMS won't play WEB-DL mkv, with subtitles included in the file- in the most of the cases (my configuration is that it shows automatically english subs)
If I extracted the subtitle, create as an external one, it plays without problem. 
My log files can be found [HERE](https://drive.google.com/open?id=0B6RTtrGMUO32aFFmUGpNZFJqRnM) 
The keyword to look for in the log file is: Westworld.S01E09 (the file i tried to play)

thanks for all your hard work!

**Comment by Sami32** [comment]
@popaz Replace your file _UMS.conf_  in your profile folder by this one: (delete the _.txt_ extension)
[UMS.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/628275/UMS.conf.txt)

**Comment by popaz** [comment]
Thank you very much Sam it works! Mostly appreciated! Would you share with me what was the problem?

**Comment by Sami32** [comment]
@popaz You are welcome.
You was using MEncoder and it didn't handled correctly your subtitle, so i just set the default UMS values for use FFmpeg only instead, meaning that it's not defered to MEncoder anymore.

Not directly related to your issue, but i set the AC3 and LPCM audio transcoding settings to default values as well, as you Panasonic Viera renderer support it, and avoid your CPU to be used for nothing.

That's said, you could verify if your renderer support MKV container and modify your renderer configuration file accordingly, as you will save a lot of CPU power if you can avoid transcoding.

**Comment by SubJunk** [comment]
The Westworld WEB-DL files are incorrectly encoded, so they don't work natively on many renderers
