### ISSUE TITLE
DNG images are not handled

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1108]
DNG images are not handled, so no thumbnails are displayed...
I just tried with one sample though...

> DEBUG 2016-12-03 12:50:15.796 [Library Scanner] Starting "C:\Program Files\Universal Media Server\win32\dcrawMS.exe" -e -c "C:\Documents and Settings\Philippe\Mes documents\Téléchargements\IMAGES\L1004220.DNG"
> TRACE 2016-12-03 12:50:15.812 [Library Scanner] Successfully initialized buffer to 6,291,456 bytes.
> DEBUG 2016-12-03 12:50:15.812 [Library Scanner] Attaching thread: dcrawMS.exe-4
> TRACE 2016-12-03 12:50:15.828 [Library Scanner] EOF
> TRACE 2016-12-03 12:50:15.828 [Library Scanner] Ready to Stop: true
> TRACE 2016-12-03 12:50:15.875 [New I/O worker #2] Ignoring self-originating request from /192.168.1.28:5620
> TRACE 2016-12-03 12:50:15.875 [New I/O worker #1] Ignoring self-originating request from /192.168.1.28:5619
> DEBUG 2016-12-03 12:50:15.875 [Library Scanner] **Caught exception
> net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for source data.**
> 	at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source)
> 	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
> 	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
> 	at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
> 	at net.pms.formats.RAW.parse(RAW.java:138)
> 	at net.pms.dlna.RealFile.resolve(RealFile.java:193)
> 	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1504)
> 	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1303)
> 	at net.pms.dlna.RealFile.isValid(RealFile.java:66)
> 	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:572)
> 	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:532)
> 	at net.pms.dlna.MapFile.manageFile(MapFile.java:114)
> 	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:171)
> 	at net.pms.dlna.RootFolder.scan(RootFolder.java:260)
> 	at net.pms.dlna.RootFolder.scan(RootFolder.java:218)
> 	at net.pms.dlna.DLNAMediaDatabase.run(DLNAMediaDatabase.java:814)
> 	at java.lang.Thread.run(Unknown Source)

EDIT: https://trac.ffmpeg.org/ticket/4364

**Comment by Sami32** [comment]
```
if (media.getWidth() > 0) {
				byte[] image = RAWThumbnailer.getThumbnail(params, file.getFile().getAbsolutePath());
				media.setSize(image.length);
				// XXX why the image size is set to thumbnail size and the codecV and container is set to RAW when thumbnail is in the JPEG format
				media.setCodecV("raw");
				media.setContainer("raw");

				if (configuration.getImageThumbnailsEnabled()) {
					// Resize the thumbnail image using the Thumbnailator library
					ByteArrayOutputStream out = new ByteArrayOutputStream();
					Thumbnails.of(new ByteArrayInputStream(image))
								.size(320, 180)
								.outputFormat("JPEG")
								.outputQuality(1.0f)
								.toOutputStream(out);
					media.setThumb(out.toByteArray());
				}
}
```

In the case of DNG, for example, the container is TIFF and the codec is RAW, so that not include in the above code definition of "raw".

**Comment by Nadahar** [comment]
DCRaw doesn't support DNG. [This project] does and seems like it could be a good addition to DCRaw in the future, but unfortunately there's no release yet.

**Comment by Sami32** [comment]
http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=8062&p=26911&hilit=dcraw#p26911

**Comment by Sami32** [comment]
@Nadahar It's look like the latest version worked for you, right ?

If yes, i can close this issue, knowing that i need to make my own compile for my CPU.

**Comment by Nadahar** [comment]
@Sami32 Yes, there's no problem with DNG's for me in #1061.
