### ISSUE TITLE
Add frame interpolation for Linux

### ISSUE THREAD

**Issue by Genius1237** [UniversalMediaServer/UniversalMediaServer#1114]
The SVP binaries are available for linux now. 
https://www.svp-team.com/wiki/SVP:Linux

I believe the windows version uses parts of it for the interframe frame interpolation option. Is it possible to add this to the linux version as well.

**Comment by Sami32** [comment]
Since it doesn't be available on 32-bit system, it doesn't feed the "universal" goal.
If i'm wrong feel free to reopen it.

@SubJunk Why it is mentioned in the "About" tab ? I thought that we was using Avisynth for that purpose.

**Comment by Nadahar** [comment]
@Sami32 32-bit Linux is almost non-existant these days.

**Comment by Sami32** [comment]
@Nadahar Don't forget the last dinosaur :wink: 
That's said i remember the log of an user this last month.

I was not able to found where we are using it. But if you think that this issue need to be reopen, feel free to do it, i'll not mind.

**Comment by Nadahar** [comment]
@Sami32 I never understood what the point of frame interpolation is, you get improved FPS but the price is "blurryness" and artifacts. I always prefer the raw material over manipulated/enhanced, so I'm not going to advocate spending time on implementing it.

My point is only that I think the situation is slightly different for Linux than for Windows in that sense. Windows has a number of factors that prevent people from upgrading: Cost/license, drivers that only exist for a given Windows version, software that only work for a given Windows version and the fact that Microsoft keeps limiting your freedom of choice for every iteration. As long as you have 64-bit capable hardware, I can't see why anyone would run a 32-bit Linux.

**Comment by Sami32** [comment]
@Nadahar Same, except if they attempt to make "slowness" video effect to see actions that are too fast for human eyes, without investing in a hight FPS camera. Bad quality though.

FFmpeg is limited to 60 FPS playing/transcoding, so we use Avisynth for handling bigger FPS, as some trailers, movies have 120 FPS, AFAIK.

Honestly i don't know each OS specific situation, so your input is welcome.
But i can see why i would run a 32-bit Linux :tongue:

**Comment by SubJunk** [comment]
Our Windows implementation uses AviSynth within FFmpeg while it looks like to get it going on Linux it needs a Vapoursynth implementation, so there would need to be a bit of work on that.
It's a cool feature for people with older TVs that don't have frame interpolation built-in. All TVs from the last 5+ years have it so that number gets smaller every year.
I personally find watching only 24fps distracting, like watching a slideshow, so I always have interpolation going on my TV

**Comment by Nadahar** [comment]
Personally I consider 60 fps to be the limit for what I percieve as "fluid". Anything below is somewhat jerky, but I simply don't believe in trying to "enhance" a low quality source. I always turn off as much such things as possible on any device, manipulating the source only makes it worse imo. I think artifacts are much more annoying than the low FPS. I guess it depends on your display/TV as well. If it's very sharp and fast, I guess you will notice it more, while a somewhat more blurry and "slow" display probably will mask it somewhat. I don't really notice on a normal movie unless something moves very fast or I start thinking about it. Once you start to look for it, it can be quite bad, but I guess I have some "frame interpolation" in my head as well that smoothes it out when I don't think about it.

VaporSynth exists on "all our platforms" and is heavily inspired by AviSynth which has been abandoned for a while (the 2.6 source is actually using CVS!). Maybe all the current AviSynth functionality could be upgraded to use VaporSynth? AviSynth can't handle Unicode AFAICR, so anyone who wants to use non-latin1 subtitles are out of luck.

Off topic: [Naming gone crazy](http://www.vapoursynth.com/about/#comment-13089).
