### ISSUE TITLE
add support for videotoolbox encoding on mac

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1118]
To reduce CPU burdens, I used
MaxVideoBitrateMbps = 0
CustomFFmpegOptions = -report -c:v h264_videotoolbox -profile high -preset none -b 15000k
CBRVideoBitrate =15000000
on render conf file. But it doesn't work.
Though I tried  -allow_sw 1 but it doesn't work. -crf option may conflict?

log
DEBUG Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (/var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
DEBUG Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (/var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
TRACE Successfully initialized buffer to 52,428,800 bytes.
DEBUG [h264_videotoolbox @ 0x7fd044806400] Error: cannot create compression session: -12915
DEBUG Attaching thread: ffmpeg-2
DEBUG [h264_videotoolbox @ 0x7fd044806400] Try -allow_sw 1. The hardware encoder may be busy, or not supported.

Full log
TRACE HTTP: get/45/x.mp4_transcoded_to.ts / 0-0
TRACE Asked stream chunk : TimeRange [start=0.0, end=null] of x.mp4 and player FFmpeg
TRACE Setting lastStartPosition from time-seeking: 0.0
INFO: container: mp4, bitrate: 575274, size: 6483631, video tracks: 1, audio tracks: 1, video codec: h264, duration: 00:01:30.00, width: 422, height: 240, frame rate: 30.000, thumb size: 6064, mime type: video/mp4
	Audio track id: 0, lang: und, audio codec: AAC, sample frequency:44100, number of channels: 2, bits per sample: 16
DEBUG Reading TranscodeFastStart: true (default: false)
TRACE Searching for a match for: und with jpn and off
TRACE Searching for a match for: und with * and jpn
TRACE Searching for a match for: und with * and eng
TRACE Searching for a match for: und with * and und
TRACE Looking for a subtitle track with lang: jpn
TRACE Looking for a subtitle track with lang: eng
TRACE Looking for a subtitle track with lang: fre
TRACE Looking for a subtitle track with lang: ger
TRACE Looking for a subtitle track with lang: und
DEBUG Reading maximum_bitrate: "0" (default: "90")
TRACE Using the video bitrate limit from the program settings (1000)
TRACE Adjusting the video bitrate limit to the H.264 Level 4.1-safe value of 31250
DEBUG Reading CustomFFmpegOptions: "-report -c:v h264_videotoolbox -profile high -preset none -b 15000k" (default: "")
DEBUG Starting mkfifo -m 777 /var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032
TRACE Setting FONTCONFIG_PATH to "/Applications/Universal Media Server.app/Contents/Resources/fonts"
DEBUG Unix process ID (mkfifo): 1322
INFO -i "/Users/x/dlna/x.mp4" -bufsize 31250k -maxrate 31250k -crf 16 -ab 320k -ar 48000 -c:a aac -level 31 -pix_fmt yuv420p -f mpegts -report -c:v h264_videotoolbox -profile high -preset none -b 15000k /var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032
TRACE Setting FONTCONFIG_PATH to "/Applications/Universal Media Server.app/Contents/Resources/fonts"
DEBUG Reading pipe: /var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032
TRACE Opening file /var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032 for reading...
DEBUG ffmpeg started on 2016-12-28 at 13:40:41
DEBUG Report written to "ffmpeg-20161228-134041.log"
DEBUG ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
DEBUG   built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
DEBUG   configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
DEBUG   libavutil      55. 24.100 / 55. 24.100
DEBUG   libavcodec     57. 44.100 / 57. 44.100
DEBUG   libavformat    57. 37.101 / 57. 37.101
DEBUG   libavdevice    57.  0.101 / 57.  0.101
DEBUG   libavfilter     6. 46.100 /  6. 46.100
DEBUG   libswscale      4.  1.100 /  4.  1.100
DEBUG   libswresample   2.  0.101 /  2.  0.101
DEBUG   libpostproc    54.  0.100 / 54.  0.100
DEBUG Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/x/dlna/x.mp4':
DEBUG   Metadata:
DEBUG     major_brand     : isom
DEBUG     minor_version   : 512
DEBUG     compatible_brands: isomiso2avc1mp41
DEBUG     encoder         : Lavf56.40.101
DEBUG     comment         : FlixEngine_8.1.0.2
DEBUG   Duration: 00:01:30.16, start: 0.000000, bitrate: 575 kb/s
DEBUG     Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 422x240 [SAR 1:1 DAR 211:120], 513 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
DEBUG     Metadata:
DEBUG       handler_name    : VideoHandler
DEBUG     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 56 kb/s (default)
DEBUG     Metadata:
DEBUG       handler_name    : SoundHandler
DEBUG Please use -profile:a or -profile:v, -profile is ambiguous
DEBUG Please use -b:a or -b:v, -b is ambiguous
DEBUG Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (/var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
DEBUG Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (/var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
TRACE Successfully initialized buffer to 52,428,800 bytes.
DEBUG [h264_videotoolbox @ 0x7fd044806400] Error: cannot create compression session: -12915
DEBUG Attaching thread: ffmpeg-2
DEBUG [h264_videotoolbox @ 0x7fd044806400] Try -allow_sw 1. The hardware encoder may be busy, or not supported.
DEBUG Output #0, mpegts, to '/var/folders/jx/3pqjsj6x5vb5_wnywhxcm9_40000gn/T/UMS-x/ffmpegvideo_58_1482900041032':
DEBUG   Metadata:
DEBUG     major_brand     : isom
DEBUG     minor_version   : 512
DEBUG     compatible_brands: isomiso2avc1mp41
DEBUG     encoder         : Lavf56.40.101
DEBUG     comment         : FlixEngine_8.1.0.2
TRACE buffered: 0 bytes / inputs: 0
DEBUG     Stream #0:0(und): Unknown: none, SAR 1:1 DAR 0:0 (default)
DEBUG Unix process ID ("/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg"): 1323
DEBUG     Metadata:
DEBUG       handler_name    : VideoHandler
DEBUG       encoder         : Lavc57.44.100 h264_videotoolbox
DEBUG     Stream #0:1(und): Unknown: none (default)
DEBUG     Metadata:
DEBUG       handler_name    : SoundHandler
DEBUG       encoder         : Lavc57.44.100 aac
DEBUG Stream mapping:
DEBUG   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_videotoolbox))
DEBUG   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
DEBUG Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
TRACE EOF
INFO  Process "/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg" has a return code of 1! Maybe an error occurred... check the log file
DEBUG Stopping Unix process 1322: mkfifo-3
TRACE Killing the Unix process: 1322

**Comment by Nadahar** [comment]
@onon765trb What is "videotoolbox encoding"? We're limited to generally supported codecs readable either by renderers or a transcoding engine like FFmpeg.

**Comment by onon765trb** [comment]
videotoolbox encoding is h264 hardware one on Mac. It is supported by ffmpeg.
And sorry. I can transcode with the above option. I don' know why.

**Comment by Sami32** [comment]
@onon765trb Did you make it work with FFmpeg ? (without using UMS)
This has nothing to do with UMS, AFAIU.

Your command line is incorrect, check your `profile`, so i'll be surprise if you can get it work.
More the fact that you will need an FFmpeg compiled with the correct library ! your is missing the `--enable-vtenc` and maybe the `--non-free` as well ;-)
