### ISSUE TITLE
add support auto crop

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1119]
To crop a movie automatically, I always execute
`cropsize=$( ffmpeg -ss 600 -i input -f null -t 600 -an -vf cropdetect  /dev/null 2>&1 | grep -o crop=.* | sort -b | uniq -c | sort -b | tail -n1 | grep -o crop=.* )`
`ffplay input -vf ${cropsize}`
But UMS don't support shellscriot.
I request suppott for auto crop on UMS.

**Comment by Sami32** [comment]
@onon765trb Why not use the already UMS option ?
FFmpeg customs options (or MEncoder ones)

If you like scripts, Avisynth will give you much more possibilities.

**Comment by Sami32** [comment]
@onon765trb Feel free to reopen if necessary.
