### ISSUE TITLE
not sure where to put this, error

### ISSUE THREAD

**Issue by Outlaw461** [UniversalMediaServer/UniversalMediaServer#1121]
When I turn on the computer, a message pops up on the screen that states: An update is available, but you don't have permission to: then the rest of it is not readable.  Also most of the time I can not delete this box other than to use Task Manager.  I own this computer, its my home personal.  Any help would be appreciated... thanks

**Comment by Nadahar** [comment]
Is the message from UMS? What language do you use? I take it that you still have [UAC](http://www.howtogeek.com/howto/windows-vista/disable-user-account-control-uac-the-easy-way-on-windows-vista/) still enabled - which means that UMS won't have administrator permissions. What is actually needed is that the user you login to Windows with has write permission to UMS' program folder without elevation.

**Comment by Sami32** [comment]
@Outlaw461 Did that solved your issue ?

If not, you can always post a screen capture here.
