### ISSUE TITLE
[false][7.0.0-a1] lost all my watched eps

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1124]
not true just needed to restart again xD loaded the wrong profile it was my old anime profile and not the newer one

**Comment by Sami32** [comment]
@Goten87 As told [there](http://www.universalmediaserver.com/forum/viewtopic.php?f=8&t=9077):

> This release adds new features to dynamically sort your media, most notably there are new "TV Shows" and "Movies" folders that are populated automatically with content from your shared folders.
> 
> Your feedback on this pre-release will be valuable, so let us know how it is working for you!
> 
> Note: This is an alpha version, which means the feature list is incomplete and may be unstable. Use at your own risk.
> Note: It is recommended you take a backup of your profile directory before installing this, as the changes to the fully played data are not reversible. The location of your profile directory are near the top of the "Logs" tab in the program.

Many changes was done in the database, so backup should a safe way to avoid bad surprise ;-)

Can this issue be closed ?

**Comment by SubJunk** [comment]
@Goten87 glad you didn't lose the eps after all :)
