### ISSUE TITLE
Wipe of played alrdy database

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1126]
i have tested this out a couple of times now with a copy of my anime profile
when i start it up with 7.x it will wipe the played alrdy overlay

also i found out its not keeping the items anymore in the UMS.mon file in data folder

ps i am thinking the eps that you alrdy watched are stored in the profiles UMS.mon file or the 1 of the database files but at least in the profile it self

**Comment by Goten87** [comment]
i have now confirmed that when u update to 7.x it will wipe the eps watched list and i cant find it at all right now when i watch a ep compleet then it shows up but its not in the USM.mon file anymore

**Comment by SubJunk** [comment]
This has been fixed
