### ISSUE TITLE
subtitles_color log informations ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1149]
Reading a log i saw that:
**subtitles_color: -52276**   (=0xFFFFFFFFFFFF33CC)

So i'm wondering why a such value is displayed...and why not 16724940 (255,51,204 ==> 0xFF33CC)

Do the value displayed in the log will not be more natural in hexadecimal ?
Maybe `Integer.toHexString(value)` or `String.format("%x", Integer.parseInt(s))` could be used ?

**Comment by valib** [comment]
@Sami32 fixed
