### ISSUE TITLE
Something went wrong with the iTunes Library scan

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1168]
http://www.universalmediaserver.com/forum/download/file.php?id=3506

> DEBUG 2016-12-26 12:38:02.049 [main] Reading itunes_library_path: "d:\Shared\Audio" (default: "")
> INFO  2016-12-26 12:38:02.064 [main] [Fatal Error] :1:1: Content is not allowed in prolog.
> ERROR 2016-12-26 12:38:02.080 [main] Something went wrong with the iTunes Library scan: 
> xmlwise.XmlParseException: org.xml.sax.SAXParseException; systemId: file:/d:/Shared/Audio/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
> 	at xmlwise.Xmlwise.loadDocument(Xmlwise.java:58)
> 	at xmlwise.Xmlwise.loadDocument(Xmlwise.java:33)
> 	at xmlwise.Xmlwise.loadXml(Xmlwise.java:175)
> 	at xmlwise.Plist.load(Plist.java:240)
> 	at xmlwise.Plist.load(Plist.java:266)
> 	at net.pms.dlna.RootFolder.getiTunesFolder(RootFolder.java:824)
> 	at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:174)
> 	at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:502)
> 	at net.pms.PMS.getRootFolder(PMS.java:151)
> 	at net.pms.PMS.init(PMS.java:774)
> 	at net.pms.PMS.createInstance(PMS.java:1099)
> 	at net.pms.PMS.main(PMS.java:1259)
> Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
> 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
> 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
> 	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
> 	at xmlwise.Xmlwise.loadDocument(Xmlwise.java:50)
> 	... 11 common frames omitted

**Comment by SubJunk** [comment]
I don't think this will get worked on, iTunes doesn't exist anymore
