### ISSUE TITLE
Unhandled exception while resolving ==> The Line 1: Illegal base64 character 20

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1169]
http://www.universalmediaserver.com/forum/download/file.php?id=3506

> DEBUG 2016-12-26 12:38:54.411 [Library Scanner] Scanning folder: Draw The Line
> TRACE 2016-12-26 12:38:54.411 [Library Scanner] Matched format MP3 to "D:\shared\Audio\ITunes Library\Aerosmith\Draw The Line\01-Draw The Line 1.mp3"
> WARN  2016-12-26 12:38:54.473 [Library Scanner] Unhandled exception while resolving 01-Draw The Line 1: Illegal base64 character 20
> DEBUG 2016-12-26 12:38:54.473 [Library Scanner] 
> java.lang.IllegalArgumentException: Illegal base64 character 20
> 	at java.util.Base64$Decoder.decode0(Unknown Source)
> 	at java.util.Base64$Decoder.decode(Unknown Source)
> 	at net.pms.dlna.LibMediaInfoParser.parse(LibMediaInfoParser.java:88)

> TRACE 2016-12-26 12:39:03.802 [Library Scanner] Matched format MP3 to "D:\shared\Audio\ITunes Library\Jonas Brothers\It's About Time\Mandy Episode One 1.mp3"
> WARN  2016-12-26 12:39:03.833 [Library Scanner] Unhandled exception while resolving Mandy Episode One 1: Input byte array has incorrect ending byte at 147476
> DEBUG 2016-12-26 12:39:03.833 [Library Scanner] 
> java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 147476
> 	at java.util.Base64$Decoder.decode0(Unknown Source)
> 	at java.util.Base64$Decoder.decode(Unknown Source)
> 	at net.pms.dlna.LibMediaInfoParser.parse(LibMediaInfoParser.java:88)

**Comment by Nadahar** [comment]
@Sami32 A link to the actual form thread would be nice. Also, you can format your links so to you know what they are using [Markdown](https://guides.github.com/features/mastering-markdown/) which makes it much easier for us to read.

UMS expects MediaInfo to extract base64 encoded album art. This error indicates that what UMS got wasn't a base64 string, so to figure this out I'm afraid the source file is needed.

**Comment by Sami32** [comment]
@Nadahar I like more without Markdown in report, so i guess it's a matter of taste...

In fact, i met this issue 2 times in diffrent logs this week. Just wondering how.
BTW, it was not the subject of their issue report.
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9066

**Comment by Nadahar** [comment]
@Sami32 Markdown or not, the point is that you need to describe you links. I don't want to have to click them all the see what they are, and I bet that goes for other people as well.

As said above, I'm pretty sure that MediaInfo is giving UMS some non-base64 data that UMS think is embedded art. The only way to figure out exactly what is happening is to have one such file.
