### ISSUE TITLE
will not be streamed because the H.264 level is unknown

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1170]
@SubJunk I was referred to that issue:
http://www.universalmediaserver.com/forum/download/file.php?id=3626
http://www.universalmediaserver.com/forum/download/file.php?id=3546
http://www.universalmediaserver.com/forum/download/file.php?id=3519
And many other since 6.5.2 version. It seem that Samsung users are more affected, or they report more ?

> TRACE 2017-01-22 15:29:23.041 [New I/O worker #1] net.pms.dlna.DLNAResource File "Batman v Superman -  Dawn of Justice..mp4" will not be streamed because the **H.264 level is unknown**.

**Comment by SubJunk** [comment]
Cool, that gives the info I need and it does seem we have a bug here. I'm looking into it now. Thanks!

**Comment by SubJunk** [comment]
I got one of the files in those logs and it gave me the level correctly when we scanned it:

```
Parsing results for file "Chicago.PD.S04E10.HDTV.x264-KILLERS.mkv": container: mkv, bitrate: 808625, size: 256001892, video tracks: 1, audio tracks: 1, video codec: h264, duration: 00:42:12.00, width: 720, height: 404, frame rate: , mime type: video/x-matroska, matrix coefficients: BT.709, avc level: 3.1
	Audio track id: 0, lang: und, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16
```

when we played it:

```
Starting transcode/remux of Chicago.PD.S04E10.HDTV.x264-KILLERS.mkv with media info: container: mkv, bitrate: 808625, size: 256001892, video tracks: 1, audio tracks: 1, video codec: h264, duration: 00:42:12.00, width: 720, height: 404, frame rate: , thumb size: 23569, mime type: video/ogg, matrix coefficients: BT.709, avc level: 3.1
	Audio track id: 0, lang: und, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16
```

and then I restarted UMS and played it again to make sure it reads the level correctly from the database and it did:

```
Starting transcode/remux of Chicago.PD.S04E10.HDTV.x264-KILLERS.mkv with media info: container: mkv, bitrate: 808625, size: 256001892, video tracks: 1, audio tracks: 1, video codec: h264, duration: 00:42:12.00, width: 720, height: 404, frame rate: , thumb size: 23569, mime type: video/ogg, matrix coefficients: BT.709, avc level: 3.1
	Audio track id: 0, lang: und, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16
```

I'll have a think about what else could cause this issue.

**Comment by Sami32** [comment]
I allways suspected [this commit](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/e186d9782c90465ccc4d8bc68dfd24cc9319b746) but i could be wrong though.

I guess that i make some hidden code flaw appear ?

**Comment by SubJunk** [comment]
My notes so far:

It seems to happen on 64-bit and 32-bit installations so that's not a factor.
The MediaInfo level of one of the files that failed `Chicago.PD.S04E10.HDTV.x264-KILLERS.mkv` is `High@L3.1` which should and does get parsed normally for me.

**Comment by SubJunk** [comment]
The commit https://github.com/UniversalMediaServer/UniversalMediaServer/commit/86a261f725a5ee55066f0c2e95fa77e437f5d47e is what has caused the logic of transcoding unsupported and unknown levels, but not the bug of not knowing the level

**Comment by Sami32** [comment]
Some users get ride of this issue, simply by changing their renderers.

2017-01-28 23:12 GMT+01:00 SubJunk <notifications@github.com>:

**Comment by SubJunk** [comment]
Can you link a forum thread/s?

**Comment by Sami32** [comment]
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9153
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9096

**Comment by Sami32** [comment]
A new one:
http://www.universalmediaserver.com/forum/download/file.php?id=3678

**Comment by Sami32** [comment]
A new one:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9200&p=29737#p29737

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1242/files

**Comment by SubJunk** [comment]
This was done recently
