### ISSUE TITLE
Server name is not XML escaped

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1172]
i have gave my profile the server name Movies & Series and now its not showing up on my net work at all
when i rename it again to Movies and Series it works
can u please fix the & symbol in the Server name input

or do i need to do something special for it ?

**Comment by Nadahar** [comment]
This sounds like a bug - the server name string should probably be XML escaped. As a workaround you can try to substitute ```&amp;``` for ```&```. If that works, please report back as it also confirms the bug.

**Comment by Goten87** [comment]
yep the `&amp;` works like a charm
