### ISSUE TITLE
Support automtic audio setting by ffmpeg

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1178]
UniversalMediaServer force audio channel layouts and audio bit rate. Can't remove `-ac foo` and `-ab bar`
I think this is trasfer losses.
But ffmpeg automatically sets appreciate audio channel layouts and audio bit rates.
I request automtic audio setting by ffmpeg

For example,
/Applications/Universal\ Media\ Server_v8.app/Contents/Resources/osx/ffmpeg -i "Si 5.1ch autumn sample.mpeg" -vn -c:a aac test.ts
ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 44.100 / 57. 44.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mpeg, from 'Si 5.1ch autumn sample.mpeg':
  Duration: 00:03:15.10, start: 0.700000, bitrate: 1136 kb/s
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x80]: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
[mpegts @ 0x7fdba897cc00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x7fdba897cc00] frame size not set
Output #0, mpegts, to 'test.ts':
  Metadata:
    encoder         : Lavf57.37.101
    Stream #0:0: Audio: aac (LC), 48000 Hz, 5.1(side), fltp, 341 kb/s
    Metadata:
      encoder         : Lavc57.44.100 aac
Stream mapping:
  Stream #0:1 -> #0:0 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
size=    9256kB time=00:03:15.07 bitrate= 388.7kbits/s speed=16.7x    
video:0kB audio:8122kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 13.965205%
[aac @ 0x7fdba897d800] Qavg: 753.681

**Comment by Sami32** [comment]
I don't understand what do you mean by "I think this is trasfer losses".

If the file have 5.1 channel, playing with `-ac 6` or not, will not change anything in the listening result, AFAIK.
But, on other way, enforcing the channel and bitrate permit to restrict it to the users choices or engines limitations.

**Comment by onon765trb** [comment]
@Sami32 Thank you for your pointing out. For channel numbers, my mistaking.

The max bit rate of audio, `-ab 320k`, is probably mp3.
The max bit rate of aac is 288 kbit/s a channel when sampling_frequency is 48 kHz, as shown in 8.2.2.3 Maximum Bitrate of ISO/IEC 13818-7[http://read.pudn.com/downloads126/ebook/535161/13818-7.pdf](url)

The automatic bit rate setting of ffmpeg isn't beyond the above, as shown in the below logs. In most cases, stereo sounds is used. I think 128kb/s is enough and it doesn't burden network bandwidth.


logs
The source of 5.1 and 7.1 is [https://www2.iis.fraunhofer.de/AAC/multichannel.html](url)
"/Applications/Universal Media Server_v8.app/Contents/Resources/osx/ffmpeg" -y -i "/Users/x/dlna/test.mp4" -vn -ar 48000 -c:a aac result.ts
ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 44.100 / 57. 44.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/x/dlna/test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.61.100
  Duration: 00:00:15.08, start: 0.000000, bitrate: 4088 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 328x336 [SAR 10:11 DAR 205:231], 3951 kb/s, SAR 149:164 DAR 149:168, 29.97 fps, 29.97 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[mpegts @ 0x7fec72013200] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x7fec72013200] frame size not set
Output #0, mpegts, to 'result.ts':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.37.101
    Stream #0:0(und): Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.44.100 aac
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
size=      13kB time=00:00:15.04 bitrate=   7.0kbits/s speed=71.3x    
video:0kB audio:4kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 206.974579%
[aac @ 0x7fec72014400] Qavg: 65536.000

"/Applications/Universal Media Server_v8.app/Contents/Resources/osx/ffmpeg" -y -i "/Users/x/dlna/SBR_LFETest5_1-441-16b.wav" -ar 48000 -c:a aac result.ts
ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 44.100 / 57. 44.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, wav, from '/Users/x/dlna/SBR_LFETest5_1-441-16b.wav':
  Metadata:
    encoder         : Adobe Audition 4.0.0.1815 (XMPDocOpsTemporal:2008.11.05)
    date            : 2012-05-15
    creation_time   : 18:11:30
    time_reference  : 0
  Duration: 00:00:45.18, bitrate: 4239 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 5.1, s16, 4233 kb/s
[mpegts @ 0x7fc7c2014600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x7fc7c2014600] frame size not set
Output #0, mpegts, to 'result.ts':
  Metadata:
    time_reference  : 0
    date            : 2012-05-15
    encoder         : Lavf57.37.101
    Stream #0:0: Audio: aac (LC), 48000 Hz, 5.1, fltp, 341 kb/s
    Metadata:
      encoder         : Lavc57.44.100 aac
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
size=    2144kB time=00:00:45.18 bitrate= 388.7kbits/s speed=10.5x    
video:0kB audio:1886kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 13.696623%
[aac @ 0x7fc7c2006000] Qavg: 372.592

"/Applications/Universal Media Server_v8.app/Contents/Resources/osx/ffmpeg" -y -i "/Users/x/dlna/7.1auditionOutLeader v2.wav" -ar 48000 -c:a aac result.ts
ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 44.100 / 57. 44.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, wav, from '/Users/x/dlna/7.1auditionOutLeader v2.wav':
  Metadata:
    date            : 2013-01-17 21:21:45 UTC
    encoder         : CopyAudio
  Duration: 00:00:31.68, bitrate: 6146 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 7.1, s16, 6144 kb/s
[mpegts @ 0x7fe42d823a00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x7fe42d823a00] frame size not set
Output #0, mpegts, to 'result.ts':
  Metadata:
    date            : 2013-01-17 21:21:45 UTC
    encoder         : Lavf57.37.101
    Stream #0:0: Audio: aac (LC), 48000 Hz, 7.1, fltp, 469 kb/s
    Metadata:
      encoder         : Lavc57.44.100 aac
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
size=    2160kB time=00:00:31.68 bitrate= 558.5kbits/s speed=5.61x    
video:0kB audio:1902kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 13.569415%
[aac @ 0x7fe42d811c00] Qavg: 373.763

**Comment by Sami32** [comment]
@onon765trb For AAC you can also look at the ISO/IEC 14496-3.

The subject about MP3 transcoding bitrate was already discussed, and the result was that it will make only minor difference in the bandwith anyway, compared to HRA or video bandwidth, so **the quality was prefered**.

That's said don't forget that we need to follow the DLNA specifications (IEC 62481-2) as well.

Specific bitrate and channels can be specified in the renderer configuration file.
So i think it's good as it is, and that this issue can be closed.

**Comment by onon765trb** [comment]
@Sami32 Thank you for your explanation. 
Is what you say is AAC_ISO_320 of 8.6.2 AAC Audio Format: exception(1) and 8.6.4 AAC Audio Format: content(1) and AAC_ADTS_320 in 8.6.3AAC Audio Format: exception(2) in DLNA Networked Device Interoperability Guideline expanded: March 2006 Volume 2: Media Format Profiles [https://www.scribd.com/document/118566781/DLNA-Networked-Device-Interoperability-Guidelines-Media-Format-Profiles](url)?

AAC_ISO_320 and AAC_ADTS_320 aren't used in the table of 9.4MPEG-4 Part 10 (AVC) Profiling Guidelines.
I think adding automatic bit rare setting by ffmpeg is useful. 128k kb/s in 2 ch, 341 kb/s in 5.1 ch, 469 kb/s in 7.1 ch follow the DLNA specifications. 8.1 AC-3 Profiling Guidelines says 64Kbps - 640Kbps.

**Comment by Sami32** [comment]
@onon765trb IEC 62481-2:2013 have much more profiles as AAC_LTP_MULT7_ISO and many more, and the next one at the end of the year should be plenty of new ones :-)

UMS doesn't support more than 5.1 channels at that time, that was done for bandwidth reason, as 7.1 can need until 24.5 MB/s.

I do not agree that, that's make CPU use to win pinuts in the bandwidth IMO.
The UMS default should provide a maximum quality, based on general CPU and bandwidth use among the users.

Since it's difficult for me to understand you, as we are 2 not english native, i suspect that you're again speaking exclusively about TSmuxeR use only, an old and not maintened engine, lovely that's said,  that could be mostly replaced by FFmpeg as for now IMO.

Just curious, why are you using TSmuxeR in the first place ? As i don't remember seen any of your full trace log.

**Comment by onon765trb** [comment]
@Sami32 Thank you for explaining the policy of UMS. I have thought 128k kb/s of AAC in 2 ch is enough quality and it decreases bandwidth burdens. But I follow the policy of UMS for many users.

using TSmuxeR is one of my experimentation.
> not maintened engine
Oh. Thank you for telling. If not so, I would rested more experimentation.

**Comment by Sami32** [comment]
@onon765trb TSmuxeR is write in Assembler, AFAIK, and the developper stoppped to work on it many years ago.
We keep it, and sadly MEncoder as well, until FFmpeg can take the full relay whithout issue.
But that's doesn't mean that some improvements cannot be done, from UMS code side, for TSmuxeR, also if few users use it.
You can open a more general "TSmuxeR issues" and set inside what you think should be improved, avoidind many issues post that we need to guess that is was in fact related to TSmuxeR.

Thank you for taking the time to report/suggest.

**Comment by Nadahar** [comment]
@Sami32 TSmuxeR is written in C or C++ (don't remember). There's talk of releasing the source code and has been for a while, but nothing has happened this far so I wouldn't hold my breath.

**Comment by Sami32** [comment]
@Nadahar I get the source code and already posted it on the forum, as i already told you.
Assembler language as far as i saw.

**Comment by Nadahar** [comment]
@Sami32 Did you tell me that? I really can't believe that someone would write something like that in assembler - that's a lot of work for very little gain. Are you sure it's not something someone has "decompiled"? What's the link?

**Comment by Sami32** [comment]
@Nadahar I taken it from a people that take it directly from the developper, on the Doom9 site i think.
I told that was the code source.
So i found it strange myself, so i dissabled it ==> ELF !

**Comment by Nadahar** [comment]
@Sami32 Can you please link or give me a hint of how to find this. I've done some searches on Doom9 but nothing obvious popped up.

**Comment by Sami32** [comment]
@Nadahar http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=8352

**Comment by Nadahar** [comment]
@Sami32 That's not the source code, it's just a regular compiled version.

**Comment by Sami32** [comment]
@Nadahar So maybe i was mistaken, i'll search if i can find the thread again.

**Comment by Sami32** [comment]
@Nadahar Now that i'm readum Doom9 forum, i'm asking myself, why ?

Do FFmpeg already able to handle what TSmuxeR does ?

**Comment by Nadahar** [comment]
@Sami32 I've been wondering the same for a long time, but as you know I try not to get too involved in the world of video - there are so much "special cases" and other irregularities that I'd rather not know it all.

I have no idea what tsMuxeR brings to the table at all.... my guess is that at one stage, FFmpeg couldn't generate TS streams or something like that. Can't one just use "copy" with FFmpeg to make it mux whatever one want into a TS as well?

**Comment by Sami32** [comment]
@nadahar Now FFmpeg can do all the TSmuxeR job, AFAIK.

That's said it was not case some years ago, so i guess that it's one more old part that was left here, as _flac.exe_.
As far that i can remember, @subjunk keeped it only because _FFmpeg_ was not able to do remuxing correctly...
