### ISSUE TITLE
Support CustomFFmpegOptions in FFmpeg Audio

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1181]
I understand trascoding with tsmuxer also use the setting of FFmpeg Audio. I don't read the source of UMS, sorry.

`CustomFFmpegOptions=` isn't used other than FFmpeg Video transcoding. FFmpeg has many useful audio filters.
For example, soxr is the change of sampling rate, which doen't occur audio delay, inserting silence, squeeze, expand, dynaudnorm avoids a sudden loud sound, etc.

Thank for reading my issues and many comments.

**Comment by Nadahar** [comment]
I think this could be worth it if anyone is up for implementing it.

**Comment by onon765trb** [comment]
What build can I test?

**Comment by Sami32** [comment]
@onon765trb That one:
https://we.tl/VvlZOCoKLZ

**Comment by onon765trb** [comment]
Thank you.

**Comment by onon765trb** [comment]
It works well!

**Comment by SubJunk** [comment]
Done in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1323
