### ISSUE TITLE
not booting UMS 6.5.3 without xattr -rc 

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1182]
Can't boot UMS 6.5.3 on macOS 10.12.3, which is downloaded from https://www.fosshub.com/Universal-Media-Server.html.
I don't try JAVA7 edition.

To boot it,  have to execute `xattr -rc "/Applications/Universal Media Server.app"`.

About command  `xattr`.
https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/xattr.1.html

**Comment by Nadahar** [comment]
@onon765trb Sorry, you have to explain the ```xattr -rc``` better. I assume you mean start when you say "boot"? If it doesn't start, what is the error? Does it start with ```xattr -rc```?

**Comment by onon765trb** [comment]
@Nadahar Sorry not enough explanation. I had thought `xattr -rc` is in general.
As you say, "boot" means "start". In the first start of UMS 
![screen shot 2017-02-09 at 14 57 48](https://cloud.githubusercontent.com/assets/24803846/22771355/2e0cb73a-ee8e-11e6-9b11-b3e459fd8b3a.png)
is displayed. 

In such a case, `xattr -rc ` solves this problem.

From the above link,
The xattr command can be used to display, modify or remove the extended attributes of one or more files, including directories and symbolic links.
-c option (``clear''), causes all attributes (including their associated values), to be removed.
-r  If a file argument is a directory, act as if the entire contents of the directory recursively were also specified (so that every file in the directory tree is acted upon).

The extended attributes of UMS before executing `xattr -rc "/Applications/Universal Media Server.appxattr`
xattr /Application/Universal\ Media\ Server.app 
com.apple.quarantine

xattr -r /Application/Universal\ Media\ Server.app 
/Application/Universal Media Server.app/Contents/Info.plist: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Java/ums-6.5.3-jar-with-dependencies.jar: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Java: com.apple.quarantine
/Application/Universal Media Server.app/Contents/MacOS/JavaAppLauncher: com.apple.quarantine
/Application/Universal Media Server.app/Contents/MacOS: com.apple.quarantine
/Application/Universal Media Server.app/Contents/PkgInfo: com.apple.quarantine
/Application/Universal Media Server.app/Contents/PlugIns: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/CHANGELOG.txt: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/Application/s.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/avisynth.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/commandline.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/coreavc.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/css/style.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/general_configuration.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/autonegotiation.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/btn_donateCC_LG.gif: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/coreavc1.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/coreavc2.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/coreavc3.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/netzwerkverbindungen.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-eng-general.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-eng-general1.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-eng-status1.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-eng-status2.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-engines1.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-engines2.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/pms-searching.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/ps3-browsing.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/ps3-server.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/ps3screen.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/setupwin1.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/setupwin2.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/setupwin3.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/setupwin4.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/ssdp.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images/topology_ps3.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/images: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/index.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/installation.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/introduction.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/links.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/navigation_share.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/networking.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/plugins.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/transcoding.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation/videolan.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/documentation: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/DummyInput.ass: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/DummyInput.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/en.lproj/Localizable.strings: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/en.lproj: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/fonts/fonts.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/fonts/fonts.dtd: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/fonts: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/libmediainfo.dylib: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/LICENSE.txt: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/logback.headless.xml: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/logback.xml: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/logo.icns: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/MediaInfo-License.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/dcraw: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/ffmpeg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/flac: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/mencoder: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/mplayer: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/tsMuxeR: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx/tsMuxeR-new: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/osx: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/plugins/README.md: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/plugins/README.txt: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/plugins: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/README.txt: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/AnyCast.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Apple-iDevice-AirPlayer.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Apple-iDevice-VLC.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Apple-iDevice-VLC32bit.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Apple-iDevice.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Apple-TV-VLC.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/BlackBerry-PlayBook-KalemSoftMP.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/CambridgeAudio-AzurBD.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/DefaultRenderer.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/DirecTV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/DLink-DSM510.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Free-Freebox.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Freecom-MusicPal.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Google-Android-Chromecast.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Google-Android.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Hama-IR320.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Hisense-K680.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Kodi.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-BP.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-BP550.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-EG910V.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LA6200.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LA644V.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LB.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LM620.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LM660.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-LS5700.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-ST600.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-UB820V.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/LG-WebOS.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Logitech-Squeezebox.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Microsoft-WindowsMediaPlayer.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Microsoft-Xbox360.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Microsoft-XboxOne.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Miracast-M806.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Naim-Mu-So.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Netgear-NeoTV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Netgem-N7700.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Nokia-N900.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Onkyo-TXNR717.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/OPPO-BDP.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/OPPO-BDP83.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-DMPBDT.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-DMPBDT220.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-DMPBDT360.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-SCBTT.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-Viera.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraAS600E.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraAS650.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraCX680.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraCX700.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraE6.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraET60.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraGT50.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraS60.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraST60.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraTHPU30Z.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraTXL32V10E.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Panasonic-VieraVT60.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Philips-AureaAndNetTV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Philips-PFL.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Philips-Streamium.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Pioneer-Kuro.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/PopcornHour.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/README.txt: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Realtek.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Roku-Roku3-3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Roku-Roku3-5.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-BDC6800.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-BDH6500.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-C6600.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-CD.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-D6400.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-D7000.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-EH5300.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-EH6070.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-ES6100.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-ES6575.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-ES8000.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-ES8005.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-F5100.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-F5505.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-F5900.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-GalaxyS5.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-H4500.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-H6203.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-H6400.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-HTE3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-HTF4.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-HU7000.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-HU9000.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-J55xx.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-J6200.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-JU6400.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-Mobile.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-NotCD.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-PL51E490.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-SMTG7400.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Samsung-WiseLink.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sharp-Aquos.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Showtime3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Showtime4.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-Bluray.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-Bluray2013.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-Bravia4500.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-Bravia5500.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaBX305.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaEX.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaEX620.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaEX725.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaHX.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaHX75.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaNX70x.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaNX800.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaW.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaX.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-BraviaXBR.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-HomeTheatreSystem.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-PlayStation3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-PlayStation4.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-PlayStationVita.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-SMPN100.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-STR5800ES.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-Xperia.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Sony-XperiaZ3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Technisat-S1Plus.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Telefunken-TV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Telstra-Tbox.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Thomson-U3.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/VideoWeb-VideoWebTV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Vizio-SmartTV.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/VLC-for-desktop.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/WesternDigital-WDTVLive.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/XBMC.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Yamaha-RN500.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Yamaha-RXA1010.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Yamaha-RXV3900.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Yamaha-RXV500D.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers/Yamaha-RXV671.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/renderers: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/UMS.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/VirtualFolders.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/background-blank.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/background.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/browse.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/bump.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/bump.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/bump16-2.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/bump32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/add16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/bump16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/clear16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/close16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/fwd16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/mute16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/next16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/pause16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/play16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/prev16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/remove16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/rew16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/skin.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/stop16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin/vol16.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump/skin: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/bump: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/button-search.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/doc.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/download.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/err32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/favicon.ico: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/flow.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/flowplayer.min.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/functional.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/icon-log.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/icon-log.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/icon-log2.jpg: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/image.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/flowplayer.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/flowplayer@2x.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/play_white.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/play_white@x2.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/play_white_rtl.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/play_white_rtl@x2.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/white.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/white@x2.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/white_rtl.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img/white_rtl@x2.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/img: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/info24.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/info32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/inputbackground-search.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/jquery.min.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/jquery.ums.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/js.cookie-2.1.0.min.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/logo.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/menu-background-content.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/menu-left-content.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/ok32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/pad32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/play.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/reset.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/search32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/settings32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/start.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/inflate.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/log.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/logviewer.html: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/sh.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/sh.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/shCore.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util/zip.js: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/util: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/view-dynamic.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/view-grid.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/view-info.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/view-padcolor.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/warn32.png: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/web-narrow.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/web-wide.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web/web.css: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/web: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources/WEB.conf: com.apple.quarantine
/Application/Universal Media Server.app/Contents/Resources: com.apple.quarantine
/Application/Universal Media Server.app/Contents: com.apple.quarantine
/Application/Universal Media Server.app: com.apple.quarantine

**Comment by Sami32** [comment]
@onon765trb The forum is full of that kind of Apple issue. Enjoy ;)

Apple protection for not be an "authorized" Apple listed application.
They just ignore/avoid the protection it and the application worked fine.

**Comment by Nadahar** [comment]
@onon765trb Yes, this looks like some greedy scheme from Apple. They want any application that should run on "their" OS to have to be "authorized" - which means paying Apple to get a certificate validating that the developer has indeed paid them. They (greedy corporations) usually say this is a "security feature" because it keeps you from running software not "approved" by them - but in reality it's just a way for them to earn money on other people's work.

Obviously as UMS is open source and made by volunteers we don't earn money of it, so we have no money to give to Apple. It's not just a one-time fee either, you have to "rent" such a certificate.

The solution is either to find a way around Apple's "protection" or switch to another OS. This has a lot in common with the well known mafia "protection money" system - you pay us or you don't operate here...

**Comment by onon765trb** [comment]
GateKeeper fee!
This issue is a note of using UMS, rather than a problem.
Please close this issue.

There is another way to avoid the above dialog. But I can't recommend it on security.

**Comment by Sami32** [comment]
@onon765trb Hoping that these ways will satisfact Mac OS X users ;-)
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Mac-OS-X-issue
