### ISSUE TITLE
100% CPU usages

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1204]
is it normal for Mencoder to use up 100% of my CPU for long periods of time ?

**Comment by Sami32** [comment]
@Goten87 Maybe.

**Comment by Goten87** [comment]
is this not bad for my CPU

**Comment by Sami32** [comment]
@Goten87 Should i guess ? i'm not seer...

**Comment by Goten87** [comment]
your not what ?

**Comment by Sami32** [comment]
A voyant, a devin...
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by Goten87** [comment]
ok ik will try to get the CPU again up and reproduce the bug then upload it here

**Comment by Goten87** [comment]
i cant upload a zip to github?

**Comment by Sami32** [comment]
@Goten87 Add a fake _.txt_ extension to your ZIP file

**Comment by Goten87** [comment]
still not working

**Comment by Goten87** [comment]
even when i rename debug .log to .txt its not working

**Comment by Sami32** [comment]
@Goten87 If don't know how to do that, post a link on **Wetransfer** that we can easily download without logging.

**Note**: Avoid using MEncoder as it's an inefficient encoder by now and FFmpeg is the default and should be prefered.
Did you get this issue with FFmpeg ?
Why did you use MEncoder ?

**Comment by Goten87** [comment]
FFmpeg is on top
MEncoder second
TSmuxeR onder there

**Comment by Goten87** [comment]
https://drive.google.com/file/d/0B2467z65T2MfZFhlTTZReHdRVkU/view?usp=sharing
hope this will work ?

**Comment by Nadahar** [comment]
@Goten87 Just to mention, what is bad for the CPU is getting too hot. As long as your CPU keeps cool, there is no damage in using 100%. Whether or not your CPU is getting hot depends on how good your cooling is. 

I use Corsair H100iGTX and my CPU cores almost never goes above 35° C. When checking you CPU temperature use something that can read your core temperatures (e.g [CoreTemp](http://www.alcpu.com/CoreTemp/) and not just the CPU sink temperature.

I know this is not the main issue here, but my point is that the CPU doesn't take any damage unless it overheats. Different CPU take damage at different temperatures, and people have different ideas of how hot is "safe". I personally draw the limit at 70° C - I never want a CPU to get above that at any core.

**Comment by Goten87** [comment]
i think i have the same CPU cooler @Nadahar its a water cooled one right

**Comment by Nadahar** [comment]
@Goten87 Yes. It has support for Corsair Link (the most buggy software in the history of mankind) which let you control it, so if that's the case you could just starte Corsair Link and see the name of the cooler, along with the water temperature, core temperatures, fan speeds etc.

**Comment by Goten87** [comment]
@nadahar why I sayed that Its becose my cpu from my server also broke under heavy load now when it gets a heavy load it Will shut down my Ubuntu server and restarts

**Comment by Nadahar** [comment]
@Goten87 Then it sounds damaged yes - it has probably overheated.

**Comment by Sami32** [comment]
@Nadahar That's look a work for you ;-) It seem that a log's language localisation was forgotten.
> DEBUG 2017-02-20 21:28:33.517 [main] Error initializing plugin credentials: {}
> java.io.FileNotFoundException: E:\Universal Media Server Profiel\TV series\UMS.cred (**Het systeem kan het opgegeven pad niet vinden**)
> 	at java.io.FileOutputStream.open0(Native Method)

@Goten87 It's look like you did something wrong with your credential so you can delete your _UMS.cred_ file.

**Comment by Sami32** [comment]
@Goten87 Go to "Transcoding settings" tab and select "FFmpeg" video engine on the left, and deselect "Defer to MEncoder when transcoding problematic subtitles".

Go in "General configuration" tab and click on "Select renderers" and deselect all renderers.

Add this renderer:
[Philips-BDP.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/788889/Philips-BDP.conf.txt)
 and restart UMS. Now you can select this renderer called "Philips BDP" and try again to test if you get this issue.

**Comment by Nadahar** [comment]
@Sami32 The log shows a message that comes from the OS. This happens for several exceptions, especially those coming from the file system. There's nothing we can do about that, it will be in whatever language the OS is.

**Comment by Sami32** [comment]
@Goten87 To answer your question:
Yes it was normal, as it used the wrong renderer having a minimal support, leaving your computer transcode near every videos.

**Comment by Goten87** [comment]
yeah its dutch @Nadahar and it saying somthing like it cant find the path to somthing

**Comment by Nadahar** [comment]
@Goten87 I just didn't know that Dutch had "het"/"the". As I'm Norwegian it's close enough that I can sort of read it (The system can the given path not find).

The point is that it isn't looking in your profile folder, but in ```E:\Universal Media Server Profiel\TV series\UMS.cred```. The question is why...

**Comment by Goten87** [comment]
@Nadahar i have made a profile for my real movies and tv shows and i have a other one for my anime

**Comment by Nadahar** [comment]
@Goten87 If the file is there, in the correct location and UMS can't read it, it has to be a permission issue. Make sure that the user under which UMS is running has permissions to the file.

**Comment by Goten87** [comment]
@Nadahar i only have 1 user on my pc so dont know how to fix permissions on it if i delete it will it make a new one ?

**Comment by Nadahar** [comment]
@Goten87 When you create a file it inherits the permissions from the folder you create it in - so if UMS doesn't have write permission to the folder, that won't help. 

To edit permissions in Windows, right-click the file and select ```Properties``` and then go to the tab ```Security```. If you have "home edition" of Windows you're out of luck, since Microsoft has blocked access to the permissions there - so you have to boot in safe-mode to be able to edit permissions.

**Comment by Goten87** [comment]
ok i checked the UMS.conf and this is in ther
`cred.path = E:\\Universal Media Server Profiel\\TV series\\UMS.cred`

**Comment by Nadahar** [comment]
@Goten87 Yes, but there could still be permission issues.

If you have home-edition of Windows 10, the command line utilities might not be blocked. Open Windows PowerShell, and try:
```PowerShell
get-acl <path> | fl
```

For this particular file that should be:
```PowerShell
get-acl "E:\\Universal Media Server Profiel\\TV series\\UMS.cred" | fl
```
The user under which UMS is running need to have ```Modify``` or ```FullControl```. It doesn't matter if you just "have one user", Windows has some built-in users and groups so there's always more than one.

If you can't start PowerShell (I don't know how crippeled the "Home Editions" are as I don't use them), start a "Command Line" (run ```cmd```) and try:
```PowerShell
icacls <path>
```
For this particular file that should be:
```PowerShell
icacls "E:\\Universal Media Server Profiel\\TV series\\UMS.cred"
```
The output from ```icacls``` is somewhat more cryptic. Ff you don't understand it paste it here.

**Comment by Goten87** [comment]
@nadahar I have win 10 pro so I think I can use powershell Will try it tomorow going to sleep now

**Comment by Goten87** [comment]
@Nadahar oke im so stupid xD my profiles are on F:\ and not E:\

**Comment by Sami32** [comment]
@Goten87 Can we close this issue now ?

**Comment by Goten87** [comment]
sure
