### ISSUE TITLE
Video/audio asynchronous on variable frame rate mkv files

### ISSUE THREAD

**Issue by owlhuang** [UniversalMediaServer/UniversalMediaServer#1210]
### SUMMARY
Video and audio is slowly drafting away on some variable frame rate mkv files.  They are about 9 seconds apart after a 2hr40min (9600s) video is played.  It appears that mediainfo is giving out incorrect frame rate number (24.099 FPS instead of 23.976 FPS.)  Detail and a proposed fix is as below.

### ENVIRONMENT
- ums 6.6.0 running on a linux box
- renderer is Playstation 3 (with mediainfo on)
- ums engine of choice is mencoder, to render subtitle correctly

### DETAIL
With UMS debug information on, '-ofps 24' is sent to mencoder as parameter.  Yet the video stream is AVC variable frame rate with 23.976 fps.  If manually set '-ofps 24000/1001', the resulting video and audio are perfectly matching to each other.

Digging into UMS codes, the number for '-ofps' in MEncoder (MEncoerVideo.java) is originated from 'Frame rate' in MediaInfo (LibMediaInfoParser.java) around line 119.  

From mkvtoolnix author, MediaInfo is providing 'Original frame rate' from the video stream directly, while 'Frame rate' is calculated as '1/duration' from the container.  The author also explains the duration in a mkv file is NOT the average duration but the most commonly used duration of the frames.
https://github.com/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed

I believe that explains why MediaInfo is giving out 24.099 instead of 23.976 to MEncoder, for a variable frame rate video stream.

P.S. ffmpeg is giving out a correct 23.98 fps but I would prefer to use MediaInfo for Playstation3 renderer.  It is easier to config the codec/container the renderer supports.

### PROPOSED FIX
I would suggest to use 'Original frame rate' instead of 'Frame rate' for MediaInfo parsing, when it is present.  The codes in LibMediaInfoParser.java would be something like
```
- media.setFrameRate(getFPSValue(MI.Get(video, i, "FrameRate")));
+ value = MI.Get(video, i, "OriginalFrameRate");    // OriginalFrameRate needs to be confirmed as the correct token to retrive the intended value
+ if (value.isEmpty())
+     media.setFrameRate(getFPSValue(MI.Get(video, i, "FrameRate")));
+ media.setFrameRate(getFPSValue(value));
```

### OTHER SOLUTION
1. Fix MediaInfo: mediainfo should not use 1/duration for variable frame rate mkv files
2. Fix MEncoder: mencoder should be smart enough to transcode from 23.976 fps to 24 fps while keeping video/audio in sync.
3. Do not use MediaInfo at all: This is more like a workaround.

Either one should also resolve this issue but I expect MediaInfo/MEncoder would take much longer to fix.  Fixing in LibMediaInfoParser.java would be the most affordable solution here, IMO.

### RESULT FROM MEDIAINFO VIDEO SECTION

> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L5.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 8 frames
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 2 h 40 min
> Bit rate                                 : 3 210 kb/s
> Width                                    : 1 280 pixels
> Height                                   : 696 pixels
> Display aspect ratio                     : 1.85:1
> Frame rate mode                          : Variable
> **Frame rate                               : 24.099 FPS
> Original frame rate                      : 23.976 FPS**
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.150
> Stream size                              : 3.57 GiB (83%)
> Writing library                          : x264 core 60 r892M ad1d7a4
> Encoding settings                        : cabac=1 / ref=8 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=6 / brdo=1 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=2 / deadzone=10,10 / chroma_qp_offset=0 / threads=6 / nr=0 / decimate=1 / mbaff=0 / fgo=4 / bframes=5 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / wpredb=1 / bime=1 / keyint=250 / keyint_min=25 / scenecut=40(pre) / rc=2pass / bitrate=3210 / ratetol=1.0 / rceq='blurCplx^(1-qComp)' / qcomp=1.00 / qpmin=8 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=10000 / vbv_bufsize=8000 / ip_ratio=1.40 / pb_ratio=1.20 / aq=2:0.70
> Language                                 : Japanese
> Default                                  : Yes
> Forced                                   : No
> 
>

**Comment by owlhuang** [comment]
Attaching conf and log files.

[ums_bug1210.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/812515/ums_bug1210.zip)

**Comment by owlhuang** [comment]
I decided to pull the source code and gave it a try.  The proposed fix in the original post should work.  My PS3 could play the same video without video/audio asynchronous, and the _-ofps_ mencoder parameter is set to _'24000/1001'_ correctly.  I post the final version below.  If it is preferred, I could push my change to master branch, too.

For the record, I did have to remove the MediaInfo database and let UMS to re-populate it to make the change taking effect.  Learn new things everyday. :)  I don't know how to just re-build the SQL database.  It would be appreciated if someone could tell me how.
```

diff --git a/src/main/java/net/pms/dlna/LibMediaInfoParser.java b/src/main/java/net/pms/dlna/LibMediaInfoParser.java
index d1cf4c9..51d5b5d 100644
--- a/src/main/java/net/pms/dlna/LibMediaInfoParser.java
+++ b/src/main/java/net/pms/dlna/LibMediaInfoParser.java
@@ -116,7 +116,10 @@ public class LibMediaInfoParser {
                                                        media.setStereoscopy(MI.Get(video, i, "MultiView_Layout"));
                                                        media.setAspectRatioContainer(MI.Get(video, i, "DisplayAspectRatio/String"));
                                                        media.setAspectRatioVideoTrack(MI.Get(video, i, "DisplayAspectRatio_Original/String"));
-                                                       media.setFrameRate(getFPSValue(MI.Get(video, i, "FrameRate")));
+                                                       value = MI.Get(video, i, "FrameRate_Original");
+                                                       if (value.isEmpty())
+                                                               value = MI.Get(video, i, "FrameRate");
+                                                       media.setFrameRate(getFPSValue(value));
                                                        media.setFrameRateMode(getFrameRateModeValue(MI.Get(video, i, "FrameRateMode")));
                                                        media.setReferenceFrameCount(getReferenceFrameCount(MI.Get(video, i, "Format_Settings_RefFrames/String")));
                                                        media.setVideoTrackTitleFromMetadata(MI.Get(video, i, "Title"));

```

**Comment by Nadahar** [comment]
@owlhuang Thank you for a very thorough explanation and proposal. I'm normally not touching video transcoding as it's not an area where I have much knowledge, but you lay it out so clearly that there doesn't seem to be much need for knowledge 😉 

Clearing the database can be done by clicking on "Reset cache" (I think that's what it's called in English) on the "Navigation and Share" tab. Rebuilding when then either happen automatically as you browse folders, or can be started manually by clicking the magnifying glass button on the same tab.

**Comment by owlhuang** [comment]
Closed.  In short, this patch only works on this particular VFR file (which is 23.976fps most of time, and a small second part in 29.97fps.)  Detail in [this ](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1211)pull
