### ISSUE TITLE
PS4 Update 4.50 Issues

### ISSUE THREAD

**Issue by BigNSavage** [UniversalMediaServer/UniversalMediaServer#1219]
Ever since updating to any of the 4.50 Betas as well as the full 4.50 release on PS4 and PS4 Pro, I am unable to stream movies to my PS4 using UMS.  Some of the movies play audio for about 30 seconds and then I get a message on the PS4 saying Cannot Play the Media.  I am running UMS 6.6

**Comment by Sami32** [comment]
Our mind reader is absent today, so could you follow these steps ?
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

**Comment by BigNSavage** [comment]
Will do.

Thanks.
