### ISSUE TITLE
POM file incorrect

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1221]
> [DEBUG] Error retrieving POM of module-dependency: org.seamless:seamless-xml:jar:1.1.1; Reason: Error resolving project artifact: Failure to find org.seamless:seamless-xml:pom:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.seamless:seamless-xml:jar:1.1.1

> [DEBUG] Error retrieving POM of module-dependency: org.seamless:seamless-swing:jar:1.1.1; Reason: Error resolving project artifact: Failure to find org.seamless:seamless-swing:pom:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.seamless:seamless-swing:jar:1.1.1

> [DEBUG] Error retrieving POM of module-dependency: org.seamless:seamless-util:jar:1.1.1; Reason: Error resolving project artifact: Failure to find org.seamless:seamless-util:pom:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.seamless:seamless-util:jar:1.1.1

> [DEBUG] Error retrieving POM of module-dependency: org.seamless:seamless-http:jar:1.1.1; Reason: Error resolving project artifact: Failure to find org.seamless:seamless-http:pom:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.seamless:seamless-http:jar:1.1.1

http://4thline.org/m2/org/seamless/parent/1.1.2-SNAPSHOT/
http://4thline.org/m2/org/seamless/

> [DEBUG] Error retrieving POM of module-dependency: commons-logging:commons-logging-api:jar:1.1; Reason: Some problems were encountered while processing the POMs:
> [ERROR] 'distributionManagement.status' must not be specified. @ line 163, column 13

> [DEBUG] Error retrieving POM of module-dependency: net.jthink:jaudiotagger:jar:2.2.5; Reason: Error resolving project artifact: Failure to find net.jthink:jaudiotagger:pom:2.2.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project net.jthink:jaudiotagger:jar:2.2.5

> 
> [DEBUG] Error retrieving POM of module-dependency: maven:maven-nsis-plugin:jar:2.1; Reason: Some problems were encountered while processing the POMs:
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 118, column 15
> [ERROR] 'distributionManagement.status' must not be specified. @ line 139, column 13

> [DEBUG] Error retrieving POM of module-dependency: commons-httpclient:commons-httpclient:jar:3.1; Reason: Some problems were encountered while processing the POMs:
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 218, column 15
> [ERROR] 'distributionManagement.status' must not be specified. @ line 252, column 13

> [DEBUG] Error retrieving POM of module-dependency: org.fourthline.cling:cling-core:jar:2.1.1; Reason: Error resolving project artifact: Failure to find org.fourthline.cling:cling-core:pom:2.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.fourthline.cling:cling-core:jar:2.1.1

> [DEBUG] Error retrieving POM of module-dependency: org.fourthline.cling:cling-support:jar:2.1.1; Reason: Error resolving project artifact: Failure to find org.fourthline.cling:cling-support:pom:2.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.fourthline.cling:cling-support:jar:2.1.1

**Comment by Nadahar** [comment]
@Sami32 How did you manage to get all those errors? Exactly what did you run to get this? Are you sure there wasn't a network issue while you tried to build? Was this in master?

**Comment by Sami32** [comment]
While trying to debug the JNA 4.3.0 build under WinXP with Maven:
`mvn -X -DforkCount=0 -DcompilerArgument=-Xlint:all -Dmaven.compiler.showDeprecation=true external:install`

I could try again tomorrow, but i don't think it's a network issue, though i cannot be sure without trying again.

**Comment by Nadahar** [comment]
Why are you running external:install? That only need to be run once, and never again unless the "external" dependencies are updated.

**Comment by Nadahar** [comment]
By the way, which version of Maven do you use? ```mvn --version```

**Comment by Sami32** [comment]
3.3.9

The command line is a copy/paste from my automatic build script for UMSbuilder. Since after the sull build it's clean all the files, it need to be rebuild. But if you interrupt the build after the JAR creation you don't need to worry about that as it'll only check and see that everything was already there.

**Comment by Nadahar** [comment]
@Sami32 You should stop using UMSBuilder. The build takes ages that way, because of the way our POM is made, a ```clean``` means that all the binaries must be downloaded again. Run ```mvn``` manually, a normal build is as simple as ```mvn package```.

**Comment by Sami32** [comment]
It doesn't appear when i build other branches.

Did you tried to build JNA 4.3.0 branch that way ? (the log will be near 26000lines)

**Comment by Nadahar** [comment]
The point is that you don't build UMS when you run ```external:install``` - you don't even run UMS' POM. You run [this](https://github.com/UniversalMediaServer/external-maven-plugin/blob/master/external-maven-plugin/pom.xml) instead, so it's hard to see how that can be relevant.

**Comment by Nadahar** [comment]
There's no surprise if there are some warnings from ```external-maven-plugin```. What I did was to build on [this Maven 2 plugin](http://code.google.com/p/maven-external-dependency-plugin/) and make a plugin for Maven 3. Unfortunately there were very fundamental changes between Maven 2 and 3, so a lot has changed. I was able to find "Maven 3 ways" of doing most of the things, but not all, so some deprecated Maven 2 dependencies are still used and called.

In the end I figured that I shouldn't spend any more time struggeling with that, as it did work perfectly fine under Maven 3. Still, some complaining from Maven is to be expected as a consequence.

**Comment by Nadahar** [comment]
@Sami32 I tried running your command on ```jna430``` and didn't get those results at all. However, I did experience another problem which led to #1223.

**Comment by Sami32** [comment]
What a shame that Checkstyle was not implemented...and that thought that somebody cared for the code :wink:

**Comment by Nadahar** [comment]
@Sami32 I have to laugh every time I see ```Checkstyle report will go out of memory because of the huge amount of issues it finds``` in the POM, but it doesn't surprise me. There's a lot of messy code in here.

**Comment by Nadahar** [comment]
@Sami32 I don't know why you suddenly closed this, but I'm guessing that you found a reason. In any case, I just attempted your command again after fixing the SSL validation. Your command 
```powershell
mvn -X -DforkCount=0 -DcompilerArgument=-Xlint:all -Dmaven.compiler.showDeprecation=true external:install
```
isn't valid (I'm using Maven 3.3.3 though). If I remove the offending argument and use
```powershell
mvn -X -DforkCount=0 -DcompilerArgument=-Xlint:all external:install
``` it works as expected, and I don't get a single ```WARN``` or ```ERROR``` in the output.

**Comment by Sami32** [comment]
I guess that i misunderstood you, i more time...I understood that it's was normal so i just close it.

Do the use of `-Dmaven.compiler.showDeprecation=true` and `-Dmaven.compiler.showWarning=true` is incorrect ? because i use them with `-DcompilerArgument=-Xlint:all` ?
I kept them as before the implementation of `-DcompilerArgument=-Xlint`:all i used them.

**Comment by Nadahar** [comment]
@Sami32 It's not "wrong", but my Maven doesn't understand it:
```
[ERROR] Unknown lifecycle phase ".compiler.showDeprecation=true".
```
If it works for you, there's nothing wrong with it. Ofcourse, if you would use Eclipse you wouldn't need any of these as Eclipse give you these warnings directly in the code.

**Comment by Sami32** [comment]
It i used Eclipse as you said, we'll never seen image libraries issue, HTTPS issue, JNA 4.3.0 issue....since i'm the last base 2 dinosaur ;)

**Comment by Nadahar** [comment]
@Sami32 You can build using Maven even if you have Eclipse - you can even do that from within Eclipse. I do that from time to time myself to check things, but I usually trust Travis to expose any problems building that way. 

The HTTPS issue wouldn't necessarily have been revealed by that, you'd also need to use an old JDK like I do 😉
