### ISSUE TITLE
PS4 Build 4.50 UMS not trancoding.

### ISSUE THREAD

**Issue by BigNSavage** [UniversalMediaServer/UniversalMediaServer#1222]
Ever since the PS4 updated to 4.50, using UMS from my PC is causing audio to play on streaming video for 10-20 seconds and then it says Media Cannot be Played.  I am attaching the trace logs as requested.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/836249/ums_dbg.zip)

**Comment by Sami32** [comment]
Please, stop to post multiple time the same issue, here or in the forum. Thanks.

Add `chromecast_extension=false` into your _UMS.conf_ file in _C:\ProgramData\UMS\UMS.conf_, and restart UMS.

If it doesn't solve your issue, please try to rephrase your comment, as I'm not sure to understand what do you mean.
- Do you mean that you have issue while playing videos on your PS4 ? PS4 Pro ?
- Do stream audio only, work fine ?
- Do you get this issue only with some videos files or all the videos ?
- Is Twonky working fine with your PS4 pro ?

**Comment by mikebutash** [comment]
I too have been seeing this on ums 6.6.0 on arch linux with watching various mkv videos, mine is more like about 20 minutes, but will stop, and I have to restart media player to resume watching, until it dies some time later again.

I will try disabling chromecasts, as I did notice it was seeing the ps4 as a chromecast device as well too now.

**Comment by Sami32** [comment]
@mikebutash I cannot really know without your trace log, but when you say 20 mn i'll though about _FFmpeg_ issue or an automatic wireless connection standby set in your OS configuration.
You can try with the latest _FFmpeg_ build. If you already updated FFmpeg to a more recent version it perhaps why you get this issue.
It worst a try with the latest, the original and 1 year old _FFmpeg_ versions and see if it solve your issue.

**Comment by mikebutash** [comment]
Even disabling chromecast extensions, the ps4 will just seemingly abort playback after 25-30 minutes.  First time today, ~25 minutes, second time was 29:59 minutes, and third was 29:03 minutes.  Really odd, no errors reported via ums, but rather looks like the ps4 is just stopping playback after 30 minutes.

Sony limiting playback of media?

**Comment by Sami32** [comment]
@mikebutash Checking at our forum, i saw that many users report and fix it different way.
http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=5563

So, i hope that one of them should fix it for you as well ;)

**Comment by Nadahar** [comment]
@mikebutash I just read the thread @Sami32 linked to, and to me it seems like this has to do with some strange behaviour by the PS4 regarding its IPv4 address. I've written a [post in that thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=5563&p=30669#p30669) with some suggestions.

**Comment by Sami32** [comment]
I think that you all have already fixed this PS4 issue with an adequat network configuration, with or without the help of our forum thread.
