### ISSUE TITLE
Better exception handling for java.nio.file.FileSystemException ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1233]
```
DEBUG 2017-03-24 12:05:43.116 [New I/O worker #6] Register error: java.nio.file.FileSystemException: E:\: The device is not ready.

INFO  2017-03-24 12:05:43.116 [New I/O worker #6] java.nio.file.FileSystemException: E:\: The device is not ready.
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at sun.nio.fs.WindowsException.asIOException(Unknown Source)
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at sun.nio.fs.WindowsWatchService$Poller.implRegister(Unknown Source)
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at sun.nio.fs.AbstractPoller.processRequests(Unknown Source)
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at sun.nio.fs.WindowsWatchService$Poller.run(Unknown Source)
INFO  2017-03-24 12:05:43.116 [New I/O worker #6] 	at java.lang.Thread.run(Unknown Source)
```

**Comment by valib** [comment]
@Sami32 which Java version do you use on your WIN XP? If you use Java 8 versions it could be the problem you are dealing with.

**Comment by Sami32** [comment]
@valib It's coming from the log of an user in our forum. He have Windows 7 64-bit and Java 7u75 32-bit.

**Comment by valib** [comment]
@Sami32 then it seems to me like wrong permission of the E: device or a problem with Java instalation or there is a problem with your OS.  I tested the UMS on the WIN XP without this problem.

**Comment by Sami32** [comment]
@valib This user didn't complained about that, yet, but i remember saw it in other logs as well sometimes ago. I suspect that affect only their external or network drive ?

Me as well, i was not able to reproduce it, though i don't have NAS. I don't think it's linked to Windows 7.

**P.S.** Note that i appreciate that you tested it on XP :wink:
If you think that this issue shoud be closed, please, feel free to do it.
