### ISSUE TITLE
PS3 External input stream instance is null

### ISSUE THREAD

**Issue by gkyildirim** [UniversalMediaServer/UniversalMediaServer#1234]
I've tried from 6.3.2 to latest 6.6.0 UMS version. No matter what I do DTS sound fails with "External input stream instance is null... sounds not good, waiting 500ms" if Keep DTS Tracks is enabled.  
I use latest Macos (Sierra) and I am pretty sure this was working flawless.

**Comment by Sami32** [comment]
Please, follow these steps:
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

And name the file used/tested while having that DTS issue.
Did you mean that before UMS 6.3.2 version, it was working for you ?

**Comment by Sami32** [comment]
@gkyildirim Feel free to reopen it when you'll have log.
