### ISSUE TITLE
Finish my half-made renderer configurations

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#1235]
@Sami32 I have some half-made renderer configuration that I've used when testing, which I've never really finished so that they can be merged because I think it's a very boring job. 

Not that I don't think it's boring for you as well, but it can't hurt to ask. If you would like, it would be very nice if you'd finish them so that they could be merged. It's kinda stupid that these are only available to me.

If you don't want to do this, simply close this issue - this is *only a suggestion*.

I made these back in 2015 so I really don't remember what state they are in, how much needs to be done. The Onkyo configuration should be for the 8xx series instead of just TXNR807, because after replacing my HDMI hard (where the DLNA part also is) I'm convinced that the exact same card is found in all the network-enabled Onkyo's of that generation. My replacement card was "configured" for a complete different model, and I had to go into some "advanced" menu to change the model.

[MediaMonkey.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/870840/MediaMonkey.conf.txt)
[Onkyo-TXNR8xx.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/870842/Onkyo-TXNR8xx.conf.txt)
[foobar2000Renderer.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/870844/foobar2000Renderer.conf.txt)
[Onkyo-TXNR807.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/870846/Onkyo-TXNR807.conf.txt)
[foobar2000.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/870850/foobar2000.conf.txt)

![onkyo-txnr807](https://cloud.githubusercontent.com/assets/12900583/24332590/7a3102cc-1249-11e7-87a3-61faaaa42a25.png)

**Comment by Sami32** [comment]
Sure, i'll have a check, though i think you already have done the job for you renderer.
We already have a MediaMonkey configuration file, so i'll compare them, though "our" have a not "standardized" name at all.

Thanks for sharing :smile:

**Comment by Sami32** [comment]
@Nadahar Bad boy :wink: 
Your MediaMonkey renderer is a fake one. A wish i guess.

Do you think i need to make only one renderer based on the latest version ? with just the supported formats by default or with all the additional plugins possibilities ?

**Comment by Nadahar** [comment]
@Sami32 What do you mean "fake"? I said that I didn't remember what state these were in or how far I had gotten with them.

When it comes to "supported" formats that's always a problem with software players. I guess the best thing to do is to make it work as it is with a default install. Still, we have to assume that some of the common codecs are installed - otherwise almost no video formats are supported.

**Comment by Nadahar** [comment]
I don't remember if this were ever completed, but I can't imagine that somebody will ever do it.

**Comment by Sami32** [comment]
I've them but i never tested the MediaMonkey one.
And your renderer conf has been done but you wanted some other Java audio issues to be fixed ;)
