### ISSUE TITLE
Thumbnails DLNA profiles and other infos incoherence

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1256]
Logging the output, and not the original informations, is very useful, IMHO.
Though we can see that the thumbnail DLNA profile set is incorrect:
> TRACE 2017-04-09 18:05:19.609 [Library Scanner] Finished converting image from format PNG. Output image width = 480, height = 480 and output profile: PNG_LRG. Flags: Convert colors = False, Re-encode = False
> TRACE 2017-04-09 18:05:19.609 [Library Scanner] Parsing results for file "14 Clementi Piano Sonata in D major, Op 25 No 6 - ALAC.M4A": Container: M4A, Size: 9395842, Bitrate: 451111, Duration: 00:02:46.00, Audio Tracks: 1 [Id: 0, Language Code: en, Audio Codec: ALAC, Bitrate: 436743, Channel(s): 2, Sample Frequency: 44100 Hz, Artist: Howard Shelley, Album: Clementi: The Complete Piano Sonatas, Vol. 4, Track Name: Clementi: Piano Sonata in D major, Op 25 No 6 - Movement 2: Un poco andante, Year: 2009, Track: 14, Genre: Classical], DLNAThumbnail: [Format = PNG, Resolution = 480×480, Size = 118231, DLNA Profile = PNG_LRG], Mime Type: audio/x-m4a

The original cover art is a BMP format, with 700 x 700 pixels.

**EDIT**: Here one sample.
[14 Clementi Piano Sonata in D major, Op 25 No 6 - ALAC.M4A.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/908384/14.Clementi.Piano.Sonata.in.D.major.Op.25.No.6.-.ALAC.M4A.txt)

**Comment by Nadahar** [comment]
@Sami32 I'm not sure what you're pointing to here. Are you referring to ```Finished converting image from format PNG```? I don't think that's a bug, the input format is reported as parsed by ```ImageIO```. Are you sure that the original cover art is properly extracted by MediaInfo, and that it isn't actually fetched from CoverArtArchive instead? Try turning of CoverArtArchive, disable caching and parse it again...

**Comment by Sami32** [comment]
> Resolution = 480×480, Size = 118231, DLNA Profile = PNG_LRG

What is for you a "thumbnails DLNA profile" ?
If it's look fine to you...

**Comment by Nadahar** [comment]
@Sami32 Yes, it looks fine. Do you mean that only JPEG_TN and PNG_TN should be used as thumbnails? If so, we would get very low resolution thumbnails.

I've set the upper limit for image and video thumbnails to 320x320, and 480x480 for audio - because the audio thumbnails/AlbumArt is often shown quite big while playing audio in players so they can benefit from the extra resolution.

**Comment by Sami32** [comment]
From my DLNA standard reference, 480x480 pixels is not an image PNG_LRG profile...

**Comment by Nadahar** [comment]
@Sami32 What is it then?

**Comment by Sami32** [comment]
OUPS... shame on me i mix with JPEG profile, so you are correct :blush: 
My standard agree with you, my memory do not :wink:
