### ISSUE TITLE
Malformed POM

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1265]
As explained here:
https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e4253f85a84402aaacad5f74635f228de1f1438d/pom.xml#L750-L810
![capture_04192017_152959](https://cloud.githubusercontent.com/assets/18471069/25182340/93d7e60e-2514-11e7-8580-c82df478a6fe.jpg)

As a general report POM good practice:
http://maven.apache.org/surefire/maven-surefire-report-plugin/usage.html

**Comment by Sami32** [comment]
bootstrap class path is not set in conjunction with `-source 1.7`
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/pom.xml#L679

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1266

**Comment by Sami32** [comment]
2 minor warnings from Maven:

> log4j:WARN No appenders could be found for logger (org.apache.commons.configuration.PropertiesConfiguration).
> log4j:WARN Please initialize the log4j system properly.

**Comment by Nadahar** [comment]
@Sami32 When, where are these warnings? If it's during tests, it's nothing to worry about. I just means that the logger isn't configured, which is fine as we don't want the tests to write to "debug.log".

**Comment by Sami32** [comment]
Thanks. I didn't worried, but i didn't know it was intentional.
Yes, they appeared at the test.

**Comment by Sami32** [comment]
Already addressed by @valib in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1266
