### ISSUE TITLE
Build profile that doesn't download binaries

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#1281]
Travis builds spend a lot of time and bandwidth on downloading binaries like FFmpeg, DCraw etc for every build. This also uses a lot of unnecessary bandwidth from your file host @SubJunk. I can't see that this is necessary to run the tests, and I think we should make a build profile that doesn't download these.

**Comment by SubJunk** [comment]
Sure, that sounds good, they're not needed for tests currently

**Comment by atamariya** [comment]
This #1371 should help.

**Comment by Nadahar** [comment]
Probably won't happen.
