### ISSUE TITLE
OGA should be fixed

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1294]
Some code fixes, OGA class, and all the renderers having `f:ogg` should be modified by `f:oga`

**Comment by Nadahar** [comment]
Taken care of in #1295.

**Comment by Sami32** [comment]
At least partially, as `f:ogg` has not been replaced by `f:oga` in the audio support section of the renderers.

Thank you :sunglasses:

**Comment by Nadahar** [comment]
@Sami32 Argh - I'm sorry, I was tired. I just "read" that as the acc -> m4a fix.
