### ISSUE TITLE
Problem playing videos on Google Chromecast 2 after update to v6.7.0

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#1301]
After update to version 6.7.0 i get problem with playing videos on my google chromecast 2.
I see there is new renderer conf file (google chromecast ultra) but playback is not working.

i am using bubbleupnp app on my android smartphone, to select video i want to play on chromecast but no luck afte 6.7.0 update (bubbleupnp error message is something about rendering)

when i try to play video manually(on Linux), i mean after clicking on renderer icon in ums main window and selecting video file, ums shows in log window: Started playing, BUT nothing is played on chromecast.

**Comment by prescott66** [comment]
Fixed in v6.7.1

**Comment by Nadahar** [comment]
@prescott66 It was the very *reason* for 6.7.1 so close after 6.7.0 😊

**Comment by prescott66** [comment]
@Nadahar thank you for your fix ;-) i was quicker like AUR repo in Arch.update comes few minutes after my bug report :smile:
