### ISSUE TITLE
Correct DLNA Flag?

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1302]
Thank you for the good app.

DLNA.ORG_OP=11 and ORG_CI=0 are used in transcoding even when using SeekByTime= true

For example,
`TRACE 2017-06-12 16:23:46.384 [HTTPv2 Request Worker 2] Network debugger: "mkv.mkv" http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_HP_HD_AAC;DLNA.ORG_OP=11 size=100000000000 duration=0:18:19 http://xxx.xxx.xxx.xxx:10045/get/27/mkv.mkv_transcoded_to.ts`
`ContentFeatures.DLNA.ORG: DLNA.ORG_PN=AVC_TS_HP_HD_AAC;DLNA.ORG_OP=11;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000`
This is a part of the attached log.
On my understanding, DLNA.ORG_OP=10;DLNA.ORG_CI=1 is correct.
My misunderstanding?

This question arises from impossible seeking when using TranscodeVideo= MPEGTS-H264-AAC.
But possible when using TranscodeVideo= MPEGPS-MPEG2-AC3, SeekByTime= true, TranscodedVideoFileSize= -1, ChunkedTransfer= True.

[ums_dbg_MPEGTS-H264-AAC.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1067886/ums_dbg_MPEGTS-H264-AAC.zip)

**Comment by Nadahar** [comment]
@onon765trb DLNA has never been properly implemented in UMS or it's predecessor. There's loads of inconsistencies like this. When it comes to the CI flag, it doesn't really matter as long as there's just one ```<res>``` source to choose from. The CI flag is supposed to aid renderers in chossing the "best" version of a given media when multiple versions are offered with the assumption that CI == 0 sources will be chosen if supported by the renderer. UMS only offer one source per media file, so it's irrelevant although technically wrong.

The seek flag on the other hand is a real problem if set wrong. Without verifying the facts here, you might have found a bug.

**Comment by Sami32** [comment]
@onon765trb In fact in our code, we call it exclusive. (that was done for Panasonic renderer ;))
You need to add this line in the renderer:
`SeekByTime = exclusive`

**Comment by onon765trb** [comment]
Thank you for your replies.
DLNA.ORG_OP=11 is used in TranscodeVideo= MPEGTS-H264-AC3,  TranscodeVideo= MPEGTS-H264-AAC, TranscodeVideo= MPEGTS-MPEG2-AC3, TranscodeVideo= MPEGPS-MPEG2-AC3 even when using SeekByTime= true.
And I can't find the way to set DLNA.ORG_OP=10. As you point out, it may be a bug.

**Comment by Sami32** [comment]
If tou still have using `SeekByTime = exclusive`, yes it's a bug.
I cannot reproduce it with my Panasonic though, and it's seem that is the same for the developpers having a Panasonic as well.

Please, could you post a new log while using `SeekByTime = exclusive` ? thank you.

**Comment by onon765trb** [comment]
I have attached the log of SeekByTime = exclusive.
Seeing the log, SeekByTime = exclusive give DLNA.ORG_OP=10 and SeekByTime = true give DLNA.ORG_OP=11.
Though I expected SeekByTime = exclusive give DLNA.ORG_OP=11, my expectation isn't correct?
The specification of Panasonic products?

[ums_dbg_exclusive.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1076268/ums_dbg_exclusive.zip)

**Comment by Sami32** [comment]
@onon765trb As i told you. So there is not bug, it work as expected.

Some renderers, like Panasonic, doesn't work with `DLNA.ORG_OP=11`.

**Comment by onon765trb** [comment]
Thank you for your pointing out and explanation.

**Comment by Sami32** [comment]
@onon765trb Thank you to you to point at our documentation not being that clear.
Sorry, i'm not known to be good at explanation :wink: 

```logtalk
# DLNA SETTINGS
#

# Set to true to use the DLNA feature seek-by-time instead of the default
# seek-by-byte method.
#
# Valid values:
#
#     true:
#
#         The renderer supports seek-by-time.
#
#     false:
#
#         The renderer doesn't support seek-by-time, so it should
#         only use the default seek-by-byte method.
#
#     exclusive:
#
#         While most renderers that support seek-by-time also support
#         seek-by-byte, some (e.g. the PS3 [1] and Panasonic TVs [2])
#         behave unreliably if both are permitted when transcoding files.
#         This option works around this by disabling seek-by-byte for
#         transcoded files when permitting seek-by-time.
#
# [1] Seeking via "Go To" with the PS3 (firmware 4.31) and MEncoder works with
#     "exclusive", but hangs or crashes with "true".
# [2] http://www.ps3mediaserver.org/forum/viewtopic.php?f=6&t=15841
#
# Default: false
SeekByTime = 
```
