### ISSUE TITLE
Browse issue with Xbox 360 in 6.7.x

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#1306]
A new problem with version 6.7.x and Xbox 360 [has been reported](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=10024). I'm a bit clueless as to what is the exact cause, but knowing how terrible Xbox' DLNA support and given the changes in #1061 I'm assuming there are som "conflicts" relating to that (and the changed ```protocolInfo``` output).

What I don't understand is why we haven't gotten more than one report. The problem is that this particular user isn't too keen on doing too many tests, and since I have to just try to change things pretty randomly to see what makes the difference I'm kinda hoping for another report.

Do we really have that few active 360 users, or is the percentage that files a report that extremely small? In any case, I really need some testing against a 360, do we know of anybody else that has one?

**Comment by SubJunk** [comment]
I have a family member with a 360 and I can go to their house to test. Can you give me some steps that will be the most useful?

**Comment by Nadahar** [comment]
@SubJunk According to the report, it doesn't show video media when browsing (only empty folders).

**Comment by pilotsr** [comment]
I'd like to think there are more XBOX 360 users out there, but just not reporting the issue. I personally used to use a PS3 with UMS for streaming but it died "yellow light of death" lol. I just signed up for a Github account and would more than glad to test out test versions of UMS. As of now I've reverted back to 6.6.0 but if needed can update back to the most recent version, you would just have to let me know what would be needed as far as logs and where to send them to. Cheers!

**Comment by Nadahar** [comment]
@pilotsr Great, thank you. I'll probably use GitHub instead of the forum for this communication as this is easier for the others to track. You'll have to give me a few days though, as I'm currently in the middle of something else.

**Comment by pilotsr** [comment]
No worries, I will check back daily and stay on 6.6.0 for now until you are able for me to assist troubleshoot.

**Comment by Nadahar** [comment]
@pilotsr I've abandoned my "proper" fix of the related issue that I was working on, and made a "quick and dirty" fix instead. That means I'm ready to start testing this issue. I've built a test version that you can install [here](http://superbum.org/downloads/UMS-setup-360.exe).

The best solution would probably be to keep 6.6.0 installed and to install this test version to another folder. Switching between versions might lead to issues with the database, so it could be smart to make a backup  of the database first (just copy the files somewhere while UMS isn't running). The database files can be found in ```<profile folder>/database```. I don't know which platform you're on, but if it's Windows that defaults to ```%ProgramData%\UMS\database```.

What I'd like you to do is to create a "testfolder" where you put just a few files of different media types (whatever you have, images, audio, video of different formats). One of each format should be sufficient. Add that folder to your shared folders, and browse that folder when making debug files.

To make debug files, go to the ```Logs``` tab in UMS and select "Create trace logs". UMS will restart in a mode with extra logging. Then do your tests (browse the folder and try to open any media files that is there if any), and finally go back to the ```Logs``` tab and click "Pack debug files". Save the ```.zip``` file somewhere and attach it here with a short description of what you tested and what worked/didn't work.

I'd appreciate if you did one "reference" test of the test folder with 6.6.0 before you do it with the test version. I makes it easier for me to compare and see what the potential culprits are.

**Comment by pilotsr** [comment]
Will test this out tonight/tomorrow and post back with results.  Thx for keeping up on this and not forgetting us X360 users lol.

**Comment by pilotsr** [comment]
I went ahead and did the test, first with 6.6.0 as a reference as you recommended, no problems and I have attached the debug files with the appropriate versions in the zip file names.  I then went ahead and installed 6.7.3 snapshot that you linked and still cannot browse any files.  My test folder with media showed as having no content, and even the default web based stuff that comes preloaded with UMS such as TED, etc, shows as having no content in folders.  I've attached the 6.7.3 snapshot logs as well.  Hope this helps.
[ums_dbg_6.6.0.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1139812/ums_dbg_6.6.0.zip)
[ums_dbg_6.7.3snap.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1139811/ums_dbg_6.7.3snap.zip)

**Comment by Nadahar** [comment]
@pilotsr Thank you for the testing. I've compiled a new test version for you: [update.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1150590/update.zip). You don't need to make logs for 6.6.0 again, but I'd appreciate if you could generate new logs with this version and post if it doesn't work.

To "install" this version, just extract and put ```update.jar``` in the folder where UMS is installed (where ```ums.jar``` is located) and start UMS normally.

**Comment by pilotsr** [comment]
Hi Nadahar, I tried downloading using the link you provided but I keep getting sent to a XML error page.  I also tried right clicking and saving the file but same thing.  https://puu.sh/wKuvv/12d252743d.png Not sure if the link is incorrect or if it did not upload properly.  As soon as I can download the zip I will test it for you.  Thanks Again.

**Comment by Nadahar** [comment]
@pilotsr That's very strange, I can download it just fine. The link is: https://github.com/UniversalMediaServer/UniversalMediaServer/files/1150590/update.zip

**Comment by Nadahar** [comment]
@pilotsr Here is an alternative link if you for some reason can't download from GitHub: http://superbum.org/downloads/update.zip

**Comment by pilotsr** [comment]
@Nadahar Was able to download the update file using your second link.  Unfortunately, still not able to browse for media, including built in media such as preloaded TED TV included in stock UMS.  I tested it on both 6.6.0 (which got stuck on splash screen) and the test version you uploaded the other day.  Attached are the debug files from the test version with the latest update file.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1150734/ums_dbg.zip)

**Comment by Nadahar** [comment]
@pilotsr This is just guessing (I don't know what the "problem" is since the 360 follows its own standard that only Microsoft knows), so it can take some attempts. The ```update.jar``` will only work with the 6.7.3 test version.

There's no need to reinstall or delete the profile folder, this problem is simply only a syntax problem. When we send the description of the media files to the renderer, there's a standard way to this according to UPnP and DLNA in combination. Unfortunately, Microsoft has decided to *not* follow the standard so that the 360 should only be able to use "their" servers. UMS, and any other media server that works with the 360, makes changes to the communication for the 360 to pretend to be a Microsoft server. The problem is that these changes/hacks to get around Microsoft's "protectionism" is trial and error. Some of these things are known and documented several places online, but nobody knows all the details (except Microsoft). We have redesigned/improved the handling of images and thumbnails in UMS in 6.7.x, so there is more and better information available. Some of this triggers Microsoft's "this isn't our server" functions, and it refuse to display the content. I'm simply trying to change a little here and a little there to see if it decides to accept it. Since I don't have a 360, this can take some time - but we can get lucky and the next change I make might solve it. It's no way to know. 

I just explained so that you know what to expect. I'd recommend anyone thinking of putting their money in some Microsoft (or Apple, they are even worse at this) product to decide if they want to support such sabotage. We all vote with our wallet in the world of capitalism 😉

**Comment by pilotsr** [comment]
@Nadahar I totally agree with you, and do thank you for your wonderful program and the time and effort you put into your project.  It sounds like a complex problem, and of course it would be Microsoft not following the standard, and as you said Apple is no better.

It's unfortunate, I used to use UMS with my PS3 until it died of yellow ring or "light" of death.  I much prefer the PS3 interface over the 360 any day.  We do all vote with our wallet in the end, and I can assure you in the future once I'm able to afford it I will be getting a PS4 replacement lol.

Till then I do thank you again for your support, and I still don't mind being a guinea pig for future tests if needed.  I will continue to check this page daily, and if you require anymore testing please do feel free to let me know.

Kind Regards,

pilotsr

**Comment by Nadahar** [comment]
@pilotsr I've uploaded a new [update.jar](http://superbum.org/downloads/update.zip). This will also only work with the 6.7.3 test version.

Regarding my bashing of Microsoft, I'd like to say that Sony isn't much better in general although their DLNA support is better. That isn't really that surprising given that Sony is the "main company" behind DLNA, which might also have something to do with why Microsoft is trying to sabotage it. In any case, when it comes to consoles and freedom (not being locked down/forced) there are no "good" choices, which is one of the reasons why I prefer computers.

I don't know your GitHub preferences, but you can configure GitHub to send you e-mail alerts when new posts are made to this thread (in fact I think it's the default configuration). I posted the alternative links within a couple of minutes of your link yesterday for that very reason, and you didn't see it for hours for the same reason 😉

**Comment by pilotsr** [comment]
@Nadahar I tried the new update.jar and still no joy :( .  Apologies for not getting back to you sooner, been busy and not sure if there is a difference in our time zones.  I went ahead for the sake of troubleshooting and removed everything pertaining to UMS including the settings folder in ProgramData, and did a fresh install of 6.7.3 snapshot you uploaded above for testing with the most current update.jar with the hopes I was overlooking something simple.  I even let it reinstall Avisynth, but still experiencing no content found while browsing on the X360.  Again it's not only with my media, but the media links included with UMS.  If it means anything, it took a little longer this time for it to say no content was found lol.  Thanks again for your patience in trying to solve this, and again attached are the latest debug files.

-pilotsr
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1151350/ums_dbg.zip)

**Comment by Sami32** [comment]
@pilotsr Maybe nothing, but have you tried with supported music file having artwork / cover art embedded ? Did they display ?

As it seem the that the Xbox 360 support only JPEG SM profile, but 480x480, i'm wondering if that could be linked to your issue.
It'll good to test it also with a UMS version only delivering JPEG_SM profile, perhaps @Nadahar did already posted your one ?

**Comment by pilotsr** [comment]
@Sami32 I do have a music collection as part of my entertainment collection, and I am having same issues with that folder and X360 not being able to locate any files, regardless of music or pictures.  In my opinion (I am no expert) there seems to be something bigger here with the issue as with what I mentioned earlier, the X360 cannot even browse or locate the default media that comes preloaded with UMS, such as TED, etc.

**Comment by Nadahar** [comment]
@Sami32 @pilotsr This is something very fundamental at the UPnP/DLNA level, I doubt it has anything to do with the media at all. What's a bit strange is that in the last test I removed thumbnail resources alltogether, so now I'm not so sure that #1061 is the cause. I didn't remove the ```AlbumArtURI```, so I guess that's what I'll have to do next. 

@pilotsr Because this is on such a fundamental level, I don't want you to waste your time on deleting/reinstalling etc. That's why I wrote the length explanation above 😉 When I make a new test, just dump the ```update.jar```, do a quick test and if it doesn't work, create the log files and upload them. Nothing more is needed 😄

**Comment by Nadahar** [comment]
@pilotsr I'm sorry to say so, but your latest logfile is *not* the from latest ```update.jar``` I made. It seems like it's from the latest "full test version" I made of 6.7.3, To make sure I didn't mix up my files, I've recreated and reuploaded the file here: [update.jar](http://superbum.org/downloads/update.zip).

Just to make sure we're on the same page, extract ```update.jar``` from the ZIP file and place it in the folder where you've installed the 6.7.3 test version (in the same folder where ```ums.jar``` is located). Once that is done, start UMS.

**Comment by pilotsr** [comment]
@Nadahar Attached are latest log files with most current update.  I made a point of triple checking everything and downloaded your re-uploaded version just in case.  Still no joy, no videos or media found :( .
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1154062/ums_dbg.zip)

**Comment by Nadahar** [comment]
@pilotsr I've got another test for you: [update.jar](http://superbum.org/downloads/update.jar)

**Comment by pilotsr** [comment]
@Nadahar Sorry took a while for me to get back to you, I was swamped with things to do yesterday.  Just tested latest update.jar this morning, still no joy :( .  Log files attached.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1159965/ums_dbg.zip)

**Comment by Nadahar** [comment]
@pilotsr I'm sorry it's taken so long, but I've had trouble finding any more to try. The results are now as good as identical to those from 6.6.0. I managed to find one more tiny difference, so let's hope that's it: [update.jar](http://superbum.org/downloads/update.jar)

**Comment by Suprah83** [comment]
Hey I was unable to register to post to the thread about this on the UMS site, it kept saying my captcha/confirmation was wrong.  Anyways, I put the latest update.jar you posted into the root of the UMS folder and ran it.  I was then able to see/play video files on my xbox 360.  Sadly, just as I was starting to test this my 360 started freezing a minute or so after powering on, so I doubt I'll be able to benefit from trying to help out lol.  At least I can still use UMS for my xbox one!

**Comment by Nadahar** [comment]
@Suprah83 That is great (not the registering part though) news. Which UMS version did you use ```update.jar``` in?

I have changed quite a few things in ```update.jar```, most of them are probably not needed. I therefore need to reverse things and verify that it still works before we can release the fix. Too bad your 360 "died", it sounds like a temperature related problem. If it is, you might be able to get it to work a little longer if you keep it cool 😇 

In any case, I'll start working on a new ```update.jar```where I've reversed the changes that probably isn't relevant.

Just to be sure, your xbox one is unaffected by this? Or did this impact xbox one use as well?

@SubJunk The CAPTCHA issue is a problem, we need users to be able to register and post on the forum. It's a bit strange though, as there has still been a few bots that has posted after the new CAPTCHA was in place, although much fewer.

**Comment by Nadahar** [comment]
@SubJunk I just tried to sign up, and there is a problem with the CAPTCHA. The CAPTCHA itself works just fine and I'm able to "solve" it and it indicates that I was successful, however when I click ```Submit``` I still get the error:
```
The visual confirmation code you submitted was incorrect
```
It must be some kind of configuration issue, it almost sounds like the check is against a different CAPTCHA than the one that's shown on screen. Could this be remains of the old CAPTCHA?

**Comment by Nadahar** [comment]
I've uploaded a new and hopefully final test version [here](http://superbum.org/downloads/UMS-setup-360.exe). I need someone to test this with a Xbox 360 before we can merge this.

I file I've uploaded is for Windows. If anyone is able and willing to test but need installation files for a different version, please let me know and I'll upload a build.

**Comment by Suprah83** [comment]
I just tested out the xbox one with update.jar and everything seems to work just as it did before.  I was using 6.7.3, build date 7/24/17.

**Comment by Nadahar** [comment]
@Suprah83 Thank you, but I need you the test the last download I made: http://superbum.org/downloads/UMS-setup-360.exe

If you need it for a different platform, please let me know. I'm currently uploading a revised version of that file, so it won't be complete for another 7 minuts.

**Comment by Nadahar** [comment]
@Suprah83 Ah, sorry, didn't see that you wrote Xbox *One*. Does 6.7.2 have problems with Xbox One as well? Nobody has reported that.

**Comment by Suprah83** [comment]
With my original post I was talking about update.jar letting me see/play video files on the 360, but I never tested whether the update.jar affected my xbox one, so I just tested that, which I thought you asked me in your last post? What exactly do you need me to do with the exe? When I try to run it I get a NSIS error, "Installer integrity check has failed.  Common causes include incomplete download and damaged media.  Contact the installer's author to obtain a new copy.  More information at:  http://nsis.sf.net/NSIS_Error"

**Comment by Suprah83** [comment]
Sorry just to be clear I haven't been able to test anything out with the exe yet, I just tested whether the last update.jar caused any problems with my xbox one.

**Comment by Nadahar** [comment]
@Suprah83 Ok, the reason the ```.exe``` didn't work is probably because you downloaded it while I was uploading it. The upload is finished now, so try to download it again.

What I tried to ask you is if there were problems with the Xbox One without using ```update.jar``` or any test version, just the regular 6.7.2. I am only aware of a problem with the 360, but I became unsure if this issue also affects Xbox One.

**Comment by Suprah83** [comment]
Oh I have had no issues with 6.7.2 and my xbox one.  I haven't had any problems with any of the test versions I've used on my xbox one.  I just setup your latest exe and ran that version.  With that latest version, I was able to see/play video files on the 360 and it didn't seem to cause any problems with my xbox one.  I'm gonna get some dust cleaner today and see if that helps the issue with my 360 crashing, so let me know if you need me to test anything else with it.

**Comment by Nadahar** [comment]
@Suprah83 Great, that's what I needed to hear. I'm going for a merge of my fix so that it will be a part of the next release then.

**Comment by RobMagus** [comment]
Hi all, I use UMS on my xbox 360 and have experienced this bug with 6.7.2. I kept 6.5.2 alongside it and it works fine. I use the Linux version on Ubuntu. Is the update.jar available for Linux? Or shall I just wait for the next release?

**Comment by Nadahar** [comment]
Hi @RobMagus. To test the latest fix you must use [this update.jar](http://superbum.org/downloads/update.jar). I won't work together with 6.5.2, so you have to put it in the 6.7.2 folder.

I'd appreciate if you could report back if the issue was resolved for you as well.

**Comment by pilotsr** [comment]
@Nadahar  Sorry mate, I've been swamped with life.  Will test first thing tomorrow as well and report back.  Didn't want you to think I forgot!  Thx again.

**Comment by RobMagus** [comment]
After putting update.jar into my 6.7.2 folder I can confirm that I was able to browse videos fine on Linux with my xbox 360. Thanks!

**Comment by Nadahar** [comment]
@RobMagus Great, thank you.
