### ISSUE TITLE
Request: Support for codec_specific_script of ffmpeg

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1310]
Thank you for the good app.

In the present UMS, mencoder option has mencoder_codec_specific_script.
On the other hand, ffmpeg doesn't.

To avoid needless reencoding, I am going to use
```
vcodec == h264 :: -ovc copy -nosync
acodec == aac :: -oac copy -nosync
acodec == ac3 :: -oac copy -nosync
vcodec == mpeg2 :: -ovc copy -nosync
container == iso :: -ovc copy -nosync
container == iso :: -oac copy -nosync
```
But mencoder don't well work, as shown by #1309. tsmuxer also is similar. Its cause is in my researching. 

The development of ffmpeg is active. ffmpeg has many useful filters.
Moreover, the burdens of CPU, GPU, and network and the usage of electric power significantly decrease by ffmpeg_codec_specific_script. Of course, video and audio quality

`CustomFFmpegOptions = -c:v copy -c:a copy` well works in my tests. But not optional.
I think ffmpeg_codec_specific_script option is useful.  I request support for codec_specific_script of ffmpeg.
This requests may overlaps with #1177.

**Comment by Sami32** [comment]
@onon765trb Sorry, i've difficulty to understand you.

> `CustomFFmpegOptions = -c:v copy -c:a copy` well works in my tests. But not optional.

What do you mean by "But no optional" ?
Any option can be added, except the video filter ones.

**Comment by onon765trb** [comment]
Sorry for my bad expression.
`CustomFFmpegOptions = -c:v copy -c:a copy` is applied to all movies.
If a movie has a codec unsupported by client when using this, the movie isn't playbacked and is needed to be reencoded. Namely, the configure file of render has to be rewritten whenever a movie is playbacked.

My request is to automatically set a codec for each code of a movie.
For example, `-c:v copy` is set in the case a codec of a movie is `h264`.  `-c:v libx264` is set in the case a codec of a movie is `vc1`.

My request is suport for a passthrough mode lile ` mencoder_codec_specific_script` when using ffmpeg.

**Comment by Sami32** [comment]
@onon765trb I see. But as you don't use PS3 or Xbox, you codecs should be stream copied or transcoded, depending on your renderer configuration. And your actual renderer configuration is weak, without offence.

So, i think that you need to have a correct renderer configuration.

`mencoder_codec_specific_script` use MEncoder and tsMuxeR, 2 old engines, and our version of FFmpeg seem weak at remuxing (timestamps issues).
So, i continue to think that having a good renderer configuration file is the key ;)

**Comment by Sami32** [comment]
RendererName=Panasonic_HDD_Recoder_2
UserAgentSearch = Panasonic-UPnPSDK/1.00 DLNADOC/1.50
UpnpDetailsSearch = Panasonic
LoadingPriority = 1
CustomFFmpegOptions = -resampler soxr -precision 28 -vf "bwdif=mode=send_frame:parity=auto:deint=interlaced,scale=iw*sar:ih:flags=spline+accurate_rnd,pad=ceil((max(iw\,ih*16/9))/32)*32:ow*9/16:(ow-iw)/2:(oh-ih)/2,fps=30000/1001"
Thumbnails = false
SendDateMetadata = false
MuxNonMod4Resolution = true
PushMetadata = false
SeekByTime= exclusive
TranscodeFastStart=true
DLNAProfileChanges=MPEG_PS_PAL=MPEG_PS_NTSC|MPEG_TS_SD_NA_ISO=MPEG_TS_SD_JP_ISO|MPEG_TS_SD_EU_ISO=MPEG_TS_SD_JP_ISO|MPEG_TS_SD_NA=MPEG_TS_SD_JP|MPEG_TS_SD_EU=MPEG_TS_SD_JP|MPEG_TS_HD_60_L2=MPEG_TS_JP_T
TranscodeExtensions=dvr-ms,dvr,mkv,dv,ty,mov,ogm,hdmov,hdm,rmv,rmvb,rm,asf,evo,asx,flv,m2v,mpe,mod,tivo,ty,tmf,tp,m2p,m4v,avi,wmv,wmx,wm,divx,div,flac,mlp,fla,wma,m4a,aac,dts,mka,ape,ogg,shn,mpc,ra,mp2,wv,oma,aa3,gif,png,arw,cr2,crw,dng,raf,mrw,nef,pef,tif,tiff,mp3,wav
StreamExtensions= ts
MimeTypesChanges=audio/wav=audio/L16|video/mp4=video/mpeg|video/ts=video/mpeg
DLNALocalizationRequired=false
TranscodeVideo= MPEGTS-H264-AAC
TranscodeAudio= LPCM
# DefaultVBVBufSize=true
# MuxH264ToMpegTS=true
# MuxDTSToMpeg=false
# WrapDTSIntoPCM=false
# MuxLPCMToMpeg=false
MaxVideoWidth=0
MaxVideoHeight=0
H264Level41Limited= true
TranscodeAudioTo441kHz=false
AutoExifRotate=true
MediaInfo=false
Supported = f:mpegps|mpegts    v:mpeg2|mp4|h264    a:ac3|lpcm|aac|mpa	m:video/mpeg|video/vnd.dlna.mpeg-tts
Supported = f:mp3	m:audio/mpeg
Supported = f:wav	m:audio/L16
Supported = f:jpg	m:image/jpeg

**Comment by onon765trb** [comment]
Thank you for a new configure.
Regrettably, stansstreaming is impossible. I will try to furthermore research.

**Comment by Sami32** [comment]
@onon765trb This is only your own incorrect renderer, it why i asked you to post the `SinkProtocolInfo` here, as we cannot read your japaneese manual, and your network configuration block it from appear in your log.
