### ISSUE TITLE
NFE in the renderer configuration lines parsing

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1345]
When incorrect parameters are set into the renderer lines, NFE are throwed.
```logtalk
java.lang.NumberFormatException: For input string: "curcumin:100"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at net.pms.configuration.FormatConfiguration$SupportSpec.isValid(FormatConfiguration.java:229)
	at net.pms.configuration.FormatConfiguration.<init>(FormatConfiguration.java:409)
	at net.pms.configuration.RendererConfiguration.init(RendererConfiguration.java:1112)
	at net.pms.configuration.RendererConfiguration.<init>(RendererConfiguration.java:975)
	at net.pms.configuration.RendererConfiguration.<init>(RendererConfiguration.java:959)
	at net.pms.configuration.RendererConfiguration.loadRendererConfigurations(RendererConfiguration.java:272)
	at net.pms.PMS.init(PMS.java:659)
	at net.pms.PMS.createInstance(PMS.java:1142)
	at net.pms.PMS.main(PMS.java:1302)
```

**EDIT**: Ex. `Supported = f:avi|mkv m:video/avi nadahar:50`

**Comment by Nadahar** [comment]
Which renderer lines?

**Comment by Sami32** [comment]
`Supported = f:`

**Comment by Nadahar** [comment]
You have to be more specific - can you give an example of such a line?

**Comment by Sami32** [comment]
`Supported = f:avi|mkv             m:video/avi              nadahar:50`

**Comment by Nadahar** [comment]
You have skipped an important part of the logged message. The pervious line would say something like ```Error parsing maximum frequency "curcumin:100", which would make it a lot more obvious. Not every stack trace logged is a problem, especially in "trace" mode (which implies just that: including stack traces). The exception is logged and handled, it should have no other consequences than that the field that couldn't be parsed (e.g sample frequency) isn't set for that line.

I'm wondering what you see as the issue here, the fact that it is logged or the fact that it is parsed as samplefrequency?

It seems like the "problem" if there is one, is found in [parseSupportLine()](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/configuration/FormatConfiguration.java#L635). That's the method that decides what part of the line is interpreted as what value. Depending on what it was actually interpreted as, that could reveal why and if that is an error or not.

**Comment by Nadahar** [comment]
I can't quite see how the example above could end up being parsed as a number, it seems that it would be parsed as ```miExtras``` with ```curcumin``` as the key and ```100``` as the value. That isn't checked during ```isValid()```, so it's unclear to me exactly how this has happened. The line numbers from the stack trace doesn't match with those of the latest master, so I'd need to know which commit/version this stack trace was produced under to be sure of the code positions.

**Comment by Sami32** [comment]
If you say that it's correctly handled, that's fine for me.
I thought that this this log part was not "normal"
I discovered it by accident.

Thank for your explainations.

**Comment by Nadahar** [comment]
@Sami32 It depends on what the missing error message is. Having the commit hash that's logged in the "header" early in the log file would also help (```Build: <commit> (<date>)```, or if you linked to the log file.

**Comment by Sami32** [comment]
In fact, after your post, i became suspect and tested it on this master and realized that it was only linked in one anterior my code mistake that i have fixed.
I wrongly thought that it will be the same in this master and was not linked to my mistake that i have solved before posting this issue here.
So, everything is fine, sorry for having used your time :pray:
