### ISSUE TITLE
[Doubt] Questions about some important settings

### ISSUE THREAD

**Issue by Resease** [UniversalMediaServer/UniversalMediaServer#1346]
Since I couldn't register on the forum, I just found here to ask for help to understand some settings in the program.  If I couldn't post here just let me know.

1 - Is the **Maximum bandwidth in Mb/s** responsible for limiting the stream transference through wifi ?
So, if I have an internet connection of 15 Mbps for download and 10 Mbps for upload and a modem of 54 Mbps to wireless connection and I'm using all the internet (25 Mbps), Can I insert a value of 29 Mbps (54-25=29) to it without having delays ? 

2 - Is the **MaxVideoBitrateMbps**, found in Renderer settings (.conf), responsible for limiting the Bitrate (Mb/s) showed at the bottom of the Status display ? Is it overwrites what is in **Transcoding quality** (UMS setting) ?  

3 - Correct me if I'm wrong: UMS take the video, transcode it at the rate defined in **MaxVideoBitrateMbps**, keep it in a circular buffer sized by **Maximum transcode buffer size in MB** (_Is this buffer some cache folder or RAM memory ?_) and send the file in the buffer at the rate defined by **Maximum bandwidth in Mb/s**.

4 - My internet connection is like described in the first question and I'm using MiraScreen as renderer with ChromeCast.conf as reference. I just set it to: 
- TranscodeVideo = MPEGTS-H264-AC3
- TranscodeAudio = MP3
- MaxVideoBitrateMbps = 8

And UMS to : 
- Maximum bandwidth in Mb/s = 10
- Maximum transcode buffer size in MB = 400
- Transcoding Quality = Lossless quality (in both)

   I've watched two movies and after 40-50 min in both, the buffering bar appeared for 2-3 minutes, after that it disappeared and the movie played as well as before. I don't know what happens if the buffer was filled up and emptied or something else ....  Can I fix it increasing the Maximum transcode buffer size ?

**Comment by SubJunk** [comment]
Unfortunately we didn't respond to this for 5 years, whoops
