### ISSUE TITLE
LG-BP550.conf

### ISSUE THREAD

**Issue by baliboss** [UniversalMediaServer/UniversalMediaServer#1359]
Since version 6.7 (including version 7) I have found about half of my mkv files and a couple of mp4 files were not being displayed on my LG-BP550 bluray players.
 When I checked the mkv files the non showing ones all had an audio stream of AAC.
 The mkv files which did show all had an audio stream of AC-3.

 I seem to have sorted it out with a modification to the LG-BP550.conf file. Most likely it is applicable to the LG-BP.conf file as well.

 The original configuration file had this:
 Supported = f:mkv v:h264|mp4|mpeg1|mpeg2|vc1 a:aac-lc|ac3|dts|mpa|mp3|wma m:video/x-matroska
 Supported = f:mp4 v:h264|mp4|mpeg1|mpeg2|vc1 a:aac-lc|ac3|dts|mpa|mp3|wma m:video/mp4

 And now changed to this (added: he-aac)
 Supported = f:mkv v:h264|mp4|mpeg1|mpeg2|vc1 a:aac-lc|he-aac|ac3|dts|mpa|mp3|wma m:video/x-matroska
 Supported = f:mp4 v:h264|mp4|mpeg1|mpeg2|vc1 a:aac-lc|he-aac|ac3|dts|mpa|mp3|wma m:video/mp4

 Perhaps a permanent change to the LG-BP550 and LG-BP conf files could looked at.

**Comment by Sami32** [comment]
As i've already told you on the forum, it has been set into the renderer_fixes branch.
Thanks.

**Comment by baliboss** [comment]
I did go to the link that you posted. I couldn’t really understand how that worked so I posted it in what I thought was appropriate.

I’m happy to put in the link that you posted but it looks like there is some process to it.

Or, do I just post it at “start a new conversation” at the bottom of the page?

 

Thanks

______________________
Brian Tetlow



Ph:(H) + 61 861023428 (VOIP)
Ph:(M) + 62 81337912255
* brian@itsbiz.com.au

**Comment by SubJunk** [comment]
Thanks @baliboss this change will be in the next release :)
