### ISSUE TITLE
No Renderers Were Found Error 

### ISSUE THREAD

**Issue by storm-knight** [UniversalMediaServer/UniversalMediaServer#1367]
can you please help me i have trying to fix this for the last 6 hours ive tried reinstalling it several times and im not sure what to do it was working fine yesterday and now it wont connect to my ps4 or any other device for some reason 
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1239786/ums_dbg.zip)

**Comment by valib** [comment]
@storm-knight please do not force the network interface and leave it empty as default. You set wlan4 but in the fact the interface which should be used is wlan1. Let UMS to choose the correct interface.

**Comment by Nadahar** [comment]
I can't see anything wrong in your log, but there's no communication from any other devices. Check your network and firewall, something is preventing your renderer from contacting UMS.

**Comment by valib** [comment]
@storm-knight also try to restart the WiFi router. It hapens to me that after some time the router stops communication without any reason.

**Comment by SubJunk** [comment]
Stale
