### ISSUE TITLE
Hide thumbnail images

### ISSUE THREAD

**Issue by kevincox** [UniversalMediaServer/UniversalMediaServer#1375]
I have thumbnails for my media at the same path with a different extension. So if my media is `Funny Video.mkv` I will have `Funny Video.jpg` with the thumbnail. UMS notices this and uses the image as the thumbnail which is great.

The problem is that this image still appears in folder listings obscuring the videos. It would be great if these images could be hidden. (In my case I would even be fine with globally blacklisting images or some file patterns from listings)

**Comment by Nadahar** [comment]
That's a valid point although I'm not sure if I see a "clean" way to solve it. You can disable images on a per renderer basis, but that's more of a workaround. In the renderer configuration set ```images = false```.

UMS first finds all media files in the folder in question, audio, video and images. Thumbnails are resolved later (only when/if the renderer asks for a thumbnail), and that's when the "matching" of the thumbnail based on file name is done. At that time it is already listed as a media file. To do this, some extended filtering must be done at the time the media files are enumerated, and this logic can never be the same logic that resolves the thumbnails which means that unless these algorithms are kept completely "in sync" the danger is that some images can either be used for both or for none.

**Comment by kevincox** [comment]
I see what you mean. The logic wouldn't be hard but it would go the other direction (currently you have media.getThumbnail() but now you need media.isThumbnail()). I think that would be a nice way to implment it.

If you don't want to do that though how would a simple file-type filter work?

**Comment by Nadahar** [comment]
I don't quite see how to implement a file-type filter. Do you mean by extension? If so, I don't think that is much of a solution - even if you don't care for images, that might not be true for other users. In any case, I doubt anyone would want their "thumbnail image files" shown as separate images even if they also use UMS for images, so I think the solution should try to address those files specifically.

**Comment by kevincox** [comment]
For the filter it would definitely have to be an option because as you said many users wouldn't want it. 

If you are ok with the thumbnail hiding could you show me where in this code the filtering occurs? Maybe I could brave the Java and submit a patch.

**Comment by Nadahar** [comment]
@kevincox The problem is that I'm on vacation abroad and only have a laptop with no development tools installed with me. My only available code-resource is GitHub, which doesn't exacly make it easy to follow code or inheritance 😉 

From what I can see, the current thumbnail resolution is made here: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/aeecbc97c563dc62b8fe623dd704364d7e3df7c6/src/main/java/net/pms/dlna/RealFile.java#L258-L300

The filtering could be done in many places, but from my limited overview using GitHub it seems like the place to do it might be somewhere in here: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/aeecbc97c563dc62b8fe623dd704364d7e3df7c6/src/main/java/net/pms/dlna/DLNAResource.java#L569-L798

**Comment by kevincox** [comment]
Don't work too hard if you are on vacation, I am in no rush :)

I was looking at DLNAResource.addChild but the problem appears to be that it filters at add time, where as this filter will likely need to occur once all files are added. For example if the image is added before the video then we have no way of knowing that it is a thumbnail at that point. Of course we could do when you add the video it removes the thumbnail, but then you have the problem if the video gets added first. I'll poke around a bit more and see if this can be solved.

**Comment by kevincox** [comment]
I have looked around the code and I think I understand the relevent parts enough for a mini design proposal.

I think the best solution is to create `DLNAResource.addBlacklistedChild(DLNAResource)`. This function would be called by `DLNAResource.addChild` upon the addition of an item with a thumbnail to blacklist that thumbnail. This function would 1. Remove any existing children that match the added item and 2. Prevent further thumbnails from being accepted by `addChild`.

This would have a couple of implications. But they seem quite reasonable.

1. Thumbnails would be idenitified upfront.
2. We need to maintain this "blacklistedChildren" set.

I definitely missed a couple of details but I was hoping if you could advise on the high-level concept. If it sounds good I'll start hacking.

There is another alternative which is slightly simpler but could have a couple of false positives. This would be to group all children who's basename is a prefix of the basename of another child. Then for each group we only return images if there are no other files in the group.

**Comment by Nadahar** [comment]
@kevincox I'm sorry for not answering your proposal, but this part of the code is kind of a mess and I wanted to find the way that slowed down the process the least. I've created #1385 which I hope will solve it in a reasonable efficient manner. The images are excluded as early as possible, to avoid having to create unnecessary instances.

Any testing and/or feedback is welcome.

**Comment by kevincox** [comment]
No worries. I'll just be glad to use it :)
