### ISSUE TITLE
Regression: Thumbnails not working on Samsung TVs in 6.7.3

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1379]
There are two posts about the regression in the release thread http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=10450

> I have many problem with Samsung D5500 too:
> - no thumbnails
> - sort is not working
> - updated srt files no see on my TV (hasn't subtitle there or my TV cannot see this .srt file).
>
> With 6.7.2 version no problem, all things is correct.

and:

> But I have the same problem as with 7.0.0-rc1. Both my Samsung TV's won't show thumbnails any more.

**Comment by valib** [comment]
@SubJunk how can we help without the log?

**Comment by valib** [comment]
@Nadahar I think that the problem is that we send not only for images but also for thumnails the flag `DLNA.ORG_CI=1`. We don't send it for folder thumnails and it works. We should avoid it and it should work because before the version 6.7.3 we don't send it. For renderer is not important than we may need to transcode thumbnails before they are send.

**Comment by Nadahar** [comment]
Possible fix in #1383.

@valib I know you are fixated on the ```CI``` flag, but I've explained that before. From what I can see, this issue isn't related to that flag at all, but a NPE if the renderer requests ```ContentFeatures``` in the HTTP header.

**Comment by Nadahar** [comment]
@SubJunk Can you please test #1383 on your Samsung TV?

**Comment by SubJunk** [comment]
I can gladly test it but I only have a Panasonic TV, is that still useful?

**Comment by Nadahar** [comment]
@SubJunk Sorry, I confused myself to believe that you'd experiences the issue yourself. This far, only one user seems to have tested the fix in the release thread, and he goes on about some sorting problem that I can't reproduce/don't quite understand. It seems that this fixed the intended issue though, but I'd like to have some more feedback.

@UniversalMediaServer/developers Do we have any other way to test this on an affected renderer, can any of you think of somebody?

**Comment by Sami32** [comment]
@Nadahar Yes, if you need a test on Samsung J55xx , you could just ask to our only one still active moderator with a link to a Windows Java 8 excecutable test version.

Talking about old, do your Onkyo renderer doesn't meet this criteria ? :wink:

**Comment by Nadahar** [comment]
@Sami32 
> you could just ask to our only one still active moderator with a link to a Windows Java 8 excecutable test version.

..whose name is?

> Talking about old, do your Onkyo renderer doesn't meet this criteria ? 😉

It might, but it doesn't show thumbnails or play videos...

**Comment by Sami32** [comment]
@Nadahar Right, i've forgotten :wink: 

His name is Squadjot

**Comment by Nadahar** [comment]
@squadjot If you have an affected Samsung TV, would it be possible to get you to test [this version](superbum.org/downloads/UMS-setup-ContentFeatures.exe) and see if it solves it?

**Comment by angeljharrison1** [comment]
@Nadahar I do have an affected Samsung TV, but the link seems to be broken. 
Could you please provide a working link to test?
Thanks.

**Comment by Nadahar** [comment]
@angeljharrison1 Thanks, I've fixed the link. The link is for Windows though. If you're on a different OS, tell me and I'll build one for that.

**Comment by angeljharrison1** [comment]
@Nadahar Thanks, no need I'm using Windows. I'm downloading it right now, will test it and let you know the result.

**Comment by angeljharrison1** [comment]
@Nadahar Thank you, I've tested it and it's working. Good job 👍 

![image](https://user-images.githubusercontent.com/25013837/30072633-a1f2fc98-9273-11e7-9c1b-ed1d006dfdc8.png)

![image](https://user-images.githubusercontent.com/25013837/30072839-479281dc-9274-11e7-83a5-b73b3cfdd843.png)

**Comment by Nadahar** [comment]
@angeljharrison1 Great, thanks 😄
