### ISSUE TITLE
UMS fails start with VPN active

### ISSUE THREAD

**Issue by mfseeker** [UniversalMediaServer/UniversalMediaServer#1386]
I am running UMS 7.0.0-rc1 on Linux 9 (stretch). It starts and runs and restarts fine so long as I do not try to start it with my VPN active. It will run with the VPN (expressvpn). The client I am using is an Arris gateway box. When startup fails, the box is recognized as ARRIS Gateway (203D66D33C46), but it is overlaid by the orange diamond, and the mediaserver is not discovered by the ARRIS box.
Once I exit the VPN, I can successfully start UMS without having to reboot.

I have attached two trace logs, one for a normal connection and one for a failed connection.

[ums_dbg-normal-2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1281824/ums_dbg-normal-2.zip)
[ums_dbg-failed-2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1281825/ums_dbg-failed-2.zip)

**Comment by Nadahar** [comment]
This isn't a problem with UMS, but with your network. Your VPN client will probably block or partially block access to the local network while running. For UMS to work, both unicast (TCP and UDP) and multicast must work, and this is defined by the UPnP/DLNA standard. If your VPN client blocks some or all of this traffic, it simply won't work. It might not be possible to run a UPnP/DLNA server while running the VPN client. If your VPN client doesn't have the necessary configuration options to make it work, you might have to look for another client that will let you configure it.

**Comment by mfseeker** [comment]
Nadahar. Thanks for the prompt and clear response. I have been working with computers as an avocation since 1967 and yours is the best support I have ever received.
I will contact Expressvpn and see whether they can offer me a solution.

**Comment by Nadahar** [comment]
@mfseeker That's good to hear 👍 While I don't know if it will help, you might be able to use the OpenVPN client instead of the "custom" one.
