### ISSUE TITLE
"subtitle: null" displayed in the DLNAResource resolver string

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1388]
> TRACE 2017-09-08 20:30:46.234 [DLNAResource resolver thread 8-1] Adding sample.ts: audio: Id: 257, Language Code: en, Audio Codec: AC3, , Delay: -2144 ms, **subtitle: null**, player: FFmpeg

This video sample have no subtitle.

And it seem that an empty string is added as well between the `Audio Codec: AC3` and `, Delay:`, because we can see the comma `,`.

**EDIT**: Other one that display `null` instead of not displaying them when no audio or subtitle are available.
```
TRACE 2017-09-08 20:30:46.234 [DLNAResource resolver thread 8-1] Adding SUDS.mov: audio: null, subtitle: null, player: FFmpeg
TRACE 2017-09-08 20:30:46.234 [DLNAResource resolver thread 8-1] Adding SUDS.mov: audio: null, subtitle: null, player: MEncoder
TRACE 2017-09-08 20:30:46.234 [DLNAResource resolver thread 8-1] Adding SUDS.mov: audio: null, subtitle: null, player: tsMuxeR
```

**Comment by Nadahar** [comment]
@Sami32 I'm not sure what you think are wrong here. There's nothing wrong with things being ```null``` if they aren't set/relevant. Is there are problem related to this, or did you just not like the way it was logged?

**Comment by Sami32** [comment]
As i said, i think that it shouldn't be displayed when no audio or subtitle are present, but i guess that its a matter of taste ?

**Comment by Nadahar** [comment]
@Sami32 Yes, I see no problem with it - it's a log after all, and at least you know that it's null - which can be useful if you're trying to debug something.
