### ISSUE TITLE
Error during initialization on UNIX

### ISSUE THREAD

**Issue by Anomaly1** [UniversalMediaServer/UniversalMediaServer#1389]
Launching 7.0.0 rc1 with an existing V6.7.3 config, or without existing config folder on ubuntu 16.10, ends-up with:
**[main] net.pms.PMS A serious error occurred during Universal Media Server initialization: null**
Same error with a fresh install on a Mac running Sierra.
Seems to be related to UnixPath...
Please see attachment.
[debug.log.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1299995/debug.log.zip)

**Comment by Nadahar** [comment]
@SubJunk This looks like a bug related to watched folders on Linux/OS X, so this is something you should look into.

**Comment by SubJunk** [comment]
@Anomaly1 thanks for this, I will have a look. I have already fixed one init bug in 7.0.0 so if you have the ability to build and test that branch it would be good, otherwise I will look at this soon
