### ISSUE TITLE
Subtitle encoding issue with Samsung E+ Series

### ISSUE THREAD

**Issue by babywin** [UniversalMediaServer/UniversalMediaServer#1396]
Hi guys,
The srt subtitles show bizarre simbols on Samsung E+ Series TV
The only way to fix it is adding this line to the bottom of Samsung cfg profile for Samsung E+ Series TV

`RemoveTagsFromSRTSubtitles = false`

Please fix it for the next releases.
Is annoying add this line every time you update, and also are so many people who can't figurate how to do it.
Cheers.

**Comment by Nadahar** [comment]
@babywin It sounds like a bug - could you provide some more information? An example of a subtitle file (just add ```.txt``` to its name and you can attach it here) that produce these symbols, and an example of how this looks on screen?

I don't know if the Samsung supports the "SRT tags", but removing them shouldn't make problems for the subtitles in any case, so I'm wondering if we have some character set/encoding issue.

**Comment by babywin** [comment]
It happens with every srt subtitle,
And add `RemoveTagsFromSRTSubtitles = false` fix all the issues.
This is the post with the solution on the Universal Media Server Forum.
[http://www.universalmediaserver.com/forum/viewtopic.php?t=9180](url)
It contains examples and pictures of the subtitles.
But, as I said, it happens on every subtitle.

**Comment by Nadahar** [comment]
Ok, it's a bit easier to have it all here so I'm posting those here as well:

![img_20170208_151243](https://user-images.githubusercontent.com/12900583/31136525-d281e030-a868-11e7-9bf9-fafa9140a1b7.jpg)

[Ben-Hur.2016.1080p.srt.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1353035/Ben-Hur.2016.1080p.srt.txt)

**Comment by Nadahar** [comment]
@babywin Just to make sure, are the letters in the picture supposed to be:
```
...o Império Romano expande-se
em milhares de quilômetros.
```
?

**Comment by babywin** [comment]
Yes! 
-The photo shows the default wrong enconding.
-The quote shows the correct encoding.
That example is for portuguese language, but the issue is on all languages. For example, I use  spanish.
Thanks @Nadahar

**Comment by valib** [comment]
@Nadahar it seems to me like a bug in the TV for subs in UTF-8 format. I tested provided subs and they are correctly recognized as charset 8859-1 and language `pt` but the `removeSubRipTags` method not only removes HTML tags but also converts subs to UTF-8 whose are than streamed to TV. When is set `RemoveTagsFromSRTSubtitles = false` than the original subs file is streamed without reencoding.

**Comment by Nadahar** [comment]
@valib I know, see #1400.

**Comment by Nadahar** [comment]
@babywin I've built a test version of #1400 for Windows which you can download [here](http://superbum.org/downloads/UMS-setup_1400.exe). 

I would appreciate if you could test this version and and report back whether the problems with the subtitles are fixed.

**Comment by babywin** [comment]
@Nadahar I've tested and is OK.
Some pictures of correct letters and tildes:

![20171008_161139](https://user-images.githubusercontent.com/10915570/31320122-7bac89d2-ac45-11e7-8357-8f7ba2639e41.jpg)
![20171008_161126](https://user-images.githubusercontent.com/10915570/31320123-7bacc4ce-ac45-11e7-9a2d-f9eabc66c555.jpg)

Thanks a lot.
PD: Reinstalling the official 6.7.4 release, the bug obiusly come back.

**Comment by Nadahar** [comment]
@babywin Thanks. Reinstalling 6.7.4 will bring the bug back, but you can just use the test version until next release - it is basically just 6.7.4 with this fix applied.

The fix will be included in the next release.

**Comment by babywin** [comment]
Awesome! @Nadahar Thanks again!
