### ISSUE TITLE
Comment mistakes in UMS.conf

### ISSUE THREAD

**Issue by fripper1214** [UniversalMediaServer/UniversalMediaServer#1397]
Comment entry line does not begin with "#"

* Original
`# Prevent system idle sleep`
`...snip...`
`# - Playback: UMS prevents the system from going to sleep while playback from`
`    UMS is active.`
`# - Running: UMS prevents the system from going to sleep while UMS is running.`
`...snip...`

* Proposal for correction
`...snip...`
`# - Playback: UMS prevents the system from going to sleep while playback from`
`#   UMS is active.`
`# - Running: UMS prevents the system from going to sleep while UMS is running.`
`...snip...`

**Comment by Nadahar** [comment]
@fripper1214 I have some trouble understanding you formatting. Is what you're suggesting that:
```powershell
# Prevent system idle sleep
# -------------------------
# If your UMS host has a power-saving mode, use this option to prevent the
# system from hibernating or sleeping. Currently only Windows and macOS are
# supported. There are three modes:
#
# - Never: UMS doesn't interfere with system idle sleep.
# - Playback: UMS prevents the system from going to sleep while playback from
    UMS is active.
# - Running: UMS prevents the system from going to sleep while UMS is running.
#
# Default: Playback
prevent_sleep =
```
..should be corrected to:
```powershell
# Prevent system idle sleep
# -------------------------
# If your UMS host has a power-saving mode, use this option to prevent the
# system from hibernating or sleeping. Currently only Windows and macOS are
# supported. There are three modes:
#
# - Never: UMS doesn't interfere with system idle sleep.
# - Playback: UMS prevents the system from going to sleep while playback from
#   UMS is active.
# - Running: UMS prevents the system from going to sleep while UMS is running.
#
# Default: Playback
prevent_sleep =
```
?

If so, I completely agree - I just want to make sure that it's just that, and nothing more.

**Comment by Nadahar** [comment]
@fripper1214 Your edit made it a little more clear, so I think I've understood it correctly. I've made #1399 to address it.

**Comment by fripper1214** [comment]
@Nadahar Thank you for your comment.
Yes, I wanted to suggest a correction as you interpreted.

I am sorry that it became unfamiliar and incomprehensible content of description...
