### ISSUE TITLE
Java GUI not scaling for HiDPI screen linux, tiny unreadable fonts.

### ISSUE THREAD

**Issue by deerewright** [UniversalMediaServer/UniversalMediaServer#1403]
I am on Ubuntu 16.04, using Oracle Java 8.  UMS does not scale properly, and the fonts are too tiny to read.

**Comment by Nadahar** [comment]
You'd need to give more information. "Do not scale properly" is very subjective, the same goes for the fonts "being to tiny". UMS doesn't set these things at all, but leaves that to the OS. If there's a problem it's probably somewhere between Java and your desktop environment. I've never heard this complaint before though, so I'm wondering if you're using a high DPI monitor?

**Comment by deerewright** [comment]
Sorry, I thought I did specify...I am using a HiDPI monitor.  From what I've gathered, it appears to possibly be a Java issue, although the few apps that have this problem in Linux, do not in Windows.  
UMS is one of those. I have simlar problems with MoneyDance, Keepass2, but not as drastic.  I am not the only one, so I'm surprised you have not heard of this.  I also know that a similar problem lies with Mac Retina displays.

![screenshot from 2017-10-12 13-15-50](https://user-images.githubusercontent.com/3875818/31514887-d3c43b86-af58-11e7-8fb9-42cec2f094f1.png)


My display resolution is set at 3200x1800 with "Scale for menu and title bars" set at 2.

![screenshot from 2017-10-12 13-22-02](https://user-images.githubusercontent.com/3875818/31514905-e70c2dc0-af58-11e7-8257-52e803960c93.png)

**Comment by Nadahar** [comment]
@deerewright I've just answered you on the forum. As stated there, I don't think there's anything we can do about this, it's a Java (Swing)/Linux desktop manager problem.

**Comment by Nadahar** [comment]
If what is said [here](https://stackoverflow.com/questions/15659044/how-to-set-the-dpi-of-java-swing-apps-on-windows-linux) is true, Java 9 might actually support DPI scaling. Java 9 has just been released and UMS hasn't been updated to work with Java 9 yet though.
