### ISSUE TITLE
Info: UPnP search syntax support

### ISSUE THREAD

**Issue by atamariya** [UniversalMediaServer/UniversalMediaServer#1413]
I've added support for searching via UPnP search syntax in [my branch](https://github.com/atamariya/UniversalMediaServer/tree/antlr). This will work for DB based search implementation. One can search for **dc:title contains \"cap\"** across items and containers. Presently, only album, artist and genre containers are supported. The prime motivation for this was web-search to search for all supported entities rather than mere filename.

I'm creating this informational ticket for the following reasons:
- Should somebody want to implement this in master branch, one can reuse the Parser instead of re-inventing the wheel.
- I'm open for some feedback on the implementation

**Details**
All the relevant files are in `net.pms.dlna.search` package.

`UpnpSearchParser` is the parser class. It uses generated Anlr files for parsing. It returns a list of objects to be returned (`getObjects()`) and criteria (`getQuery()`). The criteria is then converted to SQL using `UpnpDBMapper.getSQLForItem()` and `UpnpDBMapper.getSQLForContainer()`.

**Usage**
```
			UpnpSearchParser parser = new UpnpSearchParser(searchStr);
			List<String> objects = parser.getObjects();
			
			for (String obj : objects) {
				if (UpnpObjectUtil.isContainer(obj)) {
					String[] sql = UpnpDBMapper.getSQLForContainer(obj, parser.getQuery());
					if (sql == null)
						continue;
					
					String name = UpnpObjectUtil.getName(obj) + ":" + searchStr;
					MediaLibraryFolder folder = new MediaLibraryFolder(name, sql, new int[]{MediaLibraryFolder.TEXTS, MediaLibraryFolder.FILES});

					// Don't add containers with zero child
					folder.refreshChildren();
					if (folder.getChildren().size() > 0) {
						container.addChild(folder);
						resources.add(folder);
					}
				} else if (UpnpObjectUtil.isItem(obj)) {
					String sql = UpnpDBMapper.getSQLForItem(obj, parser.getQuery());
					if (sql == null)
						continue;

					List<DLNAResource> items = discoverWithRenderer(container, sql, start, count, searchStr, null);
					resources.addAll(items);
				}
			}
```

**Comment by valib** [comment]
@atamariya I tried to test your branch and finished with this result
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1448090/debug.log)

**Comment by atamariya** [comment]
@valib did you do a clean build? I see the following error:
```
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write Exception in thread "Thread-24" java.lang.NoClassDefFoundError: net/pms/dlna/DLNAThumbnailInputStream
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at java.lang.Class.getDeclaredMethods0(Native Method)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at java.lang.Class.privateGetPublicMethods(Unknown Source)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at java.lang.Class.privateGetPublicMethods(Unknown Source)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at java.lang.Class.getMethods(Unknown Source)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at py4j.reflection.ReflectionEngine.getMethodsByNameAndLength(ReflectionEngine.java:367)
INFO  2017-11-06 23:59:05.013 [Thread-24] net.pms.util.SystemErrWrapper.write 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:319)
INFO  2017-11-06 23:59:05.029 [Thread-24] net.pms.util.SystemErrWrapper.write 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:344)
INFO  2017-11-06 23:59:05.029 [Thread-24] net.pms.util.SystemErrWrapper.write 	at py4j.Gateway.invoke(Gateway.java:252)
```
DLNAThumbnailInputStream is not present in my branch.

**Comment by Nadahar** [comment]
@atamariya Great. Are there any way to find this implementation without reading through all the code? Any branch, particular commits or any way to separate out just that implementation?

**Comment by valib** [comment]
@atamariya yes I made clean build. I have to use `mvn site` instead `mvn install` to made it because some tests are broken.

**Comment by Nadahar** [comment]
@valib ```mvn site``` won't work. You shouldn't run ```mvn install``` normally either (that means to build and install it to a Maven repository) but ```mvn package```. ```mvn install``` will probably work for UMS though because the "install" part isn't configured in the POM - but it's still a "bad habit" when that's not what you want to do.

If there are test failures you'd either have to figure out the test failures or skip the tests (```mvn package -DskipTests```), although skipping them isn't ideal.

**Comment by valib** [comment]
@atamariya `mvn package` like `mvn install` fail on the test. I don't agree that `mvn site` won't work. It only overcame the test failures but makes the `UMS-setup.exe` . Anyway building UMS with `mvn package -DskipTests` gives for me the same result I reported.

**Comment by Nadahar** [comment]
@valib I'm not saying that ```mvn site``` doesn't run - I'm just saying that it's not meant to build the project but to build the reports. It might generate the an installer, but there's no guarantee that the proper steps to build what's put in the installer has been done. If our POM were made properly I doubt the NSIS script should run at all when running ```mvn site```.

I didn't say that ```mvn package``` would make tests pass, I just pointed out that ```mvn install``` isn't what you want to do when you build UMS. It's for building and installing artifacts into a repository.

**Comment by valib** [comment]
@atamariya OK I understand but the main problem is not working your implementation. When I tested it in the Eclipse it doesn't produce that errors but browsing doesn't work either for my Panasonic TV or for web interface.

**Comment by Nadahar** [comment]
@valib You're not replying to @atamariya but to me..

**Comment by valib** [comment]
@Nadahar sorry I din't read that properly 😃 but the rest of the comment I made is relevant for @atamariya.

**Comment by Nadahar** [comment]
I just did a build of https://github.com/atamariya/UniversalMediaServer/tree/master myself, and it fails with a lot of missing symbols:

[build.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1452048/build.txt)

It seems to me like a lot of artifacts aren't defined as dependencies in the POM, which means that they aren't downloaded. It will probably build fine it the artifacts already exist in the local repository, but will fail otherwise.

**Comment by valib** [comment]
@Nadahar you have to test the branch `antrl` where @atamariya  added support for searching via UPnP search syntax. Which of course will not work for me besause my TV doesn't respond at this level.

**Comment by Nadahar** [comment]
@valib Ok, that branch is better - but it fails on tests because ```PMS.configuration``` isn't initialized. It builds for me using ```mvn package -DskipTests``` though.

**Comment by atamariya** [comment]
@valib Can you try after disabling any plugin? I think that's where py4j is used.

@Nadahar I've updated the original post with more details. Let me know if you have any questions. Your problem is possibly due to misconfigured folder in UMS.conf. What's the value there? Can you specify a proper value there?

**Comment by SubJunk** [comment]
This got implemented and released recently
