### ISSUE TITLE
Fix Java version check on startup

### ISSUE THREAD

**Issue by TQwan** [UniversalMediaServer/UniversalMediaServer#1414]
I recently upgraded to Java 9 (SDK and SE) and uninstalled java 8 se and java 8 sdk, because they contain vulnerabilities.

Anyway when I now start UMS 6.7.4 it says Java is not installed. I press Ok.
Then it tries to install Java. I close this window by clicking on the X (the esc also closes the window but nothing heapons)

Anyway UMS seems to start after closing the install screen (I guess it never checked if Java was really properly installed :D )

My TV is still able to stream from my PC with UMS 6.7.4 running Java SDK 9 (and SE 9).

Anyway please update the Java version check to support version 9, since this works

The problem is in this file
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/86502e6a72005cf18055f8eb118f85d2d833a004/src/main/external-resources/nsis/pms.nsi

I think line 193 is the problem:
; Check if JRE7 is installed
${VersionCompare} ${JRE7_VERSION} $R1 $R2

This just checks if JRE 7 is installed, while it should check if 7, 8 and 9 are installed.
Note: Line 149 "MessageBox MB_ICONINFORMATION "${PRODUCT_NAME} uses Java Runtime Environment ${JRE7_VERSION}+"
This line specifically says JAVA 7 and higher are supported.

**Comment by SubJunk** [comment]
I have reproduced this

**Comment by SubJunk** [comment]
This is fixed in 6.8.0 and 7.0.0-rc2
