### ISSUE TITLE
Feature/Wish: Cluster Support

### ISSUE THREAD

**Issue by mStirner** [UniversalMediaServer/UniversalMediaServer#1424]
I love the universal media server.

But a cluster feature will be nice. 
Example: You have 2 or more UMS Instances, one is the master (Visible on the network), the other UMS Instances are available via the master.

You browse trought the folder structure on your  SmartTV and dont know on with UMS wich content is located. You see all content splittet on different devices merged as one large.

I think the simples way to do this is, the slaves send an table of contents to the master wich merge all into an single.

**Comment by Nadahar** [comment]
Here is no simple way to do this as the current UMS code isn't very modular. I don't quite understand the need though. What would you achieve with this? Load balancing or redundancy? Either way it would require huge changes to the code.

If you simply want to share folders from different computers, you can just map the network drives on the computer running UMS and share them as any other folder.

**Comment by Sami32** [comment]
I think that @mStirner have forgotten to read his _UMS.conf_ configuration file:
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/UMS.conf#L1168-L1191

Please, feel free to re-open this issue if you think it is necessary.
