### ISSUE TITLE
Large (>2GB) file not listed on Tablet or TV due parse error

### ISSUE THREAD

**Issue by Antoniossss** [UniversalMediaServer/UniversalMediaServer#1436]
I have following INFO on the console

`The file /media/pi/EX2/MyMovie.mp4 could not be parsed. It will be hidden`

This is actual filename. File is over 2GB large. 
Other files plays just fine from the same directory, but indeed they are only around 500mb each. I have checked video with ffprobe and looks kind of regular. What could be the issue?

**Comment by Nadahar** [comment]
@Antoniossss It is probably related to MediaInfo, which is configured to be used or not in the renderer configuration. Please make a trace log as explained [here](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556) and post it so we can see what is happening.

I assume that you have a custom compiled libmediainfo, there could be some issue with the filesystem support for that version for example.

**Comment by Antoniossss** [comment]
I did compile ffmpeg by myself yes. Is MediaInfo a part of it? As I recall I did install it using apt-get only.

**Comment by Nadahar** [comment]
@Antoniossss MediaInfo is unrelated from FFmpeg, but it's also needed by UMS. If it's available via apt-get you shouldn't have to compile it yourself, but it all depends on what options whoever compiled it used. I don't know, I'm just guessing, but the bundled version of MediaInfo has no problems parsing files over 2GB on a normal Linux.

**Comment by Antoniossss** [comment]
I did compile ffmpeg. Iv installed MediaInfo by apt-get. 

Got debug info for you - done manually.

**Comment by Nadahar** [comment]
@Antoniossss Where is the debug info?

**Comment by Antoniossss** [comment]
Its in previous post. I have just tried mediainfo manually, and while there is a large output for "valid" files, there is literally NO output on the troublesome file.

**Comment by Nadahar** [comment]
@Antoniossss If you read the link I posted on how to generate debug files, you would see that you should end up with a ```ZIP``` file that you should post here. But, if you have confirmed manually that the version of MediaInfo you have can't handle files over 2 GB, there's no need for debug files as you already have the explanation.

You might have to look for another version or compile one yourself.

**Comment by Antoniossss** [comment]
Well ye, we know it is mediainfo related. No way to bypass mediainfo? I remember that UMS worked somehow when I had not yet installed mediainfo, it just complained that it is missing.

**Comment by Nadahar** [comment]
@Antoniossss You can turn it off in the renderer configuration or simply uninstall it, but a lot of stuff won't work then. Almost everything made in later years in UMS requires MediaInfo parsing to work, so you'll effectively revert to the old PMS code. MediaInfo give us so much more information about the media files, which is needed to know how to handle them properly.

**Comment by Antoniossss** [comment]
I am aware that it is used for a reason, its just my curiosity. I think that I ahve found reported bug about this https://bugs.launchpad.net/ubuntu/+source/mediainfo/+bug/1561910 so I guess I am out of luck on this.

**Comment by Nadahar** [comment]
@Antoniossss It doesn't say why it doesn't work, but it's likely related to it being the 32-bit version. 2 GB is a common limit for 32-bit, so it might have with how MediaInfo opens the media files. I don't know for sure though, it could also be a compile option.

I take it there's no 64 bit OS for the pi since you're still using 32 bit? 32 bit is being "left behind" on many fronts these days, developers often don't care for it anymore and don't test for it or make adaptations for it to work.

**Comment by Antoniossss** [comment]
I am a new PI user, my Rasbian installation is rather up to date so I guess it should be x64 if such is available. Cannot find exact info though.

`Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
`

**Comment by Nadahar** [comment]
@Antoniossss I see from your debug log that your Rasbian version is 32-bit.

**Comment by Antoniossss** [comment]
So that is cleared out. You may be right and this  can be related to the architecture.

**Comment by Nadahar** [comment]
@Antoniossss I actually thought that 32-bit Linux couldn't handle files above 32-bit at all, so I don't quite understand how large files can work without MediaInfo.

There seems there are 64 bit options, but I don't know how stable they are: https://github.com/bamarni/pi64

**Comment by Antoniossss** [comment]
https://sourceforge.net/p/mediainfo/bugs/1077/
Filed issue. Maybe one day ill try to move to x64

**Comment by Antoniossss** [comment]
As for a disclaimer Ill try to split video in half :)

**Comment by Antoniossss** [comment]
And what would you think - smaller files plays just fine
