### ISSUE TITLE
Mark RCs as pre-release

### ISSUE THREAD

**Issue by mbentley** [UniversalMediaServer/UniversalMediaServer#1438]
Would it be possible to mark the release candidate releases in GitHub as pre-releases?  I am using the GitHub APIs to find the latest stable version of UMS and it is trying to pull in the RC because it isn't tagged as a pre-release.

https://developer.github.com/v3/repos/releases/#get-the-latest-release

Thanks!

**Comment by SubJunk** [comment]
@mbentley that's done now
