### ISSUE TITLE
Audio and Subtitles Wiki page

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#1441]
I can't find a way to comment in the Wiki, so I'm creating this issue to discuss it.

I'm trying to figure out what the ```Subtitles language priority``` field does, since the logic in the code is rather unclear to me, and we already have the ```Audio/subtitle language priority```.

I turned to the Wiki to see if it could shed some more light on this. It didn't really help anything, and there are other problems there that makes no sense to me. I know that we refer users to this for configuration of audio and subtitles, and to be honest I can't understand how they can understand much from this text:

> - **Subtitles language priority**  
> A comma separated list of language codes [ISO 639-2][4] that defines the priority when choosing subtitles languages.  
> Where `und` stands for "undefined". If empty, the default values will be used. The default depends on the configured GUI language.

**While the above explains what to put there, it doesn't explain when this applies.**

> - **Forced language**  
> By default this value is empty, which will let UMS pick the subtitles language [ISO 639-2][4].

**I don't understand what this means.**

> - **Audio / subtitle language priority**  
> Determine the audio language and subtitles language pairs ordered by priority to try to match.  
> Audio language and subtitles language should be comma separated as a pair; individual pairs should be semicolon separated. `*` can be used to match any language. Subtitles language can be defined as `off`.  
> By default the values are `eng,off;*,eng;*,und`; that mean no subtitle for english audio track and all others audio track will get an english subtitle if present or anything else otherwise.  
> **Note**: If you are running UMS in headless mode, edit your _UMS.conf_ file and uncomment the following line as showed in this example:  
> `audio_subtitles_languages = fre,off;*,eng;*,und`

**I find the note very confusing, why would you need to uncomment anything if running in headless mode, and why would you turn subtitles off for French audio?**

> - **Alternate subtitles folder**  
> GUI offers a navigator to a folder generating an absolute path.

**This makes absolutely no sense to me.**

> - **Codepage for non-Unicode subtitles**  
> The character encoding (or code page) that should use for non-Unicode external subtitles.  
> "Auto detect" leave UMS choose the right code page. Change it manually only if you have a recognition problem.  
> **Note**: As the default automatic codepage recognition can sometimes fail, if your subtitles don't display, or even the video with subtitle fail, just select manually the correct codepage.

**Very strange English.**

> - **Specify TrueType font**  
> Allow to choose a font, TTF or OTF, already registered in the OS. For Windows users it's mean that the font file should be into the "\Windows\Fonts" folder, that can be done manually or clicking the right mouse button on the font file and choose "Install".
> For other operational systems the font file must be also put into the font folder or used the specific technique to register it to the OS.
> If not properly specified or not registered in the OS, the _Universal Media Server_ default font is used.

**Very strange English.**

> - **Styled subtitles**  
> Will have effect only if you use _FFmpeg_ video engine and you selected `Use font settings` in _Transcoding Settings --> Video Files Engines --> FFmpeg_ or that you set `ffmpeg_fontconfig=true` in your _UMS.conf_ file.  
>   - **Font scale**  
> The font scale used for ASS/SRT subtitling.  
>   - **Font outline**  
> The outline parameter used for ASS/SRT subtitling.  
>   - **Font shadow**  
> The shadow parameter used for ASS/SRT subtitling.  
>   - **Margin**  
> The margin used for ASS/SRT subtitling.  
>   - **Color**  
> The integer value for the subtitles colour. GUI offers palettes to choose from.  
> By default UMS pick the white color.

**Strange English**

**Comment by Sami32** [comment]
That is my poor english, you should have recognized the style ;P
I've created that page.
I just tried to correct some sections you've mentioned, but i leave the correct english writing to some english native.

**Comment by Nadahar** [comment]
@Sami32 Ok. I really think @SubJunk should take the time to do this as the only English speaker among us. It's an area of much confusion among users, and a proper description is very much needed. I don't blame people for not understanding that Wiki page, there are several things there that I wouldn't have understood.

**Comment by SubJunk** [comment]
Ok I'll have a look

**Comment by SubJunk** [comment]
I just did some edits to the Wiki. Hopefully it is improved.
With this section:

> **Note**: If your subtitles style settings are not taken in consideration as expected, edit your renderer configuration file, and comment or delete the last lines beginning with `SupportedExternalSubtitlesFormats` and `SupportedInternalSubtitlesFormats`, then restart UMS.

that may be describing a workaround for a bug or logic flaw. If a user selects a custom way to display subtitles, then the correct thing to do might be to always transcode subtitles, so then those lines in the renderer config wouldn't matter
