### ISSUE TITLE
Does not hide #--Transcode--# folder

### ISSUE THREAD

**Issue by racer1988** [UniversalMediaServer/UniversalMediaServer#1453]

**Comment by Nadahar** [comment]
@racer1988 Exactly what is your issue?

**Comment by racer1988** [comment]
Sorry, clicked too fast, I was editing the description.

I am using last version of UMS on Mac OS

I selected the option to hide the TRANSCODE folder.
However on my TV the TRANSCODE folder shows up, as #--TRANSCODE--#

**Comment by Nadahar** [comment]
@racer1988 Have you restarted UMS after turning it off and made sure it's still turned off after restart? Some users have had problems with settings not saving on HighSierra.

**Comment by racer1988** [comment]
You are right. I had to actually relaunch both UMS (restarting the server does not take in account changes) and the TV to get the setting applied.

Thanks for the quick support
