### ISSUE TITLE
Filter out Philips Hue bridges from list of detected media renderers

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#1458]
I recently started using Philips Hue lights in my house, and the Philips Hue bridge shows up in Universal Media Server as a detected media renderer, which it obviously isn't really.

Is it possible to filter it out with an appropriate `Philipshue.conf` file or something like that? If so, please consider adding such to future releases of Universal Media Server. Thanks!

**Comment by esabol** [comment]
Trace logs:
```
DEBUG 2018-03-08 16:13:55.377 [cling-6] net.pms.network.UPNPHelper Marking upnp renderer "Philips hue (192.168.1.xx)" at /192.168.1.xx as unrecognized
DEBUG 2018-03-08 16:13:55.377 [cling-6] net.pms.configuration.ConfigurationReader Reading automatic_maximum_bitrate: true (default: false)
DEBUG 2018-03-08 16:13:55.380 [cling-6] net.pms.configuration.ConfigurationReader Reading RendererName: "PlayStation 4" (default: "Unknown renderer")
INFO  2018-03-08 16:13:55.379 [pool-4-thread-1] net.pms.network.SpeedStats Checking IP: 192.168.1.xx for Philips hue (192.168.1.xx)
DEBUG 2018-03-08 16:13:55.380 [cling-6] net.pms.PMS Adding status button for Philips hue (192.168.1.xx)
DEBUG 2018-03-08 16:13:55.381 [cling-6] net.pms.configuration.ConfigurationReader Reading RendererIcon: "ps4.png" (default: "unknown.png")
DEBUG 2018-03-08 16:13:55.397 [cling-6] net.pms.network.UPNPHelper New renderer found: "Philips hue (192.168.1.xx)" with dlna details: {friendlyName=Philips hue (192.168.1.xx), address=192.168.1.xx, udn=uuid:2f402f80-da50-11e1-9b23-xxxxxxxxxxxx, manufacturer=Royal Philips Electronics, modelName=Philips hue bridge 2015, modelNumber=BSB002, modelDescription=Philips hue Personal Wireless Lighting, manufacturerURL=http://www.philips.com, modelURL=http://www.meethue.com}
DEBUG 2018-03-08 16:13:55.398 [cling-6] net.pms.network.UPNPControl Adding device: urn:schemas-upnp-org:device:Basic:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:2f402f80-da50-11e1-9b23-0017887c74a5, Descriptor: http://192.168.1.xx:80/description.xml, Root: true
DEBUG 2018-03-08 16:13:55.400 [cling-6] net.pms.configuration.RendererConfiguration Created playback timer for Philips hue (192.168.1.xx)
```

**Comment by valib** [comment]
You can use static IP addresses for all devices on your net and make the IP filter (white list) to forbid this device to connect to the UMS. It can be done on the UMS General Configuration page. See [Wiki](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Security-and-Privacy) for example.

**Comment by esabol** [comment]
Thanks for the reply, but I don't want to use static IP addressing for all the devices on my network.

Is there a way to turn off the "Basic" renderer?

**Comment by esabol** [comment]
Closing the issue before I could even respond was kind of rude.

**Comment by Nadahar** [comment]
@esabol It's a bit hard to understand how it can be a big problem that it shows in the UMS GUI. That doesn't mean that UMS does anything to it, simply that it's detected. There's no function to "filter out" renderers found on the network from being displayed, but you can prevent it from accessing UMS by blocking the IP address.

You don't have to use static IP addresses for all your devices, you can either give it a static IP outside of the DHCP pool or you can reserve an address for it in the DHCP server configuration (so that it is always given the same IP based on MAC address).

UMS is supposed to list all UPnP devices that offera the appropriate service (I think it's called ```MEDIARENDERER:1```).

That means that either the Hue Bridge lists this UPnP service, or there is a bug in UMS. If there is a bug it should be fixed, but without a full trace log there's no way to tell what the Hue Bridge announces.

**Comment by valib** [comment]
Sorry I was a little bit fast. There are implemented such rules for a network devices like routers etc. to not recognise them as renderers but this Philips Hue seems to be a special case. I will take a look on it. What I need is the UMS log in the TRACE mode.

**Comment by esabol** [comment]
It's not matching UPnP "MEDIARENDERER" though. It's matching "Basic", which I think is only used by some very old Blu-ray players that clearly misadvertise. I guess what I'd like to see is an option to turn off matching to Basic or a way to create a Philipshue.conf file that can hide or skip that device.
