### ISSUE TITLE
Support for RTSP?

### ISSUE THREAD

**Issue by arc95** [UniversalMediaServer/UniversalMediaServer#1461]
Hi all. We need to allow users to access a web app written in ASP.NET and stream CCTV streams in their browsers. The stream formats are: RTSP, MP4, and H.264. We have a Windows Server 2016 to serve the media.

A few questions about UMS (and sorry for being a n00b):
- Can an ASP.NET app written in C# interact with and use UMS to stream media using HTML5 `video` tag?
- Does UMS support RTSP, MP4, and H.264? 

Your help is much appreciated. Thanks 👍

**Comment by Nadahar** [comment]
@arc95  I don't think UMS is the correct software for the task. UMS is a UPnP AV/DLNA media server that streams to compatible devices like smart-TVs, game consoles etc. You might be able to configure it to serve the stream (I don't know much about configuring UMS for serving streams, it's mostly used to stream files), but I'm pretty sure you'd hit a lot of problems along the way. I'm not sure if UMS would handle to stream the same stream to multiple "clients".

I think you can find software that is much closer to what you want to do. You seem to have to use for UPnP AV/DLNA, which is the main purpose of UMS.

**Comment by Nadahar** [comment]
@arc95 Sorry, it's not an area I know much about.

**Comment by Sami32** [comment]
@arc95 Not mine either, but you could have a look at [FFmpeg](https://ffmpeg.org/ffmpeg-protocols.html#rtsp) and [VLC](https://wiki.videolan.org/RTSP/) and see if that fit your needs.
