### ISSUE TITLE
[Patch] wrong option of ffmpeg in TsMuxeRVideo

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1463]
Thank you for the good app.

There id Wrong option of ffmpeg in TsMuxeRVideo.jave of 3c1eaed9fa1231ec6c70af68f2959382dd180aa8.
`-strict experimental`
I attach a patch correcting it.
[strip_experimental_in_TsMuxeRVideo.patch.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1846402/strip_experimental_in_TsMuxeRVideo.patch.txt)

**Comment by Sami32** [comment]
Welcome to the club 👍 +1
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1180
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1180/commits/f0f104838b668299e76c9b7b6553937ab4168410

**Comment by valib** [comment]
@onon765trb we appreciate your effort but @Nadahar wrote same time ago that we need not patch but the Pull request and you agree with that https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1464#issuecomment-376823851 so why do you continue with this?

**Comment by SubJunk** [comment]
This? https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1476/files

**Comment by onon765trb** [comment]
@onon765trb Please wait. I am learning github.

**Comment by valib** [comment]
Merged in the https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1476
