### ISSUE TITLE
Portable Java 8 not recognized

### ISSUE THREAD

**Issue by TehPsychedelic** [UniversalMediaServer/UniversalMediaServer#1467]
Hello,

Using the latest UMS version. All installed fine. But everytime on startup it will ask me to download Java 7.x because it's not installed. 
I know this was "fixed" (I saw an old issue around) to apparently check 8 and 9 as well, BUT, the thing is, my Java install is manual and portable.

After closing the installer the application runs OK, because well, java binaries are on the %PATH% and also %JAVA_HOME% is defined.

Could a check be implemented to just use %JAVA_HOME% if registry not found and then parse version from there?

**Comment by valib** [comment]
Is there any specific reason you use portable version of Java?

**Comment by TehPsychedelic** [comment]
I run several SDKs at the same time and also I like polluting the registry etc the least I can. I got used to macOS clean installation of 99% of apps (except PKGs).
Also if I wanna switch SDKs I just change a couple things with own scripts, don't need to recur to third party apps nor install/uninstall methods just to use a new one (same with Python and others).

**Comment by Nadahar** [comment]
@valib I don't think it's that uncommon. People that's either used to Linux or macOS will probably prefer to do it this way, and it can also be more practical under some circumstances. Registryphobia might also play a role, as it's a quite common belief that using the registry can "slow down" your computer.

**Comment by valib** [comment]
Thanks for explanation. @TehPsychedelic as a workaround you can run directly `ums.jar` not the `ums.exe`. This will avoid the Java version checking.
