### ISSUE TITLE
Viewing contents of h2database

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1470]
Do any of you have a good way to browse it? I'm used to using tools like RoboMongo or PHPMyAdmin or whatever and before I look into it for h2 I wondered if any of you already knows @UniversalMediaServer/developers

**Comment by Nadahar** [comment]
@SubJunk I simply use the H2 console from the [H2 installation](http://www.h2database.com/h2-setup-2018-03-18.exe) for quick lookups. It's a "web console" and less than ideal if you want to do more than a simple lookup, so I've also used [SQuirreL SQL Client](http://squirrel-sql.sourceforge.net/) when I want a bit more functionality.

I'm sure there are others, but those two have been enough to meet my needs.

**Comment by SubJunk** [comment]
Thanks, I'm having trouble getting H2 console to display the database although it says it is connected. Does this look right?

![image](https://user-images.githubusercontent.com/584228/38239642-703e4eb0-3781-11e8-894a-6dcae4c17a22.png)

It doesn't seem to give me any tables:

![image](https://user-images.githubusercontent.com/584228/38239666-8409dfea-3781-11e8-9dea-8f7f4377bbca.png)

**Comment by Nadahar** [comment]
@SubJunk Try URL: ```jdbc:h2:C:\ProgramData\UMS\database\medias```

**Comment by Goten87** [comment]
just ask question and sugjestion but is it not more handy for users to have it in the program as a new tab
so we can edit stuff as well if we need to edit somthing like delete a watched ep or compleet folder from the database

**Comment by Nadahar** [comment]
@Goten87 It could be useful, but would require a huge amount of work. You would need to "protect" the data so that users couldn't make it invalid causing problems for UMS. Making the GUI that allowed you to edit what could be edited would be a lot of work as well, and finally I suspect users wouldn't appreciate when UMS deletes everything they have done during an update for example.

**Comment by SubJunk** [comment]
@Nadahar that worked, thanks
