### ISSUE TITLE
How do i prefent folder to be scanned

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1475]
i have a download map in my folder and i dont want it to be scanned / be put in the database
is there a way i can disable that map from being scanned or is that just uncheck the checkbox with the
`monitor played status of files` as well if i have scanned it how can i eazy remove it from the database file
just delete the file and let it scan all again or is there a other way

**Comment by valib** [comment]
@Goten87 all files in the shared folders are scanned whether they are media files and **only media files** are stored in the database and monitored if played. So be calm.
