### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by constatinus** [UniversalMediaServer/UniversalMediaServer#1484]
I was trying to compile a fresh version of UMS when suddenly, when running `mvn compile` , i get:

>  % mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Universal Media Server 7.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 is missing, no dependency information available
[WARNING] The POM for sevenzip:jbinding:jar:4.65-1.04-RC is missing, no dependency information available
[WARNING] The POM for sevenzip-allplatforms:jbinding-allplatforms:jar:4.65-1.04-RC is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.820 s
[INFO] Finished at: 2018-04-13T15:07:12+02:00
[INFO] Final Memory: 12M/168M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:7.0.0: The following artifacts could not be resolved: jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13, sevenzip:jbinding:jar:4.65-1.04-RC, sevenzip-allplatforms:jbinding-allplatforms:jar:4.65-1.04-RC: Failure to find jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 in http://4thline.org/m2 was cached in the local repository, resolution will not be reattempted until the update interval of 4thline-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I never compiled UMS before. Help ?

**Comment by Nadahar** [comment]
Is instructed in various places, you need to run the following once before you can build UMS:
```powershell
mvn external:install
```
This does not need to be run for consecutive builds.

**Comment by constatinus** [comment]
Oh, thanks, issue solved.
