### ISSUE TITLE
Build instructions for MacOS are out of date

### ISSUE THREAD

**Issue by holtkamp** [UniversalMediaServer/UniversalMediaServer#1500]
When trying to build the project for Mac, I used the Wiki-page: https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Build

It seems [the instructions for MacOS are a bit outdated](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Build#mac-os-x), the provided link (https://developer.apple.com/register/agree/?path=%2Fdownload%2Fmore%2F%3F%26name%3Dfor%2520Xcode%2520-) results in an error:

<img width="851" alt="screen shot 2018-05-14 at 11 11 44" src="https://user-images.githubusercontent.com/776405/39988450-a19a197a-5767-11e8-975c-30214a38e1ae.png">

For what its worth, I got xCode 9.3 installed and installed Maven using brew:

```
brew install maven
```
**Off-topic / Java-noob problem**
Then we can run `mvn package`, which results in some errors:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 min
[INFO] Finished at: 2018-05-14T11:09:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:7.0.2-SNAPSHOT: The following artifacts could not be resolved: jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13, sevenzip:jbinding:jar:4.65-1.04-RC, sevenzip-allplatforms:jbinding-allplatforms:jar:4.65-1.04-RC: Could not find artifact jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 in 4thline-repo (http://4thline.org/m2) -> [Help 1]
```

and 

```
[WARNING] The POM for jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 is missing, no dependency information available
[WARNING] The POM for sevenzip:jbinding:jar:4.65-1.04-RC is missing, no dependency information available
[WARNING] The POM for sevenzip-allplatforms:jbinding-allplatforms:jar:4.65-1.04-RC is missing, no dependency information available
```

My Java version, maybe it is too new?:

```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by Nadahar** [comment]
The macOS stuff seems very outdated, back with Java 6 Apple had their own Java version that was tied to xCode. Using OracleJDK, I don't believe you need xCode at all.

Java 10 will probably lead to a lot of pain though, I'd stick to Java 8 for now.

The reason for your error is one step that *is* listed in the Wiki though: [6. Resolve and install external libraries](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Build#6-resolve-and-install-external-libraries).

**Comment by holtkamp** [comment]
Thanks for the swift response. 

> The macOS stuff seems very outdated, back with Java 6 Apple had their own Java version that was tied to xCode. Using OracleJDK, I don't believe you need xCode at all.
>Java 10 will probably lead to a lot of pain though, I'd stick to Java 8 for now.

Aah, ok, nice. In that case this step can be replaced with a:

"Install Java: `brew cask install java8`"

Would a Pull Request for this be accepted?

>The reason for your error is one step that is listed in the Wiki though: 6. Resolve and install external libraries.

Oops, missed that part, executed `mvn external:install`, after that `mvn package` continues untill `[INFO] Running net.pms.util.FileUtilTest`. A modal is displayed indicating that a folder needs to be shared. However, no folder can be selected. This is not related to this issue though, will try to find out what happens here.

**Java 10**
As expected, with Java 10 this indeed results in problems, during `mvn package` the expected errors were generated:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project ums: Compilation failure: Compilation failure: 
[ERROR] /private/tmp/universalmediaserver/src/main/java/net/pms/newgui/LooksFrame.java:[144,47] cannot access com.sun.java.swing.plaf.windows.WindowsLookAndFeel
[ERROR]   class file for com.sun.java.swing.plaf.windows.WindowsLookAndFeel not found
[ERROR] /private/tmp/universalmediaserver/src/main/java/net/pms/newgui/LooksFrame.java:[189,45] incompatible types: javax.swing.LookAndFeel cannot be converted to com.jgoodies.looks.windows.WindowsLookAndFeel

**Comment by Nadahar** [comment]
> Would a Pull Request for this be accepted?

The Wiki is free for anyone to edit AFAIK.

Regarding Java 9/10, Oracle have made a real mess of things by blocking a lot of things that has been available in previous versions of Java. Some of these issues have non-compatible workarounds (which means that if you upgrade your code, it will no longer work with earlier Java versions) and others have no workaround at all.

These aren't problems that only affect UMS, but the whole Java ecosystem. Whether a particular piece of software is affected is a bit random. The problem isn't with any of UMS' code but with some of the libraries UMS depend on, so the problem will remain until the libraries find a way around the issues or we find a replacement for the libraries. The latter can be a huge job though, so it's tempting to wait and see.

**Comment by holtkamp** [comment]
>The Wiki is free for anyone to edit AFAIK.

Mmm, unfortunately this is not as easy as I would expect. 

https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

@Nadahar maybe you can perform the change, so we can close this issue 🤓

**Comment by Nadahar** [comment]
I thought the Wiki was open to edits for everyone. I have an "Edit" button on the top of every page. Are you saying that you don't?

I know you can't do PR's for the Wiki.

**Comment by Nadahar** [comment]
I've made an edit to the Wiki, but since I can't test it I'm not really sure if my instructions are correct.

**Comment by Nadahar** [comment]
@holtkamp Ok, I didn't know. It kind of undermines the purpose of a Wiki if we have to maintain it, but ok. How does my changes look?

**Comment by holtkamp** [comment]
Thanks, looks great! Closing issue.
