### ISSUE TITLE
I can't complete my registration at the forum

### ISSUE THREAD

**Issue by EmuAGR** [UniversalMediaServer/UniversalMediaServer#1501]
Hi! I won't get the activation email ( @hotmail.com ). I also tried to contact via this link ( http://www.universalmediaserver.com/forum/memberlist.php?mode=contactadmin ) but I didn't get a reply.

My username is the same as the one I'm using here.

Regards!

**Comment by Nadahar** [comment]
Hi.

Only @SubJunk can see what has happened, but my guess it that the activation e-mail has ended up in your spam filter/trash. Check your spam/trash folder...

**Comment by EmuAGR** [comment]
I already checked the spam folder, of course.

**Comment by SubJunk** [comment]
Can you use the forgot password link?

**Comment by EmuAGR** [comment]
It doesn't seem the case: "Your account has not been activated yet."

**Comment by SubJunk** [comment]
With gmail you can use the plus trick to try again, maybe it also works with hotmail I don't know, so you would do like `myname+ums@hotmail.com` instead of `myname@hotmail.com` to try for a second account. If that still doesn't work maybe use a disposable email service if you don't care about getting email notifications in the future

**Comment by EmuAGR** [comment]
Can't you just manually activate my account? As far as I know, phpBB is able to do that.

**Comment by SubJunk** [comment]
I dunno, are you a robot? AI is getting pretty good at conversations... ;)

**Comment by SubJunk** [comment]
Just kidding, I'm gonna try that now

**Comment by EmuAGR** [comment]
Definitely not a robot. :P
I just wanted to propose a better Samsung UHD profile support I've been testing for several months.

**Comment by SubJunk** [comment]
I bet AI can tell people it's not a robot, apparently I'm not very good at administering Turing tests. You're activated now. Looking forward to seeing the new profile
