### ISSUE TITLE
Make the NSIS installer detect OpenJDK on Windows

### ISSUE THREAD

**Issue by Chase-san** [UniversalMediaServer/UniversalMediaServer#1516]
I am forced to launch the application through the batch file otherwise it will try to install Oracle JDK (Which is an issue since they are going to a pay to use model).

I am using according to the logs OpenJDK 64-Bit Server VM 1.8.0_172 (64-bit) by Azul Systems, Inc.

I have attached the debug zip.

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2129972/ums_dbg.zip)

**Comment by SubJunk** [comment]
The way we detect JRE is by looking in the Windows registry for it. If you can find out what the registry entry is for OpenJDK (if there is one) we can maybe add support in our Windows installer

**Comment by SubJunk** [comment]
I'm labelling this as an enhancement since we have never attempted to support OpenJDK in the installer. But it should be easy to do

**Comment by SubJunk** [comment]
That sounds like a good idea, @Chase-san thanks for the notes, and of course feel free to contribute a PR if you can :)

**Comment by SubJunk** [comment]
This is no longer needed since we include Java in our bundles
