### ISSUE TITLE
UMS 7.1.0 System tray Icon context menu cannot display Chinese characters?

### ISSUE THREAD

**Issue by wwj402** [UniversalMediaServer/UniversalMediaServer#1519]
system: win7x64 chinese simplified
jdk: jdk_1.8.0_161

System tray Icon context menu cannot display Chinese characters.

![2018_07_01-2](https://user-images.githubusercontent.com/8820298/42131598-72e1f0e8-7d38-11e8-8d2f-7caf90d412c8.png)

**Comment by atamariya** [comment]
This is more of a system settings problem. I was able to get simplified chinese messages using instructions [here](https://www.pinyinjoe.com/faq/change-language-for-non-unicode-programs.htm)

![untitled](https://user-images.githubusercontent.com/7592594/42859047-6dfc319e-8a6f-11e8-9f51-d8c2e527adc2.png)
