### ISSUE TITLE
Ums only works once 

### ISSUE THREAD

**Issue by cannap** [UniversalMediaServer/UniversalMediaServer#1523]
Hi, when i try to open UMS a second time it wont start anymore i dont know why

What i do

Install UMS on Windows 10
watch some movies 
close ums
restart
try to open ums again nothing happens (cant find javaw.exe running)

UMS: is installed on C:\ where also windows is located
System:

Windows: 10 Pro (10.0.17143)
UMS: 7.1.0
Java: 8 Update 171 (Build 1.8.0_171-b11)

How to get it working again:

Find all Java Processes what ever java update javaw.exe(when its present)i kill it via  task
reinstall UMS and then it works only once 

i have no idea whats wrong 🗡 

thanks

//e other java apps like jdownloader works just fine

**Comment by Nadahar** [comment]
Upload the file `%ALLUSERSPROFILE%\UMS\debug.log` here by changing its extension to `txt` (GitHub doesn't allow you to attack `log` files).

Hopefully it can reveal what's happening.

**Comment by cannap** [comment]
Hi i just installed it on a other Partition and it works, i dont have the debug.log :/ i deleted that folder befor reinstall
