### ISSUE TITLE
GPU acceleration on integrated Intel graphics (VAAPI)

### ISSUE THREAD

**Issue by goncalossilva** [UniversalMediaServer/UniversalMediaServer#1530]
Hi, and thanks for the awesome software!

I'm using ffmpeg in UMS (which I confirmed to be compiled with VAAPI support) and UMS.conf contains the following: `gpu_acceleration=true`.

To the best of my understanding, this should trigger an ffmpeg call similar to the following the following: `ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i (...)`, provided that the device is available (it is). Inspecting `top`, these aren't included.

The end result is that I'm trying to do hardware accelerated transcoding on the integrated intel graphics, which in theory should work, but in the end the GPU has close to 0% utilization while the CPU is pegged at 100%.

At this point I'm questioning if this is supposed to work out of the box, or if I am expected to edit `CustomFFmpegOptions` to add the above lines. Thank you.

**Comment by mirh** [comment]
hwaccel vaapi is for decoding. 

Encoding has [different switches](https://trac.ffmpeg.org/wiki/Hardware/VAAPI#Encoding).

**Comment by goncalossilva** [comment]
I see, thanks for the explanation! I saw your PR in #1560, looking forward to it. :smile:

**Comment by SubJunk** [comment]
This is merged now :)
