### ISSUE TITLE
UMS is not starting anymore

### ISSUE THREAD

**Issue by SamyCookie** [UniversalMediaServer/UniversalMediaServer#1534]
Hi,

UMS does not start since upgrading from 7.0.1 to 7.2.0.
It seems a database upgrade issue (cf. logs below).
````
DEBUG 2018-07-28 15:09:45.805 [main] Using database URL: jdbc:h2:C:\ProgramData\UMS\database\medias
INFO  2018-07-28 15:09:45.805 [main] Using database located at: C:\ProgramData\UMS\database
DEBUG 2018-07-28 15:09:46.118 [main] Database file count: 0
DEBUG 2018-07-28 15:09:46.118 [main] Database version: 16
DEBUG 2018-07-28 15:09:46.118 [main] Starting check of database tables
INFO  2018-07-28 15:09:46.149 [main] Upgrading database table "FILES_STATUS" from version 4 to 5
ERROR 2018-07-28 15:09:46.164 [main] A serious error occurred during Universal Media Server initialization: Referential integrity constraint violation: "CONSTRAINT_ED: PUBLIC.FILES_STATUS FOREIGN KEY(ID) REFERENCES PUBLIC.FILES(ID)"; SQL statement:
ALTER TABLE FILES_STATUS ADD FOREIGN KEY(ID) REFERENCES FILES(ID) ON DELETE CASCADE [23506-196]
````
Thanks !

**Comment by SamyCookie** [comment]
maybe related to #1528 ?

**Comment by SubJunk** [comment]
This is fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1535
I will release the fix as 7.2.1 later today

**Comment by SubJunk** [comment]
Here is a preview build of the fix you can use http://www.universalmediaserver.com/uploads/UMS-zoomcns.exe

**Comment by SamyCookie** [comment]
Thanks for the patch, that was fast !
The build provided works but it is tagged with 7.1 version (that already worked).
Anyway, I am sure that the pull request provided is the solution for my problem.
So I close the ticket, I'll reopen if the bug will still here when UMS 7.2.1 will be out.

Thanks again !

**Comment by SubJunk** [comment]
Thanks for confirming the fix @SamyCookie 
7.2.1 is now available for download

**Comment by SamyCookie** [comment]
UMS 7.2.1 downloaded and tried, everything is OK for me ! Thanks a lot for the quick fix !
