### ISSUE TITLE
Automatically detect the correct Maven profile

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1550]
We should extend the profile `activation` sections in `pom.xml` to choose the right profile based on the operating system and detected Java version

**Comment by tridungng** [comment]
Hi @SubJunk, is this issue still relevant? Would love to take it as my first ever issue

**Comment by tridungng** [comment]
Hi @SubJunk, is this issue still relevant?

**Comment by SubJunk** [comment]
@tridungng I think so, I found this StackOverflow page about it https://stackoverflow.com/questions/18015178/detect-os-and-java-on-windows-and-linux

**Comment by tridungng** [comment]
@SubJunk thanks for the quick reply, I will work on this issue next weekend.

**Comment by rexrk** [comment]
I'm new to Open Source and exploring the issue of automatically detecting the correct Maven profile (#1550). Could someone confirm if it is already implemented and relevant to this issue, or if we need to implement ```<activation>``` part for it to work? I'd appreciate clarity on the current status and how I can contribute as a beginner.

**Comment by SubJunk** [comment]
It isn't implemented yet. I don't know exactly how it will work, especially with different CPU architectures, so it will need some investigation and testing from whoever works on it

**Comment by SharanyaR07** [comment]
Hey @SubJunk, I want to contribute to the project. Can I contribute?

**Comment by SubJunk** [comment]
Hi, we welcome contributions, there seems to be a lot of interest in this issue and I don’t know who is genuinely working on it, people seem to disappear after commenting. So I won’t assign it but please submit a PR :)

**Comment by rexrk** [comment]
I tried working on this enhancement as well, but I'm unclear about it since we have to provide the profile name for building the project. Do we need to change that approach as well?

**Comment by SubJunk** [comment]
That's what this story is about. Making Maven automatically detect the profile for the current OS/architecture

**Comment by rexrk** [comment]
Hi @SubJunk, can you please review the latest PR, seems all test cases have passed.

**Comment by SubJunk** [comment]
@rexrk thank you, nice work!

**Comment by rexrk** [comment]
Thank you! I'm glad I could contribute 😊.
