### ISSUE TITLE
Increase the default web interface video transcoding resolution

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1573]
By default we transcode videos to 720x404 in the web interface but it should probably be at least 1280x720 if the source is that or larger.

Is there a reason we reduce the resolution at all, instead of displaying the input resolution? @valib ?

**Comment by valib** [comment]
@SubJunk I think that we can stream video larger than 720x404 in case that the format is supported by the web interface but I think that transcoding was limited to the 720x404 because the FFmpeg is not able to transcode to higher resolution for the OGG format in real time.

**Comment by SubJunk** [comment]
@valib thanks for letting me know, I can confirm it's very slow. Maybe we can just bump it to 848x480 instead for a little boost

**Comment by SubJunk** [comment]
Also I tested it with the latest FFmpeg and it's still slow

**Comment by SubJunk** [comment]
This is done now
