### ISSUE TITLE
Remove duplicate information from prettified filenames in Media Library

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1582]
Currently it is like:

`Media Library > TV Shows > The Simpsons > Season 1 > The Simpsons - 101 - Episode Name`

It should be like:

`Media Library > TV Shows > The Simpsons > Season 1 > 1 - Episode Name`

It needs to do this only in that context though, not in the other folders

**Comment by stasinos** [comment]
Please see also the catch clause in testGetFileNameWithRewriting()
Is there a logging convention for internal errors that should never happen in a well-installed UMS, such the JSON  file missing? Should UMS just throw an exception or should the error be logged and "swallowed"?
