### ISSUE TITLE
Add support for more specific subtitle support in renderer configs

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1584]
Support `es` and `is` (external subtitles and internal subtitles) formats to the `Supported` lines in renderer configs instead of (or as well as) `SupportedExternalSubtitlesFormats`, `SupportedInternalSubtitlesFormats` and `VideoFormatsSupportingStreamedExternalSubtitles`

That way we can finally have really granular support for them. This is an idea we have been talking about for ages and I thought we had an issue for it already but I couldn't see it

**Comment by valib** [comment]
@SubJunk what about this #961 ?

**Comment by SubJunk** [comment]
Haha I thought it was here somewhere! I'm trying to clear out the issues and PRs and this really shows the importance of that :) will test it
