### ISSUE TITLE
ID 21 - code.google.com - Dish Network Hopper Renderer

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#159]
https://code.google.com/p/universal-media-server/issues/detail?id=21

**Comment by Nadahar** [comment]
@SubJunk Was this ever completed, or did you just close it because it's old?

**Comment by SubJunk** [comment]
@Nadahar closed because it has been waiting for a response for years. It can be reopened if it ever becomes active again.
