### ISSUE TITLE
ID 28 - code.google.com - Some DVD iso's produce "Unsupported Audio" on Samsung, No Audio on PS3

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#161]
https://code.google.com/p/universal-media-server/issues/detail?id=28

**Comment by Sami32** [comment]
@cch2375 @SubJunk Did the latest UMS version solved this issue ?

**Comment by SubJunk** [comment]
We did some work on DVD ISO support so maybe. Please re-open if it's not fixed
