### ISSUE TITLE
Create the MPlayer/MEncoder SB builds for macOS

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1610]
Just a reminder for myself to do this since our current version for macOS doesn't do everything we need it to.

Related to https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1309

**Comment by Nadahar** [comment]
...and Linux :innocent:

**Comment by SubJunk** [comment]
I tried making them for Linux before and failed after investing a lot of time in it, but yeah it could be good to try again :)

**Comment by SubJunk** [comment]
Related to https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1611

**Comment by SubJunk** [comment]
and https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1798

**Comment by SubJunk** [comment]
This is done now and we can start using them when https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2183 merges
