### ISSUE TITLE
Feature Request: Scheduled Restarts

### ISSUE THREAD

**Issue by LadyHaley** [UniversalMediaServer/UniversalMediaServer#1613]
Hey, I have an issue where my media server will stop broadcasting after like 6-8 hours of being on, so whenever I or my housemates want to use it I have to go to my computer and restart it manually. It would be great if I could schedule a restart at a set interval to help mitigate the problem.

**Comment by SubJunk** [comment]
@LadyHaley thanks for reporting this. Which operating system are you using?

**Comment by LadyHaley** [comment]
[DxDiag.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2479466/DxDiag.txt)
Windows 10 Pro 64 bit

**Comment by SubJunk** [comment]
We are working hard on making UMS more stable over longer periods of time and we are close to a big fix for it. I would ideally like to do a real fix instead of this. This would be good if we weren't so close to a good fix but I think we are :)
