### ISSUE TITLE
Subtitles not linked with files without a server restart

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1624]
The files are recognised but a program restart is needed before they are linked with the file, at least that is my understanding of the problem. I'm not sure if it has been solved in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1483 already, I remember discussing it before but there has been so much discussion around that PR that I can't remember that exactly. Do you know if that addresses the problem @valib ?

There is a good forum thread about it at https://www.universalmediaserver.com/forum/viewtopic.php?p=37569 that involves Madoka who is a long-time user who may be able to help test a fix.

Also possible we already have an issue for this :)

**Comment by pipin77** [comment]
Just a feedback:  subtitles still not working without a restart. as mentioned in the thread i'm pretty sure it worked before (but it could be a very old 5.x version)

**Comment by SubJunk** [comment]
This was confirmed fixed on the forum
