### ISSUE TITLE
UMS java64 start check does not support openjdk registries 

### ISSUE THREAD

**Issue by fazleskhan** [UniversalMediaServer/UniversalMediaServer#1646]
When running UMS with openjdk on Windows the application only checks for registry entries created by Oracle's jdk.

This issue is related to 
 
https://bugs.openjdk.java.net/browse/JDK-8187906

The fix is to manually add the following Windows registry keys.

```
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JRE@CurrentVersion=<my.version> 
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JRE\<my.version>@JavaHome=<my.version.path>
```

this issue is related to https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1414

**Comment by SubJunk** [comment]
Thanks for the details @fazleskhan I think this is the same as https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1516 can you please add to that?

**Comment by SubJunk** [comment]
I'm closing this a duplicate, but if you think it is different please let us know
