### ISSUE TITLE
Document the use of ZenHub

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1649]
I don't intend to enforce the use of it but I have started to use it to help me keep better track of issues and their related Pull Requests. I should document it in a readme so that contributors can choose to use it too if they want to.

**Comment by VaiTon** [comment]
Why not use GitHub Projects?

**Comment by SubJunk** [comment]
When this issue was made, in 2018, GitHub projects were much more basic than they are now. We can look into changing. Our use of ZenHub isn't consistent anyway, it is mostly just used by me to keep track of things I'm working on. If our development team were to grow I would be more interested in using one of these tools properly

**Comment by valib** [comment]
@SubJunk I created the GitHub project to try this to track the issues and PR. We can try it.
