### ISSUE TITLE
Thumbnail is not updated to the database if TRACE logging not enabled.

### ISSUE THREAD

**Issue by mcduck76** [UniversalMediaServer/UniversalMediaServer#1655]
Seems like an obvious bug, line 95 database/Thumbnails.java:
The closing bracket in the if (trace) condition is including the updateThumbnailId call.

**Comment by mcduck76** [comment]
if (trace) {
							LOGGER.trace("Found existing file entry with ID {} in " + TABLE_NAME + ", setting the THUMBID in the FILES table", result.getInt("ID"));

							// Write the existing thumbnail ID to the FILES table
							PMS.get().getDatabase().updateThumbnailId(fullPathToFile, result.getInt("ID"));
						}

**Comment by valib** [comment]
@mcduck76 thanks for input.  Fixed in #1656

**Comment by SubJunk** [comment]
@mcduck76 thanks!
