### ISSUE TITLE
Can't add to playlist via web interface

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1659]
@acanive the recent work you did has caused the "Add to playlist" button on the right of media titles to have a flickering effect as it switches between two links, can you please look into it?

**Comment by acanive** [comment]
solved in https://github.com/acanive/UniversalMediaServer/commit/887023a487bf41f62749a53e4964b498fb46334c

**Comment by SubJunk** [comment]
@acanive thanks for the fast work, will test soon
