### ISSUE TITLE
No files on Samsung TVs

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1676]
@drakulis this might be related to your Samsung resuming contribution, are you interested in looking into it? We have two reports on the forum that look like they might be describing the same thing, the second one has a debug log.

https://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=13037#p37899
https://www.universalmediaserver.com/forum/viewtopic.php?p=37900#p37892

**Comment by drakulis** [comment]
The only thing I've noticed in the log which may cause such issue is a `X_GetFeatureList` request which cause error in the UMS:
```
POST //upnp/control/content_directory HTTP/1.1

HEADER:
  Accept: */*
  User-Agent: SEC_HHP_[TV]UE32EH5307/1.0 DLNADOC/1.50
  Host: 192.168.2.100:5001
  SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#X_GetFeatureList"
  CONTENT-TYPE: text/xml; charset="utf-8"
  Content-Length: 291
  Connection: close

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:X_GetFeatureList xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"/>
    </s:Body>
</s:Envelope>

DEBUG 2018-11-17 10:52:19.931 [HTTPv2 Request Worker 3] net.pms.network.RequestHandlerV2 Invalid action in SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#X_GetFeatureList"
TRACE 2018-11-17 10:52:19.931 [HTTPv2 Request Worker 3] net.pms.network.RequestV2 Stripping preceding slash from: /upnp/control/content_directory
TRACE 2018-11-17 10:52:19.944 [HTTPv2 Request Worker 3] net.pms.network.RequestV2 Response sent to [TV]UE32EH5307 [Samsung E+ Series]:

HEADER:
  HTTP/1.1 500 Internal Server Error
  Content-Type: text/xml; charset="utf-8"
  Server: Windows_7-amd64-6.1, UPnP/1.0 DLNADOC/1.50, UMS/7.6.0
  Content-Length: 448

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <s:Fault>
            <faultCode>s:Client</faultCode>
            <faultString>UPnPError</faultString>
            <detail>
                <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
                    <errorCode>401</errorCode>
                    <errorDescription>Invalid Action</errorDescription>
                </UPnPError>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```
As I see it is also Samsung specific request. It is possible that now, when UMS is registered as a `AllShare` service some Samsung devices need it. I've tested it on my old (2012) D-serie model and it is running fine. 
I will look on it todays evening and prepare patch for this request. We'll see if it help.

**Comment by drakulis** [comment]
Could be related: https://sourceforge.net/p/minidlna/bugs/311/

**Comment by pipin77** [comment]
I had this problem only on my Samsung UE48H6600

On my Samsung UE32 F4580SS all files were shown instantly.

**Comment by drakulis** [comment]
yeap. I think I just fixed it but I just have D-serie Samsung TV where this issue doesn't occure.

@pipin77 could you please test it on your TV?

Could anybody else could test it on other models E, F, G, H, I, J models?

Volunteers please proceed accordingly:
- stop the server
- backup your current `ums.jar`
- download new `ums.jar` from https://mega.nz/#!YnpkDCQY!JmrhYWOOHZYaT12UO5WgCR92JPCF-XBE1_i9c9KTw3A
- start the server
- check your Samsung TV if all files are in place
- change content type in your TV to Video / Audio / Picture and verify if everything is OK

If it is still broken then:
- stop the server
- restore `ums.jar`
- start the server

Please send share feedback here.

**Comment by pipin77** [comment]
Ok, here my testings for Samsung UE32 F4580SS Samsung UE48 H6600, both acted accordingly

server restart;
TV content type video, no files and folders are shown
TV content type all, files and folders are shown, 
TV content type video, still no files and folders,
TV back to content type all and playing one video,
TV content type video, all files and folders are shown
after restarting the server same problem again.

After downloading the new ums.jar the problem was gone on both TVs.

**Comment by drakulis** [comment]
Great! Thx pipin77.

@SubJunk PR is ready to merge. I suggest to create bugfix release ASAP while it may affect many users.

**Comment by pipin77** [comment]
No problem, thanks to you.
Great that some new developers are contributing to my favorite media player.

**Comment by SubJunk** [comment]
@drakulis thanks for the fast work, I will release as soon as possible :) Feel free to post the patched ums.jar on the forum in the meantime
