### ISSUE TITLE
Fully played video thumbnails no longer working in 7.6.0

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1677]
Reported on the forum. I haven't looked into it but a hunch is that it could have been the fix to storing thumbnails in the database that broke this. Needs reproducing.

**Comment by pipin77** [comment]
Its still working.
But if you restart the server, the fully played markings are gone!

**Comment by SubJunk** [comment]
I have identified that this bug was introduced in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1631
Looking into it further

**Comment by SubJunk** [comment]
@pipin77 that's both of the bugs you reported fixed, thanks for the help :)
