### ISSUE TITLE
Make a copyright-free video testing suite

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1679]
We should have a video testing suite with lots of variations of containers, codecs and subtitles formats, and it should use non-copyrighted material.

Related to https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1665

**Comment by stasinos** [comment]
@SubJunk  have a look at https://github.com/stasinos/ums_testcases
This has all 2-channel combinations from in UMS test cases, and can be freely copied to the UMS SVM repository.
