### ISSUE TITLE
net.pms.network.RequestHandlerV2 Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by itvator** [UniversalMediaServer/UniversalMediaServer#1703]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.
    
##  Thank you for your participation
[](url)

**Comment by itvator** [comment]
repeats every 20 mins or so

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2637080/ums_dbg.zip)

**Comment by amb-jarek** [comment]
@itvator Did you observe any bad behaviour on your device? Does movie didn't play or has been suddenly stopped? Anything else?

AFAIK it is common error - nothing wrong with it. It could appear eg, when TV is loading image and you choose to load next one (while previous is still loading). In such case TV may terminate connection and then such error may appear on UMS side. There are numerous cases when it may occur but as long as everything is working fine you may ignore it.

**Comment by drakulis** [comment]
@itvator Did you observe any bad behaviour on your device? Does movie didn't play or has been suddenly stopped? Anything else?

AFAIK it is common error - nothing wrong with it. It could appear eg, when TV is loading image and you choose to load next one (while previous is still loading). In such case TV may terminate connection and then such error may appear on UMS side. There are numerous cases when it may occur but as long as everything is working fine you may ignore it.

**Comment by SubJunk** [comment]
I think this is fixed now, please reopen if not
