### ISSUE TITLE
MEDIA LIBRARY FAILS TO POPULATE

### ISSUE THREAD

**Issue by S7T2V1oYMoKoqQPl9McG** [UniversalMediaServer/UniversalMediaServer#1710]
SYMPTOM
MEDIA LIBRARY FAILS TO POPULATE 
for MP3 and OGG file types

PROBLEM
My original music library was MP3 format and the Media Library function worked as expected. 
I moved the MP3 files to another folder, converted them to OGG, and placed the OGG files in the original folder. 
I can see the files in UMS listed under the folder, however the Media Library fails to populate with tags. 
I gathered Trace Logs at this point.  
I then added the MP3 folder to UMS shared folders and scanned, yet the Media Library fails to populate.  
The problem is not specific to the file type.  

In the log file we see...
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2] Output #0, image2, to 'pipe:':
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2] Output file #0 does not contain any stream
Then 10 seconds later...
DEBUG 2018-12-07 21:21:39.190 [FFmpeg Thumbnail Failsafe] Stopping process: ffmpeg64.exe-19874

A more complete bug log is below. 
This exact sequence repeats for each .OGG file. 
The trace files will be attached. 

INFO  2018-12-07 20:17:51.084 [main] Starting Universal Media Server 7.6.2
INFO  2018-12-07 20:17:51.087 [main] Build: 2392f22e3 (2018-11-22)
INFO  2018-12-07 20:17:51.087 [main] Java: Java HotSpot(TM) 64-Bit Server VM 1.8.0_191 (64-bit) by Oracle Corporation
INFO  2018-12-07 20:17:51.118 [main] OS: Windows 10 64-bit 10.0
INFO  2018-12-07 20:17:51.322 [main] Maximum JVM Memory: 1.8 GiB

DEBUG 2018-12-07 21:21:29.180 [Library Scanner] Scanning folder: Cafe de Paris
DEBUG 2018-12-07 21:21:29.189 [Library Scanner] Starting "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe" -ss 4 -i "G:\Users\public\music\Various Artists\Cafe de Paris\1-12 Maurice Chevalier - Louise.ogg" -an -dn -sn -vf scale=320:-2 -vframes 1 -f image2 pipe:
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2] ffmpeg version N-80363-g403a53c Copyright (c) 2000-2016 the FFmpeg developers
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   built with gcc 5.4.0 (GCC)
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libavutil      55. 24.100 / 55. 24.100
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libavcodec     57. 46.100 / 57. 46.100
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libavformat    57. 38.100 / 57. 38.100
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libavdevice    57.  0.101 / 57.  0.101
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libavfilter     6. 46.101 /  6. 46.101
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libswscale      4.  1.100 /  4.  1.100
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libswresample   2.  1.100 /  2.  1.100
DEBUG 2018-12-07 21:21:29.316 [ffmpeg64.exe-19874-2]   libpostproc    54.  0.100 / 54.  0.100
DEBUG 2018-12-07 21:21:29.336 [ffmpeg64.exe-19874-2] [ogg @ 00000000001b7260] 3607 bytes of comment header remain
DEBUG 2018-12-07 21:21:29.353 [ffmpeg64.exe-19874-2] Input #0, ogg, from 'G:\Users\public\music\Various Artists\Cafe de Paris\1-12 Maurice Chevalier - Louise.ogg':
DEBUG 2018-12-07 21:21:29.353 [ffmpeg64.exe-19874-2]   Duration: 00:03:22.89, start: 0.000000, bitrate: 102 kb/s
DEBUG 2018-12-07 21:21:29.353 [ffmpeg64.exe-19874-2]     Stream #0:0(eng): Audio: vorbis, 44100 Hz, stereo, fltp, 160 kb/s
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]     Metadata:
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_RELEASEGROUPID: 2758d885-c32e-4b75-9202-ea78aec75772
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ORIGINALDATE    : 2010-06-21
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ORIGINALYEAR    : 2010
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       RELEASETYPE     : album;compilation
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_ALBUMID: 8587fee2-4498-4150-9a22-f4b594026a94
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ASIN            : B003JCTIUO
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       BARCODE         : 698458651921
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       RELEASESTATUS   : official
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ALBUM           : Cafe de Paris
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       RELEASECOUNTRY  : GB
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_ALBUMARTISTID: 89ad4ac3-39f7-470e-963a-56509c546377
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       album_artist    : Various Artists
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ALBUMARTISTSORT : Various Artists
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       SCRIPT          : Latn
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       DATE            : 2010
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       LABEL           : Metro Tins
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       CATALOGNUMBER   : METRTN019
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       TOTALDISCS      : 3
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       TOTALTRACKS     : 20
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       disc            : 1
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MEDIA           : CD
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_TRACKID: a715fc54-a366-4a7d-8578-ad75cf6de076
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_WORKID: 177d96f9-eee8-3458-8028-2e777765f11f
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       LANGUAGE        : eng
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       WORK            : Louise
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       COMPOSER        : Richard A. Whiting
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       COMPOSERSORT    : Whiting, Richard A.
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       LYRICIST        : Leo Robin
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       TITLE           : Louise
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_ARTISTID: e0371cd0-a5f8-420e-be17-bd980adc7393
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ARTIST          : Maurice Chevalier
DEBUG 2018-12-07 21:21:29.354 [ffmpeg64.exe-19874-2]       ARTISTSORT      : Chevalier, Maurice
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       ARTISTS         : Maurice Chevalier
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       MUSICBRAINZ_RELEASETRACKID: a693fb17-e9ff-471b-83dd-2f967423fea9
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       track           : 12
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       COMPILATION     : 1
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       GENRE           : Mes Chansons;Chanson;Paris;1920S;20S;Oldies;Sooz French;Songs Named After A Girl;French;Twenties;Great French Music;Cabaret;Fip;Chanson Francaise;Robert Soft
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       ACOUSTID_ID     : 8ebf340e-f546-4e92-8535-3694485328cf
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       TRACKTOTAL      : 20
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2]       DISCTOTAL       : 3
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2] Output #0, image2, to 'pipe:':
DEBUG 2018-12-07 21:21:29.355 [ffmpeg64.exe-19874-2] Output file #0 does not contain any stream
DEBUG 2018-12-07 21:21:39.190 [FFmpeg Thumbnail Failsafe] Stopping process: ffmpeg64.exe-19874

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2660181/ums_dbg.zip)

**Comment by S7T2V1oYMoKoqQPl9McG** [comment]
I tried uninstalling UMS and using earlier version 7.5.0 and 7.6.0 and the log showed the same "Output file #0 does not contains any stream"

I tried substituting 
"C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe"
ffmpeg version N-80363-g403a53c   
with a the latest version 
ffmpeg version N-92657-ga271025215
from
site:www.ffmpeg.org

The results were unchanged. 

I know this worked in some previous version.

**Comment by valib** [comment]
@S7T2V1oYMoKoqQPl9McG the problem is that extension .ogg is the same for video and audio files. Seems that UMS is treated OGG audio files like video and tries to extract thumbnail from video stream which of course does not exists. Which is a bug, 
But you sent only part of the log. Please send it all to see how are treated those files by your rendererers. Are that OGG audio files played on your renderers?

**Comment by S7T2V1oYMoKoqQPl9McG** [comment]
I CONFIRM that the files are (mis)indexed in the Media Library as videos.  
No, the OGG files didn't play properly. 
Thank you for the workaround suggestion. I will rename and investigate my files. 
I think you can close this as NOT A BUG.

**Comment by S7T2V1oYMoKoqQPl9McG** [comment]
The workaround is to rename .OGG files to .OGA

**Comment by SubJunk** [comment]
Thanks @S7T2V1oYMoKoqQPl9McG I have created a related issue for this since I think we can be more clever about it https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1715
