### ISSUE TITLE
Dynamic view broken on web interface

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1719]
The dynamic view looks broken after the new changes:

![image](https://user-images.githubusercontent.com/584228/49977392-1153df80-ffab-11e8-9f5f-2d4a59c496b9.png)

**Comment by acanive** [comment]
this is ready too. uploading tomorrow.

**Comment by acanive** [comment]
@SubJunk UMS is cool to have!
