### ISSUE TITLE
TED talks doesn't play from Web folder on v7.6.2

### ISSUE THREAD

**Issue by paulene-c** [UniversalMediaServer/UniversalMediaServer#1723]
Replication steps:
Open Web > TED folder
Select any video
None work.

Noticed that in the TRANSCODE folder there is no FFmpeg option even though that displays as the enabled top entry on the Transcoding settings for Web Video Streaming Engines.

FFmpeg is in the TRANSCODE folder in 7.5.0 which the user reports works correctly.

[ums_dbg_TED.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2683171/ums_dbg_TED.zip)

Reported at https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=13165&p=38274&hilit=TED#p38274

That user's logs:
[UMS Ver 7.6.2 ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2683173/UMS.Ver.7.6.2.ums_dbg.zip)
[UMS Ver 7.5.0 ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2683174/UMS.Ver.7.5.0.ums_dbg.zip)

**Comment by SubJunk** [comment]
I have confirmed this problem, it was created in 30d7c08
