### ISSUE TITLE
warning ! Trojan detected on standalone x64 media server setup (fossub.com)

### ISSUE THREAD

**Issue by stepfr64** [UniversalMediaServer/UniversalMediaServer#1733]
Could not test the SHA value because it has been deleted by my antivirus software (microsoft defender):

webfile: E:\step\Downloads\UMS-7.7.0-standalone-x64.exe|https://download.fosshub.com/Protected/expiretime=1545479473;badurl=aHR0cHM6Ly93d3cuZm9zc2h1Yi5jb20vVW5pdmVyc2FsLU1lZGlhLVNlcnZlci5odG1s/d337e066638091c211cf377859d684e82cef397bf6f45923d981f8a6e2a634da/5b8f92b959eee027c3d78b18/5c1c41599b3b1b0a4c263e5a/UMS-7.7.0-standalone-x64.exe|pid:13924,ProcessStart:131899030789063844

Trojan:Win32/Cloxer.D!cl detected !

The UMS-7.7.0.exe full setup seems to be clean however.

A full test on the setup of this release seems mandatory !

**Comment by SubJunk** [comment]
https://www.virustotal.com/#/file/25f5ecc9be6448ea1eeb71515438a46ebee31775b8af58a8339f2d3cb3dd3350/detection

**Comment by SubJunk** [comment]
I downloaded the file from fosshub just to be sure they didn't change the file, then uploaded it to virustotal.com and it is clean. Windows Defender has had a false positive with us before too
