### ISSUE TITLE
8.0.0-a1 release in GitHub not marked as a pre-release

### ISSUE THREAD

**Issue by mbentley** [UniversalMediaServer/UniversalMediaServer#1734]
Would it be possible to re-mark 8.0.0-a1 as a pre-release?  I'm assuming it means alpha 1.  I have some automatic builds going on to build and distribute UMS as Docker containers and it is picking up the release as GA ready.

Thanks!

**Comment by SubJunk** [comment]
@mbentley that's my mistake, sorry about that! I corrected it now
