### ISSUE TITLE
Performance improvement proposal: skip thumbnail extraction for audio files

### ISSUE THREAD

**Issue by felsen2011** [UniversalMediaServer/UniversalMediaServer#1744]
Currently the library scanner starts a mencoder or ffmpeg instance for every media file scanned.

For audio only files this is bound to fail.

For known audio only filetypes such as mp3, oga, flac, wav, mpc ... this step could be omitted resulting in a performance increase during library scans of audio or mixed collections.

**Comment by valib** [comment]
@felsen2011 the library scanner works in the backgroud and doesn't prevent the renderer browsing. It a little bit slows down the standard browsing but without extracting thumbnails it has no meaning. It should speeds up browsing when the database is enabled and library scanning finished.

**Comment by SubJunk** [comment]
> For audio only files this is bound to fail.

Why would it fail? We extract the cover art

**Comment by felsen2011** [comment]
@SubJunk There is no video stream in audio files so it fails.

@valib it causes a lot of system load on my small arm server system and UMS is not the only service I have running on that. Also I have to regularly restart UMS because the communication between UMS and my TV stops working after some time ( I didn't have time to look into this and it will cause massive amount of logging data to do so when TRACE messages are switched on), so it is unfortunately not a one time event.

Of course you can argue that this is an issue that not many ppl are concerned with but from an engineering standpoint its also quite ugly to invest so many ressources in something that you know beforehand that it will fail ;)

**Comment by felsen2011** [comment]
To be clear, this is what I am talking about (log extract from UMS 7.7.1):

DEBUG 2019-01-06 07:49:06.046 [Library Scanner] Starting /usr/bin/mplayer -ss 9 -quiet "[..] Lullaby.ogg" -msglevel all=4 -vf scale=320:-2 -frames 1 -vo jpeg:outdir=mplayer_thumbs:subdirs="8725622" -nosound
DEBUG 2019-01-06 07:49:06.048 [Library Scanner] Unix process ID (/usr/bin/mplayer): 20394
DEBUG 2019-01-06 07:49:06.429 [mplayer-10-2] No stream found.
DEBUG 2019-01-06 07:49:06.436 [MPlayer Thumbnail Failsafe] Stopping Unix process 20394: mplayer-10

**Comment by Nadahar** [comment]
@felsen2011 I case you didn't know, you can configure UMS to send the logs to a remote Syslog server if you don't have the space/don't want to wear out your SD card on the local device.

**Comment by felsen2011** [comment]
@Nadahar you are right, apparently I though *.oga when reading *.ogg and I can't produce it for mp3 containing folders, these are all handled via MusicBrain so UMS already contains the feature I was proposing.

Sorry for wasteing your time :/
