### ISSUE TITLE
Errors / Not playing most of files

### ISSUE THREAD

**Issue by MarlonMrN** [UniversalMediaServer/UniversalMediaServer#1746]
Hello, I'm a long time ums user, but since I started with deepin, I can't get it to work properly. 

Using my samsung eh5300 tv, it tries to load the file but I got an error (file not supported or so, can't do it right now beacause i'm not at home)

Trying to use it with chrome (for playback), the file never loads, I can only see a thumbnail as a background of the player, the the circle never stop spinning.

I've changed my openjdk version from 11 to 8, deleted config files, tried to install all dependencies i've heard and nothing seems to fix the problem. 

At the chrome playback attempt, I've got those errors at the log:

`
23:58:41 INFO  Started playing how.i.met.your.mother.s03e01.720p.hdtv.x264-ctu.mkv on your Chrome
23:58:41 INFO  Exception in thread "Thread-290" java.lang.NullPointerException
23:58:41 INFO  	at net.pms.remote.RemoteUtil$1.run(RemoteUtil.java:100)
23:58:41 INFO  	at java.lang.Thread.run(Thread.java:748)
23:58:46 INFO  Exception in thread "Thread-291" java.lang.NullPointerException
23:58:46 INFO  	at net.pms.remote.RemoteUtil$1.run(RemoteUtil.java:100)
23:58:46 INFO  	at java.lang.Thread.run(Thread.java:748)
23:58:51 WARN  Sending kill -14 to the Unix process: 23569
`

What are those errors? 

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2731192/ums_dbg.zip)
Attached the entire log. (I don't have a WEB.conf for some reason)

**Comment by MarlonMrN** [comment]
well, I just solved the problem. 
It is something related to the ffmpeg (the one that comes along with ums) not propely rendering subtitles. 

Solved by deleting ffmpeg and ffmpeg64 folders under ??/ums-version/linux/ directory.
And installing ffmpeg in my computer

I also installed openjfx, but I have no idea of what it is and don't know if it is required

**Comment by SubJunk** [comment]
@MarlonMrN which version of FFmpeg did you use?

**Comment by MarlonMrN** [comment]
Also, I was having problems with the video timing, which stucked at 0:00:00 and was impossible to fast-forward, fixed by disabling transcode
