### ISSUE TITLE
Adding a Roku 4 Renderer

### ISSUE THREAD

**Issue by TahomaSoft** [UniversalMediaServer/UniversalMediaServer#1752]
# Some Roku 4 Renderer Code
I would like to contribute this little bit of rendering code for a Roku 4, but couldn't find the area in the UMS git repo for renderers.  So adding it here for now.

    
### Roku-4640x.conf ###

#----------------------------------------------------------------------------
# Profile for Roku 3 running Network Streaming Player 6-7.
# See DefaultRenderer.conf for descriptions of all the available options.
# Conf from http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=1563
#
# Hacked version for Roku 4640X (Identifies as Roku/4400X)
# Erik Beck, sept. 19, 2018

RendererName = Roku 4 (NSP 6-7)
RendererIcon = roku-roku3.png

# ============================================================================
# This renderer has sent the following string/s:
#
# User-Agent: Roku/DVP-6.x
#
# Actually  User-Agent: Roku/4400X
# ============================================================================
#

UserAgentSearch = Roku/4400X|Roku/4640X

TranscodeVideo = MPEGTS-H264-AAC
TranscodeAudio = MP3
MaxVideoBitrateMbps = 32
CustomFFmpegOptions = -x264opts cabac=1 -ac 2
CustomMencoderOptions = -channels 2
HalveBitrate = true
MediaInfo = true

# Supported video formats:
Supported = f:mpegts   v:h264   a:aac-lc|lpcm|mp2|mp3   n:2   m:video/vnd.dlna.mpeg-tts

# Supported audio formats:
Supported = f:m4a    m:audio/x-m4a
Supported = f:flac   m:audio/x-flac
Supported = f:mp3    m:audio/mpeg
Supported = f:wav    m:audio/wav
Supported = f:wma    m:audio/x-ms-wma

**Comment by TahomaSoft** [comment]
[Roku-4640x.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2767088/Roku-4640x.conf.txt)

**Comment by atamariya** [comment]
Renderers are defined in following location:
``
UniversalMediaServer/src/main/external-resources/renderers/
``

**Comment by TahomaSoft** [comment]
Thanks.
Just created a fork.

**Comment by valib** [comment]
@jsilverYVR you can add it to the current version.
