### ISSUE TITLE
8.0.0-b1 stops sending file icons after a while

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1761]
When thumbs creation is disabled, only white icons with extension labels (mkv, mpg, ...) are shown.

These default icons are not sent after a while, so the client does not show any icon. The first time you run the server, icons work ok, and rebooting it solves it. 

The bug happens only (or especially) if the folder was shown before (so icons were sent at least once). Sometimes you have to turn the TV off 3-4 times and try to read the same folder to reproduce the bug.

Thanks.

**Comment by valib** [comment]
@444nonymous we need the log to see if the TV is asking for thumbnails.

**Comment by SubJunk** [comment]
@444nonymous this is a bug I get too, but it is connected to that folder no longer being available (because we cleared the global ID to free memory). Are you still able to go into those folders?

**Comment by 444nonymous** [comment]
@SubJunk 

Sure, everithing works fine and I can play the files.

Log files (zip is rar)

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2871548/ums_dbg.zip)

**Comment by SubJunk** [comment]
@444nonymous in those logs can you let me know which thumbnails didn't load? (or new logs if you can't remember)
Also if you can let me know one that succeeded in the same logs that will make it easier to see what's wrong

**Comment by 444nonymous** [comment]
This is what I did and logged.

1. I run UMS (files are already indexed in the db)
2. I enter folder "Movies" (icons are shown)
3. I turn off and on again the TV (UMS still running)
4. I enter folder "Movies" (no icons are shown)

**Comment by 444nonymous** [comment]
@SubJunk

IE: There is a movie called "Anon (2018).mkv" in the folder "Movies".

I see 2 times: "GET /get/60/thumbnail0000PNG_LRG_Anon+%282018%29.mkv.png HTTP/1.1"

Because I entered the folder twice. Only the first time icons are shown.

Now, is the server response exactly the same the 2 times? I'm not sure, I can't understand that part.

**Comment by SubJunk** [comment]
I think this is fixed now, please reopen if not
