### ISSUE TITLE
No active moderator on Linux support forum?

### ISSUE THREAD

**Issue by al3xxx** [UniversalMediaServer/UniversalMediaServer#1770]
Hello,

I've started new topic about 3 days ago and it still doesn't show - not approved.

On topic - Is there a way to get more log verbosity then trace? I'm getting segfault on start about 20 sec after GUI show and nothing in the log that can give any idea on whats wrong.
(tried 3 different JRE - 7 oracle, 8 oracle, 8 openjdk, 10 openjdk)

[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2945910/debug.log)

**Comment by atamariya** [comment]
What's the output of following command?
`/usr/bin/tsmuxer -v`

**Comment by al3xxx** [comment]
`Network Optix tsMuxeR.  Version 2.6.11. www.networkoptix.com`

I tried with AUR tsmuxer as well as with bundled tsmuxer binaries - same outcome.

**Comment by SubJunk** [comment]
We are including new tsMuxeR builds now, so hopefully this is fixed. Feel free to reopen if not
