### ISSUE TITLE
Compilation errors on MS Windows 10

### ISSUE THREAD

**Issue by msaqib** [UniversalMediaServer/UniversalMediaServer#1782]
Hi
I followed the instructions on [this page](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/BUILD
) to build UMS on Microsoft Windows 10. I have javac version 11.0.2 and maven version 3.6.0 on Windows 10 x64. All went well until I gave the command "mvn package". I got the following compilation errors:

`[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[670,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[676,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[682,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/io/OutputConsumer.java:[35,9] method does not override or implement a method from a supertype
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20:31 min
[INFO] Finished at: 2019-04-02T19:30:48+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project ums: Compilation failure: Compilation failure:
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[670,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[676,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/newgui/SharedContentTab.java:[682,86] incompatible types: java.util.Vector<java.util.Vector> cannot be converted to java.util.Vector<java.util.Vector<?>>
[ERROR] /C:/Users/saqib/universalmediaserver/src/main/java/net/pms/io/OutputConsumer.java:[35,9] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

Any clues?
Thanks and regards
Saqib

**Comment by valib** [comment]
@msaqib The UMS code is compatible with Java 7 and 8. @Nadahar described problems with the new Java versions several time here in other topics.

**Comment by msaqib** [comment]
Oh, sorry about that. I searched the forum using the wrong keywords, I guess. 
Thanks so much.

**Comment by Nadahar** [comment]
I'd like to add that although I've explained the problems with Java > 8 multiple times, you shouldn't expect users to know this. For most people the expectation is that the latest versions of software is the "best", and many people aren't aware of Oracle's cynical games to extort money from those that rely on them. At the very least I think you should update the Wiki and state what JDK's can be used. That said, I thought that you had removed the JGoodies stuff that was incompatible with Java 9+..?

The above compilation error doesn't seem like a Java version issue to me, it's complaining about type safety/generics. Has more recent Java versions started to enforce type mismatches that used to only be a warning? If so, it could explain it, but except for that I don't quite see why Java 11 would cause this particular error.

My initial thought would be to make sure that the Maven build folder didn't contain partially built classes that wasn't up-to-date with the currently checked-out code, so I would recommend running `mvn clean package` to make sure that's not the issue.

**Comment by valib** [comment]
@Nadahar thanks for the comment. I updated the Wiki in the Windows part to recommend to use the Java 8.

**Comment by SubJunk** [comment]
Also updated https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/BUILD.md#1-download-and-install-the-java-8-jdk

**Comment by valib** [comment]
And I updated Wiki accordingly.
