### ISSUE TITLE
virtual_folders can't handle multiple parameters

### ISSUE THREAD

**Issue by begleysm** [UniversalMediaServer/UniversalMediaServer#1788]
I am admittedly very new to UMS but I believe I've found a bug.

I am attempting to implement two virtual folders.  The UMS.conf file says that the format should be:
`VFolderName1|Folder1Path,Folder2Path;VFolderName2|Folder1Path`

The line in my UMS.conf is:
`virtual_folders = TV\\ Shows|/mnt/media/Video/TV_Shows;Web\\ Shows|/mnt/media/Video/Web_Shows`

After saving UMS.conf and restarting UMS the websever is unavailable.  Checking debug.log shows the following:
```
DEBUG 2019-04-08 21:14:36.570 [main] Reading virtual_folders: "TV\ Shows|/mnt/media/Video/TV_Shows;Web\ Shows|/mnt/media/Video/Web_Shows" (default: "")
WARN  2019-04-08 21:14:36.620 [main] Folder not found: File "/mnt/media/Video/TV_Shows;Web\ Shows" not found
ERROR 2019-04-08 21:14:36.620 [main] A serious error occurred during Universal Media Server initialization: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 75 path $
DEBUG 2019-04-08 21:14:36.622 [main]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 75 path $
        at com.google.gson.Gson.assertFullConsumption(Gson.java:864)
        at com.google.gson.Gson.fromJson(Gson.java:854)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at net.pms.configuration.MapFileConfiguration.parseVirtualFolders(MapFileConfiguration.java:118)
        at net.pms.dlna.RootFolder.getVirtualFolders(RootFolder.java:477)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:195)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:117)
        at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:507)
        at net.pms.PMS.getRootFolder(PMS.java:159)
        at net.pms.PMS.init(PMS.java:659)
        at net.pms.PMS.createInstance(PMS.java:900)
        at net.pms.PMS.main(PMS.java:1070)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 75 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.Gson.assertFullConsumption(Gson.java:860)
        ... 11 common frames omitted
DEBUG 2019-04-08 21:14:36.839 [pool-1-thread-4] root req /
``` 

Take special notice of this line showing that the "folder" path is including the semi-colon and name of the 2nd virtual folder.
`WARN  2019-04-08 21:14:36.620 [main] Folder not found: File "/mnt/media/Video/TV_Shows;Web\ Shows" not found`

It appears as though the two instances of virtual folders are not being properly delimited by the semicolon characters.

**Comment by ExSport** [comment]
```
VFolderName1|Folder1Path,Folder2Path;VFolderName2|Folder1Path
```
It means:
```
Movies|d:\\media\\tv,d:\\media\video,e:\\movie;Music|f:\\audio,d:\\media\\mp3
```
As the slash is a special character on both Windows and Linux I don't suppose you can use it in the name of virtual folder.
Btw. be prepared that concatenated physical folders into virtual ones are not ordered per settings (alphabetically,...)
You will see them as an independent blocks. I think this "bug" was never fixed from time of first implementation.

**Comment by ExSport** [comment]
I used virtual folders years ago as the is buggy ordering so can't say how it works.
But if I remember right it worked but I never used slashes for virtual names. It is worth a try. Maybe slashes works only in case you will not combine them with ";" or more probably there is a bug as you say 😊

**Comment by valib** [comment]
There is a bug I am working on it. @begleysm you can use VirtualFolders.conf instead.

**Comment by ExSport** [comment]
Yay, now I see. In past I used virtualfolders.conf (json if I remember right) and missed you are doing it via ums.conf. 😇
Sorry for misunderstanding.

**Comment by begleysm** [comment]
Thank you (both) for the follow up.  I briefly tired VirtualFolders.conf without success.  I'll go back and attack that method again.

**Comment by valib** [comment]
@begleysm I agree with @ExSport that using back slashes in the virtual folder name is nonsens. Fortunatelly the code ignores that. In the virtual folder name you cannot define virtual subfolders. The virtual folder name is shown in the root UMS folder and there is no way to define its subs folders which are in fact parsed automatically.

**Comment by SubJunk** [comment]
The fix is merged now and I'm planning the 8.0.2 release either this week or next week which will include it

**Comment by begleysm** [comment]
Awesome!

Regarding the slashes.  I didn't intend no having "slashes" in the virtual folder I wanted a space.  The examples don't show cases with spaces so I guessed and wrote the name as "TV\ Shows" with the intention of getting "TV Shows".

It automagically got changed in the config file to "TV\\ Shows" but ended up displaying correctly as "TV Shows" so I left it alone.

I'll try doing
`virtual_folders = TV Shows|/mnt/media...`
and see what happens.

It would be awesome if the examples (on ur config file comments and in the wiki) showed cases with spaces in the virtual folder name and spaces in the path.

**Comment by begleysm** [comment]
I installed 8.1.0 and can confirm that the fixes applied solved my problem!  Thanks!

Also, in reference to my above comment leaving out all slashes works.  My current config line is

```virtual_folders = TV Shows|/mnt/media/Video/TV_Shows;Web Shows|/mnt/media/Video/Web_Shows```

The above config line creates 2 links on the webpage called "TV Shows" and "Web Shows".

**Comment by SubJunk** [comment]
Thanks for confirming the fix!
