### ISSUE TITLE
Docker image based on alpine breaks the ffmpeg transcoding feature when used with a PS3

### ISSUE THREAD

**Issue by AntoineOulevay** [UniversalMediaServer/UniversalMediaServer#1796]
Hi all,

I've been a very happy ums user for years now, and was very enthusiastic seeing your new version of UMS coming as docker image too.
As my former server broke due to hardware failure, I had to reinstall everything on some new hardware, and thought, why not directly going for this fancy new docker image.

As you mentioned it is not really ready yet, and there are a few issues with it. Maybe I can bring piece of contribution today. Here's a list of the things and issue Iran into, until now:
1. Tried to run several video files that require UMS to transcode it to be played on a PS3, I got this in the log:
```
INFO  11:28:00.839 [HTTPv2 Request Worker 3] Process mkfifo has a return code of 1! Maybe an error occurred... check the log file
ERROR 11:28:01.223 [ffmpeg-103] Error initializing process:
ERROR 11:28:06.345 [HTTPv2 Request Worker 3] There is no inputstream to return for [...]
```
Looking at the debug log, the command explicitely run return the mkfifo help telling that the option used is not recognized:
`DEBUG 2019-05-12 18:25:11.305 [HTTPv2 Request Worker 2] Starting mkfifo --mode=777 /tmp/UMS-root/ffmpegvideo_52_1557685511304`

**It turns out that "mkfifo" from "busybox", used in the alpine image, does not provide the same amount of options than the ones used by UMS or one of it's used libraries. It will only understand the "-m" option, and not --mode as it used currently.**
To work around this one, I rebuilt the docker image but starting from debian:stretch (it most certainly will work with debian:jessie too).

The other possibility could be to replace the "--mode" option by "-m" where it is used in the code (bear with me, I did not go this far in my investigation. So I can't really tell where the mkfifo call is really done).

2. I'm running this image on a Debian stretch system, using the hosts network (--network=host in the docker create/run command). This definitely requires you to add the "docker0" interface to the "**skip_network_interfaces**" list, otherwise your service will always choose the bridge interface for it's communication. But this is not so much an issue, as it is configurable in the app.

Off-topic, here are the reasons I'm running the image that way:
Until today, I had tremendous issues with the network performance using docker's default networking features, especially with databases in my all day job. (and my network bandwidth at home is limited).
A simple run of the Redis benchmark a dockerised redis service, with and without using the host's network, bypassing the docker network layer, gave extensive proof of it (Docker was introducing an additional latency time on every network packet that has to go in or out of your host, to or from your container app, showing a 30% difference in overall response times on the benchmark).
Although this might not be the case anymore with the latest versions of docker, and I will definitely try this performance test again, to make sure I'm not making my life more complicated than it should.

I thought that the day I just spent investigating an understanding how to use this in a container image was worth sharing.

Best Regards
Antoine Oulevay

**Comment by atamariya** [comment]
mkfifo command line is generated in PipeProcess.java . It already has a section for short arguments. May be you just need to add one more.
`
if (Platform.isMac() || Platform.isFreeBSD() || Platform.isSolaris())
`

**Comment by tcely** [comment]
Or you could just install `coreutils` in the Alpine Linux docker image.

**Comment by SubJunk** [comment]
Thanks, merged!
