### ISSUE TITLE
How to force x265 videos to play or transcode into x264 to play on TV, Blu-Ray DVD players, etc..?

### ISSUE THREAD

**Issue by phd21** [UniversalMediaServer/UniversalMediaServer#1797]
Hello UMS developers and maintainers,

Re: How to force x265 videos to play or transcode into x264 to play on TV, Blu-Ray DVD players, etc..?

First, Thank You. I love this media server. It is easy to install and use, and it is free. I recommend it all the time in the Linux Mint forums.

I use Linux Mint Cinnamon 19 and Linux KDE Neon user edition both are 64-bit and based on Ubuntu 18.04 bionic. I also have Java 8 runtime as the default.

I cannot play videos encoded using the x265 codec format on my smart Blu-Ray DVD player or my TV, directly using USB drives or using UMS (Universal Media Server). They play fine on my computer though?

So, I was wondering if UMS has some way of automatically recognizing x265 videos and forcing them or automatically transcoding them into x264 format which always works? 

I have UMS versions 7.0.1, 7.8.01, and 8.1.0 installed and using the v8.1.0. I see an option under Transcoding settings, video tab, misc, transcoding quality h.264, but that does not seem to work for me, what is that supposed to do and how do I use it? FYI: I use a WiFi adapter.

I could manually convert the x265 videos into x264 using various multimedia converters or ffmpeg, but that takes a long time to do.

Thank you for any help you can provide with this.

Best regards,
Phil (phd21)

**Comment by Nadahar** [comment]
UMS is supposed to figure this out automatically. You should make sure that MediaInfo is installed (since UMS uses it to analyze media files) and that the renderer configuration files for your renderers are correctly defined. In particular, you should study the lines starting with `supported` in the renderer configuration files. Any format/codec that is *not* supported should automatically be transcoded.

For anybody to look into why this doesn't happen, you'd have to post your debug files.

**Comment by phd21** [comment]
Hi Nadahar,

Thank you for responding so quickly.

I always have mediainfo and mediainfo-gui installed. 

I have never had to manually create or edit "renderers". I have an older Samsung Blu-Ray DVD player that I stream too which UMS has always correctly displayed as [BD]F5900.

I still cannot play x265 encoded video files - "not supported" or sometimes even disconnects me? 

Interestingly, I went under the Transcode folder for one x265 video and it had options for ffmpeg, mencoder, tsmuxer, vlc, etc... and I tried them all and none worked properly, seemed to have dups because of subtitles.

How do I provide (get) the debug information for you? I attached the "renderer" file for you.

Regards,
Phil (phd21)

**Comment by Nadahar** [comment]
When you created this issue, this text was shown initially:

> # How to contribute
> 
> In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:
> 
>   * Start UMS.
>   * Go to the `Logs` tab.
>   * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
>   * Reproduce the problem.
>   * Click `Pack debug files` on the lower left.
>   * Click `Zip selected files`.
>   * Save the zip file to a location you will remember.
>   * Attach the zip file to the GitHub issue.
>     
> ##  Thank you for your participation
> 

If you don't run the GUI there's another way to do it, which should be explained here as well IMO, but it seems it isn't. Some of the developers will have to give you those instructions.

Without the `trace` log, there's not much more one can do than to speculate, but it could be that your computer simply isn't fast enough to transcode it real-time. x265/HEVC is quite resource intensive even to decode, and also remember that your computer has to reencode it as x264/AVC simultaneously - it might simply not be up for it. If the computer can't do this conversion in at least 1x speed, it will fail.

**Comment by phd21** [comment]
Hi Nadahar,

Okay, here is the log file.

Phil (phd21)
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3175802/ums_dbg.zip)

**Comment by Nadahar** [comment]
I've extracted the command sent to FFmpeg from your log. Simply replace `[output.mpg]` with a path/file name of your choice, and attempt to do the transcode outside UMS. If the speed while transcoding is below 1x, your CPU is too weak.

```powershell
/home/user69/apps/ums-8.1.0/linux/ffmpeg64 -y -loglevel info -i /home/user69/Videos/test/SEAL.Team.S02E21.720p.WEB.x265-MiNX.mkv -bufsize 1835k -maxrate 29000k -g 25 -qmax 5 -qmin 2 -ab 448k -c:a ac3 -c:v mpeg2video -f vob [output.mpg]
```

Your log indicates that this isn't the case though, the initial frames are transcoded at slightly above 3x. I don't quite understand what happens, it seems to start the transcode multiple times before the renderer "gives up" and disconnects. UMS probably sends some incorrect information to the renderer leading it to try again and again before giving up.

You should verify that the file produced by running the above command is playable/valid though (in any regular media player). If the speed is like your log indicates, well about 1x and the output is valid, I'll leave it for the UMS developers to figure out.

**Comment by phd21** [comment]
Hi Nadahar,

Thank you again for your help with this.

I do not understand "Simply replace `[output.mpg]` with a path/file name of your choice, and attempt to do the transcode outside UMS." Path and file name of my choice of what? Where would I put that and what do I have to edit for doing this? 

I noticed with UMS 8 there is a Linux subfolder with versions of ffmpeg from 2007 and tsmuxer programs from 2014? I have newer versions of ffmpeg v4.xx installed and newer tsmuxer apps, does UMS use my system installed versions or the ones included in their subfolder? Should I copy my newer ffmpeg files into that UMS subfolder?

As I already stated before, I can play these x265 files in my various media players on my computer.

Also, if you could please forward this post and its replies to the UMS developers for their review, that would be appreciated as well.

Regards,
Phil (phd21)

**Comment by Nadahar** [comment]
You would have to run the command from a terminal. The output would be where the transcoded file would be created. FFmpeg would then run the transcoding with the same parameters as UMS used, but instead of sending the result to the renderer it would be written to disk. That way you could verify that the resulting video is valid, by trying to play the newly created file.

The old versions of FFmpeg and other "transcoding engines" are there because nobody has taken the time to verify and make sure that newer versions work. If you simply replace them with newer ones, some things will probably work while others will probably break. In an ideal world new versions would always be able to do what older versions did, but that definitely isn't the case with these. In addition there are often changes to syntax and parameters.

As explained above, I wasn't asking if the x265 file was playable, but if the MPEG-2 file generated by FFmpeg is.

The UMS developers are notified of all issues created here, so they simply haven't chosen to answer (yet).

**Comment by phd21** [comment]
Hi Nadahar,

Thanks again for your reply. I now understand.

I ran the command and it plays perfectly creating an "output.mpg" (mpeg2video) video file of 1.3gb from an x265 .mkv video file of 430mb and the speed averaged around 3x with the lowest at 2.8x.

Stream mapping:
Stream #0:0 -> #0:0 (hevc (native) -> mpeg2video (native))
Stream #0:1 -> #0:1 (aac (native) -> ac3 (native))
frame=63046 fps= 70 q=31.0 Lsize= 1347372kB time=00:43:46.97 bitrate=4201.7kbits/s dup=1 drop=0 speed=2.92x    
video:1186378kB audio:143663kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.303059%

FYI-1: I decided to try the same command using my installed ffmpeg v4.1.3 from folder "/usr/bin/" (ffmpeg because I don't see an ffmpeg64 executable file) and it ran at 4x average with lowest at 3.21x. I thought I would get "syntax and parameters" errors because of backward compatibility issues, but it worked.

FYI-2: I did a file find search on my tsmuxer programs and they are from 2013. But, my ffmpeg is new v4.xx.

Regards,
Phil (phd21)

**Comment by Nadahar** [comment]
@phd21 OK, at least now we know that the transcoding it self works fine, which means this must be a bug with UMS.

**Comment by phd21** [comment]
Hi Nadahar,

I do not know if it is a bug in UMS or not, but perhaps there are some settings or changes that UMS developers could do or add to make playing x265 videos work and or work better?

I even copied the newer ffmpeg programs into the UMS Linux sub-folder just to see what happens, and it still did not play the x265 videos and resulted in the same results being disconnected or not supported, but every other video formats still work great so far as they always have before.  When I tried the VLC options under the transcoding folder it showed the video but said the audio codec format not supported? I am using VLC v4.

Thanks again for helping me with this. Have a great day and night...

Regards,
Phil (phd21)

**Comment by SubJunk** [comment]
@phd21 thanks for your kind words about UMS! Can you please try adding the line:

TranscodeVideo = MPEGTS-H264-AC3

into `Samsung-F5900.conf` inside the `renderers` folder in the UMS installation directory, and see if that makes a difference?

**Comment by phd21** [comment]
Hi  SubJunk,

You are welcome. Thank you for replying.

You did not say where to put the "TranscodeVideo = MPEGTS-H264-AC3" in the Samsung-F5900.conf file or does it not matter?

UMS will still not play x265 videos and results are the same being disconnected or stating not supported. Should the line you suggested go somewhere else in the file? I am using the default UMS settings, should any settings be changed and if so which ones?

#----------------------------------------------------------------------------
# Profile for Samsung F5900 Blu-ray Disc Players.
# See DefaultRenderer.conf for descriptions of all the available options.
#

RendererName = Samsung F5900
RendererIcon = samsung-f5900.png

# ============================================================================
# This renderer has sent the following string/s:
#
# User-Agent: SEC_HHP_[BD]F5900/1.0 DLNADOC/1.50
# ============================================================================
#

UserAgentSearch = F5900
UpnpDetailsSearch = F5900
LoadingPriority = 1

DefaultVBVBufSize = true
MuxDTSToMpeg = true
MaxVideoBitrateMbps = 60
SeekByTime = true
ChunkedTransfer = true
SubtitleHttpHeader = CaptionInfo.sec
PrependTrackNumbers = true
CharMap = / :
MediaInfo = true
TranscodeVideo = MPEGTS-H264-AC3

# Supported video formats:
Supported = f:3gp|3g2         v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/3gpp
Supported = f:avi             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/avi
Supported = f:flv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-flv
Supported = f:mkv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-matroska
Supported = f:mov             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/quicktime
Supported = f:mp4             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mp4
Supported = f:mpegps|mpegts   v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mpeg
Supported = f:wmv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-ms-wmv

# Supported audio formats:
Supported = f:m4a    m:audio/x-m4a
Supported = f:ape    m:audio/x-ape
Supported = f:flac   m:audio/flac
Supported = f:mp3    m:audio/mpeg
Supported = f:ogg    m:audio/x-ogg
Supported = f:wav    m:audio/wav
Supported = f:wma    m:audio/x-ms-wma

# Supported subtitles formats:
SupportedExternalSubtitlesFormats = ASS,MICRODVD,SAMI,SUBRIP
SupportedInternalSubtitlesFormats = ASS,SUBRIP

**Comment by SubJunk** [comment]
Where you put it is good. Let's try another change, please replace the contents of the file with this:

```
#----------------------------------------------------------------------------
# Profile for Samsung F5900 Blu-ray Disc Players.
# See DefaultRenderer.conf for descriptions of all the available options.
#

RendererName = Samsung F5900
RendererIcon = samsung-f5900.png

# ============================================================================
# This renderer has sent the following string/s:
#
# User-Agent: SEC_HHP_[BD]F5900/1.0 DLNADOC/1.50
# ============================================================================
#

UserAgentSearch = F5900
UpnpDetailsSearch = F5900
LoadingPriority = 1

DefaultVBVBufSize = true
MuxDTSToMpeg = true
MaxVideoBitrateMbps = 60
SeekByTime = true
ChunkedTransfer = true
SubtitleHttpHeader = CaptionInfo.sec
PrependTrackNumbers = true
CharMap = / :
MediaInfo = true
TranscodeVideo = MPEGTS-H264-AC3

# Supported video formats:
Supported = f:3gp|3g2         v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/3gpp
Supported = f:avi             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/avi
Supported = f:flv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-flv
Supported = f:mkv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-matroska
Supported = f:mov             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/quicktime
Supported = f:mp4             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mp4
Supported = f:mpegps   v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mpeg
Supported = f:mpegts   v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/vnd.dlna.mpeg-tts
Supported = f:wmv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-ms-wmv

# Supported audio formats:
Supported = f:m4a    m:audio/x-m4a
Supported = f:ape    m:audio/x-ape
Supported = f:flac   m:audio/flac
Supported = f:mp3    m:audio/mpeg
Supported = f:ogg    m:audio/x-ogg
Supported = f:wav    m:audio/wav
Supported = f:wma    m:audio/x-ms-wma

# Supported subtitles formats:
SupportedExternalSubtitlesFormats = ASS,MICRODVD,SAMI,SUBRIP
SupportedInternalSubtitlesFormats = ASS,SUBRIP
```

If that doesn't work, please attach a new debug package

**Comment by phd21** [comment]
Hi SubJunk,

Thank you for your quick replies and helping me and others that may have the same issues with x265 videos.

Unfortunately, the recently recommended changes to "Samsung-F5900.conf" did not work and the results are the same. So, I have attached another debug trace zip file for your review. FYI: Whenever I test this, I test in a normal way, and I also go into the "transcode" folder and try every option in that too and the Transcode folder VLC option will play the video but I get a message that the audio codec is not supported therefore no sound, but the subtitle works? FYI: I have pretty much every video and audio codec I could find for Linux installed.

Best regards,
Phil (phd21)
phd21mint@gmail.com

[ums_dbg_2019-05-16.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3188765/ums_dbg_2019-05-16.zip)

**Comment by SubJunk** [comment]
Ah that's interesting that VLC works, that might be an important clue. Please try this one:

```
#----------------------------------------------------------------------------
# Profile for Samsung F5900 Blu-ray Disc Players.
# See DefaultRenderer.conf for descriptions of all the available options.
#

RendererName = Samsung F5900
RendererIcon = samsung-f5900.png

# ============================================================================
# This renderer has sent the following string/s:
#
# User-Agent: SEC_HHP_[BD]F5900/1.0 DLNADOC/1.50
# ============================================================================
#

UserAgentSearch = F5900
UpnpDetailsSearch = F5900
LoadingPriority = 1

DefaultVBVBufSize = true
MuxDTSToMpeg = true
MaxVideoBitrateMbps = 60
SeekByTime = true
ChunkedTransfer = true
SubtitleHttpHeader = CaptionInfo.sec
PrependTrackNumbers = true
CharMap = / :
MediaInfo = true
TranscodeVideo = MPEGTS-H264-AAC

# Supported video formats:
Supported = f:3gp|3g2         v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/3gpp
Supported = f:avi             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/avi
Supported = f:flv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-flv
Supported = f:mkv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-matroska
Supported = f:mov             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/quicktime
Supported = f:mp4             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mp4
Supported = f:mpegps   v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/mpeg
Supported = f:mpegts   v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/vnd.dlna.mpeg-tts
Supported = f:wmv             v:h264|mjpeg|mp4|mpeg1|mpeg2|wmv   a:aac-lc|he-aac|ac3|dts|lpcm|mp3|wma   m:video/x-ms-wmv

# Supported audio formats:
Supported = f:m4a    m:audio/x-m4a
Supported = f:ape    m:audio/x-ape
Supported = f:flac   m:audio/flac
Supported = f:mp3    m:audio/mpeg
Supported = f:ogg    m:audio/x-ogg
Supported = f:wav    m:audio/wav
Supported = f:wma    m:audio/x-ms-wma

# Supported subtitles formats:
SupportedExternalSubtitlesFormats = ASS,MICRODVD,SAMI,SUBRIP
SupportedInternalSubtitlesFormats = ASS,SUBRIP
```

**Comment by phd21** [comment]
Hi SubJunk,

Unfortunately, that last configuration did not work either. Same results.

I am more than willing to test anything you come up with regarding this and or anything else regarding UMS.

Thanks again and regards,
Phil (phd21)

**Comment by SubJunk** [comment]
We have done a lot of fixes since this issue was made. I'm sorry for letting it fall off my radar. If you're still around and interested @phd21 please reply and I'll reopen this and try to help some more.
