### ISSUE TITLE
UMS v8.2 "x86 Windows build" is Java x64-only

### ISSUE THREAD

**Issue by ltGuillaume** [UniversalMediaServer/UniversalMediaServer#1810]
The release of v8.2.0 went wrong. The standalone Windows x86 version is bundled with the x64 version of Java. It also only includes ffmpeg64.exe instead of ffmpeg.exe. When I try to run it using the x86 Java Runtime, it simply does not start.

**Comment by SubJunk** [comment]
This will hopefully be fixed by this work https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1811

**Comment by SubJunk** [comment]
This should be working now in 9.0.0-b2+. Feel free to reopen if not.

**Comment by ltGuillaume** [comment]
Thanks!
