### ISSUE TITLE
Video bit depth can not be configured per codec in renderer conf files.

### ISSUE THREAD

**Issue by bestdark** [UniversalMediaServer/UniversalMediaServer#1818]
Some devices (Samsung Q6 TV in my case), support 10 bit video, but only while using certain codec(HEVC). But currently bit depth is set per device with SupportedVideoBitDepths. I propose to make it an optional parameter for codec description to specify supported bit depths for each codec (eg. "Supported = f:mkv v:h265 a:mp3 m:video/x-mkv b:8|10").

**Comment by valib** [comment]
`b:` is used for the maximum bitrate (bits per second) of the whole file (see the DefaultRenderer.conf) but we can use eg. `bd:`. Anyway it is a good idea.
