### ISSUE TITLE
Subtitles only showing in transcoding

### ISSUE THREAD

**Issue by Weaver23PH** [UniversalMediaServer/UniversalMediaServer#1832]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3585916/ums_dbg.zip)
Subtitles only show if transcoding is chosen and then, only with ffmpeg, but this makes fast-forwarding impossible - the film appears to last 1s and after you press ff it rewinds itself to the start, Live subs don't work either.

**Comment by SubJunk** [comment]
@Weaver23PH thanks for the issue. we have an upcoming version of UMS that rewrites some of the subtitles code and may fix (or break in a different way ;)) this issue, would you be willing to test it?

**Comment by Weaver23PH** [comment]
I have tried v 9.0.0 of UMS today and the problem persists. Downgrading to 7.6.0 solves the issue. I might try any available beta later the upcoming week (it's still Sunday here).

**Comment by pipin77** [comment]
7.6.0 or 7.6.2?

I noticed some subtitle glitches in versions after 7.6.2

**Comment by Weaver23PH** [comment]
It's 7.6.0 here.

**Comment by pipin77** [comment]
Did you try 7.6.2?

Imo its broken after that version. 

I uploaded logs with 7.6.2 and 9.0.0. to the forum:
https://www.universalmediaserver.com/forum/viewtopic.php?f=4&p=40065#p40065

Maybe you can do this too?

**Comment by pipin77** [comment]
> I didn't mean 9.0.0, I meant another branch where there has been some work on subtitles support. It would make sense to put our fix, if needed, on top of that branch. Please verify the bug on https://www.spirton.com/uploads/UMS/UMS-add_subs_to_supported_line-212254b.exe

Url gives an ERR_SSL_PROTOCOL_ERROR

**Comment by SubJunk** [comment]
A server migration is in process and having some hiccups, hopefully it will be back up soon

**Comment by pipin77** [comment]
Downloaded the version. Subtitles work. But for me again only on one of my two samsung tvs

**Comment by SubJunk** [comment]
We have fixed a ton of subtitles bugs so I'm closing this, please open another issue if there are still problems
