### ISSUE TITLE
Forum problems

### ISSUE THREAD

**Issue by pipin77** [UniversalMediaServer/UniversalMediaServer#1833]
Hi,

sorry for creating an issue here, 
but the last release thread  has a wrong timestamp in the forum "Tue Aug 20, 2013" and is therefore not shown on the news site. 

Every reply or pn in the forum gets an error: "You cannot make another post so soon after your last."

**Comment by SubJunk** [comment]
@pipin77 thanks for letting us know, I'm looking into this now

**Comment by SubJunk** [comment]
@pipin77 the server time was incorrect and I have fixed that now, and fixed the date of the announcement topic. Please let me know if you are still getting that error when posting

**Comment by pipin77** [comment]
No more errors at the moment.

**Comment by SubJunk** [comment]
@pipin77 thanks!

I should mention too that there will be a server migration on Monday as we will move to a new data centre. If all goes well there should be no noticeable downtime but if there is I'll post updates on here.

**Comment by pipin77** [comment]
Good luck. We migrated to our own AMD Epyc Webserver last year.
