### ISSUE TITLE
Universal Media Server.lnk remains in startup folder after UMS is uninstalled

### ISSUE THREAD

**Issue by Pentaphon** [UniversalMediaServer/UniversalMediaServer#1838]
I don't need to post a log for this because the issue happens AFTER UMS is uninstalled.

C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Universal Media Server.lnk remains on my system even after UMS is uninstalled.  

It's easy to just delete the .lnk file to get rid of it from startup, but UMS should not leave this in the startup folder after it is uninstalled.

This happens with UMS 9.0.0 on Windows 10 64 bit.

**Comment by SubJunk** [comment]
Reproduced

**Comment by SubJunk** [comment]
@Pentaphon Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1839
Are you interested in testing?

**Comment by Pentaphon** [comment]
I was just trying it out and I didn't really think the software was for me so, no thanks, I'm not interested in testing. I just wanted to report the bug. Glad it's fixed.

**Comment by SubJunk** [comment]
No problem, I have verified the fix anyway. Thanks for reporting it
