### ISSUE TITLE
External plugin fails on Maven 3.6.2

### ISSUE THREAD

**Issue by headius** [UniversalMediaServer/UniversalMediaServer#1842]
As of Maven 3.6.2, there's no default constructor on DefaultSettingsBuilder:

https://github.com/apache/maven/commit/c5ede2fef8b63cd5c75f8bc2f53aeaa75c629adc#diff-8e6fc18c48c40423411e38cb2bdff818

This breaks using your external-maven-plugin on Maven versions 3.6.2 or higher with the following error:

```
[ERROR] ... java.lang.NoSuchMethodError: org.apache.maven.settings.building.DefaultSettingsBuilder: method <init>()V not found
```

I have pushed a PR that fixes the plugin in https://github.com/UniversalMediaServer/external-maven-plugin/pull/2

**Comment by SubJunk** [comment]
@headius thanks for your research and fix :) How can I reproduce this error? I used Maven 3.6.2 to release 9.0.0 and didn't notice an error, or does the build continue after the error?

**Comment by SubJunk** [comment]
@headius I have merged the fix

**Comment by headius** [comment]
@SubJunk Sorry I never replied when you couldn't reproduce it. Seems like that changed and this is in process now. Thanks!
