### ISSUE TITLE
Directory Listing Problem

### ISSUE THREAD

**Issue by Albertatoltec** [UniversalMediaServer/UniversalMediaServer#1843]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

**Comment by Albertatoltec** [comment]
I am willing to submit a full debug file but I wouldn't know which one you would want.  Please read through the testing configurations I am providing in this issue and let me know which one would be the best to provide the debug files for. 

I recently purchased a new Sony television, an XBR-65X900F, which is capable of rendering video from a DLNA server.  I have been trying to get it to work with my copy of UMS 9.0.0 running on a Windows 10 Pro system but have been running into a strange situation in listing the directories/folders and sub-directories.
The UMS is configured for two directories, G: & M:, one containing TV shows and the other containing movies.  Both directories have a number of sub-directories.  In the TV directory, there are directories of various TV show and each TV show has a further sub-directory listing the season.  The Movies directory contains alphabetic sub-directories with corresponding named movies in the sub-directories.
All of the renderers have been removed except for the default Sony-Blu-ray and Sony Bravia XBR renderers that come with UMS.  I should mention that I also have a Sony Blu-ray S770 player as it is part of the testing.  All three devices are located on the same ethernet segment within the same IP address range.
The following is a listing of various configurations I have tried along with the results of each configuration.
Configuration 1:
Only the Sony Bravia XBR renderer config is enabled.  The TV is turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M:.  But when selecting either of the directories/folders to get to the sub-directories, the following error message appears on the TV. “Selected server contains no media content. Please select another server”
Configuration 2:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is not turned on but the TV is turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M:.  But when selecting either of the directories/folders to get to the sub-directories, the following error message appears on the TV. “Selected server contains no media content. Please select another server”
Configuration 3:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is turned on and the UMS is present in the Blu-ray player’s menu.  The TV is turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M:.  But when selecting either of the directories/folders to get to the sub-directories, the following error message appears on the TV. “Selected server contains no media content. Please select another server”
Configuration 4:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is turned on, the UMS is present in the player’s menu and the UMS icon is selected to display the two directories/folders, G: and M:.  The TV is turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M: and now selecting either of the directories/folders to get to the multiple levels of sub-directories displays the sub-directories without any errors.
Configuration 5:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is turned off.  The TV is turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M: and now selecting either of the directories/folders to get to the multiple levels of sub-directories displays the sub-directories without any errors.
Configuration 6:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is still turned off.  The TV is turned off and back on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M: and now selecting either of the directories/folders to get to the multiple levels of sub-directories displays the sub-directories without any errors.
Configuration 7:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is still turned off.  The UMS is restarted through UMS console using the restart button.  The TV is off and then turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M: and now selecting either of the directories/folders to get to the multiple levels of sub-directories displays the sub-directories without any errors.
Configuration 8:
Both the Sony Bravia XBR and Sony Blu-ray renderer configs are enabled.  The Blu-ray player is still turned off.  The UMS is stopped through UMS console using the Quit button and then restarted.  The TV is off and then turned on and the UMS is selected within the TV’s menu option.  The TV displays the two directories/folders, both G: and M: but when selecting either of the directories/folders to get to the sub-directories, the following error message appears on the TV. “Selected server contains no media content. Please select another server”

Please let me know the debug files that corresponds to the configuration listed above.

Cheers,

**Comment by Albertatoltec** [comment]
I never closed the problem.

**Comment by atamariya** [comment]
Leave all the renderer configs intact. Turn on Bravia, navigate G: folder and generate the logs. Similarly, create separate log for bluray. That should do.

**Comment by Albertatoltec** [comment]
atamariya, thanks for responding to my problem.  Enclosed are the two zipped files that you have requested.  The first one called Config1.zip corresponds to the Configuration 1 example I provided in my initial submission.  Bluray.zip is the trace when the Blu-ray player is turned on and the directories are listed from G:.
Is there a xml parameter that is being passed by the Blu-ray player that is not being passed by the TV that causes the TV to ignore the UMS response to the directory listing request?  This begs the question whether it is an improper or incomplete request from the TV or is there a parameter that the UMS exspecting something else?

On an additional note, I did try creating a renderer for the TV that contained all of the Sony Blu-ray renderer config parameters but that did not work.
Also, the error message also occurs when I get to the bottom of a directory and the TV fails to show the actual movie files.  But my first priority is to get the sub-directories being listed and then work on the file listing problem.  It may be cleared up with the directory listing problem.

Cheers,
[Config1.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3626661/Config1.zip)
[Bluray.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3626662/Bluray.zip)

**Comment by atamariya** [comment]
You stopped the process too early. You need to give it a couple of minutes for UPnP search and discovery. Then navigate around a bit even if it's failing. That way log will have more useful information.

**Comment by Albertatoltec** [comment]
atamariya, I am providing a new debug log for you.  This new debug file starts prior to the TV being turned on and continues until after the directories have been selected at least twice.

I am confused about your comment about waiting a couple of minutes.  Perhaps the following information will aid you in looking into the problem.  When the TV is turned on, a menu appears with a series of Apps listed.  Selecting the "album" app brings up a new menu where "Universal Media Server" is one of the options.  Selecting "Universal Media Server", the TV performs the search and discovery which is demonstrated by a rotating circle.  When the search is complete three folders are presented: Recently Played, M:TV Shows, and G:Movies.  Selecting any one of these three folders results in the error message “Selected server contains no media content. Please select another server” being immediately displayed.  No search and discovery takes place as would be demonstrated by the rotating circle.

In Configuration 4 listed in my initial submission, the TV is able to perform the search and discovery demonstrated by the rotating circle after the Blu-ray player has been turned on and listed the Recently Played, M:TV Shows, and G:Movies folders.

I can provide you with the corresponding Wireshark trace of the TV 's network traffic should you need it.

Thanks,

[TV Debug 20190919.zip](https://github.com/UniversalMediaServer/Universa

lMediaServer/files/3632224/TV.Debug.20190919.zip)

**Comment by atamariya** [comment]
Any reason why you have turned caching off. Can you set following flag as true in UMS.conf?
`
use_cache = true
`

**Comment by Albertatoltec** [comment]
atamariya, this is news to me.
I have never edited the UMS.conf file directly.  In fact, I didn’t even know it was in C:\Program\ProgramData\UMS directory.  The only method I have used to configure the GUI has been through the GUI interface.  And, the GUI interface does not have an option for changing the cache.  So how did it get changed?  Unless there is a question regarding the cache in the preliminary installation of UMS.  I noticed that the system generated option settings do not leave a space after the equals sign and this is the case for the “use_cache” option.
Regardless, I will change the option to “true” and restart the UMS to see if that makes a difference.  Hurrah, changing the option now has the directories showing up.  I rebooted the server twice to make sure and the TV can drill down the directories/folders.
Now I just have to work on why the actual files do not appear in the folders.  Which has the same problem as directory listing issue as it doesn’t perform a search and discovery but immediately presents the same error message
Cheers,

**Comment by Nadahar** [comment]
@Albertatoltec You can enable/disable the cache from the GUI, the problem is just that different versions of UMS use different names for this. As far as I can remember, it has been called `cache`, `database` and `media library`. Whatever the name is in your version, it's all the same thing.

**Comment by atamariya** [comment]
@Albertatoltec if the issue is resolved, can you close the bug?

**Comment by Albertatoltec** [comment]
The issue is closed.  It is interesting to note that the Sony Blu-ray player is able to request the directories and cause them to be cached which the TV can then see, while the TV itself cannot.
Next problem is finding out why the TV doesn't list the actual video files.
