### ISSUE TITLE
Crash After Language Selection Menu v9.1

### ISSUE THREAD

**Issue by jefrotone** [UniversalMediaServer/UniversalMediaServer#1870]
[hs_err_pid6856.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3838172/hs_err_pid6856.log)

Windows 10 x64 Build 18362
AMD 3800x Processor 
X570 Aorus Elite Motherboard

**Comment by jefrotone** [comment]
[hs_err_pid7632.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3838198/hs_err_pid7632.log)

This is another log but with the AdoptOpenJDK JRE runtimes.

**Comment by SubJunk** [comment]
@jefrotone hi, thanks for providing the dumps. Are there any logs in `ProgramData/UMS`?

**Comment by jefrotone** [comment]
no logs , just conf files.

**Comment by SubJunk** [comment]
@jefrotone can you try running UMS via the Windows command prompt with the following command, from within the `C:\Program Files (x86)\Universal Media Server\` folder:

`"C:\Program Files (x86)\Universal Media Server\jre-x64\bin/java.exe" -Xmx1280M -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -classpath update.jar;ums.jar net.pms.PMS`

Then we might see some useful detail

**Comment by StuckInLimbo** [comment]
Also experiencing the same issue on 9.1. Attaching my log as well.
[hs_err_pid15000.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3908390/hs_err_pid15000.log)

**Comment by SubJunk** [comment]
@StuckInLimbo same message to you, please try running it manually with `java.exe` and let us know the output of that

**Comment by atamariya** [comment]
Guess it's related to D3D drivers on win10. This might help.
https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=13773&p=40097#p40097

**Comment by jefrotone** [comment]
it started working on version 9.1.0 and update Windows 10 x64 1909 Pro.

... not sure what happened.. but it works great now after the update.

**Comment by StuckInLimbo** [comment]
> 
> 
> Guess it's related to D3D drivers on win10. This might help.
> https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=13773&p=40097#p40097

Yeah this fixed my issue, creating an exception in RTSS did it for me. This wasn't a problem on 1903, 1909 is just buggy I guess.
