### ISSUE TITLE
Web player isn't centered

### ISSUE THREAD

**Issue by SsJVasto** [UniversalMediaServer/UniversalMediaServer#1871]
I noticed this issue on my PC using FireFox, creating an issue so a commit can be attached to it.

![image](https://user-images.githubusercontent.com/1872764/69114208-ceb84400-0a52-11ea-831b-d48171e4c81d.png)

**Comment by SsJVasto** [comment]
Well, it seems I can't push a commit to a branch of this repository, but the fix is as follows:

**/src/main/external-resources/web/web.css**, line 81
```
max-width: 720px;
```
should be
```
max-width: 1280px;
```

The result:
![image](https://user-images.githubusercontent.com/1872764/69114923-e264aa00-0a54-11ea-94f9-f716634b9acf.png)

**Comment by atamariya** [comment]
@SsJVasto You should ideally fork the repo and create a Pull Request (PR).

**Comment by SubJunk** [comment]
@SsJVasto that code change breaks it for me in Chrome and Firefox, which already have it centered for me. I'm not sure what the difference is here. I have tried to reproduce it with widescreen and non-widescreen video but it is still already correct for me. Can you attach the MediaInfo data for the video?

**Comment by SsJVasto** [comment]
@SubJunk Sorry, where can I get the MediaInfo?  Do you mean something like the output of ffprobe, or is it something verbose in ums?  (I use a headless Debian server, so I don't have a UI to explore the options)

**Comment by Nadahar** [comment]
```powershell
> apt install mediainfo
> mediainfo <filename>
```

**Comment by SubJunk** [comment]
I think this has been fixed in v10, if not feel free to reopen
