### ISSUE TITLE
BRAVIA KD-65AG9 media renderer not recognized

### ISSUE THREAD

**Issue by rubin55** [UniversalMediaServer/UniversalMediaServer#1872]
UMS 9.1.0, all rendererers enabled. Log messages about every few seconds come by like the following:

```
INFO  2019-11-23 14:09:04.865 [HTTPv2 Request Worker 9] Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA KD-65AG9";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA KD-65AG9"; mv="3.0";
```

This is the european variant of the A9G in the US I think. The TV runs Android 8 Oreo. Most content plays, although I did notice certain mkv files did not, which did play on my older TV (that was a Bravia KDL-55HX820).

**Comment by SubJunk** [comment]
@rubin55 thanks for making this issue.

I've made a renderer profile for you to test, please let me know how it goes. It can be unzipped and placed in the `renderers` folder in your UMS installation.
[Sony-BraviaAG.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/3903079/Sony-BraviaAG.zip)
