### ISSUE TITLE
Can seek video on Windows but cannot seek on Linux version

### ISSUE THREAD

**Issue by mokalovesoulmate** [UniversalMediaServer/UniversalMediaServer#1888]
**System:**
Intel i5-2400
RAM 8GB
SSD 256GB
UMS version: ums-9.2.0 for both OS below
OS (dualboot): 
- Windows 10 version 1909
- Linux Mint 19.3 Tricia

**Debug file:**
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4067435/ums_dbg.zip)

**Problem and steps taken:**
- Windows version can seek videos just fine. VLC for Android renderer can play normally
- Linux version cannot seek videos. VLC for Android renderer saying: "Unseekable Stream"
- UMS setting at Automatic (wired)
- Checked UMS.conf on both Windows and Linux installation, both identical
- Checked renderers/VLC-for-desktop.conf (even I am in Android but this version were displayed by UMS) on both Windows and Linux installation, both identical

I have Mac OS X (with Catalina) but cannot test right now.

Thank you.

**Comment by SubJunk** [comment]
@mokalovesoulmate from the logs it looks like there is a problem with your installation of MediaInfo on Linux. Having that installed and working, along with libzen (a dependency of MediaInfo), is likely to fix this

**Comment by mokalovesoulmate** [comment]
Right, `sudo apt install mediainfo` is fixing the problem. Thanks!
