### ISSUE TITLE
Add option to avoid first-run wizard by just choosing default settings

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1891]
Users shouldn't be forced to do that

**Comment by ahmedadan** [comment]
Hi @SubJunk I am interested in taking this on, I am new to contributing to OSS and I was wondering if you could provide some context on where to start.

**Comment by SubJunk** [comment]
@ahmedadan hi, welcome :) have you managed to build the program yet? The instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-build-UMS

**Comment by ahmedadan** [comment]
I haven't yet, I'll get that squared away right now.

**Comment by ahmedadan** [comment]
I have successfully built from source, anything else I should do to prepare?

**Comment by SubJunk** [comment]
@ahmedadan that's great. The wizard file is at https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/newgui/Wizard.java
Feel free to ask questions and I will do my best to answer them

**Comment by ahmedadan** [comment]
@SubJunk A few questions after reading the code.

- Do you have an idea of what a desired default configuration should be?
- I have no experience with Crowdin, it looks like that's whats used for localization. Is there a outsource you could provide, or is that handled at a later time?

**Comment by SubJunk** [comment]
@ahmedadan the defaults are already in the code, for example this line sets the default option to the second option https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/newgui/Wizard.java#L96 so I would use those same defaults

For Crowdin, you can just add your new translation string to `Messages.properties` and then I can upload it to Crowdin when the branch merges

**Comment by ahmedadan** [comment]
@SubJunk Opened a draft PR, functionality is complete just having issues with passing the linter checks. I'd love a second pair of eyes.
