### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1896]
We should probably look different in dark mode... darker

**Comment by DevCharly** [comment]
You could try FlatLaf (https://github.com/JFormDesigner/FlatLaf).
It comes with dark and light themes and scales on HiDPI screens.

**Comment by SubJunk** [comment]
@DevCharly I'm interested to try it for sure

**Comment by SubJunk** [comment]
This is done on our new web settings page
