### ISSUE TITLE
Change fully played action option from video to media in GUI

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#1901]
On the `navigation settings` tab there's a dropdown for `fully played action`.

One option is `hide video` 

For consistency with `mark media` and for relevance to other filetypes this should be updated to `hide media`

- [ ] option should say `hide media`

**Comment by valib** [comment]
@polygirl good idea. Thanks

**Comment by SubJunk** [comment]
This is merged and I made a followup story to make it actually do that
