### ISSUE TITLE
Large file causes crash on startup

### ISSUE THREAD

**Issue by georgedorn** [UniversalMediaServer/UniversalMediaServer#1905]
I'm testing this with a 36GB file downloaded from twitch.tv.  Obviously I can't grab logs from the `Logs` tab, but I can include the console output and debug.log.

To isolate the problem, I move the file into its own folder, deleted the database and cache and configured UMS to only share that folder.

Mediainfo output for the file:
```
share@teskin:~/ums-9.2.0$ mediainfo ~/test/large_file.mp4
E: File read error
General
Complete name                            : /home/share/test/large_file.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 35.5 GiB
Duration                                 : 39 h 58 min
Overall bit rate                         : 2 120 kb/s

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 39 h 58 min
Bit rate                                 : 2 029 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Stream size                              : 34.0 GiB (96%)
mdhd_Duration                            : 143917088
```

The file read error at the beginning doesn't seem to stop me from playing the file in VLC, and the details from mediainfo match what VLC says.
[debug.log.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4168722/debug.log.zip)

**Comment by georgedorn** [comment]
Additional info:

I'm on a fresh install of Ubuntu 18.04 server.  I've tried using both the bundled JRE and openjdk-8.  Mediainfo is v17.12, which is do see is a bit behind where the windows and os x builds are pinned.  I'll try building mediainfo from source to see if that helps.

**Comment by georgedorn** [comment]
Just confirmed that building libmediainfo from source (https://github.com/MediaArea/MediaInfo) and removing libmediainfo0v5 provided by ubuntu fixes this problem.  It's not a great fix as that build is not easy, but this should be a workable solution for somebody...

Maybe bundling this library like ffmpeg and tmux would solve this going forward?

**Comment by polygirl** [comment]
@georgedorn Thanks for the investigation and the update.  It looks as though your problem is resolved for now,.  You might want to follow the progress on this proposed enhancement at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1774

**Comment by SubJunk** [comment]
Also just to note, MediaInfo offers binary downloads for Ubuntu too, to save you having to build it yourself https://mediaarea.net/en/MediaInfo/Download/Ubuntu

**Comment by georgedorn** [comment]
Note that this failure caused UMS to crash hard, not just fail to import some files.  This is probably an exception that could be caught and logged, not take down the whole server, especially since mediainfo seems to work exactly the same regardless of version or file size.
