### ISSUE TITLE
Remove and refactor New Media code

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#1912]
There used to be a virtual folder for New Media but this doesn't exist anymore so it needs to be refactored and the setting removed from the GUI.

Under Navigation Settings -> Virtual Folders/ Files area there's a checkbox for `Show the "New Media" folder`

- [ ] Option to show/hide New Media folder should not appear in GUI
- [ ] Code should remove references to New Media

**Comment by atamariya** [comment]
What's the alternative for "New Media" folder?

**Comment by SubJunk** [comment]
The `Unwatched` folder in the `Media Library`

**Comment by SubJunk** [comment]
Done
