### ISSUE TITLE
[Suggestion] Film Strip Overlay

### ISSUE THREAD

**Issue by Neocazen** [UniversalMediaServer/UniversalMediaServer#1913]
It would be interesting to have this function in ffmpegthumbs.

**Comment by SubJunk** [comment]
I'm not quite sure what the suggestion is - is it that we introduce a feature to add a film strip overlay to thumbnails of video files? If that's the suggestion I don't think we would do it but I have seen a renderer before (I can't remember which brand of TV or DVD player) do that itself

**Comment by Neocazen** [comment]
Yes, that's it. 
    As I said, it would be nice to have more of this option at the almost complete UMS. Because not every user has this knowledge.
     I did it here in mine. I also added new images for my LG TV customers My Xbox Classic and for my Xbox 360, Image codes with the flag of Brazil, launcher of the application (I use Linux) renderer for my TV ...
     No more thanks for responding.

**Comment by SubJunk** [comment]
@Neocazen please feel free to contribute those enhancements to us. We are open source so we rely on that.

**Comment by Neocazen** [comment]
> @Neocazen please feel free to contribute those enhancements to us. We are open source so we rely on that.

OK. Thank you.
