### ISSUE TITLE
No Start Linux x64

### ISSUE THREAD

**Issue by Neocazen** [UniversalMediaServer/UniversalMediaServer#1922]
Package downloaded from the official website.
Error occurred during initialization of VM
java/lang/ClassNotFoundException: error in opening JAR file ~/UMS-9.3.0/ums-9.3.0/linux/jre-x64/lib/rt.jar

The Archive is corrupted.

**Comment by mbentley** [comment]
I am seeing the same; started with UMS 9.3.0; previously worked with 9.2.0

```
Error occurred during initialization of VM
java/lang/ClassNotFoundException: error in opening JAR file /opt/ums/linux/jre-x64/lib/rt.jar
```

**Comment by Neocazen** [comment]
> I am seeing the same; the issue started with UMS 9.3.0; previously worked fine with 9.2.0.
> 
> ```
> Error occurred during initialization of VM
> java/lang/ClassNotFoundException: error in opening JAR file /opt/ums/linux/jre-x64/lib/rt.jar
> ```
> 
> Wondering if it has something to do with the JRE update: `Updated JRE to 1.8.241`

I added the rt.jar file from version 9.2 and it worked. It is notoriously corrupted, as the file is only slightly over 20MB.

**Comment by SubJunk** [comment]
Thanks for reporting this, I will fix it ASAP

**Comment by Neocazen** [comment]
> Thanks for reporting this, I will fix it ASAP
Ok.

**Comment by SubJunk** [comment]
That's fixed now. Thanks again

**Comment by Neocazen** [comment]
> That's fixed now. Thanks again

don’t mention it

**Comment by Neocazen** [comment]
Package official site is still unchanged. Proceed?

**Comment by SubJunk** [comment]
@Neocazen do you mean here? https://www.fosshub.com/Universal-Media-Server.html
It looks fixed to me

**Comment by Neocazen** [comment]
> @Neocazen do you mean here? https://www.fosshub.com/Universal-Media-Server.html
> It looks fixed to me

Yes, but for me no. "rt.jar" in linux x64/lib ?

**Comment by SubJunk** [comment]
@Neocazen you're right, it looks like it is still using the old file despite me deleting and uploading again. I'll have renamed it now on FossHub which seems to have busted the cache.
I have confirmed that the SourceForge and GitHub versions are fixed too.

**Comment by Neocazen** [comment]
> @Neocazen you're right, it looks like it is still using the old file despite me deleting and uploading again. I'll have renamed it now on FossHub which seems to have busted the cache.
> I have confirmed that the SourceForge and GitHub versions are fixed too.

Ok. lol

**Comment by Neocazen** [comment]
> @Neocazen you're right, it looks like it is still using the old file despite me deleting and uploading again. I'll have renamed it now on FossHub which seems to have busted the cache.
> I have confirmed that the SourceForge and GitHub versions are fixed too.

Ok. lol
