### ISSUE TITLE
Implement DLNA.ORG_PN for streamed videos

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#1926]
See https://github.com/UniversalMediaServer/UniversalMediaServer/issues/494 for context

**Comment by SubJunk** [comment]
This is done in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/a1d230fed6553f60f3600c67043d72390ebdff6d for all of the types in the DLNA spec
