### ISSUE TITLE
Windows build documentation

### ISSUE THREAD

**Issue by luca-vercelli** [UniversalMediaServer/UniversalMediaServer#1941]
In the "BUILD.md" it is claimed that 

> By default, `mvn package` builds an installer or distibution file for the
> platform it is being compiled

However this is not true. By default the linux profile is the active one (see pom.xml). So, either the documentation is wrong or there is an issue with the non-linux builds.

**Comment by SubJunk** [comment]
@luca-vercelli thanks for reporting this, I have fixed the documentation in `master`
