### ISSUE TITLE
UE49RU7305KXXC not work subtitles

### ISSUE THREAD

**Issue by WebxMasterx** [UniversalMediaServer/UniversalMediaServer#1955]
[debug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4410577/debug.zip)
Hi subtitles not work on my TV UE49RU7305KXXC (49'' RU7305 Curva Smart 4K UHD TV 2019)

Thanks
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

**Comment by valib** [comment]
@WebxMasterx have you read the "How to contribute" ? You made the log in DEBUG mode. And we need to know which subtitles are not working.

**Comment by WebxMasterx** [comment]
The debug is added to this request.  I have a folder created only with the videos and their subtitles with the same name as the movies with the extension .srt.  For the moment this is the information I can give you.  Thanks.

**Comment by valib** [comment]
@WebxMasterx as I wrote you made the log in the DEBUG mode which is not useful. There are not information we need. You have to make the log in the TRACE mode how is written in the instructions.

**Comment by WebxMasterx** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4432100/ums_dbg.zip)
Done

**Comment by SubJunk** [comment]
@valib I had a look at the logs and it seems to me like a bug with external subs logic. The video file has external SRT subs that are detected, and that format is supported in the renderer config file, but the logs say the subtitles aren't valid for streaming. Since you know that part of the code best, can you look into it?

**Comment by SubJunk** [comment]
This has been fixed in 9.6
