### ISSUE TITLE
9.4.0: ffmpeg doesn't work on Macs

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#1959]
```
> /Applications/Universal\ Media\ Server.app/Contents/Resources/osx/ffmpeg 
dyld: Library not loaded: /Users/kyle/software/vmaf/macos64/vmaf-20200323-7f45449-macos64/lib/libvmaf.dylib
  Referenced from: /Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg
  Reason: image not found
Abort
> ls -l /Applications/Universal\ Media\ Server.app/Contents/Resources/*dylib
-rw-r--r--@ 1 esabol  admin  15786304 Dec 26  2018 /Applications/Universal Media Server.app/Contents/Resources/libmediainfo.dylib
```
`libvmaf.dylib` is not in `Universal Media Server.app/Contents/Resources/`, nor is the executable linked in such a way as to look for it there.

Please fix ASAP.

**Comment by SubJunk** [comment]
Thanks for reporting this, I have reproduced and reported it to the publisher of that binary https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=13&t=7824
In the meantime I will do a release ASAP to rollback that binary.

**Comment by SubJunk** [comment]
By the way you might help the bug to get some attention by posting on that forum I linked. For now I will switch to a different source but it would be nice to be able to use the Zeranoe builds because we use them for Windows already.

**Comment by esabol** [comment]
This is the last nightly build that works:
https://ffmpeg.zeranoe.com/builds/macos64/static/ffmpeg-20200327-e34157f-macos64-static.zip

Subsequent nightly builds starting with 2020-03-28 rely on `libvmaf.dylib` and do not.

**Comment by esabol** [comment]
> By the way you might help the bug to get some attention by posting on that forum I linked.

I tried to register, but I haven’t received the account activation email. I told it to resend it, too.

**Comment by Nadahar** [comment]
> I tried to register, but I haven’t received the account activation email. I told it to resend it, too.

Check your spam folder..

**Comment by esabol** [comment]
> > I tried to register, but I haven’t received the account activation email. I told it to resend it, too.
> 
> Check your spam folder..

I did.

**Comment by SubJunk** [comment]
I fixed this in 9.4.1 which is out now on GItHub, SourceForge and the auto updater. I'll do the rest of the release process later

**Comment by esabol** [comment]
> I fixed this in 9.4.1 which is out now on GItHub, SourceForge and the auto updater. I'll do the rest of the release process later

Did you use https://ffmpeg.zeranoe.com/builds/macos64/static/ffmpeg-20200327-e34157f-macos64-static.zip ?

**Comment by SubJunk** [comment]
I used this https://evermeet.cx/pub/ffmpeg/snapshots/ffmpeg-97091-g26a36801c0.zip which is the source we used prior to this change

**Comment by esabol** [comment]
Zeronoe replied in the forum URL posted above. He fixed the linking problem in the static ffmpeg. I confirmed this by downloading:

https://ffmpeg.zeranoe.com/builds/macos64/static/ffmpeg-20200504-5767a2e-macos64-static.zip

Please use the latest static ffmpeg build in https://ffmpeg.zeranoe.com/builds/macos64/static/ in future Mac releases, assuming you are so inclined.

**Comment by SubJunk** [comment]
Nice catch, I will include it in the release I'm getting ready now
