### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1964]
It would be nice to add something like this to guide and protect the project culture https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

**Comment by KishkinJ10** [comment]
@SubJunk Sir I am a beginner can I work on this ? And which resources should I refer for adding the code of conduct?

**Comment by SubJunk** [comment]
@KishkinJ10 that would be really helpful, thank you. There is a section on their website called "How to adopt Contributor Covenant" that describes how to do it https://www.contributor-covenant.org/

**Comment by rauthanshubham1** [comment]
Hello @SubJunk , I am beginner , and would like to contribute

**Comment by SubJunk** [comment]
@rauthanshubham1 you're welcome to do it :)

**Comment by rauthanshubham1** [comment]
@SubJunk , Sir please tell me the email address on which any harassment case will be reported. I have to provide that email in Code Of Conduct.

**Comment by SubJunk** [comment]
@rauthanshubham1 instead of email please provide a link to our forum `universalmediaserver.com/forum`

**Comment by SubJunk** [comment]
Thanks!
