### ISSUE TITLE
Rational fields are taking up a lot of database space

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1974]
I was looking through the client database and noticed that the `Rational fields`, mostly aspect ratios, can be quite large. I have entries like `aced0005737200156e65742e706d732e7574696c2e526174696f6e616c000000000000000202000649000868617368436f64654c000b64656e6f6d696e61746f727400164c6a6176612f6d6174682f426967496e74656765723b4c00156772656174657374436f6d6d6f6e44697669736f7271007e00014c00096e756d657261746f7271007e00014c00127265647563656444656e6f6d696e61746f7271007e00014c0010726564756365644e756d657261746f7271007e0001787200106a6176612e6c616e672e4e756d62657286ac951d0b94e08b0200007870000004e8737200146a6176612e6d6174682e426967496e74656765728cfc9f1fa93bfb1d030006490008626974436f756e744900096269744c656e67746849001366697273744e6f6e7a65726f427974654e756d49000c6c6f776573745365744269744900067369676e756d5b00096d61676e69747564657400025b427871007e0002fffffffffffffffffffffffefffffffe00000001757200025b42acf317f8060854e002000078700000000109787371007e0004fffffffffffffffffffffffefffffffe000000017571007e00070000000101787371007e0004fffffffffffffffffffffffefffffffe000000017571007e000700000001107871007e000671007e000b` for `PIXELASPECTRATIO`, `ASPECTRATIOVIDEOTRACK` and `ASPECTRATIOCONTAINER` and often all 3 are populated with the same value for the same file.

This was something I brought over from DMS and maybe I did it wrong, can you offer any insight @Nadahar ?

**Comment by Nadahar** [comment]
It doesn't sound unreasonable to me. I've made `Rational` to provide absolute accuracy at the cost of storage space. It is stored as two `BigInteger` values (nominator and denominator), which will take as much space as they need, so the actual length depends on the values they hold.

That said, I haven't "optimized" Rational for size either so it's caching quite a lot of stuff to make using it quicker. On top of that, you have the cost of Java serialization, which will also waste some bytes I believe.

It would probably be more effective to store these as two `BigInteger`s - most of the time two `long`s would probably do it as well. That would avoids storing the cached stuff, and at least using `long`s would get rid of serialization all together. I don't know if H2 has a "native" way to store `BigInteger`s, if it does that would probably be the best solution. Even though `long` would probably as good as always to, it is a dilemma to know how to handle the cases where `long` doesn't do it. You would need to make an algorithm that would reduce it to the closes pair of `long`s while still have a minimal impact on accuracy. That sounds challenging to me, although I haven't really dug into it so it might be easier than I imagine.

The question is if the `Rational`s add up to a storage use that really matters or not, but I guess they can quickly end up dominating the storage space for one parsed video, except the thumbnail of course.

**Comment by SubJunk** [comment]
Thanks for the explanation. I'll have a look at possible improvements
