### ISSUE TITLE
linux Start UMS error (can't find bundled ffmpeg)

### ISSUE THREAD

**Issue by silenceleaf** [UniversalMediaServer/UniversalMediaServer#1977]
```
DEBUG 2020-04-18 23:06:11.330 [main] UPNP Services are online, listening for media renderers
DEBUG 2020-04-18 23:06:11.332 [main] Attached http player control handler to web server
INFO  2020-04-18 23:06:11.332 [main] Checking the fontconfig cache in the background, this can take two minutes or so.
ERROR 2020-04-18 23:06:11.334 [main] A serious error occurred during Universal Media Server initialization: null
DEBUG 2020-04-18 23:06:11.336 [main] 
java.lang.NullPointerException: null
	at net.pms.PMS.init(PMS.java:569)
	at net.pms.PMS.createInstance(PMS.java:916)
	at net.pms.PMS.main(PMS.java:1086)
```

I don't have FFmpeg installed in my VM, I am expecting it uses "linux\ffmpeg"  but seems it can not find the binary.

At least, it should not be a NPE.

My os is Linux x64

**Comment by silenceleaf** [comment]
I think I found the config of ffmpeg path

**Comment by silenceleaf** [comment]
My another suspect is `project.binaries.dir` is not properly set in Linux platform. So, the program can not find the bundled ffmpeg.

**Comment by SubJunk** [comment]
@silenceleaf thanks for reporting it, it has already been fixed and merged to master, and will be released very soon

**Comment by silenceleaf** [comment]
> @silenceleaf thanks for reporting it, it has already been fixed and merged to master, and will be released very soon

Thanks! will post my feedback here when new version released.
