### ISSUE TITLE
How to use Hardware Acceleration for hevc_nvenc?

### ISSUE THREAD

**Issue by Spamm00r** [UniversalMediaServer/UniversalMediaServer#1996]
Hi,

I'm trying to use Hardware Acceleration for hevc_nvenc. 

So far I have only managed to make HW Acceleration work with the following settings:

In GUI in acceleration method change auto to:  -hwaccel_output_format cuda -c:v h264_cuvid

Put in the renderer file this line:
CustomFFmpegOptions = -c:v h264_nvenc -b:v 20M -zerolatency 1 -preset slow -level 41 -f matroska
What settings do I have to put there to make use of hevc_nvenc with  Hardware Acceleration?

Or alternatively HEVC with Intel Quick Sync  Hardware Acceleration. I searched everywhere and couldn't find.

**Comment by Nadahar** [comment]
Why would you want to transcode to H.265? As far as I can tell, there is nothing to gain unless you have a really low network bandwidth and really strong hardware. The encoding efficiency of H.264 far outweighs the very slight bandwidth reduction that can be achieved with H.265 with "corresponding" quality.

H.265 won't give higher image quality as long as you alllow H.264 to use slightly more bandwidth.

To answer your question, you'd probably have to change the "transcode to" setting for the renderer configuration in question to target H265 to have any chance for this to work. The "merging" of the custom and UMS' own parameters isn't very sophisticated, so it might not be doable at all. You should enable `trace` logging and then search the log file for the full FFmpeg command line when transcoding starts. That way you can see the result of the "merging", and see if you manage to tweak the custom options in a way that gives a valid resulting command.

**Comment by Spamm00r** [comment]
"unless you have a really low network bandwidth and really strong hardware. "

That is exactly my reason for doing it here.

I have HEVC capable hardware, but very limited upload bandwidth. 

With h264, I have to use extremely restrictive bitrates to remain within my upload limit.

With HEVC, I can achieve significantly better image quality given the limited upload bandwidth. And these little bandwidth savings have an large impact in my streaming situation.

I already checked the log and the source code and tried to figure out how UMS combines the ffmpeg parameters. But I seem to understand what parameters I have to set in UMS cinfig file and the renderer config file for hevc_nvenc.

Unfortunately, UMS just appends instead of replacing the parameters I set in "CustomFFmpegOptions" sometiemes leading to undesired outcomes.

I also think that the "libx265" codec is hardcoded for HEVC, and even though i use CustomFFmpegOptions = -c:v hevc_nvenc, UMS will still keep its own hardcoded libx265 parameter in the ffmpeg options so that my "-c:v hevc_nvenc" command is ignored and fails because UMS passes its own codec parameter to ffmpeg too and earlier than the custom parameter.

Outside of UMS, with running ffmpeg via command line only by hand, I can make ffmpeg use hevc_nvenc just fine, but UMS doesn't do it properly.

I was thinking, that maybe I just didn't understand it what settings to put on:  "ffmpeg_gpu_decoding_acceleration_method =" and "CustomFFmpegOptions =" sections of the UMS and renderer config file.

I have tried dozens of possible config parameters, but they all fail if I try to force hevc_nvenc.

Only libx265 via software however does work but unfortunately it does not use any Hardware Acceleration, not even Intel Quick Sync and thus maxes out the CPU.

But I now believe that UMS is by code just not handling the passing of these parameters correctly. 


I need to know what UMS will accept as "ffmpeg_gpu_decoding_acceleration_method =" and "CustomFFmpegOptions =" parameters to transcode using hevc_nvenc or at least hevc_qsv.

I start to think that these scenarios are not considered in the UMS code. Onyl h264 works, but not  hevc.

**Comment by Nadahar** [comment]
I actually don't think `ffmpeg_gpu_decoding_acceleration_method` does much at all. I did look at it a while back, and I don't remember the exact details, but I think I concluded that it essentially were useless. I also think this setting only applies to *decoding* acceleration, which hardly ever is relevant.

When it comes to the combination of the parameters, I think what you've found is pretty much the situation. The code that does this is very unstructured and has been modified by many different developers over many years, and is in such a disastrous state that any modification is likely to break multiple other things. It leaves a lot to be desired, and it wouldn't surprise me the least if it's not possible to do what you're trying to do.

I can pretty much guarantee that this situation hasn't been considered specifically. Normally UMS is used on a LAN, and the very restricted bandwidth situation typically isn't relevant.

FFmpeg doesn't help either in the "manual" way hardware acceleration works for encoding. I have concluded that until FFmpeg improves their handling, it's "impossible" to make a robust, well-functioning logic that will enable "automatic" handling of hardware accelerated encoding.

To make what you want to do possible, it seems to me that changes are needed in UMS' code. That means you'd either have to try to figure it our yourself, or wait for somebody else to pick it up.

**Comment by Spamm00r** [comment]
Yeah unfortunately, not much interest is given to HEVC also in other projects. Someone forked HEVC support into Jellyfin for example over a year ago but they haven't added a option in the gui yet to make use of it till now. So you practically have to hack the GET request to tell Jellfin to transcode in HEVC.

I was hoping to make it work with UMS, as it looked most promising until I realized, that UMS is messing up the ffmpeg commands.

I have a workaround though.

You can use NVIDIA GAmestream, or sunshine and moonlight to stream in hardware accelerated HEVC the app you wanna stream. And play the media on the remote pc. That works remarkably well, even with very limited bandwidth.

It has some drawbacks if you just want to stream your media, which i was hoping to mitigate with UMS and HEVC support, but with no DLNA Server available that supports hevc_nvenc, that is the best solution for me right now.

**Comment by Nadahar** [comment]
I'm still not exactly sure of your use-case, since it seems to involve streaming via the Internet somehow. If you just wanted to hack UMS' code to make this work without caring about what else you broke, this shouldn't be very hard to do. You could probably just replace the x265 parameters that you find hardcoded with what you want, and then configure the renderer to transcode to H.265.

But, if you find other solutions to handle your needs, you might not have to do such an effort. As I said originally, it's hard to see any benefit in using H.265 for normal, LAN-based delivery, which probably explains why this isn't very easy to find.

**Comment by SubJunk** [comment]
@Spamm00r we have handling of certain custom options to make UMS play nicer with custom configs so we can do that for you too. Please send the whole FFmpeg command you want to be used.

**Comment by SubJunk** [comment]
Never got a reply
