### ISSUE TITLE
BRAVIA KD-65AG9 no media playing, even with transcoding

### ISSUE THREAD

**Issue by rubin55** [UniversalMediaServer/UniversalMediaServer#2017]
UMS 9.4.2, trying to play any file results in timeout and a message on the TV saying "Cannot play video."

I've tried various titles, there are a few which play, but a lot that don't, especially compared to my previous TV (this TV is relatively new). 

In this particular case I'm trying to play "Van.Der.Valk.S01E01.DVDRip.XviD-SPRiNTER.avi"

See attached logs:
[trace-log-output.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4571392/trace-log-output.zip)

**Comment by SubJunk** [comment]
@rubin55 please provide the log package since that will also give us other files that can help.
I can see here that it is being transcoded both times, because the video codec divx isn't listed in the supported codecs on that renderer.
Does the file work if you play it via the `[No Transcoding] option from within the `#--TRANSCODE--#` folder?

**Comment by rubin55** [comment]
Hi @SubJunk, I re-did the issue and created the log package as described in the ticket template, see here:
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4587393/ums_dbg.zip)

Some notes: 
  * Turned on TV at line 3460
  * Tried to play file at line 53990
  * TV said "Cannot play video." at line 70019

**Comment by SubJunk** [comment]
@rubin55 the fact that it plays when you select `[No Transcoding]` means that we can fix it in the renderer config file. Looking at that issue you linked, I waited around a month for the user to respond to me before I merged what we have.

I've done some more work, can you please test https://raw.githubusercontent.com/UniversalMediaServer/UniversalMediaServer/4e0af9aa0605504ee565504e1c42d7f6e5aa7038/src/main/external-resources/renderers/Sony-BraviaAG.conf ?

I also have some code fixes that might help, I put them up at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2036/files 
I would usually build and upload a test release for you to test, but I don't have the ability to do that right now as I'm away from home. I can do it in a couple of days or you can do it if you want.
Either way this new renderer file should fix playback of the file from your logs.

**Comment by rubin55** [comment]
Hi @SubJunk, I managed to test the new Sony-BraviaAG.conf and can confirm that all my titles started playing without need of explicitly selecting [no transcoding].

I did not have a moment to make a build myself but also not in major hurry now that UMS is playing along nicely with my set!

**Comment by SubJunk** [comment]
@rubin55 thanks for confirming! That will be in the next release
