### ISSUE TITLE
Needed to replace Java lines in .sh

### ISSUE THREAD

**Issue by chadfay** [UniversalMediaServer/UniversalMediaServer#2027]
9.3.1 started and worked fine but
Starting UMS 9.4.2:

chap@410debbie:~/ums-9.4.2$ ./UMS.sh 
./UMS.sh: 72: exec: jre/bin/java: not found

So just replaced:

replaced(9.4.2):
lines 40 - 43

# Use our JVM if it exists
if [ -f jre/bin/java ]; then
    JAVA="jre/bin/java"
fi

With(from 9.3.1):
lines 40 - 49

# Use our JVM if it exists and the Linux distribution appears to be standard 32 or 64-bit
if [ "$(uname -m | grep '64')" != "" ]; then
    if [ -f linux/jre-x64/bin/java ]; then
        JAVA="linux/jre-x64/bin/java"
    fi
elif [ "$(uname -m | grep '86')" != "" ]; then
    if [ -f linux/jre-x86/bin/java ]; then
        JAVA="linux/jre-x86/bin/java"
    fi

**Comment by SubJunk** [comment]
@chadfay can you please let me know which file you downloaded?

**Comment by SubJunk** [comment]
How can line 72 report `exec: jre/bin/java: not found` if line 40 was `if [ -f jre/bin/java ]; then`? Any ideas @js-kyle ?

**Comment by SubJunk** [comment]
Closing due to no reply from @chadfay
