### ISSUE TITLE
[Request] Amazon Firestick config

### ISSUE THREAD

**Issue by nouse1234** [UniversalMediaServer/UniversalMediaServer#2042]
I recently started to use an Amazon Firestick with the Vimu App.

This app uses a "google-android.conf":
```
#----------------------------------------------------------------------------
# Profile for Android.
# See DefaultRenderer.conf for descriptions of all the available options.
#

RendererName = Android
RendererIcon = android.png
UserAgentSearch = Android
UpnpDetailsSearch = Android

TranscodeAudio = MP3
DefaultVBVBufSize = true
MuxDTSToMpeg = true
H264Level41Limited = false
StreamExtensions = mkv,hdmov,hdm,flac,fla,dts,ogg,asf,asx,m2v,mp4,mpg,mpeg,avi,mov,wmv
ChunkedTransfer = true
HalveBitrate = true
```

With this, the renderer is not able to transcode external subtitles. 
Maybe it is worthfile to provide a firestick-specific configuration file.

**Comment by valib** [comment]
@nouse1234 fine but what media formats is the Amazon Firestick supporting. Is it https://stuff.mit.edu/afs/sipb/project/android/docs/guide/appendix/media-formats.html or something else?

**Comment by SubJunk** [comment]
@nouse1234 thanks for the suggestion. It would be useful if you could also attach logs here so that we can figure out how to identify it

**Comment by Nadahar** [comment]
@SubJunk You could get these if you visited the forum once in a while. We've already found working identifiers there.

**Comment by nouse1234** [comment]
Sorry that i cannot contribute much. I have no idea which formats are supported by Firestick. I am just an end-user running into an UMS related issue. I also didnt want to bother you, i am just suggesting how to improve the software.
The firestick has no native DLNA support and relies on 3rd-Party Apps for this purpose.
I tested some of them (there are plenty), and found that UMS switched the config files quite a lot between different apps. One very basic one is "Google-Android.conf". Alternatively, UMS assigned one of the chromecast related configs to the apps. This wasnt very stable: The same app could have different assigned to different configs, even within the same session (an example log is in the forum).
Thanks to Nadahar, one config for one specific app was created, but you may want to streamline the configs for use with the Firestick.

Thank you very much.

**Comment by SubJunk** [comment]
@nouse1234 thanks for the extra information, I'll see what I can find on the forum and try to put something together, and it's certainly no bother, I really appreciate your feedback!

**Comment by SubJunk** [comment]
This is the forum thread https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14134

**Comment by SubJunk** [comment]
It should make it into the next release, when this merges https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2047

**Comment by SubJunk** [comment]
That's merged now, thank you both, and please let us know if you have any problems with it since it may still need tweaking
