### ISSUE TITLE
Travis always fails

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2048]
Seems related to Cling. I made an issue on the Cling tracker too https://github.com/4thline/cling/issues/252
https://travis-ci.org/github/UniversalMediaServer/UniversalMediaServer/jobs/685806950#L1647

@UniversalMediaServer/developers does anyone have any ideas about how we can fix it?

**Comment by valib** [comment]
@SubJunk I think that there is a problem with the 4thline.org. Not only the Cling but also other dependencies stored at that repo have long response.

**Comment by valib** [comment]
@SubJunk I made the issue in the Travis https://travis-ci.community/t/problems-with-4thline-org-repository/8702. It seems to me that they made some changes in the Travis which started this problem.

**Comment by SubJunk** [comment]
Thanks for making that issue @valib 

I'm not exactly sure about the problem - whether it is a Travis one, or Maven, or our POM config, or the 4thline servers... 🤷‍♂️ 

I'm doing some testing on this branch https://github.com/UniversalMediaServer/UniversalMediaServer/compare/20200520-travismysteries1?expand=1 to try to see if it is related to changes I made
