### ISSUE TITLE
UMS.sh `jre/bin/java` location incorrect in 9.6.0

### ISSUE THREAD

**Issue by Arceliar** [UniversalMediaServer/UniversalMediaServer#2101]
For reference, I'm using UMS 9.6.0 on x86_64, on the off chance that the java location or the build script is platform dependent.

UMS.sh checks if `jre/bin/java` exists, and when found, it sets `$JAVA` to that value. In UMS 9.6.0 (freshly downloaded from the releases page), the included jre is located in `jre14/` rather than `jre/`. This could be fixed by either updating UMS.sh to check `jre14/` instead, or moving the vendored jre to `jre/` -- I have no idea which is preferable from the developers' side.

**Comment by SubJunk** [comment]
@Arceliar damn, I thought I had changed that. I'll release a fix ASAP

**Comment by SubJunk** [comment]
It's fixed now in master and will be released soon
