### ISSUE TITLE
NPE at getSubsUrl

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#211]
Reported here http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=1438

I'm not sure of the best fix for this so maybe you guys @valib @SharkHunter @skeptical have some ideas?

**Comment by Sami32** [comment]
@SubJunk Did the NPE works done since then fixed this issue ?

**Comment by Sami32** [comment]
@SubJunk https://github.com/UniversalMediaServer/UniversalMediaServer/commit/81e0b47e543c5892462700793cfa9c9a2e464f2d https://github.com/UniversalMediaServer/UniversalMediaServer/commit/2b3750858f4e18bb17af9719494612677c70f7f5 https://github.com/UniversalMediaServer/UniversalMediaServer/commit/a4fd98d0f862c051f9ddf8f5271a8d008cd86e86 https://github.com/UniversalMediaServer/UniversalMediaServer/commit/f23aca81d8c60501ebd8582e5f8b9048485009bd https://github.com/UniversalMediaServer/UniversalMediaServer/commit/bd9feb8ad7b5c85f58ad5b759d230f7820f8fe51 https://github.com/UniversalMediaServer/UniversalMediaServer/commit/bda515aa5d99719a0496fe26c9d82e2c1611234d https://github.com/UniversalMediaServer/UniversalMediaServer/commit/1c688729bae4187b0a25ae85421a18fef88d72a4 ?

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/commit/3173fa339283bbac0abe231d19083d8bea7bf925 ?

**Comment by SubJunk** [comment]
The user didn't respond to the last question so closing this
