### ISSUE TITLE
DLNAMediaInfoTest.testContainerProperties test failure

### ISSUE THREAD

**Issue by elsabio** [UniversalMediaServer/UniversalMediaServer#2117]
For the last few releases, I've had a test failure when building from source on Linux  - this is from the current master building on Ubuntu 18.04.4 LTS:

[ERROR] Failures: 
[ERROR]   DLNAMediaInfoTest.testContainerProperties:109 
Expecting:
 <"Container: OGG, Size: 1734919, Overall Bitrate: 454643, Video Tracks: 1, Video Codec: theora, Duration: 0:00:30.528, Video Resolution: 480 x 270, Display Aspect Ratio: 16:9, Frame Rate: 30.000, Audio Tracks: 1 [Audio Codec: und, Bitrate: 112000, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/ogg">
to be equal to:
 <"Container: OGG, Size: 1734919, Overall Bitrate: 454643, Video Tracks: 1, Video Codec: theora, Duration: 0:00:30.528, Video Resolution: 480 x 270, Display Aspect Ratio: 16:9, Frame Rate: 30.000, Audio Tracks: 1 [Audio Codec: Vorbis, Bitrate: 112000, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/ogg">
but was not.
[INFO] 
[ERROR] Tests run: 375, Failures: 1, Errors: 0, Skipped: 0

Is there a missing dependency here?

**Comment by SubJunk** [comment]
It likely means you are using a different version of MediaInfo to us, and that our logic for matching Vorbis needs to be updated when we update to latest MediaInfo. That is the reason I have added so many samples to that test so I'm happy it has done its job here :)
If you revert to MediaInfo 18.12 that should resolve it

**Comment by valib** [comment]
@elsabio which UMS version do you use? In the latest version is the `Audio Codec: Vorbis` not the `Audio Codec: und` which should past the test.

**Comment by elsabio** [comment]
This is the latest from master, so that is a 9.6.3-SNAPSHOT, though I thin the last I was able to build  was 9.4.1.

I guessed it was probably mediainfo.  The latest version available as a a standard package with Ubuntu 18.04 LTS is 17.12.  So I guess that gives me at least three options:

1. Build an updated mediainfo
2. Update to Ubuntu 20.04 LTS (or some other version)
3. Fix the parser in UMS to handle at least both mediainfo versions.

and some others

4. Suggest mediainfo is pulled in as a maven dependency, either from a binary repository or built locally.
5. Maybe it is just a test or test sample issue to be fixed.

I'll ponder on those; thanks !

**Comment by SubJunk** [comment]
@elsabio are you able to use the MediaInfo version from the following line? https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/.travis.yml#L42

**Comment by elsabio** [comment]
I can look at that.  My first quick test shows that the command-line mediainfo tool versions 17.12 (standard with 18.04 LTS) and 19.09 (standard with 20.04 LTS)  give exactly the same result for video-theora-vorbis.ogg.

**Comment by SubJunk** [comment]
I'll be interested to see what you find with 18.12 since we run these tests on Linux via Travis. Maybe it is unrelated to MediaInfo but let's make sure

**Comment by elsabio** [comment]
@SubJunk I installed 18.12 as you suggested and that does pass the tests.  However, the command-line output from mediainfo 18.12 is just the same for this file as before.

**Comment by SubJunk** [comment]
I'm glad that makes it pass the tests. I'm interested in updating to the latest MediaInfo very soon, and fixing this will be part of it. Maybe you could even help us if you're motivated for it, we are open source and could use all the help we can get :)

**Comment by elsabio** [comment]
I have been involved with a few open source projects, but typically, I find that my available time gets consumed before I really get something done - but If I get some time, I could take a look at that.

**Comment by SubJunk** [comment]
No problem. I will close this issue since it seems fixed, and we have another issue for updating MediaInfo
