### ISSUE TITLE
Append a datetime to debug log zip filename

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2124]
add some info to the filename of the zip (like user name or date) to avoid confusion when looking at logs from different people.

Saw someone ask if there is an option to change log location so it doesn't write to his SSD to avoid excess writes on it.

**Comment by Nadahar** [comment]
There are ways to change the log and temp file location, and you can change the location of the "profile folder" which includes the database. However, as most other things, there is little or no documentation.

**Comment by Mik-S-UMS** [comment]
I didn't know that. would be easier if there was a section in the GUI to set it though. Could be added to the logs tab.

**Comment by Nadahar** [comment]
You should take a look at the `PmsConfiguration` and `RendererConfiguration` classes (both are found in the `net.pms.configuration` package). Reading through both of these will make you aware of what settings are actually available. I don't know if as much as 20% is available in the GUI, so if you want all the options in the GUI, I hope you have the next 10 years available :wink:

**Comment by Mik-S-UMS** [comment]
maybe not every option but some useful ones could be added. I'll have a look at those classes to get an idea of what I'm up against 😄

**Comment by SubJunk** [comment]
I was thinking of that recently too - just appending a date to the zip file. Seems like a good thing to do and wouldn't be difficult. I'll mark this as a good first issue for someone to pick up

**Comment by midhun1998** [comment]
Hey @SubJunk, 
Can I take this issue or is it assigned already? If not, From your comment what I have understood is that we need to append date and time of when the zip is being created (i.e ums_dbg.zip to ums_dbg_2020-06-22T14:42:11.223360.zip). Let me know what I have understood is correct or not. Thanks.

**Comment by SubJunk** [comment]
@midhun1998 hi :) you can certainly work on this issue, that would be very helpful. I would say the format could be like `ums_dbg_2020-06-22-1442.zip` or something similar

**Comment by Mik-S-UMS** [comment]
@midhun1998 looks good, will help to give a more unique name for the logs. 
Would be better if could include the forum username too but that might have to be done on the forum itself. @SubJunk would that be possible?

**Comment by valib** [comment]
@Mik-S-UMS the user could be on the forum but it is unclear. He/she can only make the issue here.

**Comment by Mik-S-UMS** [comment]
@valib I meant that if the log is uploaded to the forum then the username could be added then, but I guess that would involve modifying the forum code.

**Comment by Mik-S-UMS** [comment]
It appears that the date and time used is when UMS is started, not when the logs are created. when saving logs at two different times without restarting UMS they will have the same filename, or if saving logs after UMS has been running for a week or so the filename won't match the current date.

Also it would be good if the default save location was the desktop instead of appdata/UMS so it is easier for people to find.

**Comment by SubJunk** [comment]
I made two new issues for those enhancements
