### ISSUE TITLE
Unable to pass DLNAMediaInfoTest test

### ISSUE THREAD

**Issue by midhun1998** [UniversalMediaServer/UniversalMediaServer#2132]
Hello there, I'm new to Open Source Community and I would like to make my first contribution to UMS. I followed the instruction in **BUILD.md** file to build but I was unable to pass the **DLNAMediaInfoTest** and this was the console output 
![image](https://user-images.githubusercontent.com/24776450/85269110-10034d00-b495-11ea-9c45-178883034127.png)

and this was the test result in the file `net.pms.dlna.DLNAMediaAudioTest.txt`:

```
-------------------------------------------------------------------------------
Test set: net.pms.dlna.DLNAMediaInfoTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.315 s <<< FAILURE! - in net.pms.dlna.DLNAMediaInfoTest
net.pms.dlna.DLNAMediaInfoTest.testContainerProperties  Time elapsed: 3.311 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"Size: 1325017, Overall Bitrate: 0, Mime Type: video/mpeg">
to be equal to:
 <"Container: MP4, Size: 1325017, Overall Bitrate: 676979, Video Tracks: 1, Video Codec: h264, Duration: 0:00:15.658, Video Resolution: 640 x 360, Display Aspect Ratio: 16:9, Scan Type: Progressive, Frame Rate: 23.976, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.601, Reference Frame Count: 4, AVC Level: 3, AVC Profile: high, Audio Tracks: 1 [Audio Codec: AAC-LC, Bitrate: 125547, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/mp4">
but was not.
	at net.pms.dlna.DLNAMediaInfoTest.testContainerProperties(DLNAMediaInfoTest.java:75)

```

And the error is created by file **video-h264-aac.mp4**.
Here's a screenshot of debug console:
![image](https://user-images.githubusercontent.com/24776450/85268244-e39b0100-b493-11ea-9647-449d14ec3ae7.png)

PS: This is my first time running after cloning (No Edits were made to the code).

Am I doing anything wrong? Any help would be great. Thanks. :smile:

**Comment by SubJunk** [comment]
@midhun1998 do you have MediaInfo installed? You'll need version 18.12. That might fix this

**Comment by midhun1998** [comment]
Thanks @SubJunk iit worked.

**Comment by ajkessel** [comment]
Possibly related issue - I was trying to build the api-3-4e4787b branch and got this error:
`[ERROR] Failures:
[ERROR]   DLNAMediaInfoTest.testContainerProperties:104
Expecting:
 <"Container: MKV, Size: 5291494, Overall Bitrate: 2619551, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">
to be equal to:
 <"Container: MKV, Size: 5291494, Overall Bitrate: 2619552, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">`
My system has MediaInfo 19.09 installed so maybe that's the problem but I don't see any easy way to pop in 18.12 just for this build. Is there a simple fix for this?

**Comment by SubJunk** [comment]
We will be updating to the latest MediaInfo very soon. In the meantime you should be able to get UMS to use a version that isn't installed, which operating system are you on?

**Comment by ajkessel** [comment]
I'm on Ubuntu. I was able to work around this issue by adding old apt source (Eoan rather than Focal) and then downgrading mediainfo and libmediainfo to 18.12.
