### ISSUE TITLE
Website design update

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2153]
The website design should be updated to a more modern design.

Part of this should be to display instructions for mac users after they click download, because the latest macOS updates are making it tricky to install and run UMS. Users shouldn't need to search for that information.

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers I have decided to do this before the release of v10, since that will give us a lot of modern features so we should have a more modern website to go with it. I'm trying out an implementation using Bootstrap 5 now and I'll update on progress here.

I have also been checking out competitors' websites to get ideas.

If you have any ideas to suggest please let me know.

**Comment by valib** [comment]
@SubJunk it could be nice to have there also the UMS setup.

**Comment by SubJunk** [comment]
It should also offer more installation options like `brew` https://formulae.brew.sh/cask/universal-media-server#default and Docker https://hub.docker.com/repository/docker/universalmediaserver/ums

**Comment by SubJunk** [comment]
The pre-release for this website is up at https://www.universalmediaserver.com/v2/
I will be working on it a lot over the next few days hopefully so that at least a first version can be released. I will also add it to GitHub so that contributions can happen.

**Comment by SubJunk** [comment]
The new website is released now, and uploaded to GitHub https://github.com/UniversalMediaServer/website
It can still be improved a lot so I hope that having it on GitHub will encourage collaboration
