### ISSUE TITLE
9.7.0 doesn't work with debian linux

### ISSUE THREAD

**Issue by yennor** [UniversalMediaServer/UniversalMediaServer#2158]
I've just upgraded from version 9.2.x to the newest one: 9.7.0
9.2.x worked without any problems. the version 9.7.0 doesn't seem to work anymore under debian linux stable.
When executing ums.sh I get:
`./UMS.sh: 72: exec: jre14/bin/java: not found`
The same happens when I try to execute the java executable directly. 
My best guess is that the problem is, that the java executable seems to be a 32 bit version (according to the file headers).

**Comment by yennor** [comment]
I've took a short look at ums.sh and realized that it would support oder java jdks than the one included.
So i've just deleted the directory "java14" and now it seems to be working.

I guess you should not only check if java exists like you do there:
"if [ -f jre14/bin/java ]; then"
But also if it executes correctly...
Or just don't deliver any java version with the software at all

**Comment by SubJunk** [comment]
@yennor did you download the 64-bit version or the 32-bit one?

**Comment by yennor** [comment]
I've used "General Settings/Check for new updates" so I've just updated what ever ums automatically downloaded. (I didn't even know there is a 32bit and a 64bit version).
I've just downloaded the 64bit version manually and with that it works.
So maybe the question would be if the automatically download version by ums is the right one? (as it seems in 9.2.x it didn't download the correct one)

**Comment by SubJunk** [comment]
Would you be able to check that by downloading a previous 64-bit version and using the auto update to see if it grabs the correct bitness one?

**Comment by yennor** [comment]
alright. I've just downloaded version 9.6.x. Used the updated function from there, and it downloaded the 64bit version. seems like it works correctly in new versions.

**Comment by SubJunk** [comment]
@yennor thanks for checking
