### ISSUE TITLE
Renderer string is incorrect for recent releases of VLC for Apple TV

### ISSUE THREAD

**Issue by ajkessel** [UniversalMediaServer/UniversalMediaServer#2160]
VLC for Apple TV currently advertises itself as "VLC-tvOS/392", which does not match the search string in Apple-TV-VLC.conf. The following substitution will fix the problem:
`UserAgentSearch = VLC-(TV|tvOS)/\d{3}`

**Comment by SubJunk** [comment]
@ajkessel thanks for the fix, should be merged soon :)
