### ISSUE TITLE
Release 9.7.1 not launchable on macos 10.5.5 (19F101)

### ISSUE THREAD

**Issue by slackero** [UniversalMediaServer/UniversalMediaServer#2164]
Universal Media Server is damaged and cannot be opened.
<img width="547" alt="Bildschirmfoto 2020-07-06 um 10 03 52" src="https://user-images.githubusercontent.com/15139/86570355-15ba6180-bf70-11ea-92cd-a79f96b55b07.png">

9.7.0 worked well after opening it once with RIGHT-CLICK > Open

**Comment by SubJunk** [comment]
I just downloaded it from GitHub and opened it with no problems. Maybe the download got corrupted? Can you try in another browser?

**Comment by slackero** [comment]
No changes in another browser, and if download would be corrupted usually the .dmg should result in an error while opening.

But I searched a bit and `xattr -c /Applications/Universal\ Media\ Server.app` did the trick.

**Comment by SubJunk** [comment]
@slackero thanks for the update, is this something we can help on our end, or something specific to your machine?

**Comment by Nadahar** [comment]
@SubJunk It's specific to macOS - it's Apple's way of rejecting software that isn't signed with a key rented form Apple. It's the same old, same old, every iteration of macOS gets more aggressive and I expect that in the end it will be impossible to run anything that hasn't paid Apple their ransom.

Earlier one could right-click and do something to get around it, now that's gone from what I understand, and it requires people to open the terminal and use `xattr`. One day that's bound to stop working as well.

**Comment by slackero** [comment]
> @slackero thanks for the update, is this something we can help on our end, or something specific to your machine?

I think it was specific to my machine (of whatever reason), but guess can happen on any other system too.
Right click to open it for the first time with version 9.7.0 has worked as expected. I did nothing else. Expected same behaviour for the newer release, but … anyway: `xattr` helped.

**Comment by SubJunk** [comment]
Thanks. Please let us know if it happens again :)

**Comment by Nadahar** [comment]
There are many others with this problem on the forum, but it doesn't seem to be specific for 9.7.1. There's no way to tell what mechanism decides this, as Apple keeps all this a secret.

**Comment by SubJunk** [comment]
When we do the website redesign, hopefully soon, I intend to add a notification about that when mac users download it so they at least have the instructions there
