### ISSUE TITLE
WebUI https and authentication configuration issues

### ISSUE THREAD

**Issue by outnos** [UniversalMediaServer/UniversalMediaServer#2169]
When using "web_https=true" the default config says that it wants "UMS.jks" and the password "umsums" https://github.com/UniversalMediaServer/UniversalMediaServer/blob/206c80606c9546ee09fe623ff0cebdaa96864e55/src/main/external-resources/UMS.conf#L1351-L1358
But internal error message says that the keyfile is called \"DMS.jks\" with password \"dmsdms\" https://github.com/UniversalMediaServer/UniversalMediaServer/blob/7338e8e1d6b014bed2672ed011d220d77c2632a3/src/main/java/net/pms/remote/RemoteWeb.java#L116-L121
But this message appears if the error contains UMS.jks (same line as above), but the internal code expects "DMS.jks" https://github.com/UniversalMediaServer/UniversalMediaServer/blob/7338e8e1d6b014bed2672ed011d220d77c2632a3/src/main/java/net/pms/remote/RemoteWeb.java#L153-L162
And the password to be "umsums".

So the finally what needs to be supplied is "DMS.jks" with "umsums" as the password.

When using "web_authentication=true" the BasicAuthenticator is used with an empty string as realm, which isn't allowed and causes the program to crash 
java docs: https://docs.oracle.com/en/java/javase/14/docs/api/jdk.httpserver/com/sun/net/httpserver/BasicAuthenticator.html#%3Cinit%3E(java.lang.String)
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/7338e8e1d6b014bed2672ed011d220d77c2632a3/src/main/java/net/pms/remote/RemoteWeb.java#L277-L287

> DEBUG 2020-07-09 13:07:24.521 [main] Reading web_authenticate: true (default: false)
> ERROR 2020-07-09 13:07:24.522 [main] A serious error occurred during Universal Media Server initialization: realm must not be empty
> DEBUG 2020-07-09 13:07:24.524 [main]
> java.lang.IllegalArgumentException: realm must not be empty
>         at jdk.httpserver/com.sun.net.httpserver.BasicAuthenticator.<init>(Unknown Source)
>         at jdk.httpserver/com.sun.net.httpserver.BasicAuthenticator.<init>(Unknown Source)
>         at net.pms.remote.RemoteWeb$3.<init>(RemoteWeb.java:278)
>         at net.pms.remote.RemoteWeb.addCtx(RemoteWeb.java:278)
>         at net.pms.remote.RemoteWeb.<init>(RemoteWeb.java:134)
>         at net.pms.PMS.init(PMS.java:532)
>         at net.pms.PMS.createInstance(PMS.java:934)
>         at net.pms.PMS.main(PMS.java:1130)

**Comment by SubJunk** [comment]
This will be fixed in the next version, thanks for the detailed report!

**Comment by outnos** [comment]
While that should patch the https keyfile’s name, i dont see a change to the BasicAuthenticator. Which then should still remain broken

**Comment by SubJunk** [comment]
@outnos would it fix it to simply set that to any value, or is something else required?

**Comment by outnos** [comment]
I would believe so, but i had some compilation problems while trying to test it.
On the master it gives:

> [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.622 s <<< FAILURE! - in net.pms.dlna.DLNAMediaInfoTest
> [ERROR] net.pms.dlna.DLNAMediaInfoTest.testContainerProperties  Time elapsed: 3.622 s  <<< FAILURE!
> org.opentest4j.AssertionFailedError:
> 
> Expecting:
>  <"Container: MKV, Size: 5291494, Overall Bitrate: 2619551, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">
> to be equal to:
>  <"Container: MKV, Size: 5291494, Overall Bitrate: 2619552, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">
> but was not.
>         at net.pms.dlna.DLNAMediaInfoTest.testContainerProperties(DLNAMediaInfoTest.java:104)

Which looks like a 1-off error on the overall bitrate probably caused by a dependency version discrepancies, but i edited it to be 1 less and i was able to compile it.
But in my test just setting it to "UMS" worked
> web_authenticate=true
> web.server=test,test
