### ISSUE TITLE
Test DLNAMediaInfoTest.testContainerProperties:104 fails on Manjaro Linux 20.0.3

### ISSUE THREAD

**Issue by outnos** [UniversalMediaServer/UniversalMediaServer#2177]
Im running Manjaro Linux 20.0.3 and a DLNAMediaInfoTest fails with Overall Bitrate being 1 less on my machine than in the test.

> [ERROR] Failures:
> [ERROR]   DLNAMediaInfoTest.testContainerProperties:104
> Expecting:
>  <"Container: MKV, Size: 5291494, Overall Bitrate: 2619551, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">
> to be equal to:
>  <"Container: MKV, Size: 5291494, Overall Bitrate: 2619552, Video Tracks: 1, Video Codec: h265, Duration: 0:00:16.160, Video Resolution: 1920 x 960, Display Aspect Ratio: 2.00:1, Frame Rate: 25.000, Frame Rate Mode: CFR (CFR), Frame Rate Mode Raw: CFR, Matrix Coefficients: BT.709, Audio Tracks: 1 [Id: 0, Language Code: eng, Audio Track Title From Metadata: Stereo, Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 48000 Hz], Mime Type: video/x-matroska">
> but was not.

**Comment by js-kyle** [comment]
Note - I've seen this on Ubuntu 18.04 with the same error

**Comment by SubJunk** [comment]
This is caused by a different MediaInfo version. The version we rely on in UMS is 18.12 so if you run that version it should fix it. Other versions report a slightly different bitrate for some files, maybe they changed the rounding or something. We have an issue to update MediaInfo and just need to do it.
