### ISSUE TITLE
UMS-9.6.2.exe download-Windows opens but never downloads new file

### ISSUE THREAD

**Issue by nesch52** [UniversalMediaServer/UniversalMediaServer#2181]
Deinstalled this version (UMS-9.6.2.exe) without debug info, because it was not possible ! UMS-Download window permanently open without any progess-bar action. BUT this window blocks & prohibits ALL other actions on the PC .No closing possible! Pops up endlessly disturbing ALL other Window actions! Only "Process Hacker" was able to stop this by terminating "JAVAW.exe". Installed latest GitHub-version(UMS-9.7.2.exe) because of permanent "Downloadserver not available" in former version ,allthough a new version was available on GitHub! Testing latest version....

**Comment by SubJunk** [comment]
@nesch52 sorry that you experienced that problem. We fixed it in 9.7.2, that is this line in the changelog https://github.com/UniversalMediaServer/UniversalMediaServer/commit/e74638245310da9d2824141080b1bce896d2c45d#diff-a0493e27f48b50e18312b9f4508fc29dR6
