### ISSUE TITLE
Support psvita

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#220]
Will there be support for psvita in THE futhere

**Comment by Sami32** [comment]
@SubJunk Can be closed.
http://www.psx-place.com/threads/universal-media-server-4-2-2-released-added-ps-vita-support.564/
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/b444deaeea677d8159ef55a03bc24d23ea8bab24/src/main/external-resources/renderers/Sony-PlayStationVita.conf

**P.S.** So many issues, i begin to have doubt never see the end...but some comments are very interesting, teaching.
It will be great to have something like issues's bookmark in Github, but perhaps it is somewhere..8-/

**Comment by DeFlanko** [comment]
I know someone who owns a psvita still i should ask him if i can borrow it to close this out.

**Comment by Sami32** [comment]
@DeFlanko Thanks :-)

Feel free to re-open it if necessary.
