### ISSUE TITLE
Flac files throw NPE with Oppo player, show 3 versions in Trancode folder when it should be streamed.

### ISSUE THREAD

**Issue by jefff888** [UniversalMediaServer/UniversalMediaServer#222]
I am having a problem with an Oppo-105 blu-ray player. I am running UMS with 64-bit Fedora 19 and Oracle Java 1.7.0_40, but this also happens on Windows 7. The important thing I see is in the debug log. Whenever I access a folder containing flac files, UMS throws a Null Pointer Exception for each flac file in the folder. I am then getting unwanted transcoding with 3 versions of the original file. Each triple file set is in its own transcode folder. This makes it impossible to play a list of files. The Oppo can handle flac encoding itself, so this file type should never be transcoded in the first place.

I can not attach the debug zip from UMS 3.3.0 here, but I did so in the UMS support forum. I posted with the same user ID.

**Comment by Sami32** [comment]
@valib @SubJunk Could this issue be closed ? No logs and many improvements since then...

**Comment by jefff888** [comment]
I tried the latest version of UMS and flacs displayed and played correctly. Go ahead and close the issue. 


Jeff

-------- Original message --------

**Comment by Sami32** [comment]
@jefff888 Thanks for your feed back ;-)
@SubJunk Sorry, but it's seem that you'll need to do it ;-)
