### ISSUE TITLE
UMS stops streaming all videos automatically.

### ISSUE THREAD

**Issue by purevertigo** [UniversalMediaServer/UniversalMediaServer#2232]
When streaming to VLC on the Apple TV, UMS randomly stops playing the video which means I have to continually start the video playing again. It happens every time I play something.

Logs Attached.

[ums_dbg_2020-08-28-14-11.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5140205/ums_dbg_2020-08-28-14-11.zip)

**Comment by purevertigo** [comment]
Is there an update on this?

**Comment by SubJunk** [comment]
We are telling the renderer:

```
<res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="195249" colorDepth="8" duration="1:41:17.270" framerate="24p" nrAudioChannels="2" protocolInfo="http-get:*:video/mp4:DLNA.ORG_OP=01" resolution="720x300" sampleFrequency="48000" size="1186581195">http://10.0.0.2:5001/get/98/Legacy+Of+Lies+%282020%29.m4v</res>
```

which seems good, but I can see in the logs:

```
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
DEBUG 2020-08-28 15:34:15.833 [HTTPv2 Request Worker 15] net.pms.network.RequestHandlerV2 Connection error: java.io.IOException: Connection reset by peer
DEBUG 2020-08-28 15:34:15.833 [HTTPv2 Request Worker 15] net.pms.network.RequestHandlerV2 Premature end, stopping...
```

Can you try https://www.universalmediaserver.com/uploads/UMS-connection_reset-70294f1.exe

**Comment by purevertigo** [comment]
How often would I need to do this @SubJunk ?

**Comment by SubJunk** [comment]
@purevertigo I'm not sure what you mean, how often would you need to do what? This is an attempt at a fix. If it works for you then it will make it into the official releases

I have reuploaded the file now

**Comment by purevertigo** [comment]
OK @SubJunk I will test and report back as soon as I can.

**Comment by purevertigo** [comment]
Confirmed. The test build fixes the issue I was having. 

Appreciated @SubJunk

**Comment by purevertigo** [comment]
Same issue again. Play stops randomly.

Logs are attached.



[ums_dbg_2020-09-29-20-30.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5298348/ums_dbg_2020-09-29-20-30.zip)

**Comment by purevertigo** [comment]
Any updates?

**Comment by purevertigo** [comment]
Just wanted to bump this again.

**Comment by purevertigo** [comment]
@SubJunk just wanted to bump this again.. thanks.

**Comment by SubJunk** [comment]
This seems to be getting reported more frequently than it used to. I wonder if it could be caused by a Java update, since I can't think of anything we have changed that would affect it. Could you download Java Runtime Environment 8 from https://www.oracle.com/java/technologies/javase-jre8-downloads.html and replace the UMS Java with that? That would be in the `C:\Program Files (x86)\Universal Media Server\jre-14` directory.

If that doesn't work, maybe you could try using UMS v9 or v8 to see if it is a regression, which would be nice as then we can fix it

**Comment by Smoker1** [comment]
I was on 8.1.0 at the time. Restarted my Computer after Installing the latest Version, and Restarted the PS3. Now seems to be working fine. But yeah, in the Log, it was saying this...........
DEBUG 2020-10-22 13:10:52.165 [HTTPv2 Request Worker 11] Connection error: java.io.IOException: An established connection was aborted by the software in your host machine
DEBUG 2020-10-22 13:11:49.876 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2020-10-22 13:11:51.818 [HTTPv2 Request Worker 12] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 2020-10-22 13:11:51.818 [HTTPv2 Request Worker 12] Premature end, stopping...
DEBUG 2020-10-22 13:11:54.319 [ffmpeg64.exe-12-Cleanup] Stopping process: ffmpeg64.exe-12

**Comment by SubJunk** [comment]
Now that I looked more closely, these might be two unrelated errors

@Smoker1 yours may be related to a firewall or something else (or another instance of UMS) using the same port, going by this link https://www.techinpost.com/an-established-connection-was-aborted-by-the-software-in-your-host-machine/

Please let me know if it happens again.

@purevertigo please try this version https://www.universalmediaserver.com/uploads/UMS-connection_reset-10f263f.exe
It won't stop the error from happening but it might change how we respond to it

**Comment by purevertigo** [comment]
New Logs are attached.


[ums_dbg_2020-11-02-16-14.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5472982/ums_dbg_2020-11-02-16-14.zip)

**Comment by SubJunk** [comment]
@purevertigo did the problem still happen?

**Comment by purevertigo** [comment]
@SubJunk yes it did.

**Comment by purevertigo** [comment]
Any news @SubJunk?

**Comment by SubJunk** [comment]
@purevertigo sorry for the late response. I have added some more logging since I can't see what is happening yet. Please try this and make a new set of logs https://www.universalmediaserver.com/uploads/UMS-connection_reset-1de0172.exe

**Comment by purevertigo** [comment]
Thanks, @SubJunk for continuing to work through this issue.

I have attached new logs.


[ums_dbg_2020-11-24-22-33.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5589544/ums_dbg_2020-11-24-22-33.zip)

**Comment by SubJunk** [comment]
@purevertigo thanks for the logs. It seems that we are receiving communication from VLC that it is done with the stream but I'm not exactly sure about that, please make logs from this, I have added more logging. https://www.universalmediaserver.com/uploads/UMS-connection_reset-951107b.exe

**Comment by purevertigo** [comment]
@SubJunk  Didn't do it this time around so I'll keep testing, but the shares never show up the first time. I have to exit and then re-enter the app (VLC) about 10 or so times before they show. No other DLNA share program does this and it is getting annoying, and it has been doing this since the start.

I have attached logs.



[ums_dbg_2020-11-28-15-09.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5610046/ums_dbg_2020-11-28-15-09.zip)

**Comment by SubJunk** [comment]
I think you are describing a known issue with VLC detection. We have an issue on our tracker https://github.com/UniversalMediaServer/UniversalMediaServer/issues/954 and the VLC forum about it. I just re-posted on their forum to see if there are any updates https://forum.videolan.org/viewtopic.php?f=36&t=134806&p=511446#p511446

It seems to be a timing issue, since if I wait around 15 seconds before browsing on VLC, it works.

**Comment by valib** [comment]
@purevertigo can you check which VLC version is using your TV?

**Comment by purevertigo** [comment]
@valib 3.0.12 (414)

**Comment by valib** [comment]
This is the latest version which should not have this problem. Strange.

**Comment by SubJunk** [comment]
Last time I looked into this I compared what we are doing with what one of our competitors are doing via Wireshark, and I couldn't see any difference, but there obviously must be a difference. I'll do it again soon and see if I notice anything I missed last time.

**Comment by purevertigo** [comment]
thanks @SubJunk

**Comment by SubJunk** [comment]
Sorry, I realised that I was talking about the iOS app while you were talking about the Apple TV app, and I don't have an Apple TV to test, sorry.

**Comment by purevertigo** [comment]
@SubJunk @valib I have attached the latest logs about the original issue of video stopping randomly.

[ums_dbg_2020-12-05-23-27.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5647035/ums_dbg_2020-12-05-23-27.zip)

**Comment by SubJunk** [comment]
I just had a look through your logs @purevertigo and I wonder if you can try unchecking "HTTP Engine V2" in the General Settings tab?
I noticed that the connection reset happens after VLC sends a UPnP SUBSCRIBE request and we respond, but maybe it doesn't like the response, and that is handled differently between those two engines

**Comment by SubJunk** [comment]
Another thing is while I was trawling the internet for this issue, I saw a possible hint, that often this problem is caused by something that wouldn't show up in the UMS logs because it is out of the scope of UMS. Would you be able to capture the network activity with Wireshark and upload it or send it to me? I would need to know the time that the connection error happened.
That would show us the complete picture of the network on your machine instead of just UMS so it might reveal a clue about something that e.g. the router is doing

**Comment by purevertigo** [comment]
I haven't got this in a while now so I'm going to close this issue for now.
