### ISSUE TITLE
Non prettified filenames create scrollbar in web interface V10

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#2239]
In version 10 web interface the actual filename appears in the right hand panel if prettify filenames is not enabled.  

This creates a filename that extends beyond the right information panel and creates a horizontal scrollbar beneath the video.

![image](https://user-images.githubusercontent.com/20376562/92351079-da364200-f12e-11ea-9f7c-7dcb03e59fec.png)

- [x] filename should be truncated

**Comment by SubJunk** [comment]
Done
