### ISSUE TITLE
Avia_Chromecast.conf -- AAC issues

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#224]
# [Avia](http://aviatheapp.com/)
>Avia lets you play, manage and share your personal media. You get seamless access to photos, videos and music from social media sites, your home network, and your device’s local storage. The fun part is sharing it on the big screen. With Chromecast and Avia, it is even easier.

*...Now getting it to work with UMS is challenging*

**When Avia starts up**
`User-Agent: Android/4.2.1 UPnP/1.0 Cling/2.0`
**When Browsing UMS folders**
`User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)`
**When Casting to Chromecast**
`User-Agent: Mozilla/5.0 (CrKey armv7l 1.3.14651) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.0 Safari/537.36, Referer: http://receiver.aviatheapp.com/`
... so basically my User-Agent that I'm using is: `User-Agent=Mozilla` which is kinda terrible... :/

...and to top it off Chromecast only can play a certain set of media:
```
Supported Media Type: https://developers.google.com/cast/supported_media_types
All Google Cast devices at a minimum support the following media types:
Video codecs: H.264 High Profile Level 4.1, 4.2 and 5, VP8
Audio decoding: HE-AAC, LC-AAC, CELT/Opus, MP3, Vorbis
Containers: MP4/CENC, WebM, MPEG-DASH, SmoothStreaming
Level 1 DRM support: Widevine, PlayReady
```

So for starters -- I know that camera recorded material Casts ok... 720p nicely but 1080p is a bit choppy... 

The mediainfo of camera recorded material is:
![720p Media](http://content.screencast.com/users/DeFlanko/folders/Snagit/media/5cb11818-f4fa-4f69-a151-00d268a26d1b/12.28.2013-12.07.png "720p Media")

![1080p Media](http://content.screencast.com/users/DeFlanko/folders/Snagit/media/ed8f8141-1bcd-4532-b5c7-4682613cd15c/12.28.2013-12.10.png "1080p Media")

Where as my Blu-ripped Media is:
![1080p Blu-Ray](http://content.screencast.com/users/DeFlanko/folders/Snagit/media/ac2c03dc-43c2-45e4-a673-f7d170cd9332/12.28.2013-12.11.png "1080p Blu-ray Ripped Media")

So i think where my transcoded videos are failing at is at the Audio level

When I attempt to use `Libfaac` it says it `MEncoder` can't find it -- See reference logs #223 

I'm sure the two issues are related and can be solved easily... thoughts?

**Comment by Sami32** [comment]
@DeFlanko @SubJunk Did the latest UMS version solved it ?

**Comment by DeFlanko** [comment]
i think this can be closed.  Several alternative options can be used now for me at least, one being through chrome web interface back i can cast directly from there...
