### ISSUE TITLE
Save log zip to desktop by default

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2247]
See https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2124#issuecomment-695110583

**Comment by dotslash21** [comment]
Hi @SubJunk, Can I take up this issue?

**Comment by dotslash21** [comment]
Hi @SubJunk, I did some digging through the code and observed that the default log file save location is given by `PmsConfiguration.getDefaultLogFileFolder()`. Currently, the default save location is generated using the following rules:

1. (On Linux only) path to `/var/log/ums/%USERNAME%/`.
2. Path to profile folder (`~/.config/UMS/` on Linux, `%ALLUSERSPROFILE%\UMS` on Windows and `~/Library/Application Support/UMS/` on Mac).
3. Path to the user-defined temporary folder specified by the `temp_directory` parameter in UMS.conf.
4. Path to system temporary folder.
5. Path to the current working directory.

At this point, I have some questions,

1. Do I save the log zip to the desktop for all platforms at first then try all other existing fallback location in the order?
2. If not, then what should be the priority saving to desktop.
3. Should I save to desktop for all the platforms?

**Comment by SubJunk** [comment]
@dotslash21 yes you're very welcome to work on this. Good questions, thanks. I think attempting to save to desktop is good for all operating systems
