### ISSUE TITLE
REQUEST - Increase Network Icon Size

### ISSUE THREAD

**Issue by purevertigo** [UniversalMediaServer/UniversalMediaServer#2250]
Can a UMS dev, please increase the resolution of the network icon, on my TV it is very pixelated when next to the other icons.

It would be very much appreciated.

photo attached.

![IMG_4026](https://user-images.githubusercontent.com/6506461/93970835-3b5a4880-fdb2-11ea-833b-336ccfd7c5be.JPG)

**Comment by SubJunk** [comment]
We send a bunch of icon options to TVs including 256x256 PNGs, so it seems your TV is choosing a lower quality one. I wonder why. Are you still around to help test this?

**Comment by purevertigo** [comment]
@SubJunk yes definitely still around.

**Comment by SubJunk** [comment]
Cool, can you try https://www.universalmediaserver.com/uploads/UMS-icon-standard-dimensions-a3c572d.exe

**Comment by purevertigo** [comment]
no that didn't solve the issue @SubJunk stil pixelated.

**Comment by SubJunk** [comment]
Hmm ok, do any other media servers have a clear logo up there? If we can find one that works we can use Wireshark to see how they did it

**Comment by purevertigo** [comment]
yes. HDhomerun has a clear logo.

**Comment by SubJunk** [comment]
Cool, can you please use Wireshark to capture the packets that HDhomerun sends? It seems that is a paid product so I can't test it myself.
You don't need to know how to use Wireshark, just start recording, then start HDhomerun and the TV, then stop the recording and send/attach the dump. Then I can see what they're sending to the TV to make it display better quality.

**Comment by purevertigo** [comment]
@SubJunk tried this and then I realised HDHOMERUN doesn't come from my server but from the network.

**Comment by SubJunk** [comment]
Ok, maybe this is a limitation with your TV then, and not something we can fix

**Comment by Nadahar** [comment]
UMS offers multiple resolutions. Renderers are supposed to pick the most suitable for their use, but it seems to me that some implementation are "lazy" and simply picks one - probably the first.

**Comment by valib** [comment]
@Nadahar for me it seems that it picks the last one. The 48x48 PNG or JPG. To confirm that we need the log. I have one question. Why do we offer the 256x256 PNG but not the 256x256 JPEG?

**Comment by valib** [comment]
@SubJunk we can try to change the order and start with the 48x48 and finish with 256x256 and we will see. Just change the `PMS.xml`

**Comment by Nadahar** [comment]
@valib I'm pretty sure I've come across others that picks the first, so I don't think it's possible to "hack" this to work optimally.

**Comment by SubJunk** [comment]
If anyone is interested, this is the branch I had @purevertigo test https://github.com/UniversalMediaServer/UniversalMediaServer/compare/icon-standard-dimensions?expand=1

I had a look in the DLNA standard PDFs and I couldn't see anything about which sizes are recommended, but yeah I am inclined to think this is the fault of the device

**Comment by SubJunk** [comment]
Maybe we could try removing the 48x48 images from PMS.xml too, so that renderers can't choose that one

**Comment by purevertigo** [comment]
I can test if you need @SubJunk @valib

**Comment by SubJunk** [comment]
I'm not sure if it's a good idea to remove the 48px one since even if that works for your renderer, it might break some others. I'm sorry to say it looks like the device is at fault here and I don't see how we can safely do a workaround. I'll close this issue. Maybe you could contact their support and see if they have any firmware patches available

**Comment by purevertigo** [comment]
@SubJunk the app is VLC on the apple tv
