### ISSUE TITLE
Plugins needed?

### ISSUE THREAD

**Issue by felixaushartha** [UniversalMediaServer/UniversalMediaServer#2253]
I'm new here. I looked for a Media Server to adapt for own projects in Java. The UMS has rests of plugin support in the code.
I think, it is possible, to reactivate the plugin support. is this needed from others?

**Comment by SubJunk** [comment]
Hello and welcome 👍 

When we supported plugins before, there were some but gradually they broke as our code moved on and the authors didn't update them. One of the most popular plugins was MovieInfo and we are adding that functionality in the upcoming v10 anyway

Do you want to make a new plugin for UMS?

**Comment by felixaushartha** [comment]
I think, the best way is to restrict the development of plugins. For the most cases of applications only a small set of basic classes are needed. The usage of  other functions of UMS without the plugin interface must be forbidden. This is a way, to isolate the UMS kernel development from the plugin development. 
I looked for a Media Server with more support for Photos. In PLEX and so on the support for this media is insufficent. In UMS a plugin with support for own photos and movies, sorted by folders, date, keywords or locations, based on the informations in the photos (EXIF..), this is my dream.

**Comment by SubJunk** [comment]
Stale
