### ISSUE TITLE
illegal reflective access by net.pms.service.ProcessManager

### ISSUE THREAD

**Issue by yohonet** [UniversalMediaServer/UniversalMediaServer#2264]
The following error message appears at startup (using version 9.8.1 under linux):

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.pms.service.ProcessManager (file:/home/yoho/ums-9.8.1/ums.jar) to field java.lang.ProcessImpl.pid
WARNING: Please consider reporting this to the maintainers of net.pms.service.ProcessManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Attached trace:
[ums_dbg_2020-10-15-18-11.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5386317/ums_dbg_2020-10-15-18-11.zip)

**Comment by SubJunk** [comment]
I have noticed that happening too when I build the program. I don't think it causes any problems but it would be nice to not have that warning.

**Comment by yohonet** [comment]
Yes it works fine but last warning suggests something will go wrong in future releases.

**Comment by Nadahar** [comment]
The only way to avoid the warning is to stick to Java 8. There's nothing wrong with the code other than that Oracle decided that using reflection to access unavailable information has become "illegal". They will probably block it completely in some future Java version, but for now they just whine about it.

**Comment by SubJunk** [comment]
The good thing about us now bundling Java is that we have control over the impact of this. For now this is a low priority thing - I would welcome a contributed fix but likely won't work on it myself - but if it isn't fixed by the time they remove that support then I'll fix it.
