### ISSUE TITLE
Improve web interface pages with no results

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#2265]
If a web interface page does not have any results it should have an improved style so that it looks nicer.

**Comment by SubJunk** [comment]
More importantly it should have the ability to go back instead of just being broken

**Comment by Neocazen** [comment]
It would also be interesting to have an html5 player replacing the "almost deceased" flash.

**Comment by SubJunk** [comment]
@Neocazen it already uses HTML 5 by default, we just support manually changing to Flash for browsers that don't support HTML 5

**Comment by SubJunk** [comment]
Done
