### ISSUE TITLE
Compatibility with Showtime

### ISSUE THREAD

**Issue by lprot** [UniversalMediaServer/UniversalMediaServer#227]
UMS is neither recognise, neither compatible with https://showtimemediacenter.com/
Can you please install Showtime on Linux/PS3/RPI and check it against UMS?
What I found so far - UMS having issues...

**Comment by Sami32** [comment]
@SubJunk Can be closed.
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/renderers/Showtime3.conf
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/renderers/Showtime4.conf
