### ISSUE TITLE
BUILDING.txt needed

### ISSUE THREAD

**Issue by paul-hammant** [UniversalMediaServer/UniversalMediaServer#2284]
I get:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:17 min
[INFO] Finished at: 2020-11-12T09:03:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:9.8.3-SNAPSHOT: Could not find artifact jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 in 4thline-repo (http://4thline.org/m2) 
```

I looked in the README for a "building ums" section, but couldn't see it. Noobs should be catered or :)

I was going to go on and do the Docker step after that, as the Dockerfile isn't getting a release from anywhere, it's assuming ums.jar exists (relatively?) meaning it must have been locally built.

**Comment by valib** [comment]
@paul-hammant see the Wiki https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-build-UMS

**Comment by paul-hammant** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/pom.xml says that cuelib is not mavenized (as a comment inline). I'll try building that first. 

Cuelib is not mentioned in the "How to build UMS" page.

I will report back.

**Comment by paul-hammant** [comment]
Cuelib was on GoogleCode. On GitHub, `tnozaki/cuelib` is the one of three with the most recent commits (6 years ago). It is an Ant project though, not Maven.  I'm thinking there's some other place that the fine UniversalMediaServer devs are maintaining their fork of Cuelib though.  Advice?

**Comment by paul-hammant** [comment]
FindJar thinks that the only public reference for Cuelib classes is here - https://www.findjar.com/class/jwbroek/cuelib/CueSheetToXmlSerializer.html

There's many independent copies of Cuelib in git - https://github.com/search?q=CueSheetToXmlSerializer&type=code - some embedded inside other projects

**Comment by Nadahar** [comment]
You don't have to handle cuelib or any other dependency manually. Just follow the instructions given, point 6 should solve this particular problem: https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-build-UMS#6-resolve-and-install-external-libraries

**Comment by paul-hammant** [comment]
This one works - https://github.com/carlwilson/cuelib - if the GAV and package are changed to match expectations.

**Comment by paul-hammant** [comment]
I was following "Quick builds" -
  
![image](https://user-images.githubusercontent.com/82182/98977838-fc728480-2510-11eb-80b3-1ceb99a4dfab.png)

**Comment by paul-hammant** [comment]
Conclusion: Acquisition of the cuelib jar allows the quick build to go from start to finish with **no other setup steps**, and yield:

```
ums-9.8.3-SNAPSHOT-distribution.tar.gz
ums-9.8.3-SNAPSHOT-jar-with-dependencies.jar
ums-9.8.3-SNAPSHOT.jar
```

I've not tried out those binaries yet, but I am guessing they work.

**Comment by Nadahar** [comment]
The "quickbuild" works once you have followed the full procedure at least once. You must however run `mvn external:install" at one point to download non-Mavenized dependencies. If you do that, there's no need to manually fetch anything.

**Comment by paul-hammant** [comment]
I didn't run `mvn external:install` at all. Probably an accident that I had ffmpeg and others setup already.

One choice the project has is to include https://github.com/carlwilson/cuelib - as a sub-module.

**Comment by Nadahar** [comment]
FFmpeg etc gets pulled during "normal" build. The "external:install" step is only needed for non-Mavenized Java dependencies like cuelib and a few others. I would still run it to make sure you don't get problems with your builds.

**Comment by SubJunk** [comment]
Instead of BUILDING.txt we have https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/BUILD.md which points to the article Nadahar mentioned. If it doesn't work after you follow the full instructions please let us know.

**Comment by paul-hammant** [comment]
ok, thanks

**Comment by SubJunk** [comment]
Feel free to reopen in that case, thanks for your interest in UMS :)
