### ISSUE TITLE
NullPointer Exception when using VLC Web Video Engine

### ISSUE THREAD

**Issue by fu2x** [UniversalMediaServer/UniversalMediaServer#2291]
java.lang.NullPointerException: Cannot invoke "net.pms.dlna.DLNAMediaAudio.getAudioProperties()" because the return value of "net.pms.io.OutputParams.getAid()" is null
	at net.pms.encoders.VLCVideo.getEncodingArgs(VLCVideo.java:264)

[Here](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/6373d57e0d4461be95f5b9f9c8f536c7b21c1989/src/main/java/net/pms/encoders/VLCVideo.java#L264) a check for params.getAid() != null is missing as it is implemented for example in line [527](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/6373d57e0d4461be95f5b9f9c8f536c7b21c1989/src/main/java/net/pms/encoders/VLCVideo.java#L527) in the same file.

Use Case:
I have a .m3u file with a list of local network streams (rtsp://).
Opening the playlist file shows the streams as single videos.
In the preparation of the transcoding with VLC Web Video Engine the exception occurs.

**Comment by SubJunk** [comment]
Thanks for reporting it and finding the fix in the code, it will be in the next release
