### ISSUE TITLE
WEB-feeds don't work.

### ISSUE THREAD

**Issue by antifarben** [UniversalMediaServer/UniversalMediaServer#230]
When I try o open a web stream I always get an error.

The first error line is always `Failed to resolve hostname …: Name or service not known` so I expect that it could be related to some resolving issue.
DNS works on this machine flawlessy elsewhere.

```
DEBUG 2014-01-18 15:05:32.396 [ffmpeg-3] Starting /home/mediaserver/apps/universalmediaserver/ums-3.3.0/linux/ffmpeg -y -loglevel warning -i http://feedproxy.google.com/~r/topgearliveofficial/~5/9avW87K-cns/tgl_podcast_2012_ep3.mp3 -c:a ac3 -c:v mpeg2video -f vob -bufsize 1835000 -maxrate 11000000 -g 5 -q:v 1 -qmin 2 -qmax 3 -q:a 3 /tmp/universalmediaserver/ffmpegwebvideo_17_1390053932067
DEBUG 2014-01-18 15:05:32.397 [ffmpeg-3] Reading pipe: /tmp/universalmediaserver/ffmpegwebvideo_17_1390053932067
DEBUG 2014-01-18 15:05:32.434 [Thread-17] [tcp @ 0x9a88f20] Failed to resolve hostname feedproxy.google.com: Name or service not known
DEBUG 2014-01-18 15:05:32.435 [Thread-17] http://feedproxy.google.com/~r/topgearliveofficial/~5/9avW87K-cns/tgl_podcast_2012_ep3.mp3: Input/output error
```

PS: Thank you very much for UMS. I love it. So far I can tell it is the most useful mediacenter I saw so far. So this is really great work from you. Thank you for this.

**Comment by Sami32** [comment]
@SubJunk Can be closed. I cannot reproduce it on Windows. Some of the developpers use it on Mac, Windows and never report it recently.

**Comment by antifarben** [comment]
I'm not needing this any more and as nobody else seem to have this issue anyway I will close this here.
