### ISSUE TITLE
Support for Samsung The Frame QLED TV (partially solved)

### ISSUE THREAD

**Issue by jkl16** [UniversalMediaServer/UniversalMediaServer#2315]
Samsung The Frame QLED TVs are not being recognized correctly by UMS. I have tried both 9.8.2 and 9.8.3-SNAPSHOT from master.
I believe that `Samsung-UHD-2019.conf` is the correct renderer for those devices (4K, no DTS, etc.)
Some examples of model numbers are:

- GQ43LS03TAUXZG (2020 model, German version)
- QE43LS03TAUXXH (2020 model, European version)
- QE55LS03RAUXXH (2019 model, European version)
- QN32LS03TBFXZA (2020 model, US version)

Changing UserAgent and UpnpDetails regex fixes the issue.
`
UserAgentSearch =(QN|UE|GQ|QE)\d{2}(Q|RU|LS)[0-9]\d`
`UpnpDetailsSearch = (QN|UE|GQ|QE)\d{2}(Q|RU|LS)[0-9]\d
` 

However I have encountered another problem possibly not related only to this specific renderer.
For some movies with only embedded subtitles, which should be streamed I am getting the following message in logs:

> This video has embedded subtitles that must be transcoded  

The movie format is f:mkv, v:h264, a:ac3, m:video/x-matroska, embedded subs: SUBRIP
In the attached logs one example of such behavior is _Sala.Samobojcow.Hejter.2020.PL.720p.BDRiP.x264-PSiG.mkv_

The issue seems to be caused by empty `SupportedInternalSubtitlesFormats` for that renderer , but according to the description from `DefaultRenderer.conf` that property is overriden by `si:` value, which is set to `si:ASS|SUBRIP|VOBSUB` in this case.

Is it a bug in detection algorithm or should `SupportedInternalSubtitlesFormats` be present no matter what is defined in `si:`?

[ums-dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/5691387/ums-dbg.zip)

**Comment by SubJunk** [comment]
@jkl16 thanks for this, I will update the renderer regex you provided. Also I think the bug you described has been fixed. Please let us know if it is still there in the latest release
