### ISSUE TITLE
cuelib resource crashes build

### ISSUE THREAD

**Issue by anthraxn8b** [UniversalMediaServer/UniversalMediaServer#2322]
Trying to build UMS on Fedora 31.

    mvn clean
    mvn external:install
    mvn package -P linux-arm64

Fails with:

    [ERROR] Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:9.8.3-SNAPSHOT: Could not find artifact jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 in 4thline-repo (http://4thline.org/m2) -> [Help 1]

The instructions to build do not include additional information about cuelib:
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-build-UMS#6-resolve-and-install-external-libraries

The only thing that seems to solve my problem is adding it with scope "system" and define the "systemPath":

    
    <dependency>
        <groupId>jwbroek.cuelib</groupId>
        <artifactId>cuelib</artifactId>
        <version>${cuelib-version}</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/src/main/external-resources/lib/cuelib-1.2.1-2008-06-13.jar</systemPath>
    </dependency>

**Comment by valib** [comment]
@anthraxn8b is seems like the MediaInfo library is not properly installed or initialized.

**Comment by SubJunk** [comment]
That's strange, it is supposed to be taken care of by `external-maven-plugin`. Which version of Maven are you using?
