### ISSUE TITLE
my subs dont work

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#233]
This is what i have my subs set to: ```dut,off;jpn,eng;*,dut;eng,off;*,und;*,*```
if i do only ```*,dut``` its working else it will go back to english subs
when there needs to be dutch sub it well so none or english
i have had this problem with 2 eps of a serie now and a movie

what can i do to fix it

**Comment by Sami32** [comment]
@Goten87 @SubJunk @valib Could this issue be closed ?
Perhaps `dut,off;eng,off;*,dut;*,eng;*,und` will work fine ?

**Comment by Nadahar** [comment]
See #372
