### ISSUE TITLE
Deinstallation does not remove autostart entry for wrapper.exe

### ISSUE THREAD

**Issue by pipin77** [UniversalMediaServer/UniversalMediaServer#2343]
The deinstallation routine does not remove the autorun entry for the wrapper.exe;

HKLM\System\CurrentControlSet\Services			

Digital Media Server	Universal Media Server: Java UPnP AV/DLNA Media Server		File not found: D:\ums\Universal Media Server\win32\service\wrapper.exe -s D:\ums\Universal Media Server\win32\service\wrapper.conf		

If I delete it by myself I do need administrator rights.

**Comment by SubJunk** [comment]
Ah yeah I can see we haven't handled that in the code, good catch

**Comment by pipin77** [comment]
I noticed that ums was still running as service although I had it installed new (same folder/location). 

And it had two autostart entries.  Still not sure, if this relates to the same bug.

**Comment by SubJunk** [comment]
Yeah the service is basically ignored on uninstall right now. It wouldn't be hard to fix
