### ISSUE TITLE
Fully played marking broken on Samsung?

### ISSUE THREAD

**Issue by pipin77** [UniversalMediaServer/UniversalMediaServer#2344]
It seems that in 10.0 the fully played marking with an overlay is broken.

**Comment by SubJunk** [comment]
@pipin77 I just tested and it works for me, can you attach logs from when it broke?

**Comment by pipin77** [comment]
I will test it on my second TV but I have only Samsung and with version 9.8.3 because I had the same problem with the alpha version.

Will attach the logs after this.

**Comment by pipin77** [comment]
Ok its strange. 
Its working now. Kind of any way. 

Some files are only marked if I play them through on fast forward.

**Comment by SubJunk** [comment]
@pipin77 that is strange. I think that timing code has a lot of room for improvement on some devices. It can depend on what the client sends to us, and probably depends on whether the file is being transcoded too.
Can you post logs from when you fully play a file and it is not marked fully played?

**Comment by pipin77** [comment]
Sorry,

couldn't do some logs. 

But the behaviour seems to be restricted to smaller files.

**Comment by SubJunk** [comment]
@pipin77 ok, but there's not much I can do without logs. I'll close this issue since it seemed stalled but please reopen it if you manage to get logs
