### ISSUE TITLE
problems displaying raw images - outofmemory, some images can't be displayed

### ISSUE THREAD

**Issue by rnnr** [UniversalMediaServer/UniversalMediaServer#235]
I've installed version 3.4.0. I run "outofmemory" when I'm displaying images.

The original formats are PEF and DNG and the thumbnail is provided for them using DCRAW thumbnailer but after showing tens to hundreds images UMS runs out of memory and crashes. 

The other problem is that for some reason some images can't be displayed - the TV (Samsung UE40F6400) just keeps "loading" and I had to cancel the actio and skip the image. So far it seems that for certain images always, albeit I've not found any difference between images displayed and images not displayed.

**Comment by Sami32** [comment]
@rnnr Do you have some log ? Did the latest UMS version solved this issue ?
@SubJunk Good to know ;-) because my little TV in the bedroom have some problems...
It look like without log...and if i remember well @ExSport use a lot his camera with RAW support and maybe other format as well.
