### ISSUE TITLE
Poll for updates every 24h

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2353]

**Comment by NeelakshSharma** [comment]
Hi @SubJunk, I'm looking for an Open Source Contribution. Can you help me out in giving the required context for this issue? Thanks.

**Comment by SubJunk** [comment]
@NeelakshSharma this is actually not a good time for this story because in v12 we have a big rewrite of our GUI, so I will close this issue for now. Please feel free to contribute to another story :)
