### ISSUE TITLE
Often netwok port results blocked, therefore UMS cannot work

### ISSUE THREAD

**Issue by Simone98RC** [UniversalMediaServer/UniversalMediaServer#236]
UMS reports free network ports as blocked, rarely it works without error messages.
I already checked if these ports were really blocked, but it was not.
Please fix it, in future releases you could set a casual port if default (5001) isn't accessible.

**Comment by Arglanir** [comment]
Using Windows 10's resource monitor, I can see after UMS shutdown, that the port 5001 is still used, but attached to no process.
So if I restart UMS, it cannot bind to the port 5001 and thus says it cannot work.
![image](https://cloud.githubusercontent.com/assets/5308010/9833649/555c1810-599f-11e5-84a5-f98ada1bb1cb.png)
Is it the same bug or should I start another?

**Comment by Nadahar** [comment]
@Arglanir It's probably the same bug. We need to figure out what causes this to be able to solve it. This might be a stupid question, but you do close UMS on the ```Quit``` button and not by clicking ```x``` on the window? I'm also wondering if run UMS from a administrator account, and if you have [UAC] (https://en.wikipedia.org/wiki/User_Account_Control) enabled or not?

It would also be great if you could create trace logs of this happening (closing down without releasing the port) and then post the log [in this thread] (http://www.universalmediaserver.com/forum/viewtopic.php?t=1656).

**Comment by Arglanir** [comment]
Yes I quit it by using the "Quit" button (not the X button of course, as it only minimizes it)
I was not running it as administrator to it was not possible for UMS to change it's own files.
I tried to make the error appear today by restarting UMS a lot of times (with port 5002) but I did not succeed in bugging UMS.

But even when it's shutdown and not running, in the Resource monitoring window I still have 5 weird local connections to UMS configured port 5002 (but not attached to a process). But they disappear after some time.

Using port 5001, UMS did not succeed in starting. (I cannot log to the UMS web server so [here are the debug files](https://dl.dropboxusercontent.com/u/1889097/ums_dbg_pb_port5001.zip))
But there are a lot of connections for the local port 5001 that have been created (but still not attached to a process).

I restarted using port 5002, and it worked, but a lot a

**Comment by Nadahar** [comment]
@Arglanir 
> I was not running it as administrator to it was not possible for UMS to change it's own files.

Could you please rephrase this sentence as I'm not sure what you mean.

Are you running UMS as a service?

**Comment by skeptical** [comment]
@Arglanir this sounds (maybe) similar to the "lingering UMS instance" bug on Windows, described by @ExSport and others in [this discussion](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2920&start=20#p15203) concerning a separate issue, which triggered some [ultimately inconclusive](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/489#issuecomment-85193485) investigation of the issue as part of #489. Basically we have reports that on Windows sometimes the previous UMS instance takes 3-6 minutes to shut down and release its network assets, preventing proper startup of any subsequent UMS instance for that period. This is apparently a longtime bug that exists in PMS also.

If you could try starting UMS only when there aren't any other *java.exe* and *javaw.exe* processes running and seeing if behaviour is any better, then we'll know whether you're experiencing some variant of it also.  Note that apparently the lingering UMS process isn't killable from Task Manager, one can only wait for it to shut down on its own.

**Comment by Arglanir** [comment]
Ok thanks. I'll check that next time.

**Comment by polygirl** [comment]
@Simone98RC it's been some time since you reported this so we hope it's still not an issue for you, but on the General settings tab we have an option to  force the port of the server, which is 5001 by default to any other port and this may fix your issue.  If it doesn't please feel free to reopen this issue by attaching full TRACE logs as described in the new issue template.
