### ISSUE TITLE
Show the address of the web interface on the Status tab

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2372]
At the moment we have a button to open the web interface in the Java GUI, and we list the address of it on the Logs tab, but it would be useful to have the address visible on the Status tab itself so it is easier to see.

The same text as the logs can be used, e.g.
`Web interface is available at: http://192.1.1.1:9001`

**Comment by Chris211313** [comment]
I'd love to grab this as a first issue?

**Comment by SubJunk** [comment]
@Chris211313 yes please :)

**Comment by Chris211313** [comment]
Seeing some issues when running the setup guide. Executing the Maven commands is failing when it tries to download jaudiotagger from bintray. Looking at bintray, it appears they've retired the service. Are you aware of this?

My solution would have been to install this manually into the Maven repo. Unfortunately I can't seem to find the jar file in the central repo. Do you guys have a workaround available for this issue?

**Comment by Nadahar** [comment]
I have tried to contribute to a solution with this PR: https://bitbucket.org/ijabz/jaudiotagger/pull-requests/67

I have gotten no response in quite a while though, so it doesn't seem like the author/maintainer is interested :disappointed:

**Comment by Chris211313** [comment]
FYI, I compiled the third party library myself and installed it into the local Maven repo. This allows me to compile. I'm happy to continue setting up my development environment and address the issue in this ticket. We can always revisit this issue in another ticket :)

**Comment by valib** [comment]
@Chris211313 the issue with the jaudiotagger repository is fixed in #2513

**Comment by valib** [comment]
@Nadahar it seems that the developer tried to use different repositories like https://repo.spring.io/plugins-release/ for version 2.2.6 and the current https://repository.mulesoft.org/nexus/content/repositories/public/ for versions 2.2.6 and 2.2.7.

**Comment by Nadahar** [comment]
@valib I don't think that's the developer, but other people that have wanted the newer versions. I don't really understand the problem, if he just merges the PR I made and follow the instructions, he could have 2.2.5, 2.2.6 and 2.2.7 available on Maven Central in less than one hour of "work".

**Comment by valib** [comment]
@Nadahar maybe this is not the original developer but they continue with this code and it works for us.

**Comment by Nadahar** [comment]
@valib Ok, the project you're pointing to is the same that I've made a PR to. But, the one you used comes from here: https://github.com/goxr3plus/jaudiotagger

I don't like to use other repositories anyway, I think everything should be on Maven Central, because you never know when those other repos "die"/are shut down, just like what happened with bintray. Things that are on Maven Central will stay available, so there's no risk that builds will suddenly stop working in the future.

**Comment by valib** [comment]
@Nadahar agree with you.
