### ISSUE TITLE
Music playback messed up 

### ISSUE THREAD

**Issue by divanikus** [UniversalMediaServer/UniversalMediaServer#238]
Something is definitely wrong with Android as DMC and separate renderer.
If i connect with Bubble UPnP from my Tablet using Local Renderer, everything works fine, FLACs are shown, they are playable and ok.
If I choose to use my Yamaha receiver as media renderer (recognized as Streamium), I cannot play my FLACs properly. Whatever I choose it plays wrong file! Renders states it is playing the one I have choosed, but UMS's log says it plays another. Everything is messed up. Same problem with Samsung Allshare renderer (2012's TV).
If I use Skifta instead of Bubble UPnP, I see all my FLACs duplicated and none of them can be played.
If I connect using my receiver directly, everything is ok and perfectly playable. Also no problem with any other devices connecting directly. 
MP3s are played as they should even in DMC mode.

**Comment by Sami32** [comment]
@divanikus @n4pst3rking Did the latest UMS version solved this issue ?
@SubJunk https://github.com/n4pst3rking/UniversalMediaServer/commit/2e22234fa4575b1a399e21a87c10a3709b82b74c https://github.com/UniversalMediaServer/UniversalMediaServer/pull/340 It's seem that it was fixed long ago.

**Comment by polygirl** [comment]
@divanikus @n4pst3rking thanks for reporting this. It appears that this has now been resolved so we are closing, but if you continue to experience the same issue, please feel free to reopen with full TRACE logs
