### ISSUE TITLE
Fix web interface video playback in Edge

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2383]
Edge doesn't understand the format we send it. We already send different formats depending on the browser so we just need to do the same for Edge

**Comment by SubJunk** [comment]
Maybe. I was using Edge on Windows 10 when I reproduced it

**Comment by Manishpandey11** [comment]
Hi ,I want to work on this issue
please assignee this issue to me

**Comment by SubJunk** [comment]
@Manishpandey11 first it should be reproduced because maybe it works in the latest UMS, can you do that?

**Comment by SubJunk** [comment]
I just tested and it is working already, closing
