### ISSUE TITLE
Use automatic bitrate setting as default.

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#2397]
@SubJunk why we not set the automatic bitrate as default when we stated  in tooltip `The automatic settings will serve the maximum quality for your system and are highly recommended`? We can add to the notes that user can experiment with the default bitrate to achieve better video quality. There are several users dealing with the problems  that the video is not working properly because the bitrate setting.

**Comment by SubJunk** [comment]
Yup let's do it

**Comment by valib** [comment]
Done in #2399

**Comment by SubJunk** [comment]
Let's leave the issue open until the code merges? Then it's easier to track

**Comment by valib** [comment]
@SubJunk it depends on you if you approve the #2399

**Comment by SubJunk** [comment]
The PR goes beyond this issue so I'll need to test and review the other changes

**Comment by valib** [comment]
#2399 merged
