### ISSUE TITLE
A serious error occurred during Universal Media Server initialization: Resource "button-restart-requiredF٠.png" not found

### ISSUE THREAD

**Issue by meratkha** [UniversalMediaServer/UniversalMediaServer#2398]
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٢٩٧ [main] Could not create "/var/log/UMS/meratkha": Unable to create directory /var/log/UMS/meratkha
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٢٩٨ [main] Default logfile folder set to: /home/meratkha/.config/UMS
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٦١ [main] LogBack started with configuration file: /home/meratkha/ums-10.1.0/logback.xml
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٦٦ [main] Starting services
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٦٧ [main] Starting ProcessManager
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٧٢ [Process Terminator] ProcessTerminator is starting
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٧٣ [main] Starting SleepManager
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٧٣ [main] SleepManager doesn't support current platform
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٧٩ [main] Thu Feb 18 11:18:09 CET 2021
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٣٧٩ [main] Reading cred.path: "/home/meratkha/.config/UMS/UMS.cred" (default: "")
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٢ [main] Writing PID: 10220
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٧ [main] Reading show_splash_screen: false (default: true)
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٧ [main] 
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٧ [main] Starting Universal Media Server 10.1.0
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٨ [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٨ [main] https://www.universalmediaserver.com
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٨ [main] 
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٨ [main] Build: bc9b6632f (2021-02-16)
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٨ [main] Java: OpenJDK 64-Bit Server VM 15.0.2 (64-bit) by AdoptOpenJDK
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤١٩ [main] OS: Linux 64-bit 5.4.0-65-generic
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢١ [main] Maximum JVM Memory: 1.3 GiB
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٧ [main] Language: Arabic
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٧ [main] Encoding: UTF-8
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٧ [main] 
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٧ [main] Working directory: /home/meratkha/ums-10.1.0
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٧ [main] Temporary directory: /tmp/UMS-meratkha
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] Logging configuration file: /home/meratkha/ums-10.1.0/logback.xml
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] Logfile: /home/meratkha/.config/UMS/debug.log
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] 
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] Profile directory: /home/meratkha/.config/UMS
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] Profile directory permissions: drwx
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٨ [main] Profile configuration file: /home/meratkha/.config/UMS/UMS.conf
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٩ [main] Profile configuration file permissions: -rw-
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٩ [main] Profile name: jedpc
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٩ [main] 
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٢٩ [main] Reading web_conf: "/home/meratkha/.config/UMS/WEB.conf" (previous: null, default: "/home/meratkha/.config/UMS/WEB.conf")
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٠ [main] Web configuration file: /home/meratkha/.config/UMS/WEB.conf
WARN  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٠ [main] Web configuration file not found: File "/home/meratkha/.config/UMS/WEB.conf" not found
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٠ [main] 
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٥ [main] Using database URL: jdbc:h2:/home/meratkha/.config/UMS/database/medias
INFO  ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٥ [main] Using database located at: "/home/meratkha/.config/UMS/database"
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٤٣٦ [main] Database logging is disabled
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٠٣ [main] Database file count: 66
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٠٣ [main] Database version: 23
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٠٣ [main] Starting check of database tables
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٢٣ [main] Reading run_wizard: false (default: true)
ERROR ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٤٥ [main] A serious error occurred during Universal Media Server initialization: Resource "button-restart-requiredF٠.png" not found, please check your pattern (button-restart-requiredF%d.png) and indices (٠-٢٤)!
DEBUG ٢٠٢١-٠٢-١٨ ١١:١٨:٠٩.٦٤٧ [main] 
java.lang.IllegalArgumentException: Resource "button-restart-requiredF٠.png" not found, please check your pattern (button-restart-requiredF%d.png) and indices (٠-٢٤)!
	at net.pms.newgui.components.AnimatedIcon.buildAnimation(AnimatedIcon.java:554)
	at net.pms.newgui.LooksFrame.<init>(LooksFrame.java:102)
	at net.pms.PMS.init(PMS.java:479)
	at net.pms.PMS.createInstance(PMS.java:882)
	at net.pms.PMS.main(PMS.java:1048)

**Comment by SubJunk** [comment]
@meratkha thanks for reporting this. Do you get the same error on 10.0.1 or is this new to 10.1.0?

**Comment by SubJunk** [comment]
I have reproduced this by changing my language to Arabic

**Comment by SubJunk** [comment]
This bug was introduced in 9.6.0

**Comment by meratkha** [comment]
I think that the problem is related to the so-called Indian numbers, which we see here: 
java.lang.IllegalArgumentException: Resource "button-restart-requiredF٠.png" not found.....
so the real name of the png is: button-restart-requiredF0.png not button-restart-requiredF٠.png... Because in the Indian numbers the (0) is written (.), and the rest of the numbers (1,2,3,4,5,6,7,8,9) are written (١,٢,٣,٤,٥,٦,٧,٨,٩)

**Comment by valib** [comment]
@SubJunk to fix it the Locale should be set in the AnimatedIcon class. In the https://github.com/UniversalMediaServer/UniversalMediaServer/blob/bef93d36a60915ee0d69d7225fb1fc4018a5cee1/src/main/java/net/pms/newgui/components/AnimatedIcon.java#L552 the Locale should be used like `Icon icon = LooksFrame.readImageIcon(Locale.ROOT, String.format(resourceNamePattern, idx));` or something else. I am not sure which value of the Locale should be set.

**Comment by Nadahar** [comment]
@valib I had no idea that `String.format()` could do this, I thought locale was only needed for decimal symbol, grouping and for changing character case.

The numbers aren't "Indian numbers" (which is something entirely different, but [Eastern Arabic/Indic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals). It seems that the correct fix is applying a `Locale`, so your suggestion should work.

I must say that I think you will find the same problem many other places in the code though. `String.format()` is used many places, and as far as I can tell, mostly without `Locale`. Every use of `String.format()` where numbers are used (`%a`, `%d`, `%e`, `%f`, `%g` etc) are probably vulnerable for this. When the output is meant to be read by humans, it might not be a problem, but whenever it's mean to determine some "code", it will likely cause problems.

When it comes to which `Locale` to use, I always use `Locale.ROOT`. The reason is that it is the "root" locale where no special rules are applied. I don't know if there's any real difference between `Locale.ROOT`, `Locale.English` or `Locale.US`, but in theory, "English" and "US" might have specific rules applied while "ROOT" should not. The problem, as I've understood it, is that `Locale.ROOT` doesn't exist on Android, which is why many use `Locale.English` instead (to make the code portable).

**Comment by SubJunk** [comment]
That fix worked @valib thanks, please review

**Comment by valib** [comment]
Fixed in #2400

**Comment by valib** [comment]
@Nadahar thanks for comment.
