### ISSUE TITLE
Video goes way faster than Audio

### ISSUE THREAD

**Issue by mWaltari** [UniversalMediaServer/UniversalMediaServer#241]
(For this video), or all made by those webinars (Video file it self is more than less public)

https://dl.dropboxusercontent.com/u/3780852/CodeRage7_IDE-Talk.mp4

-tee-

**Comment by Sami32** [comment]
Perhaps "PS3" could be add to the title.
@mWaltari @mpenguin Did the latest UMS version solved this issue ?
@SubJunk I was not able to reprocuce it on Viera, could you have a try with your PS3, please ?

**Comment by polygirl** [comment]
@mWaltari thanks for reporting this, unfortunately the link has expired.  If you are still experiencing that issue, please reopen and attach the file again so that we can look into it for you.
