### ISSUE TITLE
Crowdin glossary needs updating

### ISSUE THREAD

**Issue by treylav** [UniversalMediaServer/UniversalMediaServer#2420]
I ran into a problem with a lack of terms when I tried to correct the Russian translation. The current version of the translation contains several terms, which, in my opinion, are not translated accurately ("application", for example). The problem is that Crowdin has no mechanism for suggesting a term in a glossary.
How should I suggest new terms? Post in a discussion section or a pull request to one of the project files?

**Comment by SubJunk** [comment]
@treylav that's weird that you can't suggest changes to the glossary. I assume that has been possible at some point, since that would be how the existing ones got made.
I can change them manually if you let me know which ones on here

**Comment by Nadahar** [comment]
I made the existing ones.

**Comment by treylav** [comment]
Okay, I found it. You need to select a section of the original text, a drop-down menu will appear. It does not always drop, which is a bit confusing.
![glossary](https://user-images.githubusercontent.com/617704/111068384-948d7400-84d9-11eb-8d16-a7a58b6e1b49.gif)
