### ISSUE TITLE
Chromecast discovery fails

### ISSUE THREAD

**Issue by DanielHeath** [UniversalMediaServer/UniversalMediaServer#2424]
I'm running UMS 10.2, the latest release, on ubuntu focal 20.04 .

[ums_dbg_2021-03-12-15-51.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6127688/ums_dbg_2021-03-12-15-51.zip)

This machine can definitely see the chromecast (eg can cast to it from chrome), but it doesn't appear in the receiver list on UMS.

I can also see it with `avahi-browse --all`, so it's definitely not broken MDNS, and it has no trouble discovering e.g. my plex install as a target, so it's not broken discovery either.

Happy to source-dive if needed, but it'd help to have a few pointers.

**Comment by Nadahar** [comment]
The Chromecast implementation in UMS is kind of half-way done only. There's a lot to dive into there if you feel like it, but before you do, you should make sure that Chromecast discovery is enabled. Because this code has issues, I think it's disabled in the configuration by default.

**Comment by DanielHeath** [comment]
What setting controls that?

Thanks,
Daniel Heath

**Comment by Nadahar** [comment]
I don't have UMS available here now, but I think you must set
```
chromecast_extension = true
```
in `UMS.conf`

**Comment by DanielHeath** [comment]
Ahh that works, thanks :)

**Comment by DanielHeath** [comment]
That would be a good thing to add to the "Chromecast" wiki page or other documentation (I read it before raising an issue, but it wasn't mentioned there that it's disabled by default)

**Comment by SubJunk** [comment]
@DanielHeath that's a good idea. If you could please let us know if you find any bugs after enabling that, they would be good to document too

**Comment by DanielHeath** [comment]
Thanks. Seems to work well after enabling the feature.
