### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2425]
Me and @js-kyle have been playing around with a new support website for us to consolidate our documentation. I had originally intended to use the GitHub Wiki but this is way more powerful. I'm interested in thoughts about it from anyone 

https://support.universalmediaserver.com

Also @valib would you be interested in adding Czech translations of articles? When we have more articles, we can also do an announcement to try to get translators for other languages. Some of our other Crowdin contributors may be interested.

Most of the articles on there are older ones copied over so they need review and updating.
The newer one I made is at https://support.universalmediaserver.com/books/use/page/how-to-play-media

**Comment by valib** [comment]
@SubJunk I can try to do it but you know that I am 63 years old man (now one year retired) and you still should be aware that I can suddenly stop answer your questions because I can be dead (Covid or whatewer) 😄

**Comment by valib** [comment]
@SubJunk the https://support.universalmediaserver.com/ is automatically translated to the Czech language. Only topics in the "Last actualized page" and "Last books" are not translated.

**Comment by SubJunk** [comment]
@valib congratulations on your retirement! does your country have a covid vaccine rollout? I hope you can get one soon

**Comment by valib** [comment]
@SubJunk thanks. I may get a vaccine at the end of August or May.

**Comment by SubJunk** [comment]
This is going well now. We still need to move/remove our content from other areas to this one, but this part is working. Thanks for your translations @valib !!
