### ISSUE TITLE
tsmuxer fails with HEVC

### ISSUE THREAD

**Issue by thedude911** [UniversalMediaServer/UniversalMediaServer#2433]
Ubuntu 20.10 / 10.3.0:

I have a HEVC encoded video, mediainfo shows HEVC (Main@L3.1@Main) video with HE-AAC audio. Nevertheless, when transconding with tsmuxer the UMS will create a .meta file that contains "V_MPEG4/ISO/AVC", which is IMHO wrong. Correct would be "V_MPEGH/ISO/HEVC". The not-so-surprising result is that the H264 code of tsmuxer will fail to accept the transconding:

[tsMuxeR-6-2] tsMuxeR: ../tsMuxer/h264StreamReader.cpp:486: virtual int H264StreamReader::getTSDescriptor(uint8_t*, bool, bool): Assertion `0' failed.

[tsmuxer.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6175142/tsmuxer.zip)

**Comment by valib** [comment]
@thedude911 thanks for info. Fixed in #2434
