### ISSUE TITLE
Media Library TV Show Metadata

### ISSUE THREAD

**Issue by Woodstock6969** [UniversalMediaServer/UniversalMediaServer#2441]
Hi There,

Firstly great work on this project!

I've an issue that started since 10.2 which is that the API TV Show search isn't selecting the correct TV show.  My file names are 'ShowName S01E01 EpisodeName.ext'
[ums_dbg_2021-03-23-09-56.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6188540/ums_dbg_2021-03-23-09-56.zip)
 and I have used MetaX to update the files metadata but for these series the IMDB data is pointing to either an older series of the same name or a short film of the same name.  I've tired adding the series year to the end of the file name or after the series name without success.

The affected series are Black Mirror, Grimm, The Flash 2014 series and the Tick 2016 series - there could be more but these are the ones I'm affected by.  

The 10.1 release was the best API correctly getting then IMDB data for both Movies and TV Shows.

Many thanks
Steve

**Comment by SubJunk** [comment]
@Woodstock6969 thanks for this report and your kind words, I have moved this issue to our API repository https://github.com/UniversalMediaServer/api/issues/477

**Comment by SubJunk** [comment]
@Woodstock6969 this should be fixed now, thank you for reporting it

**Comment by Woodstock6969** [comment]
Thanks for the update.
