### ISSUE TITLE
Oppo Player Shows All Files As MPEG Types

### ISSUE THREAD

**Issue by AYColumbia** [UniversalMediaServer/UniversalMediaServer#245]
Everything was fine through version 3.3.0.  Once updated to 3.4.0 and 3.4.1, I started having this issue.  For now, I reverted back to 3.3.0.

My DLNA device to play content is an Oppo BDP-103 blu-ray player.  After updating to 3.4.x, all files are now listed as "mpeg" file types as opposed to their native types, i.e., MKV as MKV, AVI as AVI, etc.  This causes the player not to play certain files because it thinks they're in one container, e.g., M2TS when the file is actually an MKV.

What steps will reproduce the problem?
1 You need the Oppo BDP-103 I guess (or BDP-83 or BDP-93)
2 Set up UMS to:
- NOT: hide file extensions nor transcode files of type mkv,m2ts,ts,avi,mpg,mp4
- NOT show #transcode# folder
- pass DTS track as is

3 Use player to pull up server files

I set up another UMS on my other server to run 3.4.x for testing/comparison and both UMS settings are identical.  Both my servers are running Windows 7 Ultimate 64bit.  I set one up with 3.4.x so I can show you (in the attached images) how the player sees the files from the two servers.  The image file names have the UMS version.  You can see on the one that works fine, all the file types show the proper icon/type and play all the files.

Also, you can see in the images that the file info (left side) for the same file is recognized when served from 3.3.0 but not recognized when from 3.4.x.

Note that the images attached are from the same issue that cropped back between versions 2.1.2 and 2.2.0.  So the 2.1.2 image shows what 3.3.0 shows and 2.2.0 is to 3.4.x.

If I left out anything you need, please ask and I'll provide any additional information.  Thank you very much.

![ums 2 1 2 works-s](https://f.cloud.github.com/assets/6758781/2238979/8610ce36-9c0b-11e3-939c-1704fb7d3303.jpg)
![ums 2 2 0 does not work-s](https://f.cloud.github.com/assets/6758781/2238982/99e68554-9c0b-11e3-955f-f3d7b0767c3a.jpg)

**Comment by jonghs** [comment]
So sorry to ask a novice question - where do i find the oppobdp105.conf file and what tool do i use to edit it.  I encountered the same problem that my oppo 105D sees all MVK files as MPEG file and the AVR shows audio input as PCM zero, no sound at all.  I thought was my new Denon problem. Desperate and tried changing wires, etc, served the web for three days and finally googled this site.  Thankful and excited but i need the basics to be able to know how to apply the solution here.  Hope someone can point me to the basic stuff and on one get offended.  thanks.  Jonghs from Singapore

**Comment by jonghs** [comment]
Just to add that my media files are stored on a Synology NAS. The Oppo 105D access the NAS and the output sent to a Denon AVR.  I do not have a PC running a Universal Media Server software.  Again, i hope i am not too 'off'.  Is there a way to correct this problem where the file is in a commercial NAS.  the same setup played perfectly before.  only recently the MKV files becomes MPEG file on the Oppo.

**Comment by Nadahar** [comment]
@jonghs Do you run Universal Media Server at all? If not, none of the above is relevant for you.

**Comment by Slanggurka** [comment]
jonghs, unfortunately, in my expiries is Oppo and UMS not suited for each
other. I have tried to get it to work but never succeeded. Besides problem
with mkv turns up as mpeg there is problems with external subs.
I think there is something with the Oppo causing the problems, not UMS.
However, I run oShare media server and that works perfectly. No issues at
all. oShare is not as versatile as UMS but it works. I have tried a bunch
of media servers (such as Serviio) and the Oppo have the same problem with
all of them but oShare.

**Comment by Sami32** [comment]
@AYColumbia @DeFlanko @SubJunk Did the latest UMS version solved this issue ?

**Comment by AYColumbia** [comment]
I haven't used UMS for a few months as I got a new TV that has the PLEX app built in so been using PLEX now.  If I have time over the weekend, I can check the latest UMS and see how things look on the Oppo.

**Comment by Sami32** [comment]
@AYColumbia It would be nice, thank you ;-)

**Comment by SubJunk** [comment]
@AYColumbia did you get around to checking or could you?

**Comment by AYColumbia** [comment]
Sorry I never got around to checking this issue.  I'll try to make time this weekend to do that.  I'll need to install the latest UMS first.

**Comment by SubJunk** [comment]
Thanks for these @AYColumbia 
Could you please make logs for this so we can see what the difference is, and see which configs each renderer is using?

**Comment by polygirl** [comment]
Closing as TRACE logs never arrived.
