### ISSUE TITLE
No Renderer Found Toshiba TV

### ISSUE THREAD

**Issue by shaypaige1982** [UniversalMediaServer/UniversalMediaServer#246]
Hi i have a toshiba lcd tv (58L7300U) and a mac recently updated to mavericks.   I am using the latest ums software 3.4.1 and am trying to stream to my tv using the tv's media software.  I have already enabled my tv as a renderer.  It has worked 3 maybe 4 times but now i cannot get it to work.  Need some help.  Thanks.

DEBUG 2014-02-23 17:35:47.266 [main] Reading cred.path: default: "", current: "/Users/shaypaige/Library/Application Support/UMS/UMS.cred"
DEBUG 2014-02-23 17:35:47.273 [main] Reading run_wizard: default: true, current: false
INFO  2014-02-23 17:35:47.273 [main] Starting Universal Media Server 3.4.1
INFO  2014-02-23 17:35:47.274 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  2014-02-23 17:35:47.274 [main] http://www.universalmediaserver.com
INFO  2014-02-23 17:35:47.274 [main] 
INFO  2014-02-23 17:35:47.274 [main] Build: 7e3ae892a (2014-02-13)
INFO  2014-02-23 17:35:47.274 [main] Java: Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 64-bit by Apple Inc.
INFO  2014-02-23 17:35:47.275 [main] OS: Mac OS X 64-bit 10.9.1
INFO  2014-02-23 17:35:47.275 [main] Encoding: UTF-8
INFO  2014-02-23 17:35:47.280 [main] Memory: 759 MB
INFO  2014-02-23 17:35:47.280 [main] Language: en
INFO  2014-02-23 17:35:47.280 [main] 
INFO  2014-02-23 17:35:47.280 [main] Working directory: /Applications/Universal Media Server.app/Contents/Resources/Java
INFO  2014-02-23 17:35:47.281 [main] Temp directory: /var/folders/96/bng20t9165x3qg6vy3cgh74c0000gn/T/universalmediaserver
INFO  2014-02-23 17:35:47.281 [main] Logging config file: /Applications/Universal Media Server.app/Contents/Resources/Java/logback.xml
INFO  2014-02-23 17:35:47.282 [main] debug.log: /Users/shaypaige/Library/Application Support/UMS/debug.log
INFO  2014-02-23 17:35:47.282 [main] 
INFO  2014-02-23 17:35:47.282 [main] Profile directory: /Users/shaypaige/Library/Application Support/UMS
INFO  2014-02-23 17:35:47.282 [main] Profile directory permissions: rw
INFO  2014-02-23 17:35:47.283 [main] Profile path: /Users/shaypaige/Library/Application Support/UMS/UMS.conf
INFO  2014-02-23 17:35:47.283 [main] Profile permissions: rw
INFO  2014-02-23 17:35:47.283 [main] Profile name: Shays-iMac.local
INFO  2014-02-23 17:35:47.283 [main] 
INFO  2014-02-23 17:35:47.283 [main] Web conf path: /Users/shaypaige/Library/Application Support/UMS/WEB.conf
INFO  2014-02-23 17:35:47.283 [main] Web conf permissions: file not found
INFO  2014-02-23 17:35:47.284 [main] 
DEBUG 2014-02-23 17:35:47.819 [main] Reading hide_advanced_options: default: true, current: false
DEBUG 2014-02-23 17:35:47.826 [main] Reading port: default: 5001, current: 5000
DEBUG 2014-02-23 17:35:47.833 [main] Reading network_interface: default: "", current: "en1"
DEBUG 2014-02-23 17:35:47.835 [main] Reading maximum_bitrate: default: "110", current: "50"
DEBUG 2014-02-23 17:35:47.837 [main] Reading http_engine_v2: default: true, current: false
DEBUG 2014-02-23 17:35:48.134 [main] Reading use_mplayer_for_video_thumbs: default: false, current: true
DEBUG 2014-02-23 17:35:48.159 [main] Reading folders: default: "", current: "/Users/shaypaige/Desktop/Movies"
INFO  2014-02-23 17:35:48.159 [main] Checking shared folder: /Users/shaypaige/Desktop/Movies
DEBUG 2014-02-23 17:35:48.178 [main] Reading mpeg2_main_settings: default: "Automatic (Wired)", current: "Automatic (Wireless)"
INFO  2014-02-23 17:35:48.463 [main] Loading MediaInfo library
INFO  2014-02-23 17:35:48.509 [main] Loaded MediaInfoLib - v0.7.58
INFO  2014-02-23 17:35:48.533 [main] Loading renderer configurations from /Applications/Universal Media Server.app/Contents/Resources/Java/renderers
INFO  2014-02-23 17:35:48.537 [main] Loaded configuration for renderer: AirPlayer
INFO  2014-02-23 17:35:48.539 [main] Loaded configuration for renderer: Android
INFO  2014-02-23 17:35:48.543 [main] Loaded configuration for renderer: KalemSoft Media Player
INFO  2014-02-23 17:35:48.546 [main] Loaded configuration for renderer: Sony Bravia 4500
INFO  2014-02-23 17:35:48.550 [main] Loaded configuration for renderer: Sony Bravia 5500
INFO  2014-02-23 17:35:48.554 [main] Loaded configuration for renderer: Sony Bravia EX
INFO  2014-02-23 17:35:48.559 [main] Loaded configuration for renderer: Sony Bravia EX620
INFO  2014-02-23 17:35:48.563 [main] Loaded configuration for renderer: Sony Bravia HX
INFO  2014-02-23 17:35:48.567 [main] Loaded configuration for renderer: Sony Bravia W6/W8/W9
INFO  2014-02-23 17:35:48.570 [main] Loaded configuration for renderer: D-Link DSM-510
INFO  2014-02-23 17:35:48.571 [main] Loaded configuration for renderer: DirecTV HR
INFO  2014-02-23 17:35:48.573 [main] Loaded configuration for renderer: Freebox HD
INFO  2014-02-23 17:35:48.575 [main] Loaded configuration for renderer: Freecom MusicPal
INFO  2014-02-23 17:35:48.577 [main] Loaded configuration for renderer: Pioneer Kuro
INFO  2014-02-23 17:35:48.579 [main] Loaded configuration for renderer: LG 42LA644V
INFO  2014-02-23 17:35:48.582 [main] Loaded configuration for renderer: LG Smart TV Upgrader
INFO  2014-02-23 17:35:48.584 [main] Loaded configuration for renderer: Nokia N900
INFO  2014-02-23 17:35:48.586 [main] Loaded configuration for renderer: Netgear NeoTV
INFO  2014-02-23 17:35:48.588 [main] Loaded configuration for renderer: OPPO BDP-83
INFO  2014-02-23 17:35:48.589 [main] Loaded configuration for renderer: OPPO BDP-93
INFO  2014-02-23 17:35:48.590 [main] Loaded configuration for renderer: Onkyo TX-NR717
INFO  2014-02-23 17:35:48.596 [main] Loaded configuration for renderer: PlayStation 3
INFO  2014-02-23 17:35:48.600 [main] Loaded configuration for renderer: Panasonic TV
INFO  2014-02-23 17:35:48.602 [main] Loaded configuration for renderer: Panasonic TX-L32V10E
INFO  2014-02-23 17:35:48.604 [main] Loaded configuration for renderer: Philips Aurea
INFO  2014-02-23 17:35:48.608 [main] Loaded configuration for renderer: Philips TV
INFO  2014-02-23 17:35:48.609 [main] Loaded configuration for renderer: Popcorn Hour
INFO  2014-02-23 17:35:48.611 [main] Loaded configuration for renderer: Realtek
INFO  2014-02-23 17:35:48.614 [main] Loaded configuration for renderer: Sony SMP-N100
INFO  2014-02-23 17:35:48.618 [main] Loaded configuration for renderer: Samsung SMT-G7400
INFO  2014-02-23 17:35:48.620 [main] Loaded configuration for renderer: Samsung D7000
INFO  2014-02-23 17:35:48.621 [main] Loaded configuration for renderer: Samsung AllShare
INFO  2014-02-23 17:35:48.623 [main] Loaded configuration for renderer: Samsung Mobile
INFO  2014-02-23 17:35:48.624 [main] Loaded configuration for renderer: Samsung WiseLink
INFO  2014-02-23 17:35:48.626 [main] Loaded configuration for renderer: Sharp Aquos
INFO  2014-02-23 17:35:48.629 [main] Loaded configuration for renderer: Showtime 3
INFO  2014-02-23 17:35:48.631 [main] Loaded configuration for renderer: Showtime 4
INFO  2014-02-23 17:35:48.634 [main] Loaded configuration for renderer: Sony Blu-ray
INFO  2014-02-23 17:35:48.637 [main] Loaded configuration for renderer: Sony Home Theatre System
INFO  2014-02-23 17:35:48.640 [main] Loaded configuration for renderer: Sony STR-DA5800ES
INFO  2014-02-23 17:35:48.641 [main] Loaded configuration for renderer: Streamium
INFO  2014-02-23 17:35:48.642 [main] Loaded configuration for renderer: Telstra T-Box
INFO  2014-02-23 17:35:48.644 [main] Loaded configuration for renderer: VideoWeb TV
INFO  2014-02-23 17:35:48.646 [main] Loaded configuration for renderer: Vizio Smart TV
INFO  2014-02-23 17:35:48.648 [main] Loaded configuration for renderer: WD TV Live
INFO  2014-02-23 17:35:48.650 [main] Loaded configuration for renderer: WMP
INFO  2014-02-23 17:35:48.651 [main] Loaded configuration for renderer: XBMC
INFO  2014-02-23 17:35:48.653 [main] Loaded configuration for renderer: Xbox 360
INFO  2014-02-23 17:35:48.654 [main] Loaded configuration for renderer: Yamaha RX-A1010
INFO  2014-02-23 17:35:48.655 [main] Loaded configuration for renderer: Yamaha RX-V3900
INFO  2014-02-23 17:35:48.656 [main] Loaded configuration for renderer: Yamaha RX-V671
INFO  2014-02-23 17:35:48.658 [main] Loaded configuration for renderer: iPad / iPhone
INFO  2014-02-23 17:35:48.658 [main] Checking the fontconfig cache, this can take two minutes or so.
DEBUG 2014-02-23 17:35:48.662 [mplayer-0] Starting "/Applications/Universal Media Server.app/Contents/Resources/Java/osx/mplayer" dummy
DEBUG 2014-02-23 17:35:48.662 [ffmpeg-1] Starting "/Applications/Universal Media Server.app/Contents/Resources/Java/osx/ffmpeg" -y -f lavfi -i nullsrc=s=720x480:d=1:r=1 -vf ass=DummyInput.ass -target ntsc-dvd -
DEBUG 2014-02-23 17:35:48.786 [Thread-8] File not found: 'dummy'
DEBUG 2014-02-23 17:35:48.786 [Thread-8] Failed to open dummy.
DEBUG 2014-02-23 17:35:48.786 [Thread-9] ffmpeg version N-59836-g1e90d89-tessus Copyright (c) 2000-2014 the FFmpeg developers
DEBUG 2014-02-23 17:35:48.787 [Thread-9]   built on Jan  5 2014 16:13:21 with llvm-gcc 4.2.1 (LLVM build 2336.1.00)
DEBUG 2014-02-23 17:35:48.787 [Thread-9]   configuration: --prefix=/Users/tessus/data/ext/ffmpeg/sw --as=yasm --extra-version=tessus --disable-shared --enable-static --disable-ffplay --enable-gpl --enable-pthreads --enable-postproc --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-libspeex --enable-bzlib --enable-zlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libxavs --enable-version3 --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvpx --enable-libgsm --enable-libopus --enable-fontconfig --enable-libfreetype --enable-libass --enable-libbluray --enable-filters --enable-runtime-cpudetect
DEBUG 2014-02-23 17:35:48.787 [Thread-9]   libavutil      52. 60.100 / 52. 60.100
DEBUG 2014-02-23 17:35:48.787 [Thread-9]   libavcodec     55. 47.100 / 55. 47.100
DEBUG 2014-02-23 17:35:48.808 [Thread-9]   libavformat    55. 22.102 / 55. 22.102
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   libavdevice    55.  5.102 / 55.  5.102
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   libavfilter     4.  0.103 /  4.  0.103
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   libswscale      2.  5.101 /  2.  5.101
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   libswresample   0. 17.104 /  0. 17.104
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   libpostproc    52.  3.100 / 52.  3.100
DEBUG 2014-02-23 17:35:48.809 [Thread-9] Input #0, lavfi, from 'nullsrc=s=720x480:d=1:r=1':
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   Duration: N/A, start: 0.000000, bitrate: N/A
DEBUG 2014-02-23 17:35:48.809 [Thread-9]     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 720x480 [SAR 1:1 DAR 3:2], 1 tbr, 1 tbn, 1 tbc
DEBUG 2014-02-23 17:35:48.809 [mplayer-0] Attaching thread: mplayer-0
DEBUG 2014-02-23 17:35:48.809 [Thread-9] [Parsed_ass_0 @ 0x102a01880] Added subtitle file: 'DummyInput.ass' (6 styles, 1 events)
DEBUG 2014-02-23 17:35:48.809 [Thread-9] Output #0, dvd, to 'pipe:':
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   Metadata:
DEBUG 2014-02-23 17:35:48.809 [Thread-9]     encoder         : Lavf55.22.102
DEBUG 2014-02-23 17:35:48.809 [Thread-9]     Stream #0:0: Video: mpeg2video, yuv420p, 720x480 [SAR 1:1 DAR 3:2], q=2-31, 6000 kb/s, 90k tbn, 29.97 tbc
DEBUG 2014-02-23 17:35:48.809 [Thread-9] Stream mapping:
DEBUG 2014-02-23 17:35:48.809 [ffmpeg-1] Attaching thread: ffmpeg-1
DEBUG 2014-02-23 17:35:48.809 [Thread-9]   Stream #0:0 -> #0:0 (rawvideo -> mpeg2video)
DEBUG 2014-02-23 17:35:48.809 [Thread-9] Press [q] to stop, [?] for help
DEBUG 2014-02-23 17:35:48.809 [Thread-9] frame=    1 fps=0.0 q=1.6 Lsize=       8kB time=00:00:00.03 bitrate=1964.1kbits/s    
DEBUG 2014-02-23 17:35:48.809 [Thread-9] video:5kB audio:0kB subtitle:0 global headers:0kB muxing overhead 51.227617%
DEBUG 2014-02-23 17:35:48.811 [mplayer-0] Unix process ID (/Applications/Universal Media Server.app/Contents/Resources/Java/osx/mplayer): 702
DEBUG 2014-02-23 17:35:48.811 [ffmpeg-1] Unix process ID (/Applications/Universal Media Server.app/Contents/Resources/Java/osx/ffmpeg): 703
INFO  2014-02-23 17:35:48.820 [main] Searching for plugins in /Applications/Universal Media Server.app/Contents/Resources/Java/plugins
INFO  2014-02-23 17:35:48.821 [main] No plugins found
INFO  2014-02-23 17:35:48.834 [main] Registering transcoding engine: FFmpeg Audio
INFO  2014-02-23 17:35:48.838 [main] Registering transcoding engine: MEncoder
INFO  2014-02-23 17:35:48.838 [main] Registering transcoding engine: FFmpeg
INFO  2014-02-23 17:35:48.839 [main] Registering transcoding engine: VLC
DEBUG 2014-02-23 17:35:48.841 [main] Error reading ffmpeg web filters: File '/Users/shaypaige/Library/Application Support/UMS/ffmpeg.webfilters' does not exist
DEBUG 2014-02-23 17:35:48.858 [main] FFmpeg supported protocols: [bluray, cache, concat, crypto, data, ffrtmphttp, file, ftp, gopher, hls, http, httpproxy, mmsh, mmst, pipe, rtmp, rtmpt, rtp, srtp, tcp, udp, unix, mms]
INFO  2014-02-23 17:35:48.858 [main] Registering transcoding engine: FFmpeg Web Video
INFO  2014-02-23 17:35:48.859 [main] Registering transcoding engine: MEncoder Web
INFO  2014-02-23 17:35:48.859 [main] Registering transcoding engine: VLC Web Video
INFO  2014-02-23 17:35:48.860 [main] Registering transcoding engine: tsMuxeR
INFO  2014-02-23 17:35:48.861 [main] Registering transcoding engine: Audio High Fidelity
INFO  2014-02-23 17:35:48.861 [main] Registering transcoding engine: VLC Web Audio (Legacy)
INFO  2014-02-23 17:35:48.862 [main] Registering transcoding engine: VLC Web Video (Legacy)
INFO  2014-02-23 17:35:48.862 [main] Registering transcoding engine: dcraw Thumbnailer
INFO  2014-02-23 17:35:48.903 [main] Using address /192.168.1.105 found on network interface: name:en1 (en1)
INFO  2014-02-23 17:35:48.904 [main] Created socket: /192.168.1.105:5000
INFO  2014-02-23 17:35:48.921 [HTTP Server] Starting DLNA Server on host 192.168.1.105 and port 5000...
DEBUG 2014-02-23 17:35:48.944 [main] Sending ALIVE...
DEBUG 2014-02-23 17:35:48.953 [main] Reading uuid: default: null, current: "a1328257-d011-49c6-af21-601469f1755c"
INFO  2014-02-23 17:35:48.953 [main] Using the following UUID configured in UMS.conf: a1328257-d011-49c6-af21-601469f1755c
INFO  2014-02-23 17:35:49.210 [main] The server is now available for renderers to find
DEBUG 2014-02-23 17:35:59.210 [UPNP-AliveMessageSender] Sending ALIVE...
INFO  2014-02-23 17:36:08.614 [AWT-EventQueue-0] Configuration saved to: /Users/shaypaige/Library/Application Support/UMS/UMS.conf
INFO  2014-02-23 17:36:08.958 [AWT-EventQueue-0] Configuration saved to: /Users/shaypaige/Library/Application Support/UMS/UMS.conf
DEBUG 2014-02-23 17:36:12.213 [background-task-0] singleton task restart started
DEBUG 2014-02-23 17:36:12.213 [background-task-0-restart(0)] task started
INFO  2014-02-23 17:36:12.213 [background-task-0-restart(0)] Sending BYEBYE...
INFO  2014-02-23 17:36:12.214 [background-task-0-restart(0)] Stopping server on host 192.168.1.105 and port 5000...
DEBUG 2014-02-23 17:36:12.580 [background-task-1] singleton task 'restart' already running, exiting
DEBUG 2014-02-23 17:36:12.805 [background-task-1] singleton task 'restart' already running, exiting
DEBUG 2014-02-23 17:36:12.996 [background-task-1] singleton task 'restart' already running, exiting
DEBUG 2014-02-23 17:36:13.209 [background-task-1] singleton task 'restart' already running, exiting
DEBUG 2014-02-23 17:36:13.218 [background-task-0-restart(0)] Reading port: default: 5001, previous: 5000, current: 5001
INFO  2014-02-23 17:36:13.219 [background-task-0-restart(0)] Using address /192.168.1.105 found on network interface: name:en1 (en1)
INFO  2014-02-23 17:36:13.219 [background-task-0-restart(0)] Created socket: /192.168.1.105:5001
DEBUG 2014-02-23 17:36:13.220 [background-task-0-restart(0)] Sending ALIVE...
INFO  2014-02-23 17:36:13.220 [HTTP Server] Starting DLNA Server on host 192.168.1.105 and port 5001...
DEBUG 2014-02-23 17:36:13.221 [background-task-0-restart(0)] task ended
DEBUG 2014-02-23 17:36:19.209 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2014-02-23 17:39:19.195 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2014-02-23 17:41:52.815 [AWT-EventQueue-0] Checking dbgpack property in UMS.conf
DEBUG 2014-02-23 17:41:52.815 [AWT-EventQueue-0] adding /Users/shaypaige/Library/Application Support/UMS/WEB.conf
DEBUG 2014-02-23 17:41:52.815 [AWT-EventQueue-0] adding /Users/shaypaige/Library/Application Support/UMS/UMS.conf
DEBUG 2014-02-23 17:41:52.815 [AWT-EventQueue-0] adding /Users/shaypaige/Library/Application Support/UMS/debug.log.prev
DEBUG 2014-02-23 17:41:52.815 [AWT-EventQueue-0] adding /Users/shaypaige/Library/Application Support/UMS/debug.log

**Comment by Sami32** [comment]
@shaypaige1982 @SubJunk Any log ? Can we close this issue ?
UMS trully miss Toshiba renderer conf but without any log or renderer's user-agent information we cannot help.

**Comment by Sami32** [comment]
@shaypaige1982 http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=8862&p=28475#p28475
