### ISSUE TITLE
Multiple Errrors Hitting Log - Duplicated or Same Issue Scannning Target Folders

### ISSUE THREAD

**Issue by marksjc** [UniversalMediaServer/UniversalMediaServer#2466]
[ums_dbg_2021-04-24-16-42.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6370935/ums_dbg_2021-04-24-16-42.zip)

I see multiple issues upon runnihg 14.1 for first time.  I'm a dumb user so I would appreciate a simple yes/we're workihg oh it or no/it's not a problem.  I think I provide attached the correct data as specified.  Of course if you need more ihforamatioh simply say what you need and I'll forward it along.  If it's likely noh-programmers would not know how to access/collect please provide explicit instructions (for collecting the data, only, to keep focused on this possible issue :-)  _Long live emoticohs, were emoji found in Cheop's pyramid?_

**Comment by SubJunk** [comment]
Why was this closed? Is it working now?

**Comment by marksjc** [comment]
I closed this accidentally and it's still broken  I deleted the old access path to the files (out of hundreds, 5 were actually displaying in the UI).  Got the same 5 and a lot of log errors consistent with the log file attached.  Sorry I closed it, I use Github infrequently, but will be more careful in the future.

**Comment by valib** [comment]
@marksjc please try to delete the database at `/Users/mac/Library/Application Support/UMS/database` and start the UMS again. It seems like the wrong database version.

**Comment by valib** [comment]
Fixed in  #2482

**Comment by valib** [comment]
@marksjc thanks for the report.
