### ISSUE TITLE
[HOT FIX] Transcoding is not working with Renderer Samsung AllShare

### ISSUE THREAD

**Issue by AndreLRM** [UniversalMediaServer/UniversalMediaServer#247]
STEPS TO REPRODUCE:
                1) Open any video with any transcoding software (MEncoder, FFMpeg, AviSynth) from #TRANSCODING# path

ERROR CODE:
         - OutOfMemory
         - BufferReadError

HOT FIX (SOLUTION):
         1) Change rederer "SamsungAllShare.conf" line:

                     ChunkedTransfer=false

to the new line:

                       ChunkedTransfer=true

BUG FOUND IN VERSION:
       - 3.4.2
       - 3.4.1
(didn't test any other versions to check it out)

TESTED ON:
         - SAMSUNG TV LED UN46ES6500G

Don't have any debug file with me, but as long as I tested, it doesn't seem to be an intermitent bug. It occurs everytime unless you change renderer's file "SamsungAllShare.conf".

**Comment by Sami32** [comment]
@AndreLRM @Optimusprimeums @skeptical @SubJunk Could this issue be closed now ?
Since it's look like @skeptical https://github.com/UniversalMediaServer/UniversalMediaServer/pull/330 fixed it already.

**Comment by valib** [comment]
@Sami32 you are so fast that I have problem to follow you :smile:
