### ISSUE TITLE
[GITHUB APP] ADDON to Readme.md 

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#248]
@SubJunk I'm starting to roam around other github repo's and noticing some interesting addon's folks are using. 

## Feature Request
- [ ] add [travis-ci][1] graphic so that at a highlevel we can see project status :) (Its free)
Example: ![image](https://f.cloud.github.com/assets/5233969/2290645/b6cfa2aa-a024-11e3-9fcf-f7ec7bc8594c.png)

- [ ] add [Code Climate][2] for code security reasons. (this one i think is pay only but try the 14 day trial and see what it exaclty does....)
Example: ![image](https://f.cloud.github.com/assets/5233969/2290648/c5ce874e-a024-11e3-81ab-bd7a7e87768f.png)

[1]:https://travis-ci.org/
[2]:https://codeclimate.com/github/signup

**Comment by Sami32** [comment]
@DeFlanko @SubJunk No mean that it's not great to know and keep it in mind ;-) but perhaps now it could be closed without offend anyone ?

**Comment by Sami32** [comment]
@DeFlanko Thanks ;-)
I'm just trying to clean up the issues to rediscover some forgotten one or relation between them.
Btw, thank you for the UMS wiki :+1:
