### ISSUE TITLE
Force reboot

### ISSUE THREAD

**Issue by protocrypt** [UniversalMediaServer/UniversalMediaServer#2506]
now in version 1.5.0 to quit from media server I need FORCE QUIT its hangs up...

**Comment by Nadahar** [comment]
Version 1.5.0? That's a long time ago.

**Comment by protocrypt** [comment]
Sorry its 10.5.0 last one..

**Comment by SubJunk** [comment]
I have noticed that too, please feel free to follow the issue we already have for this https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2431
