### ISSUE TITLE
Translate the IMDB metadata

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#2546]
@SubJunk is it possible to make in the API that metadata will be returned in the default language set by the UMS? Like use Google translator see 
![google translator](https://user-images.githubusercontent.com/1472678/124329634-0c1c0780-db8c-11eb-88a1-213d94a7a8f8.jpg)

**Comment by SubJunk** [comment]
@valib it might be possible, maybe you can try?

**Comment by SubJunk** [comment]
This is done now
