### ISSUE TITLE
Problem with Chapters

### ISSUE THREAD

**Issue by gligort** [UniversalMediaServer/UniversalMediaServer#2560]
Hi
Since version 10.7.0 I can not use chapters.
Common Transcode Settings - Chapters Support  is checked as 5 minutes, yet it does not appears on my TV Philips 42PFL4007H12.
I'm going to the movie folder, # -TRANSCODE-#, selecting any of the coders, but there are no CHAPTERS anymore.
It worked in previous version (10.6.0).
Thanks
[ums_dbg_2021-07-16-23-57.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6833562/ums_dbg_2021-07-16-23-57.zip)

**Comment by valib** [comment]
I checked it and chapters are showed in the TRANSCODE folder. What is wrong chapters start from beginning not the time the chapter should start.

**Comment by Mik-S-UMS** [comment]
@valib when I was using the chapters to bypass the no seeking issue for transcoded videos, sometimes the same would happen to me. sometimes it would play at the right time but could also restart from the beginning. can't remember what version I was using at the time, it was a while ago. 

I just checked on my ps4 and the chapters are not displaying for me too. I double checked that they are enabled and gave both UMS and ps4 media player a restart.

Trying on my Samsung TV with chapters enabled causes it to constantly wait and it looks like UMS is stuck in a loop. there might be an error in the data causing the TV to constantly request UMS to resend the directory listing
[ums_dbg_2021-07-17-01-55.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6833920/ums_dbg_2021-07-17-01-55.zip)


Also I have found that you have to quit and restart UMS for any change to this setting, a server restart won't work.

**Comment by Mik-S-UMS** [comment]
could it have something to do with removal of filenames in the #--TRANSCODE--# folder? #2539

**Comment by gligort** [comment]
Same with version 10.8.0.
:(
For now I'm staying with version 10.6.0'

**Comment by SubJunk** [comment]
@gligort I have a fix, please try https://www.universalmediaserver.com/uploads/UMS-2560-chapters.exe

@Mik-S-UMS you were right, it was that change :)
