### ISSUE TITLE
Fully played broken?

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2563]
A user has mentioned that some features like moving or marking fully played videos are not working, and I have noticed marking has not been working for me either at all on 10.7.0
Maybe the fully played logic has been broken when the issue with the cached thumbnails was fixed?
https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14768

**Comment by SubJunk** [comment]
Thanks, I'm looking into this now

**Comment by SubJunk** [comment]
Do you still have the full logs? It would be useful to have the log package

**Comment by SubJunk** [comment]
I left a reply in the forum thread since I can't reproduce

**Comment by Mik-S-UMS** [comment]
Just finished watching something and made sure it played to the end, the log should also have the section I posted on the forum.

[ums_dbg_2021-07-18-04-54.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6835637/ums_dbg_2021-07-18-04-54.zip)

**Comment by SubJunk** [comment]
@Mik-S-UMS thanks for the logs
I can see that the file was in a folder that is not monitored, so the feature is working properly here. If you want it to work for that directory you'll need to enable the "Monitor played status of files" checkbox (step 3 of https://support.universalmediaserver.com/books/use/page/how-to-use-the-fully-played-feature#bkmrk-setup)

**Comment by Mik-S-UMS** [comment]
Strange, it should be monitored. That folder is from a virtual directory spanning several drives and has always been monitored in the past. only thing I did differently this version was to use the "reset the cache" button so that all old thumbnails would be flushed. I'll do more testing of a folder listed in the shared content tab later

**Comment by Mik-S-UMS** [comment]
It looks to be working for folders listed in the shared content tab, it must just be for virtual folders that it is not working.

**Comment by SubJunk** [comment]
It should work for virtual folders too as long as the file is also within a monitored directory. It shouldn't matter if it was started via a virtual folder or not, I think. Can you confirm?

**Comment by Mik-S-UMS** [comment]
No the VF is not inside a monitored directory, I thought that if "addToMediaLibrary":"true" was set then that would also track played status, I'm sure it used to. TBH I have not paid any attention to mark as played so could be completely wrong.

If that is not the case then maybe it would be a good idea to add another option to the virtual folder config to monitor played status?

**Comment by SubJunk** [comment]
Yeah that's a good idea, can you make an issue for it?

**Comment by Mik-S-UMS** [comment]
done. 
That explains my problem with marked files. once we hear from speckeledegg on the forum to see if his issue is similar, this can be closed

**Comment by Mik-S-UMS** [comment]
He has confirmed it is now working with the test build.
