### ISSUE TITLE
Use newer FFmpeg

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2565]
Last time we tried to update FFmpeg was in March, and it caused some crashes for some people. I was not able to reproduce the bug but @valib I think you were?

We rolled it back in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2432

That build was from https://www.gyan.dev/ffmpeg/builds/ because Zeranoe isn't making builds anymore. Can you please try the latest build from that page @valib and see if it fixes that problem?

Another option is to try the latest from https://github.com/AnimMouse/ffmpeg-autobuild/releases

**Comment by valib** [comment]
@SubJunk the latest FFmpeg version works for me but there is only 64bit version. Do we stop support for 32bit version?

**Comment by SubJunk** [comment]
Thanks for checking. The way I did it last time was to keep the old 32-bit file

**Comment by SubJunk** [comment]
This has been happening
