### ISSUE TITLE
TV doesn't recognise UMS running on dual boot OS with identical configs as the same instance

### ISSUE THREAD

**Issue by saveli** [UniversalMediaServer/UniversalMediaServer#2573]
So I have a dual boot OS setup (Windows/Ubuntu) with UMS installed on both and configured the same on both OS.
But the TV differentiates between the two albeit they have the same config files, same IP, and same hostname.

So when I connect to UMS, the connection is put to a quick access menu. When I then switch the OS and use that quick access menu, the TV says UMS is offline.
But when I go into network devices, there is UMS online and I can then connect (putting the "new" UMS to quick access, malfunctioning when I switch OS again).

Is there something else I have to adjust, e.g. user agent string, to make the TV not differentiate between the OS?

(Sorry I can't create a forum account, site is not working, no response to my mail.)

**Comment by Nadahar** [comment]
If you open both `UMS.conf` files (they have different locations for different OSes) you will see that they have different `UUID`s. Make sure they are the same, and your TV should treat them as the same server. The entry looks something like this:
```ini
uuid = 3955ddeb-7227-422e-ad40-bd432c94b167
```

**Comment by saveli** [comment]
Solved it, thanks!
