### ISSUE TITLE
UMS is not being discovered by CP any more (10.8.0)

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#2574]
I have an odd issue: Since version 10.8.0 UMS (linux build / Ubuntu) is not being discovered by control points any more. This issue disappears building and running version 10.7.0. 

However: On my development environment (Mac) version 10.8.0 also works as expected ... ?!

Any ideas ?

**Comment by SubJunk** [comment]
@ik666 please provide logs :)

**Comment by ik666** [comment]
It was an out of memory ... sorry for the inconvenience.

**Comment by SubJunk** [comment]
Cool thanks for responding :)
