### ISSUE TITLE
macOS icon not conforming to latest design standards

### ISSUE THREAD

**Issue by alexgurr** [UniversalMediaServer/UniversalMediaServer#2593]
It seems like the app icon is pretty out of date and doesn't conform to Big Sur+ design standards.

I've made a couple that that conform. Let me know if you like them or want me to open a PR (or even tweak one).

![ums-icon](https://user-images.githubusercontent.com/4161867/128138292-fe3c7f17-98db-4ca3-865b-a596918803bd.png)

![ums-icon-alt](https://user-images.githubusercontent.com/4161867/128276728-4f96c98d-92c8-4974-ae74-7c606a13bd65.png)

**Comment by SubJunk** [comment]
@alexgurr good idea, yes please make a PR

**Comment by alexgurr** [comment]
Can you point me in the right direction? Where's the current macOS icon? Do you prefer 1) or 2)?

**Comment by SubJunk** [comment]
@alexgurr thank you! It will be in the next release
