### ISSUE TITLE
Set MediaInfo=true by default

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2598]
The default value in RendererConfiguration should be set to `true`, but without changing behaviour for any existing renderers, to avoid breaking compatibility for them.
So existing renderers that do not have that line, or have set it to false, should still have it as false, while those who set it to `true` can have it removed.

The main benefit of this change is that new renderers going forward will not have to have the line at all, because it is much better to use MediaInfo than not.

**Comment by ahmedadan** [comment]
Can I be assigned to this @SubJunk ?

**Comment by SubJunk** [comment]
@ahmedadan yes that sounds good :)

**Comment by ahmedadan** [comment]
So is this issue to make sure every renderer has some default value for `MediaInfo`? If it's `true` to leave it as such and if it's missing or false to explicitly set it to `false`?

**Comment by SubJunk** [comment]
I have edited the description to provide clarity after the code review on #2621
