### ISSUE TITLE
Pausing/resuming broken in UMS 3.4.x on SAMSUNG UE46B7000 (SamsungWiseLink.conf)

### ISSUE THREAD

**Issue by dusank** [UniversalMediaServer/UniversalMediaServer#260]
Pausing/resuming is broken on SAMSUNG UE46B7000 (SamsungWiseLink.conf) in UMS 3.4.0, 3.4.1 and 3.4.2, though it is working well in 3.3.0, 3.2.0 and 3.1.2.1.

**Comment by Sami32** [comment]
@dusank Did the latest UMS version improved or solved your renderer support ?
Since the bug was fixed by @SubJunk in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/269#issuecomment-235350784, could this issue be closed ?

**Comment by polygirl** [comment]
@dusank - it's been some time since your latest update.  We believe this has now been resolved so we are closing this issue, but if it's still a problem for you please feel free to reopen with full TRACE logs so that we can investigate further.
