### ISSUE TITLE
Add link to releases page to automatic downloader

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2604]
The automatic downloader should have text like "Click here to see the changes in this release" that links to https://github.com/UniversalMediaServer/UniversalMediaServer/releases

**Comment by CodeLover254** [comment]
I would love to take on this one

**Comment by valib** [comment]
@CodeLover254 please be free to do it. You are welcome.

**Comment by CodeLover254** [comment]
Could anyone guide me on how to deal with dependency issues? Am using IntelliJ and a good number of dependencies cannot be found by maven. Are there additional repositories I need to configure?

**Comment by valib** [comment]
@CodeLover254 you need to follow https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-build-UMS#6-resolve-and-install-external-libraries
