### ISSUE TITLE
Log splitting

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2608]
Sometimes our logs get very large, usually due to bugs or because the user is running UMS in TRACE log mode for debugging. It would be useful to split the logs at an interval (maybe every 100MB) to make it easier to open them in editors

**Comment by Nadahar** [comment]
If you look in `logback.xml` you will see that this has already been prepared and only takes a small configuration change, although I believe the limit configured there is 10MB. Either way, it's very easy to change, but it will break the whole "debug.prev" logic.

**Comment by valib** [comment]
@SubJunk I tested it and it doesn't work. Logs are not zipped and only first log named `debug.txt` with the defined size is produced. Following logs are replaced by next produced logs. So the setting should be investigated and fixed.

**Comment by Nadahar** [comment]
@valib It does "work", but you have to configure it to work like you want it to. I'm pretty sure you can define how the naming should work, but as I said, the "debug.log.prev" functionality is something that is made in our code without logback's knowledge, so it won't play ball. Also, if I remember correctly, the "rolling appender" doesn't start a new log file when you start UMS - it will just continue writing to the "active" one.

When it comes to "DbgPacker" (what is included in the zip-file), it is pretty much hardcoded to one specific behavior as far as I remember, so it will have to be adapted to any new logic.
