### ISSUE TITLE
Restart server when network interface becomes available

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2615]
A user has a situation where their computer starts with no network access, then it becomes available later on. They want UMS to notice that a viable network connection is there and use it. That seems like it would be a good thing to me.
https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14824

**Comment by SurfaceS** [comment]
I'll post something for that after JUPnP merge.

**Comment by Mik-S-UMS** [comment]
I wonder if this is similar to what was happening to me when I was using my phones hotspot for internet in #2334 (and #2338) last year. a server restart would fix it for me too.
