### ISSUE TITLE
Renderer displays image file size as "NaNundefined"

### ISSUE THREAD

**Issue by BugExplorer-Plus** [UniversalMediaServer/UniversalMediaServer#2630]
UMS is started in Trace mode.
Powered on renderer/LG TV.
Selected "UMS->Media Library->Fotos->all fotos" as display source.
Displayed the first image (or any image from every path) - the TV shows in the title: "Universal Media Server | NaNundefined | 3244x2160"
Zipped & attached debug files to this issue.
Submitted the issue.
[ums_dbg_2021-09-03-09-54.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7104315/ums_dbg_2021-09-03-09-54.zip)

**Comment by SubJunk** [comment]
@BugExplorer-Plus thanks for reporting this. That is because we are transcoding the image in realtime, which means we can't know how big it will be.
The TV should be handling those cases when the size can't be known ahead of time, so this is more a bug of the TV
