### ISSUE TITLE
Wrong java binary in x86 packages

### ISSUE THREAD

**Issue by cudBwrong** [UniversalMediaServer/UniversalMediaServer#2640]
Packages later than 10.10.0 have 64 bit java binaries packaged in the Linux 32 bit x86 tarballs.
10.10.1 and 10.11.0 give exec errors on jre8/bin/java.  For example:
$ ls
ums-10.10.1  UMS-10.10.1-x86.tar  ums-10.11.0  UMS-10.11.0-x86.tar
$ cd ums-10.10.1/
$ cd jre8/bin
$ ls
java  keytool  pack200     rmid         servertool  unpack200
jjs   orbd     policytool  rmiregistry  tnameserv
$ file java
java: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=d39fc26b0890aed557312526b96ddab8a8034723, not stripped

**Comment by SubJunk** [comment]
@cudBwrong thanks for reporting this, I'm looking into it now

**Comment by SubJunk** [comment]
@cudBwrong that's fixed now and I'll do a release in the next few days. thanks again
