### ISSUE TITLE
Network speed test only runs once per renderer

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2643]
My understanding of how the network speed test is that it is supposed to run periodically, or after certain events. But I can see in my logs that it only runs once for each renderer, which has resulted in some non-ideal behaviour for my instance.

Was my understanding wrong @valib or is this a bug?

**Comment by valib** [comment]
@SubJunk you are correct. The test is running only once during the UMS inizialization. The idea to run it periodically sounds good.
