### ISSUE TITLE
Fork jaudiotagger

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2662]
> @SubJunk it seem that the owner of the jaudiotagger is an idiot who is not able to merge the PR made by @Nadahar in the https://bitbucket.org/ijabz/jaudiotagger/pull-requests/67 so we should fork the https://bitbucket.org/ijabz/jaudiotagger/src/master/ to the GitHub and store it in the Maven repository instead of the https://repository.mulesoft.org/nexus/content/repositories/public/ which seems to stop working. You now how to store it in the Maven repository so you should help. To use the Maven repository will be better than to use the obscure repositories like the repository.mulesoft.org or jitpack.io

From https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2661

**Comment by SurfaceS** [comment]
#2813 done
