### ISSUE TITLE
Folders being re-added if deleted from shared content.

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2663]
A user on the forum only wants to use virtual folders and has tried to delete the default folders set in the shared content tab, but when they are deleted they are added again.
https://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=14874

I have noticed similar behaviour if I try and delete all the items in web content.

I think these should only be auto added if it is a new install but not on an existing one.

**Comment by SubJunk** [comment]
@griffrawk please test https://www.universalmediaserver.com/uploads/UMS-2663-content-readd-x86_64.tgz

**Comment by griffrawk** [comment]
@SubJunk looks OK re. editing the user's WEB.conf. It behaves as expected when deleting entries, they don't reappear (immediately or on restart). Added entries work as expected too.

I have deleted the user WEB.conf, and it is initialised with the defaults as expected. As above it all works fine from then on.

**Comment by SubJunk** [comment]
@griffrawk thanks for testing it thoroughly, very useful
