### ISSUE TITLE
Allow to set the log level of FFmpeg in its engine settings in the desktop UI

### ISSUE THREAD

**Issue by sken130** [UniversalMediaServer/UniversalMediaServer#2677]
The main reason I use Universal Media Server is, it can stream to DLNA clients while supporting external subtitles, which Windows Media Player can't do yet, and this functionality depends greatly on FFmpeg itself, so being able to quickly check the FFmpeg logs is important.

Currently, the FFmpeg's log level is set to "fatal" by default, and if I want to set the log level to have more details, I could only set it to "info" at best (by adding <logger name="net.pms.encoders.FFMpegVideo" level="TRACE" /> in C:\Program Files (x86)\Universal Media Server\logback.xml, and restarting the server and the desktop UI)

It would be great if there's a quick option to adjust the FFmpeg log level.

- I would suggest placing such option next to the "Filter" option for UMS's own log level.
- Also, currently, in addition to FFmpeg's log level, FFmpeg logs requires UMS's log level to be set to "debug" as well. You may either document this in the mouse over hint, or, make sure the FFmpeg log no matter of UMS's log level.

**Comment by sken130** [comment]
Here is a mock-up screen for my suggestion:

![ums_logs_tab_and_suggested_ffmpeg_log_filter_placement](https://user-images.githubusercontent.com/7981861/137434191-7d0013f6-e874-454a-9f9c-a2f1625e806c.png)

**Comment by SubJunk** [comment]
@sken130 sounds like a good enhancement. I'm not sure when, if ever, it would be done, but I'll leave it here in case anyone wants to do it. The fastest way is probably for you to learn Java ;)

**Comment by sken130** [comment]
Thanks!
