### ISSUE TITLE
MP4 Video is stuttering 

### ISSUE THREAD

**Issue by tibetwolfgit** [UniversalMediaServer/UniversalMediaServer#2683]
My problem is quite difficult to explain.

My UMS Configuration:
. no transcode for mp4 Videos
. Version 8.2.0
. Windows 10

My problem:
. Playback of video with variable frame rate
for example: average Frame Rate: 24,558 fps
Minimum Frame Rate: 0.101 fps
Maximum Frame Rate: 25,000 fps

The playback of that MP4 video stops every 10 minutes for about 10 seconds. Meanwhile, a two-time repetition loop runs on the soundtrack. Then the video continues normally.
--------
If I convert the same video before playing in a video with the fixed frame rate 24,000 fps, there are no problems with playback. 
If I convert the same video before playing in a video with the fixed frame rate 25,000 fps, there are the same problems with playback, as with the variable frame rate.

**Comment by SubJunk** [comment]
Stale
