### ISSUE TITLE
Folders like Name.1 will not Displayed only when i rename the Folder to Name_1

### ISSUE THREAD

**Issue by UMSGirl** [UniversalMediaServer/UniversalMediaServer#2697]
Folders like Name.1 are not displayed since Universal Media Server version 10+. Only folders names like Name_1 are displayed correctly on my TV. Are points in folder name a problem? 
Now I have to use version 9.5. I operate Universal Media Server with Linux / GNU Debian 11 Bullseys. Please help. The log has no errors displayed. That's why I have none attached.

**Comment by SubJunk** [comment]
@UMSGirl hey, cool username!
Are you using default settings, do you have prettifying enabled? That's something logs can help us see too

**Comment by UMSGirl** [comment]
Hey :) Thank you SubJunk ^^ 

Now i Uploaded the Debug File:
[ums_dbg_2021-11-28-07-28.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7612935/ums_dbg_2021-11-28-07-28.zip)

Yes, I use the default Settings. Without prettifying enabled.

The error ist only in UMS Versions 10.x.x+.
The Old Version 9.x.x

 works Great.

Please check the File :)

Thank you so much!

Kind regards
UMSGirl ^^

**Comment by Mik-S-UMS** [comment]
Someone else on the forum has come across this bug and I have confirmed it on my system too by renaming a folder to end in ".1"
https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14946

**Comment by SubJunk** [comment]
Thanks all, sorry I am low on time at the moment but I will try to fix this soon

**Comment by SubJunk** [comment]
@UMSGirl this is fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2771 which will be in the next release, thank you for reporting it!

**Comment by UMSGirl** [comment]
> @UMSGirl this is fixed in #2771 which will be in the next release, thank you for reporting it!
Thank you for your good Work :1st_place_medal:
