### ISSUE TITLE
Cannot use UMS: Another program is using port 5001, which UMS needs.

### ISSUE THREAD

**Issue by aemondis** [UniversalMediaServer/UniversalMediaServer#2698]
Unable to start UMS due to the port apparently being in-use (which it is not, as confirmed through multiple means including telnet, test-netconnection and netstat).
- Tried restarting computer
- Tried different ports (all same error)
- Tried running as admin
- Tried reinstall
- Tried clean configuration
- Tried reverting version
- Disabling AV
- Validated port is not in use before starting
- Ensured UMS Windows Service is not installed

This issue only occurred following most recent update and was working perfectly previous for many months. It had been working fine previously. OS is Windows 11 21H2 (22000.282).

Not sure what else it could be apart from a bug?

As an aside, the log messages below seems to be false, since this port binding issue prevents renderers being found and the admin interface being available:
INFO  2021-11-05 23:36:47.974 [main] net.pms.PMS Universal Media Server is now available for renderers to find
INFO  2021-11-05 23:36:37.225 [main] net.pms.PMS A tiny cache admin interface is available at: http://192.168.100.102:5001/console/home

[ums_dbg_2021-11-05-23-37.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7486026/ums_dbg_2021-11-05-23-37.zip)

**Comment by valib** [comment]
What is the correct IP address for your network `172.16.1.1` or `192.168.100.102`? Please try to set the network interface manually.

**Comment by aemondis** [comment]
> 
> 
> What is the correct IP address for your network `172.16.1.1` or `192.168.100.102`? Please try to set the network interface manually.
It is 192.168.100.102. The logs were from a clean config, just to be sure I didn't have any errors somewhere in there. I normally have it bound to the Intel NIC. Behaviour is unchanged.

**Comment by aemondis** [comment]
Updated ZIP following correct NIC binding. Same behaviour.
[ums_dbg_2021-11-06-00-38.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7486364/ums_dbg_2021-11-06-00-38.zip)

**Comment by SubJunk** [comment]
@aemondis if it is working using a previous version of UMS, can you please post logs from the previous version too, for us to compare?

**Comment by aemondis** [comment]
> 
> 
> @aemondis if it is working using a previous version of UMS, can you please post logs from the previous version too, for us to compare?

Will do, I just need to work out what version I had previously as I hadn't updated it in quite some time and used the auto-update. Will upload it once I have found the working version.

**Comment by aemondis** [comment]
So, after enabling IPv6 on my system (no idea why it was disabled, since I usually have it configured and running), everything is working properly now, even with the latest version... nothing else on the system changed.

As I can't reproduce the issue, even by disabling IPv6 again - I'm going to close this issue for now.

**Comment by valib** [comment]
@aemondis the UMS is using only IPv4 so I have no odea how to enable IPv6 can fix it. But you use WIN 11 we have no experience with it.

**Comment by SubJunk** [comment]
@aemondis thanks for updating us on it, it sounds like whatever it was, it was something unrelated to UMS

**Comment by aemondis** [comment]
@valib & @SubJunk, the more I've looked into it the more this seems to be a weird combination of events that led it here.

It is Windows 11, and I discovered by digging through some event logs that it had done an update behind the scenes without notifying. It looks like after a reboot, it changed my Wifi settings - so my Wifi & LAN were both connected on the system (both are different subnets). IPv6 got disabled somehow, and for whatever reason - reenabling it seemed to resolve the issue. When UMS encountered a file in one of my media folders with a corrupt file, it was also hanging with an unhandled exception and failing to start (unrelated to this original issue, this occurred due to a BSOD a few weeks ago I suspect). Multicast is currently misbehaving, but I suspect that is my NGFW causing this issue now.

All in all though, the original issue is gone but there is a lot of speculation as to what caused it...

In any case, thanks for your help and keep up the good work with UMS!

**Comment by aemondis** [comment]
@valib just FYI, UMS seems to normally run just fine with W11. It's very similar to W10, but has a few quirks more around usability than anything else. You will potentially need to do some good testing with the newer Intel CPUs though, as W11 introduces a new CPU governor to allocate threads to cores. The latest 12th Gen Intel CPU have "efficiency" cores (essentially Atom CPUs), and "performance" cores. If you don't get the scheduling right, you might end up with UMS utilising the slower cores for important activities or behaving weirdly by switching between E & P cores. Windows may not get it correct by default. I run an AMD system, and even it has seen massive issues initially due to the governor changes - but it is a traditional CPU architecture with only "performance" cores, so the aforementioned situation won't occur for anyone who doesn't have a 12th Gen Intel. At this stage, there is no announcement on these governor changes being backported to W10 either...

Just my two cents on what to expect with UMS on W11.

**Comment by Nadahar** [comment]
UMS is a Java program, and Java is "an abstraction layer" between the underlying OS and the applications. This means that you generally have very little control of the low-level details like this. For any "option" to be available, it must generally be valid across the different platforms supported by Java. This means that almost anything that is special for one OS or one hardware platform isn't available from Java "by design", the core idea is "write once, run everywhere".

So, either the OS'es or the Java virtual machine (JRE/JDK) must address issues like this, or they will remain issues for every Java program I'm afraid. Scheduling in general falls under the responsibility of the OS as I see it, so I hope they have a better plan than to let this fall on software developers.

**Comment by aemondis** [comment]
@Nadahar agreed, but it may for example need a JRE/JDK update to address potentially. My guess is there will be some sort of "affinity" option that might need to be set in the Java code to force it to the right cores. Haven't seen any word on this being available yet though. W11 as it stands runs slightly slower than W10 in most workloads too.
