### ISSUE TITLE
Web Interface does not display chinese characters

### ISSUE THREAD

**Issue by KrisCris** [UniversalMediaServer/UniversalMediaServer#2700]
[ums_dbg_2021-11-06-20-22.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7491535/ums_dbg_2021-11-06-20-22.zip)

![image](https://user-images.githubusercontent.com/38860226/140628719-fd24a0b0-874f-4bd4-b659-d2d7d71d0e7a.png)

**Comment by SubJunk** [comment]
@KrisCris thanks for reporting this problem, I'll try to fix it

**Comment by SubJunk** [comment]
@KrisCris I can't reproduce this actually, see this screenshot

![image](https://user-images.githubusercontent.com/584228/142820172-b22a097c-2748-43a5-b040-eb14fb660320.png)

I did notice you're using JDK 16.0.1 which will cause problems, though probably not this one.

Am I right that you have a Windows 10 server, but the web interface requests are coming from Google Chrome on macOS?

**Comment by KrisCris** [comment]
Yes you’ re right. I will switch the default idk to JDK8 and try that again :)

**Comment by SubJunk** [comment]
Stale
