### ISSUE TITLE
Cound not open the default web browser: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by MGAnton** [UniversalMediaServer/UniversalMediaServer#2725]
I just changed the computer and installed UMS-10.13.0 with Debian 11-Xfce and openjdk-11. I'd some problems but now everything works fine except the Web Interface. When I click system returns: _"Cound not open the default web browser: The BROWSE action is not supported on the current platform!"_. The debug.log file doesn't add any additional information.
On the old computer I installed UMS-9.8.0 with Debian 9-Xfce and openjdk-8, and all options work fine. I tried the same configuration in the new one and the error remains.
I check the UMS source and think that the problem is caused by different Linux distributions not saving the default applications, such as the web browser, in the same path or file, or not register them same.
So, when **PMS.getConfiguration().UseWebInterface()** (line 490 - UniversalMediaServer/src/main/java/net/pms/newgui/**LooksFrame.java**) can not find the web browser, returns a null point or a invalid value and the system returns the error message.
If I'm right, the problem can be solved simply with a symbolic link or by writing an ad hoc config file.
I tried to simulate the process in my computer with Eclipse, but with my little knowledge of Java and the handling of the IDE it was impossible.

**Comment by Nadahar** [comment]
As far as I can remember, this is abstracted by Java. UMS doesn't know where the browser is located, it just asks Java for "a place to send URLs to the desktop". Java takes care of the details with the OS/graphical environment which will forward the URL in question to the actual browser that is registered as the "default" browser. So, there's nothing much UMS can do when Java reports back that the `BROWSE` action isn't available.

It's very easy to open the web interface manually though. Just type the name or IP for the computer running UMS with `:9001` appended. If you're on the same computer that runs UMS, `http://localhost:9001` should work.

**Comment by SurfaceS** [comment]
Should be implemented in V11
