### ISSUE TITLE
[UMS v10.15.0] 'Media Library' Subfolders no longer populated + Start-Up Media Scan now incredibly slow.

### ISSUE THREAD

**Issue by JK98062** [UniversalMediaServer/UniversalMediaServer#2826]
[ums_dbg_2022-02-13-09-20.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8054670/ums_dbg_2022-02-13-09-20.zip)

Since updating from v10.13.0 to v10.15.0, the Subfolders inside the "Media Library" Directory are no longer being populated. (ie, Recently Added/Played etc.)

Additionally, the Media Scan that occurs upon Application Start-Up now takes significantly longer. Prior to updating it took between 1m and 1m10s, and after updating it takes 12 to 14 minutes.

Unsure if issues are related to each other.
Debug logs are attached.
Issues are completely resolved by rolling back to v10.13.0.

Happy to help with troubleshooting following advice Re: possible fixes.

**Comment by JK98062** [comment]
@SubJunk I thought that as well, so I made sure to kill all processes related to UMS (javaw.exe _**was**_ running even though UMS was closed) but the issue still persists.
Restarted PC, made sure all UMS processes weren't running then opened UMS and issue still persists.

Checked UMS' database directory (with and there's 4 files in it (thought was only meant to be 2).
![UMS](https://user-images.githubusercontent.com/32981828/153738197-1fe426c6-5286-4297-bbaf-b82d3af7f432.png)

Should any be removed? I did notice that 'medias.lock.db' is a few months old whereas the rest are all new-ish.

**Comment by SubJunk** [comment]
@JK98062 yeah I think removing the lock file should fix it. Strange that it is still there. I guess we could try to remove it when UMS starts since if it is really being used, that operation will just fail. I'll make an issue for it
Please let me know if removing the file fixes it

**Comment by JK98062** [comment]
Too easy, I’ll try deleting it when I get back on my Desktop.
Not sure how many other people, if any, have had the same issue, but I know I’ve had identical problems before when doing upgrade-installs of UMS. From memory, it occurred 4 times during a v9.x.x install and once during a v8.x.x install.
Would implementing a step during Setup; after it checks whether UMS is running and kills the process if it is; that looks for and deletes ‘medias.lock.db’ be a plausible step to prevent the issue from re-occurring?

**Comment by SubJunk** [comment]
@JK98062 good idea, once you confirm whether that fixes it I'll put that detail in an issue

**Comment by JK98062** [comment]
**_Can confirm_** that deleting 'medias.lock.db' completely fixes the issue. Installed v10.15.0, deleted lock file, ran UMS, and DB Migration appears to execute successfully. I let it finish then updated to v10.16.0, and zero issues as yet.

Rolled back to v10.13.0 then tried updating to 15 or 16 out of curiosity to see if the same issue returned and it did indeed. So it might be worth implementing that simple file-check fix into the Setup/Installer as discussed to prevent any future issues.

Checked to see if behaviour was same on Win10 x64 & x86 as well (I'm on Win7 x64). The issue presents; and is fixed; identically.
Just FYI.


On a completely unrelated note, I can't get UMS to Serve/Play Videos on two of my devices: a Panasonic DMR-HWT260 (DVR) and an FFalcon Smart TV (Rebranded version of TCL P65 Series with MS6586 Media Renderer). The Media Server's Visible on both, and I can browse my entire library but cannot play anything at all. I've got what appears to be the correct Renderer Profiles Enabled. Any Suggestions?

**Comment by SubJunk** [comment]
@JK98062 can you make another issue for the last paragraph please?

**Comment by SurfaceS** [comment]
This file was created before H2 v2 was released, so it's not related to the upgrade.
But it can explain why the auto upgrade failed.

> **From the H2 documentation :**
Default lock mode for version 1.4 and newer : This database file locking mechanism uses native file system lock on the database file. **No `*.lock.db` file is created in this case**, and no background thread is started.

So I presume this file was left from a hard shutdown, hibernate, or something like that when the H2 version was 1.3.
