### ISSUE TITLE
Attempt to remove medias.lock on install/startup

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2838]
Sometimes the h2database lockfile is getting left behind during the upgrade to h2 v2, which breaks the upgrade and leaves UMS in a very broken state.

The Windows installer should be able to remove the file after it kills the process, which it already does. Then we should also try to remove it on UMS startup, for other operating systems. If it fails because of permissions it could leave a note in the logs or otherwise notify the user. It could be a good use for the SSE notification system that @SurfaceS built.

**Comment by SurfaceS** [comment]
I don't think that the h2database lockfile delete can fail as the db folder don't need root privileges.
The only way it can fail is if an old version of UMS is started on the same time (it will lock the file).

I will add a h2database lockfile delete if exist on the #2843
