### ISSUE TITLE
FFmpeg releases

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#2840]
[FFmpeg 5.0 "Lorentz"](https://www.ffmpeg.org/download.html#release_5.0), a new major release, is now available.

5.0 was released on 2022-01-17. It is the latest stable FFmpeg release from the 5.0 release branch.

UMS should use the latest stable FFmpeg releases on all arch.

We find easily all arch ffmpeg for Linux and Arm.

But that can be difficult to have the 32 bits versions for mac and windows.

**Comment by SubJunk** [comment]
@SurfaceS this looks good, I will bump our versions soon. Since we use their development builds instead of release versions we aren't that far behind

**Comment by SubJunk** [comment]
Our source for Linux binaries seems to not be updating with changes since January 8. They did do a v5 release but nothing since then so I'll wait to see what has happened there https://www.johnvansickle.com/ffmpeg/

**Comment by SubJunk** [comment]
It looks like the builds are happening again so I'll do this soon

**Comment by SubJunk** [comment]
This was done
