### ISSUE TITLE
Piped ffmpeg InputStream give rubbish bytes at end

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#2866]
When I tried to made HLS working, I was not understand why it's not working as I expected.
To debug, I created files directly from ffmpeg with the same command as the transcoder do (from log). And when I HLS directly from that files it worked as expected.
Then, I downloaded the files from the transcoder and compare hex in files.
The file are identical at start, but UMS transcoder's file have rubbish at end.

I then logged the number of byte transferred from the server in `WebInterfaceServerUtil.dump(in, os);`:
From ffmpeg to the pipe :
`[AVIOContext @ 00000213b04f0c80] Statistics: 1136836 bytes written, 0 seeks, 198 writeouts`
From the pipe to the renderer :
`[Thread-221] Sending stream finished after: 1146880 bytes.`

And looking at the difference on files, it is 10044 more rubbish bytes on the UMS transcoder's file.

It may be a bug only on windows platform.

**Comment by SurfaceS** [comment]
A bit more investigation :
`WebInterfaceServerUtil.dump` use a 32*1024 bytes buffer (32768 bytes).
It's like the `bytes = in.read(buffer)` return the full buffer size for the last `read` instead of the total number of bytes read into the buffer.

**Comment by Mik-S-UMS** [comment]
Would this have effected all transcoding before or is this just for HLS?

**Comment by Nadahar** [comment]
As far as I know, this is a problem that has been there since PS3MS and that probably affected a lot of things. That said, I'm not sure if these "irregularities" are caused by only one bug.

**Comment by Mik-S-UMS** [comment]
I'm just wondering if this has been the cause of transcoded videos not resuming after being paused on the PS4.

**Comment by SurfaceS** [comment]
@Mik-S-UMS 
> Would this have effected all transcoding before or is this just for HLS?

all transcoding
