### ISSUE TITLE
UMS.conf overwritten at service start

### ISSUE THREAD

**Issue by Krakinou** [UniversalMediaServer/UniversalMediaServer#2875]
Hi,
I'm using UMS on a headless server on a Debian Buster
Since 10.17.0 (or 10.17.1 not sure): any changes done on file UMS.conf is systematically overwritten when restarting the systemd service that run UMS. For example if I add a new folder in the "folders" parameter, it is not taken into account and disappear from the settings. Same for changing the log level. I did not try other settings.

I successfully succeeded to change it by:
1/changing the setting in UMS
2/chmoding UMS.conf to read only and restarting the server
3/chmoding it again to rw and rerestarting the server again.
With this manipulation, changes are kept after a restart.

Here is the debug.log in TRACE mode:
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8201332/debug.log)

**Comment by Krakinou** [comment]
maybe related to #2864 and #2865?

**Comment by SubJunk** [comment]
@Krakinou yes that seems related, especially if UMS was unable to write to UMS.conf, since it needs to record that it ran once

**Comment by ik666** [comment]
Actually, I see the same behaviour, same setup like Krakinou. If you change any setting on the command line while UMS is running, they get overwritten after a `systemctl restart ums` call. As a workaround I stop UMS, make all changes and start it again.

**Comment by SurfaceS** [comment]
Their is no `FileWatcher` on the `UMS.conf` and the conf is saved at shutdown.
So it is a "normal" behavior as it is implemented.

When you change any setting from the command line while UMS is running, UMS doesn't know it, and doesn't apply this settings.
If it was, it can break itself (ex headless / gui, etc).
As the conf is implemented, their is no easy way to handle a reload.
So the best way to avoid your "bug" is to check if the file was changed from last load/save (by date, crc, etc) and do not save at shutdown if it was.

**Comment by ik666** [comment]
@SurfaceS It's not about reloading. I think in the past, the config wasn't saved at shutdown. Now, even though GUI config chances couldn't have possibly been made by a user in a headless environment, the config is overwritten by the GUI values and that without any user interaction. This is the bug.

**Comment by ik666** [comment]
@valib I think you might have done the change in PMS.java around line 724 (6 month ago):

````
	// force to save the configuration to file before stopping the UMS
	saveConfiguration();
````

**Comment by SubJunk** [comment]
I guess a fix could be to only run that line in GUI mode, or remove that line. I wonder why it was added
