### ISSUE TITLE
LG TV Voice sync issues

### ISSUE THREAD

**Issue by SAsquith** [UniversalMediaServer/UniversalMediaServer#288]
Hi. I am having voice sync issues with my TV a 42 inch LG 760T (42LM760T-ZB). The voice is lagging behind the video. 
I do not have this issue when I try to view the same video on my Sony Tablet which would suggest that it could be a setting on the TV itself, but then I do not have the issue when I access video through the network from my PVR.
Stuck, can anyone help?

**Comment by Sami32** [comment]
@SAsquith @SubJunk Did the latest UMS version solved this issue ?
If not please provide your full log http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
