### ISSUE TITLE
Default subtitle track is used even if other subtitle track is selected

### ISSUE THREAD

**Issue by andre-koehler** [UniversalMediaServer/UniversalMediaServer#289]
On my Sony TV I used the [Transcode] folder to select a certain audio and subtitle track, but no matter what subtitle track I select, UMS 3.5.0 always delivered the one marked as (default) in the mkv container.
(Issue occurs with the MEncoder backend)

The file plays fine after I remux it with mkvtoolnix to only contain only one audio and subtitle track.

Here is MediaInfo about the file I played:
General
Unique ID                                : 245940989077898934987079755238177350573 (0xB90682F46629EE188C81D069D4D5A3AD)
Complete name                            : D:\Videos\[Exiled-Destiny] Grenadier\[Exiled-Destiny]_Grenadier_Ep01_(67461123).mkv
Format                                   : Matroska
Format version                           : Version 1
File size                                : 339 MiB
Duration                                 : 24mn 14s
Overall bit rate                         : 1 957 Kbps
Encoded date                             : UTC 2007-07-12 04:43:39
Writing application                      : mkvmerge v2.0.0 ('After The Rain Has Fallen') built on Jan 13 2007 19:58:56
Writing library                          : libebml v0.7.7 + libmatroska v0.8.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 8 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24mn 14s
Bit rate                                 : 1 534 Kbps
Nominal bit rate                         : 1 949 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 3:2
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Original frame rate                      : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.185
Stream size                              : 266 MiB (78%)
Writing library                          : x264 core 55 svn-663
Encoding settings                        : cabac=1 / ref=5 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=7 / brdo=1 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / chroma_qp_offset=0 / threads=1 / nr=0 / decimate=0 / mbaff=0 / bframes=2 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=3 / wpredb=1 / bime=1 / keyint=250 / keyint_min=25 / scenecut=40 / rc=2pass / bitrate=1949 / ratetol=1.0 / rceq='blurCplx^(1-qComp)' / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / pb_ratio=1.30
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 24mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 33.3 MiB (10%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 24mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 33.3 MiB (10%)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 6
Format                                   : VobSub
Muxing mode                              : zlib
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : English
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 7
Format                                   : VobSub
Muxing mode                              : zlib
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Japanese
Default                                  : No
Forced                                   : No

**Comment by Sami32** [comment]
@andre-koehler Did the latest UMS version solved this issue ? @valib did make many improve on subtitles part since then so...
