### ISSUE TITLE
Cannot use "Downloads" folder as shared folder on macOS

### ISSUE THREAD

**Issue by afpr252** [UniversalMediaServer/UniversalMediaServer#2907]
After adding the Downloads folder as a shared folder, the following error appears in the logs:
> An error occurred while trying to browse folder "/Users/fury/Downloads": /Users/fury/Downloads: Operation not permitted

Full debug logs: [ums_dbg_2022-03-27-21-01.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8358372/ums_dbg_2022-03-27-21-01.zip)
I'm using the latest version of macOS, 12.3.

When I go to System Preferences > Security & Privacy > Privacy > Files and Folders, the UMS application isn't listed there, meaning that the application never triggers the point where macOS asks me if I want to give access to this folder or not, which is what happens when I use other applications. Maybe this has to do with the OS system call being used?
I've tried adding the application manually but the + button in that UI is disabled and I don't know if it's possible to add via command-line.

I am still able to use the application normally, it is just not possible to access the content inside the Downloads folder.

**Comment by SubJunk** [comment]
That's strange. For me on macOS, it asks me whether it can have access when UMS starts. However I'm still on 11.6.4 and Apple seems to lock down each major version more than the last.
I'll update to 12 soon so I can investigate this

**Comment by SubJunk** [comment]
On 12.3.1 it is working for me:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/584228/163707916-d0b3b4af-abb2-4d71-ac42-9f49e650199c.png">

I guess there must be some setting that needs to change. Can you try reinstalling? That might trigger macOS to renew permissions

**Comment by SubJunk** [comment]
I'm closing this since I believe it is a macOS problem. Feel free to reopen if reinstalling UMS doesn't work
