### ISSUE TITLE
mencoder in docker

### ISSUE THREAD

**Issue by Jille** [UniversalMediaServer/UniversalMediaServer#2922]
Hi @SubJunk and @wegotshrimp.

wegotshrimp wrote on https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1841#issuecomment-679272360:
> As a side note, has anyone gotten mencoder to work in the docker image? It doesn't come with it at all, but I wonder if you could compile it in alpine.

SubJunk wrote on https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1841#issuecomment-747142726:
> @wegotshrimp I have been unsuccessful at compiling a static version of MEncoder for Linux in the past after spending a long time trying. If you have any success with that we would love the contribution!

So naturally I was challenged.

I sent a patch to mplayer/mencoder upstream to fix the static build. (Still pending mailman moderation, I'll post a link soon.) I updated the Dockerfile to compile mencoder and include it (https://github.com/Jille/UniversalMediaServer/commit/c9fa879d76b6bc862fd6bad920f4632db9f4beaf). That seemed successful:

```
INFO  19:03:09.283 [main] Transcoding engine "MEncoder Video" is available
```

However, then I realized I didn't know why you wanted a statically compiled version. Can't we just do `apk add mplayer`? Even funnier, that actually seems to be statically compiled:

```
# apk add mencoder
# file $(which mencoder)
/usr/local/bin/mencoder: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

So, should I just send a PR to add `mplayer` to the list of things to install in docker?

**Comment by SubJunk** [comment]
@Jille nice writeup and investigation, thanks! The reason I prefer static versions is to prevent hard to catch bugs caused by different versions of dependencies.
That command looks promising, can you check which capabilities that version of MEncoder has enabled? Ideally it would have `libass` and `libx264` since that will let it handle subtitles.

**Comment by Jille** [comment]
That was surprisingly difficult to check. In the end I manually built the APK package and grabbed these lines from the `configure` output:

```
Checking for SSA/ASS support ... yes 
...
Checking for x264 ... yes (in FFmpeg: yes)
```

So it seems included. I've sent #2924 to add it to the Dockerfile, that seems easier than https://github.com/Jille/UniversalMediaServer/commit/c9fa879d76b6bc862fd6bad920f4632db9f4beaf.

**Comment by SubJunk** [comment]
Great work, thank you! :D

**Comment by Jille** [comment]
:)

My mplayer patch still wasn't let through mailman moderation. I'll set up a reminder to myself to link it here once it's finally approved.

@SnoozeThis mplayer-dev-eng@mplayerhq.hu has new message from jille@quis.cx

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/zdv8nbAOYa0) I will wait until mplayer-dev-eng@mplayerhq.hu has a new post from jille@quis.cx and then add a comment.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by Jille** [comment]
After a short two year delay my mail got through moderation :D

https://lists.mplayerhq.hu/pipermail/mplayer-dev-eng/2022-April/074240.html

**Comment by SubJunk** [comment]
Oh that is speedy. Congrats!
