### ISSUE TITLE
No response when a folder include 32bit float wav audio file

### ISSUE THREAD

**Issue by acvlwe** [UniversalMediaServer/UniversalMediaServer#2929]
OS:win10
UMS version:10.19.0

when a upnp client try to open a folder that include a 32bit floating point wav file or  server push to a client and the program dead.
a scan will trapped at that folder too.
nothing appear in the log.

**Comment by SurfaceS** [comment]
To debug, please attach a log in trace mode.

**Comment by acvlwe** [comment]
> To debug, please attach a log in trace mode.

sure i think i do that
this is the last related log.

TRACE 2022-04-16 21:21:03.705 [HTTPv1 Request Worker 104] Matched format WAV to "D:\1\1.wav"
DEBUG 2022-04-16 21:21:03.706 [HTTPv1 Request Worker 104] Reading enable_archive_browsing: true (default: false)
TRACE 2022-04-16 21:21:03.707 [HTTPv1 Request Worker 104] Matched format WAV to "D:\1\1.wav"

**Comment by SurfaceS** [comment]
With that 3 lines of log, I can't do nothing :)
I only see that you use the socket engine, maybe you should use the "default" one, as socket engine is not updated since a while.

I personally work/run on V11, and can't reproduce your bug on it.

But mediainfo is updated on this version and I see on the latest version [changelog ](https://mediaarea.net/MediaInfo/ChangeLog):
x WAV: fix freeze with 32-bit PCM

Maybe that's related.

**Comment by SurfaceS** [comment]
If you want to try if it doesn't failed with the latest mediainfo dll, close UMS, download the [mediaInfo64.dll](https://www.universalmediaserver.com/svn/binaries/win32/MediaInfo64.dll) and replace the one in your install folder.

**Comment by acvlwe** [comment]
> If you want to try if it doesn't failed with the latest mediainfo dll, close UMS, download the [mediaInfo64.dll](https://www.universalmediaserver.com/svn/binaries/win32/MediaInfo64.dll) and replace the one in your install folder.

no luck from replace the [mediaInfo64.dll](https://www.universalmediaserver.com/svn/binaries/win32/MediaInfo64.dll).
i restore the engine to "default".
here is the whole log
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8500935/debug.log)

**Comment by acvlwe** [comment]
i try the mediainfo given example with my problem wav and the latest version dll the results came out good:
[out.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8500964/out.txt)
it did freeze when i change it to the old version.

**Comment by SurfaceS** [comment]
It's definitely mediainfo version problem.
Your log run under old mediainfo version.
Maybe you need to replace the dll in program/win32 folder.

I'll not be available for few days.
I'll check that then.

**Comment by acvlwe** [comment]
> It's definitely mediainfo version problem. Your log run under old mediainfo version. Maybe you need to replace the dll in program/win32 folder.
> 
> I'll not be available for few days. I'll check that then.

the problem solved when i replace MediaInfo64.dll at the root of the pragram folder.
previously i repace the program/win32 folder one which the wrong one to replace.
thank for your time.

**Comment by SubJunk** [comment]
@acvlwe thanks for confirming. That MediaInfo update will be in our next release, probably this week

**Comment by acvlwe** [comment]
> @acvlwe thanks for confirming. That MediaInfo update will be in our next release, probably this week

good to hear that,appreciate your work
