### ISSUE TITLE
10.20: "A serious error occurred during Universal Media Server initialization: null"

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#2952]
```
ERROR 2022-04-29 01:26:04.148 [main] A serious error occurred during Universal Media Server initialization: null
DEBUG 2022-04-29 01:26:04.150 [main] 
java.lang.NullPointerException: null
	at net.pms.dlna.RootFolder.addVirtualMyMusicFolder(RootFolder.java:100)
	at net.pms.dlna.RootFolder.<init>(RootFolder.java:87)
	at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:497)
	at net.pms.PMS.getRootFolder(PMS.java:171)
	at net.pms.PMS.init(PMS.java:724)
	at net.pms.PMS.createInstance(PMS.java:928)
	at net.pms.PMS.main(PMS.java:1094)
```
Note: I have _all_ options under Navigation Settings' "Virtual folders / files" section turned off _except_ for "Show the '#--TRANSCODE--#' folder".

That's a very informative error message.

Back to 10.19....

**Comment by esabol** [comment]
The fix for this error is not in 11.0.0-a1, unfortunately. The error message is at least a bit more informative in 11.0.0-a1:
```
ERROR A serious error occurred during Universal Media Server initialization: Cannot invoke "net.pms.dlna.virtual.MediaLibrary.getAudioFolder()" because the return value of "net.pms.PMS.getLibrary()" is null
```

**Comment by ik666** [comment]
Ups, `getLibrary()` is null. Didn't guess that, sorry ... thanks for the more precise log info! I have updated #2953.

**Comment by SubJunk** [comment]
I'll do another release soon with that fix

**Comment by SubJunk** [comment]
@esabol if you let me know your operating system I can upload a build for you ASAP

**Comment by esabol** [comment]
> @esabol if you let me know your operating system I can upload a build for you ASAP

Oh, thanks for the offer. I use the Mac pre-10.15 dmg build.

**Comment by SubJunk** [comment]
No problem, I hope this works https://www.universalmediaserver.com/uploads/UMS-esabol.dmg

**Comment by esabol** [comment]
> No problem, I hope this works https://www.universalmediaserver.com/uploads/UMS-esabol.dmg

Thanks! This bug is fixed in that version.

However, an hour after I launched It, I couldn't browse any of my shared folders on my TV and had to quit/relaunch UMS again to get it to respond to any directory request other than the top-level listing of my shared folders. From my inspection of the logs, it sure seems like UMS is too busy scanning my hard drives (shared folders) to respond. I was really hoping this version would fix this problem which has plagued UMS for multiple releases. I really wish there was an option to not have UMS scan my hard drives on start up or ever really. Sorry, unrelated issue(s)....

**Comment by SubJunk** [comment]
@esabol can you please attach a debug package for this problem? I suspect that you have a combination of settings that makes that happen, but I need to see the config to be sure. Instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/blob/fd7534d220b854d0f0e164c8cf30de1df0b8172f/CONTRIBUTING.md#reporting-an-issue

**Comment by SubJunk** [comment]
Actually I don't think I need the config because this issue proves it. The problem is that you have the cache disabled, which means that UMS scans your drives but never remembers the things it scanned :D
I will work on preventing that in the program, but basically you have two options:
- enable the cache on the `Navigation Settings` tab, or
- disable startup scanning on the `Shared Content` tab

I highly recommend choosing the first option, because it will make all folders load faster after that initial scan. The scan should be very fast after the initial one, as long as the cache is enabled. Mine takes about 5 seconds on startup for a pretty big library

**Comment by esabol** [comment]
> I will work on preventing that in the program, but basically you have two options:
>
> * enable the cache on the Navigation Settings tab, or
> * disable startup scanning on the Shared Content tab

I have the "Scan shared folders at startup" option disabled in the Shared Content tab. I think I've always had it disabled. Frankly, I don't believe that option has ever worked as advertised.

I tried enabling the cache in the Navigation Settings tab for a couple weeks a few versions ago (somewhere between 10.13 or 10.17), but the cache would get corrupted almost every day presumably when UMS would run out of memory doing nothing but scanning my hard drives. Disabling the cache was the only way I found to prevent UMS from running out of memory on a daily basis and be usable.

> I highly recommend choosing the first option, because it will make all folders load faster after that initial scan. The scan should be very fast after the initial one, as long as the cache is enabled. Mine takes about 5 seconds on startup for a pretty big library

I'm skeptical, but I'll give it another shot though. I saw in the release notes for either 10.20 or 11 that the memory partition on macOS has been increased, so maybe it can finish caching now without getting corrupted. I have like 28 TB of content spread over 7 drives....

> Edit: I checked the code and my assumption was wrong, so I do still need to see your config file

OK, I'll try to get that to you tomorrow.

**Comment by SubJunk** [comment]
28TB of content is a lot, nice work!
I have noticed on macOS that UMS can spend a lot of time scanning because I back up my iPhone to the machine, and so UMS takes a long time to go through all the images. That can also lead to out of memory problems with the default shared folders.
Ok I'll take a look at your config when it's up and we can go from there. I am sure we can solve it.

**Comment by esabol** [comment]
@SubJunk : Here it is: [ums_dbg_2022-05-09-19-13.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8655932/ums_dbg_2022-05-09-19-13.zip)

**Comment by SubJunk** [comment]
@esabol thanks. I can see in the config there that the startup scan is disabled, and so is the cache. There isn't any scanning happening. So it all appears fine in those logs.
Can you enable the cache then reproduce a problem with it?
