### ISSUE TITLE
Web interface problem. ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by favorit5503** [UniversalMediaServer/UniversalMediaServer#2958]
Hi,

i installed the 10.20 version. I tried clean install aswell. After the initial setup it works fine but after a 1 day the web interface wont work.
This is the error what i got. Chrome: ERR_EMPTY_RESPONSE

The log shows this. 

14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:22 DEBUG authenticate mediaserver
14:19:22 DEBUG Got a browse request found id 0
14:19:22 DEBUG Make browse page 0
14:19:22 DEBUG Cookie 'UMS=' not found: [_ga=GA1.2.40731887.1623241630]
14:19:29 DEBUG Sending ALIVE...

I am using the web with authentication. I hope it helps but if somebody needs more info just tell me. Thanks.

**Comment by SubJunk** [comment]
@favorit5503 hi, sorry you're having that problem. Can you please provide full trace logs? Instructions at https://github.com/UniversalMediaServer/UniversalMediaServer/blob/907c0b60ce422293dcac4e81b6a5522589e935a6/CONTRIBUTING.md#reporting-an-issue

**Comment by favorit5503** [comment]
[ums_dbg_2022-05-04-07-59.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8618164/ums_dbg_2022-05-04-07-59.zip)

Hi here it is.

**Comment by SurfaceS** [comment]
@favorit5503 can you try v11 to see if you can reproduce this ? thx

**Comment by favorit5503** [comment]
Yep. On V11 no such issue. I will close this now.
