### ISSUE TITLE
Error on Linux makes UMS crash

### ISSUE THREAD

**Issue by jerry1970** [UniversalMediaServer/UniversalMediaServer#2965]
Since today, UMS crashes with the following response:

> \# A fatal error has been detected by the Java Runtime Environment:
> \#
> \#  SIGSEGV (0xb) at pc=0x00007f02fe3732cc, pid=44416, tid=0x00007f02f5e63700
> \#
> \# JRE version: OpenJDK Runtime Environment (8.0_332-b09) (build 1.8.0_332-b09)
> \# Java VM: OpenJDK 64-Bit Server VM (25.332-b09 mixed mode linux-amd64 compressed oops)
> \# Problematic frame:
> \# C  [libmediainfo.so.0.0.0+0x51f2cc]
> \#
> \# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> \#
> \# An error report file with more information is saved as:
> \# /home/<ME>/bin/ums-10.21.0.1/hs_err_pid44416.log
> \#
> \# If you would like to submit a bug report, please visit:
> \#   https://bell-sw.com/support
> \# The crash happened outside the Java Virtual Machine in native code.
> \# See problematic frame for where to report the bug.

I have been using UMS versions 10.8.2 for some months now and the error came up today. I installed UMS 10.21.0.1 and the same thing happens.

The error is at the very end. This is the last line of the output of `./UMS.sh`:

> INFO  22:32:01.343 [main] Universal Media Server is now available for renderers to find

I cannot start UMS (splash screen visible, dock icon does not even appear or for a fraction of a second).

The log file mentioned in the lines above has the same lines and then this:

> ---------------  T H R E A D  ---------------
> Current thread (0x00007f03904b8000):  JavaThread "Library Scanner" [_thread_in_native, id=44656, stack(0x00007f02f5c63000,0x00007f02f5e64000)]
> siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

I run Xubuntu: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

There is no newer version for libmediainfo.

Any ideas, even a hint of where to start looking and testing would be great!

**Comment by SubJunk** [comment]
Do you get any more details if you set this in `UMS.conf`?
`log_level=TRACE`

**Comment by jerry1970** [comment]
Thanks for the feedback! Yes, the regular log was 100 K, now it's 130 K. I attached the latest one.

There's but a few lines about libmediainfo. I am not sure which other software uses libmediainfo0v5 but I am using several apps that fetch metadata from media files. It is on version 19, which has been around since 2020-03-24 and definitely not new on my machine.
`libmediainfo0v5/focal,now 19.09+dfsg-2build1 amd64`

Any ideas?

[hs_err_pid71300.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8686443/hs_err_pid71300.log)
.

**Comment by SubJunk** [comment]
@jerry1970 which operating system are you on? You might have already tried this, but there is a list of operating systems on the MediaInfo website that might have more current versions than OS package managers https://mediaarea.net/en/MediaInfo/Download

**Comment by jerry1970** [comment]
@SubJunk , I am on Xubuntu (Ubuntu 20.04.4 LTS with XFCE 4.4):
```
Linux 5.4.0-109-generic 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Thanks for that link! No, I have not tried that yet. Will do and report back when I have!

**Comment by SubJunk** [comment]
Stale
