### ISSUE TITLE
help getting UMS up and running using Docker/Portainer installation

### ISSUE THREAD

**Issue by heater19** [UniversalMediaServer/UniversalMediaServer#2972]
I would like help in installing UMS on an openmediavault server;

In short, when i run the web interface at the port :9001, i'm not seeing the directory which contain my videos, what i do get are ums, root and Web as the folders, furthermore, I'm not seeing the media server come up on the PS3;

Thanks in advance;

the details are below:::::::::::::::::: 

the installation was done via portainer with the following settings:

image: universalmediaserver/ums:latest

added 3 ports - 1044, 5002 and 9001, all are TCP;

then I added 2 volumes:

the container is labeled - /media with the 'bind' option set, the path is set to '/srv/dev-disk-by-uuid-31265/Videos', which is then set to writable;

the second container is labeled - /profile with the 'bind' option set, the path is set to '/srv/dev-disk-by-uuid-31265/Config', which is then set to writable;

the environment variables are the following:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JVM_OPTS=-Xmx512M

Restart policy is 'unless stopped'

everything else was left with the default settings;

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[_ums_omv_logs.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8694135/_ums_omv_logs.txt)

**Comment by heater19** [comment]
ok, was able to make some progress;

by using atamariya's suggestion in this post: https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=12922&p=44808&hilit=docker#p44808 and set the UMS_PROFILE environment variable to /profile, I am now able to view the video files and it does stream through the web interface on port 9001 on my pc;

But, the PS3 is still not seeing the media server;
[_ums_logs(2).txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8696633/_ums_logs.2.txt)

a few interesting things I noticed from the logfile:

there is a line stating the MulticastReeiverImpl is being initialized on port 1900, is this important for the DLNA function?

also, the multicast joins the network interface: docker0

last, but likely not least, there is a renderer found that is identified as Sony Xperia Z/ZL/ZQ/Z1/Z2, i have no Sony Xperia, but i do have a Sony PS3, could the mixup be at this level?

**Comment by SubJunk** [comment]
Stale
