### ISSUE TITLE
4K scale

### ISSUE THREAD

**Issue by Hypnos-CH** [UniversalMediaServer/UniversalMediaServer#2974]
Theres is a problem with the scale 4K, Win 11 scales 300% in 4K, but UMS doesn't follow the scale.

**Comment by SubJunk** [comment]
Which version of UMS? It might be better in v11 alpha

**Comment by Hypnos-CH** [comment]
10.21.0.1 public build

**Comment by SubJunk** [comment]
Can you try v11?
