### ISSUE TITLE
UPnP: DeviceDetails.BaseURL not set in 11.0.a2

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#2987]
It seems like the baseURL is not set in the UPnP DeviceDetails attribute with configured `server_engine = 4` (JUPnP Netty).

**Comment by SubJunk** [comment]
@SurfaceS can you look at this please?

**Comment by SurfaceS** [comment]
From UPnP Device Architecture 1.0

URLBase
Optional. Defines the base URL.
Use of URLBase is no longer recommended.
If URLBase is empty or not given, the base URL is the URL from which the device description was retrieved (which is the preferred implementation)

From UPnP Device Architecture 1.1
Use of URLBase is deprecated in UPnP 1.1
UPnP 1.1 devices MUST NOT include URLBase in their description documents.

From UPnP Device Architecture 2.0
UPnP 2.0 devices shall NOT include URLBase in their description documents.

**Comment by ik666** [comment]
OK, then we probably don't need it ...
