### ISSUE TITLE
Web Interface doesnt show control once it starts playing OSX

### ISSUE THREAD

**Issue by schroef** [UniversalMediaServer/UniversalMediaServer#2994]
UMS 10.21.0.1
OSX 10.11.6
Chrome 101.0.4951.64

Description
When start watching a video using the web interface. It will show the video controls when buffering starts. However once it has buffered and video starts playing. No controls are shown and it acts like its a live feed without only a pause and play button to control the video. This happens on both desktop and mobile

Controls show before pressing play
![Screen Shot 2022-05-23 at 15 40 39](https://user-images.githubusercontent.com/6923008/169894243-5182b87d-9e4e-4103-b06c-dc52ae9f652f.png)

No controls visible when it plays
![Screen Shot 2022-05-23 at 15 40 47](https://user-images.githubusercontent.com/6923008/169894239-78c79439-7973-4388-9a21-77dfe23f747b.png)

**Comment by schroef** [comment]
On OSX chrome browser i can rightclick and use "show all controls" it will show a timeline now, hardly usable since its locations is below other buttons. Not sure how to reach this on mobile though

![Screen Shot 2022-05-23 at 15 45 46](https://user-images.githubusercontent.com/6923008/169894930-dc170ceb-3364-4d3d-8169-3334a50f948e.png)

The issue is in the div with VJS settings (video.js), it has the class vjs-live, therefor the scrubber is hidden. If remove it, it does show scrubber. This would be more useful i think

**Comment by SubJunk** [comment]
@schroef we have greatly improved the web interface player in v11 and I think that will fix this for you. Please try the latest alpha version and let me know.

**Comment by schroef** [comment]
Ah nice! I was trying that out as well. But the page kept reverting to original code. I didnt understand where vjs-live came from all the time.
But that was exactly what i was testing with video.js
