### ISSUE TITLE
Apple Silicon M1

### ISSUE THREAD

**Issue by soulnick** [UniversalMediaServer/UniversalMediaServer#3009]
Hi all, thank you for tour effort. 
I would like to know if there is any plan to release a version that runs natively on the new apple cpu.

**Comment by SubJunk** [comment]
@soulnick yes I am planning that, there is a discussion at https://github.com/UniversalMediaServer/UniversalMediaServer/discussions/2989 too
I don't know how long it will take but this issue can be the place for updates on it, and of course we welcome code contributions as we are open source :)

**Comment by tfagundess** [comment]
Since this is going to be the issue to discuss that, I leave the Apple official link for the matter here as well: https://developer.apple.com/programs/universal/

**Comment by SubJunk** [comment]
Our first Apple Silicon build was just released, 11.2.0.
It included an ARM binary for FFmpeg which seems to give around 3x transcoding speed improvement. We will continue to add more native binaries as we find them, and please feel free to help us locate them.

**Comment by tfagundess** [comment]
That was fast! I will try it and see if it works without issues and report back. Thanks!

**Comment by SubJunk** [comment]
We have also just released 11.3.0 which is has signed and notarized macOS builds, hope you enjoy :)

**Comment by soulnick** [comment]
task manager says intel executable, is it normal?

**Comment by jconley** [comment]
@SubJunk seeing the same, [UMS-11.2.0-arm.dmg](https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/11.2.0/UMS-11.2.0-arm.dmg) is only a x86_64 binary
```
% file UMS
UMS: Mach-O 64-bit executable x86_64
```

**Comment by SubJunk** [comment]
It's 11.3.0 that is signed, not 11.2.0
