### ISSUE TITLE
Windows Media Center ".wtv" chapter support is missing

### ISSUE THREAD

**Issue by snickerweb** [UniversalMediaServer/UniversalMediaServer#301]
Hi, wtv Stream works. But the chapter folder is empty. 
Is there a reason?

Steps to Issue:
1.  Record Live TV with Windows Media Center 7/8
2.  Look in the Transcode Folder "Chapter" in the recoded wtv file
3.  Nothing there

System:
Server: Windows 8.1
Renderer: Philips TV/ Sony Bravia TV/iOS Apps

(Same like issue 91 on Google Code)

**Comment by Sami32** [comment]
@snickerweb Did the latest UMS version solved this issue ?
If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
