### ISSUE TITLE
Filescanning - OS-X

### ISSUE THREAD

**Issue by Optimusprimeums** [UniversalMediaServer/UniversalMediaServer#303]
Just putting this in as a marker (to fix it if possible):
When using the regular 3.6 build with mac OSX java 1.65 , every file starts up almost immediately and filescanning seems no problem.
However when watching files there is a continues glitch first in the picture which seems to pause while audio keeps running and then the audio stops and the picture continues running until the two catch up on each other and starts running like they should simultaniously again.
This happens about five to six time during a movie.
Then the 'funny' thing : When using the Java 7 or Java 8 builds the filescanning seem to take forever and it takes a long time before a file starts to play , weather it is a audio or video file and no mater if it is Flac/Mp3/Avi/Mkv/Mp4 it is all the same.
Now however , every file when it starts it keeps on running smoothly like you want it to be until the end.

I really don't know what the differences between the builds can be and if this is a Java or UMS related thing , but is it an option for one of the great developers working on this project to try and sort this out so there can be one perfect UMS to use ?

As for now I stick with the latest Java 8 build and the long loading times as I prefer this to watching or listening with glitches. (Thanks Snakebyte for your help)

**Comment by Sami32** [comment]
@Optimusprimeums @SubJunk Did the latest UMS release fixed this issue ? No such problem on Windows by now, but i don't have a Mac to test on it.
