### ISSUE TITLE
build issue with JDK 17 on MacOS

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#3034]
Hi guys: I've a build issue on MacOS (12.4) using Amazon JDK with the current main branch (11.x).

Using JDK 17 I get a `javax.net.ssl.SSLHandshakeException` error while downloading some files from `[...] src="https://www.universalmediaserver.com/svn/binaries/linux/x86_64/ffmpeg/ffmpeg?p=155" [...]`. I believe JDK 17 has other (intermediate) certificates and the provided certificate from `www.universalmediaserver.com` is not accepted any more ... 

In the past I could switch to a JDK <17 version like JDK 15 or 8. Then all downloads went fine. Now, that we have a "JDK 17" release (defined in pom.xml) this trick doesn't work any more.

Has anyone discovered the same?

**Comment by ik666** [comment]
Strange: Using same JDK on Linux (Ubuntu) works ... 
On Mac: I am using the following

`MAVEN_OPTS='-Xms512m -Xmx1024m -Djavax.net.ssl.trustStoreType=KeychainStore -Djavax.net.ssl.trustStoreProvider=Apple'`

**Comment by SubJunk** [comment]
Hmm not sure about the extra flags you're using, I don't use any flags. This is the entire script I use on macOS:

```
export JAVA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-17.jdk/Contents/Home"
export M2_HOME="~/apache-maven-3.8.5"
export M2="${M2_HOME}/bin"
export PATH="${PATH}:${M2}"

mvn -P macos package -Doffline=true -DskipTests=true

hdiutil create -volname "Universal Media Server" -srcfolder target/ums-*-distribution UMS-.dmg
```

**Comment by ik666** [comment]
ok, i see ... thanks for the build script ... I deleted the MAVEN_OPTS opts and this made it work again ...

The maven opts were set for using the apple keystore in the maven build. This is not neccesary for UMS.
