### ISSUE TITLE
Web settings: Remove initial user

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3046]
This is a task to complete for https://github.com/UniversalMediaServer/UniversalMediaServer/issues/3004

At the moment there is a default user `ums` with a default password that is changed manually on first login. This allows anyone to create the initial user, but also requires hidden knowledge of the username and password. 

Instead, it would be just as secure and more user-friendly to have no default user. The first time someone goes to the configuration section they are greeted with a form to create the initial user, with any username or password.

**Comment by SurfaceS** [comment]
I add some code #3063 to allow that but I'm not confident with react, so I cannot do a lot on this side.

When react app will handle the session data, we can delete the user creation on db creation.

I think that the "change password" should be replaced by "accounts", with 2 tabs on the page ("users", "groups").
Then on the "users" tab, a user can change his (or other if he have permission) password, username, display name, group, etc.
And permissions, name on the "groups" tab.

This also may enable in the future, the ability to assign custom shared content by group, as some users have requested.
