### ISSUE TITLE
docker container: Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by vrtlspd** [UniversalMediaServer/UniversalMediaServer#3050]
Error when running via docker container.
please add: JAVA_OPTS="-XX:+UseContainerSupport"
```
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by SubJunk** [comment]
@vrtlspd thanks for reporting this problem!
It looks like `UseContainerSupport` is enabled in Java by default, so enabling it wouldn't fix this. I have instead removed `UseCGroupMemoryLimitForHeap`

**Comment by SubJunk** [comment]
@vrtlspd if you pull latest from Docker it should have fixes for both of the bugs you reported. Thanks again

**Comment by Theo-user** [comment]
Issue still occurs with the updated version 10 hours ago

Unrecognized VM option 'UseCGroupMemoryLimitForHeap'

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

**Comment by Theo-user** [comment]
Fixed. Thank you.
