### ISSUE TITLE
Media metadata does not show in logs if exists in DB

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3052]
Something I miss from the logs that is helpful to track down problem files for users is seeing the media info for that file in the logs.
When a new file is scanned it's mediainfo is shown in the logs but if a file has already been scanned and it's metadata is stored in the database it does not log them so I have no idea why some videos is not playing on the renderer.

Could it be possible to show that in trace logs when the metadata already exists?

**Comment by SubJunk** [comment]
Yeah that would be possible to do it when it's read from the database, as long as it's in TRACE mode so that we don't bloat the logs for the average user

**Comment by SubJunk** [comment]
Done thanks to @Priyanka-GD
