### ISSUE TITLE
Program window scaling problem

### ISSUE THREAD

**Issue by antekeli** [UniversalMediaServer/UniversalMediaServer#3059]
On a 4K monitor, the buttons and texts in the program look very small. Windows 10 scaling does not work in this program.

![1](https://user-images.githubusercontent.com/35841233/173823830-70f9a2bf-3013-4a2a-8567-f1dbf32c205e.jpg)

**Comment by SubJunk** [comment]
@antekeli thanks for reporting this. You might find it is better if you update to v11, please let us know

**Comment by SurfaceS** [comment]
was already reported and closed on java 8.
V11 has solved that.
