### ISSUE TITLE
Unknown transcoding engine "ffmpeghlsvideo"

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3060]
The user Paradox has reported this bug since v11 https://www.universalmediaserver.com/forum/viewtopic.php?p=45702#p45702
Probably one for you @SurfaceS when you're back

**Comment by SurfaceS** [comment]
This message is only an information that the player is not found.

HLS was first on it's own player (v11 alpha), then it was included in ffmpeg player.
If someone change settings (enabled players, player's order) from v11 alpha, it can have this message.

To completely remove this message, remove `,ffmpeghlsvideo` from the `ums.conf` file, on line starting with `engines =` and `engines_priority =`.
