### ISSUE TITLE
Audio not playing in web interface in V11

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3061]
Another [user](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15158) has an issue playing audio from the web interface and I can confirm it happens to me too in all V11s so far but works fine in 10,21.0
The length of the track is shown as 0:00 and pressing play does nothing for mp3 and flac.

**Comment by DiegoBM** [comment]
I can confirm that audio won't play on web interface for UMS windows neither on v12 nor v13. When you navigate to the song no player will be displayed. Video and pictures work fine though

**Comment by Mik-S-UMS** [comment]
It happens to me too. I can just see a flash of the player then it disappears when clicking on a mp3 file.
This is on firefox and I have made sure my adblocker is disabled.
I don't see any mention of the "invalid value 30" error in the logs though. 

This may be a different issue as the original did show the player but had the length of the tracks as 0

**Comment by SubJunk** [comment]
Hopefully this was fixed by #3739
