### ISSUE TITLE
UMS Build in Netbeans :)

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#307]
Granted i know this isant a UMS issue in it self -- and maybe by design and all. 

But how do I get Netbeans to build UMS using all cores?

![image](https://cloud.githubusercontent.com/assets/5233969/2882476/e42b5de0-d48e-11e3-8b86-bcb162ffd219.png)

**Comment by Sami32** [comment]
@SubJunk I guess it could be closed now ?
