### ISSUE TITLE
Web settings firstLogin cleanup

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3082]
There are still references to `firstLogin` since that logic was used to force a password change. That is no longer needed anymore so the associated logic should be removed, from the API and client.

**Comment by SurfaceS** [comment]
`firstLogin` was first intended to force a password change. The associated logic was already removed.
Now it check for the first admin on the db (as a user can delete all the admin users or the db itself) to create the first admin account.
Maybe we can rename it to `noAdminFound` or something like that to be more explicit ?

**Comment by SubJunk** [comment]
Good idea. We can also rename the `FirstLogin` React component to `CreateUser`, or even merge it with the `Login` component since they are very similar
