### ISSUE TITLE
Square appears in upper left corner in headless mode

### ISSUE THREAD

**Issue by andreicristianpetcu** [UniversalMediaServer/UniversalMediaServer#312]
Hi! A little square appears in upper left corner when I run in headless mode. I think it takes a screenshot of the desktop and then it replaces that part with the screenshot. I use Arch GNU/Linux with GnomeShell
![screenshot from 2014-05-10 16 41 09](https://cloud.githubusercontent.com/assets/922368/2936141/b5be2948-d848-11e3-8360-baf8c271e9a2.png)

**Comment by polygirl** [comment]
@andreicristianpetcu Please could you attach full TRACE logs - you can get these by going to Logs and clicking Create TRACE logs.  This will help us to investigate further.
