### ISSUE TITLE
AUDIO AND VIDEO NON SYNCRONIZE IN DIRECTV HD RENDER

### ISSUE THREAD

**Issue by LEOUMS** [UniversalMediaServer/UniversalMediaServer#313]
Hi.
I just install UMS into my pc W7.
Everything is fine but  when i play a movie in my Directv set top box , delay between audio and image appear.
I need to know how i can resolve this problem.
thanks a lots.
Best regards.
Leo

**Comment by Sami32** [comment]
@LEOUMS @SubJunk Did this issue can be closed ? No log...

**Comment by polygirl** [comment]
Hi @LEOUMS It's been some time since you posted this issue and we see that you didn't post the logs that we need to investigate so we are closing the issue.  If it's still a problem for you please feel free to reopen with the TRACE logs we need as per the instructions above.
