### ISSUE TITLE
Autorotate videos based on EXIF tags

### ISSUE THREAD

**Issue by pierrequere** [UniversalMediaServer/UniversalMediaServer#315]
Hi everyone ! I'm new on Github and on UMS too ! (sorry for my english, i'm french...)
In my iPhoto Library folder (mac OS X, mavericks) i have many videos, all in .mov (h.264/mp4) format. Mplayer play the ones shot with my Lumix TZ7 camera all right, but those shot with the iPhone 4S/5S upside down ! I found that the problem comes from the iPhone and I found a Mplayer code that should be able to solve this problem see http://ygrek.org.ua/p/code/mplayer_autorotate.
I'm not good at command lines, and this code unfortunately doesn't work when i add it directly in expert parameters for Mplayer in UMS...
Meanwhile, i've tried this : container == mov :: -vf flip,mirror "180" : it works well but of course flips all the video files :(
Would it be possible to include those code lines directly in the application ? Thanks for my neck :)

**Comment by Sami32** [comment]
@pierrequere Did EXIF not used for images only ?
FFmpeg since february have a good XMP support for MOV files that could be implemented, but you camera or yourself (Exiftool) will need to give this kind of informations.

@SubJunk will more helpful on this subject
