### ISSUE TITLE
Log Level cannot be changed to Error or Warning

### ISSUE THREAD

**Issue by amalic** [UniversalMediaServer/UniversalMediaServer#317]
whenever i change the loglevel to something else than "Error" or "Warning" the change is displayed in the Log -> "Changed debug level to ..." (should be more like "Changing log level to ..."). 

This seems not to be working with Log Level "Error" or "Warning".

**Comment by Sami32** [comment]
@amalic @SubJunk I cannot reproduce this issue on Windows.
Can you close this issue ?

**Comment by Nadahar** [comment]
The logging has since been pretty much rewritten and this works AFAIK.
