### ISSUE TITLE
why youtube-dl

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#3197]
why do you use youtube-dl.exe in the project and not yt-dlp witch is a lot beter i think
i also back in the day used youtube-dl but sins i use yt-dlp i cannot go back

**Comment by SubJunk** [comment]
@Goten87 I hadn't heard of that, can you explain why it's better for us?

**Comment by Goten87** [comment]
@SubJunk i dont realy know why you use it for but from what i see yt-dlp is more up to date (now i see that youtube-dl is being updated again as well) but at my time of switching youtube-dl had not had a update for 1 or 2 months

also the functions are beter in yt-dlp for what i wanted to do with it but again i dont know why you use it

**Comment by SubJunk** [comment]
@Goten87 it allows live YouTube videos to be played via UMS

**Comment by neutric** [comment]
`yt-dlp`, a fork of `youtube-dl`, is an order of magnitude more active than `youtube-dl` and improvements on the latter are being pulled into `yt-dlp`. Please compare https://github.com/yt-dlp/yt-dlp/pulse/monthly with https://github.com/ytdl-org/youtube-dl/pulse/monthly.

**Comment by Goten87** [comment]
i was not able to say it beter then neutric haha

**Comment by rhayy** [comment]
I would to argue in favor of yt-dlp.
- Statistics aside, as neutric said, youtube-dl updates are pushed into yt-dlp. You should have at least the same capabilities.
- Bandwith is limited to a few kb/s with youtube-dl for some reason whereas yt-dlp can play videos smoothly.
- As it is updated more actively and people contributing more in this project, it supports more video platforms.
At the moment, youtube-dl is a symbolic link pointing at yt-dlp.

**Comment by SubJunk** [comment]
@rhayy I think it's a good idea, it just has to be done :) Will you contribute a PR?

**Comment by SubJunk** [comment]
This almost got done but now youtube-dl is active again and is backporting good changes from yt-dlp so let's stick with it. If youtube-dl becomes inactive again we can switch.

**Comment by SubJunk** [comment]
We have just switched over because youtube-dl got inactive again, in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/5693
