### ISSUE TITLE
Web settings: Split tabs into components

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3208]
settings.tsx is over 1,000 lines long, let's split each tab into its own component

**Comment by SurfaceS** [comment]
Maybe the settings should be rearranged?
I always thought it was messy.

**Comment by SurfaceS** [comment]
@SubJunk I think about something like : 

In **General settings** :
  - Application settings
  - Services settings
  - Advanced Network settings
  - External outgoing traffic settings

Application Settings : language, tray, etc Prevent sleep (moved here).

Services settings : Server name (move here), Upnp on/off, server engine for Upnp, mDNS (chromecast) on/off (if upnp on)

Advanced Network settings : same as now.

External outgoing traffic settings : EnableExternalNetwork  + API / CoverArtArchive / MusicBrainz etc to be more explicit on what they allow or not.

Create **Renderers settings** tab :
Move the renderer configs here.
(maybe someday customize/add/delete etc for personal renderer setups)

In **Navigation settings** :
  - General settings
  - Thumbnails
  - File sorting / naming
  - Virtual Folders

General settings : Enable the cache, Reset the cache, Browse compressed archives (zip, rar, etc.), Minimum item limit before using A-Z folders, Enable video resuming, Use target file for symbolic links, Fully played action, Hide empty folders

Thumbnails : same as now rearranged (video then audio, then image).

File sorting / naming: same as now (without Use info from our API moved before).

Virtual Folders : only the "Show....".

**Comment by SubJunk** [comment]
Yes definitely the settings are messy, I look forward to rearranging them too. I find it hard to work with Java GUI so didn't make the improvements I wanted to, but with Mantine I think it will be easy for us

I was waiting until we had finished migrating so I wouldn't lose track of what was done, but since we only have the Shared Content tab left, maybe we can start improving the layout now

**Comment by SurfaceS** [comment]
I started it

**Comment by SurfaceS** [comment]
#3213 something like that

**Comment by SurfaceS** [comment]
Also, I try to take care that the GUI is working well from mobile.
Going to sleep now

**Comment by Mik-S-UMS** [comment]
I had some similar ideas for improving the GUI a while ago and wanted to attempt to learn Java to help but gave up. Some of them might be easier to do now if relevant. #2125 

I think the Shared folders tab needs a lot of improvement from what is there in the program GUI. I was thinking it might be better to treat all folders as virtual folders from now on so this gives the option to rename them for the renderer, and easily add additional folders by expanding the folder.
All the security options could be included here too to make it easier to setup IP filtering etc.
It would be even better if things like the #--TRANSCODE--# folder could be enabled/disabled and shown here, and all folders can be rearranged with drag and drop.

Maybe something like this I mocked up in excel
![image](https://user-images.githubusercontent.com/66766335/182674325-c2f974bb-915c-4f59-bb49-e935c12ca869.png)
[v] and [^] to show the folders
[S] could be a shield icon to open security options and if enabled could be shown in a different colour.
[O] could be a gear icon for extra options like monitor folder/play status, plus maybe specific transcoding options per folder in the future.
[+] to add a new folder

You could also combine the virtualfolders.conf, web.conf and the Security and privacy rules in to one file, maybe something called like media.conf. This could be created from existing settings and the original settings can be kept for compatibility if someone wants to use a previous version.

**Comment by SubJunk** [comment]
These are good ideas. I'm really looking forward to being able to iterate faster on the GUI with our web interface and can certainly do some of these ideas
