### ISSUE TITLE
Frequent disconnects on Samsung AllShare

### ISSUE THREAD

**Issue by cschroedt** [UniversalMediaServer/UniversalMediaServer#321]
Hi, I'm connecting to a Samsung Player via AllShare and WLAN. Initally this works fine but the connection always breaks down after a couple of minutes even if no streaming occurs just by looking into the server directories. Thanks for help. (I would like to attach the log zip but this seems to be not possible here.)

**Comment by Sami32** [comment]
@cschroedt @SubJunk Did the latest UMS version solved this issue ?
If yes, please close it, if not submit your TRACE log following these instructions
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
Hi @cschroedt it's been some time since you posted this issue so we presume it's not longer a problem for you and we're closing it.  If it's still an issue for you please feel free to reopen with TRACE logs as detailed above so that we can investigate.
