### ISSUE TITLE
Dates not shown on renderer after updating to 11.x

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3215]
A [user](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15233) has found that dates are no longer being sent to the renderer after upgrading to V11. I thought it was a database problem as there were errors about missing a column in the logs but after a database rebuild it still happens.

From what I can tell UMS is sending CREATIONDATE=0 for each file to the renderer as part of the directory listing.

**Comment by SubJunk** [comment]
Ah yeah, I can see that will have been happening since 11.2.0, and somewhat since 10.20.0
I'll make a fix
