### ISSUE TITLE
New Media folder not sorted.

### ISSUE THREAD

**Issue by robertc99** [UniversalMediaServer/UniversalMediaServer#323]
The items in the New Media folder appear in "random" order rather than your selected ordering,

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/626

**Comment by Sami32** [comment]
@robertc99 If the latest UMS version don't feel your need, get a look at this @taconaut nice fork oriented medias libraries.
http://www.universalmediaserver.com/forum/viewtopic.php?f=6&t=3355

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942
