### ISSUE TITLE
4.0.0-a1 on Mac OS X 10.7 Lion - fails to start up

### ISSUE THREAD

**Issue by dreamcat4** [UniversalMediaServer/UniversalMediaServer#331]
Hi there.
If I delete my v3 config folder. First start I get the setup wizard, asking few dialog popups about the network speed, etc.

After setup wizard ends, then nothing more happens. Execution does not continue. The console shows it threw an exception here:

    26/06/2014 19:39:29.750 [0x0-0x4e04e].Universal Media Server v4: INFO  2014-06-26 19:39:29.747 [main] 
    26/06/2014 19:39:29.757 [0x0-0x4e04e].Universal Media Server v4: INFO  2014-06-26 19:39:29.747 [main] Web conf path: /Users/id/Library/Application Support/UMS/WEB.conf
    26/06/2014 19:39:29.757 [0x0-0x4e04e].Universal Media Server v4: INFO  2014-06-26 19:39:29.748 [main] Web conf permissions: file not found
    26/06/2014 19:39:29.757 [0x0-0x4e04e].Universal Media Server v4: INFO  2014-06-26 19:39:29.748 [main] 
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: ERROR 2014-06-26 19:39:30.404 [main] A serious error occurred during PMS init
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: java.lang.StringIndexOutOfBoundsException: String index out of range: -5
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at java.lang.String.substring(String.java:1937) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at java.lang.String.substring(String.java:1904) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.util.WindowsRegistry.readRegistry(WindowsRegistry.java:34) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.configuration.PmsConfiguration.isAutoStart(PmsConfiguration.java:1513) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.newgui.GeneralTab.build(GeneralTab.java:104) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.newgui.LooksFrame.buildMain(LooksFrame.java:419) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.newgui.LooksFrame.buildContent(LooksFrame.java:391) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.newgui.LooksFrame.<init>(LooksFrame.java:264) ~[ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.PMS.init(PMS.java:520) [ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.PMS.createInstance(PMS.java:1038) [ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at net.pms.PMS.main(PMS.java:1130) [ums-4.0.0-a1.jar:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at apple.launcher.LaunchRunner.run(LaunchRunner.java:116) [na:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51) [na:na]
    26/06/2014 19:39:30.406 [0x0-0x4e04e].Universal Media Server v4: 	at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52) [na:na]

It downloaded today, this build:

    UMS-4.0.0-a1.dmg	2014-06-02	55.2 MB
    http://sourceforge.net/projects/unimediaserver/files/Official%20Releases/OS%20X/UMS-4.0.0-a1.dmg/download

**Comment by Sami32** [comment]
@dreamcat4 FreeBSD
Already solved by @SubJunk 
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/294#issuecomment-48833689
