### ISSUE TITLE
Sound disappears when using ffmpeg

### ISSUE THREAD

**Issue by Djdfy14** [UniversalMediaServer/UniversalMediaServer#3317]
Hello, when playing some mkv files, after about 1 minute of watching the video, the sound is turned off when using FFmpeg, after that the image disappears for a few seconds, so it repeats every minute. How to fix it?

[ums_dbg_2022-08-31-22-45.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/9475332/ums_dbg_2022-08-31-22-45.zip)

**Comment by SubJunk** [comment]
I can reproduce the problem, I'll look into it

**Comment by SubJunk** [comment]
It happens for me on my TV but not if I open the file on my PC. I'll keep digging

```
ffmpeg -y -loglevel info -i file.mp4 -bufsize 31250k -maxrate 31250k -crf 19 -ab 448k -c:a ac3 -c:v libx264 -tune zerolatency -level 31 -pix_fmt yuv420p -f mpegts -preset superfast file.ts
```

**Comment by SubJunk** [comment]
I have a fix for it now, it should be in the next release

**Comment by Djdfy14** [comment]
@SubJunk When is the release with the fix planned?

**Comment by SubJunk** [comment]
I'm not sure, but I can build it for you later today, I'll attach it here

**Comment by SubJunk** [comment]
@Djdfy14 please let me know when you have downloaded it so I can remove it
https://www.universalmediaserver.com/uploads/UMS-Djdfy14.exe

**Comment by Djdfy14** [comment]
@SubJunk thank you very much, everything works. The file can be deleted.

**Comment by ExSport** [comment]
@SubJunk Are you sure there is not a better fix? "**tune zerolatency**" and "**preset superfast**" makes UMS much more responsive for start of playing and FF/RW actions or UMS response on Wifi networks. Without it I am afraid some renderers will lose the benefit of UMS app, to rewind with transcoded files with some renderers like Panasonic, etc....
Maybe it is an issue of current FFMPEG build only? If yes, it is a shame to lose better responsivity by this change. Or am I missing something? :-) Thx

**Comment by SubJunk** [comment]
@ExSport I tried a lot of options to narrow down the bug and only this combination worked. My theory is that there is something common to `ultrafast` and `zerolatency` that Panasonic TVs don't like.

Normally I would have made a renderer override for it just for Panasonic TVs but then I realised that `superfast` is probably a good setting for most people, though I'm interested in disagreement as always.

More research could be done to discover exactly which setting is causing the problem. The `tune zerolatency` command is just a wrapper for these x264 flags according to [here](https://superuser.com/a/564404):
```
                                --bframes 0 --force-cfr --no-mbtree
                                --sync-lookahead 0 --sliced-threads
                                --rc-lookahead 0
```
so with more testing we could discover which one of those flags is the problem, and then just disable that one while keeping the others.

What is the real world benefit to using `zerolatency`? We should make sure we have a really good reason for disabling those bandwidth optimizations. There is some latency improvement but what is it? If it is 50ms is that worth it?
We could use the UMS logs to do benchmarking with and without the command. When I look online I just see vague comments about it but no real numbers.

Are you able to do that comparison?

**Comment by SubJunk** [comment]
I also found https://www.reddit.com/r/ffmpeg/comments/bhs6vf/comment/elve4xg/?utm_source=reddit&utm_medium=web2x&context=3 which says:

> - ultrafast:
  --no-8x8dct --aq-mode 0 --b-adapt 0
  --bframes 0 --no-cabac --no-deblock
  --no-mbtree --me dia --no-mixed-refs
  --partitions none --rc-lookahead 0 --ref 1
  --scenecut 0 --subme 0 --trellis 0
  --no-weightb --weightp 0
> - superfast:
  --no-mbtree --me dia --no-mixed-refs
  --partitions i8x8,i4x4 --rc-lookahead 0
  --ref 1 --subme 1 --trellis 0 --weightp 1

So the intersection between `ultrafast` and `zerolatency` is `--bframes 0`. That means we can try doing `--tune zerolatency --bframes 3` and if it works we can put back zerolatency, and do bframes=3 for Panasonics
