### ISSUE TITLE
Package UMS for debian/ubuntu.

### ISSUE THREAD

**Issue by popman** [UniversalMediaServer/UniversalMediaServer#333]

**Comment by Sami32** [comment]
@popman https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions
Hoping that help.
Any suggestions are welcome ;-)

**Comment by Nadahar** [comment]
I'd like to add that I'm sure anyone wanting to package it would be very welcome. There's noone in the core team with the intricate knowledge of exactly how to set up and maintain a package for a certain distro AFAIK, but I'm sure anyone from the "outside" would get any help needed to figure out how to best configure it when packaging.

**Comment by Sami32** [comment]
@Nadahar Thanks for the link :-)
Wiki updated.
