### ISSUE TITLE
Web settings: Shared directories

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#3351]
On "shared web directories"

Can't add shared web directory if none is set (no new line).

Fail to add stream as it will never have name (always try to use the feed funct).

Maybe we should add a button + modal to create a new one, instead of table row. (shared dir as well).

Save button will always try to send "shared web settings", even if not changed.

**Comment by SubJunk** [comment]
Nice issue. Modal would be ok if you want, I have mixed opinions about them
