### ISSUE TITLE
Subtitles in MPEG-TS Streams

### ISSUE THREAD

**Issue by atkinsd** [UniversalMediaServer/UniversalMediaServer#336]
Digital TV Contains subtitles within the stream it self, I would expect most players will ignore this. Unless 
e.g.
TRACE 2014-07-10 01:09:14.386 [New I/O worker #8] Matched format MPG to "E:\TVcaptureE\24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts"
TRACE 2014-07-10 01:09:15.755 [New I/O worker #8] Parsing results for file "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts": container: mpegts, bitrate: 5343573, size: 3365569608, video codec: mpeg2, duration: 01:23:58.00, width: 720, height: 576, frame rate: 25.000, muxing mode: null, mime type: video/mpeg
    Audio track id: 650, lang: en, flavor: null, audio codec: mpa, sample frequency:48000, number of channels: 2, bits per sample: 16
    Subtitle track id: 576, type: UNKNOWN, flavor: null, lang: en, externalFileCharacterSet: null
TRACE 2014-07-10 01:09:15.757 [New I/O worker #8] Adding new child "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" with class "net.pms.dlna.RealFile"
TRACE 2014-07-10 01:09:15.758 [New I/O worker #8] Format "mpegts" failed to match supported line f:mpegps     v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm           m:video/mpeg
TRACE 2014-07-10 01:09:15.760 [New I/O worker #8] Matched support line f:mpegts     v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm|mpa|mp3|aac       m:video/mpeg
TRACE 2014-07-10 01:09:15.763 [New I/O worker #8] Overriding detected mime type "video/mpeg" for file "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" with renderer preferred mime type "video/mpeg"
TRACE 2014-07-10 01:09:15.764 [New I/O worker #8] File "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" can be streamed with mime type "video/mpeg"
TRACE 2014-07-10 01:09:15.764 [New I/O worker #8] Getting player for resource "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts"
TRACE 2014-07-10 01:09:15.764 [New I/O worker #8] Returning compatible player "MEncoder"
TRACE 2014-07-10 01:09:15.766 [New I/O worker #8] File "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" has subs that need transcoding
TRACE 2014-07-10 01:09:15.766 [New I/O worker #8] Format "mpegts" failed to match supported line f:mpegps     v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm           m:video/mpeg
TRACE 2014-07-10 01:09:15.767 [New I/O worker #8] Matched support line f:mpegts     v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm|mpa|mp3|aac       m:video/mpeg
TRACE 2014-07-10 01:09:15.768 [New I/O worker #8] Final verdict: "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" will be transcoded with player "MEncoder" with mime type "video/mpeg"
TRACE 2014-07-10 01:09:15.769 [New I/O worker #8] Adding "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts" to transcode folder for player: "MEncoder"
TRACE 2014-07-10 01:09:15.772 [New I/O worker #8] Adding new child "24- Live Another Day.2014-07-07 20-36.8-00 P.m. 9-00 P.m.ts [MEncoder]" with class "net.pms.dlna.FileTranscodeVirtualFolder"

from mplayer
VIDEO MPEG2(pid=512) AUDIO MPA(pid=650) SUB Teletext(pid=576)  PROGRAM N. 1589
ID_VIDEO_ID=512
ID_AUDIO_ID=650
ID_AID_650_LANG=eng
ID_SUBTITLE_ID=576

It seems it wants to transcode this all the time, even if subtitles is not requested.
i.e eng,off;_,eng;_,und

**Comment by Sami32** [comment]
> HTTP/1.1 Persistent Connections 
> Persistent connections is the default behavior defined by HTTP/1.1. It is strongly RECOMMENDED that this behavior be maintained, as it may be beneficial in many scenarios, as it allows for resources to be utilized more efficiently. Support for Pipelined request handling is also RECOMMENDED if persistent connections are supported. 
> If a server responds with a “**CONNECTION: close**” header line, it MUST close the session after responding. Similarly if a client specifies “CONNECTION: close” in the request, the server MUST also close the session after responding. 
> When Requests are pipelined to a server, the server MUST answer the requests in the order that they are received. Clients MUST also be prepared to retry connections if pipelining fails, for example, if the server does not support them.

**Comment by Nadahar** [comment]
@Sami32 How is the quote above related to the issue at hand?

**Comment by Sami32** [comment]
@Nadahar Oups, wrong place...too fast post after logging :-(
Thanks for caring ;-)

**Comment by SubJunk** [comment]
We will need full logs to look into it, feel free to reopen
