### ISSUE TITLE
20-30 minutes until it actually opens every single time I try to start it, & even during OS startup

### ISSUE THREAD

**Issue by SpaceOctopus** [UniversalMediaServer/UniversalMediaServer#341]
Whenever I try to open it, it takes a ridiculously long time to actually open the program & show me the window/tray icon. It never did this when I first started using it several months ago & I'm not sure when it started doing this, but it happens with admin running it & regular user, and I have plenty of resources for everything (4 processors & 16gb ram, a ridiculously good video card & everything else I could need, but never had problems with UMS before anyways). I even uninstalled with Revo & installed again. I also have issues where I can't get subtitles to work at all on my ps3, no matter what I do with settings or anything. I suppose I should likely submit that as another bug, unless this is a PS3 thing that won't work, because I don't wanna waste anybody's time.

**Comment by Sami32** [comment]
@SpaceOctopus @SubJunk Did the latest UMS version solved this issue ? If no logs are provided it can be closed.

**Comment by SubJunk** [comment]
@Sami32 I haven't worked on it directly but we have had quite a few OS X improvements since then so I hope it's better

@SpaceOctopus feel free to re-open
