### ISSUE TITLE
Several problems on 4.0.0

### ISSUE THREAD

**Issue by Arkadietz** [UniversalMediaServer/UniversalMediaServer#343]
TV Model: SONY 50W815W
Wired Connection 100 Mb/s

- When i check "keep DTS Tracks" the picture is going blurred.
- Some .mp4 files won't start.
- Some .mkv files won't start. (it gives me current bitrate 120/140 which is not possible)
- Some external subs won't loaded.

**Comment by Sami32** [comment]
@Arkadietz Did the latest renderer update solved this issue ?
http://www.universalmediaserver.com/forum/viewtopic.php?t=2066
Already solved.
