### ISSUE TITLE
Support mpv as mplayer alternative

### ISSUE THREAD

**Issue by codygarver** [UniversalMediaServer/UniversalMediaServer#344]
Playback failed for me until I installed mplayer2. mplayer2 is a dead projects, mpv is the successor.

**Comment by mcepl** [comment]
> Both mplayer and mplayer2 are dead projects, ...

That's a strong stuff! What do you smoke? https://mplayerhq.hu/design7/news.html presents new release of mplayer from October this year.

**Comment by codygarver** [comment]
Nice meme, 10/10

On Tue, Dec 22, 2015 at 7:55 AM, Matěj Cepl <notifications@github.com>
wrote:

> Both mplayer and mplayer2 are dead projects, ...
>
> That's a strong stuff! What do you smoke?
> https://mplayerhq.hu/design7/news.html presents new release of mplayer
> from October this year.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UniversalMediaServer/UniversalMediaServer/issues/344#issuecomment-166623412>
> .
>



-- 
Cody Garver

**Comment by Sami32** [comment]
@SubJunk Could i close it ? because AFAIK we would like get rid of MPlayer when FFmpeg will be able to do the job, not replace it, right ?
Feel free to reopen it if need.
