### ISSUE TITLE
LG BP540 Blu-Ray Player Issues

### ISSUE THREAD

**Issue by YourGraveyard** [UniversalMediaServer/UniversalMediaServer#345]
Hello,

I recently acquired an LG BP540 Blu-Ray player and strangely I've been having issues with playing HD/MKV format files on it. It plays MP4 files just fine on the network but anything in HD/MKV it either works on just 1 video then stops or just completely hangs on the player. Sometimes it shows up on the log that the video/file has been accessed but nothing happens, other times nothing happens at all and it doesn't show up on the logs. UMS also by defaults thinks its an LG LA6200. I've tried switching the default profiles multiple times but it ends up going to the LA6200. I've tested the Blu-ray player using Plex and it played just fine, however I dislike Plex & find it rather useless.. I've grown to using UMS and will forever want to use UMS so please help me out on this one.

I had uploaded the logs to MediaFire. Link: http://www.mediafire.com/download/6xa95ou13otfb4a/ums_dbg.zip

Thanks

**Comment by Sami32** [comment]
@YourGraveyard @valib Could this issue be closed ?
