### ISSUE TITLE
FFmpegVideo doesn't support attached fonts

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#346]
MKV files can have "attachments" which can be fonts that are then referenced by ASS/SSA subtitles. MEncoderVideo supports that (because we don't have to do anything tricky with MEncoder so it just does it automatically) but FFmpegVideo doesn't since we just extract the subtitles then reference the external .ass file.
Is it possible to also extract the embedded fonts and have FFmpeg use them? In the meantime maybe we should detect when embedded fonts are present and have FFmpeg defer to MEncoder in those cases, like we already do with tsMuxeR.

Any thoughts @valib ?

**Comment by Sami32** [comment]
@SubJunk @Valib Did this commits https://github.com/UniversalMediaServer/UniversalMediaServer/commit/c57a5fa4d90926287b6cdb7f1f1840acef34b6fb https://github.com/UniversalMediaServer/UniversalMediaServer/commit/0355f43020b82fc96485effeb49ee5ae657388b8 https://github.com/UniversalMediaServer/UniversalMediaServer/commit/9ee66a33e1a43c21d1ea34859c49ff8adfddafe4 and https://github.com/UniversalMediaServer/UniversalMediaServer/commit/39fee865129c059ca2acc5f6f5762771b6e477d6 fixed it ?

**Comment by valib** [comment]
@SubJunk no it was fixed by FFmpeg when they updated the font config internally and UMS updated to reflect it.
