### ISSUE TITLE
(FEATURE) get back the plugins or turn off PC from ums dlna

### ISSUE THREAD

**Issue by animekai** [UniversalMediaServer/UniversalMediaServer#3475]
I want a feature to turn off PC server from the ums device, like my PS4, it was possible with my ps3 when plugins were available, but now plugins don't exists, but some feature to turn off PC from my ps4 would be appreciated 👍

**Comment by SubJunk** [comment]
Thanks for the issue @animekai I will work on this

**Comment by SubJunk** [comment]
@animekai which operating system? I'll make a build for you to test

**Comment by animekai** [comment]
> 

I use windows 10, and I use my ps4 fat to watch movies thought ums

**Comment by SubJunk** [comment]
@animekai please let me know when you have downloaded https://www.universalmediaserver.com/uploads/UMS-remote-shutdown.exe
