### ISSUE TITLE
UMS CANNOT PLAY HRA FILES PROPERLY

### ISSUE THREAD

**Issue by machead52** [UniversalMediaServer/UniversalMediaServer#348]
Hi all, 

I'm a new (MAC) user to UMS and am streaming via Ethernet to my OPPO BDP-105D. My iTunes Library resides on an external HD attached via Thunderbolt. The files play just fine with the EXCEPTION of the HRA files such as 96/24. What I hear is a very speeded up version of each track. In other words, it is essentially worthless and unlistenable. Does someone know of a way to address and resolve so I can enjoy these HRA files on my Home Theater?

Thanks!

**Comment by Sami32** [comment]
@machead52 Did the latest UMS version solved this issue ?

If not, could you provide a MediaInfo export log of your HRA files, or post your log following these instructions after trying to play your "HRA" files:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
Hi @machead52 it's been some time since you reported this issue and there has been a suggested update, or the latest version of UMS, which we presume has resolved your issue so we are closing.  If this is still an issue, please feel free to reopen with full TRACE logs so that we can investigate.
