### ISSUE TITLE
Remove old engines

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#3501]
UMS use the `JUPnP (Netty)` engine as default since v11.0.0.
It's maybe time to remove old upnp engines :
`Sockets` that is not up to date.
`Netty` and `Java` that use the `SocketSSDPServer` (datagram) instead of `JUPnP` one.

I may add `ContentDirectory` service implementation to `JUPnP`, and put this engine in alpha for now to test it.

@SubJunk what do you think about this ?

**Comment by SubJunk** [comment]
@SurfaceS yes that sounds good to me
