### ISSUE TITLE
Uniformizing settings files format

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#3508]
UMS use a lot different file format to store settings.

`/UMS.conf` use java properties file format.
`/renderers/*.conf` files use java properties file format.

`/ffmpeg.webfilters` use custom file format
`/UMS.cred` use custom file format
`/data/UMS.tmpmgr` use custom file format
`/data/dynpls/*.ups` use custom file format
`/data/resume/*.resume` use custom file format

We may look if it is possible to avoid custom's file format.

~~`/VirtualFolders.conf` use JSON format~~
~~`/WEB.conf` use custom file format~~

- [x] `WEB.conf`, `VirtualFolders.conf` and `folders`'s setting part from `UMS.conf` should be stored on the same file, like `shared.conf`. #3561
- [ ] `/UMS.conf` and `/renderers/*.conf` files could be updated from `commons-configuration` to `commons-configuration2`

**Comment by SubJunk** [comment]
Good idea

**Comment by SubJunk** [comment]
This has been done
