### ISSUE TITLE
Can't browse server using Windows

### ISSUE THREAD

**Issue by divanikus** [UniversalMediaServer/UniversalMediaServer#351]
Universal Media Server is visible as a separate host on windows network (using windows explorer), but if you enter it, you'll see "root" folder, which contains "root" folder, which contains "root" folder... endless loop of "root" folders.

**Comment by Sami32** [comment]
@divanikus Did the latest UMS version solved this issue ?
If not, please, post your log following these instructions: http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
