### ISSUE TITLE
Web settings: Shared Content tab moved to its own page

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3522]
Users will sometimes need to change settings but I think the Shared Content tab would be the most frequently used, so I think we should make that selected and expanded by default. I'm interested in opinions from @UniversalMediaServer/developers about it too

**Comment by SurfaceS** [comment]
In my opinion, Shared Content tab should be moved to it's own Shared Content on the menu.
It is on the same goal than #3508

**Comment by SubJunk** [comment]
Yeah that's good too

**Comment by SurfaceS** [comment]
fixed in https://github.com/SurfaceS/UniversalMediaServer/commit/35551e8cf372f35b832329fc795f0237839a4ff7
