### ISSUE TITLE
Web settings: Fix shared content not updating on web

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3523]
Reproduction steps:
1) Add a new shared folder in the new web settings area and click Save
2) Go to the Player area, observe the new folder isn't there, even if you refresh the page

I can see the update if I go to port 9002, but not 9001

**Comment by SubJunk** [comment]
@SurfaceS I think this should be fixed before we merge the branch for v12, because it will affect every new user who uses the web player, which is a lot of people

**Comment by SurfaceS** [comment]
@SubJunk : Have a try on this one https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3561.
It is a confs cleanup that I was working on, and that should handle shared changes differently.

**Comment by ik666** [comment]
@SurfaceS I've merged the new branch. I do not see my configured shared resources in the root folder any more. I'm using a headless environment. The files are available over the media library though.

**Comment by SurfaceS** [comment]
@ik666 
can you post your SHARED.conf and what is missing on your root ?

**Comment by SubJunk** [comment]
My problem is fixed, but I'll leave it for this new one and delay the release until it's resolved

**Comment by ik666** [comment]
@SurfaceS Maybe I've missed something, but I don't see a SHARED.conf ... where should it be and what is the content? If this is a new config element, maybe the folder settings (UMS.conf) from 11.x can be merged?

And I am missing the "My Album" folder displayed in the RootFolder.

**Comment by ik666** [comment]
@SubJunk @SurfaceS I think my issue is fixed now. I had a NPE during scan (see #3604). Maybe this is why nothing showed up. Also the SARED.conf is now being created and merged as expected ... Thx all.
