### ISSUE TITLE
Web player: Update location bar while navigating

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3524]
Currently in the new web player, the location bar in the browser does not change while navigating.
This means a user can't refresh the page, or copy/paste the location to somewhere else - it will just load the front page.

**Comment by SurfaceS** [comment]
This one will need a lot of change as browse / play is handled by SSEProvider.
Also, changing page will cut/load SSE each time.

**Comment by SubJunk** [comment]
@SurfaceS we don't have to do a page load each time, just store a reference to the page. Often websites do it with hash, so like `localhost:9001/#id=123`
