### ISSUE TITLE
Web player: Download button not working

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3533]
The download button on the play video page doesn't work, just goes to an empty React page

**Comment by SurfaceS** [comment]
On my side, it works (Firefox, Chrome and phone Samsung browser).

The link open a new tabs, so it should not have something to do with React.

Do you have any errors ?

**Comment by SubJunk** [comment]
I tested more and it works for me if I use the compiled version (port 9001) but not the live development version using `yarn start` and port 3000

**Comment by SubJunk** [comment]
The new window opens but it's just an empty React shell with no content, instead of a file. I can look into it more later
