### ISSUE TITLE
Broken thumbnails in Web folder

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3541]
On first load, the thumbnails are broken:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/584228/197878568-ab32ed27-7368-49eb-9b40-ef72df43c867.png">

But they work the second time:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/584228/197878715-36d7765f-e34f-47c0-9a9c-48e88dc397f6.png">

It seems to happen on the old web player too, so I'm not sure when the bug was introduced. In the old one I see some work first time and others don't, which makes me think there is a race condition where the page isn't waiting for them to resolve before loading, but some can resolve fast enough to make it.

**Comment by SurfaceS** [comment]
Maybe try to see if #3507 fix this as this was a lot of non sense code fixed their.

**Comment by SubJunk** [comment]
@SurfaceS yes that fixes the bug, good timing!
