### ISSUE TITLE
[HorribleSubs] Tokyo ESP - * [720p].mkv

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#359]
hello UMS dev team
when i was on UMS-3.6.4 i was able to watch the anime
when i updated to 4.0.2-java8 or higher i cant al off a sudden not watch it anymore
its saying the datatype is not supported or somthing

i watched ep 1 with 3.6.4 and i cannot watch anything anymore with 4.0.2+

what can i do to fix it

**Comment by Sami32** [comment]
@SubJunk If it's only an TsMuxeR issue on a weird video, what need to bo done with this issue ?
