### ISSUE TITLE
PEAQ PDR300 mp3-Radio

### ISSUE THREAD

**Issue by herbert2** [UniversalMediaServer/UniversalMediaServer#360]
I have a Windows7-PC and a Internet-Radio.
On the PEAQ PDR300 I can browse Music-Folders, but not the mp3-Files.
Maybe the file extension ".mp3" is missing for the transcoded files.
Of Course "Hide File-Extensions" is not enabled.

**Comment by Sami32** [comment]
@herbert2 @Enrice If the latest UMS version didn't solved your issue, could you, please, post your log following these instructions http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
Hi @herbert2 it's been some time since you reported this and a suggestion to upgrade was made.  We presume this has now been resolved but feel free to reopen with full TRACE logs as outlined above if not, so that we can investigate.
