### ISSUE TITLE
file is null test failure

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3607]
The last 2 test runs in main are failing https://github.com/UniversalMediaServer/UniversalMediaServer/actions/runs/3459327505/jobs/5774610765#step:5:412

**Comment by SurfaceS** [comment]
Rerunning the check pass.

I think the problem is on SearchRequestHandler :
```
								default -> filesList.add(new RealFileDbId(new DbIdTypeAndIdent(type, resultSet.getString("FID")),
										new File(resultSet.getString("FILENAME"))));
```
where resultSet.getString("FILENAME") is rubbish.

**Comment by ik666** [comment]
@SubJunk I agree. Because "FILENAME" is not in the filesystem you get a "NULL" filename. Howeer, I think the code should be mature enough to get along with it. The #3608 PR at least fixes this. Or would you rather like to adjust the test ?

**Comment by ik666** [comment]
@SurfaceS I also added the fix for your commented line to the PR  ...

**Comment by SubJunk** [comment]
I merged the fix
