### ISSUE TITLE
UMS crashes when monitor turned off

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3613]
[This](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15423) is a strange one that has me stumped. When the monitor is turned off UMS (or java) crashes but I don't see how that can happen. It does not happen when the monitor goes to sleep. 

I'm not sure if the problem is with their computer or some weird interaction with the graphics card. It also happens with an older version of UMS from 2020 so I'm leaning toward it being a computer problem, but I don't know.

Any Ideas?

**Comment by Mik-S-UMS** [comment]
Update: 
It appears to have fixed itself after running as administrator and turning off UAC. 
I have suggested turning UAC back to default to see if the problem has gone and looks like it has.

Something must have needed admin rights on their system, and that was causing UMS to crash for some reason. I don't know if this is an isolated problem unique to them or hints to a bug/config problem somewhere. 

Any thoughts before I close this?

**Comment by SubJunk** [comment]
@Mik-S-UMS I'm glad it's resolved, thanks for the update. It's a weird one and maybe we will never know what happened. If it happens again to another user we might learn more
