### ISSUE TITLE
Multiple Streaming Issues with Xbox 360 (Not playing)

### ISSUE THREAD

**Issue by TV-Tastic** [UniversalMediaServer/UniversalMediaServer#364]
I had been using UMC 3.6.2 until last night without a problem.  I have three Xbox 360s in the house and now none of them are able to stream from UMS even after I updated to 4.0.03 (clean install).  I'll try to provide as much information as possible.

1.)  Issue is occurring on Xbox 360 Slims from 2011, 2012 and 2013 (4GB, 250GB, 250GB, respectively). I don't use the 4GB, my kids do, but I'd thought I'd mention it since the results have been the same.

2.) I also have two PlayStation 3's and the issue is NOT occurring on either one of those consoles.  UMS is running flawlessly.

3)  Wireless network.  Netgear Nighthawk AC 1900 R7000.  Edimax Wireless AC1200 Dual Band USB 3.0 Adapter (EW-7822UAC). Consistenet connection speed pf 390 Mbps - 585 Mbps. Server PC running UMS: 64-bit WIndows Vista Home Premium, 4GB RAM, Intel Core 2 Quad CPU Q6000 @ 2.40 Ghz .

Timeline:

1.) 360 doesn't see UMS at all.  UMS shows Samsung AllShare (odd, because no Samsung devices were powered on) and "Unknown Renderer."

2.)  Reboot computer and restart UMS.  360 sees UMS, "There are no videos" message appears.

3.) Shutdown/resart UMS on PC, restart 360, 360 sees UMS and all folders, attempts to play video, freezes after 5 minutes.  400 Mb buffer full at 388 Mb on UMS GUI.  

4.) Shutdown/resart UMS on PC, restart 360, 360 sees UMS, when selected after a long attempt, a message about being unable to connect to the computer appears mentioning a possible firewall issue. There are no firewall issues.

5.) Realized that there was an update available so I updated to the latest version (clean install, 1536 heap size).  The exact same issues have occurred in no particular order repeatedly on all 360s in the house.

**Comment by Sami32** [comment]
@TV-Tastic Did the latest UMS version solved this issue ?
If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by polygirl** [comment]
@TV-Tastic it's been some time since you opened this issue but we didn't receive further info from you about versions, or confirmation that a specific new version now works so we presume this is now resolved for you.  If it's not please feel free to reopen with full TRACE logs.
