### ISSUE TITLE
audio file thumbnails should not have an overlay

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#3646]
I've an issue with v12: thumbnails of audio and image items get an overlay:

This is a thumbnail for an `object.item.audioItem`:

<img width="192" alt="Bildschirm­foto 2022-11-23 um 10 58 02" src="https://user-images.githubusercontent.com/8244468/203518836-c2701a5e-cc33-489b-8783-8e5a5adf45bc.png">

This is a thumbnail for an `object.item.imageItem`:

<img width="268" alt="Bildschirm­foto 2022-11-23 um 11 03 32" src="https://user-images.githubusercontent.com/8244468/203519693-5ef0203f-b15a-4c3f-84ab-0a617ecfebfc.png">

I think this is not intentional ...

**Comment by SubJunk** [comment]
Depends if they have been played/viewed?

**Comment by ik666** [comment]
@SubJunk Nope, I deleted the database before testing this ... Images can't be played anyways ... And for audio items it makes no real sense either, does it?

**Comment by ik666** [comment]
@SubJunk @SurfaceS  With the current `main` branch, this issue doesn't come up any more. I'll close it.
