### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3672]
The forum is not working, I get this error when trying to access it.

```
General Error
SQL ERROR [ mysqli ]

Resource temporarily unavailable [2002]

An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
```

**Comment by SubJunk** [comment]
Thanks for letting me know, I made a change and it seems to be working now, can you let me know if it's unstable again?

**Comment by SubJunk** [comment]
@Mik-S-UMS by the way you might notice some brief downtimes while I make some server upgrades to try to prevent this happening again
