### ISSUE TITLE
Regex in VLC conf not matching some versions

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3676]
Got a user [here](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15468&p=46487#p46487) where UMS was not identifying their version of VLC
It would not match `1.14.13` in the header as it was looking it to be in `x.x.xx` format not `x.xx.xx`

I have modified the VLC conf for them changing the `UserAgentSearch` to `Portable SDK for UPnP devices\/1\.\d{1,2}.\d{1,2}`

Could you make this change in the VLC-for-desktop.conf?

**Comment by SubJunk** [comment]
Done in #3679
