### ISSUE TITLE
Files being marked as fully played as soon as they are detected

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3683]
In main now (e013586333d93ac7e2e4dade06d3dfa89d5cee11) videos are being marked as Fully Played when they are parsed, so in the log viewer I see:

```
12:58:34 INFO  New file video.mkv was detected and added to the Media Library
12:58:34 INFO  video.mkv marked as fully played
```

**Comment by SubJunk** [comment]
The logs show it is the `StopPlaying Event` that is doing it, when the video hasn't been played, so that's a clue

```
INFO  2022-12-10 12:58:34.124 [StopPlaying Event] New file video.mkv was detected and added to the Media Library
TRACE 2022-12-10 12:58:34.170 [StopPlaying Event] Searching for file in FILES_STATUS with "HikariProxyPreparedStatement@1743389994 wrapping prep671637: SELECT * FROM FILES_STATUS WHERE FILES_STATUS.FILENAME = ? LIMIT 1 {1: 'video.mkv'}" before setFullyPlayed
TRACE 2022-12-10 12:58:34.170 [StopPlaying Event] File entry "video.mkv" not found in FILES_STATUS, inserting new row with ISFULLYPLAYED set to true
TRACE 2022-12-10 12:58:34.171 [StopPlaying Event] Searching for file in FILES_STATUS with "HikariProxyPreparedStatement@2140188327 wrapping prep671639: SELECT * FROM FILES_STATUS WHERE FILES_STATUS.FILENAME = ? LIMIT 1 {1: 'video.mkv'}" before setLastPlayed
INFO  2022-12-10 12:58:34.171 [StopPlaying Event] video.mkv marked as fully played
```

**Comment by SubJunk** [comment]
I think it's likely related to https://github.com/UniversalMediaServer/UniversalMediaServer/commit/0b3eed1c3ff0cbbab1f6c86947eb0f07919ca573 can you have a look @SurfaceS ?
It seems strange that the StopPlaying Event should be doing the parsing

**Comment by SubJunk** [comment]
Possibly related to this old issue too https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1479

**Comment by SurfaceS** [comment]
```
StartStopListenerDelegate.stop()
DLNAResource.stopPlaying()
-> Thread "StopPlaying Event"
DLNAResource.internalStop()
RootFolder.stopPlaying()
MediaMonitor.stopped();
MediaMonitor.setFullyPlayed();
```

If you where in trace mode, you should have something like `Fully Played feature logging:` on log.

Also, maybe check presence of `UMS.mon` file in data folder.

**Comment by SubJunk** [comment]
I restarted UMS and now it's not happening anymore - it is logging as a `[File event]` instead of `[StopPlaying Event]`. So it seems like it was in a bad state somehow.

**Comment by Mik-S-UMS** [comment]
@SubJunk I saw that you said you now have a LG TV on the forum. I tried to get my parents new LG TV to play transcoded video a while ago but could not get it working well, probably due to slow laptop and a short time to try it, but one thing I noticed was there was a lot of transcoding happening when nothing was being played. just on the video selection screen with all the thumbnails. The TV was creating its own thumbnails from the whole video and animating them when the pointer hovers over it. maybe this is falsely triggering the fully played status.

**Comment by SubJunk** [comment]
@Mik-S-UMS yes I think it's related too. Whenever you hover over a thumbnail it attempts to animate it using video stills, and while seeking during playback it's the same to provide previews on the seek bar. It's a very nice user experience (honestly it makes it seem like UMS is a completely new product compared to using it on my Panasonic) but we will need to fix it.
Another thing is the browsing is slow, possibly related to that and some pre-fetching. I have done a lot of testing and made some improvements, and will continue to improve things on it.

**Comment by SubJunk** [comment]
I think this is fixed now. Can be reopened if not
