### ISSUE TITLE
Dolby Vision showing up purple and green via DLNA on LG webOS

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3686]
It might not be possible to display Dolby Vision properly via DLNA, since I have tested Plex and Serviio and they have the same problem. If it's not possible then we should at least transcode it so the colours are accurate, ideally still HDR but even SDR would be more watchable.

**Comment by ExSport** [comment]
The question is if there is any Dolby Vision file supported or all are scrambled.
`Some Dolby Vision video is played properly. `
https://www.lgwebos.com/topic/4258-oled55c6v-videoplayer-displays-green-shaded-picture-for-some-dolby-vision-videofiles/
Maybe it is only false info but if there is any Dolby Vision file playable on the TV, maybe there exists some specific settings which will create "compatible" Dolby Vision files for TV internal players (USB/DLNA) but I am sceptical here....
OK, here some more testing files...seems promising some support is there when correct profile is used and all required HDR10 metadata is included?
`So LG B7 webOS can play Dolby Vision L5 in MP4 container, fails with L5.2.`
https://www.reddit.com/r/PleX/comments/r1t3hy/comment/hm24082/
Original thread: https://www.reddit.com/r/PleX/comments/r1t3hy/green_purple_tint_with_dv_dolby_vision/
Some info about correct decoding of DV files (MPV/FFMPEG/GPU): https://github.com/mpv-player/mpv/issues/7326
Some Dolby Vision/Atmos sample files with different profiles for testing: https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/

**Comment by SubJunk** [comment]
Cool, thanks for the links, I will go through them.

Also I have discovered that some Dolby Vision files have HDR10 compatibility, and they play via UMS, but the only play in HDR mode instead of Dolby Vision mode, meaning the contrast metadata is fixed instead of dynamic. It's not as good as full DV but at least the colors look correct.
However most of my DV files were not made with that compatibility mode, I only have one with it.

**Comment by SubJunk** [comment]
I also got a reply from a LG developer about this on their forum so I have some things to try https://forum.webostv.developer.lge.com/t/dolby-vision-video-playback-via-media-player-app/1358

**Comment by SubJunk** [comment]
Based on that response I have a small step forward - if I mux our DV sample files as MPEG-TS using tsMuxeRGUI, and play them via UMS, the TV plays them as DV perfectly. So now the trick will be to do it on-the-fly.

**Comment by SubJunk** [comment]
There are a lot of fixes related to this now in `main` but it is still not working reliably with the FFmpeg-to-tsMuxeR muxing. For now we have Dolby Vision working inside MPEG-TS and MP4 files on LG TVs, but they do not support it inside MKV files, so that is the one that needs work.

I suspect that the remaining bug is more related to muxing H.265 than HDR, I can see the same problems with SDR content, but I will leave this issue open until it's working for MKVs too

**Comment by SubJunk** [comment]
This is working and released
