### ISSUE TITLE
Dialog Display Failure

### ISSUE THREAD

**Issue by OldMan100** [UniversalMediaServer/UniversalMediaServer#3688]
Just install version 12, if you look at the two pics attached, there are problems in displaying any listings within the dialog windows.
I couldn't direct the app where to scan for files, local or network, nothing would list. The only locations the app would go to are the default locations already in the app. If you look at the first pic, bottom part of the buttons are missing. On the second pic, the area is blank.
I clicked on Network, the names of of two NAS should displayed.
[ums_dbg_2022-12-12-21-40.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10214873/ums_dbg_2022-12-12-21-40.zip)
![Screenshot_20221212_090219](https://user-images.githubusercontent.com/35414666/207237137-c9641f21-a719-4c0e-93c6-0fa726220d98.png)
![Screenshot_20221212_093254](https://user-images.githubusercontent.com/35414666/207237140-21f9ab7f-bbda-4d64-97d7-61ad51c32727.png)

**Comment by OldMan100** [comment]
Problem solved. A third-party app, Stardock's Windowblinds is the problem. This app re-skins apps and for all my other apps, does a great job, but UMS, the app seems to screwup the dialog windows in the program. Once I instructed Windowblinds to exclude UMS from re-skinning, everthing was good.

**Comment by SubJunk** [comment]
@OldMan100 thanks for the update
