### ISSUE TITLE
Unknown video feeds & podcasts listed as shared content, cannot be removed

### ISSUE THREAD

**Issue by aemondis** [UniversalMediaServer/UniversalMediaServer#3697]
Upon first load of the GUI and creation of an admin user, the shared folders list numerous podcasts, video feeds, etc. that cannot be removed. These are not channels I created, or have even accessed before. When I try to remove them via the GUI, then click save, they reappear again. Refer to screenshots and attached trace:
![image](https://user-images.githubusercontent.com/22867555/207986662-3e92a50d-d092-48f4-b2e2-689f78732f30.png)
![image](https://user-images.githubusercontent.com/22867555/207986791-1c4f29e2-bfb6-42dc-8913-86503b2ba457.png)

[ums_dbg_2022-12-16-10-18.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10241376/ums_dbg_2022-12-16-10-18.zip)

**Comment by aemondis** [comment]
I can also confirm that this version does not resolve the issue: https://www.universalmediaserver.com/uploads/UMS-boblatimer.exe

It seems however that I can mark any of those feeds as "disabled" with no issue, and this saves successfully. When I click "Remove" via the GUI the item disappears from the web page, but once I click save it says "successful", only for the items to reappear immediately at the bottom of the list of shared content.

**Comment by SubJunk** [comment]
Thanks for reporting this. That's the correct set of default sample channels but yeah that's a bug that they can't be removed. I'll have a look

**Comment by aemondis** [comment]
Glad to hear I'm not going crazy!

I do have something new to add to this. After closing the UI in the browser (without closing the browser), then re-loading the UI and logging in, the shared folder changes now appear to have taken effect, and all the defaults have gone...

The joys of working with physical files! FWIW - this is Win11 on an insider build, so always possible there's some weird interaction going on behind the scenes with the way files are accessed on disk.

**Comment by SurfaceS** [comment]
this should be fixed in #3699 and #3703

**Comment by SubJunk** [comment]
I’m away from my build computer but will upload a fixed version for you in the next few days

**Comment by SubJunk** [comment]
@aemondis this should be fixed in this version https://www.universalmediaserver.com/uploads/UMS-OldMan100.exe
Please let us know if it works
