### ISSUE TITLE
Shared Contents Location Not Saved

### ISSUE THREAD

**Issue by OldMan100** [UniversalMediaServer/UniversalMediaServer#3698]
No matter how any times I've tried, version 12.0.1 will not save the addresses I've placed in shared contents location, whether I use a Windows Letter or Network address to specific the location of my files. After the program is shutdown and re-started, only the three user location are still there. This is the same through the web interface. Through both the program and interface, everything looks and appears to be saved, once the program is shutdown and restarted, all the locations a user enters are gone. Once I re--installed 11.6, everything was good again.

[ums_dbg_2022-12-15-22-44.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10243377/ums_dbg_2022-12-15-22-44.zip)

**Comment by SubJunk** [comment]
Can you please try this version and let me know if that works? It works for me https://www.universalmediaserver.com/uploads/UMS-boblatimer.exe

**Comment by OldMan100** [comment]
After installing 13, whatever is causing 12.0.1 from saving any shared locations add by the user, is present in version 13. Right now, version 11.6.1 is the last good version.

**Comment by SurfaceS** [comment]
@SubJunk v13 does not have the fix PR

**Comment by SubJunk** [comment]
I’m away from my build computer but will upload a fixed version for you in the next few days

**Comment by SubJunk** [comment]
@OldMan100 this should be fixed in this version https://www.universalmediaserver.com/uploads/UMS-OldMan100.exe
Please let us know if it works

**Comment by infectormp** [comment]
@SubJunk I installed (clean install) version you provided and it doesn't save newly added Shared Content entry. UMS saves only entry added through wizard at first run.

**Comment by SubJunk** [comment]
@infectormp is that when adding it via the old settings or the browser? Can you make a new issue for it?
