### ISSUE TITLE
UMS fails to start when port 9002 is in use

### ISSUE THREAD

**Issue by idontusenumbers** [UniversalMediaServer/UniversalMediaServer#3706]
When port `9002` is in use before starting UMS, starting UMS largely fails.

The log shows:

```
20:43:36 INFO  GUI is available at: http://localhost:9001
20:43:36 ERROR Failed to start web player server : Address already in use
20:43:36 ERROR A serious error occurred during Universal Media Server initialization: Cannot invoke "com.sun.net.httpserver.HttpServer.getAddress()" because "this.server" is null
```

Changing settings appears to have no effect. If the port is 

Closing UMS, Shutting down the process using port 9002, then restarting UMS seems to do the trick.

I see no way to disable the web interface that starts up on port 9002, and I don't really have any need for it. Seems like the inability to start the web interface socket shouldn't block the rest of the app from functioning. Some more feedback on what's going wrong (logging the port number in the log, presenting to the user that the port is in use, etc) might help too.

Same issue in version 12.0.1 and 13.0.0

**Comment by SurfaceS** [comment]
> I see no way to disable the web interface that starts up on port 9002
On the HTTP GUI (http://localhost:9001/settings by default)
Be sure to tick `Show advanced settings`.
settings -> general settings -> services -> Web player
You can change port or disable it.

**Comment by idontusenumbers** [comment]
Wow, nice response time on a fix! Thanks!
