### ISSUE TITLE
GUI update error logs

### ISSUE THREAD

**Issue by fifisave** [UniversalMediaServer/UniversalMediaServer#3707]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
[ums_dbg_2022-12-17-09-45.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10251334/ums_dbg_2022-12-17-09-45.zip)

  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

**Comment by fifisave** [comment]
Hello when changing setup parameter to not open web GUI when windows starts raise an error message

**Comment by SubJunk** [comment]
I think this is fixed in the next version, I’ll upload a fixed build for you in the next few days

**Comment by SubJunk** [comment]
Please let me know when you have downloaded this https://www.universalmediaserver.com/uploads/UMS-fifisave.exe

**Comment by fifisave** [comment]
Done ! 
Regards 

----- Mail original -----

De: "SubJunk" ***@***.***> 
À: "UniversalMediaServer/UniversalMediaServer" ***@***.***> 
Cc: "fifisave" ***@***.***>, "Author" ***@***.***> 
Envoyé: Samedi 24 Décembre 2022 00:18:54 
Objet: Re: [UniversalMediaServer/UniversalMediaServer] GUI update error logs (Issue #3707) 



Please let me know when you have downloaded this https://www.universalmediaserver.com/uploads/UMS-fifisave.exe
