### ISSUE TITLE
UMS

### ISSUE THREAD

**Issue by Euvir** [UniversalMediaServer/UniversalMediaServer#3719]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

**Comment by SubJunk** [comment]
@Euvir I don't see any details here so I'm closing it, feel free to reopen or make a new one
