### ISSUE TITLE
A/V desynchro and no subs with PS3 / PS4

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#372]
Hello I'm trying to watch chibi vampire Karin from exiled destiny http://www.nyaa.se/?page=view&tid=61720

And I don't have subs at all on the ps3

**Comment by Sami32** [comment]
@Goten87 Did the latest UMS version solved this issue ?
If not, please, post your log following these instructions: 
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556
@valib Your verdict as a PS3 owner ?

**Comment by Goten87** [comment]
@Sami32 i will check it later on oke not @ my ps3 now

**Comment by Goten87** [comment]
Tested it still no subs and now i also have audio video desync on that anime i Will test again tomorow with tracer logger on to send it to u peeps

**Comment by Sami32** [comment]
@Goten87 Sorry to hear that but without your log we cannot help...
So, please, follow these steps http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by Goten87** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/405198/ums_dbg.zip)
This is the files that i made while getting the bug once i knew it was there
no subs/ audio/video desync i stopt it the again

**Comment by valib** [comment]
@Goten87 you set a different path to the UMS.cred. And it seems to me that `DEBUG 2016-08-06 23:39:51.225 [main] Error initializing plugin credentials: {}
java.io.FileNotFoundException: E:\Universal Media Server Profiel\Anime\UMS.cred (Het systeem kan het opgegeven pad niet vinden)` means that the file is not accessible. Please delete the `cred.path = E:\\Universal Media Server Profiel\\Anime\\UMS.cred` in the UMS.conf and let the UMS to make the UMS.cred without changing the path.

**Comment by Goten87** [comment]
Ok Will try that when i wake up again ^^

**Comment by Goten87** [comment]
oke i have deleted the path from my UMS.conf and i deleted the file it self as well
still not working

**Comment by Sami32** [comment]
@Goten87 Could you send your new log please ?

**Comment by Goten87** [comment]
i will watch anime now so i can do that just let me setup again to go to trace mode

**Comment by Goten87** [comment]
Logs:
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/405744/ums_dbg.zip)

i will also this time upload the profile i use
Profile:
[Anime.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/405745/Anime.zip)

hope this is helpfull

again no subs and desync of audio/video

**Comment by Sami32** [comment]
@Goten87 In the purpose to help me narrow your issue i'll ask you some questions:

1) Can you see subtitles from your USB from your PS3 ?
2) Can you see videos with **external subtitle only** on you PS3 ?
3) Did everything play fine on your Samsung E+ ?

**N.B.** It will not solve your issue but you could modify your _Transcoding Settings_ as following:
_Audio language priority_                      nl,en,ja,und
_Subtitles language priotity_                  nl,en,ja,und
_Audio/subtitles languages priority_       nl,off;ja,eng;*,nl;*,und

**Comment by Sami32** [comment]
@Goten87 Can this issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/233 be closed ?

**Comment by Goten87** [comment]
@Sami32 yeah that old one can close i think sins its the same one as this one 
and i will come back at u when i done all the things u sayed in the other post

**Comment by Sami32** [comment]
@Goten87 Don't worry, we can continue debugging your issue here.

**Comment by Goten87** [comment]
Testen it on my Samsung tv and no subs there as Well
But THE audio/video desync is gone on my tv

**Comment by Sami32** [comment]
@Goten87 What about the others tests: #--TRANSCODE--# [No Transcoding] [Sub: ?
FFmpeg with and without subtitle ?
With external subtitle only ?
A new log when something get better is welcome.

**Comment by Goten87** [comment]
i think i found my sub problem its the jap subs i need for english tested it on my pc
and the engish subs dint work on my pc as well so thats fixed now the only thing i need to fix is the audio/video desync thats happening

**Comment by Sami32** [comment]
@Goten87 Good, not for your defectuous ASS subtitle though...
So try to play a video file, without subtitle if possible, with [No Transcoding] in  #--TRANSCODE--# folder and report back with you log, please.

**Comment by Goten87** [comment]
oke i setted in the transcode settings FFmpeg on top of it all and its still giving me no subs and desync on my ps3

**Comment by Sami32** [comment]
@Goten87 Play a video using [No Transcoding] in #--TRANSCODE--# folder and send us you log, please.

**Comment by Goten87** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/414217/ums_dbg.zip)
here are the debug files for the watching true #--TRANSCODE--# folder

**Comment by Sami32** [comment]
@Goten87 I didn't saw problem in your log, but that MEncoder only was used.

Add or change these values in your UMS.conf:
```
ffmpeg_mux_tsmuxer_compatible = true
mencoder_mux_compatible = true
mencoder_forcefps =true
```

From inside #--TRANSCODE--# folder, try **[FFmpeg]** and **[TSmuxer]** when you play a video and tell if you see any difference and post your new log.

**P.S**. Could you check you CPU use in you Task manager while transcoding ?

**Comment by Goten87** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/416034/ums_dbg.zip)
settings on cant find FFmpeg files in my transcode folder
also my CPU is not getting above the 10% only when starting UMS up its spikes for a few sec to 35%

**Comment by Sami32** [comment]
@Goten87 That's strange that you cannot see [FFmpeg] engine.

Try to add `disable_subtitles =true` to your UMS.conf file.

And if you don't see any improvement try UMS version 6.3.2 with a clean install.
After that i hope you will get FFmpeg working fine and solve your issue, because i'm short of bullet.

Your problem is only on PS3, right ? the other formats MP4...are played fine, with and without subtitles ?

**Comment by Goten87** [comment]
no its also my ps4 (my samsung tv is working fine no desync and i can select subs from there)
somthing my ps3/4 not let me do

**Comment by Sami32** [comment]
@Goten87 So, if your tried all without success, you'll need a PS3 expert...as i'm short of bullet :-(

**Comment by Goten87** [comment]
@Sami32 i just fixed the desync on my own i just made a compleet new profile for my anime may left it all default and now it works fine again
i will now 1 by 1 set my settings on my test profile to the one i have on my anime profile and get back at u when i have the setting that will chance it all

**Comment by SubJunk** [comment]
@Goten87 it's likely that the sync issues are when using MEncoder but now by default we use FFmpeg for almost everything. There's not much we can do about the sync with MEncoder since it's all but abandoned so I think we can close this

**Comment by Goten87** [comment]
Yeah just close it ^^ I will use FFmpeg as my encoder now ^^
