### ISSUE TITLE
Duplicate "move file to different folder" in fully played action

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3721]
I found that there is a duplicate option for fully played action and I think one of those should be "move and mark as played" as option 5
![fully played duplicate move](https://user-images.githubusercontent.com/66766335/209062224-231dd55f-57d8-46df-953f-2f8ce015c733.jpg)

Also if this option is set and the settings are opened then this shows as blank.
![fully played blank](https://user-images.githubusercontent.com/66766335/209062377-350109a6-da4a-4ba9-973d-266dfa05f274.jpg)

When it should be showing
![fully played move](https://user-images.githubusercontent.com/66766335/209062440-798338ae-7a1b-4a75-adda-378d0b9b5c11.jpg)

**Comment by SubJunk** [comment]
Sweet, thanks for this

**Comment by SubJunk** [comment]
That's funny, the Java app is serving the wrong translation there:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/584228/209220425-ac1ce1c0-d155-4fc4-b7b6-a80623349575.png">

Looking into it now

**Comment by SubJunk** [comment]
I can't see anything wrong with what we are doing here, it's just using the built-in Java methods to load the resource and iterate through it. It might be a bug in Java itself. Maybe we can workaround it somehow though

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers can anyone see anything obvious that would cause this?

**Comment by SurfaceS** [comment]
I don't have this on my computer.

Browser have good data in i18n tested for en-US and fr.
Does the JAVA GUI do the same things ?

**Comment by Mik-S-UMS** [comment]
I wonder if this is an error in en-UK language.
The Java GUI shows the right options. Both options in the web settings do different things, first sets the option it to 3 and the other sets to 5.

I tried changing languages to see if others are different but nothing changes in the web interface, even after refreshing the page. It does change in the Java GUI after restarting UMS though. Might be something to look into.

**Comment by Mik-S-UMS** [comment]
I have confirmed it is the "English, United Kingdom" language setting that has the duplicate. Choosing "English, United States" shows it correctly.

I have had a play around and found the language button on the top right of the interface. I was using the the option in `general settings>application>language` before but this seems independent of the button and does not work instantly requiring a restart of UMS, even then it only effects the old Java GUI.

Should this not control both the web interface and Java GUI language? Or maybe there needs to be clarity that the one in the options is only for the old GUI or could even be removed from the web settings.

**Comment by SubJunk** [comment]
@Mik-S-UMS Good find, yes that translation was wrong in Crowdin. I have fixed that now.

Interesting suggestion that the language could be different between Java and browser
