### ISSUE TITLE
(FEATURE) 2D to 3D Algorithmic Enhancement

### ISSUE THREAD

**Issue by threedguru** [UniversalMediaServer/UniversalMediaServer#3723]
Hi Guys,

This is a bit of a heads up. I'm hoping we can get this into the next release. I've developed a significant enhancement to the 2D to 3D algorithm that iscurrently in UMS Release 13. I've described the enhancement here:

https://iwantaholodeck.com/enhanced-2d-to-3d-algorithm/

I've already proven it against my development version of UMS. I need to create a pull request - just need a little time. There are changes to the conversion script, but the main application addition is a new AviSynth library masktools2, which is added in exactly the same way as mvtools2 library currently in UMS. 

More specifically, the code uses the motion vector analysis (MAnalyse) and scene change detection routines (MSCDetection) from the mvtools2 library, see documentation and github repository below:

http://avisynth.org.ru/mvtools/mvtools2.html#version2
https://github.com/pinterf/mvtools
 
In addition, it uses the mt_merge routine from the masktools2 library,
see documentation and github repository below:
 
http://avisynth.nl/index.php/MaskTools2/Mt_merge
https://github.com/pinterf/masktools

**Comment by SubJunk** [comment]
@threedguru that sounds good, I'm familiar with those libraries and those functionalities. Thanks for the heads up

**Comment by threedguru** [comment]
This is now in the main branch so closing.

**Comment by SubJunk** [comment]
@threedguru great, I'm planning to do a release in the next few days
