### ISSUE TITLE
App asked me to report this bug.. 

### ISSUE THREAD

**Issue by Yojione** [UniversalMediaServer/UniversalMediaServer#3725]
Will just detail.. I guess you may know about this.. and may be fixed in 13.0.1 already..
But since you asked.. I will report the bug... shout if you want more details.
Just upgraded to 13.0.0 and on start up its now showing the browser page for http://localhost:9001/
I really dont want it to do that.. I just happy with the "normal" app interface..
So went to the settings (in the browser version) and went to general settings ->  Launch GUI in browser on startup (which I assume to be my area of interest) and unticked the box.,... pressed the "Save" and got a notification/popup to say something like "your configuration changes were not saved, please click here to report the bug to us"
So here I am.. 
Oh, machine is Windows 10 Pro, 22H2, fully patched etc.. Kaspersky Antivirus
As I say, shout if you have questions or need log files etc.
Thanks and best regards

**Comment by SubJunk** [comment]
@Yojione thanks for reporting this :) you are right it's fixed in 13.0.1
