### ISSUE TITLE
Shared content not saved via old settings dialog

### ISSUE THREAD

**Issue by infectormp** [UniversalMediaServer/UniversalMediaServer#3726]
I installed v13 (clean install) posted in issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/3698 and it doesn't save newly added Shared Content entry add via old settings dialog. UMS saves only entry added via wizard at first run.

Step to reproduce:
1.Open old settings dialog
2.Add new Shared content entry
3.Press Quit
4.Run UMS again, Shared content will be same as on 1st step.

**Comment by infectormp** [comment]
But work if you are using web interface

**Comment by SubJunk** [comment]
I have reproduced this

**Comment by SubJunk** [comment]
This is fixed now, please let me know when you have downloaded the fixed build at https://www.universalmediaserver.com/uploads/UMS-infectormp.exe

**Comment by infectormp** [comment]
fix confirmed
