### ISSUE TITLE
Impossible d'enlever le démarrage automatique dans le navigateur .

### ISSUE THREAD

**Issue by Mic44mat** [UniversalMediaServer/UniversalMediaServer#3730]
[ums_dbg_2022-12-25-16-08.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10300193/ums_dbg_2022-12-25-16-08.zip)

**Comment by SurfaceS** [comment]
fixed in next release

**Comment by Mic44mat** [comment]
Hello SurfaceS,Great, great news, thanks for the return.
