### ISSUE TITLE
Unable to save configuration file in new GUI

### ISSUE THREAD

**Issue by ghost** [UniversalMediaServer/UniversalMediaServer#3734]
Unable to save configuration file in new GUI

**Comment by SubJunk** [comment]
@ghost what do you mean by "configuration file"?

**Comment by rimroot** [comment]
I am having the same issue. Unable to save settings. Running version 13.0.0 on windows 10

![2022-12-29_15h06_32](https://user-images.githubusercontent.com/29730129/209955271-04833222-5626-4466-b7da-dc6bd19bce1c.png)

**Comment by SubJunk** [comment]
If you let me know your operating system I can upload a fixed build, I think this is already fixed

**Comment by rimroot** [comment]
> If you let me know your operating system I can upload a fixed build, I think this is already fixed

In my case it is Microsoft Windows 10 build 19044 64-bit

**Comment by SubJunk** [comment]
Can you please let me know if it is still happening here https://www.universalmediaserver.com/uploads/UMS-3734.exe
If it still doesn't work, please attach TRACE logs as described here https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new

**Comment by amarcionek** [comment]
I downloaded the latest 13.1 release today and do get the same error about the settings not being saved. However, they do appear to be saved because if I refresh http://localhost:9001/settings, it does appear the settings change took.

**Comment by mykeehu** [comment]
Same problem here with 13.1, I cannot turn off the Launch GUI in browser on startup setting in the browser

**Comment by Mik-S-UMS** [comment]
A few others on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=15499) has the same problem. I added a link to this issue so they can help too.

**Comment by mykeehu** [comment]
@SubJunk I get this error when saving in console, I have Windows 10 with Chrome, both are up to date.

```
xhr.js:247          POST http://localhost:9001/v1/api/settings/ 500 (Internal Server Error)
(anonymous) @ xhr.js:247
xhr @ xhr.js:49
Pe @ dispatchRequest.js:51
Promise.then (async)
value @ Axios.js:118
(anonymous) @ Axios.js:181
(anonymous) @ bind.js:5
(anonymous) @ Settings.tsx:126
f @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ Settings.tsx:108
(anonymous) @ use-form.ts:137
De @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
zr @ react-dom.production.min.js:105
Mr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
uu @ react-dom.production.min.js:274
Ie @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
Gt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
```

**Comment by mykeehu** [comment]
Here is my logs, hope it helps you find the cause of the error! I have two options enabled:
- Launch GUI in browser on startup
- Enable standalone web player

[ums_dbg_2023-01-04-06-24.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10341654/ums_dbg_2023-01-04-06-24.zip)

**Comment by SubJunk** [comment]
@mykeehu thanks for the logs. I have identified one bug with the database from them so that is very useful! Can you please see if this build still has your bug? https://www.universalmediaserver.com/uploads/UMS-3734.exe

**Comment by mykeehu** [comment]
@SubJunk you have found the cause of the bug, with this latest version I get a different Saved state instead of an error and the interface also changes the modified options. Thanks for the quick help!

**Comment by SubJunk** [comment]
@mykeehu that's great news, thanks for confirming!
