### ISSUE TITLE
Login screen repeatedly showing since 13.1.0

### ISSUE THREAD

**Issue by Richardk2n** [UniversalMediaServer/UniversalMediaServer#3751]
I am running UMS in the docker image.
Starting with the 13.1.0 image (13.0.1 worked in that regard) the login screen is somewhat persistent.
As in steps to reproduce:
Create new docker
Create Admin account
Get login screen

Whenever I open it I get the login screen. If I enter my login the site refreshed and still presents the login screen (about 90% of the time, sometimes it works).
If I go to inspect and delete the \<form> tag and refresh it lets me through.

Log for the login process shows:
INFO  16:50:06.238 [pool-3-thread-2] Checking user table have admin
INFO  16:50:18.797 [pool-3-thread-4] Finding user: richard 
INFO  16:50:18.798 [pool-3-thread-4] Got user from db: richard
INFO  16:50:19.206 [pool-3-thread-4] User richard logged
INFO  16:50:19.502 [pool-3-thread-6] Checking user table have admin

Whenever I refresh, I just get
INFO  16:50:43.769 [pool-3-thread-9] Checking user table have admin
with increasing numbers

I am clearly logged in however, the server seems to restart the login script.

**Comment by SubJunk** [comment]
@Richardk2n thanks for reporting this, any ideas @SurfaceS ?

**Comment by BitEater21** [comment]
@SubJunk : As stated in #3750 I also get the login screen repeatedly sometimes when switching between settings pages. But today it appears less often. Logs attached.

I don't use docker, just directly in Windows 10.

[_ums_dbg_2023-01-05-07-40.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10349937/_ums_dbg_2023-01-05-07-40.zip)

**Comment by SubJunk** [comment]
This should be fixed now, here is a build to confirm. Please let me know when it's downloaded https://www.universalmediaserver.com/uploads/UMS-3751.exe

**Comment by BitEater21** [comment]
@SubJunk : I was not easy to install this because my Norton 360 always denied updating the ,png files. I had to disable some features temporarily.
But now that I got it installed, it seems all works fine.
Thank you

**Comment by SubJunk** [comment]
@BitEater21 that's weird about Norton! Thanks for confirming the fix

**Comment by BitEater21** [comment]
@SubJunk : unfortunately the uploaded version from last week is not available any more and on my new computer I don't have it yet. Can I get a fixed where anywhere else?

**Comment by SubJunk** [comment]
@BitEater21 13.2.0 has been released publicly now
