### ISSUE TITLE
Erro ao Salvar Configuração

### ISSUE THREAD

**Issue by FxStillus** [UniversalMediaServer/UniversalMediaServer#3759]
![image](https://user-images.githubusercontent.com/121981904/210657343-367cca70-7163-4983-a519-04bc5f57ebe5.png)

**Comment by FxStillus** [comment]
quando eu ligo o computador abre a janela do google chrome com o serviços midia universal
eu não quero que abra a janela, quero que inicie minimizado

**Comment by SubJunk** [comment]
@FxStillus please try https://www.universalmediaserver.com/uploads/UMS-3750-2.exe

**Comment by SubJunk** [comment]
Stale
