### ISSUE TITLE
Missing font dependency in docker

### ISSUE THREAD

**Issue by Richardk2n** [UniversalMediaServer/UniversalMediaServer#3762]
When opening my audio folder in the web player, the generic MP3 file thumbnail does not load and the log has loads of java errors stemming from:
`INFO  12:16:36.682 [pool-3-thread-29] Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null`

This can be fixed by running:
`apk add ttf-dejavu`
in the container

This package is also a dependency of vlc so everyone who has that installed does not have an issue.
Could you add that package to the docker?

**Comment by SubJunk** [comment]
@Richardk2n thank you for the detailed issue, this will be fixed in the next release
