### ISSUE TITLE
Show Media Library option disables the cache and other web settings not working.

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3774]
I found that if you change the `Show the "Media Library" folder` in web settings it will change `use_cache` in the conf instead of `show_media_library_folder`

`Show the "Live Subtitles" folder`, `Audio language priority:` and `Subtitles language priority:` do nothing

I have documented a few other settings that don't work as their should [here](https://github.com/UniversalMediaServer/UniversalMediaServer/discussions/3773)

**Comment by Mik-S-UMS** [comment]
This still happens in the release of 13.1.0 and @Boss on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?p=46843#p46843) has also reported it.

**Comment by SubJunk** [comment]
Working on a fix now

**Comment by Mik-S-UMS** [comment]
I have tested all these options and they are now working correctly (at least updating UMS.conf)
 
I still plan on going over every option again sometime to confirm they still work as intended and update that discussion post with any other issues I find and mark things that have improved.
