### ISSUE TITLE
Add folders via startup wizard

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#378]
@UniversalMediaServer/developers I think the startup wizard is a good way for new users to avoid most of our interface, which is amazing for advanced users but not so amazing for noobs, and would love to add the ability to add folders to the wizard, rather than just mentioning it at the end.

I tried doing it a while ago and failed, any takers?

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers I think this would be a really great feature to have, is anyone interested in taking this on? If not I can try again

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942

**Comment by SubJunk** [comment]
This was implemented a while back, you can add your first folder there
