### ISSUE TITLE
React development permissions

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3787]
When I develop the react application by running `yarn start` in the `react-client` folder, I can only see the player. What's your workflow for developing web settings @SurfaceS ?

**Comment by SubJunk** [comment]
@SurfaceS did you see this? it is making it hard to work on the web settings

**Comment by SurfaceS** [comment]
**package.json**
`"proxy": "http://localhost:9002"`
**UmsConfiguration**
`DEFAULT_WEB_GUI_PORT = 9001`
`DEFAULT_WEB_PLAYER_PORT = 9002`
so basically, you end in the player.

**Comment by SubJunk** [comment]
Ah I see, it works if I change that proxy port. I'll make some documentation about it. Thanks
