### ISSUE TITLE
what is webui 's default username and password?

### ISSUE THREAD

**Issue by PaintOnBrush** [UniversalMediaServer/UniversalMediaServer#3788]
![image](https://user-images.githubusercontent.com/2153952/213964947-56730a81-937b-44f8-aff9-8755c6b8ab95.png)

**Comment by SubJunk** [comment]
@PaintOnBrush there is no default user. The first time UMS runs you will see:

![image](https://user-images.githubusercontent.com/584228/213987427-781348f6-9dba-4bc1-b879-ae1056340384.png)

If you or someone else created a user and forgot the password, you can delete your local database folder (on Windows it is at `C:\ProgramData\UMS\database`) to reset the whole thing, or maybe just the `USERS` files in that folder could be enough
