### ISSUE TITLE
Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null

### ISSUE THREAD

**Issue by XzaR90** [UniversalMediaServer/UniversalMediaServer#3811]
# Error/Log
18:27:05.625 [main] A serious error occurred during Universal Media Server initialization: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null

# How to reproduce
Clean installation of windows with media feature pack, UMS and java and started the UMS. 

# Symtom
The web UI is blank, the media server does not list anything.

# Platform and Version
Edition	Windows 10 Pro N x64
Version	22H2
Installed on	‎2021-‎04-‎28
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
Universal Media Server Windows (installer)] 13.1.0 x86 (Also 13.0.1)
Java Version 8 Update 351, (build 1.8.0_351-b10) x86

# Related 
https://www.universalmediaserver.com/forum/viewtopic.php?p=46144

**Comment by ExSport** [comment]
Already fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/3794 👍
