### ISSUE TITLE
Unknown Devices Incorrectly Named

### ISSUE THREAD

**Issue by purevertigo** [UniversalMediaServer/UniversalMediaServer#3813]
Unknown devices always come up as Sony Xperia Z devices. 

Do Sony even make phones anymore??

**Comment by Mik-S-UMS** [comment]
Have you changed the "Default renderer when automatic detection fails:" option? This is "Unknown renderer" as default.

**Comment by purevertigo** [comment]
There is no option to change it.

**Comment by Mik-S-UMS** [comment]
This is where it is in the options.

![image](https://user-images.githubusercontent.com/66766335/217596493-ec195adf-26df-4636-91fa-ec9cac8db698.png)

![image](https://user-images.githubusercontent.com/66766335/217596435-26d7d73a-94d5-47f0-852d-c4ffdb083c21.png)

**Comment by purevertigo** [comment]
I don't get any of those settings on the top screen.

**Comment by SubJunk** [comment]
If you provide logs we can see the answer for ourselves. Instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new

**Comment by purevertigo** [comment]
Doesn't seem to happen in TRACE mode which makes it hard to get logs.

**Comment by purevertigo** [comment]
attached.


[ums_dbg_2023-02-09-19-28.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10694940/ums_dbg_2023-02-09-19-28.zip)

**Comment by SubJunk** [comment]
It looks like this is a funny coincidence. So there is something on your network called `NRDP MDX` that sends `2c127e30-a844-11ed-9c8f-c697a4720188` with its messages, and that matches the Sony Xperia config line `C65??|C66??|C69??|D65??` because it has `C69`
You could verify that by changing the Xperia config to just `C65??|C66??|D65??` and see if it still happens

**Comment by purevertigo** [comment]
Makes no difference. Logs attached.

[ums_dbg_2023-02-10-18-51.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10704980/ums_dbg_2023-02-10-18-51.zip)

**Comment by SubJunk** [comment]
Weird, can you attach logs from this version please? I added more logging https://www.universalmediaserver.com/uploads/UMS-3813.exe

**Comment by purevertigo** [comment]
attached

[ums_dbg_2023-02-11-16-20.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10712687/ums_dbg_2023-02-11-16-20.zip)

**Comment by SubJunk** [comment]
I see now, I think the Xperia config was written wrong. Probably the author thought the `?` character was a wildcard, but it causes this string `uuid:aff61462-43be-4501-9db1-cf4474fd63af` to match `d65??` as I have confirmed on regex101.com

![image](https://user-images.githubusercontent.com/584228/218246898-6a7e59b0-be0e-482b-b568-7febe80826c7.png)

I will fix it in the next release. In the meantime you can just disable that Xperia config

**Comment by purevertigo** [comment]
Great. Thanks so much @SubJunk 

How do I disable the config?

**Comment by SubJunk** [comment]
Make sure you have advanced settings enabled in the web settings at http://localhost:9001/settings
Then enable only the renderers you want in General Settings tab, like this:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/584228/218277938-bf4812c0-876f-472e-9f8b-bd1ad33acd30.png">

**Comment by Mik-S-UMS** [comment]
Another option is to just delete the Sony-Xperia.conf from your system and it will be replaced when you next update.
