### ISSUE TITLE
WEB Interface not responding.

### ISSUE THREAD

**Issue by amigoexp** [UniversalMediaServer/UniversalMediaServer#3818]
Hi i cannot acces WebUI. I have tried localhost:9001/9002. My local ip 192.168.1.33:9001/9002. Both not responding.
[ums_dbg_2023-02-07-19-44.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10677490/ums_dbg_2023-02-07-19-44.zip)
++
I have added 9001 and 9002 ports to the firewall.
How can i fix it?

**Comment by Mik-S-UMS** [comment]
This is a known bug and has been fixed in 13.2.0. This version has just had its public release on the website.
