### ISSUE TITLE
[Feature Request] Resolve "Access Denied" IPs

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#382]
use any method that allows for easy reading of IP's that show up as Access Denied IP's.

is there a way we can incorporate a DNS lookup or a whois lookup to this?

(also hey guys!)

**Comment by Sami32** [comment]
@DeFlanko @Optimusprimeums @Nadahar Did this issue get solved already ?
Since i don't saw any report since mars 2015, i'm just wondering...lucky to don't have experimented this one myself :-D

**Comment by Nadahar** [comment]
@Sami32 I have no idea, I'm not even sure what's the idea. Is it to find the IP blocklist in an easier manner? I'm having a hard time to understand what resolving DNS would help, DLNA only works on local networks and local networks rarely have DNS records for it's hosts (except Microsoft AD networks, but how many of UMS' users use that?). I'm just not sure what the request is for..

**Comment by Sami32** [comment]
@Nadahar I saw a similar issue somewhere else but i can't remember where it was...and i only understood that some users was not able to get "connected"
But it was sometime ago, and like tell the proverb water have gone under the bridge.
As you told me, never presume that it was solved...it's why i asked you. Thanks for answering :-)

**Comment by Sami32** [comment]
I understand that something that was in version 3 is not in UMS version 4, related to "Access denied" ?
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e637a81cd604353938eaf9a3d40039b0d7949a5d/src/main/java/net/pms/network/RequestHandler.java
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/afcc9c1e651bce9698bb414695a24318a2a5deee/src/main/java/net/pms/configuration/IpFilter.java
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e637a81cd604353938eaf9a3d40039b0d7949a5d/src/main/java/net/pms/network/RequestHandlerV2.java

**Comment by polygirl** [comment]
@DeFlanko since this was reported some time ago and there's been no further information we presume this has now been resolved for you and so we'll close the issue.  Please feel free to reopen if you have further info.
