### ISSUE TITLE
Subtitles cause freezing.

### ISSUE THREAD

**Issue by crossmr** [UniversalMediaServer/UniversalMediaServer#383]
Windows 7 
8 GB ram
intel core 760 2.8 ghz

Google Chromecast

I have on the PC:
Bubble upnp server (transcoding)
universal media server 

on my phone:
bubbleupnp to choose videos and send them to chromecast

I previously had this set up with twonky demo in place of UMS. With that in place of UMS I had zero playback issues. 

The first movie I tried to play with subs and UMS skipped horribly. It would play 2-3 seconds then freeze over and over and over. I thought it was a wifi issue, restarted everything and it made no change. Tried the movie again with subtitles removed, and it played perfectly from start to finish without any skipping. 

Subtiltes are SRT in UTF-8 format.

**Comment by Sami32** [comment]
@crossmr @SubJunk Did this issue can be closed ?
Many renderers improved since then, and no log was given so...
