### ISSUE TITLE
Browser Opens on startup

### ISSUE THREAD

**Issue by purevertigo** [UniversalMediaServer/UniversalMediaServer#3839]
I am not sure I needed logs but can provide if needed.

My browser starts up and opens to localhost login everytime I autostart the app. How to turn this off?

**Comment by Mik-S-UMS** [comment]
In the General settings tab under the "Graphical User Interface" section there is the option "Launch GUI in browser on startup".

**Comment by purevertigo** [comment]
Great! Thanks so much @Mik-S-UMS
