### ISSUE TITLE
PlayerUtilTest build failure

### ISSUE THREAD

**Issue by Mr-Figs** [UniversalMediaServer/UniversalMediaServer#3841]
I'm unable to build UMS from source on my system; `net.pms.util.PlayerUtilTest` always hits an error and halts the process. Logfiles are attached, here's the interesting bit:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   PlayerUtilTest.setUpClass:45 » NullPointer Cannot invoke "net.pms.configuration.UmsConfiguration.isUseSymlinksTargetFile()" because "this.configuration" is null
[INFO] 
[ERROR] Tests run: 375, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.571 s
[INFO] Finished at: 2023-02-25T17:03:33-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M9:test (default-test) on project ums: 
```

I'm running Fedora 36. Any idea what this could be? The compiled binaries run fine on the same system.

[buildLog.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10832429/buildLog.txt)
[net.pms.util.PlayerUtilTest.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10832430/net.pms.util.PlayerUtilTest.txt)

**Comment by SubJunk** [comment]
We are getting that in our CI builds too, for one operating system https://github.com/UniversalMediaServer/UniversalMediaServer/actions/runs/4268910586/jobs/7431726417

**Comment by SubJunk** [comment]
That's fixed now in `main`

**Comment by Mr-Figs** [comment]
Looking good on my end too. Thanks!
