### ISSUE TITLE
IP-Filter not blocking all IP Addresses

### ISSUE THREAD

**Issue by Optimusprimeums** [UniversalMediaServer/UniversalMediaServer#385]
I'm not sure if this is just me but i've added a IP Address to the IP-Filter (Whitelist) section of the general config. Now i'd see in the log's that it blocks some IP Addresses but it never blocks one in particular which is associated with a Windows media player renderer. It always detects that particular one and displays it in the front page 'Detected Renderer' section. I would think that by whitelisting the ones you want to access UMS all other IP's should be blocked. Debug log is here http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=12285#p12285

**Comment by Sami32** [comment]
@Optimusprimeums @SubJunk Did the latest UMS version solved this issue ? I don't get this problem but i don't have WMP to test this special case...
