### ISSUE TITLE
Stream doesn't start on PS3 Showtime (loading indefinitely) 

### ISSUE THREAD

**Issue by wesyr** [UniversalMediaServer/UniversalMediaServer#387]
Hi there, 
I've recently downloaded the newest version of UMS, and I can't stream my mkv files to my PS3 with Showtime I've tried playing with renders configuration but it's still a no go :( 
This is what's going on: 
1. I've made a clean Win7 machine with Java 7 Update 67
2. Installed UMS 
3. Configured (as always) Showtime4 conf 
4. Launched PS3 and started newest build of Showtime4 on PS3
5. Started UMS and configured the folders and the rest
6. Going to start playing Z.Nation.S01E02.720p.HDTV.x264-KILLERS.mkv
7. Loading indicator starts to load ( ;) ) and it's loading indefinitely, when i check the debug log on showtime it tels me that UMS send theinformation that file size is:

> HTTP [DEBUG]: Read error (-1) [bytes=9223372034707226623-9223372034707292158] filesize 9223372034707292159 -- retrying

ums_dbg.zip and pictures how it looks like are available also on your forum under [UMS forum General Help Topic](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2261)

Screen of UMS and Shwotime on PS3 with Debug log: 
![ums](https://cloud.githubusercontent.com/assets/6331666/4475056/220ffd70-4968-11e4-9559-e5385fb4402a.png)
![dsc_1392](https://cloud.githubusercontent.com/assets/6331666/4475057/22100130-4968-11e4-8e7b-22e2581a9126.JPG)

**Comment by Sami32** [comment]
@wesyr @Nadahar Did the lastest UMS version solved this issue ?

**Comment by SubJunk** [comment]
Closing this due to no response from @wesyr 
Feel free to reopen if it is still happening
