### ISSUE TITLE
Не сортирует по дате

### ISSUE THREAD

**Issue by stnnzp** [UniversalMediaServer/UniversalMediaServer#3881]
С какого оно так странно стало сортировать по дате? Вообще нет логики.
[https://ibb.co/fXXtYbM](url)

**Comment by stnnzp** [comment]
Это на последней версии Universal Media Server 13.2.1. Лучше бы не обновлялся ) ведь раньше было нормально.

**Comment by SubJunk** [comment]
Sorting works for me, so we need logs to help. See instructions at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new

**Comment by stnnzp** [comment]
[ums_dbg_2023-04-15-09-59.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/11238345/ums_dbg_2023-04-15-09-59.zip)
Here, on the old version everything works, on this one it does not work.

**Comment by stnnzp** [comment]
![tv](https://user-images.githubusercontent.com/13903649/232185410-c70c3526-5f50-4184-bf4b-a41109d0c056.jpg)
![Снимок экрана от 2023-04-15 10-37-59](https://user-images.githubusercontent.com/13903649/232185447-b879ac7f-8549-40af-88d9-681c60a5853d.png)
Photo of my TV and computer screenshot. Doesn't erase. I already deleted all the settings and did it again and rearranged the program. Nothing helps.

**Comment by SubJunk** [comment]
Thanks for the logs and images. I searched the logs for "2023 03 23" and nothing came up, that might mean you didn't browse to that folder before packing the logs. Can you do that please?

**Comment by stnnzp** [comment]
![Снимок экрана от 2023-04-22 07-41-20](https://user-images.githubusercontent.com/13903649/233757790-f9a14fbd-f4b6-4fb5-84ff-e9baa50e8d74.png)
[ums_dbg_2023-04-22-07-38.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/11300088/ums_dbg_2023-04-22-07-38.zip)

I updated to version 13.3.0. The error is there again. Here is a new screenshot and a new log.

**Comment by stnnzp** [comment]
![Снимок экрана от 2023-04-22 08-00-05](https://user-images.githubusercontent.com/13903649/233758468-c9d091d1-9865-4342-ba43-aba7fa701d1f.png)
Folder dates in the log

**Comment by SubJunk** [comment]
@stnnzp I think I see the problem and working on a fix

**Comment by SubJunk** [comment]
@stnnzp that is fixed now and here is the fixed build. Please let me know when you have downloaded it https://www.universalmediaserver.com/uploads/UMS-stnnzp.tgz
