### ISSUE TITLE
Automatic startup with Windows

### ISSUE THREAD

**Issue by Liridy** [UniversalMediaServer/UniversalMediaServer#3898]
In the new version, the function of enabling the automatic launch of UMS at the start of Windows does not work. There is no such possibility in the Web interface (it was present in previous versions). When using Settings (old)" -> "Basic Settings" -> "Run with Windows" (using administrator rights), the program does not appear in the startup. Forced attempts to start automatically: through Windows "Startup", the Run (registry) section - unsuccessfully. At the same time, UMS is present in the startup menu. If possible, please fix it. Or are there good reasons for excluding this function? Thanks. 
=======================================================================
P.S. Sorry! I was wrong - I had problems with Windows. When fixed, UMS loads perfectly. Sorry again for the trouble.

**Comment by SubJunk** [comment]
@Liridy that's good news, thanks for updating us :)
