### ISSUE TITLE
Low bitrate on Samsung TVs

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#391]
@UniversalMediaServer/developers I noticed that some of the Samsung TV renderer configs have the maximum bitrate set to 25, does anyone know if that was tested on a wired or wireless connection?
If it was tested on wireless then it may have been a network limitation instead of a renderer one.

Can someone with a Samsung TV and wired network remove that bitrate limit and see how things go with high bitrate videos?

**Comment by Sami32** [comment]
@SubJunk @Optimusprimeums  @Nadahar So, what's happen since then ? is it really a Samsung limitation ? Because some Samsung renderers have bitrate at 25 again now.
Could this issue ble closed ?

**Comment by SubJunk** [comment]
Those values came from the TV manuals so I think they're good, we should just make sure that new configs don't needlessly inherit them on creation
