### ISSUE TITLE
Knowledge base offline

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3914]
Just seen [this](https://www.universalmediaserver.com/forum/viewtopic.php?t=15731) post on the forum that the Knowledge base is not working and trying it myself I get the Cloudflare page with the error "Web server is down"

**Comment by SubJunk** [comment]
Ah I didn’t know it was down, but it’s good timing since I had this weekend picked out to try a new software for it. The one that is being used just isn’t the right tool for the job. I’ll post updates on progress in this issue. Thanks for letting me know!

**Comment by SubJunk** [comment]
The knowledge base is back up now. I'll make a new issue for the new one

**Comment by SubJunk** [comment]
I have also added uptime monitoring so I'll know if it goes down again
