### ISSUE TITLE
New knowledge base

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3919]
Our current Knowledge Base has some good content, but needs more, and more importantly I think it needs software that is better suited to docs.
It currently uses [BookStack](https://www.bookstackapp.com/). I have started using [Docusaurus](https://docusaurus.io/) locally and I like it so far. I plan to push it to a new repository in this org soon.
One major difference between those two is that BookStack uses a database while Docusaurus is a static site generator.
This means it's easier to make edits with BookStack because the data isn't in the code.
There are advantages to having the data as code though since it means it is reviewable, and that we don't have to create and manage user access for editors, since that access is managed by GitHub with Pull Requests as usual.

@UniversalMediaServer/developers (or anyone) any thoughts are welcome

**Comment by ik666** [comment]
I think from a developers perspective the concept behind Docusaurus is easier to handle and maintain.

**Comment by SubJunk** [comment]
Ok great. I have mostly migrated the existing docs so I'll push it soon

**Comment by SubJunk** [comment]
The code is pushed to https://github.com/UniversalMediaServer/knowledge-base
I haven't deployed it anywhere yet but you can see it by checking out the code and running `yarn` then `yarn start`

**Comment by SubJunk** [comment]
There are some opt-in features of Docusaurus that we probably want, like search, i18n (could be hooked up to Crowdin too), and versioning

**Comment by SubJunk** [comment]
I added search and i18n which is now integrated with Crowdin. I will deploy it soon

**Comment by SubJunk** [comment]
This is going really well, it is set up for automatic deployments which sync with Crowdin. I'll close this now but we could do with more content
https://support.universalmediaserver.com/
