### ISSUE TITLE
"Show Media library" not working correctly in web settings

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3948]
Just saw a [post](https://www.universalmediaserver.com/forum/viewtopic.php?t=15773) on the forum that if they turn off the media library then it will also stop metadata.

I have checked on the 13.4.1 snapshot build and I can't see the option to show the media library. Instead the Resume folder was marked as being on even though I have that off. Hovering over the Resume option brings up the Media Library tooltip instead (the other options don't show tooltips too)

![Clipboard Image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/66766335/99eda756-2696-485f-a4aa-78e4e15306a5)

Toggling the Resume option changes `show_media_library_folder` in UMS.conf

I think this is related to #3774

**Comment by SubJunk** [comment]
@Mik-S-UMS I'm looking into this now. One of us needs to go through https://github.com/UniversalMediaServer/UniversalMediaServer/issues/3774 and see what things have been fixed and remove them, then I can fix the remaining things. Do you have time to do that please?

**Comment by SubJunk** [comment]
I can see there are two bugs causing this. The first one is that UMS is using the British English translation, and the second is that the British English translation has the wrong value for that. I'm working on these now.

**Comment by SubJunk** [comment]
Hmm it looks like UMS is using the right language according to what the browser is telling it, and Chrome defaults for some reason to British English:
<img width="698" alt="image" src="https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/598c2b66-8e36-4815-9cba-2f89944ab1de">
I have fixed the translation in Crowdin, so this issue is resolved

**Comment by Mik-S-UMS** [comment]
I'll see if I have time to check everything tomorrow. 

If it is a language problem then I'll change to English-US to test as well. There should be very little differences between US and UK translations besides spelling.

If I run that build script will it get this change so I can see if it is fixed?

**Comment by SubJunk** [comment]
@Mik-S-UMS great, thanks. Yes it should show up with the build script. You can see the change here https://github.com/UniversalMediaServer/UniversalMediaServer/commit/971de7d024601861bd8679722badb8db896feb3d#diff-33e08afb617dd534c4f5fa455c236cf7842c8916f3b28ea1da095005d5ddc465L523

**Comment by Mik-S-UMS** [comment]
I have tried the patch and it has fixed that translation bug, but now I was able to see what the original issue was.

If the "Show Media Library" option is on I get
![Show Media library-50%](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/66766335/df25ad4d-fb94-4185-8dd9-e48b40b9534e)

But with it turned off
![Hide Media Library-50%](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/66766335/0957660e-3809-4c2e-bf39-764b407ec4c9)

This should only hide the virtual folders not prevent the display of the metadata.

Might be better to have the media library always on for the web interface anyway but have that option control showing the Media library folder on other renderers.

**Comment by SurfaceS** [comment]
> This should only hide the virtual folders not prevent the display of the metadata.

true, fixed in #3960

> Might be better to have the media library always on for the web interface anyway but have that option control showing the Media library folder on other renderers.

No, it's not needed.
