### ISSUE TITLE
Custom renderer configs not working correctly

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3949]
There is a [user](https://www.universalmediaserver.com/forum/viewtopic.php?t=15776) that has upgraded to 13.4 from 10.15.0 and found that their custom confs have stopped working. 

As some of their devices did not use UUID so they had added the IPs in the `device` field but now these ones are ignored when it worked before. 

Also when I tried to create a custom conf in the old GUI, UMS was saving in `C:\Program Files (x86)\Universal Media Server\renderers` which it does not have privileges to do so it does not work. Running UMS as admin will work but it should be saving in `C:\ProgramData\UMS\`

I was not able to change the save location too.

**Comment by Mik-S-UMS** [comment]
It appears that using IPs in the device field stopped working after 11.6 as that version was the last one where it still works.

**Comment by SubJunk** [comment]
@Mik-S-UMS those are serious bugs, damn. Good investigation

**Comment by SubJunk** [comment]
@SurfaceS this looks like a bug introduced in v12, any ideas?

**Comment by SubJunk** [comment]
The user has confirmed this fix works, thanks!
