### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Twig6943** [UniversalMediaServer/UniversalMediaServer#3957]
Why doesn't ums have youtube-dl? The rss method doesn't work on my tv but when I manually download the video it does. (Also getting the rss link for every channel you subscribed is a bit pain in the ass.)

**Comment by SubJunk** [comment]
@Twig6943 UMS does have youtube-dl. What is it exactly that doesn't work for you? Will need logs too

**Comment by SubJunk** [comment]
Closing for lack of response
