### ISSUE TITLE
v14

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3969]
This issue is to document and discuss v14 features.

I want to focus on access control. There are two aspects to it:
1) Deny and allow renderers
1) Show and hide folders based on renderers

For 1, we currently have it in a limited way; we have the ability to either allow all renderers (the default), or to specify an allowlist. 
There is no option for a denylist strategy, and I have started to implement that with a GUI in a branch, so the user can choose whether to use allowlist or denylist, and toggle it for each renderer in the GUI https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3968
Here are some screenshots of that branch:
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/4e6e28b5-6d37-419f-8a14-866b88afe758)
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/11d8da2d-fe87-4375-96a7-1aa8272a9f80)
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/e717c0bb-5528-487d-8d75-8d4a479ca1a3)

For 2, we used to have this, and it has been requested a few times to re-add it. Our implementation in the past had no GUI so it wasn't as widely used, but some power users relied on it. There is a GitHub issue documenting some of the history here https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1801

If anyone wants to help with this it would be great @UniversalMediaServer/developers

**Comment by SurfaceS** [comment]
**Deny and allow renderers**
Renderer can be described by an IP address, but also an upnp uuid.

IP address can change (DHCP or manual change).
UUID can be changed as well when you reset the device (dynamically created).

So it's an hard goal.

**Show and hide folders based on renderers**
Maybe to allow this, we can use the users/groups.
Default shared conf -> all
Added custom shared -> user only

Then, link user to a device by UUID.

**Comment by SubJunk** [comment]
Cool idea about the user groups. I like it

**Comment by SurfaceS** [comment]
Did we need to keep the old browser files ??

Also, if you ban an IP for a renderer, it will not be able to reach the server, so you will not fill the allowed renderer field.
I will back with a better solution.

**Comment by SubJunk** [comment]
I think the old browser files can be removed if you agree

I look forward to seeing your better solution

**Comment by SubJunk** [comment]
Goal 1 is done thanks to @SurfaceS 
Do you want to work on number 2 as well? Otherwise I can try

**Comment by SurfaceS** [comment]
I will be able to look at this only in a week.

**Comment by SubJunk** [comment]
@SurfaceS ok, I will focus on continuing my HDR and transcoding/muxing fixes so you can do that

**Comment by SurfaceS** [comment]
@SubJunk 
After looking at `Show and hide folders based on renderers`
I tried some way to do this, and I end with :

**Easy part :**
Set the rigth on shared:
Add a member `AuthorizedGroups` to `SharedContent` that keep a `List<Integer>` (group ids).
If empty, all groups are allowed.

Set the account on renderer :
Add a new key `UserId` on `RendererConfiguration` that keep the user id (integer).

Add a member `Account` to `Renderer` that keep the account linked to the renderer device, filled by the `RendererConfiguration` or logged account for `WebRenderer`.
If empty, set to a fake account (0) that allow only `SharedContent` with empty authorized groups.

**Hard part :**
UMS was coded in the way that all renderers share everything (shares, global repo ids, status, etc).

For the DLNAResource part :

`DLNAResource` is a lot messy.
`
DLNAMediaInfo` as well (should have nothing to do with DLNA nor renderer or account)
Should not reside under DLNA things.
Should not have user related things (Status of playcount, etc) -> `MediaStatus`.
It should not be video related but container related, then it can contain `MediaVideo`, `MediaAudio`, `MediaChapter`, `MediaImage`, and so on.
Refactor `DLNAMediaInfo`  -> `MediaInfo`
Is used by all renderer, so updating it should be replicated to every renderer.
So, should use a static Object Array that keep `MediaInfo` for all the `DLNAResource`.

Added class `MediaStatus` that keep the status -> 
Is used by multiple renderer sharing the same user, so updating it should be replicated to same user renderers.
So, should use a static Object Array that keep `MediaStatus` for all the `DLNAResource` by user id.
This will allow to track status based on user.

DLNAResource is renderer aware, so it should be created for each renderer under its own RootFolder.


But first I need to clean some things.

**Comment by SubJunk** [comment]
Cool, those all seem like good changes and will make the code more readable. Nice work

**Comment by SubJunk** [comment]
The code changes for v14 have been merged. I think there are some Knowledge Base updates that should happen before the release, this article for example is out of date for this version https://github.com/UniversalMediaServer/knowledge-base/blob/main/docs/configuration/security-and-privacy.md

Also @SurfaceS I wonder if we should try reverting the change I suggest at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4037#issuecomment-1937459231 and you implemented in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4037/commits/3c90365d01e42bb4c5d20b6084178bdc3167df01
I think browsing got slower after that change, and it did not fix the problem we thought it would. What do you think?

**Comment by SurfaceS** [comment]
> Also @SurfaceS I wonder if we should try reverting the change I suggest at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4037#issuecomment-1937459231 and you implemented in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/3c90365d01e42bb4c5d20b6084178bdc3167df01
I think browsing got slower after that change, and it did not fix the problem we thought it would. What do you think?

@SubJunk I think that you should have a look on
- #4635 with review/comments
- #4638
- #4639 with comments
- #4640
- #4643

**Comment by SubJunk** [comment]
I think Nadahar made a good point that we shouldn't do IO concurrently except when they are stored on SSD, but the retrievals should be concurrent. In general I like having smaller PRs with a tightly defined scope too so I like those 3 separate ones in theory.
That's just a conceptual reply without looking at the specific code changes.

**Comment by SubJunk** [comment]
I have updated the Knowledge Base for v14 now, so I will do the v14 release. We can continue to improve performance in future releases

**Comment by SubJunk** [comment]
This is released!
