### ISSUE TITLE
Resume play a transcode movie on XBOX360 fail?

### ISSUE THREAD

**Issue by harveyhu2012** [UniversalMediaServer/UniversalMediaServer#399]
a minor problem: 
resume play a transcode movie on XBOX360 fail, but play from start is ok.

if i comment `this.timeseek = params.timeseek;` , resume will be ok.

just like this:

```
public class BufferedOutputFileImpl extends OutputStream implements BufferedOutputFile
....
public BufferedOutputFileImpl(OutputParams params) {
        this.minMemorySize = (int) (1048576 * params.minBufferSize);
        this.maxMemorySize = (int) (1048576 * params.maxBufferSize);
....
        this.bufferOverflowWarning = this.maxMemorySize - margin;
        this.secondread_minsize = params.secondread_minsize;
        //this.timeseek = params.timeseek; // disable the time seek, resume play will be ok!
        this.timeend = params.timeend;
        this.shiftScr = params.shift_scr;
        this.hidebuffer = params.hidebuffer;
        this.cleanup = params.cleanup;
```

i don't understand all the codes, but i think we have used `-ss` param in MEncoder and FFMpeg, why we need add timeseek at here?

if this is a problem only on XBOX 360, how to modify the code?

**Comment by Sami32** [comment]
@harveyhu2012 Did the latest UMS version solved this issue ?
If not, post your log following these instructions http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
@Nadahar  Could this issue be closed ?

**Comment by polygirl** [comment]
Hi @harveyhu2012 it's been some time since you've reported this issue.  We presume this has now been resolved for you, but if it's still an issue please feel free to reopen.
