### ISSUE TITLE
нет элементов для отображения

### ISSUE THREAD

**Issue by hwlloleg** [UniversalMediaServer/UniversalMediaServer#3998]
# Howпосле обновления на версию 13.4.1  появилась ошибка нет элементов для отображения и сервер не работает. телевизор Sony. в чем проблема??

**Comment by SurfaceS** [comment]
Not understandable.

**Comment by Mik-S-UMS** [comment]
Translating it reads

> How after updating to version 13.4.1 there is an error no items to display and the server is down. Sony TV. what is the problem??

But would not be able to help without logs.
