### ISSUE TITLE
Avaible when device is connected.

### ISSUE THREAD

**Issue by Arkadietz** [UniversalMediaServer/UniversalMediaServer#401]
Hello! Today i faced with a new unpleasant problem. When i trying to get in from TV it says "Avaible, when device is connected." I've tried to restart the network, to restart the computer, but the problem is still on face. Will be glad to be fixed this. Also i am using the latest version. All seems fine but i can't get in the DLNA server...

Here's the debug log: http://pastebin.com/TdXAJGWV
Here are the pics:
http://imgbox.com/7UdUHSzi
http://imgbox.com/eFkpayOm

**Comment by Sami32** [comment]
@Arkadietz So since then, did the latest UMS version solved this issue ?
If not could, please post a new log, since the old one is not accessible anymore.

**Comment by polygirl** [comment]
Hi @Arkadietz it's been some time since you reported this, and you didn't respond to further requests for information so we're closing this issue but feel free to reopen it with full trace logs if needed.
