### ISSUE TITLE
Subs are too small

### ISSUE THREAD

**Issue by Arkadietz** [UniversalMediaServer/UniversalMediaServer#402]
Hello! I've tried the latest version using UMSBuilder-1.8.0. What i can say? With the same settings from  4.1.2 now subs are small even too small. I don't know what exactly is changed in the code but it's not for good!

**Comment by Sami32** [comment]
@Arkadietz @valib Did the latest UMS version solved this issue ?
If not, please post your log following these instructions: http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
