### ISSUE TITLE
broken audio info

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#4029]
Hi guys,

the current main branch seem not to deliver detailed audio metadata. Looks like the table `AUDIOTRACKS` is empty (after migration). Creating a new database leaves `AUDIOTRACKS` also empty. `AUDIO_METADATA` is filled though.

**Comment by SurfaceS** [comment]
fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/2c3a7c5d37f3a94e1865e399bf17db7bc84f6f4d

Thanks to found it.

**Comment by SurfaceS** [comment]
I think that was for video file audiotrack language to allow same file and id with different lang ? IDK

**Comment by ik666** [comment]
I don't mind the LANG field! I think indexes have to match the query to be taken into account. 
- One query has as WHERE parameter `fileid` and will use the index generated by the FOREIGN_KEY constraint.
- The other query stepping through the audiotracks uses `fileid` and `ID` and will most likely not match the PRIMARY_KEY constraint because the index spans over 3 fields (fileid, id, lang).

I proposed to change 
```
CONSTRAINT + TABLE_NAME + PK_MARKER + PRIMARY_KEY + "(" + COL_FILEID + COMMA + COL_ID + COMMA + COL_LANG + ")" + COMMA +
```
into
```
CONSTRAINT + TABLE_NAME + PK_MARKER + PRIMARY_KEY + "(" + COL_FILEID + COMMA + COL_ID + ")" + COMMA +
```
