### ISSUE TITLE
FFMPEG

### ISSUE THREAD

**Issue by RoStarMC** [UniversalMediaServer/UniversalMediaServer#4033]
Hello. Pls change the ffmpeg.exe fron the bin folder with a newer one because the movie goes frame by frame and the processor goes crazy, that is, it consumes a lot of resources, after I replaced the executable with a newer one it worked perfectly. ( https://github.com/GyanD/codexffmpeg/releases/download/2023-08-17-git-9ae4863cc5/ffmpeg-2023-08-17-git-9ae4863cc5-full_build.7z ).  I hope it was useful information. Good luck in the future!

**Comment by SubJunk** [comment]
@RoStarMC thanks for reporting this, I will update it

**Comment by RoStarMC** [comment]
Thank you

**Comment by SubJunk** [comment]
@RoStarMC which version of UMS are you using?

**Comment by SubJunk** [comment]
@RoStarMC thank you for your reply. We already updated FFmpeg to `2023-07-02-git-50f34172e0-essentials` in 13.6.0 so I think that should fix this. Please let us know if it still needs to be a newer one.
