### ISSUE TITLE
Since 4.1.3 all folder names end with " | JPG"

### ISSUE THREAD

**Issue by netx123** [UniversalMediaServer/UniversalMediaServer#404]
Since upgrading to UMS 4.1.3 all folder names are being displayed with an additional " | JPG" at the end of the name.

This makes browsing folders look a little ugly, for example in 4.1.2 folders would look like:
 Films
 --> Science Fiction
 --> Action

In 4.1.3 folders now show as:
 Films | JPG
 --> Science Fiction | JPG
 --> Action | JPG

I don't know if this is linked to the new blue folder icon that was introduced in 4.1.3?

**Comment by Sami32** [comment]
@SubJunk Could this issue be considered fixed ?
It's look like you did already add Apple renderer to the Sony BraviaW.
I close it, but feel free to reopen it if need.
