### ISSUE TITLE
Remove Netty

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4058]
We have a long history of trying to update from Netty v3 to v4.

The last attempt, we tried updating to `4.1.50` and it broke browsing for some renderers as detailed in this issue: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2105
So we reverted it in this PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2107

I had hoped we didn't have to touch this again, but last month there were a lot of vulnerabilities disclosed that affect Netty v3:
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/24
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/29
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/27
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/30
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/28
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/26
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/25
https://github.com/UniversalMediaServer/UniversalMediaServer/security/dependabot/23

**Comment by SurfaceS** [comment]
As I understand, Netty was used to replace the first old (removed now) sockets server, to serve HTTP requests.
It's an socket nio server, so low level (com.sun.net.httpserver is high level).
Low level was important as upnp is adding some methods (UNSUBSCRIBE, M-SEARCH, etc) that high level HTTP implementation does not handle.
Also, high level HTTP implementation often strictly follow HTTP things, so you cannot, for example, set a transfer size that not match what you send.

I tried few year ago to upgrade to Netty v4 without success (it was working, but transcoded stream fails).

Did you tried the JavaHttpServer ?
Maybe we can switch to it if it works well for all (or fix if not) ?.

Or switch to Apache Http Core 5 server ?

**Comment by SubJunk** [comment]
I'll do some testing with JavaHttpServer

**Comment by SubJunk** [comment]
Should I do `JUPnP+ (Java)` or `JUPnP (Java)`?

**Comment by SurfaceS** [comment]
as the default is `JUPnP (Netty)`, I think it is better to start with `JUPnP (Java)`.

JUPnP+ add ContentDirectory service inside JUPnP.

On V14, it's also create DIDL from brand new classes that handle ContentDirectory V4 things, but I need to finish it (DLNA).

The final long term goal could be to use all UPnP things under JUPnP, served by the common JDK HTTPServer, as it use nio now.

UPnP things -> JUPnP services.
Media things (thumbnails, streams, media infos, etc) -> javahttpserver.

Then we will have only one "engine" to manage with, and things will be well splitted between the upnp services and the media server itself.
