### ISSUE TITLE
SoundCloud4PS3 Plugin no longer functions

### ISSUE THREAD

**Issue by sniper-x** [UniversalMediaServer/UniversalMediaServer#406]
It appears that the SoundCloud4PS3 can no longer obtain an OAUTH key or otherwise authorize to SoundCloud.

Can someone please simply update the OAUTH routine to the latest request format or something?
Based on it's history, the rest of the plugin seem like it will work otherwise

**Comment by Sami32** [comment]
@sniper-x Did you solved your issue since then ? It's not an UMS issue but a plugin issue.

**EDIT:** This plugin is not anymore developed.
http://www.ps3mediaserver.org/forum/viewtopic.php?f=12&t=6583
https://github.com/dradovic/SoundCloud4PS3/issues/3

**Comment by sniper-x** [comment]
No resolution of course.

 

I knew it was a plugin issue, and since it’s not developed anymore – I abandoned it.
