### ISSUE TITLE
Movie with total time 0

### ISSUE THREAD

**Issue by u3712** [UniversalMediaServer/UniversalMediaServer#4060]
I have several series of movies, when watching the series sequentially, sometimes a movie is loaded with a time of 0-0. At the same time, the film is shown nominally, in its entirety. If you exit this movie and press play again, it will open normally, with the correct length. This bug has occurred before and may have been fixed now. I describe only because today I saw something similar. In the usual directory is the file "Spirited_Away.m4v" 4.7Gb. In UMS, its length is completely wrong (976kb):
![01](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/59c50baf-31c3-4ad0-a087-c5bc1ca74635)

When I open it, I get the time 0-0. The film itself plays normally, but some of the functions are gone - there is no choice of voice acting language and subtitles.
![02](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/2d2f58a8-d01b-4ef2-84a0-cc43665d8f5f)
Copying the file to another location or copying+renaming it to "123.avi" doesn't change anything.

If the same file is opened on a computer and the playback stream is directed to the same TV, then everything works correctly:
![03](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/81e0b5e8-3d84-4cd7-be75-f898be4cdac1)

![04](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/cbde7d87-9ea5-472a-81d8-7c8955ee98da)

[ums_dbg_2023-09-05-23-42.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12528257/ums_dbg_2023-09-05-23-42.zip)

**Comment by SubJunk** [comment]
Thanks for reporting this. It looks like it is transcoding that file when it doesn't need to. Can you please replace your renderer file `C:\Program Files (x86)\Universal Media Server\renderers\Samsung-5300series.conf` with the attached one? 
[Samsung-5300series.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12545081/Samsung-5300series.zip)

**Comment by u3712** [comment]
Alas, it got worse.
When you start the movie shows 0-0, as described. The catalog on this film does not show its volume in kilobytes - this part simply does not exist. "Date", "mpeg format" and nothing else. The line "file size xx kb" disappeared.
On the next file, everything remained fine.

**Comment by u3712** [comment]
Guilty.
After a full reboot, everything was fixed and began to work normally. Thank you!
Added.
Then he went to watch on another TV - UE32H6200. With the new file, everything is the same 0-0. Perhaps there is another configuration file?

**Comment by SubJunk** [comment]
@u3712 cool that it worked! I can fix it for the other TV if you give logs again

**Comment by u3712** [comment]
Thank you, I corrected it myself, similar to the 5300 series. The problem has also been fixed.
You see, this bug does not affect my Samsung TV model, but many models. It needs to be changed everywhere, on many types of TVs.

**Comment by u3712** [comment]
The configuration file is new, the TV is the same (Samsung 5300). Movie "Countdown.2019.D.BDRip.72Op.mkv" 4.6Gb.
The defect is the same, it shows the film time 1 sec - 1 sec. At the beginning of the topic there was 0 sec - 0 sec.
Probably it’s not worth giving the logs?
![103](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/5d58b0e1-d958-41a2-acb8-0fb9a0a7dbe8)
The description of the film indicates the mpeg format and does not indicate the file length at all.
![104](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/2ad417e5-49ee-4d21-b833-2c30514297ce)
![105](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/b4a3fc03-e459-4733-8157-55415e761ac9)

**Comment by u3712** [comment]
I installed the old configuration file for Samsung 5300 - the message “File size 976.56 kb” appeared on the Countdown movie. Then I installed it again - a new configuration file - the line about the file size disappeared. For any configuration file on the film it says: mpeg format.

**Comment by SubJunk** [comment]
There are two problems here. The first problem which is fixed now, is that UMS did not recognize that your TV supports subtitles inside MP4 files, so it would try to transcode them.

The other problem is that the TV does not know how long a video is when it is going to be transcoded. We will need to do more testing to try to fix that. Here's another config to try which will try to transcode to a different format

[Samsung-5300series.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12623662/Samsung-5300series.zip)

**Comment by u3712** [comment]
With the new config file:
Countdown.2019.D.BDRip.72Op.mkv - on the directory there is information "vnd.apple.mpegurl format". The TV refuses to show the movie, the message is "The selected file is currently not supported."
Spirited_Away.m4v - didn't notice any problems.
I didn't notice any problems with other films.

Information on the file Countdown.2019.D.BDRip.72Op.mkv 
[mediainfo.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12639798/mediainfo.zip)

**Comment by SubJunk** [comment]
Can you please test this version? https://www.universalmediaserver.com/uploads/UMS-4060-2.exe

**Comment by u3712** [comment]
Installed UMS-4060-2, rebooted the computer. The UMS DLNA server did not appear.
Features of the installation - the process took about 2 times longer than usual. After installation/launch, the UMS settings window usually opens in the browser. When installing this file, this page was not created.
I have two Samsung TVs, the UMS server did not appear on either the 5300 model or the 6200 model.
As an additional measure, I tried to open UMS (icon-settings-old) and click “Restart server” on it. After that, UMS appeared on the TV in a few seconds. This version has not appeared.
![90](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/39446534/bf1ccb8a-64c7-4eb7-a782-675d4224e135)
[ums_dbg_2023-09-20-22-10.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12676786/ums_dbg_2023-09-20-22-10.zip)

**Comment by SubJunk** [comment]
Closing this because of the other comment https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4034#issuecomment-1727578952
