### ISSUE TITLE
using wrong network card even though specified which one to use

### ISSUE THREAD

**Issue by d3xt3r01** [UniversalMediaServer/UniversalMediaServer#407]
I see this when doing ./UMS.sh at first start.

INFO  2014-10-25 13:15:54.368 [main] Using address /192.168.28.1 found on network interface: name:vboxnet0 (vboxnet0)

Even though I have this in UMS.conf
network_interface = eno1
skip_network_interfaces = vboxnet0
hostname = 192.168.1.95

If I then go to ~/.config/UMS/UMS.conf and add the same lines I had in the UMS.conf when untar-ing the archive ..all is ok.

**Comment by Sami32** [comment]
@d3xt3r01 Did the latest UMS version solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
Hi @d3xt3r01 it's been some time since you reported this issue and you haven't left further information as requested so we're closing this issue. Please feel free to reopen with full TRACE logs if needed.
