### ISSUE TITLE
Background for subtitles

### ISSUE THREAD

**Issue by Arkadietz** [UniversalMediaServer/UniversalMediaServer#408]
Hello. I think will be nice if there is a background (black) for subtitles. When u have some bright picture you barely can see the subtitles. Also if this future is like an option much better.

**Comment by Sami32** [comment]
@Arkadietz You can now choice the font size and type for your subtitles or color and many different other styles with ASS subtitles in the "Subtitles Settings" tab inside the "Transcoding Settings" tab.
Hoping that you will enjoy nice and clear subtitles from UMS ;-)

@valib Feel free to re-open it.
