### ISSUE TITLE
Discoverd a couple of bugs in 13.7.0

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4082]
I installed 13.7.0 yesterday (using Subjunk's build script) but found that nothing would play that needed transcoding on my PS4.

Looking though the logs I saw it was now using tsMuxeR for some reason and giving broken pipe errors. I guessed it had something to do with the "**Remux videos with tsMuxeR when possible instead of transcoding**" setting. This should normally have no effect as the videos were h265 so needed to be transcoded not remuxed.

The other bug was when I went to change that setting in web settings and hit save. The notification came up with a spinning icon saying saving, but it did nothing and did not go away. Someone else mentioned this on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?p=47797#p47797) a day or so earlier too. It is also not related to that one option as nothing will save.

Editing UMS.conf manually (or using the old GUI) and setting `ffmpeg_mux_tsmuxer_compatible =false` allowed the videos to play properly. 

[ums_dbg_2023-09-17-01-26.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12641799/ums_dbg_2023-09-17-01-26.zip)

**Comment by SurfaceS** [comment]
> The other bug was when I went to change that setting in web settings and hit save. The notification came up with a spinning icon saying saving, but it did nothing and did not go away. Someone else mentioned this on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?p=47797#p47797) a day or so earlier too. It is also not related to that one option as nothing will save.

I fixed that in v14

**Comment by SubJunk** [comment]
@Mik-S-UMS thanks for reporting this, I have a fix for the tsMuxeR problem locally too, I will push it soon

**Comment by SubJunk** [comment]
@Mik-S-UMS that fix is merged so you should be able to build and test it, can you let me know if it worked?

**Comment by Mik-S-UMS** [comment]
That worked. I guess the saving problem was not merged but I know it has been fixed for V14. 
Is there a way to have that script build V14 so I can have a sneak peek?

**Comment by SubJunk** [comment]
@Mik-S-UMS cool thanks for confirming!
If you go into the script and replace `main` with `v14` it should work, maybe make a new folder for that one so you have both branches to try.
Also before you run v14, you should make a backup of `C:\ProgramData\UMS` because v14 will modify the database. Then you can switch between the two UMS data folders if you need to go back to v13

**Comment by SurfaceS** [comment]
saving problem was not merged
#4090 fix that for v13
