### ISSUE TITLE
Marking media played entirely, UMS 13.6.0

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4083]
Hello,
The problem of media not being fully marked has returned, a bug that I thought was resolved until today, no episodes have been marked. **final decision: not legitimate playback**

I am attaching the logs of the unmarked episodes fully played.

UMS 13.6.0

Fully Played feature logging:
duration: 2957.792
getLastStartPosition: 2957.7919945103695
getStartTime: 1695152641461
getLastStartSystemTime: 1.695155569981E12
elapsed: 2961.7949945103696
minimum play time needed: 2721.16864
final decision: not legitimate playback

![UMS](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/a7e9831c-43bb-4f92-9725-e05ae52a2a72)

[episodes 1.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12666897/episodes.1.zip)
[episodes 2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12666898/episodes.2.zip)
[episodes 3.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12666899/episodes.3.zip)

**Comment by SubJunk** [comment]
The fix for this problem is in version 13.7.0+, and in that test version I uploaded on the old issue
