### ISSUE TITLE
PS3 Does not find UMS

### ISSUE THREAD

**Issue by MissValeska** [UniversalMediaServer/UniversalMediaServer#409]
I am on the same wifi network and I tell my PS3 to search for a media server in the video section just like I did with my PS3 media server years ago, And it doesn't find it. I will provide any additional information needed, Thank you for reading.

**Comment by Sami32** [comment]
@MissValeska Did the latest UMS version solved this issue ?
I guess yes, no news good news...

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
Hi @MissValeska it's been some time since you opened this issue and as we haven't heard back with further information we presume this is resolved for you so we're closing.  Please feel free to reopen with the requested TRACE logs if needed.
