### ISSUE TITLE
Please provide patch level updates for security vulnerabilities to ensure users safety

### ISSUE THREAD

**Issue by bluepuma77** [UniversalMediaServer/UniversalMediaServer#4094]
You make the current release available via your Patreon page, and it will be available to everyone when the next release happens.

That's totally fair for new features and maybe bug fixes, but you shouldn't gamble with the safety of your users.

Please always release patch versions to [fix security vulnerabilities](https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/13.7.0), like a 13.6.1 according to [Semantic Versioning](https://semver.org).

**Comment by SubJunk** [comment]
@bluepuma77 thank you for the suggestion. I had a think about it. We are open source and users are always able to build the latest version for themselves, and we provide detailed instructions about how to do that on major operating systems. The downloads are provided for convenience.

You do make a good point, but I think users who are especially motivated by anything in the changelog can either build it for themselves for free, or pay $1 for access to the compiled binaries

**Comment by bluepuma77** [comment]
@SubJunk Most users will just use the free version, which you continuously provide with known security vulnerabilities.

**Comment by SubJunk** [comment]
If there was a critical priority vulnerability fix I might do a patch release like you said. In this case it wasn’t. It was a reference to security bumps in the bundled Java runtime, which again any user is free to bump for themselves without waiting for a download.

I do like the approach you have suggested and you have convinced me to do that in the future for serious vulnerability patches.
