### ISSUE TITLE
mygrid repository unreliable

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#411]
For over a week now I've had intermittent problems with connecting to mygrid.org.uk when compiling UMS. For me it doesn't work most of the time.
Does anyone else have this issue? Is there a better site we can tell maven to use for thumbnailator?

**Comment by mfulgo** [comment]
The other week, I actually emailed the maintainer for `imageio` (@stain) who said he'd find some time to put it on Maven Central.  I think that's the only thing getting downloaded from there, so once that happens, you should be able to drop the myGrid repo from the pom.

**Comment by SubJunk** [comment]
@mfulgo great!

**Comment by Jensaarai** [comment]
I've been trying to build and also ran into this issue. I found this comment with an alternate URL, which seems to work :) http://stackoverflow.com/a/23640746

I made a pull request if this is a change you guys would like to keep https://github.com/UniversalMediaServer/UniversalMediaServer/pull/560

**Comment by SubJunk** [comment]
@Jensaarai thanks!
