### ISSUE TITLE
Pigasus.conf issue.

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4116]
I have seen several times (recent one [here](https://www.universalmediaserver.com/forum/viewtopic.php?t=15874)) that Pigasus.conf is being used over the right conf for some renderers because it is only matching "Android" in  `UserAgentSearch`
It also has "Hanging Hat Studios" in `UpnpDetailsSearch` but I don't think this is being used.

I can't remember but I think it used to be the case where both `UserAgentSearch` **and** `UpnpDetailsSearch` had to match and not one **or** the other.

This might also explain why my phone started appearing in UMS as another TV as it is a Samsung and was using the CD conf.

Is this intentional or a bug?

If it is working as intended then I think the pigasus.conf can be changed to a narrower match to prevent clashes.

**Comment by SubJunk** [comment]
I think it has always been an OR match on those, but I can see the `LoadingPriority` is too high here so I have changed it in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4118. I hope that will fix it

**Comment by Mik-S-UMS** [comment]
I think when that conf was made for the VR feature the author assumed it was AND. 

There are also a few other confs for android that use "Android" in `UserAgentSearch` so that must be why this was given a higher priority. This could stop the valid matching for users of pigasus though.

Might be better to remove "Android" and just use "Hanging Hat Studios" if it uses OR. I tried to find any logs on the forum from users of pigasus to get the headers but could not find any so don't know what would be a better match.

I think it would be better if AND was used when both `UserAgentSearch` and `UpnpDetailsSearch` are defined in the conf to get more accurate matches and less false positives. This should help with things like the Samsung-NotCD.conf being used instead of the Samsung-CD.conf for newer TVs, which is also another fairly common thing I see. And there is also the ability for the user to change the device name so could use the `modelName` in `UpnpDetailsSearch` and have something more generic in `UserAgentSearch` to match instead.

Another solution is to have it so if both `UserAgentSearch` AND `UpnpDetailsSearch` match to one conf then automatically give that a higher priority over anything that just matches `UserAgentSearch` OR `UpnpDetailsSearch` instead of needing to set the `LoadingPriority` in the conf.

**Comment by SubJunk** [comment]
Ok, I have removed Android in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4121
