### ISSUE TITLE
Samsung TV #4114 and #4039 bug Solved

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4119]
Hello, following post #4114 and #4039 I carried out other tests only with the original renderers files Samsung-CD.zip version 13.5.0 and the videos which show me the incorrect time and codec not supported charge,
I noticed that these videos were encoded at 50 fps/s, I re-encoded them with exactly the original codecs (EAC3) but at 29.97 fps/s, after that all the videos were played correctly, the times returned correct.
The new Samsung-CD file (modified) which will be integrated soon in version 13.7.0 contains the incorrect times bug unlike the original one which is in version 13.5.0
I was able to get the video to work correctly in EAC3 (Dolby Digital Plus) with the original 13.5.0 file, I just had to re-encode the video from 50fps/s --> 29.97fps/s , Samsung TV supports EAC3 (Dolby Digital Plus) without transcoding with 29.97fps/s MAX

Can you leave the original Samsung-CD.zip file in the next 13.7.0 update ?

hoping that this post could help other people who encounter these problems.

thank you have a nice day.

Attached in .zip Renderers from the origin:

[Samsung-CD (Origin).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12838049/Samsung-CD.Origin.zip)

**Comment by SubJunk** [comment]
@Fredo1650 hi, that's a good discovery. Which file format did you mux the video to? That's strange because the manual for the TV says it only supports DD+ (EAC3) in TS containers, so it would be good to know which container really supports EAC3 https://downloadcenter.samsung.com/content/UM/201112/20111208185713733/Web_GSDVBEUA_Eng.pdf

**Comment by Fredo1650** [comment]
Hello,
Only Indiana Jones (Images 1 and 2) works correctly, the times are correct it is in eAC3 Audio, the other 3 videos (Fear The Walking Dead) do not work, incorrect times or codec not supported, the only difference it was at 50ip/s
1. 50ip/s --> Unsupported codec or incorrect timing
2. 30ip/s --> the video starts but the time was incorrect
3. 29.97ip/s or lower --> video starts + correct time
Test with Samsung-CD (Origin).zip only

Can we keep the Samsung-CD (Origin).zip file in the next UMS update? because it works correctly and the times are correct, it's just that the video must be less than 29.97 ips/s.

thank you.

![Indiana Jones](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/e65cbcb9-4dfd-4c72-86d2-222cf090c476)
![Indiana Jones](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/6f98c260-5780-4871-b809-a95292abc4fa)
![Fear The Walking Dead S05E01](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/6bf0a2d4-bada-47f2-b48b-dbec090a54b2)
![Fear The Walking Dead S05E02](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/2fd54580-452d-4ab8-8bb9-5ca7c9122245)
![Fear The Walking Dead S07E01](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/0723522b-0ca7-4e75-9bd0-528153f8f0a4)

**Comment by Fredo1650** [comment]
30ips/s OK
![Fear The Walking Dead S07E01](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/e7b2c496-e72c-42b4-9296-62d9ee0463a5)
![Fear The Walking Dead S07E01 (3)](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/dc29a663-7684-40e9-897f-a3c0ed07e514)

**Comment by SubJunk** [comment]
Ok cool, so we have proven that EAC3 is supported inside MKV files for that TV. That's good. Let's change the config to this:

```
#----------------------------------------------------------------------------
# Profile for Samsung C/D series TVs and Blu-ray players with AllShare DLNA.
# See DefaultRenderer.conf for descriptions of all the available options.
# Version: 1.4.4 (modified)
#

RendererName = Samsung C/D Series
RendererIcon = samsung-tv.png

# ============================================================================
# This renderer has sent the following string/s:
#
# User-Agent: SEC_HHP_[HT]D5500/1.0
# User-Agent: SEC_HHP_[TV]UE32D5000/1.0
# User-Agent: SEC_HHP_[TV]PS51D6900/1.0
# User-Agent: DLNADOC/1.50 SEC_HHP_[TV]UE32D5000/1.0
# User-Agent: DLNADOC/1.50 SEC_HHP_[TV]UN55D6050/1.0
# User-Agent: SEC_HHP_TV-37C5100/1.0
# User-Agent: SEC_HHP_HTS-C5500/1.0
# User-Agent: SEC_HHP_TV-50C7000/1.0
# User-Agent: SEC_HHP_TV-40C610/1.0
# User-Agent: SEC_HHP_[TV]PS64D8000/1.0
# User-Agent: SEC_HHP_[TV]UA55D8000/1.0
# User-Agent: SEC_HHP_[TV]PS51D8000/1.0
# User-Agent: SEC_HHP_BD-C5500/1.0
# User-Agent: SEC_HHP_[BD]D5300/1.0
#
# Note: if the device name "[TV]PS51D6900" has been edited by the user via the
# TV menu it will likely be misidentified as E and later series
# (see SamsungAllShare.conf), e.g.:
# User-Agent: DLNADOC/1.50 SEC_HHP_ Family TV/1.0
# User-Agent: SEC_HHP_ Family TV/1.0
# ============================================================================
#

UserAgentSearch = SEC_HHP.*(TV|HT|BD).*[CD]S?\d{3}\d?/
UpnpDetailsSearch = [CD]S?\d{3}\d? , (Samsung|AllShare)

TranscodeVideo = MPEGTS-H264-AC3
MuxDTSToMpeg = true
MaxVideoBitrateMbps = 25
SubtitleHttpHeader = CaptionInfo.sec
PrependTrackNumbers = true
CharMap = / :

# Supported video formats:
Supported = f:avi       a:ac3|adpcm|dts|lpcm|mp3         m:video/avi
Supported = f:flv       a:ac3|adpcm|dts|lpcm|mp3         m:video/mp4
Supported = f:mkv       a:ac3|adpcm|dts|eac3|lpcm|mp3    m:video/x-mkv
Supported = f:mov                                        m:video/quicktime
Supported = f:mp4       a:aac|adpcm|mp3                  m:video/mp4
Supported = f:mpegps    a:aac|ac3|lpcm                   m:video/mpeg
Supported = f:mpegts    a:aac|ac3|eac3|he-aac|mp3        m:video/mpeg

# Supported audio formats:
Supported = f:mp3   m:audio/mpeg
Supported = f:wav   m:audio/L16

# Supported subtitles formats:
SupportedExternalSubtitlesFormats = SUBRIP,ASS,TEXT,MICRODVD,WEBVTT,SAMI
SupportedInternalSubtitlesFormats = SUBRIP,ASS,TEXT,MICRODVD,WEBVTT,SAMI
```

**Comment by Fredo1650** [comment]
Hello, I have done a lot of testing:
Samsung-CD (modified) Pictures 1/2/3/7
1. S06E16 Video playback OK / Incorrect time
2. S07E02 Video playback OK / Incorrect time
3. S06E15 Video playback OK / Incorrect time / No sound / Video works with Windows Media Player to TV with sound
4. S04E16 Video playback OK / Correct time
5. Re-encoding S06E15 Video playback OK / Incorrect time / Sound OK (Picture 13)

Samsung-CD (Origin) Pictures 4/5/6/7
1. S06E16 Video playback OK / Correct time
2. S07E02 Video playback OK / Correct time
3. S06E15 Video playback OK / Correct time / No sound / Video works with Windows Media Player to TV with sound
4. S04E16 Video playback OK / Correct time
5. Re-encoding S06E15 Video playback OK / Correct time / Sound OK (Picture 13) 

I also noticed when I completely deleted the line a:ac3|adpcm|dts|eac3|lpcm|mp3 the times came back correct like the original file
Supported = f:mkv                                          m:video/x-mkv

Which is curious, the S04E16 video works perfectly well and has exactly the same codec as S06E15, the sound of which no longer works in all cases (Unless I send the video via Windows Media Player to the TV, Picture 12)

Conclusion of the test the best would be to keep the original file less bug over time and to ensure that the video does not exceed 30fps/s because above in all cases the video no longer works
[Samsung-CD (Origin).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12841238/Samsung-CD.Origin.zip)


![20231008_154455](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/a10a87a8-900c-454a-ab3c-cdbbbb2d464e)
![20231008_154530](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/f980e9a2-1c46-4ce0-a8f2-913540c8c434)
![20231008_165113](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/d34912d1-97a2-4591-9b91-6da1650adf33)
![20231008_153850](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/4948aee8-d060-494d-9f39-85a4781f6ddb)
![20231008_153934](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/5ee52f13-5ebf-45d8-96bc-08543071f185)
![20231008_164531](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/c983c6ff-910e-4d86-bb94-616946251937)
![20231008_170300](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/eb6a6664-0250-4818-9260-56ef55bcea19)
![Fear The Walking Dead S06E16 FINAL](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/d2ece0c3-77ab-4182-83fa-46b02cfc73dc)
![Fear The Walking Dead S07E02](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/0db146be-386d-49c4-bb88-f4872f0a4d1c)
![Fear The Walking Dead S06E15](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/3e8802e4-c3b2-48ec-89c7-10262d13aecf)
![Fear The Walking Dead S04E16 FINAL](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/8f5d9541-5ae3-457f-a295-df8d650e3666)
![Windows Media](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/fb5850ec-732e-44fe-9fed-b2f4a56cf3cc)
![Re-encoding Fear The Walking Dead S06E15](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/2660201a-ead4-4760-8a25-46d77c5a2b7a)

**Comment by SubJunk** [comment]
Ok I'll revert the file since it seems easier for now
