### ISSUE TITLE
Double iTunes entries on Xbox One

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#412]
@UniversalMediaServer/developers we've had several reports of double entries of songs on Xbox One when using iTunes support, can someone with an Xbox One have a look?

**Comment by Sami32** [comment]
http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=2387&p=12759&hilit=Double+iTunes+Xbox+One#p12759
