### ISSUE TITLE
UMS for Java 7 and Java 8 will not execute

### ISSUE THREAD

**Issue by WayfairingStranger** [UniversalMediaServer/UniversalMediaServer#413]
I am running Mountain Lion, with Java 8 installed.  When I try to execute either version I get the following message:
![screen shot 2014-11-02 at 4 37 04 pm](https://cloud.githubusercontent.com/assets/9520074/4877211/364a9952-62e1-11e4-91eb-4269e2cc1f5b.png)
 or, 
![screen shot 2014-11-02 at 4 38 01 pm](https://cloud.githubusercontent.com/assets/9520074/4877212/3f837d90-62e1-11e4-912f-1b457948d439.png)

This error does not occur on the Java 6 version.  And in case you were wondering....
![screen shot 2014-11-02 at 4 42 17 pm](https://cloud.githubusercontent.com/assets/9520074/4877226/930fc5b8-62e1-11e4-8d99-108da489a7bf.png)

**Comment by WayfairingStranger** [comment]
*|MC:SUBJECT|*

    

 img { width:100%; }



        
    
        
            
                
                    
                        
                        
                            
                                
                                    
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
    
            
                
                    
                        
                            


                                        


                            
                        
                    
                
            
    

                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                    
                                
                            
                            
                                
                                    
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
    
        
            

                
                    

                        




Hi UniversalMediaServer/UniversalMediaServer,


Your friend Brent wants you to try UnoTelly!



You'll get 8 days of free geo-unlock access. UnoTelly unlocks geo-blocked streaming channels from all over the world like different regions of Netflix, Hulu Plus, and BBC iPlayer.



Try now - it only takes 30 seconds!




Sign up and claim your free access




Thanks!

-The UnoTelly team





                        
                    
                

            
        
    

    
        
            
                
                    
                        
                            
                        
                    
                
            
        
    

                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                    
                                
                            
                            
                                
                                    
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    



                        

                        
                    

                        
                        If you prefer not to receive invites from UnoTelly, please click here.
                            
                            UnoTelly, 110 Eglinton Ave East, Toronto, ON, Canada
                            © 2015 UnoTelly

**Comment by SubJunk** [comment]
It's possible to have 2 different versions of Java installed, so maybe UMS is being launched with the old version. I'm not familiar enough with OS X to help in detail but maybe see if you can remove any older versions of Java

**Comment by Sami32** [comment]
@WayfairingStranger Did you solved this issue already ?

**Comment by WayfairingStranger** [comment]
No

**Comment by Sami32** [comment]
@WayfairingStranger I'm not a MAC user so my help will be very limited :-(

Did you tried uninstall all you Java version and reinstall the 7 ? and use the UMS for Java 7.
Did you tried with the Java 6 version and UMS for Java 6 ?

What is your computer model ? Do you use again OS X 10.7 ?

**Comment by Nadahar** [comment]
@WayfairingStranger I have a OS X 10.8.5 VM that I use to test UMS with Oracle Java 8. It works without any such problems.

**Comment by Nadahar** [comment]
This is a typical "Apple bullshit message". It has nothing to do with the image being "damaged", it's because it isn't signed with an "Apple approved signature" (which happens to cost money). 

A quick search led me to a couple of solutions:
* Make the "security settings" less restrictive: http://support.kaspersky.com/us/11578
* Remove the "this is a scary file" flag by running ```xattr -c <image file>```

**Comment by Sami32** [comment]
@WayfairingStranger You've a Gatekeeper issue, it's not the UMS fault.

You can find how to solve it with Google or in our Wiki:
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Mac-OS-X-issue

Enjoy ;)

**Comment by WayfairingStranger** [comment]
No. I could not find a solution.  So I quit using the app

**Comment by Nadahar** [comment]
@WayfairingStranger As you can see above, it's not an issue with UMS, you will have the same problem with any software that hasn't paid Apple to "approve" it. As UMS is open source, we can't pay such "bloodmoney" and the users will have to know how to get around Apple's "security".
