### ISSUE TITLE
Happy 5th anniversary with UMS, SurfaceS!

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4132]
@UniversalMediaServer/developers today marks 5 years since the first contribution from SurfaceS was released, in v7.5.0, which improved support for Samsung UHD (4k) TVs.

Since then, their contributions have been huge and really driven UMS forward, and I'm always excited to see what will happen next

Thank you, @SurfaceS !

**Comment by SurfaceS** [comment]
`what will happen next` ->  :building_construction: V14

still waiting for my anniversary :gift: 
:joy::joy::joy:
