### ISSUE TITLE
UMS 5.0.0-a1

### ISSUE THREAD

**Issue by charlesmanix** [UniversalMediaServer/UniversalMediaServer#415]
Hi, I'm Carlos from Spain. I have installed the version 5.0.0-a1 and there is a problem with sound. The problem is that the level sound on whatever film is too low.

**Comment by Sami32** [comment]
@charlesmanix Did the latest UMS version solved this issue ?

If not, please, post you log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
