### ISSUE TITLE
External Subtitles all end with a [?] character on screen

### ISSUE THREAD

**Issue by netx123** [UniversalMediaServer/UniversalMediaServer#420]
When streaming mkv's with external subs in .srt files to my Sony Bravia W series TV, each sentence appears with an extra character at the end of each line which looks like a question mark inside a rectangle, for example:
" Here is my sub line with this strange character. [?] ".
" And here it is again. [?] ".

**Comment by Sami32** [comment]
@netx123 Did the latest UMS version solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by netx123** [comment]
Yes it appears to have been fixed in some version between November 2014 and now, not sure if it was the latest version or not.
