### ISSUE TITLE
 Can't stream neither flac nor ogg files no Naim Mu-So

### ISSUE THREAD

**Issue by vigneras** [UniversalMediaServer/UniversalMediaServer#422]
I own a Naim Mu-So and would like to use it as a UPnP renderer.

Various problems:

1. It is detected as a Streamium -> I solve the issue with my own renderer config file (in attachment)
2. It must be controlled through a separate application (an UPnP controller or streamer,
I don't know the exact vocabulary). Naim provides such an application for Android that I use.
It is detected as an Android renderer -> I provide my own renderer config file (in attachment too).

Since the controller does not render anything but just control the Naim Mu-So, its supported
features seems irrelevant. What really matters is what the Naim Mu-So actually support.
Therefore, I set up the NaimApp renderer config file with the same Supported lines than the
Naim Mu-So but I am not sure if this is the right thing to do.

Now, the problem is that all flac files (and also ogg files) are always transcoded instead of
being streamed since these formats are natively supported by the Mu-So.

I don't get what is wrong in my setup, and watching the debug.log file (in attachment) does not help
to find the root cause of the problem.

Therefore I kindly ask for your help. Regards.

My setup :

pierre@gaia ~ $ uname -a
Linux gaia 3.13.7-calculate #1 SMP PREEMPT Wed Mar 26 18:41:04 UTC 2014 i686 Genuine Intel(R) CPU T2400 @ 1.83GHz GenuineIntel GNU/Linux
pierre@gaia ~ $ mediainfo --Version
MediaInfo Command line,
MediaInfoLib - v0.7.65
pierre@gaia ~ $ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) Server VM (build 25.25-b02, mixed mode)
pierre@gaia ~ $

PS : I mistakenly wrote the same issue first in the Forum. Therefore, the files are available there:

debug.log: http://www.universalmediaserver.com/forum/download/file.php?id=1671
NaimApp.conf: http://www.universalmediaserver.com/forum/download/file.php?id=1670
Naim-Mu-So.conf: http://www.universalmediaserver.com/forum/download/file.php?id=1669

**Comment by Sami32** [comment]
@vigneras Since then did you solved your problem ?
