### ISSUE TITLE
v14 : JDK API Handler with limited functionality

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#4220]
Just for reference : We have 2 `ApiHandler`

- one located in `net.pms.network.mediaserver.handlers` being used by netty, having the full functionality (using the `ApiResponseHandler`)
- one located in `net.pms.network.mediaserver.javahttpserver` being used by the internal `com.sun.net.httpserver`, having limited functionalities. The `ApiResponseHandler` is missing. Manually only `rescan` and `rescanFileOrFolder` is implemented. 

This means, the netty server has to be used for full API usage at the moment. This can be achieved by setting the server engine in the UMS.conf i.e. to `server_engine=2`.

What is our strategy? 
1) Is one of the two http server deprecated?
2) server_engine is not documented in UMS.conf and it looks like I cannot choose the server_engine in the Web-UI any more. Is this on purpose ?

**Comment by SurfaceS** [comment]
> Is one of the two http server deprecated?

#4058 
> I had hoped we didn't have to touch this again, but last month there were a lot of vulnerabilities disclosed that affect Netty v3

> server_engine is not documented in UMS.conf and it looks like I cannot choose the server_engine in the Web-UI any more. Is this on purpose ?
Menu > Server Settings > General Settings (tab) -> Services (Accordion) -> Engine

**Comment by ik666** [comment]
I don't have server settings? Any clue ?
<img width="175" alt="Bildschirmfoto 2023-11-07 um 16 10 52" src="https://github.com/UniversalMediaServer/UniversalMediaServer/assets/8244468/60bc9e7c-1248-4a6c-91e3-bf549362485b">

**Comment by SurfaceS** [comment]
are you browsing the 9001 port ?

I'm on your api fixing

**Comment by SurfaceS** [comment]
#4224 should have fixed your api things under `net.pms.network.mediaserver.javahttpserver`.

From your picture, it's like if you browse from the player only port (9002).

**Comment by ik666** [comment]
> Menu > Server Settings > General Settings (tab) -> Services (Accordion) -> Engine

Looks like I'm missing "service" accordion ... strange ... 

<img width="554" alt="Bildschirmfoto 2023-11-08 um 13 14 01" src="https://github.com/UniversalMediaServer/UniversalMediaServer/assets/8244468/5d8ef31c-3da7-4137-a8a0-b35d801828ee">

**Comment by ik666** [comment]
This did it. Thx.

**Comment by SubJunk** [comment]
It will be great to remove netty. I think that should be a priority after v14 is released

**Comment by ik666** [comment]
ok. Sounds like a plan. I'll close this as completed.
