### ISSUE TITLE
Updating svn binaries.

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#4237]
**FFmpeg :** 
November 10th, 2023, FFmpeg 6.1 "Heaviside"
FFmpeg 6.1 was released on 2023-11-11.
It is the latest stable FFmpeg release from the 6.1 release branch, which was cut from master on 2023-10-29. 

binaries/win32/ffmpeg64.exe [exe 7z](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z)

**MediaInfo :**
MediaInfo Version 23.10, 2023-10-04.

binaries/osx/libmediainfo.dylib [library bzip2](https://mediaarea.net/download/binary/libmediainfo0/23.10/MediaInfo_DLL_23.10_Mac_x86_64+arm64.tar.bz2)
binaries/win32/MediaInfo.dll [DLL zip](https://mediaarea.net/download/binary/libmediainfo0/23.10/MediaInfo_DLL_23.10_Windows_i386_WithoutInstaller.zip)
binaries/win32/MediaInfo64.dll [DLL zip](https://mediaarea.net/download/binary/libmediainfo0/23.10/MediaInfo_DLL_23.10_Windows_x64_WithoutInstaller.zip)

**SVN not used anymore :**
binaries/MediaInfo.dll
binaries/MediaInfo64.dll

**Comment by SubJunk** [comment]
Thanks for the list, I have done them except MediaInfo which I'll do soon

Also do you have an email address I can contact you on?

**Comment by SurfaceS** [comment]
I don't like giving my email on open read thread (spam).
You can email me on the junk email address vallard at orange dot fr.
I'll check it until I receive your email and reply you back with my personal one.

**Comment by SubJunk** [comment]
@SurfaceS I sent the email

**Comment by SubJunk** [comment]
This is done now. I have left old binaries on SVN because that is needed to build old versions of UMS - the web server doesn't find removed files even if you specify the revision in the URL
