### ISSUE TITLE
Unable to load Java Runtime Environment on MacOS Sonoma 14.1.1

### ISSUE THREAD

**Issue by ragones** [UniversalMediaServer/UniversalMediaServer#4241]
Hi, I've recently purchased a new iMac and tried installing UMS 13.7, but it came up with the error "Unable to load Java Runtime Environment".

I've tried installing "Unable to load Java Runtime Environment" and restarting my computer, even deleting UMS server again and loading it back again, but still the same issue.

My previous old iMac didn't have any issues playing UMS, so was wondering if there's a fix I can use to make this work.

Thanks in advance.

**Comment by ragones** [comment]
@SubJunk Yes that worked, thank you so much. :)

I guess I was downloading the wrong .dmg file so no wonder it didn't open.

**Comment by SubJunk** [comment]
@ragones thank you for confirming this works :)
