### ISSUE TITLE
Unable to open any files using Smart TV "BRAVIA XR-55X90K"

### ISSUE THREAD

**Issue by celery22** [UniversalMediaServer/UniversalMediaServer#4279]
New TV (Sony BRAVIA XR-55X90K) and unable to open any video files using UMS. Here are the log files: 

19:37:28 INFO  Transcoding engine "AviSynth/FFmpeg" is available
19:37:28 INFO  Transcoding engine "AviSynth/MEncoder" is available
19:37:28 INFO  Transcoding engine "FFmpeg Audio" is available
19:37:28 INFO  Transcoding engine "MEncoder Video" is available
19:37:28 INFO  Transcoding engine "FFmpeg Video" is available
19:37:28 WARN  Transcoding engine "VLC Video" is not available
19:37:28 INFO  Transcoding engine "FFmpeg Web Video" is available
19:37:28 INFO  Transcoding engine "MEncoder Web Video" is available
19:37:28 WARN  Transcoding engine "VLC Web Video" is not available
19:37:28 INFO  Transcoding engine "tsMuxeR Video" is available
19:37:28 INFO  Transcoding engine "tsMuxeR Audio" is available
19:37:28 WARN  Transcoding engine "VLC Web Audio (Legacy)" is not available
19:37:28 WARN  Transcoding engine "VLC Web Video (Legacy)" is not available
19:37:29 INFO  Transcoding engine "DCRaw" is available
19:37:29 INFO  Transcoding engine "youtube-dl" is available
19:37:29 INFO  Using the following UUID configured in UMS.conf: ac177520-65b5-4c70-adc9-0cf65b4b12c7
19:37:29 INFO  IP Filter: Access allowed to RichardPC1.home
19:37:29 INFO  IP Filter: Access allowed to mynetwork.home
19:37:29 INFO  IP Filter: Access allowed to TIZEN
19:37:29 INFO  Checking IP: 192.168.2.1 for Unknown renderer
19:37:29 INFO  IP Filter: Access allowed to 192.168.2.51
19:37:29 INFO  Checking IP: 192.168.2.19 for Samsung 8 Series
19:37:29 INFO  Renderer Samsung 8 Series found on address: TIZEN (192.168.2.19)
19:37:29 INFO  Renderer Unknown renderer found on address: mynetwork.home (192.168.2.1)
19:37:29 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:29 INFO  Checking IP: 192.168.2.51 for Unknown renderer
19:37:29 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:29 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:29 INFO  Renderer Unknown renderer found on address: 192.168.2.51
19:37:29 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:29 INFO  Web player is available at: http://192.168.2.34:9002
19:37:30 INFO  Universal Media Server is now available for renderers to find
19:37:30 INFO  Launching the graphical interface on a browser
19:37:31 ERROR Error verifying JWT: The Token has expired on 2023-12-03T21:08:00Z.
19:37:31 INFO  Checking user table have admin
19:37:31 INFO  Checking user table have admin
19:37:31 INFO  Checking user table have admin
19:37:31 ERROR Could not lookup audio cover for "": musicbrainz.org replied with status code 400
19:37:33 INFO  Finding user: admin 
19:37:33 INFO  Got user from db: admin
19:37:33 INFO  Finding user: admin 
19:37:33 INFO  Got user from db: admin
19:37:33 INFO  User admin logged
19:37:33 INFO  User admin logged
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:44 INFO  Renderer Unknown renderer has an estimated network speed of 32.46594125874126 Mb/s
19:37:44 INFO  Renderer Samsung 8 Series has an estimated network speed of 24.790195101253616 Mb/s
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:37:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:37:44 INFO  Renderer Unknown renderer has an estimated network speed of 18.31191009461127 Mb/s
19:37:47 INFO  Library scan completed in 17 seconds
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:38:18 INFO  IP Filter: Access allowed to DESKTOP-80FG3JS
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:38:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:39:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:40:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:14 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:41:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:42:16 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:42:16 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-av-client-info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";
X-av-physical-unit-info: pa="BRAVIA XR-55X90K";
19:42:44 INFO  Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: UPnP/1.0
X-AV-Physical-Unit-Info: pa="BRAVIA XR-55X90K";
X-AV-Client-Info: av=5.0; cn="Sony Corporation"; mn="BRAVIA XR-55X90K"; mv="3.0";

**Comment by SubJunk** [comment]
@celery22 hi, please follow the instructions to create logs https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new
