### ISSUE TITLE
'Check for updates' button locks up UMS (13.8.0)

### ISSUE THREAD

**Issue by IntelliMoo** [UniversalMediaServer/UniversalMediaServer#4315]
The 'Check for updates' button displays a blank white "Universal Media Server Auto Update" dialog and locks up UMS (13.8.0).  The dialog and main window cannot be closed by normal means including Alt+F4.

**Comment by SubJunk** [comment]
I have confirmed this, thanks for reporting! Fixing now

**Comment by SubJunk** [comment]
This is fixed since 13.9.0
