### ISSUE TITLE
Buggy MediaInfo

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#432]
Using latest code of v5 ( https://github.com/UniversalMediaServer/UniversalMediaServer/commit/3a4c9a73b0b12f4e943eb43b9b1c11292bf7d07e ) and found problems. One of them is about MediaInfo.
https://copy.com/RCmRfMtaSGlQnFz9
MediaInfo with this file detects incorrect bitrate as 15GBits or similar wrong values. Last working one is MediaInfo v0.7.68. Duplicate this file 400x to one folder to see the same behavior.
Another problem is that parsing similar files (from my Panasonic camcorder) took 2secs for one file. Imagine folder with 700 files ==> server disconnects. In this case ffmpeg was much faster.
Is it possible to speed it up somehow so renderer will not disconnect?
Thx

**Comment by Sami32** [comment]
@ExSport @SubJunk @valib Did the latest MediaInfo version solved this issue ? I don't have that free space on my little HDD to test it myself ;-)

**Comment by SubJunk** [comment]
Yeah we are passing a few parameters to it for this now
