### ISSUE TITLE
video files not showing on Marantz SR6008

### ISSUE THREAD

**Issue by talk2somani** [UniversalMediaServer/UniversalMediaServer#435]
Hi,

I am trying to stream videos and songs from my ASUS laptop/tablet to my Marantz SR6008 receiver. The ASUS laptop/tablet has Windows 8.1 and I have installed UMS 4.3.1

When all connected, and I browse the UMS on Marantz SR6008 receiver, I can see all the folders I have shared. I can play songs successfully from the receiver. However, when I go to any of the folders having video files, I cannot see the video files. It only shows "#Transcode#"
If I select "#Transcode#", it shows the video file names, but if I select any of these files, it shows only - 
----empty----
but doesn't play it.

I tried selecting the checkbox "Do not show Transcode folder in the settings. This time going into the folder with video files it shows only - 
----empty----

Please note I have tried multiple video file types - mp4, mkv and avi
Its the same issue with all file types.

Can you please suggest what can be an issue and any possible resolution?

Regards,
Aakash Somani

**Comment by Sami32** [comment]
@talk2somani Did you solved this issue ?

If not, please, post your log following these steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
