### ISSUE TITLE
Disable engines when they don't exist on the computer

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#436]
This would be a cool addition, since on Linux it can be confusing for users who don't have MEncoder installed, as we see on the forums. Also for Windows users who don't have VLC or AviSynth installed.

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk We just had a forum thread about the missing [MEncoder for Linux] (http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=5752). I looked at the distribution archieve for Linux, and it doesn't seem like MEncoder is there. 

What I read above here also supports that. I need some orientation about MEncoder/MPlayer, and I figure here is as good a place to ask as any:
* Is there a real difference between MEncoder and MPlayer, or is MEncoder simply a part of MPlayer? Is it possible to install MEncoder and not MPlayer? 
* Why isn't MEncoder distributed in the Linux package? Is it licensing issues, technical issues or simply that noone ever bothered to do it?
* I've picked up from various sources that @SubJunk have a special build/fork of MEncoder for Windows. I'm guessing that's the version we're distributing. It that the case?
* What is different with the @SubJunk build of MEncoder compared to the "normal" MEncoder?
* Why is it only available for Windows?
* Is the sourcecode available somewhere?
* Is it kept in "sync"/updated when new releases of MEncoder/MPlayer is made?

**Comment by SubJunk** [comment]
Good questions @Nadahar 

* MEncoder is the transcoder that comes with MPlayer, which is a video player, so we mostly use MEncoder, but we use MPlayer to generate font caches for subtitles so we include both.
* For a while I was including my builds of MPlayer/MEncoder with the Linux releases but I wasn't able to figure out how to build them completely statically so it defeated the purpose of that
* Yes, we use that for Windows
* I'm a MPlayer developer (very inactive but with commit access) so a lot of my fixes have made it into the main code, but there have been some decisions I've made differently to the main trunk so I've kept them in my build. The main difference is that my build is the most stable for transcoding AC-3 and reading/transcoding DVDs.
* It's only available for Windows because that's all I know how to build for statically
* The MPlayer source code is available from their website, and I'm happy to provide my modified source code if you want it
* I do a lot of testing before releasing new versions, and since MPlayer is built on top of FFmpeg which is a very active project, but MPlayer isn't, the trunk is increasingly in a less stable state. So my latest MPlayer/MEncoder release was intentionally out of date because I found that newer code broke things we need.

Ideally I would love to be able to release builds of MPlayer/MEncoder for our 3 operating systems and would welcome help with that. We are generally trying to move away from MPlayer/MEncoder as much as possible but there are some things that FFmpeg seems unlikely to ever have, like DVD support and support for certain subtitles configurations.

**Comment by Sami32** [comment]
Cool...but for now we have that ;-)
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions

**Comment by SubJunk** [comment]
This was done recently
