### ISSUE TITLE
Catch up...

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#437]
Hey guys.. i have a break coming up and i might have some time to help out if i can... any tasks i can assist in?

**Comment by DeFlanko** [comment]
Hey guys, the best thing to do if you need the wiki updated is send me what ever you have and i pretty it up

**Comment by DeFlanko** [comment]
(again in and out.. sorry guys..)

**Comment by Sami32** [comment]
@SubJunk Could be closed now.
