### ISSUE TITLE
Wrong aspect ratio when subtitles enabled (Bravia EX720)

### ISSUE THREAD

**Issue by pastuchagrzegorz** [UniversalMediaServer/UniversalMediaServer#438]
Hello. I've been trying for hours to play some Full HD movies on my Bravia EX720 through wire but there is one big problem. Firstly, the movie I was testing is x264 .mkv 1920x1040 with built-in multiple subtitles and double audio (two languages). When playing it with subtitles disabled everything is fine, but enabling them makes the picture squeezed horizontally - it's still covering whole width of the TV, but takes half the height than it should. Subtitles are working well though. Can I ask for advice about settings having impact on this? I didn't really edit any files, tried some configs but without result.

**Comment by sprooose** [comment]
Same issue on Bravia 46EX520.
I have not yet tried modifying any settings.

**Comment by Sami32** [comment]
@pastuchagrzegorz @sprooose Did the latest UMS version solved this issue ?

I guess that renderer update with `KeepAspectRatioTranscoding` and `KeepAspectRatio` stettings solved this issue.

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by SubJunk** [comment]
This was fixed last yearhttps://github.com/UniversalMediaServer/UniversalMediaServer/commit/ca935854d07fc08408cf7ba7d7950e1673f0eedf#diff-7ca69bb14ebec12f6ca9f802e522d9b9
