### ISSUE TITLE
Readme: The CI badge image broken

### ISSUE THREAD

**Issue by buhtz** [UniversalMediaServer/UniversalMediaServer#4398]
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2118b256f166071c3e1905268cda5d3d02bef819/README.md?plain=1#L2

The image link is missing or somehow broken.

**Comment by SurfaceS** [comment]
![Universal Media Server CI](https://github.com/UniversalMediaServer/UniversalMediaServer/workflows/Universal%20Media%20Server%20CI/badge.svg) [![Crowdin](https://badges.crowdin.net/universalmediaserver/localized.svg)](https://crowdin.com/project/universalmediaserver) 

I think not.

**Comment by SurfaceS** [comment]
![Universal Media Server CI](https://github.com/UniversalMediaServer/UniversalMediaServer/workflows/CI/badge.svg)

Thanks, fixed in #4473
