### ISSUE TITLE
INSTALL.txt for Linux (x86_64) refers to vlc-nox rather than vlc-bin

### ISSUE THREAD

**Issue by easleydp** [UniversalMediaServer/UniversalMediaServer#4409]
INSTALL.txt for Linux (x86_64) says to install the following dependencies:

> sudo apt-get install mediainfo dcraw vlc-nox mplayer mencoder

On Ubuntu 22.04.3 this gave an error:

> E: Unable to locate package vlc-nox

Searched for "Unable to locate package vlc-nox" and found this page - https://askubuntu.com/a/1029005/62445 - which suggests vlc-nox has been replaced by vlc-bin. After switching to this the installation proceeded without error.

**Comment by SubJunk** [comment]
@easleydp thanks for this, I have corrected it now.

We should really migrate this document to our knowledge base at https://support.universalmediaserver.com/category/installation

Any interest in helping us do that? It would involve creating a new markdown file in our knowledge base repository at https://github.com/UniversalMediaServer/knowledge-base/tree/main/docs/installation
