### ISSUE TITLE
Error streaming some files with filename containing (

### ISSUE THREAD

**Issue by brabulla** [UniversalMediaServer/UniversalMediaServer#441]
When trying to stream some files which got ( in their name, UMS throws an error, that ffmpeg has a return code 2. I went through the debug log, and as far as i can tell, it is a bash error, when calling ffmpeg with the parameters and the filename, as the log says 
>DEBUG 2014-12-23 17:08:34.240 [ffmpeg-123-2] /home/linaro/downloads/ums-4.3.1/linux/ffmpeg: 1: /home/linaro/downloads/ums-4.3.1/linux/ffmpeg: Syntax error: "(" unexpected

I tried ffmpeg with the same file manually, and still got a bash syntax error, but the error is gone when I put the filename between " " . I don't know if this is a known issue or not, or whether should i just avoid filenames containing a ( , but fixing this would be great.

**Comment by Sami32** [comment]
Not an issue on Windows with actual UMS version.

@SubJunk @valib Testing this issue i accidentally discovered that (_) in the file name make it hidden because it couldn't be parsed. Very minor issue, just letting you know.

**Comment by SubJunk** [comment]
@Sami32 do you mean files with the character `_` or the 3 characters `(_)`?

**Comment by Sami32** [comment]
@subjunk The 3 together. `(_)`
