### ISSUE TITLE
Configuration file Samsung QLED 4K 2023 Q68C (DTS codecs are not supported, disable mkv transcoding)

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4410]
Hi, can you add the Samsung QLED 4K 2023 Q68C configuration file to the UMS renderer list ?

modelName= TQ43Q68CAU

UMS is currently using the wrong configuration for this TV set.
Can't start a video with UMS if I don't disable mkv transcoding.
The DivX and DTS codecs are not supported by the Samsung TV models released in 2023

Best regards

![20240204_144836](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/a3d5ea2f-8574-47c6-9626-2691a823d60b)
![20240204_144939](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/b9cf97eb-f773-4f98-a0ee-6f4a08b0406c)

[ums_dbg_2024-02-04-14-50.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/14157010/ums_dbg_2024-02-04-14-50.zip)
-----------------------------------------------------------------------------------------------------------------------------------------
![1](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/ab277bef-8bf9-463d-adb1-4fd9851ccbda)
![20240204_145317](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/0a80ed96-aa04-46c2-ab54-6775789b5183)

[ums_dbg_2024-02-04-14-54 (disable mkv transcoding).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/14157011/ums_dbg_2024-02-04-14-54.disable.mkv.transcoding.zip)

**Comment by SubJunk** [comment]
Thanks for this. It's weird, I can't find any mention of `TQ` on Samsung TV model name guides, like 
https://en.tab-tv.com/marking-decoding-tvs-lg-samsung-sony-etc/labeling-and-marking-samsung-tv/ or
https://www.samsung.com/us/support/answer/ANS00087664/

Anyway it's done in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4604

**Comment by Fredo1650** [comment]
The exact label of the TV if that helps
![20240423_025423](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/c519187c-be56-49a6-9d24-45cef77913ae)

**Comment by SubJunk** [comment]
Yeah these confs could be designed with better fallbacks for sure. This issue is done now
