### ISSUE TITLE
UMS stops streaming from PC

### ISSUE THREAD

**Issue by krisz777** [UniversalMediaServer/UniversalMediaServer#444]
Hello,

I downloaded UMS 4.3.1 today, becuase I wanted to replace Samsung Allshare finally.
I kept all the config on default, UMS recognized my TV, everything went well. Started playing a video and after a few minutes it started faltering and stopped. I tried other files but I got the same result. Then I installed UMS 5.0.0-b1. Same happened. I created and packed the debug files, but I cannot attach it here. Is there an e-mail address to send?

Thank you for your help in advance!

Regards,
Krisz

**Comment by SubJunk** [comment]
@krisz777 please let me know if it still happens with this one: http://www.spirton.com/uploads/UMS/UMS-482101e.exe
Also in your debug logs I can't see any files being played, please make sure you play them before the log is made :)

**Comment by waterdownscott** [comment]
Hello,

I have the same problem could be the Samsung TV, my model is LNS3251DX/XAA.

I just updated the program to 5.0.0 

and still have the same problem, seems to work fine on mp4 and avi files but has the freezing and jump to next file with mkv files.

**Comment by waterdownscott** [comment]
Sorry here is my log files

https://mega.co.nz/#!dU4EBKqI!uXNpkTfCka_ttZ9MKlzuIu2wf06rq3GqE3d5DTutQqA

**Comment by krisz777** [comment]
Thank you, the new config file solved the problem! :)

**Comment by Sami32** [comment]
@waterdownscott Samsung LNS3251DX/XAA do not appear in the log so we cannot create a renderer configuration file.

Feel free to re-open this issue if you have a new log, just follow these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by horrorman009** [comment]
I think I need a config file for my TV as well. It's a Samsung. The model number is UN55JU6700. Thanks in advance.

**Comment by Sami32** [comment]
@horrorman009 I need your full trace log.

Use UMS 6.7.1 and follow these steps:
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

And attach it here with a fake _.txt_ extension.

**Comment by horrorman009** [comment]
I didn't see anything in the log. The movie stops after 15 to 20 minutes of playback, stops, loads, then continues playing. Here is my log file.
[ums_dbg.txt.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1083320/ums_dbg.txt.zip)

**Comment by Sami32** [comment]
@horrorman009 You didn't do a clean install, so the old DLL are used, and your database became corrupted. So, you'll need to do a clean install.

You didn't played the movie, as explained in the link given, before saving your log, so it's not useful.
Please, try again.

Note: I guess that you already know that you're using a Java 8 32-bit version on your Windows 64-bit OS.

**Comment by horrorman009** [comment]
I have done a clean install by checking the box labeled "clean install" during installation. I have replaced the 32 bit java with the 64 bit. I let the movie run thru to completion. I know that it did the pause to load and continue playing at least once. I hope it works this time. Again, thank you so much for your quick response and help. I really appreciate. Here is the new debug file.
[ums_dbg.txt (2).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1083501/ums_dbg.txt.2.zip)

**Comment by Nadahar** [comment]
@horrorman009 There's still something wrong with UMS' database version in your installation. If you go to the "Navigation/Share" tab and click "Reset cache" I think it should be sorted out.

**Comment by Sami32** [comment]
@horrorman009 Sorry, i saw nothing about your video playing inside your log.

Do you've only one movie that give you issue ? Terminator.
Please, could post the MediaInfo log from this video ?

**Comment by horrorman009** [comment]
Here is the mediainfo from the movie. There are a couple others that do it as well but I can't remember off the top of my head.
[Terminator media info.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1083642/Terminator.media.info.txt)

**Comment by horrorman009** [comment]
And one more time, here is the debug file. I have reset the cache as well.

[ums_dbg.txt (3).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1083673/ums_dbg.txt.3.zip)

**Comment by Sami32** [comment]
@horrorman009 The good point is that you finally have an healty database.

The bad, is that no video engine command line are displayed into your log, so i really don't know how you manage to do it...

Anyway, the only blindy thing that i can do for you, is to give you a renderer configuration file:

[Samsung-JU6700.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1084769/Samsung-JU6700.conf.txt)
(Delete the fake .txt extension and add this file into your UMS "renderers" subfolder.
