### ISSUE TITLE
Donation links broken

### ISSUE THREAD

**Issue by SurfaceS** [UniversalMediaServer/UniversalMediaServer#4453]
Forum paypal donation link and App paypal donation link are not working.
Forum link : hosted_button_id=KZLD5J8DS6K6W
App link (`src/main/external-resources/documentation/index.html`) = hosted_button_id=86EZ3CGNMZB5G

**Comment by SubJunk** [comment]
Oh good find. It looks like PayPal changed their rules around receiving donations. I'll try to fix it

**Comment by SubJunk** [comment]
I can't find a way to make PayPal work again so I have replaced it with Open Collective, because Patreon does not accept one-time donations. I think I have removed all references to PayPal now
