### ISSUE TITLE
Folders are not filtered with folder_names_ignored when new files are added or deleted

### ISSUE THREAD

**Issue by MarkoMarjamaa** [UniversalMediaServer/UniversalMediaServer#4458]
I'm now using version 13.8.0
Folder filtering works ok when folders are scanned at startup: 
DEBUG 2024-02-08 17:35:50.475 [jupnp-netty-worker 13] Ignoring NoUMS because it is in the ignored folders list

This is checked in 
\src\main\java\net\pms\dlna\VirtualFile.java in line 145
	} else if (f.isDirectory() && !ignoredFolderNames.isEmpty() && ignoredFolderNames.contains(f.getName())) {
		LOGGER.debug("Ignoring {} because it is in the ignored folders list", f.getName());

But when new file is added, it uses event based code and there's no filtering for folder_names_ignored
DEBUG 2024-02-08 18:25:23.808 [File watcher] ENTRY_CREATE (ct=1): D:\NoUMS\You should not see me.txt
DEBUG 2024-02-08 18:25:23.808 [File watcher] ENTRY_MODIFY (ct=1): D:\NoUMS
DEBUG 2024-02-08 18:25:23.808 [File watcher] ENTRY_MODIFY (ct=1): D:\NoUMS\You should not see me.txt
DEBUG 2024-02-08 18:25:23.832 [File event] Could not parse the bitrate for: D:\NoUMS\You should not see me.txt

I'm using some folder names like NoUMS to prevent UMS of scanning them. For instance folders for backups.

**Comment by SubJunk** [comment]
@MarkoMarjamaa can you please check on version 14? There has been a lot of work on access control on there

**Comment by MarkoMarjamaa** [comment]
Tested with v14 (UMS-14.0.0-b1) 

DEBUG 2024-02-09 21:21:49.898 [File watcher] ENTRY_CREATE (ct=1): D:\Test\NoUMS\Test.mkv
DEBUG 2024-02-09 21:21:49.900 [File event] scanning file or folder : D:\Test\NoUMS\Test.mkv
DEBUG 2024-02-09 21:21:49.914 [File event] Reading show_recently_played_folder: false (default: true)
DEBUG 2024-02-09 21:21:49.916 [File event] Discovering the root folder for MediaScanner
DEBUG 2024-02-09 21:21:49.916 [File event] Reading show_media_library_folder: false (default: true)
DEBUG 2024-02-09 21:21:49.922 [File event] scanning file or folder : D:\Test
DEBUG 2024-02-09 21:21:49.924 [File event] Ignoring NoUMS because it is in the ignored folders list
DEBUG 2024-02-09 21:21:50.003 [File watcher] ENTRY_MODIFY (ct=1): D:\Test\NoUMS
DEBUG 2024-02-09 21:21:50.004 [File watcher] ENTRY_MODIFY (ct=1): D:\Test\NoUMS\Test.mkv
INFO  2024-02-09 21:21:50.154 [File event] New file Test.mkv was detected and added to the media store
...
DEBUG 2024-02-09 21:21:50.505 [File event] scanning file or folder : D:\Test\NoUMS\Test.mkv
DEBUG 2024-02-09 21:21:50.505 [File event] scanning file or folder : D:\Test
DEBUG 2024-02-09 21:21:50.506 [File event] Ignoring NoUMS because it is in the ignored folders list
INFO  2024-02-09 21:21:50.508 [File event] New file Test.mkv was detected and added to the media store

Seems it's logging that file is ignored, but still I found it in db(medias.mv.db). I can't browse it with DLNA but it is in the db. 

Besides, I can't use v14 (b1) because I have disks mounted as NTFS junction points, and v14 does not show them and gives error if it is a shared folder.

**Comment by SurfaceS** [comment]
> Seems it's logging that file is ignored, but still I found it in db(medias.mv.db). I can't browse it with DLNA but it is in the db.

The filtered things should be fixed in #4461.

> Besides, I can't use v14 (b1) because I have disks mounted as NTFS junction points, and v14 does not show them and gives error if it is a shared folder.

@MarkoMarjamaa Can you give me details about error you had on that ?

**Comment by SubJunk** [comment]
@MarkoMarjamaa are you able to compile UMS? If not, if you let me know which OS you're on, I can upload the version with the fix SurfaceS posted above for you to test

**Comment by MarkoMarjamaa** [comment]
I can't compile, but I have Win7(64bit). 

I didn't copy the error about junction points. I'll try again later. I like to use junction points so they show as one disk (like in unix) and you can name your shares. I you are using disks, you have to use disk letters as share name.

**Comment by Mik-S-UMS** [comment]
@MarkoMarjamaa setting up virtual folders will do the same thing as junction points to your renderer and you can name them too.

**Comment by SubJunk** [comment]
@MarkoMarjamaa here is the latest v14 build, please let me know when you have downloaded it https://www.universalmediaserver.com/uploads/UMS-v14-9aa840b.exe

**Comment by MarkoMarjamaa** [comment]
@Mik-S-UMS 
I though virtual folders were gone when they stopped working in some version and there's no more section virtual_folders_file in UMS.conf in clean install...
So they are now in SHARED.conf, I'll look into that.

**Comment by SurfaceS** [comment]
@MarkoMarjamaa 
UMS need to work with NTFS junction points btw.

**Comment by MarkoMarjamaa** [comment]
@SurfaceS 
Seems the new version does not give same java error. Junction points work when it's the directory mounted. But if I mounted it's parent, it scanned it's data and set file watches but when I tried to use it in Kodi, the junction point was empty ! 
For me this is ok now, because I share the junction point.

**Comment by SubJunk** [comment]
Thanks for confirming the fix!
