### ISSUE TITLE
Gatekeeper Problem

### ISSUE THREAD

**Issue by readingsnail** [UniversalMediaServer/UniversalMediaServer#448]
I'm using OS X 10.10.2, and os say it's a broken app.

so I upgrade your app, it is so complicated (handle to Gatekeeper Configure). so please, Solve Gatekeeper Problem :)

**Comment by Optimusprimeums** [comment]
Gatekeeper requires UMS (and its developer/release techs) to pay for a Apple developer account (a yearly subscription) to get programs certified as 'Apple Certified' thus Gatekeeper complaint. As we are open source and not for profit we rely on donations to pay for these kind of things. I don't use OS-X all the time and only build UMS releases for OS-X, thus I cannot myself afford to pay or justify to pay apple to have the App 'Certified'. If people want UMS Certified (for OS-X), then donate to enable us to afford to pay these fees to keep our App free and not for profit.

**Comment by SubJunk** [comment]
How much is the subscription fee for Gatekeeper?

**Comment by Optimusprimeums** [comment]
We've investigated this before, but it's $99 for a year just to sign the apps. Here's the forum post from 2013 when we talked about it http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=1368

**Comment by SubJunk** [comment]
@Optimusprimeums darn. I was thinking we could get it from donations if it were cheaper but we don't get that many. Typical Apple overcharging for things that should be free or cheap.

**Comment by Optimusprimeums** [comment]
@SubJunk Thats right, i'd pay it if i developed apps for apple devices. Lucky Oracle didn't charge anything, we'd be broke!!!!

**Comment by Sami32** [comment]
The end.
