### ISSUE TITLE
Move FAQ entries to Knowledge Base

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4497]
We have a broken FAQ page that contains some helpful information https://www.universalmediaserver.com/faq/
We should migrate that into our Docusaurus Knowledge Base https://support.universalmediaserver.com/ the code for which is at https://github.com/UniversalMediaServer/knowledge-base

**Comment by 3akare** [comment]
Hello @SubJunk, I would like to work on this issue.

**Comment by SubJunk** [comment]
This is really great, thank you! I will suggest some changes on that repo

**Comment by SubJunk** [comment]
This is merged now, thanks again
