### ISSUE TITLE
Subtitle size are too small 4.3.1

### ISSUE THREAD

**Issue by Arkadietz** [UniversalMediaServer/UniversalMediaServer#451]
What's the way to configure size of the subs? I've tried everything to change it but without succcess. Please, respond.

**Comment by SubJunk** [comment]
Transcoding Settings tab, Subtitles Settings subtab, Font scale setting. Doesn't it work?

**Comment by Sami32** [comment]
@Arkadietz https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Audio-and-Subtitles
