### ISSUE TITLE
HLS transcoding not using the GPU

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4534]
I have been trying to figure this one out on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=15994)
It appears GPU encoding is not working for HLS but works normally when not using it. 
I don't have a graphics card that can do the encoding so I can't test it myself.

All I see in the logs is "Something wrong" before the transcode command and it uses `lib264` instead of `h264_nvenc`

```
net.pms.encoders.FFMpegVideo Switching from FFmpeg to Hls FFmpeg to transcode.
net.pms.platform.windows.WindowsUtils Using short path name of "F:\Films et Séries 4K\Avatar - la voie de l'eau\Avatar - la voie de l'eau.mkv": "F:\FILMSE~2\AVATAR~1\AVATAR~1.MKV"
net.pms.configuration.ConfigurationReader Reading gpu_acceleration: true (default: false)
net.pms.encoders.FFMpegVideo Something wrong, falling back to h264
net.pms.platform.windows.WindowsNamedPipe Creating pipe \\.\pipe\ffmpeghlsvideo_100_1710168890735
net.pms.platform.windows.WindowsNamedPipe Waiting for Windows names pipe connection "\\.\pipe\ffmpeghlsvideo_100_1710168890735"
net.pms.io.ProcessWrapperImpl Starting "C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe" -y -loglevel info -t 6.0 -sn -i F:\FILMSE~2\AVATAR~1\AVATAR~1.MKV -sn -map 0:V -map 0:a:0 -dn -copyts -c:v libx264 -keyint_min 25 -preset superfast -profile:v high -level 30 -pix_fmt yuv420p -c:a aac -ac 2 -ab 160000 -f mpegts -skip_estimate_duration_from_pts 1 -use_wallclock_as_timestamps 1 -movflags frag_keyframe \\.\pipe\ffmpeghlsvideo_100_1710168890735
```

There are issues with the speed test too as they are getting a speed of 2Mb/s on wifi but high bitrate 4K videos will play normally when streaming, and this speed test was forcing everything to be transcoded and unplayable. Even with a wired connection they only get 17mb/s.

**Comment by SurfaceS** [comment]
fixed in #4647
