### ISSUE TITLE
Upgrade to Netty 4.x

### ISSUE THREAD

**Issue by mfulgo** [UniversalMediaServer/UniversalMediaServer#454]
To improve streaming from the server, an upgrade to Netty 4.x is needed. See [issue 253](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253#issuecomment-70592990) for more info.

**Comment by mfulgo** [comment]
@SubJunk Smoke testing this, it seems to server up SOAP responses and stream videos just fine.  I just can't fully test it because I'm still fighting to figure out the right config to transcode for my Vizio.  Please let me know if you run into errors.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942
