### ISSUE TITLE
Make all settings positive

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#456]
I think it would be good to go through the user settings and change instances of negatives to positives, for example "Do not add engine names to filenames" would become "Add engine names to filenames", etc.
The old settings should be kept with a deprecated flag for backwards-compatibility.
I think this will make our settings easier to understand more quickly.

**Comment by Sami32** [comment]
@SubJunk I agree with it, not that it bother me, but i can remember psychological studies on that subject.
http://www.psychologicalscience.org/index.php/news/releases/true-or-false-how-our-brain-processes-negative-statements.html

**Comment by SubJunk** [comment]
I did some of this in 7.0.0 already BTW

**Comment by SubJunk** [comment]
I think this is done
