### ISSUE TITLE
Cover art for folders

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#458]
It would be cool to allow cover art for folders, like if there's an image called "cover.jpg" inside a folder, that is used.

Suggested on the forum http://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=2786

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942

**Comment by SubJunk** [comment]
This is already how it works afaict

**Comment by Nadahar** [comment]
@SubJunk This was implemented during the "images/thumbnails" refactoring.
