### ISSUE TITLE
Updating Fully Played Thumbnails

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4608]
Hello,
Following post #4592  I open the problem of updating fully played thumbnails
Excerpt from my last post:
I still have this TV/UMS synchronization problem on the thumbnail marked fully playing, I think there is a bug in the UMS database, because by moving the files and restarting UMS several times, the thumbnails which was not marked before on the television are now marked fully played after this manipulation.
On the WEB player it works correctly.
@Mik-S-UMS,  @SubJunk  the problem that I am currently describing is well linked to the post #2664

**Comment by SubJunk** [comment]
@Fredo1650 thank you for making this issue. @Mik-S-UMS pointed out that we already have an issue for this that I forgot about so I will close this and continue in that one https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2664
I'm working on it now
