### ISSUE TITLE
Wrong HLS audio bitrate

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#4636]
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/1f21cf7b5653d7f4dcee4ef881c0686a30206bb4/src/main/java/net/pms/encoders/HlsHelper.java#L565-L566

Seems like typo. Is the 1200000 bit/sec (1.2 Mb/s) correct audio bitrate?

**Comment by SurfaceS** [comment]
@valib Nice find.

fixed in  #4637
