### ISSUE TITLE
Wrong database implementation

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#4641]
The column "TRACK_ID" in the "MediaTableMusicBrainzReleases" is not implemented when introduced the "MBID" but it is still called in

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/47b0b1804f66feeb4dcd79129037cf7b4b4f2deb/src/main/java/net/pms/database/MediaTableMusicBrainzReleases.java#L226

and

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/47b0b1804f66feeb4dcd79129037cf7b4b4f2deb/src/main/java/net/pms/database/MediaTableMusicBrainzReleases.java#L325

which causes errors.

**Comment by SurfaceS** [comment]
fix https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4641
