### ISSUE TITLE
wrong download url for linux on https://www.universalmediaserver.com

### ISSUE THREAD

**Issue by freggeldoe** [UniversalMediaServer/UniversalMediaServer#4648]
Since quite a few versions the linux download url is wrong and leads to a `404` page.
Currently presented download url for linux on https://www.universalmediaserver.com is
`https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/13.10.1-/UMS-13.10.1-x86_64.tgz`
working url is
`https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/13.10.1/UMS-13.10.1-x86_64.tgz`
The wrong url contains a trailing `-` at the last directory.

**Comment by SurfaceS** [comment]
thanks for pointing this.

@SubJunk 
should be fixed with https://github.com/UniversalMediaServer/website/commit/bb2bdf41a1e9bf61e2e3582ee02ac12241951e96

**Comment by SubJunk** [comment]
I just published the fix, thank you both!
