### ISSUE TITLE
V14 - Cannot open DLNA on TV it crashes.

### ISSUE THREAD

**Issue by favorit5503** [UniversalMediaServer/UniversalMediaServer#4650]
Hi, 

i updated the UMS from V13 to V14 and after the update i found two issues. (Tried it with clean install its the same)
First when the TV finds the UMS after selecting it in the TV the TV responds with "that the page cannot be displayed" and the server generates an error i included the logs.
Second problem is when i launch the server as service all folder names are wrong and the half of the names are missing. Maybe its a language problem see the shared.conf in the zip. When the server is launched without the service then the problem is not there. 
Its a Samsung TV UE32H6200.
Thanks.

**Comment by favorit5503** [comment]
[Uploading ums_dbg_2024-05-14-12-18.zip…]()

**Comment by SurfaceS** [comment]
@favorit5503 
the debug file is not there.
Upload it pls.

**Comment by favorit5503** [comment]
[ums_dbg_2024-05-14-12-18.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15307477/ums_dbg_2024-05-14-12-18.zip)

**Comment by favorit5503** [comment]
Sorry. It didnt upload the first time.

**Comment by SurfaceS** [comment]
For a strange reason, your TV is asking a `null` `objectId`, what is not DLNA permitted.

```
    <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
            <ObjectID/>
            <BrowseFlag>BrowseDirectChildren</BrowseFlag>
            <Filter>*</Filter>
            <StartingIndex>0</StartingIndex>
            <RequestedCount>30</RequestedCount>
            <SortCriteria/>
        </u:Browse>
    </s:Body>
```

Previous implementation are allowing this, so I fixed it in #4652 and add some NPE handle.

**Comment by favorit5503** [comment]
Thank you i will test when its available and report back.

**Comment by SubJunk** [comment]
@favorit5503 thanks for reporting, I will upload the fixed version to Patreon for you

**Comment by SubJunk** [comment]
That's done at https://www.patreon.com/posts/v14-quick-fixes-104283462

**Comment by favorit5503** [comment]
Thank you! I tested it works.

**Comment by SubJunk** [comment]
@favorit5503 thank you for confirming
