### ISSUE TITLE
UMS 5.0.0 java7 and ums 5.0.0 java8 for OS X cannot parse film titles containing German umlaut

### ISSUE THREAD

**Issue by jashanti** [UniversalMediaServer/UniversalMediaServer#466]
Wheras the Java6 version of UMS for OS X has no problems with film titles containing German umlauts like "ö", "ä", "ü", the versions of Java7 and Java8 produce error statements like "cannot handle ..." and ignore the corresponding videos. This is on OS X Yosemite 10.10.1.

**Comment by SubJunk** [comment]
@jashanti please provide logs by following these instructions: http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556
Two sets of logs would be great in this case - one from the Java 6 version and one from Java 7 version.

@skeptical any idea why this would be?

**Comment by jashanti** [comment]
Thanks for responding so quickly. 
I've created the log files that you wanted. In the Java 6 version there are no error messages.
Unfortunately I cannot upload the files here. So you can find them at uploaded:
http://ul.to/gkwnf388
http://ul.to/dufyvrq1

**Comment by skeptical** [comment]
@jashanti please post the logs to [this thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656) in the ums forum.  Uploaded is behind captcha and only allows 1 free download per hour :).

**Comment by jashanti** [comment]
Just now I realized, that the freshly arrived 5.1.0 version of UMS has the same bug even in the Java 6 version, which worked fine in 5.0.0. Seeing this I checked 5.0.1 Java6 and found the bug there, too.

**Comment by Sami32** [comment]
@jashanti Did the latest UMS version solved this issue ?
Your log is not accessible anymore, and i din't found it on the thread in UMS forum.
So, if it's not solved, could post your log following these instruction, please:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by Nadahar** [comment]
@Sami32 I don't think it's solved, AFAIK this is because MediaInfo can't handle non Latin-1 for Linux and OS X. There's an open bug at MediaInfo (or, it was open the last time I checked and it was hinted that someone would have to pay money for it to be fixed). The strange thing is that the bug weren't there with older versions, but it could be as simple as an updated renderer profile (that use MediaInfo while it didn't used to). There are some other issue (or forum thread) where this has been discussed quite a bit, I'm not sure there's anything we can do from UMS' side to solve this.

**Comment by Sami32** [comment]
@Nadahar Thanks for your feedback :-)
I didn't know it was fine with older version. It could be useful to find which one.
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/355

**Comment by jashanti** [comment]
@Sami32 The problem is not solved in the latest version. The last version that works is 5.2.3 (Java 6)

**Comment by Sami32** [comment]
@jashanti Thanks for you feedback :+1:

Don't worry if this issue is closed because we already have the same issue report, so it will not forgotten, but it's look like it's not an UMS problem
AFAIK Java 6 handle unicode not the same way as the latest version.
