### ISSUE TITLE
Broken string replacement on Java GUI

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4668]
The Crowdin one 

![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/7c973a03-7888-4e35-bcce-9994f1db9dae)

**Comment by SurfaceS** [comment]
this seems to be a really old bug.

**Comment by SubJunk** [comment]
No we don't have really old bugs... 🤣
