### ISSUE TITLE
Push from the UMS interface doesn't work

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#4682]
We offer the ability to push media from the UMS interface to renderer. See https://support.universalmediaserver.com/guides/how-to-play-media. I found the problem in the version 14 see the [debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15381737/debug.log)
Version 13 is working well.

EDIT: it seems to me like the access control problem or if we remove that feature we should delete it in guide and remove the UMS interface support.

**Comment by SubJunk** [comment]
Oh that's a big bug, I know some users rely on that feature. Any ideas about what might have broken it @SurfaceS ?

**Comment by SurfaceS** [comment]
should be fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4684

**Comment by SurfaceS** [comment]
> it seems to me like the access control problem

@valib 
No, as you may want to send a media to children for example, even if they do not have access to the folder.
