### ISSUE TITLE
The wrong numeration in 14's series.

### ISSUE THREAD

**Issue by MEGAKNIGHT88** [UniversalMediaServer/UniversalMediaServer#4694]
An insignificant but quite important for browsing bug found in new version.
![изображение_2024-05-26_074155344](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/170844881/b6acdc7d-e174-45c3-9159-6b15f819ff86)

**Comment by SurfaceS** [comment]
will be fixed in next release that coming soon.

**Comment by SubJunk** [comment]
This would be quite easy to add automated tests for in Playwright too, to protect against regression
