### ISSUE TITLE
To make a new category called "Specials".

### ISSUE THREAD

**Issue by MEGAKNIGHT88** [UniversalMediaServer/UniversalMediaServer#4696]
For an enhancement. It will be very comfortable and easy to find! Now it is in "All videos" category.

**Comment by SurfaceS** [comment]
I think you are talking about specials episodes ?

If so, you need to rename your files as specials episodes are in season 0.

eg : [Aladdin specials : Introduction Season 1](https://www.themoviedb.org/tv/2745-aladdin/season/0/episode/1)
you can see it is in `/season/0/episode/1`

So if filename contains `S00E01`, it will be founded.

**Comment by SurfaceS** [comment]
Season 0 will be named 'Specials' in next major release.

**Comment by MEGAKNIGHT88** [comment]
> Season 0 will be named 'Specials' in next major release.

No, I mean special movies like this ones: https://www.themoviedb.org/movie/74622
https://www.themoviedb.org/movie/72886-mortal-kombat-the-journey-begins

It is only can be viewed in the folder with all videos.

**Comment by SurfaceS** [comment]
Yes, that exactly what it is.
If TMDB say it is a movie, it should be on movies.

Specials are special media/episodes/movies related to a TV Series.
They are name under season 0.

This film for example is under TV Series : https://www.themoviedb.org/tv/12786-murdoch-mysteries/season/0/episode/29

So either theses specials movies are not well stored in TMDB, either they are real films. But we cannot change it like that.

**Comment by MEGAKNIGHT88** [comment]
Thank's again for a reply!
