### ISSUE TITLE
Folder sorting does not work by date - 14.0

### ISSUE THREAD

**Issue by mykeehu** [UniversalMediaServer/UniversalMediaServer#4698]
I had no problem reordering the folders in version 13, but now, even though it's set to show the latest by date, it still shows the folders in alphabetical order on the TV, so it's hard to find the latest movies.
Please fix this! 

[ums_dbg_2024-05-26-12-11.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15447054/ums_dbg_2024-05-26-12-11.zip)

**Comment by SurfaceS** [comment]
> even though it's set to show the latest by date

where/how ?

If it is from TV, I don't see any sorting asked from your TV on your log.
`<SortCriteria/>` are all empty

**Comment by mykeehu** [comment]
> If it is from TV, I don't see any sorting asked from your TV on your log. `<SortCriteria/>` are all empty

This is the problem. Because in the UMS settings (web or old version) the sorting is set.
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/6390413/566ebc26-8f32-49d6-94e5-7eb854e5ea4a)

In addition, even if the web settings are set to English, the display is in Hungarian:
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/6390413/4b3bb63f-4384-44da-aa31-4c510e826f90)

**Comment by SurfaceS** [comment]
will be fixed in next release that coming soon.

**Comment by mykeehu** [comment]
I just installed version 14.1 because it just became available to me.
Unfortunately the error persists. No matter what I set for file sorting, the folders are not reordered. I reverted back to version 13.10 and it worked fine there, 14.x versions do not sort well.

**Comment by SurfaceS** [comment]
Are you talking about folders under `Media Library` (that has and should have their own sorting) ?

Can you try to browse a direct folder on the ums gui player ?
`Your folders` -> `Filmek`
If it this one is not ordered, then I'll need debug log to understand.

**Comment by mykeehu** [comment]
So whatever I choose under the **File order** option, when I go into a folder on TV, the subfolders are always in alphabetical order. Up to version 3.10, the order was fine, i.e. if I chose the order sorting to the last modification under **File order** option in UMS, the last updated folder was also on top on TV. Now whatever I change, the order of the folders does not change, I get alphabetical sort always.

**Comment by SurfaceS** [comment]
> the last updated folder was also on top on TV.

@SubJunk 
About the `File order:` parameter :
Does the folders need to be ordered as well ?
Only files are for now.

**Comment by mykeehu** [comment]
Yes, it would be necessary to sort the folders (even with an extra parameter), because they were sorted before, not just the files. This way, I can find the folder where I last uploaded pictures or videos faster.

**Comment by mykeehu** [comment]
This is how it worked in version 13:
- Sort by ABC:
- - Apple folder
- - Banana folder
- - Carrot Folder
- - AFile
- - BFile
- - CFile

By modified date:
- - Banana folder
- - Carrot Folder
- - Apple folder
- - CFile
- - AFile
- - BFile

So folders are always placed first by modification date, and files come after, if there are multiple folders and files in a folder.

**Comment by mykeehu** [comment]
[Fixed in 14.3.0](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4814) Thank you!

**Comment by SubJunk** [comment]
Thank you for confirming!
