### ISSUE TITLE
Samsung TV UE40ES6500 does not work with new version 14.0.0

### ISSUE THREAD

**Issue by si70so15** [UniversalMediaServer/UniversalMediaServer#4713]
I have updated UMS to version 14.0.0, but after upgrading UMS my Samsung TV UE40ES6500 displays immediately the message "The request cannot be completed" when the TV connecting to UMS.
With the old version 13.10 everthing work fine.

I have attach the log.

Thank you very much
Simon
[ums_dbg_2024-05-27-20-50.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15459243/ums_dbg_2024-05-27-20-50.zip)

**Comment by SurfaceS** [comment]
```
TRACE 2024-05-27 20:47:20.270 [jupnp-sync-protocol 617-1] Received a request from 192.168.1.197:
================================== HTTPSERVER REQUEST BEGIN =====================================
POST /dev/7e98e011-5d6f-4e6b-b782-1bb3f2dd61ba/svc/upnp-org/ContentDirectory/action HTTP/1.1

HEADER:
  Accept: */*
  Connection: close
  Host: 192.168.1.65:5001
  User-agent: SEC_HHP_[TV]UE40ES6500/1.0 DLNADOC/1.50
  Content-type: text/xml; charset="utf-8"
  Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
  Content-length: 452

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
            <ObjectID>D</ObjectID>
            <BrowseFlag>BrowseDirectChildren</BrowseFlag>
            <Filter>*</Filter>
            <StartingIndex>0</StartingIndex>
            <RequestedCount>30</RequestedCount>
            <SortCriteria/>
        </u:Browse>
    </s:Body>
</s:Envelope>
================================== HTTPSERVER REQUEST END =======================================
TRACE 2024-05-27 20:47:20.271 [jupnp-sync-protocol 617-1] Matched media renderer "[TV]UE40ES6500" based on address 192.168.1.197
DEBUG 2024-05-27 20:47:20.271 [jupnp-sync-protocol 617-1] Recognized media renderer "[TV]UE40ES6500"
DEBUG 2024-05-27 20:47:20.271 [jupnp-sync-protocol 617-1] Bad id D found in path
DEBUG 2024-05-27 20:47:20.272 [jupnp-sync-protocol 617-1] Trying to browse direct children on a null object for objectID 'D' !
TRACE 2024-05-27 20:47:20.279 [jupnp-sync-protocol 617-1] Send a response to 192.168.1.197:
================================== HTTPSERVER RESPONSE BEGIN ====================================
HTTP/1.1 500 Internal Server Error

HEADER:
  Ext: 
  Server: Windows11/10.0 UPnP/1.0 UMS/14.0.0
  Content-type: text/xml;charset="utf-8"

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>UPnPError</faultstring>
            <detail>
                <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
                    <errorCode>701</errorCode>
                    <errorDescription>The specified ObjectID is invalid</errorDescription>
                </UPnPError>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
================================== HTTPSERVER RESPONSE END ======================================
```


`<ObjectID>D</ObjectID>` !!

**Comment by si70so15** [comment]
Hello surfaces
Sorry, but I don’t understand your message.
Should I do something with the content of your message?

Thank you very much.
Simon

**Comment by SubJunk** [comment]
The TV has requested something with the ID `D` which is strange. I can't see anything in the logs where we are telling the TV we have anything with that ID. It is interesting that it did not happen on v13

**Comment by si70so15** [comment]
Hi,
The TV's behavior is erroneous. Whenever I connect it to UMS version 13.10, the popup will always display options for content (Video, Music, or Photos), while with UMS version 14.00, the message 'The request cannot be completed' appears immediately.
To help you to understanding the trouble, I have attached the log created from UMS version 13.10 and the log from UMS version 14.0 also.

Thank you very much.
Simon.
[ums_dbg_2024-05-29-20-08 ver 13.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15489688/ums_dbg_2024-05-29-20-08.ver.13.zip)
[ums_dbg_2024-05-29-20-37 ver 14.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15489689/ums_dbg_2024-05-29-20-37.ver.14.zip)

**Comment by SurfaceS** [comment]
this should be fixed in the next release

**Comment by si70so15** [comment]
It's a good news.
Only one thing, the next version will be the 14.0.1, now released on Patreon, or another new one?
Thank you very much SurfaceS.

**Comment by SubJunk** [comment]
I can upload the fixed version for you, are you on Patreon or do you want it posted here?

**Comment by si70so15** [comment]
HI SubJunk,
I'm not on Patreon, if you can posted here please.
Thank you very much
Simon

**Comment by SubJunk** [comment]
@si70so15 here is the download link, please let me know when you have downloaded it so I can remove it https://www.universalmediaserver.com/uploads/UMS-si70so15.exe
Thank you for reporting the bug and helping us improve!
