### ISSUE TITLE
UMS 5.0 causes high CPU usage (10%) when GUI is visible

### ISSUE THREAD

**Issue by netx123** [UniversalMediaServer/UniversalMediaServer#472]
I've noticed that when running UMS 5.0 Java 8, on Windows 7 64bit, the CPU usage for the javaw.exe process stays at around 10% when the GUI is visible but returns to 0% when GUI is minimized..

Steps to reproduce.
1) Start streaming any video
2) Pause the video
3) With the GUI visible the javaw.exe process runs at around 10%
4) Minimize the GUI, the javaw.exe process immediately return to 0% CPU utilization

**Comment by valib** [comment]
@netx123 It is not an issue it is a feature :) We implemented in the GUI new information like memory ussage, rotating media playing name and so on whose when are repeatedly displayed consume the CPU power. But users have choice to minimalize the GUI and save the CPU power.

**Comment by netx123** [comment]
OK I'll take your word for it, 10% CPU though still sounds very high just for a rotating media name, memory usage etc.
