### ISSUE TITLE
UMS V14 Bugs Media marking fully played

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4728]
Hello,
UMS no longer marks the media in the whole of version 14, I checked with the web player nothing was marked on the episodes that were read on TV
UMS displays “marked as fully played” on the first 2 videos, the last video (Outlander) I read in full but was not marked either, I cut it in the last 10 seconds before the episode change.
Unmarked video fully play:
Special Ops Lioness S01E01
Special Ops Lioness S01E02
Outlander S07E01

![Capture d’écran 2024-06-04 012730](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/3a704fd9-98d6-4256-8400-08ebd87f0a5f)
![Capture d’écran 2024-06-04 012849](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/2d7e6afe-e462-462f-832d-b5e214324438)
![Capture d’écran 2024-06-04 012917](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/3665d6d3-a5e2-40d8-ad3a-4237f83e03fa)
[ums_dbg_2024-06-04-01-24.zip](https://github.com/user-attachments/files/15540880/ums_dbg_2024-06-04-01-24.zip)

**Comment by SubJunk** [comment]
I can see you are logged in to the web player as `Fredo`, you might need to assign that same user to your TV to get them showing the same information, or use your web player as the same user as your TV

**Comment by Fredo1650** [comment]
Hello, that's indeed it, I activated the option "authenticate the local host as administrator" because there is no connection identification on the television, but that does not explain the bug on certain videos which are played entirely until the passage of the other episodes "Outlander S07E01, S07E2" 
(S07E01 first post) [ums_dbg_2024-06-04-01-24.zip](https://github.com/user-attachments/files/15540880/ums_dbg_2024-06-04-01-24.zip)
final decision: not fully played because the video was started within 2 seconds of the end, usually meaning it was an automatic parsing request

Episode 3 was marked but in the logs I have 2 final decisions for the same video:
final decision: fully played
final decision: not fully played because the video was started within 2 seconds of the end, usually meaning it was an automatic parsing request
![Capture d’écran 2024-06-05 024518](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/025c711d-2c4e-4ada-bd5d-2a497aac4acd)
[ums_dbg_2024-06-05-02-17.zip](https://github.com/user-attachments/files/15571784/ums_dbg_2024-06-05-02-17.zip)

**Comment by SubJunk** [comment]
@Fredo1650 I see, I have an idea how to make it more reliable by using a real timer in those cases. I will try to get a test build to you in the next few days

**Comment by SubJunk** [comment]
@Fredo1650 can you please test this fix and let me know when you have downloaded it? https://www.universalmediaserver.com/uploads/UMS-4728.exe

**Comment by Fredo1650** [comment]
I just tried the UMS-4728 Test version, it works correctly the media is well marked, I performed the test on a single video.
I will do another test on several videos this weekend to confirm
I post the logs of the test version if you want to perform analyses of this modification
Thank you very much.
[ums_dbg_2024-06-13-20-17.zip](https://github.com/user-attachments/files/15827843/ums_dbg_2024-06-13-20-17.zip)

**Comment by SubJunk** [comment]
@Fredo1650 great, thanks for letting me know! I look forward to seeing how the other videos go too
