### ISSUE TITLE
Xbox 360 dont play some movies with external subtitles

### ISSUE THREAD

**Issue by bigfatblue** [UniversalMediaServer/UniversalMediaServer#473]
What to do? I tried diffrent srt files but problem still exist. When i watch movie from computer then everything is fine. And when i stream movie with no srt to Xbox then it works.

I only have that issue with one movie: Lets be a cops
I use latest UMS.

**Comment by skeptical** [comment]
@bigfatblue if you mean "*Let[**'**]()s be Cops*", @valib just yesterday [Fixed support for subtitled files with apostrophes in the name](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/f847994acdbb4359ff32f1c7e676e0cf4efa3458), so hang on till the next release :)

**Comment by Sami32** [comment]
@bigfatblue Did the latest UMS version solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**EDIT**: Except if it was specific to XBOX 360, i don't have this problem with the actual version on Windows.

**Comment by polygirl** [comment]
@bigfatblue it looks as though this has been resolved so we're closing.  If it's still an issue for you please provide further file information and full TRACE logs.
