### ISSUE TITLE
nice tool; real streaming that simple work to TV; but why you choose java lang.....

### ISSUE THREAD

**Issue by mzayarnyuk** [UniversalMediaServer/UniversalMediaServer#4738]
nice tool; real streaming that simple work to TV; but why you choose java lang.....
what about build to arm 1709 uwp with C#

**Comment by SurfaceS** [comment]
UWP -> Universal Windows Platform
we target linux/mac/windows/docker and so on, so no point here, it will need bridge everywhere.

C# -> C# and java are quite similar languages. https://en.wikipedia.org/wiki/Comparison_of_C_Sharp_and_Java
Also, JVM which is free open-source software with OpenJDK.
