### ISSUE TITLE
Folder refresh with empty folders hidden

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#475]
It seems that when "hide empty folders" is enabled, if a video is added to that folder, the folder won't be shown until the program is restarted. We should fix this.

http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2914

**Comment by Jensaarai** [comment]
I attempted to fix this with https://github.com/Jensaarai/UniversalMediaServer/commit/49e856f6df96dc6327b4c1aa6e92dc0fd19291ad but as the comment says I was unsuccessful :( I think I figured out the general gist of what needs to happen, but I'm too unfamilar with the overall codebase and program execution flow to know the proper way to implement the fix. I left notes from what I looked at, though, so hopefully someone more experienced with this project can pick it up from where I left off :)

**Comment by taconaut** [comment]
@Jensaarai From the top of my head I'd say the isRefreshNeeded() method in MapFile has to check if a previously empty folder (which has been hidden) now contains files.

**Comment by Jensaarai** [comment]
Thanks @taconaut ! Seems so obvious now...very close to the solution I had, except the isRefreshNeeded() function didn't actually check the empty folder(s), it just returned True if we had empty folders we were keeping track of, so a re-check would fire.

I added a call to FileUtil.isFolderRelevant for each "empty" folder in isRefreshNeeded() and that seems to solve the issue https://github.com/Jensaarai/UniversalMediaServer/commit/c5eb4eb73eca3e43e239e62abfbe4f317fd8c3e1 I'll clean up this branch later and submit a pull request, gotta go to work now. Thanks!

**Comment by Jensaarai** [comment]
Created pull request https://github.com/UniversalMediaServer/UniversalMediaServer/pull/567

**Comment by taconaut** [comment]
@Jensaarai Dood job! Glad I could point into the right direction. Creating the DlnaResources for pms-mlx and now ums-mlx gave me some headaches at some points ;)

**Comment by Sami32** [comment]
@subjunk Done https://github.com/UniversalMediaServer/UniversalMediaServer/pull/567/commits/c8a90fdf11a12c0174a6d443733068fa13689d4b
