### ISSUE TITLE
MOV detected as MP4

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#477]
If a renderer lists MP4 as a supported container (f:mp4), UMS thinks it is the same as a MOV container so it streams it.

Many renderers support MP4 files but not MOV files so in those cases, issues are occurring when they try to play MOV files.

**Comment by valib** [comment]
@SubJunk fixed in 3c227ef

**Comment by SubJunk** [comment]
@valib nice one!
