### ISSUE TITLE
Folder order broken

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4771]
a bug was recently introduced where the folders that are supposed to be at the top of results, like “Filter by Information” are instead mixed in with the regular results. For example the contents of:

Media Library -> Video -> TV Shows

appear on my tv as:

Apple
Filter by Information
Pear

while before it was:

Filter by Information
Apple
Pear

@SurfaceS it was probably that recent ordering story, can you look into it please?

**Comment by SurfaceS** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4772
