### ISSUE TITLE
FFmpeg bug - FFmpeg trac ticket 11055

### ISSUE THREAD

**Issue by markfilipak-windows** [UniversalMediaServer/UniversalMediaServer#4776]
Greetings,

This is not a problem with UMS, it's a problem _for_ UMS (and for the MPV player and others that depend on FFmpeg for time stamps).

https://trac.ffmpeg.org/ticket/11055 is a bug report in the FFmpeg trac bug system. It has been downgraded from "important" to "normal". That means it will be shelved along with hundreds of other 'normal' bugs that are decades old.

I'm a very experienced FFmpeg user. I'm a professional engineer, retired. The bug is a time stamp bug. The "Summary of the bug" is all you need read. I firmly believe that this bug is a duplicate of many, many other bugs that sit in FFmpeg's trac system labeled 'normal' priority.

If you take the 4 second sample here:
  https://streams.videolan.org/ffmpeg/incoming/11055/Ticket_11055.m2ts
and run the scripts listed at the bottom of "Summary of the bug", you will see the problem. The results are summarized in the listing that forms the bulk of "Summary of the bug".

I strongly suggest that this bug does impact UMS.

I have not been able to coax the users in the ffmpeg-users mailing list into action.

Note that Ticket_11055.m2ts plays fine in VLC and PowerDVD but not in MPV. I'm quite convinced it doesn't play well in MPV due to FFmpeg returning bogus timestamps. From what I have read here, UMS works around bogus time stamps returned by FFmpeg.

Regards,
Mark Filipak.
mark[remove_this_box]filipak.imdb[@_sign_here]gmail.com

**Comment by SubJunk** [comment]
Thanks for the tip. It's an interesting discussion over there and in the new one https://trac.ffmpeg.org/ticket/11080
There isn't anything for us to do though so I'll close this. Good luck getting the fix in FFmpeg and hopefully UMS can benefit from it
