### ISSUE TITLE
Increased false-matches from API recently

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4777]
I have some very bad TV series matches from our API lately. One is:
`From` -> `Chillin' in My 30s after Getting Fired from the Demon King's Army`
and
`Diagnosis` -> `Diagnosis: Murder`

So it seems it is accepting very partial matches.

Edit: It seems like the client might eventually get the correct IMDb and TMDB IDs, so it can be hard to debug. But I managed to get this URL https://api.universalmediaserver.com/api/media/series/v2?title=From which returns `3rd Rock from the Sun` instead of `From`

**Comment by SubJunk** [comment]
I'm working on this

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers I wrote [a test on the API](https://github.com/UniversalMediaServer/api/pull/1351/files#diff-60de45fa289ca661f141f39c71777c14d290b4a0e8e9699c553203dce6a84254R91-R105) to try to reveal this bug, but it did not cause the bug, so I am still unsure about it. Do you have any ideas about what would cause [that URL](https://api.universalmediaserver.com/api/media/series/v2?title=From) to return `3rd Rock from the Sun`?

**Comment by SubJunk** [comment]
@SurfaceS just tagging you in case you missed this, no problem if you haven’t had time

**Comment by SurfaceS** [comment]
I had a lot of cloudflare reject this time on tmdb (that's why I handle it now on the direct tmdb api).

Maybe you had some of this when first requesting "from", then you fall back to an already know tv series ?
And now it is linked in db, so you still have it as a result ?

**Comment by SubJunk** [comment]
It's a good idea, I'm trying to see how it could happen. I have a lot of bad results in my list of series now, and I am worried that it is similar for our users.

The results from searching for `from` on TMDB do not include `3rd Rock From the Sun` unfortunately, and the first result is the correct one.

There is a way to poison the TV series results by passing in a valid IMDb ID with a wrong title, and then the API server will save the wrong title in the list of `searchMatches`. But I don't know how likely that is to happen, or to be the cause of this problem. I will try to fix that anyway in case it is the problem.

**Comment by SubJunk** [comment]
The fix for that idea is at https://github.com/UniversalMediaServer/api/pull/1356 but I am still not sure if that's this

**Comment by SurfaceS** [comment]
> The fix for that idea is at [UniversalMediaServer/api#1356](https://github.com/UniversalMediaServer/api/pull/1356) but I am still not sure if that's this

yes, that should do the trick.
as you do not have to save the search in case imdbId is found.

but here as well it should not save the title if found.
```
    if (seriesID) {
      const seriesRequest = {
        append_to_response: 'images,external_ids,credits',
        id: seriesID,
      };

      const tmdbResponse = await tmdb.tvInfo(seriesRequest);
      tmdbData = mapper.parseTMDBAPISeriesResponse(tmdbResponse);
    }
```

before ending the condition, you should clear title things.
 
```
if (tmdbData && !_.isEmpty(tmdbData)) {
      titleToCache = null;
      searchMatch = null;
}
```

**Comment by SubJunk** [comment]
Good point, that is done at https://github.com/UniversalMediaServer/api/pull/1359
I will deploy and refresh the database and see what happens

**Comment by SubJunk** [comment]
That has been deployed now and the URL is still returning `3rd Rock From the Sun` instead of `FROM`. I will see if there are any clues in the db

**Comment by SubJunk** [comment]
```
    searchMatches: [
      'From',
      '3rd rock',
      '3rd',
      '3rd Rock from the Sun',
      'Cosas de Marcianos',
      'from',
      '3rd Rock'
    ],
```

**Comment by SubJunk** [comment]
The DB has 3 results for the `searchMatch` `From`:
```
api_mongo> db.getCollection('series_metadata').find({searchMatches: {$in: ['From']}}, {title: 1})
[
  { _id: ObjectId('6687c049e777196229cf644e'), title: 'FROM' },
  {
    _id: ObjectId('6687cb3477b37097d621402e'),
    title: "Chillin' in My 30s After Getting Fired From the Demon King's Army"
  },
  {
    _id: ObjectId('6687d555e4e69b88526773db'),
    title: '3rd Rock from the Sun'
  }
]
```
But it is hard to make it save that way unless very wrong data is being searched.

If UMS client searched for `title=From&year=1996` I think that would find and populate `3rd Rock from the Sun` as `From`, because TMDB returns `3rd Rock From the Sun` in that case and we would trust it. But I don't know how likely it is that would happen.

**Comment by SubJunk** [comment]
When that `searchMatch` is populated I can see why it always returns 3rd Rock - we have a query that does `sortBy['startYear'] = 1` but I don't see realistically how it is populated that way.
Any other ideas?

**Comment by SubJunk** [comment]
It might be fixed now but I'll have to look at my list in a couple of days to see if it happens again

**Comment by SubJunk** [comment]
No, it happened again https://api.universalmediaserver.com/api/media/series/v2?title=From

**Comment by valib** [comment]
Try this
https://api.universalmediaserver.com/api/media/series/v2?title=from
Seems like it is made by capital letter in title

**Comment by SubJunk** [comment]
@valib when I go to that page it says `"title":"Daughter from Another Mother"`

**Comment by valib** [comment]
> @valib when I go to that page it says `"title":"Daughter from Another Mother"`

@SubJunk strange! Yesterday it worked for me and now I have the same result.

**Comment by SubJunk** [comment]
:/ somehow the `searchMatches` must be getting polluted but I don't know how. I'll look at the code again. If I can't see it I will add a logging service to the API server so we can trace the path of the events

**Comment by SubJunk** [comment]
Ah I have found the problem thanks to a lot of logging. Someone is searching for `title=From&year=2023` and we pass that on to TMDB, which makes it find `Chillin' in My 30s After Getting Fired From the Demon King's Army` because that is something that contains "from" and started in 2023.

```
tmdbQuery: {
  query: "From",
  first_air_date_year: 2023
}
seriesTitle: "From"
searchResult: {
  adult: false,
  backdrop_path: "/6Z8uMC4Bj30dbYKc3LkQbpXx4eA.jpg",
  genre_ids: [
    16,
    10759,
    10765
  ],
  id: 206324,
  origin_country: [
    "JP"
  ],
  original_language: "ja",
  original_name: "解雇された暗黒兵士（30代）のスローなセカンドライフ",
  overview: "Dariel, a dark soldier in the demon king's army who cannot use magic, has risen to the position of assistant to the Four Generals with his talent and energy, and has been wielding his skill. However, as soon as the Four Generals are replaced, Dariel is fired from the army. Dariel is devastated, but when he arrives in a human village, he finds that his adventuring skills, which are supposed to be useless to demons, have blossomed! "I was... human?" Dariel decides to spend his second life in this village, and the requests start pouring in! Trouble! False charge! Duel! With his natural skills and the adjusting power that he developed in his old place, the former dark soldier solves them all!",
  popularity: 76.925,
  poster_path: "/wt3y5uru1yaHRHl8KUZ68HqcaMv.jpg",
  first_air_date: "2023-01-07",
  name: "Chillin' in My 30s After Getting Fired From the Demon King's Army",
  vote_average: 7.2,
  vote_count: 30
}
```

**Comment by SubJunk** [comment]
I think it is fixed now but I will leave this open for a couple of days in case it comes back. It also might happen for other series in rare cases but I hope we will have a very high success rate now

**Comment by SubJunk** [comment]
It seems to have worked
