### ISSUE TITLE
Stop calculating OpenSubtitles hashes

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4778]
These are no longer used by the API so we do not need them. Some operations should get a bit faster when it is removed

**Comment by SurfaceS** [comment]
As OpenSubtitles is not anymore serving (OpenSubtitles.org XmlRPC API was turned off), I think we could also delete completely OpenSubtitles things ?

@SubJunk what do you think about it ?

**Comment by SubJunk** [comment]
Cool, yes I think it can all go. I think it is paid now unless they changed that. The "Live Subtitles" feature can go too. It's a shame because that was a cool feature
