### ISSUE TITLE
Re-enable self-originating requests

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#478]
It seems there is a problem with self-originating requests and BubbleUPnP Server: http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=2901#p14476

**Comment by valib** [comment]
@SubJunk it seem to me that it is solved here http://www.universalmediaserver.com/forum/viewtopic.php?t=2919

**Comment by SubJunk** [comment]
Oh very cool, thanks for pointing that out :)
