### ISSUE TITLE
PS4 transcoding broken

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4797]
I updated to V14.2.0 (via the build script) and found that nothing would would play correctly on the PS4 when transcoding. 

Strangely audio would play but the Playstation busy icons will remain on screen for a few seconds before coming up with the error that it cannot play.

I did a clean install just in case but has the same result.

Going back to 14.1.0 it works again.

Comparing the transcode commands between versions, V14.2.0 is missing options `-pix_fmt yuv420p` (I added spaces to line these up)
```
V14.2.0
Starting "C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe" -y -loglevel info -i "D:\Users\Mik\Downloads\Video\The Acolyte S01E05 - Night.mkv" -bufsize  9000k -maxrate 8000k  -crf 23 -ab 448k -c:a copy -c:v libx264 -preset superfast -level 31                  -f mpegts \\.\pipe\ffmpegvideo_95_1719854318995
V14.1.0
Starting "C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe" -y -loglevel info -i "D:\Users\Mik\Downloads\Video\The Acolyte S01E05 - Night.mkv" -bufsize 18000k -maxrate 17000k -crf 23 -ab 448k -c:a copy -c:v libx264 -preset superfast -level 31 -pix_fmt yuv420p -f mpegts \\.\pipe\ffmpegvideo_100_1719854827477
```

If I am understanding it right this is what it is being encoded as.
```
V14.2.0
    encoder         : Lavf61.3.104
  Stream #0:0: Video: h264, yuv420p10le(tv, bt709, progressive), 1920x804 [SAR 1:1 DAR 160:67], q=2-31, 24 fps, 90k tbn (default)
V14.1.0
    encoder         : Lavf60.21.101
  Stream #0:0: Video: h264, yuv420p    (tv, bt709, progressive), 1920x804 [SAR 1:1 DAR 160:67], q=2-31, 24 fps, 90k tbn (default)

```
[Mik V14.1_ums_dbg_2024-07-01-18-47.zip](https://github.com/user-attachments/files/16057471/Mik.V14.1_ums_dbg_2024-07-01-18-47.zip)
[Mik V14.2_ums_dbg_2024-07-01-18-19.zip](https://github.com/user-attachments/files/16057472/Mik.V14.2_ums_dbg_2024-07-01-18-19.zip)

**Comment by SubJunk** [comment]
Ah that’s my fault. Will fix it. It looks like FFmpeg is defaulting to 10-bit output which will be incompatible for older devices

**Comment by SubJunk** [comment]
That should be fixed by https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4798
