### ISSUE TITLE
Web GUI on 14.1.0 with Linux not working

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4803]
A few users on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=16043) have found that the web GUI is not working in 14.1.0 on Linux.

I had a look at their logs and did not see any errors but my best guess is something to do with the switch to Jetty.

**Boss** has done a bit of experimenting and found that it could be the react index.html

> The problem is: ums-14.1.0/web/react-client/index.html.
If I copy ums-14.0.2/web/react-client/index.html
to
ums-14.1.0/web/react-client/index.html
It all works fine. 

I am guessing this is just restoring Netty so something about Jetty is not working right on Linux, assuming it was this version that made the switch.

**Comment by SubJunk** [comment]
Probably one for you @SurfaceS 
Thanks for the issue @Mik-S-UMS

**Comment by SurfaceS** [comment]
Nothing related to Jetty.

We moved to vitejs build, and the build output hash had lower/uppercase on filename.
Linux is aware of case on filename, when windows is not.

I changed the hash in filename to always be lowercase.
