### ISSUE TITLE
File order still broken in 14.2.1

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4810]
We have this comment on Patreon:

Since version 14 came out, I have been experiencing a problem with folder and file sorting.  I was excited to see it was on the list in 14.2.1 and it does have some improvement, but certain folders still appear randomly ordered.
I am running the OSX ARM version.  I have the File Order set to "By Display Name".
All of the files within the folders are properly alphabetized.
However, folders themselves are randomly sequenced (or I just cannot see the pattern).  For example, folders may show up as:
  Season 2
  Season 1
  Season 3
Any ideas?

@SurfaceS

**Comment by SurfaceS** [comment]
I can't reproduce this.

Btw, expected output SEASONS and EPISODES are not children ordered, only sql sorted.

**Comment by SubJunk** [comment]
I have asked them to provide logs so we can see what's happening

**Comment by SubJunk** [comment]
Closing this for https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4814
