### ISSUE TITLE
14.2.1 File Sorting Issue

### ISSUE THREAD

**Issue by MandyD-coder** [UniversalMediaServer/UniversalMediaServer#4814]
Since version 14 came out, I have been experiencing a problem with folder and file sorting.  I was excited to see it was on the list in 14.2.1 and it does have some improvement, but certain folders still appear randomly ordered.
I am running the OSX ARM version.  I have the File Order set to "By Display Name".
All of the files within the folders are properly alphabetized.
However, folders themselves are randomly sequenced (or I just cannot see the pattern).  For example, folders may show up as:
  Season 2
  Season 1
  Season 3
Any ideas?

[debug.log](https://github.com/user-attachments/files/16215303/debug.log)
![image](https://github.com/user-attachments/assets/d7f64c05-a555-40cf-8332-32f330e1c650)
![image](https://github.com/user-attachments/assets/f6392486-ff5a-4106-bfd6-a20e2cc61357)
![image](https://github.com/user-attachments/assets/896f27ee-c0f1-478c-afe2-95d0f3c20161)

**Comment by SubJunk** [comment]
@MandyD-coder thanks for the logs, but we need the full log package after reproducing (loading the page) in order to see enough information. The instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new
We can't reproduce the problem so need to rely on the detailed logs

**Comment by pb-audio** [comment]
I've seen the same issue when using vlc and Yamaha Musicast players, running UMS 14.0.2 and now 14.2.0 on Ubuntu Linux.  I spent some time looking at it today.  The folders aren't in random order, they're in unsorted (ls -f) order.  Ordinary files are sorted properly when there is a mix of files and folders inside the same folder.

**Comment by SubJunk** [comment]
Thanks @pb-audio for that tip, I have reproduced it now, so I don't need those extra logs anymore @MandyD-coder :)

@SurfaceS I have reproduced it on macOS with that hint about `ls -f`, but it is a bit difficult. First I made a new folder, and made three new folders inside that in this order `Carrot`, `Apple`, `Banana`, but `ls -f` output them in alphabetical order still. Then I copied in an existing folder I created last year and I reproduced it:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/070bde15-c813-42e2-b5d1-393adebd0457">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/92aa0353-fd18-4ac6-8348-201814d7c338">

**Comment by MandyD-coder** [comment]
Awesome!  Thanks, @SubJunk.  Please let me know if you need anything from my end.
On both the Settings and Old Settings, I have the file order as "By display name"

**Comment by SubJunk** [comment]
@MandyD-coder I uploaded the fixed version to https://www.patreon.com/posts/member-fix-bug-108270388
I tested and it worked for me, please let us know if it works for you

**Comment by MandyD-coder** [comment]
That fixed it! Thanks!
