### ISSUE TITLE
Per renderer information not clearing when file is detected as having stopped

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#485]
Usually when I stop playing a file, and the UMS logs say it has stopped playing, the GUI isn't updated; it still says the name of the file that was being played, and the small blue buffer bar can remain full.

**Comment by SubJunk** [comment]
Reported by another user at http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=3026&view=unread&sid=fede0960517d3afbdd5b3a4d1be1e740#p14990

**Comment by skeptical** [comment]
@SubJunk this doesn't happen for me, can you narrow it down a little? As usual context/logs would be helpful :).

**Comment by ExSport** [comment]
Are you httpv2 or v1? :-)
Dne 19. 2. 2015 13:50 "skeptical" <notifications@github.com> napsal(a):

**Comment by skeptical** [comment]
@ExSport usually v2 for me, but v1 is also stopping/clearing correctly here. Are you seeing the same behaviour?

**Comment by ExSport** [comment]
I am using v2 only. Will try to test it during the weekend when I will be
at parents home (PS3+Panasonic TV+LG TV).
Dne 19. 2. 2015 16:00 "skeptical" <notifications@github.com> napsal(a):

**Comment by SubJunk** [comment]
@skeptical I'll make logs for it soon, and as you already saw there's another mention of it (or a related issue) in http://www.universalmediaserver.com/forum/viewtopic.php?p=15035#p15035

**Comment by SubJunk** [comment]
In the following logs I played test.mkv and stopped it, and UMS didn't detect that it had stopped. Then I played test2.mkv and then it registered that test.mkv had stopped, and it gave the error:

```
Unexpected input stream removal
java.lang.ArrayIndexOutOfBoundsException: -1
```

Which I hadn't got before now. Then I stopped playing test2.mkv and UMS detected it had stopped playing, but the Status tab still displays the word "test2". The per-renderer buffer cleared properly this time.

http://www.spirton.com/uploads/UMS/logs/20150221-NoStoppedPlayingDetection.zip

**Comment by skeptical** [comment]
@SubJunk does it happen if you set ```ffmpeg_mux_tsmuxer_compatible=false```?

**Comment by valib** [comment]
@skeptical it happens also for me. I tried to play video on the web page and when I close the browser during  the video was playing the file name was not cleared and also the icon of the browser remained active. Debug log put on http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15048#p15048

**Comment by skeptical** [comment]
@valib good point, We've seen similar usage-based issues before, like. shutting the renderer off while playing, or pressing 'play' again before the previous 'stopPlaying' event had registered, and so on. Will look at it.

**Comment by skeptical** [comment]
@SubJunk @valib 2ef3412 and cea8e76 attempt to fix some of the holes related to sudden death/disappearance when streaming.  Some issues remain, but please post logs to help narrow things :).

**Comment by ExSport** [comment]
@UniversalMediaServer/developers
Unfortunately short time what I was at home I fought with HDD going dead so I have no logs and deeper troubleshooting. What I spotted was parents new TV was displayed twice and inconsistently. Once as two different LG renderer profiles and other time as one LG renderer + cling info (LG renderer not connected to any renderer profile). What profile is used then?
One renderer is once detected as unknown, second time as iPhone (it is QNAS).
Another spot is about start/stop behavior. After short test I spotted when starting+stopping+starting+stopping+starting+stopping same file on TV, UMS logged start/stop behavior for every action except last one. So when I didn't played any other file after stop, it wasn't logged so last message was start action with missing stop action. Don't remember the GUI behavior sorry.
Another spot in log was spam about "SeekByTime" like:
``
DEBUG 22:01:59.264 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.264 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.264 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.264 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.264 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.265 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.266 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.266 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.266 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.267 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.267 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.267 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.267 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.267 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.268 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.268 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.268 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.268 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: "true" (previous: true, default: "")
DEBUG 22:01:59.269 [New I/O worker #6] Reading SeekByTime: true (previous: "true", default: false)
``

Hope it helps

![ums_duplicaterenderer2](https://cloud.githubusercontent.com/assets/1260408/6333323/6337d73c-bb8c-11e4-80c8-0e79b633cf33.png)
![ums_duplicaterenderer](https://cloud.githubusercontent.com/assets/1260408/6333322/6337308e-bb8c-11e4-8d26-79b710e8e785.png)

**Comment by skeptical** [comment]
@ExSport looks like your parents' shiny new LG may have a second (unrecognized) embedded renderer (providing 'webos-second-screen', whatever that is), possibly being picked up by this new [snippet](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/88c4edd003992448475b5a217a95784cec248232#diff-5d10b964428c945eb6e17c3873b0378eR279), too bad the logs are lost.  Not sure why the built-in icon was fetched on the first try but missed in the second (where ipad recognition failed similarly). These TVs are getting maybe too smart :-). 

Anyhow thx, will see if I can make any sense of it all :).

**Comment by ExSport** [comment]
@skeptical
The one (LG) without TV icon, when I clicked on it it wasn't linked to any
renderer and also it didn't ask for creating new one so I expected it is
what cling returned.
QNAS server once detected as iPhone and once as a unknown... Maybe Qnas
send two different replies or once it is detected via cling and once with
Netty?
Will try to catch some new logs remotely. Can't simulate renderer actions
but will try few ums restarts to have two different logs as on the
screenshots...
Thx

**Comment by ExSport** [comment]
@skeptical
I have logs for you:) http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15142&sid=bbb3dc8ead2b0bbfe0ea31d4f33f4b56#p15142
1: LG detected twice differently via defined renderer.conf + Yamaha receiver detected by cling(?) so UMS offers creating new renderer file for it (I suppose Netty doesn't support this behavior)
2: LG detected twice differently, once via renderer.conf and once ???. There is no option to create new conf as in previous example (Yamaha)
3: Yamaha detected twice differently, as unknown renderer and as Philips-Streamium (existing conf file)
Hope it helps. I only started and shutted down UMS many times to see different recognition without any user action on renderer side.

**Comment by ExSport** [comment]
@skeptical Should I redone logs with "visibility debug": http://www.spirton.com/uploads/UMS/UMS-1bbfc78.exe ?
DEBUG is enough or TRACE is better?

**Comment by skeptical** [comment]
@ExSport was just looking at your yamaha/streamium case and it seems one basic issue is the sequence/order of discovery events, so "visibility debug" could be useful since it probably would show yet another sequence (and make my head spin even more :-). TRACE is good.

**Comment by ExSport** [comment]
@skeptical : Nobody at home to switch on LG TV so for now logs with Yamaha only:
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15159#p15159
One log detected as Yamaha and one log as Unknown(without IP) and Philips/Stremium renderer.
Will provide logs with LG TV later...

**Comment by ExSport** [comment]
@skeptical I uploaded new logs with LG TV on: http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15168&sid=b627dcf96d8027c64b224f35603cad06#p15168
Log 1: LG TV detected as two different renderers (both via existing confs) + iPhone is Notebook. I don't have any Apple devices. Sometimes this IP is detected as iPhone, sometimes as Unknown renderer
Log 2: LG TV detected once via existing LG conf and once via ???. "IPhone" is detected twice! So sometimes I can see this IP as Unknown, other time as iPhone and sometimes as double iPhone.
Thanks for looking into it.

**Comment by ExSport** [comment]
@skeptical Maybe "Basic:1" should not be ignored completely (as mentioned in #494) as it includes some useful info as proper model name.
![lg_inspector](https://cloud.githubusercontent.com/assets/1260408/6430292/dd50616c-c003-11e4-9f43-1e301621af42.PNG)

**Comment by SubJunk** [comment]
Last night UMS detected a video as stopped when it was paused but I didn't save logs, I'll try to reproduce and keep logs

**Comment by skeptical** [comment]
@ExSport some late comments :)
* I didn't mention it specifically here, but bd1122b attempts to fix the "unknown renderer" part of this issue (which had to do with sessions where httpV1/V2 saw the renderer first).
* The misrecognitions are secondary, but the renderer confs need to be looked at
 * yamaha -> streamium (due to ```USER-AGENT=KnOS/3.2```)
 * LG WebOs -> LGLA6200 (due to dlna details ```LG Electronics. LG TV```)
 * Qnap Nas -> ipad (due to ```User-Agent= ... Twonky```). This one is fixable because we find out it's really a MediaServer when cling sees it later.

On Basic:1, since uuids are different we don't have a non-fuzzy way of knowing we're dealing with the same device (other than ip, but then we need to know beforehand it's not another software device at the same address), so we don't know enough to be sure the details can be merged.

**Comment by ExSport** [comment]
@skeptical @valib @SubJunk 
I am open to help in any way but must mention my limits:
- In most cases I am totally out of time so I am happy when I am able to monitor news via my Nexus 4 phone so I am also very limited to browse logs, find bugs, help fixing bugs etc. mainly from mobile :(
- Second problem is I don't have any smart TV at home. My tests, made fixes, reports etc. is from parents home where I am once in a month or two for a short time like a day so there is no room for deep testing. Most of my tests are via VPN without possibility to make real actions on renderers so I manly test renderer detection via UMS restarts etc.:)

About the "too smart" LG TV or QNAP recognition - they are new devices my brother bought to new house so now I checked it deeper remotely and I found that QNAP NAS has two DLNA servers inside. One native and one Twonky. Maybe this is root cause why UMS has problems in detecion sometimes...
When I will talk about "old" renderers in house like PS3 and Panasonic TV, I must say I spotted few months ago problem in UMS like maybe others:
- UMS detected PanTV but PanTV shown no DLNA server available. At time I closed UMS, TV shown UMS server in GUI and after a while it disappeared (because UMS was quitted). No logs unfortunatelly
- UMS detected new LG TV, TV displayed UMS is accessible. One behavior was that browsing folders worked but when I tried to play any file, it failed. Second behavior was that browsed folders were empty. Only what helped to LG to be working correctly was to first browse folders via e.g. my Android phone which fixed this weird behavior. When LG was first renderer browsing folders, there were problems but browsing with Android or PS3 first (or maybe with PanTV) fixed it on LG. Also forcing LG tv to be e.g. PS3 or PanTV fixed it.

I suppose all these weird problems started with dual detection. Behavior seems to be inconsistent like it depends on which engine first detects renderer, if Netty or Cling. Maybe this is the main problem why some others also have problems with renderer detection.
Question is if better to try update old buggy Netty or divide detection to only one engine, if it helps to detection problems.
...building custom version with edited https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/UPNPHelper.java#L549 to see if it is root cause of slow javaw.exe process termination on my system.

**Comment by ExSport** [comment]
When fake IP address or localhost network adapter is forced I expect no renderers will be found but if yes, it is a feature or a bug? :-)
As mentioned above, these renderers are visible for me with latest master code (and also with older builds):
```
WIFI Speaker: RenderingControl, ConnectionManager, AVTransport
Yamaha AV Receiver: RenderingControl, ConnectionManager, AVTransport
```

**Comment by ExSport** [comment]
@SubJunk @skeptical @valib 
Lame question. NTB without Eclipse installed and configured. Installed UMSBuilder_v2. Build from latest master branch created so all external dependences already downloaded, everything synced with local repository.
Now I edited one java file and started building again. New build ignores my changes like it is bulit from origin/master. How to recompile it with my modified file? Playing with git settings, omitting "git stash", using "git pull -s ours", nothing helps.
Thanks for guidance :+1:

**Comment by skeptical** [comment]
> and started building again.

Do you mean building via UMSBuilder_v2 or typing ```mvn compile``` etc? You can compile the edited current branch using a batch file like this ('mvnx.bat'):
```bat
echo off
set JAVA_HOME=c:\path\to\UMSBuilder\JDK-xxx
set M2_HOME=c:\path\to\UMSBuilder\Maven-xxx
set M2=%M2_HOME%\bin
set PATH=%M2%;%JAVA_HOME%\bin;%PATH%

::%M2_HOME%\bin\mvn.bat -o -Doffline compile
%M2_HOME%\bin\mvn.bat package
if "%errorlevel%" == "0" if not "%1" == "" %*
```

btw I should be posting a netty-free debug build that does all udp via cling soon (works, but need to check a few things still :-)

**Comment by ExSport** [comment]
@skeptical 
Thanks, will test it again but same I already did before:
```
call mvn -P windows package
call mvn -DskipTests -Doffline compile
git ... ways
```
Always when I manually modified some file in e.g. notepad and recompiled/rebuilded, I got same class, same ums.jar :)
Probably result of overworked or tired state of my mind :+1:

**Comment by SubJunk** [comment]
This is fixed
