### ISSUE TITLE
Web settings not loading

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4852]
The console shows `Error: [@mantine/core] Duplicate options are not supported. Option with value "AirPlayer" was provided more than once`
This was reported on Patreon and I reproduced it

I will work on this and am adding testing for it

**Comment by SubJunk** [comment]
This happens after you click the `Restart server` button

**Comment by SurfaceS** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4853
should be fixed
