### ISSUE TITLE
UMS 5.0.0: Bug with disabling renderers

### ISSUE THREAD

**Issue by ZestMyu** [UniversalMediaServer/UniversalMediaServer#486]
When I have all renderers enabled (total of 105 renderer configurations), my Playstation 3 is detected as a renderer and files can be played from it. 

Example of bug I've encountered:
Disable Nokia & Onkyo renderers, restart application, UMS log now shows only 9 enabled renderer configurations.
Also my Playstation 3 is now detected as an unknown renderer and files can not be played from it.

After re-enabling the Nokia & Onkyo renderers and restarting the application, UMS log will once again show 105 enabled renderer configurations and my Playstation 3 is once again a detected renderer.

This issue was not present in previous versions of UMS. I am able to recreate this problem 100% of the time. This issue is not limited to disabling the Nokia & Onkyo renderers, I only used those as examples.

**Comment by valib** [comment]
Thanks for reporting that bug. Fixed in  6d11493
