### ISSUE TITLE
Duplicate file and folders immediately after adding or removing new video file.  

### ISSUE THREAD

**Issue by KYFHO22** [UniversalMediaServer/UniversalMediaServer#4860]
Starting with one of the recent releases, I have noticed that both files and folders are duplicated in the listing on my Samsung TV immediately after anything is added/removed/changed within that specific folder.

A restart of the app fixes the issue until any other files or folders are changed.

This happens every single time anything changes.

Samsung TV Model - UN75RU9000FXZA
[ums_dbg_2024-07-28-17-04.zip](https://github.com/user-attachments/files/16405374/ums_dbg_2024-07-28-17-04.zip)

**Comment by SubJunk** [comment]
@KYFHO22 thanks for reporting this. Can you please try older versions to let us know when the bug appears? That will really save us time

**Comment by KYFHO22** [comment]
I ended up having to download some older versions to nail this down, but it looks like it is 14.1.0 where this issue may have been introduced.  14.0.0 seems fine.  One additional note:  I tested everything from renaming files, copying files into the same folder "with - COPY" suffixed to the file name, deleting files, etc.  Sometimes this did cause the issue, however, it happened 100% of the time when I was re-encoding a video file to that same folder (effectively creating another file that keeps changing in size until the re-encode completes). I'm more than happy to continue troubleshooting, and will be available again next week if need be.  Have a good weekend everyone!

**Comment by SubJunk** [comment]
Interesting, I can see in the changelog that we added support for `X_GetFeatureList` for Samsung TVs in 14.1.0 so I wonder if that is related. I'm away from my Windows machine but will make you a test build after the weekend, hope yours is good too!

**Comment by SubJunk** [comment]
@SurfaceS do you have any ideas about this?

**Comment by SurfaceS** [comment]
@SubJunk I was not able to reproduce this. I'll check a bit more when I have some time.

**Comment by SubJunk** [comment]
@KYFHO22 this is fixed now, would you like me to upload a build for you?

**Comment by KYFHO22** [comment]
I see there is a new build.  I will take a look today or tomorrow (was out
of town this past weekend)
