### ISSUE TITLE
Sony XBR-49X850B  Content could not be acquired

### ISSUE THREAD

**Issue by dberkham** [UniversalMediaServer/UniversalMediaServer#4884]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

Hi
Files are mp4 on a MacBook pro.  Using Safari.  I have a log zipped which is attached.  please help.  Does the number of files have anything to do with this problem?
[ums_dbg_2024-07-31-15-07.zip](https://github.com/user-attachments/files/16533225/ums_dbg_2024-07-31-15-07.zip)

* Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

Additionally, if the problem happened in the browser, it can be useful to know about any browser console errors, so please paste them into the issue too.

**Comment by dberkham** [comment]
Updated app to the latest.  No change.  Still won't acquire any files.

**Comment by SurfaceS** [comment]
Can you explain a bit more what is the bug ?

Is the web browser player give you the good content ?

**Comment by dberkham** [comment]
Attached is the log as requested for help in original post.  It simply reads the files but than states that it can't acquire files.  All files are mp4.

**Comment by dberkham** [comment]
Sony TV doesn't acquire the files.  
The file folders flash and then I get the message that the files can't be acquired.  web browser functions ok.  It's the TV that has the problem.  Been using Jellyfin instead (it works well) but I prefer to use UMS.

**Comment by SubJunk** [comment]
@dberkham I will upload the fixed version for you soon

**Comment by dberkham** [comment]
Thank you for your efforts.

**Comment by SubJunk** [comment]
@dberkham please let us know if this works https://www.universalmediaserver.com/uploads/UMS-issue-4884.dmg

**Comment by dberkham** [comment]
Thank you SubJunk!  Got it to go.  No problems so far.

**Comment by SubJunk** [comment]
@dberkham thanks for confirming!
