### ISSUE TITLE
Videos never marked as "Stopped playing"

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4887]
Recently, a lot of videos are never marked as "stopped playing". If I look at the last 5 videos I watched, only 2 have `StopPlaying Event` logs. I think the logged ones are the only ones that were transcoded too, not sure whether that is a coincidence.

**Comment by SubJunk** [comment]
I think in the code there is a 4 second buffer (`STOP_PLAYING_DELAY`) that is stopping it, maybe that is implemented wrong. Did that change recently @SurfaceS ?

**Comment by SurfaceS** [comment]
@SubJunk @Mik-S-UMS 
You should have this log trace line `"Stop playing {} on {} if no request under {} ms"` if `STOP_PLAYING_DELAY` is involved.
I think you do not have it.

You should also have this log info line `"Started playing {} ({}) on your {}"`

I found that when stream has premature end (like when the renderer stop the stream), Jetty async context is not completing the listeners, where stop playing is handled.

I'll try to fix that.
