### ISSUE TITLE
Trouble joining the support forum

### ISSUE THREAD

**Issue by Putzo** [UniversalMediaServer/UniversalMediaServer#4897]
This may not be the right place to put this, but at least I was able to join GitHub.  I have been trying for a while to sign up to the support forum on universalmediaserver.com.  I have created an account, but the system doesn't seem to want to send me the confirmation e-mail, though I have re-requested several times.  I have also e-mailed the admins using the form and have received no response to that.  Does anyone here know what I'm doing wrong?

Thanks!

**Comment by SubJunk** [comment]
@Putzo which email address provider are you using? Sometimes certain providers might have problems with certain domains. Maybe you can try using a different email address to see if that works. There are providers of temporary email addresses. A service I have used is the DuckDuckGo email service which also strips trackers before it forwards to your preferred address

**Comment by Putzo** [comment]
Hi SubJunk.  I'm using a GMail account. Never had any issues with it before.  I'll maybe try a different account. Do you have any contact with the mods over on that forum. Wondering if they even see my messages show up. Putzo
-------- Original message --------From: SubJunk ***@***.***> Date: 2024-08-14  2:44 a.m.  (GMT-07:00) To: UniversalMediaServer/UniversalMediaServer ***@***.***> Cc: Putzo ***@***.***>, Mention ***@***.***> Subject: Re: [UniversalMediaServer/UniversalMediaServer] Trouble joining the support forum (Issue #4897) 
@Putzo which email address provider are you using? Sometimes certain providers might have problems with certain domains. Maybe you can try using a different email address to see if that works. There are providers of temporary email addresses. A service I have used is the DuckDuckGo email service which also strips trackers before it forwards to your preferred address

**Comment by Mik-S-UMS** [comment]
I am the mod for the forum but I don't have any control with accounts, only banning spam.

There should not a problem with Gmail as the spam accounts are using this just fine.

Maybe there is a problem with the sign up page and the account is not created so no email is sent.
I do see quite often that new accounts are made but are never activated as their last active time is blank when looking at the member list.

Are you using any ad blockers or anything else that modifies webpages?

**Comment by Putzo** [comment]
Hi Mik,No, I don't use blockers of any kind, just a vanilla Chrome browser. I am running things through NordVPN, though.Whenever I go back to the forum to try again, when I put in my username and password, it tells me that "The specified username is currently inactive. If you have problems activating your account, please contact a board administrator."Putzo
-------- Original message --------From: Mik ***@***.***> Date: 2024-08-14  10:23 a.m.  (GMT-07:00) To: UniversalMediaServer/UniversalMediaServer ***@***.***> Cc: Putzo ***@***.***>, Mention ***@***.***> Subject: Re: [UniversalMediaServer/UniversalMediaServer] Trouble joining the support forum (Issue #4897) 
I am the mod for the forum but I don't have any control with accounts, only banning spam.
There should not a problem with Gmail as the spam accounts are using this just fine.
Maybe there is a problem with the sign up page and the account is not created so no email is sent.
I do see quite often that new accounts are made but are never activated as their last active time is blank when looking at the member list.
Are you using any ad blockers or anything else that modifies webpages?

**Comment by SubJunk** [comment]
With gmail you can do a trick where you have different accounts going to the same email, try signing up with e.g. `username+ums@gmail.com`, the `ums` part can be anything

**Comment by Putzo** [comment]
I'm going to try signing up with a new account using an e-mail address from
a non-Gmail provider to see if that makes a difference at all.

**Comment by Putzo** [comment]
Wow, okay, using a Hotmail account it the forum sent me the reg
confirmation e-mail immediately.  I wonder what the hold up was with my
Gmail.  Anyway, consider this matter closed.  I will submit my support
request over on the forum now.

Thanks for your assistance, folks!

Putzo
