### ISSUE TITLE
Automatic updates broken since 14.0.0-b1

### ISSUE THREAD

**Issue by DasSmeagle** [UniversalMediaServer/UniversalMediaServer#4899]
Sorry, I was not able to do any logs/traces. I have no "Tabs" in UMS!? I only know the Web Interface and cannot find any "Logs-Tab".

I Have Version 14.2.1. installed.

My Problem is, since my first install several versions ago I get this Prompt, there is a new version.

![grafik](https://github.com/user-attachments/assets/c5906dad-076d-45e9-8183-e731c4044f3c)

I can click "Cancel" and the window goes away and fine. But if I want to Update, I click "Download". The button is greyed out, it shows "Download in progress" and nothing more happens. Even after hours.

![grafik](https://github.com/user-attachments/assets/7b057041-0e85-4a10-9178-3f897d0559a6)

After a while I just kill everything and install the latest version manually. That works fine, but as soon as there is a new version, the same problem occurs. 

Anything I can do? I don't see what I could be doing wrong here... ;)

Thanks,
- Oliver

**Comment by Gehi14** [comment]
Same at my installation.
No ideas anywhere?
Thanks
Gerhard

**Comment by SubJunk** [comment]
Thanks for reporting it, I will look into it

**Comment by SubJunk** [comment]
I have confirmed this bug.
However when it happens, I am able to click the X on the upper right of the window to close the update popup, so you should not need to "kill everything". I am working on a fix now

**Comment by SubJunk** [comment]
The error in the logs is:

```
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] Exception in thread "pool-1-thread-1" java.lang.NullPointerException: Cannot invoke "net.pms.configuration.UmsConfiguration.getProfileDirectory()" because "net.pms.external.update.AutoUpdater.CONFIGURATION" is null
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at net.pms.external.update.AutoUpdater.downloadUpdate(AutoUpdater.java:213)
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at net.pms.external.update.AutoUpdater.doGetUpdateFromNetwork(AutoUpdater.java:142)
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at net.pms.external.update.AutoUpdater.lambda$getUpdateFromNetwork$1(AutoUpdater.java:113)
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO  2024-08-18 09:18:50.740 [pool-1-thread-1] 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
This is fixed now, the fix will be in the next release. Thank you @DasSmeagle and @Gehi14 for reporting it!

**Comment by DasSmeagle** [comment]
> I have confirmed this bug. However when it happens, I am able to click the X on the upper right of the window to close the update popup, so you should not need to "kill everything". I am working on a fix now

Thank you very much for quick fix!

The (X) was greyed out, so i I did not try to click it ;)

I now found the interface where a log is available. I never clicked "settings (old)" as it sounded like it is not used any more. But I now tried it and found, those "old" settings are a lot more useful an better designed than the "new" settings!? I find that a little strange.

- Oliver

**Comment by SubJunk** [comment]
The old settings are only available on the one machine that UMS is installed on, but the browser one can be used anywhere on the network which is something we had a lot of requests for
If you have any suggestions about how to improve the design please let us know
