### ISSUE TITLE
Default "MPEGPS-MPEG2-AC3" transcoding profile broken

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4901]
Got a user on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=16089&sid=77b179799909ba317bf223065ba231d1) where transcoding has not been working for them since v13.60 and gives the error return code of -22. 
I have managed to replicate this on my PS4.

There is no transcoding profile defined in the renderer's conf so it is using the default `MPEGPS-MPEG2-AC3`

It appears to be caused by the invalid argument `vob` in the output stream. I'm guessing this was once the correct argument but it may have changed in the newer version of FFmpeg.

`ffmpeg.exe -y -loglevel info -i "XXXX" -bufsize 7000k  -maxrate 44000k -g 5 -q:v 1 -qmin 2 -qmax 3 -ab 448k -c:a copy -c:v mpeg2video -f vob \\.\pipe\ffmpegvideo_103_1723683251229
`

`[ffmpeg.exe-2-2] [vob @ 00000226d32c8640] Unsupported audio codec. Must be one of mp1, mp2, mp3, 16-bit pcm_dvd, pcm_s16be, ac3 or dts.`

**Comment by SubJunk** [comment]
Ahh this makes sense, it is trying to copy the audio when the input is not supported. I'll fix this
