### ISSUE TITLE
Resume files not using correct ORG_PN

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#491]
@SharkHunter in DLNAResource.java:1918 we check if player != null, and it seems that resume files don't set "player" normally so it doesn't pass this check, and it needs to because it makes resume files not play on renderers that use TranscodeVideo=MPEGTS*, since we report to them incorrectly that the resume file is MPEGPS.
Can you please fix it? :)

**Comment by Sami32** [comment]
@SubJunk Wooaaah...i'm just surprise to discover how many open issues are related to "Resume", 50 !!!

One more issue related to "Resume": https://github.com/UniversalMediaServer/UniversalMediaServer/issues/481

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987

**Comment by atamariya** [comment]
@Sami32 Adding a tag to issues would be a good way of tracking similar issues.

**Comment by Sami32** [comment]
@atamariya Give time, please ;-)
I begin to review all issues and i'm far to finished it...but when i did a search i saw 20 open issues and 30 already closed conerning this subject.
I try to review from the oldest ones first, as i will get lost or forget some issues if i don't process by order. But by no mean it's the best way to go, only the one i chosen as a newbie ;-)

**Comment by SubJunk** [comment]
The fix for this went out with 7.1.0 https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1503/commits/e7699c35dd56d6fec2d05917bad0db6de2897ca5#diff-d47cdc0b5914bdba90e4805fd207c6e0R775
