### ISSUE TITLE
Unicode text uncorrectly showed

### ISSUE THREAD

**Issue by mashibana** [UniversalMediaServer/UniversalMediaServer#492]
Non-ASCII characters are fine in the logs tab and the web interface but are showed as "□" on most of the fields and in the shared folders tab.
Changing the language to an UTF-8 one (like japanese) seems to resolve the problem only partially.

I'm running UMS on Windows 7 64-bit.

**Comment by XakepSDK** [comment]
What language? Russian works fine.

**Comment by Sami32** [comment]
@mashibana Did the latest UMS version solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
@mashibana we presume this is now resolved so we're closing, but if not, can you please confirm which language and post full TRACE logs as per instructions above.
