### ISSUE TITLE
Marking media as fully played does not work UMS 14.3.0

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4938]
Hello,
Marking media as fully played no longer works on UMS 14.3.0, I also noticed that it does not detect when the episode is finished (UMS log screenshot)

Thank you

![Capture d’écran 2024-09-01 021028](https://github.com/user-attachments/assets/a7497960-5089-4b3a-b82f-68fe7aebd807)

[ums_dbg_2024-09-01-02-11.zip](https://github.com/user-attachments/files/16826562/ums_dbg_2024-09-01-02-11.zip)

**Comment by Mik-S-UMS** [comment]
I think this was one of the bugs that was fixed recently, #4887 I think, as I don't see any "stopped playing" messages.

**Comment by SubJunk** [comment]
Yeah this was fixed in 14.5.0, see the release changelog at https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/14.5.0
Thanks for reporting it
