### ISSUE TITLE
UMS becomes unstable over time since new media server engine

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4939]
For me, this has been happening since the default media server engine was changed from Netty.
It runs for a time, usually a few days, and then I will be watching a video and it will have long pauses that become more frequent, as UMS is not able to smoothly serve the video anymore.
At first I thought it was network related so it has taken me some time to figure out it is CPU, and it takes so long to reproduce.
I have logs from the last time it happened and can provide them if anyone looks into it, I would upload them and email a link

What I know so far:
1. UMS will not close when this happens. It is still semi-responsive, but it does not shutdown unless forced via Task Manager
2. The logs are huge, several gigabytes, and I wonder if this might be the cause of the problem. We also have reports of the recent huge logs on the forum
3. It is immediately fixed after a forced restart of UMS
4. It does not happen if I select the old default Netty engine

Probably one for @SurfaceS since you have been working on the engine refactoring

**Comment by SurfaceS** [comment]
@SubJunk I do not have a java profiler, but it may good to see what is going on when this happens.

I can have a look on logs and try finding what is the cause of this.

> It is immediately fixed after a forced restart of UMS

This is with "restart the server" button or shutdown completely and run ?

**Comment by SurfaceS** [comment]
@SubJunk 
I think that it is the logging Rolling File Appender that made this mistake.

**Comment by SurfaceS** [comment]
@SubJunk
Was a logging compressor things.

**Comment by SubJunk** [comment]
Great! I will run that now. Thank you
