### ISSUE TITLE
DLNA.ORG_xxx and other spotted probems with UPnP Inspector

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#494]
@skeptical  @SubJunk  @valib 
Hi guys. In UPnP Inspector I spotted that for Unknown Renderer no **DLNA.ORG_PN** is sent.
Ok, so I forced Unknown to Panasonic TV and now I spotted transcoded video has it but not streamed file.
Also that e.g. **Twonky** sends thumbnails as **"upnp:albumArtURI"** and also **"DIDL-Lite:res"** but UMS as **"upnp:albumArtURI"** only.

```
[UMS] Unknown Renderer:
[No Encoding]   http-get:*:video/x-matroska:DLNA.ORG_OP=01  (Misssing PN)
[FFmpeg]        http-get:*:MIMETYPE_AUTO:DLNA.ORG_OP=01     (I nowhere found if "MIMETYPE_AUTO" is acceptable Content-Type, PN is missing)
```

```
[UMS] Panasonic TV:
[No Encoding]   http-get:*:video/x-matroska:DLNA.ORG_OP=01                              (Missing PN)
[FFmpeg]        http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_HD_24_AC3_ISO;DLNA.ORG_OP=10   (Here PN is included)
```

```
[Twonky server]
http-get:*:video/x-matroska:DLNA.ORG_PN=MKV;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000
```
- Is it not better to send **"upnp:albumArtURI"** and also **"DIDL-Lite:res"** by UMS as Twonky does so it is not needed to define special **"ThumbnailAsResource = true"**?
- Is **"MIMETYPE_AUTO"** compliant Content-Type?
- Is benefical to add **"DLNA.ORG_FLAGS"** as some renderers can require it for **FF/RW** to be working correctly? Codetip: http://libdlna.sourcearchive.com/documentation/0.2.3/dlna_8h-source.html
- For streamed videos UMS doesn't send any **"DLNA.ORG_PN"**. Twonky sends e.g. **"DLNA.ORG_PN=MKV"** for streamed MKV file. Some renderers don't like if no **PN** is defined (**AccurateDLNAOrgPN** doesn't influence PN for streamed files)
- Forcing renderer option doesn't show all available renderers to choose from in GUI.
- For PS3 UMS doesn't send **PN** for any files (streamed or transcoded). Don't remember if it is "by design" :-)
- LG Smart TV is detected in UPnP Inspector twice. Once as **"MediaRenderer:1"**.The other one is **"Basic:1"** with **"webos-second-screen:1"**-->Type **"urn:schemas-upnp-org:device:Basic:1"**. UMS should ignore this webos/basic response to not confuse user and itself. 
  Check discussion here: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/485#issuecomment-75594059
- When **"DLNALocalizationRequired = True"**, it generates three **"DIDL-Lite:res"**, one with **_PAL** and **?two?** with **_NTSC DLNA.ORG_PN**. There should be only one **PAL** and one **NTSC** I suppose.
- I forced **Localhost interface** but UMS logged that it will use **physical network adapter** so all renderers in network were detected. When I forced IP **127.0.0.1**, log shown correctly forced localhost ip but it detected LG TV anyway. Other renderers were not shown so maybe it has connection to "remote play" support of TV? Anyway weird behavior possibly that nonlocal renderer wasn't ignored?
- Funny behavir for **"AccurateDLNAOrgPN = true"**. When not used, files are always shown as: **Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv [FFmpeg]**
- When it is enabled, first time file is snown as:
  - **Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv [FFmpeg]**
- But any other refresh renderer (UPnP Inspector in this case) shown them as:
  - **[FFmpeg] {Audio: AC3/Czech (CZE AC3 5.1)} {Sub: SubRip/Czech (CZE forced)}**

Quite messy behavior:-)

**Comment by skeptical** [comment]
@ExSport thanks, but a single patch is worth a 1000 bullets I always say :-).  Shooting back a little:
* [urn:schemas-upnp-org:device:Basic:1](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/UPNPControl.java#L45) is for older Sony Bluray, though you're right, it does misfire a lot. We should maybe filter only for Sony Bluray.
* your mystery ipads in #485 are actually [twonky](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/renderers/Apple-iDevice.conf#L82), though you probably know this already.

**Comment by ExSport** [comment]
I agree basic:1 should be limited to Sony Bluray only.
#485 report was't about only what is iPhone icon but that once it is
unknown and once it is IPhone:-) In reality it is Qnap Nas with Twonky
Server inside so not renderer but server as UPnP Inspector shown me.
But as you exactly said in you first sentence, there is no comment needed:-)
Wanted to mention somewhere what I spotted so it will not be lost. Some of
them maybe hides bigger problems which can lead to unpredicted behavior,
ignored packets, changing filenames in time, unplayable files,...:-)

**Comment by skeptical** [comment]
@ExSport yeah, I didn't mean to imply #485 is solved, only the misrecognition part.  Will chase down the known/unknown phantoms soon, or one of these days anyway :).

**Comment by ExSport** [comment]
@skeptical Maybe "Basic:1" should not be ignored completely as it includes some useful info as proper model name.
![lg_inspector](https://cloud.githubusercontent.com/assets/1260408/6430292/dd50616c-c003-11e4-9f43-1e301621af42.PNG)

**Comment by SubJunk** [comment]
@ExSport you've raised some good points here and I think we can work to improve this stuff

**Comment by SubJunk** [comment]
@ExSport I'm trying to set up UPnP Inspector but it doesn't see UMS, how do I set it up? I'm being very slack by not just Googling this ;)

**Comment by ExSport** [comment]
@SubJunk 
No rocket science. Start UPnP Inspector v0.2.2 on same PC as UMS. Wait for a while or sometimes click on "Rediscover Devices" to see UMS server. After that right click on it and selecting "browse mediaserver". That's all.

**Comment by SubJunk** [comment]
@ExSport oh, it doesn't work for me

**Comment by ExSport** [comment]
Weird. Works for me on two different PC...

**Comment by ExSport** [comment]
@SubJunk Now I spotted sometimes "Inspector sends M-Search on wrong adapter"
Go to "View-->Show global log" if it listen on right adapter/IP. If not, disable adapter or stop service (like VPN in my case). Unfortunately sometimes still Inspector listen on wrong IP like LOCALHOST. Restarting Inspector few/many times and voila Inspector started to listen on right adapter again. Behavior is quite weird but it worked to fix it this way for me.

**Comment by SubJunk** [comment]
Oh yeah it's only looking on my wireless adapter but my devices are all on wired. Cool I'll try disabling that adapter while using the program

**Comment by Sami32** [comment]
Concerning DLNA.ORG_PN issue, see this PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987

**Comment by polygirl** [comment]
Split out into individual stories so closing this main reference one.
