### ISSUE TITLE
UMS locked certain files and now can not parse them. 

### ISSUE THREAD

**Issue by ctreulieb** [UniversalMediaServer/UniversalMediaServer#495]
I have a very strange bug.

I was watching Parks and Rec on my PS3 when it suddenly stopped working. When I went to watch on my laptop all the files had a locked icon and were set to share with no one. I've since revered that, or so I thought, and since then I can watch anything except parks and rec and it will work fine. As soon as I attempt to view parks and rec files on my PS3 I will be unable to browse to anything else. If titles have been cached and I attempt to watch something that shows up in that list my PS3 will freeze at a black screen and require a restart.

I can't see anything wrong with the parks and rec files, and I was initially able to stream them from my PC to my PS3. Now I can not. 

Here's my logs
https://drive.google.com/file/d/0B9jwNTtyOZNnbG9ubFJLYTVXbVk/view?usp=sharing

**Comment by Sami32** [comment]
@ctreulieb Did the latest UMS version solved this issue ?
(with a clean install and only one instance of UMS enabled in the purpose to narrow this issue)

If not, please, could you post the text log from MediaInfo standalone on the problematic files ?

EDIT: Your database was locked or corrupted for these specific files.
> Request: HTTP/1.1 : POST : upnp/contERROR 00:00:11.747 [New I/O worker #3] null
> org.h2.jdbc.JdbcSQLException: Database may be already in use: "C:/ProgramData/UMS/database/medias.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-185]
...
> INFO  00:00:11.747 [New I/O worker #3] The file F:\Videos\TV\Parks and Rec\Season.05\Parks.And.Recreation.S05E02.DVDRip.X264-DEMAND.mkv could not be parsed. It will be hidden
> ...
> TRACE 00:03:17.151 [New I/O worker #1] Parsing results for file "Parks.And.Recreation.S05E01.DVDRip.X264-DEMAND.mkv": container: null, bitrate: 0, size: 0, video codec: null, duration: null, width: 0, height: 0, frame rate: null, muxing mode: null, mime type: null, matrix coefficients: null, attached fonts: false
> DEBUG 00:03:17.151 [New I/O worker #1] Could not parse the bitrate from: F:\Videos\TV\Parks and Rec\Season.05\Parks.And.Recreation.S05E01.DVDRip.X264-DEMAND.mkv
> INFO  00:03:17.151 [New I/O worker #1] The file F:\Videos\TV\Parks and Rec\Season.05\Parks.And.Recreation.S05E01.DVDRip.X264-DEMAND.mkv could not be parsed. It will be hidden

**Comment by SubJunk** [comment]
Closing this as there was no response from @ctreulieb 
Thanks for responding to it @Sami32
