### ISSUE TITLE
Filenames/Titles replaced by encoder details on v5+ when Sony Bravia is the client

### ISSUE THREAD

**Issue by MattDetroit** [UniversalMediaServer/UniversalMediaServer#499]
Similar to bug #490, but rather than replacing the filename/title with the title from the meta data, the filename/title is being replaced with the encoder details. For instance:
"[FFmpeg] {Audio: AAC/Japanese ()} {Sub: SSA/English ()} | MPEG"

Appears to occur when Sony Bravia is the renderer (is not occuring with IOS or Android).

An example log file is posted under this thread (by Raident):
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2963&start=20#p15266

**Comment by ExSport** [comment]
Check "AccurateDLNAOrgPN" part mentioned here https://github.com/UniversalMediaServer/UniversalMediaServer/issues/494 if your renderer has it enabled.

**Comment by netx123** [comment]
This issue does not apply to all Sony Bravia renderers, I have the KDL47W805A, which correctly displays filenames/titles as expected.

**Comment by ExSport** [comment]
As I mentioned in my earlier post, check your renderer.conf file. Not all Samsung TV include this parameter or set it to true to see if problem arise.

**Comment by sprooose** [comment]
I am seeing this on a Sony Bravia 46EX520...
I haven't seen this issue since I  enabled: 

prettify_filenames = true

**Comment by ExSport** [comment]
You are mixing here another behavior. What you mentioned prettify names from e.g. Spiderman.dvd.hd.dts.ac3.mkv to Spiderman.mkv and not that file is shown as "[FFmpeg] {Audio: AAC/Japanese ()} {Sub: SSA/English ()}". If yes, than it is bug but I suppose your problem is different.

**Comment by sprooose** [comment]
Yes I know. I enabled prettify filenames to workaround the issue.. (as you can't determine which files are which when the issue presents itself)
The issue exists when: prettify_filenames = false;

**Comment by SubJunk** [comment]
Does this build fix it? http://www.spirton.com/uploads/UMS/UMS-e8ca950.exe
