### ISSUE TITLE
14.5.1 will not scan files when the number for alphabetical organizing is set below 10000

### ISSUE THREAD

**Issue by radioresearch** [UniversalMediaServer/UniversalMediaServer#4992]
Thank you very much for the update!  I am sorry to report that my issue as discussed in Issue #4937 continues.  While the program recognizes the d, e, f, g drives, it does not see any files.  If I change the minimum number of files required for alphabetical grouping back to the default of 10000, it then sees all the files, however, I do not have that many files (movies) on a drive, so I get no alphabetical grouping.

Trace logs attached.
-- radioresearch
[ums_dbg_2024-09-23-05-56.zip](https://github.com/user-attachments/files/17095730/ums_dbg_2024-09-23-05-56.zip)

**Comment by SurfaceS** [comment]
already handled in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4937

**Comment by radioresearch** [comment]
But the issue from #4937 remains, at least with my installation. If you have a look at the trace logs I submitted you will see what I mean.  Cheers!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SurfaceS** [comment]
issue #4937 is still open, so we are aware of that.

Today, I added a commit that should solve this issue.
