### ISSUE TITLE
Current problems with new versions under ubuntu 24.04.1

### ISSUE THREAD

**Issue by SomeUSer69** [UniversalMediaServer/UniversalMediaServer#5001]
Hello,
I'm sorry but i can't follow the way you want and give a .log as the problem is old. I specify that I use the free version.
I used to watch films on my TV through UMS and I sometimes interrupted the watch. I could then watch the film again from the point I interrupted. Since version 13 I think, when I interrupt the watching of a film, I must watch it from the beginning each time. There's no more memory of the interruption point.
And from older version, I could watch some films (i don't know the Codec). I interrupted the watch. Then I was told that a new version was available. I downloaded it and then the film interrupted was no more readable from UMS. It was in version 11 or 12, I don't remember. I've tried the last 14.5 and always the same problems. So, i'm still using the 12.0.1 version.

**Comment by SubJunk** [comment]
@SomeUSer69 thanks for reporting these problems. I know it can take time, but we do need to know specific versions if you want us to fix them. You can download older versions to figure out when the problem appeared. I am happy to help by providing download links and instructions for the older ones if you are willing, please let me know

**Comment by SomeUSer69** [comment]
Hello,
I thank you for your suggestion but I won't test any old versions in order to find when the bugs appeared, especially for the codecs that did function on a version and then didn't function on a new one as it's not possible to find again the videos concerned. According to the version, I had to delete all configuration files as it seems the database structure changed according the version. it is an additional difficulty to do tests. 
I’m surprised you didn’t notice that resuming a video at some point didn’t work. Maybe is it specific to Ubuntu?
Best regards

    Le mardi 1 octobre 2024 à 02:09:49 UTC+2, SubJunk ***@***.***> a écrit :  
 
 


@SomeUSer69 thanks for reporting these problems. I know it can take time, but we do need to know specific versions if you want us to fix them. You can download older versions to figure out when the problem appeared. I am happy to help by providing download links and instructions for the older ones if you are willing, please let me know
