### ISSUE TITLE
UMS crashes on Java error

### ISSUE THREAD

**Issue by KRLVE3** [UniversalMediaServer/UniversalMediaServer#501]
having a problem with java crashing after several minutes or even hours
I think it's strictly a Java error but was wondering if anyone can help.
Already submitted the error info to Java site.

thanks

**Comment by Sami32** [comment]
@KRLVE3 Did a clean Java uninstall and install of the latest Java and UMS version solved your issue ?

If not, please, post your lod following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
@KRLVE3 it's been a while since you reported this. We suspect this has likely been resolved now with later versions of UMS.  If not, feel free to reopen with TRACE logs as suggested above.
