### ISSUE TITLE
FF, RW, and jump to time problem

### ISSUE THREAD

**Issue by JSLavigne** [UniversalMediaServer/UniversalMediaServer#502]
Hi,  
I tried versions 3.x.x (I don't really remember), 4.4.0 and 5.0.0 and so far on all three versions the only renderer on which I can "jump to time" is "Infuse" on iPhone 5. (and it's detected as unknown renderer) 
On VLC 2.2.0 I can see my files but I can't play it. 
On Windows Media Player it detect the server as a playlist but it's empty. 
On my Samsung BD-H5100 I had to create my own renderer .conf file for it to have sound since 5.0.0 ( on 4.4.0 it used netgear netTV as renderer but on 5.0.0 it was unknown) now it works way faster than with unknown renderer and even faster than with the previous version but still no jump to time.
On the web ui on http://"server-ip":9001  with flash player I can jump to time but not with HTML.

Is there any way that I could Fast forward, Rewind and/or jump to time on my Blu-ray Player Samsung BD-H5100? 

I will upload both the debug.log file and my homemade samsung bd-h5100 .conf file.
But I use UMS on a headless server with no desktop GUI so I can't use the instruction to retrieve logs files. If you need anything else let me know and I will provide any files you need (just tell me where to look please) 
Any help would be much appreciated, Thank you

**Comment by JSLavigne** [comment]
Here is the link to the attachments : http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15389#p15389

**Comment by Sami32** [comment]
@JSLavigne Did the latest UMS version solved this issue ?
**Do not use your own renderer file while trying the latest UMS version**.

If not, please, provide your _UMS.conf_ file as well that can be found in your profile's folder.

EDIT:
> DEBUG 15:02:51.369 [ffmpeg-1-2] Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
> DEBUG 15:02:51.369 [ffmpeg-1-2] Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

**Comment by polygirl** [comment]
@JSLavigne it's been a while since you reported this so we presume it's no longer an issue.  Feel free to reopen with the files as requested if needed.
