### ISSUE TITLE
Set HTML title to reflect the page you're on

### ISSUE THREAD

**Issue by SpitFire-666** [UniversalMediaServer/UniversalMediaServer#5039]
No matter where you navigate, the HTML title stays as "Universal Media Server". It would be awesome if it could update depending on what area you navigate to, eg "Universal Media Server - TV Shows"

![image](https://github.com/user-attachments/assets/26c62dfc-237f-4e1f-8af1-a55633b2bf8d)

It would also speed up navigation and make browser history more meaningful:

![image](https://github.com/user-attachments/assets/d1748fa5-f663-48a9-a876-e7d1e08b4f40)

**Comment by SubJunk** [comment]
Good idea

**Comment by Shripad-Joshi** [comment]
Hello @SpitFire-666 , I would like to work on this issue.

**Comment by AnshikaSingh33** [comment]
Hello @SpitFire-666 ,I would like to work on this issue kindly assign it to me

**Comment by SubJunk** [comment]
Anyone can work on it, just submit a PR
