### ISSUE TITLE
Problems with Samsung Smart TV

### ISSUE THREAD

**Issue by prepu** [UniversalMediaServer/UniversalMediaServer#505]
I had UMS 3.3 before and everything worked great with my Samsung Smart TV. Since I have updated to UMS 5.0.1 I have problems sometimes. It is very strange because it is not always.

What it happens is that if I have my TV switch off and then I turn it on, I press the "source" button and I don't see the UMS source. I have to go to my computer and press the "reset server" button. Then it works. With the former version (3.3) was always working.

I haved download the UMS 4.4 version and it works good so now I have to use this version.

Thanks.

**Comment by Norm64** [comment]
I have some similar issues as well scene installing the version 5.0 it can't read anymore my .mp4 extension only. See part of the Debug log below. I'll continue to use UMS 4.4 that work great at the moment until you tell me that a fix is apply.

Thank you

INFO  20:16:21.044 [StartPlaying Event] Started playing Under.the.Dome.S02E12.HDTV.x264-LOL.mp4 on your Samsung AllShare C/D
DEBUG 20:16:21.044 [StartPlaying Event] The full filename of which is: E:\Share\Under.the.Dome.S02E12.HDTV.x264-LOL.mp4 and the address of the renderer is: 192.168.2.12
INFO  20:16:24.164 [StartPlaying Event] Started playing The.Vampire.Diaries.S06E17.HDTV.x264-LOL.mp4 on your Samsung AllShare C/D
DEBUG 20:16:24.164 [StartPlaying Event] The full filename of which is: E:\Share\The.Vampire.Diaries.S06E17.HDTV.x264-LOL.mp4 and the address of the renderer is: 192.168.2.12
INFO  20:16:25.132 [StopPlaying Event] Stopped playing Under.the.Dome.S02E12.HDTV.x264-LOL.mp4 on your Samsung AllShare C/D
DEBUG 20:16:25.132 [StopPlaying Event] The full filename of which is: E:\Share\Under.the.Dome.S02E12.HDTV.x264-LOL.mp4 and the address of the renderer is: 192.168.2.12
INFO  20:16:27.253 [StartPlaying Event] Started playing White.House.Down.2013.FRENCH.BDRip.XviD-HMiDiMADRiDi.avi on your Samsung AllShare C/D
DEBUG 20:16:27.269 [StartPlaying Event] The full filename of which is: E:\Share\White.House.Down.2013.FRENCH.BDRip.XviD-HMiDiMADRiDi.avi and the address of the renderer is: 192.168.2.12
DEBUG 20:16:27.300 [New I/O worker #9] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 20:16:27.300 [New I/O worker #9] Premature end, stopping...
DEBUG 20:16:28.751 [New I/O worker #7] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 20:16:28.751 [New I/O worker #7] Premature end, stopping...
DEBUG 20:16:28.782 [New I/O worker #8] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 20:16:28.782 [New I/O worker #8] Premature end, stopping...
DEBUG 20:16:28.813 [New I/O worker #9] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 20:16:28.813 [New I/O worker #9] Premature end, stopping...
DEBUG 20:16:55.864 [New I/O worker #6] Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
DEBUG 20:16:55.864 [New I/O worker #6] Premature end, stopping...
DEBUG 20:16:56.597 [New I/O worker #7] HTTP User-Agent: DLNADOC/1.50 SEC_HHP_[HT]D6500/1.0
DEBUG 20:16:56.597 [New I/O worker #7] Invalid action in SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#X_GetFeatureList"

**Comment by Sami32** [comment]
@prepu Did the latest UMS version solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by polygirl** [comment]
@prepu it's been some time since you reported this, so we presume this is no longer an issue for you with the later versions of UMS.  Feel free to reopen with the TRACE logs as requested above if needed.
