### ISSUE TITLE
Audio MIME types stated in the renderer config file are no longer used

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#509]
It seems that with the 5.1.0 release, the media renderer MIME types for the audio formats stated in the renderer config file are no longer used.

This results on the renderer-side for faulty recognizing of the media.
Most or maybe all non mp3 files are now incorrect stated as: audio/mpeg:DLNA.ORG_PN=MP3

This issue does not occur with video media, where the renderer prefered mime type is used.

Debug log posted on forum:
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15599#p15599

**Comment by ler0y** [comment]
For comparison i also posted a debug log with version 5.0.1 on the forum.
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15599#p15599
This previous version doesn't have this issue.

The same bug is also with image files.
bmp, gif and png are all sent to the renderer with the image/jpeg MIME-type instead of the MIME-types given to the renderer profile Supported lines.

Related post on forum:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3192

**Comment by SubJunk** [comment]
@ler0y thanks for the testing! It's fixed in 69e04b6
