### ISSUE TITLE
unable to turn off universal media server metadata

### ISSUE THREAD

**Issue by ryncor21** [UniversalMediaServer/UniversalMediaServer#5094]
If I uncheck "Use info from our API" the program is unable to play any media in the website gui. If I uncheck use "external network" it will still search for metadata and add it to the server. The only way i could stop it from using metadata from the API was actually blocking the URL https://api.universalmediaserver.com/

The code in the file APIUtils.java has a method called shouldLookupAndAddMetadata() . This method may have a case where it always returns true. Not sure if this is the problem. UMSConfiguration.java has a method called getExternalNetwork(); This method can return a default value of true. Perhaps getBoolean() in the configuration reader should throw an exception rather than return a default value of true to getExternalNetwork();

I mean if i had a bad config file I would rather the server crash when i try to start it and show me some exception that wasnt caught or whatever.

**Comment by SurfaceS** [comment]
> If I uncheck use "external network" it will still search for metadata and add it to the server. 

Do you save the settings (the blue save button) ??
Because it is not possible that it still search for metadata and add it to the server.
```
		if (!CONFIGURATION.getExternalNetwork()) {
			LOGGER.trace("Not doing background API lookup because external network is disabled");
			return false;
		}
```
And all call are guarded by the same check before accessing external servers.

> UMSConfiguration.java has a method called getExternalNetwork(); This method can return a default value of true.

This is the way it should be.

> if i had a bad config file

For what reason ? You break the config file by hand ?
