### ISSUE TITLE
default location for media server is the users home folder

### ISSUE THREAD

**Issue by ryncor21** [UniversalMediaServer/UniversalMediaServer#5095]
So not really a functionality issue I guess but from a security standpoint I don't think the server should default to the users home folder without explicitly creating a new user just for the media server program to run on. I mean you download the software and run it on your linux computer and it just scanned everything in your home folder and sent the metadata to the api.universalmediaserver.com website. I mean they said this is a media server that doesn't spy on you. It sure seems like it does.

**Comment by SurfaceS** [comment]
@ryncor21 

> I don't think the server should default to the users home folder

User have a `Wizard to ask users to make the UMS initial setting` on first startup.
- Should UMS scan shared folders when the program starts?
- Finally, choose a folder to share. You can choose more later on the Navigation/Share Settings tab.
If you don't choose a folder, we'll choose a default based on your operating system.

What is wrong with that ?
It default to the user home folder if the user don't choose any folder.
And the user can add/remove what he want on settings, nothing is hidden... so... ?

> Sent the metadata to the api.universalmediaserver.com website.
> I mean they said this is a media server that doesn't spy on you. It sure seems like it does.

- The source code of the API server is visible here : https://github.com/UniversalMediaServer/api
The source code of what is sent from UMS to the API is here : https://github.com/UniversalMediaServer/UniversalMediaServer/blob/main/src/main/java/net/pms/external/umsapi/APIUtils.java
Can you review code and tell us where it does something not anonymously or sent sensitive data ?

- If you are afraid of using it, you don't have to use it, you can deactivate it (`Use info from our API`).

- Also, you can provide your own TMDB API key and check `Use info from TMDB`, then it will completely bypass the UMS API server, allowing us to save server resources/bandwidth.

**Comment by Mik-S-UMS** [comment]
I think on Linux it does have the home folder shared as default from some logs I have seen as people have mentioned they did not add it themselves, even if they use the wizard to chose shared folders themselves.

As this includes things like user program configurations, including for UMS, it causes problems whenever there is any change and that folder is re-scanned and I have seen UMS trying to scan its own database many times and failing in some logs.

It is like sharing `C:\Users\[user]\` in windows which would include the AppData folder along with that users documents and non media content. This will also mean those files are checked against the API which would give the impression of it spying.

I don't exactly know where videos are usually stored on Linux but I think it is something like `home/Videos` or `home/Media` and these should be used instead for default locations.

**Comment by SurfaceS** [comment]
@Mik-S-UMS 
> It is like sharing C:\Users\[user]\ in windows which would include the AppData folder along with that users documents and non media content. This will also mean those files are checked against the API which would give the impression of it spying.

UMS is not parsing files if it is not a media file.
```
		if (!SystemFilesHelper.isPotentialMediaFile(file.getAbsolutePath())) {
			LOGGER.trace("Not parsing file that can't be media");
			return false;
		}
```

So users documents and non media content are not analyzed, even less checked against the API.

**Comment by SurfaceS** [comment]
Just to clarify :

UMS is designed to allow basic users (most users) to install and run without a lot of manual settings after install.

Like other app, it need to store conf, db, etc.
According to [linux XDG Base Directory spec](https://wiki.archlinux.org/title/XDG_Base_Directory) : 
UMS use the environment variable `$XDG_CONFIG_HOME` to store its config files.
If not founded, it default to the environment variable `user.home` `/.config` as requested.


```
    XDG_CONFIG_HOME
        Where user-specific configurations should be written (analogous to /etc).
        Should default to $HOME/.config.
```


But it also include a lot of customization for advanced users.
And those ones know what they do, or they should not touch anything.
If they prefer to create a separate user for UMS and run under it, they know how to do it.

An option can be the wizard to ask for `all users or current user only` thing.

**Comment by ryncor21** [comment]
Thanks for so much feedback about this issue. I just remember seeing information about qbittorrent-nox and how people recommend running the program/webui under its own user and group on a linux machine for security. I think its a good idea to do this for UMS also
