### ISSUE TITLE
Select renderers option broken

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#510]
The GUI setting for "Select Renderers" no longer saves - it seems that the setting itself saves but the GUI doesn't update after the popup is closed

**Comment by SubJunk** [comment]
@valib might be related to the automatic saving feature

**Comment by valib** [comment]
@SubJunk I have retested it and it works for me. What it means the GUI doesn't update? For me the GUI shows exactly the same state before the popup is closed or previous one if the cancel button is hit.

**Comment by SubJunk** [comment]
@valib after more testing it seems to work for most things but if I do these steps it will forget:

1) Open "Select renderers"
2) Untick "select/deselect all renderers"
3) Enable one renderer
4) Click OK
5) Open "Select renderers"

Now they are all selected again

**Comment by valib** [comment]
@SubJunk I see. I used at least two renderers so I didn't realised this bug :-) I will try to fix it.

**Comment by valib** [comment]
@SubJunk done. Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/49156a9b12c0f580b9255d4683e1663856ebeb63

**Comment by SubJunk** [comment]
@valib great job
