### ISSUE TITLE
Issue with LG TV playback of videos using UMS

### ISSUE THREAD

**Issue by NDPerels** [UniversalMediaServer/UniversalMediaServer#5132]
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
[_ums_dbg_2024-11-28-09-49.zip](https://github.com/user-attachments/files/17946211/_ums_dbg_2024-11-28-09-49.zip)

  * Attach the zip file to the GitHub issue.

Additionally, if the problem happened in the browser, it can be useful to know about any browser console errors, so please paste them into the issue too.

**Comment by SubJunk** [comment]
@NDPerels thanks for the logs, I will upload a build for you to test soon

**Comment by SubJunk** [comment]
The TV is 32LQ63006LA which I think is a FHD LED from 2022. We don't have a profile for that type of TV yet so I'm making one

**Comment by NDPerels** [comment]
Thanks guys. Appreciate this.

**Comment by SubJunk** [comment]
@NDPerels please try https://www.patreon.com/posts/116974517

**Comment by NDPerels** [comment]
This seems to have solved most problems, although still having difficulties
with playback of some videos - this may be due to video quality, although
Windows Media Player still somehow manages! Will get back to you if problem
persists, but many thanks for this update.

Regards
Nigel Perels

**Comment by SubJunk** [comment]
Great, thank you. I will close this issue and release the code change in the next release, feel free to open a new issue for any more problems
