### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#514]
In 5.1.1 we're getting logs with this message occurring during playback:

```Connection error: java.io.IOException: An existing connection was forcibly closed by the remote host
Connection error: java.io.IOException: An established connection was aborted by the software in your host machine```

http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3243

**Comment by Sami32** [comment]
@SubJunk Can this issue be closed ? because the 5.1.1.1 version or a clean install solved it.
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3243&start=10

Feel free to reopen it if necessary.
