### ISSUE TITLE
macOS Intel version 14.7 gives Unnotarized Developer ID.

### ISSUE THREAD

**Issue by sordoneF** [UniversalMediaServer/UniversalMediaServer#5150]
The App can not be started due to Gatekeeper settings.

spctl -a -vvv -t install Universal\ Media\ Server.app/
Universal Media Server.app/: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Klaus Townsend (9V2H7S647T)

Downloaded file is UMS-14.7.0.dmg.

**Comment by SubJunk** [comment]
@sordoneF thanks for reporting this. Is this the first version with the problem? Does 14.6.0 work?

**Comment by sordoneF** [comment]
Previous versions had no problem when installing and running.

**Comment by sordoneF** [comment]
Version 14.6.0 has this output:

spctl -a -vvv -t install Universal\ Media\ Server.app/
Universal Media Server.app/: accepted
source=Notarized Developer ID
origin=Developer ID Application: Klaus Townsend (9V2H7S647T)

Your Apple developer ID (profile) needs an update or check.

**Comment by SubJunk** [comment]
@sordoneF thanks for reporting it, I might have forgotten a step during the release process. I will check it next time

**Comment by sordoneF** [comment]
Problem is solved with build Version 14.8.0. Thanks you. Ticket can be closed.

**Comment by SubJunk** [comment]
Thanks for confirming!
