### ISSUE TITLE
Major release question

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#5156]
@UniversalMediaServer/developers I am interested in opinions. In https://github.com/UniversalMediaServer/UniversalMediaServer/pull/5135 I have fixed some very wrong parsing values that have been making parsed values incorrect, and those values are stored in the database. That means those videos will be transcoded when they shouldn't be, which is especially bad because some renderers do not support transcoding, or their support is inferior (like you can't seek in the videos)
We have some options on how to proceed:

1) Just merge it as it is, which means existing videos will be wrong, but newly added ones will be correct.
2) Release a new minor version (like 14.9.0) that forces a re-parse of all video files. I don't think we can write a migration script that only does some videos, because there are too many wrong values.
3) Release a new major version (like 15.0.0) that forces a re-parse of all video files. It's the same as option 2, but maybe the version indicates to the user that they can expect something like this. We usually base our major versions on features, not breaking changes, but maybe this makes sense.
4) Another option you thought of?

Opinions?

**Comment by ik666** [comment]
I wonder, what is the exact implication of a re-parse of all videos, as long as they are "lazy" updated?

**Comment by SurfaceS** [comment]
UMS that use parsed values from MediaInfo are right no ?

**Comment by SubJunk** [comment]
I didn't notice we had a PARSER column. That's very convenient. Thanks for the input both of you!

**Comment by SubJunk** [comment]
This is done
