### ISSUE TITLE
Videos that work with UMS 5.1.0 will not play with UMS 5.1.1

### ISSUE THREAD

**Issue by TWCunningham** [UniversalMediaServer/UniversalMediaServer#516]
I recently updated to 5.1.1 and as I was trying to play a movie through LocalCast on my Android phone to ChromeCast on my TV, the Chromecast complained that the movie was not in a supported format.  I then tried playing the same movie through the media player on the TV (it's a Sony Internet TV) and the media player claimed the file was corrupted or unsupported.  When I switched back to 5.1.0 all was well.  I'm running UMS on a Windows 8 machine under Java 8.

**Comment by SubJunk** [comment]
@TWCunningham hopefully this is fixed in 5.1.1.1. If not, we can reopen this and will need logs to see what has gone wrong

**Comment by TWCunningham** [comment]
Seems to have fixed it for me, thanks.

**Comment by SubJunk** [comment]
@TWCunningham thanks for confirming :)
