### ISSUE TITLE
Samsung external subtitles not working

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#5168]
I have been trying to figure out why external subtitles are not working for someone on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=16306) when the video is streamed. 
They have a 2021 TV (UN65AU8000BXZA) and are unable to select them even though UMS is offering them.

Testing on my old series F Samsung it is working correctly and the only thing I can do to break it is to comment out the `SubtitleHttpHeader = CaptionInfo.sec` option in the conf. 
In the Samsung-TV-2021-0.conf this is already set along with `UseClosedCaption = true`

Could Samsung be using a different header now? Or maybe they need something else set to work?

Anyone with a similar model TV can you confirm external subtitles are not working?

**Comment by SubJunk** [comment]
I don't have a Samsung TV, I think @SurfaceS might?

**Comment by Vikip68** [comment]
I have Samsung oled 65s90c (2023).
External subtitles are not working on TV with UMS 14.7.0 but working fine with UMS 14.6.0 .

**Comment by SurfaceS** [comment]
I'll have a look when I can take time / test for it.
Before new year, for sure.

**Comment by timiman** [comment]
The same issue with a Samsung QN90B (2022) and 14.7.0+.
By using version 14.6.0 external subtitles are working just fine.

**Comment by SurfaceS** [comment]
broken since #4918
