### ISSUE TITLE
Java 8 causing connection issues

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#518]
It seems that maybe some of the connection issues we're seeing are being caused by Java 8. We have some users reporting that uninstalling Java 8 and installing Java 7 fixed their connection issues.
Any ideas @UniversalMediaServer/developers ?

http://www.universalmediaserver.com/forum/viewtopic.php?p=15644

**Comment by skeptical** [comment]
Maybe some, but we have java 7 visibility reports too. I think it must have several aspects.

**Comment by SubJunk** [comment]
This appears to have been resolved, either by us or Oracle
