### ISSUE TITLE
Passthrough of AAC Audio by PS3 encoded by Dolby Pro Logic 2 (5.1 DTS->2.0 AAC) does not work past v3.2 of UMS

### ISSUE THREAD

**Issue by Walbuls** [UniversalMediaServer/UniversalMediaServer#520]
On my PS3 I am able to pass my 5.1 audio, encoded by Dolby Pro Logic 2 from DTS 5.1 channels to AAC 2.0, to my receiver just fine with my old 3.2 version of UMS and the transcode option of FFmpeg, but any new version i try past this no longer works with any transcode. It will only ever play 2.0 audio. I have changed all the audio settings i can find on the newer versions, nothing works. Please fix this so i can upgrade my version or allow the passthrough of DPL encoded audio in general with any transcode method.

My audio settings in v3.2:
![dpl](https://cloud.githubusercontent.com/assets/11848187/7039797/3e597b4c-dd8c-11e4-8a6f-860d04025598.png)

**Comment by SubJunk** [comment]
@Walbuls please follow the instructions at http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556 to give us the logs we need. Make sure to include logs from UMS 3.2 and from 5.1.1.1

**Comment by Walbuls** [comment]
Here are the 2 log zips. Both with same file and settings. v3.2 i get full 5.1 Dolby Digital audio sent to the receiver via the PS3. v5.1.1 i only get 2.0 audio with any of the transcodes. Not sure if it matters at all but when selecting a transcode type for the file in the PS3 on v5.1.1, next to the transcode type it has Audio: AAC (), where as in v3.2 is it just Audio: AAC, without the brackets.

http://www.filedropper.com/umsdbgv32
http://www.filedropper.com/umsdbgv511

**Comment by Walbuls** [comment]
Any update on this issue?

**Comment by valib** [comment]
Try to set FFmpeg as the default engine (move it on the top of the list). I don't know for now why in version 3.2 the UMS chooses FFmpeg to play the test video when is set on the third place. In version 5 UMS correctly takes the Mencoder which is on the first place but there is set `-channels 2` which makes the bug. I will take a look on it.

**Comment by Walbuls** [comment]
I specifically chose FFmpeg from the transcode folder as it was the only one to pass the 5.1 audio instead of 2.0. Does that channels 2 bug effect all renderers? None of them would pass the 5.1 in the newer versions of UMS.

I also have 2 separate install locations with 2 separate config files for my versions. Although not sure if this would still cause the issue you mentioned.

**Comment by Walbuls** [comment]
Don't suppose the new version fixed this?

**Comment by Walbuls** [comment]
Hi UMS team. Any update on this issue?

**Comment by Walbuls** [comment]
Hi UMS team. Any update on this issue?

**Comment by SubJunk** [comment]
@Walbuls the links expired, feel free to upload the logs to our forum so they won't expire :)

**Comment by Sami32** [comment]
@Walbuls Did the latest UMS version, on a clean install, solved this issue ?

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by Walbuls** [comment]
It works now for tsMuxer but doesn't work for any others. It used to only work for FFmpeg on version 3.2. I have included trace logs for both versions at the link below and attached them here. Hope yall can track this down. Being able to play DPL2 audio (Which i use for all my encodes) encoded media and have it actually playback at 5.1 for any encoder would be great.


Same file was used for all. Its specs are below the link.
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=8579#p27967
[ums_dbg v6.5.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/428186/ums_dbg.v6.5.zip)
[ums_dbg v3.2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/428187/ums_dbg.v3.2.zip)

General
Complete name                            : D:\Test\test file.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/avc1/iso6)
File size                                : 584 MiB
Duration                                 : 21 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 795 kb/s

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 9 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 21 min
Bit rate                                 : 3 595 kb/s
Maximum bit rate                         : 24.9 Mb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 59.940 (60000/1001) FPS
Original frame rate                      : 59.940 (59940/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.065
Stream size                              : 553 MiB (95%)
Title                                    : 264@GPAC0.5.2-DEV-rev58-ge59cb02-master
Writing library                          : x264 core 144 r2525 40bb568
Encoding settings                        : 

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 21 min
Bit rate mode                            : Variable
Bit rate                                 : 192 kb/s
Maximum bit rate                         : 198 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 spf)
Compression mode                         : Lossy
Stream size                              : 29.5 MiB (5%)

**Comment by valib** [comment]
@Walbuls now I don't understand what is the problem. Do you want to send stereo audio as 5.1 ? The testing file info you provided says there is only 2 channels audio.

**Comment by Sami32** [comment]
@Walbuls Thanks for your logs ;-)

@valib About Avisynth error i read that it's a DirectShow issue and found that post: http://video.stackexchange.com/questions/18819/avisynth-mp4-not-supported
Why not leave as default behavior as it is, and add an option, in GUI and UMS.conf, forcing the audio output to the number of channels choosen ?

**Comment by Walbuls** [comment]
@valib 
> @Walbuls now I don't understand what is the problem. Do you want to send stereo audio as 5.1 ? The testing file info you provided says there is only 2 channels audio.> 

It is 5.1 audio that was converted to 2.0 using Dolby Pro Logic 2. When Dolby Pro Logic 2 audio is passed to a receiver that can read DPL converted audio, it knows how to split the channels back apart. That type of audio ability is what I am looking for. Although it sounds like this might not happen at all, it was more of an artificial 5.1 done by UMS.

**Comment by valib** [comment]
@Walbuls this testing video is correctly streamed to the PS3 because it passed setting `Supported = f:mp4        v:mp4|h264               a:aac                m:video/mp4                n:2`. If it is not working it seems to me that PS3 doesn't have ability to do what you are looking for. In this case the only way how it could work is to transcode it back to 5.1. 
@Sami32 We can add this option but the only problem I see is that all AAC 2.0 audio doesn't matter if it is converted by Dolby Pro logic 2 or not will be transcoded to AC3 5.1. I don't see any way how to check the AAC 2.0 was made with Dolby. Anyway current implementation is a mess because it should work the same way for all transcoding engines.

**Comment by Walbuls** [comment]
Sounds fine then. Looks like I will make due. DPL can only be decoded by a dolby system or by using a licensed dolby decoder. 

I still wouldn't mind an option to transcode all audio to 5.1, even if we are faking it.

**Comment by Sami32** [comment]
@Walbuls if i understood correctly, you converted your file to Dpl2 yourself for use it with your PS3, right ?

@valib if it that case, it could be more simple using this FFmpeg filter: `aresample=matrix_encoding=dplii`
And for MPlayer something like that; https://hydrogenaud.io/index.php/topic,62940.0.html
And yes i agree that should be the same for all engines.

**Comment by Walbuls** [comment]
@Sami32 
> @Walbuls if i understood correctly, you converted your file to DPL2 for use them with your PS3, right ?> 

Yes, I had a 5.1 source that i converted to 2.0AAC with DPL2

**Comment by valib** [comment]
@Walbuls why do you convert them to AAC 2.0 when PS3 supports AC3 5.1?

**Comment by Walbuls** [comment]
Compatibility across all my devices (When watching without UMS). 5.1 doesn't work well on some.

**Comment by Sami32** [comment]
@Walbuls You are using a Java 32-bit version on your 64-bit Windows OS, and you are using the 32-bit FFmpeg executable, so it fail.
`INFO  2016-08-20 03:03:10.306 [ffmpeg.exe-10] Process C:\Program Files (x86)\Universal Media Server 3.2\win32\ffmpeg.exe has a return code of 1! Maybe an error occurred... check the log file`

`INFO  2016-08-20 03:03:15.663 [mencoder.exe-11] Process C:\Program Files (x86)\Universal Media Server 3.2\win32\mencoder.exe has a return code of 1! Maybe an error occurred... check the log file`

In the log (3.2) where you said it work, VLC is used, as FFmpeg and Mencoder failed.
```
DEBUG 2016-08-20 03:03:18.720 [New I/O worker #14] Found VLC version 2.2.4 in Windows Registry: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
DEBUG 2016-08-20 03:03:18.720 [Thread-71] Waiting for pipe connection \\.\pipe\VLC1471680198720.ps
TRACE 2016-08-20 03:03:18.720 [New I/O worker #14] Finalized args: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe -I dummy --dummy-quiet D:\Test\test file.mp4 --audio-track=0 --sub-track=214748361 --sout #transcode{ab=640,vcodec=mp2v,channels=2,strict-rc,soverlay,acodec=mp2a,scale=1.0,threads=8,vb=4096,keyint=16,samplerate=48000}:standard{access=file,mux=ps,dst='\\\\.\pipe\VLC1471680198720.ps'} vlc://quit
TRACE 2016-08-20 03:03:18.876 [New I/O worker #14] Sleeping for 6000 milliseconds
DEBUG 2016-08-20 03:03:18.876 [vlc.exe-12] Starting "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" -I dummy --dummy-quiet "D:\Test\test file.mp4" --audio-track=0 --sub-track=214748361 --sout #transcode{ab=640,vcodec=mp2v,channels=2,strict-rc,soverlay,acodec=mp2a,scale=1.0,threads=8,vb=4096,keyint=16,samplerate=48000}:standard{access=file,mux=ps,dst='\\\\.\pipe\VLC1471680198720.ps'} vlc://quit
DEBUG 2016-08-20 03:03:18.892 [vlc.exe-12] Reading pipe: \\.\pipe\VLC1471680198720.ps
```
I would suggest you to cleanly uninstall your Java and reinstall the correct version.
Then do a clean UMS install with the latest version.

I just become suspicious: **What is your CPU model ?**

If you still get issue, please post a new log, as the logging verbose was enhanced.
But try without using AviSynth/FFmpeg and AviSynth/MEncoder as you did.

**Comment by Sami32** [comment]
@Walbuls When you(ll have a working UMS installed, you will just need to add this line into your renderer configuration file:
`CustomFFmpegOptions =  -af aresample=matrix_encoding=dplii -ac 2`

Can this issue be closed now ?

**Comment by Nadahar** [comment]
This seems abandoned, reopen if the issue still isn't solved.
