### ISSUE TITLE
Extend automated testing

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#524]
There have been a lot of bugs lately that could have been prevented by extending our automated testing.
We should have more comprehensive tests that make sure our code is delivering what the renderer configs tell it to deliver.
I'll be working on this when I have the spare time, and if other @UniversalMediaServer/developers have the time I think it would be really useful to the stability of the program.

**Comment by SubJunk** [comment]
Some tests were added in #561

**Comment by SubJunk** [comment]
More tests are being added in #572

**Comment by Sami32** [comment]
@SubJunk Are you satisfied by the actual automated tests ?

**Comment by SubJunk** [comment]
@Sami32 I'd like to see at least 80% test coverage of our code but we probably only have about 1% so I'm not satisfied but we can close this issue since it needs to be an ongoing goal that will never be reached
