### ISSUE TITLE
Debug log path broken on Java 6 version

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#527]
In the traces window it says:

debug.log: debugLogPath_IS_UNDEFINED\debug.log

And there's an error when you click the "Open full debug.log" button.

@skeptical could this be related to the recent trace logging changes?

**Comment by skeptical** [comment]
@SubJunk probably :). Was away, will take a look soon.

**Comment by skeptical** [comment]
@SubJunk I'm guessing your ```logback.xml``` needs to be updated, see 3672973.

**Comment by SubJunk** [comment]
@skeptical it's using this version of the file https://github.com/UniversalMediaServer/UniversalMediaServer/blob/Java6/src/main/external-resources/logback.xml which is the same as the master version

**Comment by skeptical** [comment]
@SubJunk you're right, Java6 branch gives me the same error (now that I actually tried it :-). Haven't found any reason why it might be different fron java7 so far.

**Comment by SubJunk** [comment]
@skeptical ah great work, that's my fault for merging it like that :)

**Comment by skeptical** [comment]
@SubJunk happens to me all the time too, some things I never learn :P.
