### ISSUE TITLE
Resolution sent to renderer is not correct for rescaled/expanded files

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#531]
Playing file with e.g. 1920x800 resolution. When renderer is configured to rescale resolution by UMS, subs are added so res is expanded, keepAspectRatio is true etc., final file is 1920x1080 but sent resolution is 1920x800.
Some renderers can use it to manually add missing black bars so it can break final AR. Real resolution should be sent instead of original non-transcoded ones as metadata.

**Comment by ExSport** [comment]
v5.1.2 used

**Comment by SubJunk** [comment]
@ExSport thanks for the report, can you link to trace logs for it?

**Comment by ExSport** [comment]
@SubJunk If still required one example for both transcoding engines:
```
TRACE 09:56:16.610 [New I/O worker #2] <?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
<Result>&lt;DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"&gt;&lt;item id="25" parentID="24" restricted="true"&gt;&lt;dc:title&gt;Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv [FFmpeg]&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_HD_24_AC3_ISO;DLNA.ORG_OP=10" duration="01:38:58.00" resolution="1920x816" bitrate="2032810" nrAudioChannels="6" sampleFrequency="48000"&gt;http://192.168.1.3:5001/get/25/Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv&lt;/res&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_HD_24_AC3_ISO;DLNA.ORG_OP=10" duration="01:38:58.00" resolution="1920x816" bitrate="2032810" nrAudioChannels="6" sampleFrequency="48000"&gt;http://192.168.1.3:5001/get/25/Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv&lt;/res&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_HD_24_AC3_ISO;DLNA.ORG_OP=10" duration="01:38:58.00" resolution="1920x816" bitrate="2032810" nrAudioChannels="6" sampleFrequency="48000"&gt;http://192.168.1.3:5001/get/25/Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv&lt;/res&gt;&lt;upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN"&gt;http://192.168.1.3:5001/get/25/thumbnail0000Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv&lt;/upnp:albumArtURI&gt;&lt;upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM"&gt;http://192.168.1.3:5001/get/25/thumbnail0000Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv&lt;/upnp:albumArtURI&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</Result>
<NumberReturned>1</NumberReturned>
<TotalMatches>1</TotalMatches>
<UpdateID>2</UpdateID>
</u:BrowseResponse>
</s:Body>
</s:Envelope>
DEBUG 09:57:02.587 [New I/O worker #4] Starting transcode/remux of Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv with media info: container: mkv, bitrate: 16262485, size: 12072353935, video codec: h264, duration: 01:38:58.00, width: 1920, height: 816, frame rate: 24.000, thumb size: 5924, mime type: video/x-matroska, matrix coefficients: BT.709, attached fonts: false
DEBUG 10:00:51.956 [ffmpeg64.exe-8] Starting C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe -y -loglevel info -i E:\_Test_\Belle.et.Sebastien.2013.1080p.DTS.HDMA\Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv -filter_complex subtitles=C\\:/ProgramData/UMS/data/subs/Bella.a.Sebastian.2013.1080p.AC3.CZ_ID0_1413807101263.ass,pad=iw:iw/(16/9):0:(oh-ih)/2,scale=1920:1080 -map 0:v -map 0:a:0 -bufsize 31250000 -maxrate 31250000 -crf 19 -c:a copy -c:v libx264 -preset superfast -level 31 -pix_fmt yuv420p -f mpegts \\.\pipe\ffmpegvideo_54_1429430451588
DEBUG 10:54:32.709 [mencoder.exe-19] Starting C:\Program Files (x86)\Universal Media Server\win32\mencoder.exe -ss 0 E:\_Test_\Belle.et.Sebastien.2013.1080p.DTS.HDMA\Bella.a.Sebastian.2013.1080p.AC3.CZ.mkv -msglevel statusline=2 -oac copy -of lavf -lavfopts format=mpegts -mpegopts format=mpeg2:muxrate=500000:vbuf_size=1194:abuf_size=64 -ovc lavc -channels 6 -lavdopts debug=0:threads=4 -lavcopts aspect=16/9:vcodec=libx264:threads=4:o=preset=superfast,crf=19,g=250,i_qfactor=0.71,qcomp=0.6,level=3.1,weightp=0,8x8dct=0,aq-strength=0,me_range=16:vrc_maxrate=31250:vrc_buf_size=31250 -ass -ass-color ffffff00 -ass-border-color 00000000 -ass-font-scale 1.4 -font C:\Windows\Fonts\Arial.ttf -ass-force-style FontName=C:\Windows\Fonts\Arial.ttf,Outline=1,Shadow=1,MarginV=10 -fontconfig -aid 0 -noautosub -sid 0 -ofps 24 -vf expand=::::0:16/9,scale=1920:1080,softskip -lavdopts fast -mc 0 -noskip -o \\.\pipe\mencoder1429455272686
```
Resolution 1920x816 is sent to renderer as metadata but transcoded file is 1920x1080 as FFmpeg&MEncoder show.

**Comment by ExSport** [comment]
Right now I am not sure why I see scale filter in MEncoder when I don't use any rescaling:
```
-vf expand=::::0:16/9,scale=1920:1080,softskip
```
I understand expand filter to fix Panasonic AR problem so black bars are added to fit 16:9 AR.
With resolution 1920x816 there is no need to scale again which is more CPU intensive than expand and also why rescale something what is already 1920x1080 after applied "expand"?
Ok, in PanTV config there is RescaleByRenderer=false so UMS will rescale when renderer is not good it it but it should be applied to non SD/HD files only! In code I saw "if res.width < 720" which means to not rescale anything better or equal to PAL SD (720x576).
@valib @SubJunk @skeptical Do someone remember why "scale" is used here? :)

**Comment by SubJunk** [comment]
@ExSport I think it's to make sure the output is a compatible resolution. We were getting some weird output resolutions like 1281x619, which fail on most renderers because they need mod2 or mod4.

**Comment by ExSport** [comment]
@Subjunk If I remember right, the last number defines mod so there is no need for scale - this makes res mod 4:
```
-vf expand=::::0:16/9:4
```
Now I know why some files started stuttering. I thought it is mainly due to slow MEncoder and required subs in combination with h.264 transcoding instead of mpeg2. Now I see there is also another factor and it is useless scaling when there is expand already there for same purpose but much cpu less intensive.
I must make some other tests with 720p files if they will be scaled to 1080p or only made mod4 and stay in 720p because my first thought was it can be due to RescaleByRenderer=false and some bug in code.
Will test it and let you know if it affects anything.
I made some speed tests years ago with MEncoder and expand/rescale and I remember both filters were quite different in speeds so for my system most of the files with subs, MEncoder,h.264 transcoding,scale to 1080p stutter on core2 quad core system for real-time transcoding. FFmpeg is faster but with embedded subs it is no go.
Thx

**Comment by SubJunk** [comment]
@ExSport I looked this up and found that you're right, and it's a cool setting. It rounds "up" to the mod though which means we will have to anticipate whether it will push the video over the resolution limit, but that's not too hard. I'll do it soon

**Comment by SubJunk** [comment]
@ExSport I did a somewhat lazy implementation of this in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/95ca8a8bb8ec66d158b184ed03e09e7f470883d0

It seems that the FFmpeg "pad" option doesn't have a mod argument so I don't think we can do the same with that.

**Comment by SubJunk** [comment]
@ExSport by the way I'm still interested in seeing logs - just pasting a few lines from logs often doesn't show us what we want to see so it would be cool to get the whole thing :)

**Comment by ExSport** [comment]
@Subjunk Then it is pity there is no expand equivalent in FFmpeg. BTW. Using 16/9:4 will never get over resolution. For 720p mod is OK up to 16 and for 1080p it is OK up to mod 8 as mod 16 creates 1920x1088 I suppose which is still in most cases OK. Not sure with 3D content:-)
About logs, I copied them from two different logs as one was with FFmpeg and other one with MEncoder but both logs were created when I troubleshoot thumbs regeneration or problem of subs exporting which generated 4min delay unacceptable for renderers.
Will take a look for them and resend it today

**Comment by SubJunk** [comment]
@ExSport Yeah it is a pity! Maybe we should request they add the extra parameter.

**Comment by ExSport** [comment]
@SubJunk I am not sure what exactly you are trying to find in logs but here you are:
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=16151#p16151

**Comment by SubJunk** [comment]
@ExSport I wonder if this is a reliable way to make sure the video is mod4? expand=::::0::4
Then we can avoid the scale filter even more

**Comment by ExSport** [comment]
@SubJunk For e.g. 1920x816 final mod 4 res will be 1920x816 so yes it is mod-reliable but not AR+subs reliable. I expect when 16/9 is omitted, renderer like Panasonic TV will squeze picture but I expect PS3 will be OK as expand wasn't needed to have correct AR when I tested it years ago when I introduced this "expand,softskip :0: or :1: and 16/9 things". But with enabled subs I am not sure as subs will be rendered to picture and not to the added black bars so PanTV will squeze picture and PS3 will show subs too high in the picture?
This should be tested but I am sure defining 16/9 AR is nothing contraproductive (except Sony or what renderer is it which needs specail formula, already set in renderer conf or directly in code...don't remember exactly)

**Comment by ExSport** [comment]
Hi guys.
What is the state of this? :-)

**Comment by valib** [comment]
@ExSport it is implemented since that time. Is it working or not?

**Comment by Sami32** [comment]
@ExSport @SubJunk So, did @valib  and @Nadahar commits fixed that issue ?

**Comment by SubJunk** [comment]
I think it's fixed now. Can re-open if not
