### ISSUE TITLE
Defer always to MEncoder for internal subs until FFmpeg fully support it

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#532]
New clean install of v5.1.2. As a possible newbie I will try to play file... Nothing works and my Panasonic TV displays loading and after 30sec it fails. Uninstalling crappy sw...
Root cause when reading the log:
My PanTV doesn't support mkv and any subs. By default FFmpeg is used and almost all of my files have internal or external subs, full or forced.
When I tried to play mkv file with internal forced subs, after clean install, loading on TV failed. One minute later I played file again, it failed, next minute again it failed, next minute it failed again. After four minutes from first try, file stated to play.
Log says: internal subs found in 11GB mkv file. Exporting them by FFmpeg takes 3.5min and after that transcoding is started and failed as TV already closed connection. After 4min, when extracted subs exists, transcoding starts successfully on renderer.
Conclusion: until FFmpeg will not support internal subs natively, we will have lot of complains why UMS doesn't work. I already saw this problem on forum with errors like network connection was forcibly closed by remote host,... Exporting subs takes too much time to be generally usable.
Or is there other option how to avoid broken connection, file can't be played etc., meanwhile subs are exported? I suppose FFmpeg still doesn't support them:-(
Thx

**Comment by SubJunk** [comment]
@ExSport we do have a GUI setting called "defer to MEncoder when transcoding subtitles" on the FFmpeg settings page. That will do what you want. I have wondered about enabling it by default too.

Yeah AFAIK FFmpeg doesn't support internal subtitles without parsing the whole file first - so even if we do ask it to do it internally like this https://github.com/UniversalMediaServer/UniversalMediaServer/pull/470 it still has the loading time at the start.

What do @UniversalMediaServer/developers think about enabling the "defer to MEncoder when transcoding subtitles" FFmpeg option by default?

**Comment by valib** [comment]
@ExSport FFmpeg supports embedded subs but it always internally parse them before the video is played. That is why the support was removed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/91c4e752673e66d8d4019c858a900a3b4bdaaa8c. And extracting takes almost the same time. I have no idea how MEncoder is dealing with the embedded subs and if it will be faster but we can try it.

**Comment by SubJunk** [comment]
@valib :) MEncoder seems to start transcoding instantly with subs so it must skip the initial parse. I wish FFmpeg cared more about subs but they seem to have little interest in it

**Comment by ExSport** [comment]
@SubJunk @valib Yes I know there is "defer" option. But when talking about newbie, they can't imagine why almost any of their files doesn't work. It is because FFmpeg is default engine and "defer"  disabled by default so any file with embedded subs is unplayable so UMS doesn't work. Uninstall.
At this stage UMS behavior must be different by default so file will be played any time. General user will never imagine file doesn't work because 4mins in the background there is extraction initiated so user tries it 3x times? and not more so will never spot file started to work. In most cases user will try another file with same problems.
As MEncoder plays file immediately without required internal or external extraction, it is only possibility how to avoid broken files on renderers.
Btw. with new clean install and playing files like above, it is almost impossible to find root cause in log for general user. As thumbs generation is enabled and doesn't work correctly until UMS is restarted (check another issue I created), there is 60 FFmpeg records in log in few minutes as every failed try playing file or general refresh of folder generates new thumbs so logs shows huge amount of FFmpeg processes in log so the one which extracts subs and other one which loads the subs (4mins later after it was initiated on renderer) are totally hidden between other thumb processes. I found out root cause after 2-3 hours of troubleshooting :+1: 
So my opinion is a must of "defer to MEncoder" for embeded ones or FFmpeg with support of embedded subs.

**Comment by SubJunk** [comment]
@ExSport I agree we should always have the most stable defaults. I've enabled it by default in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/a96cae6dbbb48f21a96606afb65a3d1cd2d90302

**Comment by ExSport** [comment]
@Great, thx.
What about to enable defer for embedded subs only as FFmpeg is faster.
I hope this change will reduce reports that UMS doesn't work for most of the files as there are lot of non-english native speakers so the chance they are using any subs is almost 100%.
Thx!

**Comment by SubJunk** [comment]
@ExSport yeah it might be better to change the setting to only embedded subs, I think you're right.

**Comment by SubJunk** [comment]
@ExSport I think maybe FFmpeg can handle internal ASS/SSA subtitles instantly too, or maybe I'm not remembering it right...?

**Comment by ExSport** [comment]
@Subjunk Not sure I have any mkv with embedded ass/SSA subs. Will try to create one and test it. Not at home so all will be from command line but it is enough to see if there will be export delay or not.

**Comment by ExSport** [comment]
@SubJunk I extracted srt subs to ass with FFmpeg and muxed them back to mkv file.
When I started transcoding the first subs track (srt) or second subs track (ass), there is no difference, all have about 4min delay so it is irrelevant what format embedded subs have.

**Comment by SubJunk** [comment]
@ExSport okay cool, thanks for testing that

**Comment by Sami32** [comment]
@SubJunk @valib https://github.com/UniversalMediaServer/UniversalMediaServer/commit/39fee865129c059ca2acc5f6f5762771b6e477d6 Could it be considered as solved for now ?
