### ISSUE TITLE
FFmpeg attached font support

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#533]
It is a known issue to us that FFmpeg doesn't support attached fonts but I'm putting it up here now that FFmpeg have an issue for it on their trac: https://trac.ffmpeg.org/ticket/4465

Hopefully they can move on it soon and then we can remove the UMS condition that defers to MEncoder when embedded fonts exist

**Comment by Sami32** [comment]
@SubJunk Did that commits https://github.com/UniversalMediaServer/UniversalMediaServer/commit/39fee865129c059ca2acc5f6f5762771b6e477d6 solved this issue already ?

**Comment by SubJunk** [comment]
It's no bother, it's very helpful. I want to get these issues into a better state so I welcome the help
