### ISSUE TITLE
Slow loading and seeking on PS3

### ISSUE THREAD

**Issue by vertigo220** [UniversalMediaServer/UniversalMediaServer#534]
I just found UMS, and it seems to be a very nicely done program, but for some reason it takes a significantly longer time to load most videos and is extremely slow at rewinding and fast-forwarding compared to other media servers, such as Serviio and Mezzmo. I'd really like it to work for me, since it has some great features and seems to be well done, and while Serviio and Mezzmo work pretty well, with the former being my primary and the latter being my backup, I sometimes have issues with them and was hoping to find a new primary server in UMS. Does anybody have any ideas why it would be so slow, and if there are hopefully just some settings I can tweak to improve it? Unfortunately, I didn't have the logging level set to trace when it happened and now I'm unable to repeat it, so I've not included the log and I'm not sure if it was an issue with certain videos (it didn't happen with all) or if it was just acting up for a short time.

Also, I've noticed UMS takes a very long time to load the contents of a directory; much, much longer than the other servers. This is the case both on the PS3 and on my phone with BubbleUPnP.

**Comment by SubJunk** [comment]
@vertigo220 thanks for the post. Loading is almost instantaneous on my PS3 so we will need logs to see what's going on :)

**Comment by vertigo220** [comment]
Yeah, I'm thinking it was just a weird fluke. If it happens again I'll be sure to get the logs. What about loading of directory contents, i.e., does it take a long time to begin loading the contents of directories with a lot of videos in them, and do they load a handful at a time then pause for a couple seconds (that's how it is for me), or is it quick? Unfortunately, it doesn't log anything for just accessing a folder, so attaching logs for that won't help, but I'm curious if others have the same problem.

**Comment by SubJunk** [comment]
I think PS3 loads items in chunks of 20 so yeah that is normal :) Closing this as it seems to be resolved
