### ISSUE TITLE
fix NPE when pid file is empty

### ISSUE THREAD

**Issue by comicfans** [UniversalMediaServer/UniversalMediaServer#540]
if ums.pid contains nothing , killProc will throw NPE  when ProcessBuilder construct. 
```diff
diff --git a/src/main/java/net/pms/PMS.java b/src/main/java/net/pms/PMS.java
index 00a3f2f..b1c32da 100644
--- a/src/main/java/net/pms/PMS.java
+++ b/src/main/java/net/pms/PMS.java
@@ -1397,6 +1397,10 @@ public class PMS {
                        pid = in.readLine();
                }

+        if (pid == null) {
+            return;
+        }
+
                if (Platform.isWindows()) {
                        if (verifyPidName(pid)) {
                                pb = new ProcessBuilder("taskkill", "/F", "/PID", pid, "/T");
```

**Comment by skeptical** [comment]
@comicfans thx :-), applied in 5a3c09f.

**Comment by valib** [comment]
There is a temporary error before the ums.pid file is created. This fix an error when this file could be empty but the error will appear always when the UMS is running for the first time with the admin privilege.

**Comment by skeptical** [comment]
@valib yeah, I'm not sure how exactly how  the empty file scenario might happen, but the resulting NPE will prevent startup for no good reason.
