### ISSUE TITLE
Website timeout 

### ISSUE THREAD

**Issue by Optimusprimeums** [UniversalMediaServer/UniversalMediaServer#541]
@SubJunk mate getting a 
Fetching of original content failed with the following error: Proxy Publisher Failure - TIMEOUT. If you own this domain, please consult this FAQ.
from the forum

**Comment by SubJunk** [comment]
@Optimusprimeums hmm this is happening a lot lately. I'll try disabling Google Pagespeed and see if that helps. The server is running fine and I can connect to it via IP address normally so it's something between the server and our computers.

**Comment by Optimusprimeums** [comment]
too easy, @SubJunk i know what thats like. Seems ok now

**Comment by SubJunk** [comment]
I've been talking to my hosting company about this and they said next time it happens, can we run an MTR on the server's IP. If you spot it happening can you please use this tool https://sourceforge.net/projects/winmtr/ or another one to do the MTR?

**Comment by Optimusprimeums** [comment]
@SubJunk can do mate, thats why i'd rather host a home :)

**Comment by Optimusprimeums** [comment]
hey mate very slow to get a connection with the site. Every now and again i get a full page load then nil response. here's a MTR printout
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                           192.168.2.100 -    0 |   50 |   50 |    0 |    0 |    1 |    0 |
|                           192.168.0.254 -    0 |   50 |   50 |    0 |    1 |    2 |    1 |
|                lo0.lns20.syd4.on.ii.net -    3 |   46 |   45 |    0 |   27 |   33 |   28 |
|            xe-11-2-1.cr1.syd4.on.ii.net -    3 |   46 |   45 |    0 |   28 |   38 |   29 |
|                   No response from host -  100 |    9 |    0 |    0 |    0 |    0 |    0 |
|            te0-0-0-1.br1.lax1.on.ii.net -    3 |   45 |   44 |    0 |  175 |  181 |  176 |
|              los-brdr-01.inet.qwest.net -    3 |   45 |   44 |    0 |  174 |  180 |  174 |
|                   No response from host -  100 |    9 |    0 |    0 |    0 |    0 |    0 |
|      63-234-188-82.dia.static.qwest.net -    3 |   45 |   44 |    0 |  186 |  192 |  187 |
|             vl-119.core2.phx1.ip.io.com -    3 |   45 |   44 |    0 |  195 |  204 |  199 |
|             te-1-2-core2.scd1.ip.io.com -    0 |   49 |   49 |  195 |  197 |  209 |  197 |
|             vl-103.edge1.scd1.ip.io.com -    0 |   49 |   49 |  219 |  221 |  256 |  221 |
|                           174.128.25.52 -    0 |   49 |   49 |  192 |  193 |  203 |  193 |
|                           65.23.129.103 -    0 |   49 |   49 |  192 |  201 |  221 |  197 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by Optimusprimeums** [comment]
This is after around 20mins of time |------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                           192.168.2.100 -    0 |  632 |  632 |    0 |    0 |    2 |    0 |
|                           192.168.0.254 -    0 |  632 |  632 |    0 |    0 |   34 |    1 |
|                lo0.lns20.syd4.on.ii.net -    1 |  624 |  622 |    0 |   27 |   79 |   26 |
|            xe-11-2-1.cr1.syd4.on.ii.net -    1 |  624 |  622 |    0 |   27 |   62 |   27 |
|                  ae5.br1.syd4.on.ii.net -   78 |  153 |   34 |    0 |   33 |   66 |   30 |
|            te0-0-0-1.br1.lax1.on.ii.net -    1 |  627 |  626 |    0 |  174 |  237 |  174 |
|              los-brdr-01.inet.qwest.net -    1 |  627 |  626 |    0 |  174 |  236 |  175 |
|                   No response from host -  100 |  126 |    0 |    0 |    0 |    0 |    0 |
|      63-234-188-82.dia.static.qwest.net -    1 |  627 |  626 |    0 |  187 |  739 |  184 |
|             vl-119.core2.phx1.ip.io.com -    1 |  627 |  626 |    0 |  193 |  251 |  202 |
|             te-1-2-core2.scd1.ip.io.com -    0 |  631 |  631 |  195 |  201 |  386 |  197 |
|             vl-103.edge1.scd1.ip.io.com -    0 |  631 |  631 |  219 |  221 |  272 |  221 |
|                           174.128.25.52 -    0 |  631 |  631 |  191 |  192 |  271 |  193 |
|                           65.23.129.103 -    0 |  631 |  631 |  191 |  200 |  279 |  196 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by SubJunk** [comment]
@Optimusprimeums thanks for that, I've passed it on to the host. Unfortunately residential upload speeds in this country aren't good enough to host high traffic servers, at least not in my experience, otherwise I'd look at doing it myself too. These guys do know more about servers than I do though and they're very helpful so there are perks.

**Comment by Optimusprimeums** [comment]
@SubJunk not a problem. Used to host off site until the NBN over this way came along. It's good too see your host trying to fix it!!

**Comment by SubJunk** [comment]
@Optimusprimeums they said:

"It doesn't seem to be a networking problem. The packet loss I'm seeing doesn't carry over to the other hops. That is usually an indication that the hop is deprioritizing icmp packets."

but they changed some settings on my server to try to help. Please let me know if it happens again

**Comment by Optimusprimeums** [comment]
@SubJunk Will do mate

**Comment by Sami32** [comment]
@Optimusprimeums @SubJunk Did this issue fixed ? No news good news :-)
