### ISSUE TITLE
Merge the Windows/Linux and OS X poms

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#548]
The only difference between the OS X branches and the Windows/Linux branches AFAIK is the pom.xml files, so if we can find a way of having conditional statements in that file or something, it will cut down the time we spend tagging by half, and be less messy with 3 tags for each release instead of 6.

**Comment by Optimusprimeums** [comment]
@Subjunk might have a fix for this but just need to do some testing. I believe that the App blunder/launcher used for the Java 7/8 releases may work with Java 6 versions as well. If so that will cut us back down to 3, i'll do some testing and let you know

**Comment by SubJunk** [comment]
@Optimusprimeums awesome!

**Comment by Optimusprimeums** [comment]
@Subjunk can we have it like this, one Java6 build and one for Java 7 and one for 8. If thats the case the only pom.xml difference is for Java6. I know by having a split pom.xml it may create some minor confusion but the App Bundler for Java 7/8 isn't at all compatible with the Java 6 binarys that apple use. Java 6 has to use apples bundler full stop.....

**Comment by Optimusprimeums** [comment]
@SubJunk i have a solution, i will get the pull request ready in the next few days.

**Comment by Optimusprimeums** [comment]
@SubJunk https://github.com/UniversalMediaServer/UniversalMediaServer/pull/552 ready to go

**Comment by Sami32** [comment]
@SubJunk Since @Optimusprimeums fixed this issue and that you merged it already, can it be closed now ?

**Comment by Nadahar** [comment]
This has been in effect for a long time already.
