### ISSUE TITLE
can't read mp4

### ISSUE THREAD

**Issue by rd1** [UniversalMediaServer/UniversalMediaServer#563]
ums chokes on some mp4, shows black screen, no sound, timer display doesn't move from 0:00:00. cpu is active on computer buffers goes up tp 300mb in ram but nothing output to tv bravia kdl w600b

here is one mediainfo header
General
Complete name               : 
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom
File size                   : 40.3 MiB
Duration                    : 1mn 20s
Overall bit rate mode       : Variable
Overall bit rate            : 4 199 Kbps
Encoded date                : UTC 2014-11-27 20:11:10
Tagged date                 : UTC 2014-11-27 20:11:10

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings, CABAC      : Yes
Format settings, ReFrames   : 3 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1mn 20s
Bit rate mode               : Variable
Bit rate                    : 3 876 Kbps
Maximum bit rate            : 62.5 Mbps
Width                       : 1 920 pixels
Height                      : 800 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.105
Stream size                 : 37.2 MiB (92%)
Encoded date                : UTC 2014-11-13 18:15:54
Tagged date                 : UTC 2014-11-27 20:11:10

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 1mn 20s
Bit rate mode               : Variable
Bit rate                    : 320 Kbps
Maximum bit rate            : 328 Kbps
Channel(s)                  : 2 channels
Channel(s)_Original         : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 KHz
Compression mode            : Lossy
Stream size                 : 3.07 MiB (8%)
Language                    : English
Encoded date                : UTC 2014-11-13 18:17:23
Tagged date                 : UTC 2014-11-27 20:11:10

**Comment by Deviator13** [comment]
Same problem here, can't play mp4, got only black screen. Sony Bravia KDL-48W585B.

**Comment by Sami32** [comment]
@rd1 @Deviator13 Please, post your full trace log following these steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by rd1** [comment]
it's an old thread, problem's been solved. 

thanks anyway
