### ISSUE TITLE
disable_transcode_for_extensions can't be enforced if subtitles are not explicitly disabled

### ISSUE THREAD

**Issue by Iridias** [UniversalMediaServer/UniversalMediaServer#565]
**Problem**: even setting disable_transcode_for_extensions to "*" will sometimes result in UMS transcoding a file!

**Investigation**: after having a look at the source-code it seems, that this config-entry will only be used to determine compatibility, but not to enforce not transcoding the matched files.
In `net.pms.dlna.DLNAResource#resolvePlayer` its used to determine compatibility, but when deciding if transcoding is preferred, it might get overruled by the existence of subtitles:
`boolean preferTranscode = isIncompatible || hasSubsToTranscode;`
(Unless of course they're not disabled as well)

In the final decision there is a check for `isSkipTranscode()`, but this member is never set!

**possible solution**: allow setting the skipTranscode-member by configuration.

**temporary workaround for users**: disable subtitles in the config (key is: disable_subtitles )

**Comment by Sami32** [comment]
@Iridias Please, could you post your full trace log when that's append, following these steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by Nadahar** [comment]
@Sami32 There's no need for a log, the problem is fully explained. This isn't a bug, it's a "design flaw".

**Comment by Sami32** [comment]
Using `disable_transcode_for_extensions` in UMS.conf, alone, will not have effect on files with subtitle(s).` StreamExtensions = ` in the renderer configuration will not either.
But using the two together will do the trick, AFAIU.
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/dlna/DLNAResource.java#L607-L621

It need to use `VideoFormatsSupportingStreamedExternalSubtitles = `, `SupportedInternalSubtitlesFormats = ` and `SupportedExternalSubtitlesFormats = ` to get the job done without disabling the subtitles (`disable_subtitles`).

**Note**: `disable_transcode_for_extensions` is given as a test, debugging function, and the renderer configuration parameters should be preferred.
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1040

**Comment by Nadahar** [comment]
@Iridias This should finally be fixed now with #1053. This will be a part of the next release.
