### ISSUE TITLE
[Request] Check if Xbox One support HEVC in MKV

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#568]
Microsoft recently added support for HEVC/H.265 to Xbox One (http://wccftech.com/xbox-update-fixes-multiplayer-issues-adds-hevc-10bit-codec-patch-notes-detailed/).

Their changelog states that they added it for apps so we need someone to test if it will work via UMS.

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers does anyone have an Xbox One and can test this quickly? I can provide a sample file if you don't have any

**Comment by SharkHunter** [comment]
I got an XB1 so I'll test just send a file (and maybe an image)

**Comment by SubJunk** [comment]
@SharkHunter awesome, check this out :) http://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Windows/VideoTestingSuite-1.0.7z/download

**Comment by SharkHunter** [comment]
DOn't I need any new code for this?

**Comment by SubJunk** [comment]
No, you can use the [No encoding] entries in the #-TRANSCODE-# folder to see which files are compatible

**Comment by SharkHunter** [comment]
Nope it doesn't seem like it's in teh mediaplayer. The NoEncoding doesn't work (playing via encoders works like a charm though)

**Comment by SubJunk** [comment]
Thanks for checking :)
