### ISSUE TITLE
Pictures from web pages not playable on the UMS web interface

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#576]
@UniversalMediaServer/developers I tried to retest the UMS web interface and found that all pictures from the image feeds in the WEB.conf are marked like

`<li>
					<a class="webdisabled" href="javascript:notify('warn','This item not playable via browser but can be sent to other renderers.')" title="Taipei-61.jpg (NOT PLAYABLE IN BROWSER)"><img class="thumb" src="/thumb/270" alt="Taipei-61.jpg"></a>
					<a class="bumpIcon" href="javascript:bump.start('//10.0.0.3:80','/play/270','Taipei-61.jpg')" title="Play on another renderer"></a>
<a class="playlist_add" href="#" onclick="umsAjax('/playlist/add/270', false);return false;" title="Add to playlist"></a>
					<span class="webdisabled caption">Taipei-61.jpg</span>
				</li> `

Can somebody confirm that bug or I have something set wrong? Tested clean instalation.

**Comment by skeptical** [comment]
@valib working for me now after a061b03, 99ecccb, and ade2eee.  Please test :-).

**Comment by valib** [comment]
@skeptical great job. Pictures are working again but the same bug is for video.

**Comment by valib** [comment]
@skeptical it could be nice to make images to fit the browser window size and not to show them in the original size. To show the original size should be possible to double click on the image and the second double click should again resize the image to fit the window. Do you think that it is possible?

**Comment by skeptical** [comment]
@valib I've got a couple of half-done implementations of that in my old stuff I could dust off. I agree an image viewer without fit/zoom is pretty weak :P.

Btw image feed thumbs turn out horrible (upscaled/blocky) in web interface (at least from google plus / picasa which I was testing).  We should look into that too.
