### ISSUE TITLE
Look into Plex's transcoder

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#582]
It seems like Plex is able to use their modified version of FFmpeg to transcode to PS4, which we don't appear to be able to do.
I think FFmpeg's licensing will allow us to use the transcoder from Plex, I will have to double-check on that if we find that it works.
Basically they have modified it to take some new commands that seem to improve compatibility on picky devices.

**Comment by ExSport** [comment]
https://github.com/mine260309/ps3mediaserver/issues/1

**Comment by ExSport** [comment]
It seems generated file is compatible but not when played in real-time. Generated transcoded file streamed to PS4 works as stated in linked post...

**Comment by SubJunk** [comment]
Yeah that's one of the things that has made me think the difference is the Plex transcoder

**Comment by ExSport** [comment]
It seems to me that transcoded file by our ffmpeg version is compatible but problem is how it is streamed to ps4. Maybe testing Plex transcoding if it works as is and then test it with replacing their ffmpeg with our if anything will change. If it will play than problem is how file is sent to the renderer...

**Comment by ExSport** [comment]
Btw. has the _-tune zerolatency_ any effect on better compatibility for PS4? Worth a try...

**Comment by valib** [comment]
It seems to me that the solution is to send to renderer a fake chunk of the video when it is asking for it before it start to play the video. It was reported somewhere that PS4 (and also some other renderers) are asking for some video samples from the middle and the end of the file before it start playing. I think that Plex or Serviio do that trick. I think that It has nothing to do with FFmpeg version.

**Comment by SubJunk** [comment]
Yeah zerolatency is worth a try ExSport, will try that now. Plex doesn't use that command but it could still be good
