### ISSUE TITLE
Endless loop during ContentDirectory1#Browse when some files are filtered

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#584]
I've enountered a bug where browsing certain folders from a Onkyo renderer will result in an endless loop between UMS and the renderer. UMS will spawn hundreds of threads in no time and the log grows like crazy spamming e.g.
```
DEBUG n.p.c.RendererConfiguration - Matched media renderer "TX-NR807" based on address /10.72.64.23
DEBUG n.p.c.RendererConfiguration - Matched media renderer "TX-NR807" based on address /10.72.64.23
DEBUG n.p.c.RendererConfiguration - Matched media renderer "TX-NR807" based on address /10.72.64.23
```

The trace log doesn't reveal much more, to me at least (this is just a snippet, it repeats the same pattern for endless threads):

```
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Opened request handler on socket /10.72.64.23:4553
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Request: HTTP/1.1 : POST : upnp/control/content_directory
06:02:17.672 [nioEventLoopGroup-3-2] DEBUG n.p.c.RendererConfiguration - Matched media renderer "TX-NR807" based on address /10.72.64.23
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Connection: close
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Content-Type: text/xml; charset=utf-8
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Content-Length: 694
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Host: 10.72.64.11:5001
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Received on socket: User-Agent: Mediabolic-IMHTTP/1.8.225 UPNP/1.0 DLNADOC/1.50
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - HTTP User-Agent: Mediabolic-IMHTTP/1.8.225 UPNP/1.0 DLNADOC/1.50
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - Recognized media renderer: TX-NR807
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestHandlerV2 - HTTP: upnp/control/content_directory / 0-0
06:02:17.672 [nioEventLoopGroup-3-2] TRACE net.pms.dlna.DLNAResource - discover 30 refresh forced: true
06:02:17.673 [nioEventLoopGroup-3-2] TRACE net.pms.dlna.DLNAResource - End of analysis for C:\Users\xxx\Desktop\UMS Sample sounds
06:02:17.673 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestV2 - Sent to socket: Content-Type: text/xml; charset="utf-8"
06:02:17.673 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestV2 - Sent to socket: Server: Windows_7-amd64-6.1, UPnP/1.0, UMS/5.1.5
06:02:17.673 [nioEventLoopGroup-3-2] TRACE net.pms.network.RequestV2 - Sent to socket: Content-Length: 598
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Opened request handler on socket /10.72.64.23:4554
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Request: HTTP/1.1 : POST : upnp/control/content_directory
06:02:17.681 [nioEventLoopGroup-3-3] DEBUG n.p.c.RendererConfiguration - Matched media renderer "TX-NR807" based on address /10.72.64.23
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Connection: close
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Content-Type: text/xml; charset=utf-8
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Content-Length: 694
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: Host: 10.72.64.11:5001
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Received on socket: User-Agent: Mediabolic-IMHTTP/1.8.225 UPNP/1.0 DLNADOC/1.50
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - HTTP User-Agent: Mediabolic-IMHTTP/1.8.225 UPNP/1.0 DLNADOC/1.50
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - Recognized media renderer: TX-NR807
06:02:17.681 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestHandlerV2 - HTTP: upnp/control/content_directory / 0-0
06:02:17.682 [nioEventLoopGroup-3-3] TRACE net.pms.dlna.DLNAResource - discover 30 refresh forced: true
06:02:17.682 [nioEventLoopGroup-3-3] TRACE net.pms.dlna.DLNAResource - End of analysis for C:\Users\xxx\Desktop\UMS Sample sounds
06:02:17.683 [nioEventLoopGroup-3-3] TRACE net.pms.dlna.DLNAResource - Network debugger: "Media-Convert_test2_AAC-LC_v2_Stereo_VCR_96kbps_32000Hz.aac" http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01 size=5384320 http://10.72.64.11:5001/get/71/Media-Convert_test2_AAC-LC_v2_Stereo_VCR_96kbps_32000Hz.aac
06:02:17.684 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestV2 - Sent to socket: Content-Type: text/xml; charset="utf-8"
06:02:17.684 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestV2 - Sent to socket: Server: Windows_7-amd64-6.1, UPnP/1.0, UMS/5.1.5
06:02:17.684 [nioEventLoopGroup-3-3] TRACE net.pms.network.RequestV2 - Sent to socket: Content-Length: 1150

```

I've researched the issue to the best of my abilities, and I think I've found the reason for the bug (although I haven't made a fix and can't be sure). It seems like the problem is due to the fact that `<TotalMatches>` returned is wrong if some of the files are hidden for the renderer (TotalMatches returns the actual number of files, not the number being presented to the renderer). Since my renderer can play audio only, I've set **Video = false, Image = false, Audio = true** in the renderer configuration. In my test case, the folder in question contains a number of .mp4 files that probably is classified as video files (although they are strictly audio files in a MP4 container in this case), and those are then filtered out from the reply. That leads to confusion on part of the renderer endlessly querying for the remaining items and getting the same lacking answer.

I've done a WireShark trace to figure this out, and the pattern is like this (the actual number of files in the folder is 39, where 12 are .aac files, 16 are .m4a files and 11 are .mp4 files, the renderer lists 21 items per page):

* In the 1. request the renderer asks for StartingIndex=0, RequestedCount=21. UMS answers with NumberReturned=14, TotalMatches=36.
* In the 2. request the renderer asks for StartingIndex=13, RequestedCount=7. UMS answers with NumberReturned=2, TotalMatches=38.
* In the 3. request the renderer asks for StartingIndex=13, RequestedCount=6. UMS answers with NumberReturned=2, TotalMatches=39. The two items returned are the same as in the previous reply.
* In the 4. request the renderer asks for StartingIndex=13, RequestedCount=5. UMS answers with NumberReturned=1, TotalMatches=39. The item returned is the same as the first item it the previous two packets.
* In the 5. request the renderer asks for StartingIndex=14, RequestedCount=4. UMS answers with NumberReturned=0, TotalMatches=39 (nothing is returned).
* In the 6. request the renderer asks for StartingIndex=13, RequestedCount=5. UMS answers with NumberReturned=1, TotalMatches=39. The same item as i in reply 4.
* In the 7. request the renderer asks for StartingIndex=14, RequestedCount=4. UMS answers with NumberReturned=0, TotalMatches=39 (nothing is returned).
* In the 8. request the renderer asks for StartingIndex=13, RequestedCount=5. UMS answers with NumberReturned=1, TotalMatches=39. The same item as i in reply 4.
* ...and on we go into eternity where every even query/reply is identical to exchange 4, and every odd query/reply is identical to exchange 5. 

While the logic for the renderer probably could be written a bit better avoiding this loop, I can certainly understand the confusion. It simply tries to fill up it's first page of 21 items since TotalMatches >= 21. When it doesn't get what it needs, it seems to decrease RequestedCount by 1 until the reply is 0, where it actually increases RequestedCount by 1. The causing issue seems to be that TotalMatches is wrong. There are two errors with TotalMatches:

1. It doesn't take into account the filtering it's doing before replying
2. In the first two replies, the number is for some strange reason lower than the actual number of files.

I have more data on this, a full WireShark trace at about 3 Mb and about 6000 lines of partial trace log. I didn't manage to get the full log since Eclipse would crash with an out of memory error when I tried to copy the whole log, but it's simply an endelss repeat of what's shown above. I can upload or send the files upon request, but I think I've captured the essentials here.

The issue should be fairly easy to replicate - one would need a renderer which requests the entries on a per-page basis (if it simply fetches all in one go, I guess it will simply accept what it gets even though TotalMatches is off). Then create a folder of mixed audio and video files (for example), and configure filtering by only enabling audio or video in the renderer configuration.

**Comment by valib** [comment]
@Nadahar I confirm that bug. Partially fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/c2e95e28a2cb7224a3799187170b5c940b701da8 The recognition of MP4 audio files is another issue.

**Comment by Nadahar** [comment]
I don't know if recognition of MP4 audio files is really an issue - aren't they usually stored as .aac or .m4a files in the real world? The reason I have them is that I downloaded a set of test sample files.

**Comment by Nadahar** [comment]
@valib The issue if fixed at my renderer with your modifications. I haven't done a WireShark trace and checked what's going on, but my renderer lists the files as expected.

**Comment by valib** [comment]
@Nadahar you know to use MP4 container instead of m4a is the Apple feature :) Nobody else use it. You can rename the MP4 audio files to m4a and it will work.

**Comment by Sami32** [comment]
@valib Could this issue be closed ?
