### ISSUE TITLE
Disable transcoding

### ISSUE THREAD

**Issue by garygreen** [UniversalMediaServer/UniversalMediaServer#597]
Just getting to grips with the media server, so my understanding maybe lacking. Does it always have to transcode or can you disable it? Basically I don't want files transcoded that can be natively played on TV. It should just instead 'push' to tv and that is all

**Comment by Nadahar** [comment]
What formats are transcoded or streamed is decided by your renderer configuration. If you select the status tab in UMS you hopefully see your renderer (your TV). If you click it, you get some additional information about it. On the very top there's a ```<filename>.conf```. If you hold your mouse over this, you will see the full path to the configuration file, unless your TV is "unknown renderer" as simply running a default configuration. This file can be a bit cryptic to understand, so look at the ```DefaultRenderer.conf``` in the same folder for an explanation of the different parameters.

**Comment by Iridias** [comment]
Keep in mind, that UMS may transcode files even if they're natively supported by your renderer, if those files contain subtitles. And even if you have configured UMS to not transcode files with those extensions. See: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/565
