### ISSUE TITLE
PS4 FF/RW

### ISSUE THREAD

**Issue by vampiricwulf** [UniversalMediaServer/UniversalMediaServer#602]
I tried playing an mkv with subtitles and using ffmpeg for transcoding. FF/RW were denied (but the video played perfectly).
I'm curious as to why since when I stream to a samsung blu-ray player I can.
Used Version 5.2.0.

**Comment by valib** [comment]
The answer is here http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=3519&start=50 where @SubJunk made a remark.
