### ISSUE TITLE
How do you send/push to play a video on renderer

### ISSUE THREAD

**Issue by garygreen** [UniversalMediaServer/UniversalMediaServer#609]
I would like to (ideally) right click on a video on my computer and click a 'send to tv' or 'cast' button -- or alternatively is there an exe I can call with some command line parameters that will send the signal to the TV and start playing the video?

**Comment by Nadahar** [comment]
@garygreen That, or something similar (I'm not sure you're able to do if from explorer, but that would be up to the software) is possible, but not via UMS as far as I know. UMS is a media server, with some basic control point functionality if you click the renderer, but that would require a more advanced control point software.

In uPnP/DLNA you have three "classes" of devices: Renderer (a device playing media), Control Point (a device controlling renderers) and Media Server (a device serving media). You would need a control point software on your computer that controls your renderer to achieve that. Many of the software renderers also have more or less control point functionality, so you'll just have to test them out and see if any of them will do what you want. 

Here is [a list of software control points and renderers] (https://en.wikipedia.org/wiki/List_of_UPnP_AV_media_servers_and_clients#UPnP_control_points_and_player_software).

**Comment by ExSport** [comment]
On Android I know about e.g. MediaHouse which supports control point or you can easily use web interface implemented directly in UMS. Check log messages on which port it is initialized after UMS start.

**Comment by Nadahar** [comment]
UMS web interface is port 9001 as standard (http://UMS_Computer:9001). I've also managed to do it with several Android apps, but I'm not sure about software that does it from Windows. I didn't know about the "bump" functionality in UMS' web interface, but I worked on my renderer when I tried it. The playlist didn't seem to work though, but I guess that's only relevant for music.

**Comment by skeptical** [comment]
* Push from gui:
![gui2](https://cloud.githubusercontent.com/assets/1594203/8763775/fde3b16e-2d7b-11e5-80e0-dbb3dd697827.jpg)

* Bump from web interface:
![bump](https://cloud.githubusercontent.com/assets/1594203/8763760/49616ca4-2d7b-11e5-86c7-e2346f209a83.png)

**Comment by valib** [comment]
@Nadahar yes as @skeptical wrote the "bump" functionality is there in the UMS but it is not properly documented.  I think that it's time to remove help from UMS and make only a reference to the Wiki which should be updated like @skeptical perfectly made here. Not only for that  topic but generally. Maybe @DeFlanko or @Optimusprimeums can help us?

**Comment by garygreen** [comment]
@skeptical thanks for the instructions. I tried that with the Java and the GUI freezes without explanation (and tv does not play video). However the bump through the web interface works..... yipee!!

**Comment by skeptical** [comment]
@garygreen Gui controls are working for me on Win7 and linux, possibly there's a secondary issue with your setup. If you post a set of TRACE logs in the [GitHub attachments thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656) showing an attempted gui push maybe we'll see something.

**Comment by garygreen** [comment]
Seems to be working fine today I must have just done something wrong yesterday. It would be cool if this bump feature could be documented in the wiki (not too obvious how to do this in the GUI).

**Comment by Nadahar** [comment]
@skeptical I think there are some issues with the GUI controls, they are a bit hit and miss for me. Often they will do nothing, but sometimes they will respond. If I try to adjust the volume, the volume keeps moving all around the place for a while afterwards. The volume on the renderer is not adjusted, but I'm not sure if it supports that.

**Comment by Sami32** [comment]
@garygreen Since it was already solved, could this issue be closed ?
@Nadahar I don't know if the wiki or help was updated since then as i was not able to found it...but i confess that i have difficulties to find something in this wiki 8-/
