### ISSUE TITLE
Xbox One issue: when playing .mkv files with soft subs, I am not able to fast forward/rewind

### ISSUE THREAD

**Issue by apav** [UniversalMediaServer/UniversalMediaServer#610]
Before the latest version I was running a version from last year (sorry, I forgot the specific number) without any issues. After I updated to the latest, I lost the ability to fast forward/rewind on videos with soft subs. In previous versions when I streamed a .mkv video with soft subs to my Xbox One I was always able to fast forward and rewind in 2x, 4x, 8x, 16x, 32x, 64x, and 128x. Now the option on my screen is greyed out and pressing the buttons on my remote do nothing. The only way I have found to renable fast forwarding/rewinding for these videos is to disable subs entirely in my transcoding options menu, which isn't a solution because I need both. Please note that these only affect videos with soft subs as far as I know, any other video I tested is fine. Also, I played the same videos on my Sony smart TV through UMS and I was able to fast forward and rewind with subs working, so I know this is a Xbox (One?) only issue as well. 

For the meantime, it looks like I'm going to work my way down uninstalling UMS and installing each later version in chronological order until I finally find a version where it's working again.

**Comment by apav** [comment]
Hmm strange, I went down a version all the way down to 4.0 and tested this issue, and the issue persisted throughout all versions. It definitely was working when I was on whichever version I was using before this one, not sure why it didn't fix it by rolling back. The only plausible explanation I can think of was that I tweaked the subtitle settings in the previous version and that got erased when I did a clean install, but it still works as intended on my Sony TV and something like this should work right from the start without any extra tweaking anyway. So that can't be it either.

**Comment by Sami32** [comment]
@apav Did a clean install solved this issue ?
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Audio-and-Subtitles

If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556
