### ISSUE TITLE
MIME types stated in the renderer config file are not used with the web bump feature

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#619]
MIME types stated in the renderer config file are not used with the web bump feature.

This result in a serious error on my philips TV. Power off/on is needed because the TV just totally hangs.
For most of files the default MIME type is compatible for this renderer, but not for all media files.

For example my Philips TV needs the video/x-msvideo MIME type as stated in the Philips-PFL config file for DivX files.
The file plays fine when started from the TV.
However when started trough the web interface or a UPnP control point the default MIME type is used,
instead of the MIME type given in the renderer config file.

I have made two trace debug logs posted on forum,
one where I started the DivX file on the TV, and one started trough the web interface bump feature:

Video started through tv: (video/x-msvideo is used as stated in Philips-PFL.conf)
Sent to socket: Content-Type: video/x-msvideo
The video plays fine.

Video started through the web interface bump feature: (an UMS default MIME type video/mpeg is sent)
Sent to socket: Content-Type: video/mpeg
Big failure: Power off/on is needed.

There also java.io.IOExceptions mentioned in the bebug logs wich I guess are not related to this issue.

Debug logs:
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=17456#p17456

**Comment by Nadahar** [comment]
I've also noticed that some files that are playable from the renderer is not playable when using a (Android) control point, and this i likely to be the same issue.

**Comment by skeptical** [comment]
@ler0y see if 732af0b does the trick :).

**Comment by ler0y** [comment]
@skeptical You have your magical hat opened again :).
Your trick works great. Thanks for resolving this issue.

**Comment by ler0y** [comment]
This issue can be closed :)
