### ISSUE TITLE
DSF/DFF audio format MediaParserV2 issue

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#623]
DFF and DSF formats are not supported when the  MediaParserV2 is used (MediaInfo = true) in the renderer config file.
MediaInfo can't parse these files.

However when using the old parser, instead of using the "Supported lines" with:
MediaInfo = false
TranscodeExtensions = DFF,DSF
In the renderer config file, these files can be transcoded by The FFmpeg Audio engine.

Extension support for .dff and .dsf should be added to the net.pms.formats

A fix, like a fallback on the old parser, for the formats that MediaInfo can't read would be great I guess.

So that:
"TranscodeExtensions = "or "StreamExtensions =  " can be used combined with "MediaInfo = true".

Test dff/dsf media files:
https://www.oppodigital.com/hra/dsd-by-davidelias.aspx

**Comment by Nadahar** [comment]
@ler0y Thanks for sample files - I'll add them to my audio format branch at least. I didn't find any .DFF files among the samples, but i was kind of messy. Do you have a link for one?

**Comment by ler0y** [comment]
@Nadahar look at: http://www.2l.no/hires/index.html

**Comment by Nadahar** [comment]
There's a slight problem: MediaInfo can't parse those files, so UMS can't get any codec information about them. I'm not sure how to solve that, any ideas?

**Comment by ler0y** [comment]
I have tried ffprobe and it seems that this program can parse those files.
Maybe it's an alternative that can be used for the rare files that are not supported by MediaInfo.
ffprobe is bundled with FFmpeg.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987/commits/b49d04af578357d3204b819c9efba69de1ee2bbe

**Comment by Nadahar** [comment]
@ler0y Isn't this working in the latest version? We've simply made sure these files aren't parsed with MediaInfo.

**Comment by ler0y** [comment]
@Nadahar Yes this is working in the latest version. the .dff and .dsf files are now recognized and transcoded by default. cool!

I can confirm also that MediaInfo still can not parse these files.

1 thing.. I saw that the tags "dff" and "dsf" are been added to the list of tags in the DefaultRenderer.conf, but these tags can not be used with the supported lines.
All the mentioned test files are parsed with both, format and audio codec as "dsd".
The tag "dsd" however is not mentioned in this tags list.

Maybe dff and dsf should be mentioned separate in this tags list for supported file extensions only?

**Comment by Nadahar** [comment]
@ler0y This sound like something for @Sami32 😉 Are DFF and DSF actually separate formats?

**Comment by Nadahar** [comment]
Hmm, it seems there's an actual difference 😭 

https://www.computeraudiophile.com/forums/topic/19074-dsf-or-dff-what-is-the-difference/

We'd need to different ```Format```s for them then.

**Comment by Sami32** [comment]
@nadahar I don't see the point nor the need.

FFmpeg only have the DSF demuxer, so no need to go further.
DSF is the "best", and JAudioTagger only support DSF, as expected.

**Note**: Some renderers have `audio/dsd` MIME type, non standard though, more the 2 other ones.

**Comment by Nadahar** [comment]
@Sami32 If we can't parse and can't transcode DFF, why should we list it as media? It should be excluded then. Are you sure that FFmpeg's DSF demuxer can't handle DFF as well? As far as I understand, the data is the same - the difference is that DSF can store metadata as well. Maybe DFF is "the audio data" in the DSF format?

**Comment by Nadahar** [comment]
I only have 2 dff sample files. I have no way to "verify" that they are really DFF, but I have no reason to believe they aren't.

FFmpeg parse them just fine:
```powershell
Input #0, iff, from 'R:\data\Sourcecode\Java\Media Sample Audio\sacd\2L50SACD_tr1_DSD_stereo.dff':
  Metadata:
    creating_machine: DSDHandler - Version '6, 0, 10, 402'
    operator_name   : Morten
    general_remark  : Created with straight track mapping
    channel0_comment: Selected SDM:     D
  Duration: 00:03:03.01, bitrate: 5644 kb/s
    Stream #0:0: Audio: dsd_msbf (DSD  / 0x20445344), 352800 Hz, stereo, fltp, 5644 kb/s
    Metadata:
      absolute_start_time: 00h:29m:16s:317995
      comment_time    : 2008-03-31 19:31
```
```powershell
Input #0, iff, from 'R:\data\Sourcecode\Java\Media Sample Audio\sacd\2L-056_stereo-DSD128_04.dff':
  Metadata:
    comment         : Weiss Engineering Saracon 01.61-30 (Jul  5 2010, 15:53:48)
  Duration: 00:03:24.41, bitrate: 11289 kb/s
    Stream #0:0: Audio: dsd_msbf (DSD  / 0x20445344), 705600 Hz, stereo, fltp, 11289 kb/s
    Metadata:
      absolute_start_time: 00h:00m:00s:0
      comment_time    : 2013-01-09 22:01
```

Here's a couple of DSF files for comparison:
```powershell
Input #0, dsf, from 'R:\data\Sourcecode\Java\Media Sample Audio\sacd\01 - David Elias - The Window - Vision of Her (DSD64).dsf':
  Metadata:
    title           : Vision of Her
    artist          : David Elias
    genre           : Folk
    encoder         : KORG AudioGate ver.1.5.0
    date            : 2007-11-20 22:52
  Duration: 00:05:07.11, bitrate: 5644 kb/s
    Stream #0:0: Audio: dsd_lsbf_planar, 352800 Hz, stereo, fltp, 5644 kb/s
```
```powershell
Input #0, dsf, from 'R:\data\Sourcecode\Java\Media Sample Audio\sacd\2L-106_stereo_DSD-2822k_MAGNIFICAT_04.dsf':
  Metadata:
    encoded_by      : Merging Technologies Album Publishing
    comment         : Generated by Merging Technologies Album Publishing
                    : Label Code: 2L
    title           : Arnesen: MAGNIFICAT 4. Et misericordia
    artist          : Nidarosdomens jentekor & TrondheimSolistene
    album_artist    : Nidarosdomens jentekor & TrondheimSolistene
    composer        : Kim Andre Arnesen
    album           : MAGNIFICAT
    track           : 4/10
    disc            : 1
    TSRC            : NOMPP1407040
                    : 7041888519621
    publisher       : 2L
    genre           : Classical
    date            : 2014
  Duration: 00:04:55.36, bitrate: 5644 kb/s
    Stream #0:0: Audio: dsd_lsbf_planar, 352800 Hz, stereo, fltp, 5644 kb/s
```

**Comment by Nadahar** [comment]
Both DSF and DFF also transcode just fine with FFmpeg.

**Comment by Sami32** [comment]
@Nadahar Thanks for having tested it :+1: . I don't have such samples, so i cannot test FFmpeg, and it was necessary, imo, before make any more changes.

**Comment by polygirl** [comment]
@ler0y This was implemented, thanks for suggesting.
