### ISSUE TITLE
Yamaha renderers GUI "Select renderers" bug

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#633]
The Yamaha renderers are not listed in the GUI "Select renderers" option.
With default UMS settings (all renderers enabled) the Yamaha renderers are loaded and used as normal:

DEBUG 19:17:27.736 [main] Added file watch at renderers: renderers\\Yamaha-RN500.conf
DEBUG 19:17:27.738 [main] Added file watch at renderers: renderers\\Yamaha-RXA1010.conf
DEBUG 19:17:27.739 [main] Added file watch at renderers: renderers\\Yamaha-RXV3900.conf
DEBUG 19:17:27.740 [main] Added file watch at renderers: renderers\\Yamaha-RXV671.conf

But if for example the Xbox360 renderer is disabled in the GUI, than the Xbox360 renderer is ignored,
but also the Yamaha renderers be ignored:

DEBUG 19:35:40.703 [main] Added file watch at renderers: renderers\\Microsoft-Xbox360.conf
DEBUG 19:35:40.703 [main] Ignored Xbox 360 configuration
DEBUG 19:35:40.871 [main] Added file watch at renderers: renderers\\Yamaha-RN500.conf
DEBUG 19:35:40.871 [main] Ignored Yamaha R-N500 configuration
DEBUG 19:35:40.872 [main] Added file watch at renderers: renderers\\Yamaha-RXA1010.conf
DEBUG 19:35:40.872 [main] Ignored Yamaha RX-A1010 configuration
DEBUG 19:35:40.878 [main] Added file watch at renderers: renderers\\Yamaha-RXV3900.conf
DEBUG 19:35:40.879 [main] Ignored Yamaha RX-V3900 configuration
DEBUG 19:35:40.880 [main] Added file watch at renderers: renderers\\Yamaha-RXV671.conf
DEBUG 19:35:40.880 [main] Ignored Yamaha RX-V671 configuration

After some testing, I found some workaround to this issue which hopefully can give you guys more insight about this.

It seems that UMS does not like the "Y" character in the naming Yamaha, as renderer name.
If in the Yamaha config files the RendererName is changed from "Yamaha" to "Jamaha" like:

Yamaha-RN500.conf:
#RendererName = Yamaha R-N500
RendererName = Jamaha R-N500

Yamaha-RXA1010.conf:
#RendererName = Yamaha RX-A1010
RendererName = Jamaha RX-A1010

Yamaha-RXV671.conf:
#RendererName = Yamaha RX-V671
RendererName = Jamaha RX-V671

Yamaha-RXV3900.conf:
#RendererName = Yamaha RX-V3900
RendererName = Jamaha RX-V3900

Then all Yamaha renderers are listed in the "Jamaha" folder in the GUI "Select renderers" option.

I have also tried the character Z like "Zamaha" instead of "Yamaha" but also that fails.
strange behavior...

**Comment by ler0y** [comment]
Somewhat related to this..
The UMS.conf setting "ignored_renderers = " is no longer used in the codebase.
I guess this can be safely removed, because the not yet documented setting "selected_renderers = " is now used?

**Comment by valib** [comment]
Thanks for the report. The bug was there from the beginning when I introduced renderers selection :-(
