### ISSUE TITLE
Web interface [No encoding] playlist issue

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#634]
If [No encoding] is started from the transcode folder in the Web interface for the first time, 
the correct file will be played.
If you then start a new [No encoding] file from the transcode folder of another media file,
the first file is played again, instead of the new one.

The option "Clear playlist" repairs this.
After the playlist is cleared, the correct file is played.
But that's not the nicest way, right?

**Comment by skeptical** [comment]
@ler0y I think 2d0ca26 fixes this, though it may introduce other side-effects.  The bump playlist logic is a bit weird, needs some more work to get it to behave as one would expect in a 'normal' playlist.

**Comment by ler0y** [comment]
Strangely I can't reproduce the mentioned issue with the latest oficial UMS 5.2.1.
I also tested the build from UMS trunk before 2d0ca26.

As your fix "may introduce other side-effects" as you mentioned, then maybe then it is best to keep the code as was?

I am sure that I had this issue, so I keep testing and report only when I am sure that I can reproduce it again..

Thanks for your time.

**Comment by skeptical** [comment]
@ler0y I reproduced it (otherwise I wouldn't have fixed anything :-).  It happens whenever another (different) item with the identical title is already in the bump playlist. And side effects, if any, would still be preferable to leaving it as-is I think.

**Comment by ler0y** [comment]
@skeptical I am reassured that you also reproduced it, I thought I was going crazy here. :)

**Comment by skeptical** [comment]
@ler0y the bug was in *web/bump/bump.js*, not *ums.jar*. Were you reinstalling everything between version tests or just swapping jars?

**Comment by ler0y** [comment]
@skeptical Thanks for this note, I had indeed just swapping jars.
But also tried a clean install of 5.2.1..
With the new knowledge, i'll test some more :)

**Comment by ler0y** [comment]
@skeptical Today I could reproduce the bug again,
and I can confirm that your fix in web/bump/bump.js works :)
Thanks
