### ISSUE TITLE
Idea: A better way to handle UMS language selection

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#641]
When I first installed UMS, it started up in Norwegian, which gave me a pretty bad user experience because the Norwegian translated was so outdated and incomplete that the GUI was hardly comprehensible. 

I think this is a bad practice for two reasons: 
- If the translation is bad and/or incomplete, the whole application seems like one big mess and users are likely to be thrown off just by this.
- Personally I prefer to use english language on applications in many cases, because the norwegian language simply lacks good translations og a lot of computer related words, and the "constructed" norwegian terms are often both confusing and hard to read. That doesn't mean that translations are a bad idea, but I atleast prefer to have a choice. 

I've since been thinking of ways to improve this. One thing would be to simply present a language choice in the configuration wizard, but that's not really enough since you don't really know what you're choosing at that time if the translation is outdated or incomplete, not to mention if it's machine translated.

What I've come up with so far, is that on every build statistics about the translations should be gathered, that could then be used to make a more informed choice both for the automatic default and for the user. It's very hard to judge bad translations, but at least we couldn judge whether or not the translation is complete, or by what degree it is. @taconaut's input in adf5075f3b708fd78e3048caeee7d61d207eadf8 brought this idea further up my agenda again. I had been thinking of making some script/java that would generate this completion percentage upon build for the different languages, and then store this is e.g a `.properties` file that the configuration wizard could read, but as @taconaut shows this is already being done. My Maven knowledge is lacking, but is there a simple/good way to make this information accessible to UMS at runtime by storing it to a `.properties` file or similar during build?

My idea further was that there should be a link, preferably to universalmediaserver.com (or the forum as a next best option) that explained in detail how to contribute translations. 

When the wizard was running, if the translation for the system locale was complete, it would simply default to that language but give the user the option to choose something else. If it wasn't complete, it should still default to that language if the translation was above a certain threshold, but also link to the "How to submit translations" page. The user should also be told to what extent any given language was translated, and being able to choose the language best suited to him/her from that. If the translation was below the threshold, it should default to english but still give the user the choice and explain why the locale language was not selected - and providing the same link.

I'd like to know before I do anything more with this, if you think it's a good idea, and I'd appreciate any help on the Maven part. I also think it's worth considering converting the language files to UTF-8, from what I've seen it's no big deal to make UMS accept UTF-8 instead of the current "java special lation encoded format". The files would be easier to both read and write.

**Comment by Nadahar** [comment]
Even better, why not move to e.g [crowdin] (https://crowdin.com/page/open-source-project-setup-request). That way it's very easy for people to contribute, I'm already translating e.g Adblock Plus there and I get email reminders when action is needed and the whole process is very fluid. I don't know how much work it would be to get that automated though, but that would probably be doable.

**Comment by taconaut** [comment]
To get the translation percentage for a languages, I'd start with having a look at the [l10n-maven-plugin](https://code.google.com/p/l10n-maven-plugin/) and creating a standalone application using the business logic from the plugin and writing it to a properties file which then could be used by UMS.
I haven't made any collaborative translations myself and can't estimate how much effort it would represent to put in place, but it sounds interesting :)

**Comment by Nadahar** [comment]
@taconaut The logic for calculating the percentages is easy enough, but I was thinking that since the I10n-maven-plugin already does this we could probably utilize this instead of generating it again..?

**Comment by taconaut** [comment]
@Nadahar It just seemed cleaner to me to use the plugin code to do the business and use its results to generate a file than to parse a html file where it wrote those values. Both are possible and maybe there are better solutions around.

**Comment by Nadahar** [comment]
@taconaut I didn't know that the only output was HTML, but in that case I agree. Still, there's a lot I don't know how to do here, assuming that this idea is accepted:

Where do I place this application/script in the source tree? How do I make sure it's run during build but not packaged as a part of UMS. Do I have to concern myself with compiling it, or does Maven handle that? A great tip would be if anyone knew if this kind of functionality has a name in Maven, if I could only find that I'm guessing there would be explanations out there.

**Comment by taconaut** [comment]
@Nadahar  Lets see what the devs say, there's a solution for everything :)

**Comment by SubJunk** [comment]
I'm very keen to adopt more user-friendly ways for people to translate. I had meant to make a web GUI for it but I never found the time. There are some good ideas in here.

**Comment by Nadahar** [comment]
@SubJunk My experience with crowdin is very good. Anyone can sign up and translate, and if there are multiple translations people can vote for the best translation. It will also show translations for other languages, many whom are similar enough for me to be useful (like german, dutch, swedish, danish) and translation of similar phrases in your own language. In addition, the person who inputs the "original"/english can give a _context_ that is shown to any given translation to show usage. The translators can also discuss a given translation on the side. I actually translate there just for fun some times, that's how good it is.

The thing is, you as the [project owner much apply] (https://crowdin.com/page/open-source-project-setup-request) - it's free for open-source projects, but you get access by applying. I think UMS ticks most if not all the boxes they list. On top of that, you have the [Maven crowdin-plugin] (http://mvnrepository.com/artifact/com.googlecode.crowdin-maven/crowdin-plugin/1.4) - so we could probably make the whole process more or less automated.

**Comment by SubJunk** [comment]
@Nadahar cool, I'll have a look, thanks for the info :)

**Comment by SubJunk** [comment]
@Nadahar I created an account and applied to have it recognized as open source just now

**Comment by Nadahar** [comment]
@SubJunk Great, there's some way to go to get it all automated and working, but I think it could be really good once it's in place.

**Comment by SubJunk** [comment]
@Nadahar cool, the project is at https://crowdin.com/project/universalmediaserver/

I assume there's an ability to give you rights to manage it if I have your username?

**Comment by Nadahar** [comment]
I've just translated, never managed there, but I hope they have such possibilities. I've sent you a message on crowdin so you can find my user.

**Comment by SubJunk** [comment]
@Nadahar cool, I made you a manager of the project

@UniversalMediaServer/developers if anyone else wants to be a manager of the Crowdin project let me know

**Comment by Nadahar** [comment]
@SubJunk Yes, I'm in already. Now we just have to figure out how to get all of this propertly set up. I have to sleep now, but I will look at it later.

**Comment by squadjot** [comment]
So i signed up as i want to contribute to better translation. Can i just go ahead, or do i need to be granted a permission?

**Comment by Nadahar** [comment]
@squadjot The integration is not done yet, but the files are uploaded into [Crowdin] (https://crowdin.com/project/universalmediaserver) so if you want you can just log in there (sign up or log in with your github account) and correct those that's bad and translate those that's not translated.

Since the integration is not done yet, I can't promise that the translation will be in for the next release, but we will get there later. Everyone has permission to translate, and then the users can vote if there are conflicting translations for the same text. As long as only one translation to that language exists, that will be used in any case (as long as we approve it). I'm norwegian so I understand enough danish to know if you're actually translating :wink:

**Comment by squadjot** [comment]
Oh ok, the reson i ask is, i did some translations the other day..but i don't see them being added to suggestions. That also means i can't see which translations i already translated

**Comment by squadjot** [comment]
Aw goddamn it, it was because i didnt verify my email with crowdin yet. Sorry for the inconvinience. 
Great initiative by the way..this translation thing.

**Comment by taconaut** [comment]
This is pretty cool, I'm curious to see how the integration into UMS will work.

**Comment by Nadahar** [comment]
@taconaut I don't expect that to be to difficult, there already exists a Maven plugin. But, #616 must be merged first since it's dependent on the language code/locale changes that's done there.

**Comment by Sami32** [comment]
@Nadahar That was a great move :+1: 
Can it be closed now or you want add something else ?

**Comment by Nadahar** [comment]
@Sami32 Thanks for closing, I had simply forgotten this issue existed :+1:
