### ISSUE TITLE
Comiling snapshot code - test failured

### ISSUE THREAD

**Issue by ykowalewski** [UniversalMediaServer/UniversalMediaServer#648]
Hi,
when I try to compile UMS from source code I get error during that test:
	@Test
	public void testGetFileNameWithRewriting() throws Exception {
		assertThat(FileUtil.getFileNameWithRewriting("Universal.Media.Server.S01E01E02.720p.mkv", null)).isEqualTo("Universal Media Server - 101-102");
	}

When I commented out this assert, compilation was complited with success. 

Compilation envirnoment:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: pl_PL, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-25-generic", arch: "amd64", family: "unix"

Regards,
Jarek

**Comment by Nadahar** [comment]
@ykowalewski I've seen that test fail a couple of times to, but not been able to reproduce it when I debugged it. Can you add the line: 
```java
system.out.println(FileUtil.getFileNameWithRewriting("Universal.Media.Server.S01E01E02.720p.mkv", null));
```
...close to the commented out line, and see what value is actually printed?

**Comment by ykowalewski** [comment]
For me its look like another type of error then test failure. Compiler report that "Null" value instead of a File is not allowed. 

testGetFileNameWithRewriting(net.pms.util.FileUtilTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NullPointerException: null
	at net.pms.util.FileUtil.getFileNameWithRewriting(FileUtil.java:225)
	at net.pms.util.FileUtilTest.testGetFileNameWithRewriting(FileUtilTest.java:82)

**Comment by ykowalewski** [comment]
As I tested I get info
Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.121 sec <<< FAILURE! - in net.pms.util.FileUtilTest
testGetFileNameWithRewriting(net.pms.util.FileUtilTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException: null
	at net.pms.util.FileUtil.getFileNameWithRewriting(FileUtil.java:225)
	at net.pms.util.FileUtilTest.testGetFileNameWithRewriting(FileUtilTest.java:82)

So the fragment causes error
if (PMS.getConfiguration().isUseInfoFromIMDB() && formattedName.equals(formattedNameTemp)) {
				isEpisodeToLookup = true;
			}

System.out.println(PMS..getConfiguration()) gets
cannot find symbol
  symbol:   variable PMS
  location: class net.pms.util.FileUtil

**Comment by Nadahar** [comment]
@ykowalewski I hope:
> System.out.println(PMS..getConfiguration())
was only a typo?
It should be ```System.out.println(PMS.getConfiguration())```

**Comment by ykowalewski** [comment]
only a typo...

**Comment by Nadahar** [comment]
@ykowalewski The problem is that I can't replicate the error. Could you post your ```UMS.conf```? Do you buy the way have multiple ```UMS.conf``` files on your computer, and if so: where?

**Comment by ykowalewski** [comment]
I don't really know if I have specific configuration. I have one UMS.conf in my home folder .config/UMS/UMS.conf I should set another path to config while I try to compile code? 

cred.path = /home/yaro/.config/UMS/UMS.cred
minimized = true
maximum_bitrate = 90
mpeg2_main_settings = Automatic (Wireless)
x264_constant_rate_factor = Automatic (Wireless)
hide_advanced_options = false
run_wizard = false
uuid = f5f115f0-b01d-4293-8a56-1f99fbf170d7
log_level = ALL
folders = /home/yaro/Wideo,/media/yaro/Dane
folders_monitored =
hostname = 192.168.0.17
append_profile_name = true
vlc_use_experimental_codecs = true
vlc_audio_sync_enabled = true
engines = mencoder,ffmpegvideo,tsmuxer,vlctranscoder,ffmpegaudio,tsmuxeraudio,vlcwebvideo,mencoderwebvideo,ffmpegwebvideo,vlcvideo,vlcaudio,rawthumbs
mencoder_skip_loop_filter = true
mencoder_forcefps = true
audio_resample = false
renderer_default = Kodi
disable_subtitles = false
gpu_acceleration = true
audio_embed_dts_in_pcm = false
encoded_audio_passthrough = false
audio_use_pcm = false
audio_channels = 2
enable_archive_browsing = true
use_mplayer_for_video_thumbs = true
dvd_isos_thumbnails = true
audio_thumbnails_method = 1
automatic_maximum_bitrate = true

**Comment by ykowalewski** [comment]
Today I checked out master repo from git and then run 3 commands and have the same problem 
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
mvn -P linux package

**Comment by Nadahar** [comment]
@ykowalewski I think I found the error. 09830d15ea52d25a671fbed9228a8cab928161e2 should fix it, so if you check out master again now it should work.

Thank you for your assistance.

**Comment by Nadahar** [comment]
@ykowalewski I'd appreciate if you'd report back if it solved it or not.

**Comment by ykowalewski** [comment]
BUILD SUCCESS with last repo revision. Good job:)

**Comment by Nadahar** [comment]
Thank you for reporting back :+1:
