### ISSUE TITLE
Desktop API is not supported on the current platform

### ISSUE THREAD

**Issue by ykowalewski** [UniversalMediaServer/UniversalMediaServer#649]
Action to reproduce:
- run serwer
- on system try unity right click
- choose "interfejs in browser" (run in browser?). I translated it from polish.

INFO  00:02:13.811 [main] Build: 4660ba3df (2015-08-13)
INFO  00:02:13.812 [main] Java: Java HotSpot(TM) 64-Bit Server VM 1.7.0_80 64-bit by Oracle Corporation
INFO  00:02:13.812 [main] OS: Linux 64-bit 3.19.0-25-generic
INFO  00:02:13.812 [main] Encoding: UTF-8
INFO  00:02:13.836 [main] Memory: 683 MB
INFO  00:02:13.837 [main] Language: pl

INFO  00:03:04.920 [AWT-EventQueue-0] Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Desktop API is not supported on the current platform
INFO  00:03:04.922 [AWT-EventQueue-0] 	at java.awt.Desktop.getDesktop(Desktop.java:144)
INFO  00:03:04.923 [AWT-EventQueue-0] 	at net.pms.io.BasicSystemUtils.browseURI(BasicSystemUtils.java:125)
INFO  00:03:04.923 [AWT-EventQueue-0] 	at net.pms.io.BasicSystemUtils$3.actionPerformed(BasicSystemUtils.java:166)
INFO  00:03:04.924 [AWT-EventQueue-0] 	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
INFO  00:03:04.925 [AWT-EventQueue-0] 	at java.awt.MenuItem.processEvent(MenuItem.java:628)
INFO  00:03:04.925 [AWT-EventQueue-0] 	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
INFO  00:03:04.926 [AWT-EventQueue-0] 	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
INFO  00:03:04.926 [AWT-EventQueue-0] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:750)
INFO  00:03:04.927 [AWT-EventQueue-0] 	at java.awt.EventQueue.access$300(EventQueue.java:103)
INFO  00:03:04.927 [AWT-EventQueue-0] 	at java.awt.EventQueue$3.run(EventQueue.java:706)
INFO  00:03:04.928 [AWT-EventQueue-0] 	at java.awt.EventQueue$3.run(EventQueue.java:704)
INFO  00:03:04.928 [AWT-EventQueue-0] 	at java.security.AccessController.doPrivileged(Native Method)
INFO  00:03:04.929 [AWT-EventQueue-0] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
INFO  00:03:04.929 [AWT-EventQueue-0] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
INFO  00:03:04.930 [AWT-EventQueue-0] 	at java.awt.EventQueue$4.run(EventQueue.java:720)
INFO  00:03:04.931 [AWT-EventQueue-0] 	at java.awt.EventQueue$4.run(EventQueue.java:718)
INFO  00:03:04.931 [AWT-EventQueue-0] 	at java.security.AccessController.doPrivileged(Native Method)
INFO  00:03:04.932 [AWT-EventQueue-0] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
INFO  00:03:04.932 [AWT-EventQueue-0] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
INFO  00:03:04.933 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
INFO  00:03:04.934 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
INFO  00:03:04.934 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
INFO  00:03:04.935 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
INFO  00:03:04.935 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
INFO  00:03:04.936 [AWT-EventQueue-0] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by Nadahar** [comment]
I don't have access to a linux with desktop/GUI to test on, but [this article] (http://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform) suggests that the solution might be to install ```libgnome2-0```. It seems to be a Java problem rather than an UMS problem, even though UMS could probably handle the error a bit more gracefully.

**Comment by Nadahar** [comment]
I don't know if the polish translation is correct for this one or not, but the English term it's translated from is "Web interface" - google and bing translate suggests that should be "interfejs WWW" in polish. Anyway, it's useful to know that what you're trying to do is to open the web interface.

**Comment by ykowalewski** [comment]
ok. that's right. The problem was solved by installing libgnome2 library. Issue can be closed.
