### ISSUE TITLE
DVDISOTitle  and instance stream is null

### ISSUE THREAD

**Issue by ykowalewski** [UniversalMediaServer/UniversalMediaServer#650]
Action to reproduce:
- run server
- open link webinterface e.g. WEB interface is available at: http://192.168.0.17:9001 (chrome on my local computer)
- navigate to DVD folder (dvd disc saved on harddrive)
- error accures

INFO  00:07:38.991 [pool-9-thread-1] Exception in thread "pool-9-thread-1" java.lang.NullPointerException
INFO  00:07:38.991 [pool-9-thread-1] 	at net.pms.dlna.DVDISOTitle.resolveOnce(DVDISOTitle.java:211)
INFO  00:07:38.992 [pool-9-thread-1] 	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1444)
INFO  00:07:38.992 [pool-9-thread-1] 	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1246)
INFO  00:07:38.993 [pool-9-thread-1] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO  00:07:38.993 [pool-9-thread-1] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO  00:07:38.994 [pool-9-thread-1] 	at java.lang.Thread.run(Thread.java:745)

AND then try to play some position in web browser

ERROR 00:12:02.901 [Hanging External Process Stopper] External input stream instance is null... stopping process
INFO  00:12:02.905 [StartPlaying Event] Started playing Tytuł 1 on your Chrome
INFO  00:12:02.906 [Thread-98] Exception in thread "Thread-98" java.lang.NullPointerException
INFO  00:12:02.919 [Thread-98] 	at net.pms.remote.RemoteUtil$1.run(RemoteUtil.java:105)
INFO  00:12:02.920 [Thread-98] 	at java.lang.Thread.run(Thread.java:745)

INFO  00:02:13.811 [main] Build: 4660ba3df (2015-08-13)
INFO  00:02:13.812 [main] Java: Java HotSpot(TM) 64-Bit Server VM 1.7.0_80 64-bit by Oracle Corporation
INFO  00:02:13.812 [main] OS: Linux 64-bit 3.19.0-25-generic
INFO  00:02:13.812 [main] Encoding: UTF-8
INFO  00:02:13.836 [main] Memory: 683 MB
INFO  00:02:13.837 [main] Language: pl

**Comment by ExSport** [comment]
Seems it is not problem only when played via Web Browser.
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3857&p=17752#p17752

**Comment by ykowalewski** [comment]
For linux version the soluton is installing libasound2-plugins-extra. Debug logged error in lvac_audio.

**Comment by Sami32** [comment]
@SubJunk solved it in 5.3.1 version: http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3857&start=50#p26693
