### ISSUE TITLE
Config option to use flash player by default not working

### ISSUE THREAD

**Issue by wallypg03** [UniversalMediaServer/UniversalMediaServer#651]
All of the PCs at work use Explorer 11 and won't play files from UMS in HTML5 format. They will play if you click the 'Flash' button at the bottom of the player.

There is an option in the UMS config file of 5.2.1 that I assume should force the player to default to play in flash rather than html5 but setting the value to true doesn't seem to change anything.

Would appreciate any help or clarification of what that setting does if it's not what I'm assuming:

# Web flash
#----------------
# Use flash player by default.
# Deafult: false
web_flash=

**Comment by skeptical** [comment]
Fixed in 546560f.

**Comment by wallypg03** [comment]
Really appreciate the fix thank you. The 'use flash player by default' setting in the UMS config file now works.
