### ISSUE TITLE
Samsung UExxJ551x doesn't support subs natively in UMS

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#654]
There should be new conf file for this renderer as this one supports subs with correct options set:
```manufacturer=Samsung Electronics, modelName=UE40J5510, modelNumber=AllShare1.0, modelDescription=Samsung TV DMR```
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3874&p=17844#p17836

**Comment by squadjot** [comment]
Same thing for Samsung JU6400W: http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=3981

**Comment by SubJunk** [comment]
Applied the fixes from the forum in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/91fb8fe155ad6cac61090ed6c808f8cf14c4ca69 and https://github.com/UniversalMediaServer/UniversalMediaServer/commit/5ba19d7d9492c4f934adc40a448e421323eaab9b

Thanks for the work guys!
