### ISSUE TITLE
GUI translation issues

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#656]
The Dutch language and others often need more characters than the English to describe a UMS setting.
Writing a GUI correct translation into Dutch and other languages is because of this  not always possible.
A longer text than the English can cause display problems in the GUI, like not displaying the complete text or overlapping the text with other settings.

To be really 'Universal', all the earthly languages should be supported well. right? :)

Here some GUI misprint examples with UMS 5.2.2:

The next screenshot shows the currently translated languages of the 'Universal Media Server Auto Update' popup window.
As you can see is the 'close' button is completely unreachable in the French language:
![auto update text issue](https://cloud.githubusercontent.com/assets/2998326/9558327/7ef37d1a-4de4-11e5-98fe-f3a4d372dba2.png)
Besides it is odd that I get this update notification..
I have 5.2.2 installed, and the UMS.jar overwritten with the latest from the 'Jenkins' server.
The UMS 5.2.3 has not yet been released yet, so there should not be any new update available. right?

Text not displayed in the Spanish 'Navigation Share Settings' tab:
![spanisch navigation share settings tab](https://cloud.githubusercontent.com/assets/2998326/9558347/b36d6d3a-4de4-11e5-8283-3453c1e2aa02.png)

Text overlap in the Spanish 'Transcoding Settings' tab / Subtitles settings:
![spanisch transcoding settings tab](https://cloud.githubusercontent.com/assets/2998326/9558352/c6576388-4de4-11e5-87e4-f24e7a943d2c.png)

Text overlap in the Norwegian 'Transcoding Settings' tab/ MEncoder:
![noorse navigation share settings tab mencoder](https://cloud.githubusercontent.com/assets/2998326/9558368/feb12214-4de4-11e5-8a23-bbdeb984fb90.png)

**Comment by SubJunk** [comment]
@ler0y yes, you're right. I have sometimes removed strings that are too large. Maybe I'm naive, but I think it is possible in other languages to re-word things to be shorter, as it is in English.

**Comment by ler0y** [comment]
@SubJunk Sure, I always try to shorten the translation where needed.
A keen GUI with less settings text where possible, but fully understandable, is better readable / understandable.

I have already made an updated Dutch language with corrections for the 'Universal Media Server Auto Update' with shortened text that fits.

But I guess and hope that it is possible to change some GUI settings, so that longer text can be used for some problematic short allowed GUI strings.

The most problematic is:
MEncoderVideo.12=Styled subtitles:

Because of the next setting that is not aligned with the rest of the tab:
MEncoderVideo.133=Font scale

**Comment by Nadahar** [comment]
> Maybe I'm naive, but I think it is possible in other languages to re-word things to be shorter, as it is in English.

@SubJunk That's not true. Norwegian is one of those languages that typically have long words, and I think that goes for all "german based" languages at least. The problem is simply that many words have many more characters than their English counterparts, and that addes up. The only way to shorten this is to make "homemade" short versions that make the text difficult to read at best. This i an exp. of such a sent., I hope you all agr. that it's less than ideal.

Try translating some random texts to German or Finnish for that matter in google translate, and you'll see what I mean :wink: It's not how you build the sentence, but the words themselves most of the time.

I think that the GUI needs to be as dynamic as possible, and I don't think that the column based layout used in most GUI tabs is fortunate. Sometimes it's simply impossible to allocate dynamic space, and one simply has to make semi-cryptic short versions, but for a translator translating a text file there's no way to know for which texts this is true. To achieve that, you need context and constraints, which is currently not supplied. [Crowdin] (https://crowdin.com/) would make such context possible, have you had the time to look at it?

**Comment by skeptical** [comment]
@ler0y #657 fixes the core problems (more or less) but still needs further prettifying :).

**Comment by ler0y** [comment]
@skeptical Thanks for looking into this :+1: Sorry for the swing/jgoodies headaches:)
I will test the [ #657] (https://github.com/UniversalMediaServer/UniversalMediaServer/pull/657) soon.
@Nadahar Thanks for improve the stating that the  "german based" languages often have many more characters than their English counterparts.

**Comment by ler0y** [comment]
@skeptical just tested #657 All mentioned GUI text issue examples are fixed with this :)

Some more prettifying would be nice indeed.
Maybe it's possible to use the text alignment code that is used for the with '1' marked settings for the settings marked with '2'.
So the label is located next to the correct setting.
This maybe also removes the horizontal scrollbar now introduced in the Dutch and other languages.

![nederlands](https://cloud.githubusercontent.com/assets/2998326/9696975/6d3dffee-537c-11e5-98e6-fc3db6351b36.png)

**Comment by Sami32** [comment]
@ler0y @SubJunk Did the latest UMS interface and latest Crowdin updates fixed this issue ?

**Comment by Nadahar** [comment]
> Since i don't read german or norvegian i am not a good adviser, but 

@Sami32 Do you *only* learn French in France? :stuck_out_tongue: I'd think that German would be core knowledge in France since Germany is your biggest neighbour, they speak German in Switzerland and parts of Belgium as well. Dutch which is also spoken in Belgium is really just a "variant" of German too. You're more or less surrounded by the German language except in the south.

**Comment by Sami32** [comment]
@Nadahar As you know we was not the best friend with german, so yes my grand-father learned it in concentration camp...
Like japanese, the french are very bad in learning language and don't really search to communicate with foreign countries. It's also one of the worst welcome that you could received as a tourist i think; many touristes complain about that !
But slowly, with the new generation and new political lines for the development of the tourism, as chinese government complained about that, this should change.
So if come to France and you don't speak french, good luck :wink: 

**P.S.** the exeption is Alsace-Loraine region, as it was german for 100 years.
We go only in french part of Belgium and Switzerland ;-)

**Comment by Nadahar** [comment]
@Sami32 We were occupied by the Germans too, so they're not exactly considered heroes here either. But the German language is bigger than just Germany, and Germany is more than the nazi period. You had Napolean, he wasn't that much better. Also, if you look at poeple being "elected" today like Putin, Erdogan and possibly Trump other countries doesn't seem to be any better - I'd say that all these three are as dangerous as Hitler was at the time he was elected. I guess Germany has been France's nemesis from before WWI/II, but so has England, Spain, Portugal and the Netherlands... so I don't know if you are simply bad neighbours.

I've been to France a couple of times and I don't speak any French (I know one word: Sortie - which was needed to find my way out ot the Paris metro), so I know what you mean. You get the feeling that the French only cares about the French and kinda ignores the rest of the world :wink:

**Comment by Sami32** [comment]
@Nadahar Bad neightbour ? we don't like so much when they come in France that they considerate it as a dustbin ! very clean at home and dirty in France; they do not mix with french as well, i mean they stay with other german only, except for listen classical music ;-)
Dutch, english are very appreciate, and no worry about other europeans.

I agree about Napoleon, except that he was worst than Hitler, near this asshole of Lenine...for killing too much people, but he did a lot for science, laws and education. Maybe he was thinking that african people was not humans...

Peru with Pinochet, Romania with Ceausescu, and let's see what's happened now in Austria...yes the human society seem hopeless, humans have very short memory :-(

Personnaly i don't have any problem with german, i love their righteousness, as a traveller i just see my country differently.

Yes, it's what i tried to explain you, but hopefully that's on the way to change, the frenches are visiting europe and sometimes farest, thanks to the global economic crisis that make their holiday cheaper abroad :wink:
