### ISSUE TITLE
Wiki build instructions doesn't work for me

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#658]
I installed Centos 7 on a VM to test #616 on Linux. But, as my development environment is on Windows, I need to build for Linux from Windows. I tried the description for this found in the Wiki, but it won't work for me. I don't understand the problem, it should work from what I can find of Maven documentation. I can't find a way to link to a specific line on the Wiki or comment on it, so I'm writing this is an issue. 

The Wiki says to run:
```
mvn package -P linux,-windows
```
Sounds reasonable, it means: "Activate the ```linux``` profile, deactivate the default ```windows``` profile". The response however is:
```
Unable to parse command line options: Unrecognized option: -windows
```
It looks like Maven is classifying ```-windows``` as an option despite no leading space, so I tried what should be an equivalent command:
```
mvn package -P linux,!windows
```
This also fails, but with a completely different output:
```
[ERROR] Unknown lifecycle phase "!windows". You must specify a valid lifecycle phase or a goal in the format <plugin-pre
fix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validat
e, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, gener
ate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-clas
ses, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, dep
loy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```
So it seems Maven on my computer simply isn't able to parse this, doesn anyone have any idea what is wrong?

I actually got it to build a Linux build by issuing:
```
mvn package -P -windows
```
However, that makes absolutely no sense to me as I'm only removing the default as far as I can understand, and I don't know why it chooses Linux in this case.

@Optimusprimeums Aren't you the one that usually does the release builds? If so, what are the commands you use?

**Comment by skeptical** [comment]
@Nadahar what happens with just plain ```mvn package```? It works fine on debian for me (or from Windows in same repo, doesn't matter).

**Comment by Nadahar** [comment]
@skeptical That builds the Windows build, but not the Linux build as far as I can see.

**Comment by skeptical** [comment]
@Nadahar weird, if you're in linux it should (and does, for me) by default build the linux package.  Possibly it's somehow detecting the actual host platform despite the VM. The wiki options you cite are for cross-compiling, i.e. building for the other platform.  Does it work to cross-compile for linux on windows and then test the package in centos?

FYI I have a dual-boot setup and work in linux mainly, but reboot back and forth to Windows and continue building/committing in the same repo as needed; works pretty much seamlessly (as long as line-ending settings are correct);

**Comment by Nadahar** [comment]
@skeptical I'm not trying to build from Linux, I've just installed standard CentOS 7 "developer" as a VM on a VMWare ESXi host. This host isn't even in-house, so I haven't taken the trouble of setting up a working development environment on this, this is simply a freshly installed default CentOS 7 that I wanted to try a build of #616 on. 

What I'm trying to do is therefore to cross-compile a Linux build from my Windows computer, and in fact I succeeded in doing so, but not by following the wiki and in fact it doesn't make sense to me why it worked like i did it (by simply disabling the "windows" profile). 

The build seems to work on Centos, even though I can't find the "tray icon" on the Gnome? desktop that ships with Centos 7. That lead to a little bug when I chose to start minimized, since there's no way to find the GUI after that without editing UMS.conf, but that is totally unrelated to my branch so I'll try to leave that be for now.

The core issue here is to figure out why Maven behaves like it does on my computer, and if the Wiki needs to be updated or if something is misconfigured in my end.

**Comment by skeptical** [comment]
@Nadahar sorry, missed that you explicitly said you were cross-compiling in the top post :).

**Comment by Nadahar** [comment]
@skeptical NP, but do you have any idea? Have you tried cross compiling, and does it do the same for you?

**Comment by skeptical** [comment]
@Nadahar I think long ago I tried a cross-compile in Windows and it worked, will test again.  Normally I just run ums directly off ```target/classes``` (by putting it first in the jvm classpath, whether in Windows or linux), so I don't usually bother with ```mvn package``` at all, just ```mvn compile```  (but of course this isn't foolproof and unsuitable for comprehensive testing).

**Comment by skeptical** [comment]
@Nadahar in Windows (maven-3.3.3) running ```mvn package -P linux``` builds both tarball+exe for me, and ```mvn package -P linux,-windows```just the tarball, so everything seems ok.  Maybe your maven is different, or is Eclipse involved somehow?

**Comment by Nadahar** [comment]
@skeptical Not as far as I can tell. The behaviour you describe is what I'd expect to, so there must be something really weird with my installation. 
```
> mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Program Files\Apache Maven\apache-maven-3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_45\jre
Default locale: no_NO, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

At least we know it's something with my installation then - but I haven't got a clue what it is. That means that the Wiki is correct, and this issue should probably be closed. I'd like to let it stay a little while though, in case somebody else have had any similar experiences.

**Comment by Nadahar** [comment]
@skeptical :bulb: I found the reason!

I use the "Windows PowerShell" (powershell.exe) instead of "Command Line" (cmd.exe) because it supports copy and paste better, accepts "ls" (which I automaticly type) etc. For some reason Maven can't correctly parse the input from there, when I tested with the normal "Command Line" mine behaves as it should as well.

It's really strange how Microsoft always manages to make things that's not really compatible with anything.

**Comment by skeptical** [comment]
@Nadahar in linux the odds of preserving one's sanity increases greatly imo :).

**Comment by Optimusprimeums** [comment]
@Nadahar Mate I only build the OSX Versions with a VM of OS-X (10.8). Also never had an issue building Windows Or Linux on Windows but I use Netbeans as I just getting used to the CMD line stuff

**Comment by Nadahar** [comment]
@skeptical I'd say that varies a lot, I've lost a lof of hair to Linux as well, but if we're sticking to command line I agree that one's sanity has better odds in Linux.

@Optimusprimeums Thanks for your reply, as you can see above I already figured out the problem :smile:
