### ISSUE TITLE
Problems with sony devices

### ISSUE THREAD

**Issue by OzzyBees** [UniversalMediaServer/UniversalMediaServer#662]
Hi - having problems with multiple sony devices when transcoding.
Trying to stream MP4 files to my Sony TV and Blu ray players using 5.2.2.
Problem 1 - to a Sony KDL-40EX503. Sound and audio go out of sync as soon as fast forward / fast reverse are used. Found posts this is fixed in 5.2.2 but it isn't. Multiple .mp4 files.
Problem 2 - to a Sony BDP-S370 Blu Ray. I found the bit in the conf file that needed uncommenting for a UK model - that allows transcoding of .mp4 files. MP4 playback takes about a minute to start then play ok for a few seconds then play with both audio and video breaking up.

Please help.

**Comment by Sami32** [comment]
@OzzyBees As we not necessary own the same renderer for testing, your full trace log should be very helpful.
Just follow these few steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by paulene-c** [comment]
@OzzyBees we're presuming this is no longer an issue for you so we're closing.  However if you need to reopen please upload TRACE logs as requested above.

**Comment by polygirl** [comment]
@OzzyBees we're presuming this is no longer an issue for you so we're closing.  If you need to reopen, please add TRACE logs as requested above.
