### ISSUE TITLE
Support for Samsung TV C5000's built-in Resume function

### ISSUE THREAD

**Issue by nitrobg** [UniversalMediaServer/UniversalMediaServer#665]
The TV's built-in media player has the function of resuming a previously stopped video using the remote's "D" button. I know that UMS already has a similar functionality but it transcodes the video on the fly and there are some limitations to it - such as you cannot FF or rewind and it's not as precise as the built-in option.
It seems like the same issue is already discussed here: http://forum.serviio.org/viewtopic.php?p=6504&sid=308fb26b61282ae7fa65fcd191ad4e7a#p6504
I can supply you with a wireshark dump if necessary. Thank you.

**Comment by SubJunk** [comment]
This seems like it would be a good addition to the program. Thanks for the suggestion.
