### ISSUE TITLE
Add support for Horizon Mediabox

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#666]
Hello dev team
sins yesterday we have a Horizon mediabox
it has the support to connect with UMS but cant yet i think
i have tryed to connect but it sayed no servers where found at all
so donno what you peeps need to do but can you add it to UMS
if you need info please tell me what you need and i will do my best to profide it

**Comment by polygirl** [comment]
@Goten87 if you're still having trouble connecting your mediabox can you please upload full TRACE logs so that we can look into it?

**Comment by SubJunk** [comment]
Logs never arrived
