### ISSUE TITLE
Buffer full after stopping playback

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#674]
http://i.imgur.com/Z5NcjPr.png

Happened with https://github.com/UniversalMediaServer/UniversalMediaServer/commit/f5afcde612a1d281622e1321b6f2bec9e354bead

Logs available on request.

**Comment by Nadahar** [comment]
Could this also be related to #672? Isn't the easy solution for now just to downgrade JavaAssist again?

**Comment by SubJunk** [comment]
@Nadahar I don't mean the bug was caused by f5afcde, just that that was the version I was using when the bug occurred. I'm not sure if it could be related, I haven't noticed the bug described in #672 before

**Comment by Nadahar** [comment]
@SubJunk Ok, I misinterpreted you. The reason I thought about the issues being related is that since #672 behaves like it does in intervals, a buffer issue would seem like a prime suspect.

**Comment by Sami32** [comment]
@SubJunk Yes, if this issue is again a valid one, i'm interested to get your log ;-)

I think like @Nadahar that it have somethink to do with a buffer issue.

**Comment by SubJunk** [comment]
I don't think I've seen this again but will reopen if it happens again
