### ISSUE TITLE
What is a nameless ```DLNAResource```?

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#675]
@UniversalMediaServer/developers @SubJunk 
What is a nameless ```DLNAResource``` and why is it called ```[No encoding]```? I'm asking because I have to provide some context to ```DLNAResource.0``` at [crowdin] (https://crowdin.com/translate/universalmediaserver/1/enus-ca#q=[no+encoding]) so that the translators can know how to translate it.

It is used [here] (https://github.com/UniversalMediaServer/UniversalMediaServer/blob/305b76af5acf7bc1ae3a47e7daa129331efcdb66/src/main/java/net/pms/dlna/DLNAResource.java#L1299) and committed here: https://github.com/UniversalMediaServer/UniversalMediaServer/commit/305b76af5acf7bc1ae3a47e7daa129331efcdb66#comments

**Comment by SubJunk** [comment]
@Nadahar it's an entry that goes into the #-TRANSCODE-# folder which forces the file to play without transcoding, instead of automatically detecting how to play the file.

**Comment by Nadahar** [comment]
@SubJunk Ok, but isn't this behavior general - meaning that any ```DLNAResource``` with no name will get this label, not only the "unmodified" file in the ```#-TRANSCODE-#``` folder? Also, "No encoding" could mean so many things, wouldn't "No transcoding" be a better description?

**Comment by SubJunk** [comment]
Yes, "No transcoding" would be more accurate. I'm not sure if it would be the same for any unnamed DLNAResource.

**Comment by Nadahar** [comment]
@SubJunk Ok, thanks - I've changed the wording in 7f052787a4d1e47c1c026802a81b53e8fa98b63b.
