### ISSUE TITLE
What is a forced tag for a subtitle?

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#676]
I'm struggelig to understand forced tags for subtitles, and need to give a context for [the term on crowdin] (https://crowdin.com/translate/universalmediaserver/1/enus-ca#q=Forced+tags:). 

It's being used [here] (https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/dlna/DLNAResource.java#L2058), [here] (https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/encoders/Player.java#L418), in the ```Transcoding``` tab in the GUI under common settings -> subtitles and in ```UMS.conf``` as ```forced_subtitle_tags```. The default value is ```forced```. 

From the code, it seems that both forced tag and forced language has to match for the subtitle to be forced..? I certainly don't understand what it does, and I think it's optimistic at best to expect the users to understand it, so we might need a little redesign here.

**Comment by ExSport** [comment]
@Nadahar As an owner of the code I will try describe it.
https://code.google.com/p/pms-exsport/wiki/FAQ
In the link there are some general principles how to use it so this info should be enough to understand.
The feature was a user request to play subs for klingonese, cantonese,latin, titles, singing or other language parts.
It means forcing subs also in case native language audio track is chosen.
In general audio/subtitle logic came from Audio/Subtitle combination. If you are from USA,UK etc., your native language is EN so probably you will use these preferences:
```
ENG,OFF;UND,OFF;*,ENG
```
It means to load english audio if present with no (full) subs. If there is UNDefined audio track, don't load subs as some may have untagged audio tracks (or container doesn't support it). At last if any other audio language is played, UMS will load english subs for you (JPN audio and ENG subs).
And now FORCED LANGUAGE and FORCED TAGS:
If UMS will find subs which are tagged as "FORCED TAG" (can be multistring divided by ","), without this feature UMS will load no subs for native ENG audio. Unfortunately it is Startrek and some of us don't understand Klingonese so UMS is so clever that when subs with forced tag are found, UMS will load them also in case native audio without subs is resolved via Audio/Sub preference.
FORCED LANGUAGE defines your native language to UMS (only one langtag/native audio is supported) so it knows for what language forced subs should be loaded as forcing "Klingonese only" subs for non-native e.g. german audio track is not expected as you want full subs in this case.
Provided link shows how to understand this feature and correct settings definition in UMS GUI and how to define external subs to be resolvable correctly by UMS.
There are few who know how to correctly tag external subs with audio tag as also UMS leads you to name subs exactly same as video but in this case UMS automatics is limited greatly.
Hopefully you understand the meaning of this feature and its logic.

**Comment by Nadahar** [comment]
@ExSport Thank you for the explanation, it definitly clears up some of my confusion. I know what forced subtitles are, but because of they way it's implemented in the GUI it never occurred to me that that is what this was about. What particularly derailed me was that I didn't understand what the tag was, but I understand now it's just a part of the title/filename of the subtitle in question. Btw. I am Norwegian and use subtitles for almost everything, so I am generally familiar with subtitles.

Forced subtitles is useful, but I think we need to find a more descriptive way to define it.

Btw. shouldn't you export the project to github before google code is closed for good (I think it will only stay up for one year). Even if it's not maintained anymore, it's a shame to loose it.

Does anyone have any suggestion to how this could be simplified or at least made easier to understand for the average user? I guess some descriptive tooltips would be the very minimum...

**Comment by ExSport** [comment]
@Nadahar The code origin is from time where PMS and UMS was sitting on google code and there was no github project :+1: so on google code there is only very old and not updated FAQ which I am using in forums to not repeat myself million times.
I agree it can be reformulated to be better understandable but I don't know how.
Bigger problem is that users don't understand how to define preferred audio/subs combination what is key part also for forced subs.

**Comment by Nadahar** [comment]
@ExSport I understand that it's old, but when Google shut down Google Code completely it will all be lost.

About the configuration design, it's no wonder that the users don't understand the configuration, I hardly understand it myself. For example I'm confused by the mix of alpha2 and alpha3 language codes used, some places alpha2 is used and some places alpha3 is used. Does this actually work? From the little debugging I did, it seemed to me like the codes actually compared to is alpha2, while the default codes in the GUI is alpha3. For me that means that "no" is not equal to "nor", so I would think it would fail for this reason alone.

The configuration for the subtitles setup should be redsigned entirely in the GUI where one can choose languages from lists/checkboxes in some dynamic way. That and descriptibe tooltip texts could make it much more managable for normal users.

**Comment by ExSport** [comment]
@Nadahar Yes, only FAQ part will be lost, nothing more, I know.
If I remember right there is a call (to conversion table) which translates any 2char or 3char definition when parsing so the result should be same for both.
There are some breaking bugs in UMS/PMS so noone has much time to play with GUI which is quite confusing to code it :-) I can't see any easy way how to define AUDIO/SUBS preference in some dynamic way. But I agree it is quite misleading to set preference separately as AUDIO preference and SUBTITLE preference (here using list is possible) and then we have here combination of both as AUDIO/SUB preference. Noone knows the precedence, few know how to correctly set it but it is a key feature in UMS/PMS automation.

**Comment by Nadahar** [comment]
Even though I think this is far from ideal, I guess I got the answer I needed.

**Comment by ExSport** [comment]
@Nadahar Feel free to ask again. My english is limited so maybe I missed your meaning so didn't answer what you asked for :-)
Also my programming skills are limited so I added some new code and reused or edited existing one to make it work so there is no extra GUI options from what UMS offers by default. From start configuration was via conf files only and later to be easily visibe and usable from GUI there was these two boxes addded to not confuse users more then needed so some ignores it as is (for 90% users settings it valid) and others who knows, they reconfigure it for their own as forced lang is gathered automatically from settings (UMS GUI/OS localization if I remember right) and "forced" tag is widely used by many to tag forced subs in containers whatever laguage they are using... Only french guys sometimes are using "forcé" so because of that definition can be "multistring".

**Comment by Nadahar** [comment]
@ExSport I didn't mean anything wrong, I only meant that I think we should improve the GUI to make it more understandable, maybe building further on #74. Your explanation was just fine, I fully understand what it does now :+1:

**Comment by ExSport** [comment]
Great! :+1: Explanation fine but java coding so poor so I can't help optimizing as I am server admin with general knowledge of Pascal, PowerShell, batching etc. co I am not able to code something completely new but I know enough to be able reuse another code, understand it somehow and edit it for my own purpose :-)

**Comment by Nadahar** [comment]
My native is Pascal/Delphi as well :wink: In fact I've never touced Java until i pulled UMS.
