### ISSUE TITLE
Movies playing but will freeze and unplayable after on MAC

### ISSUE THREAD

**Issue by serenads** [UniversalMediaServer/UniversalMediaServer#678]
Whenever I'm watching a movie or TV show it will open fine the first time, completely freeze about 10-20 minutes in sometimes less sometimes more and then say "Cannot play the media" over and over - restarting UMS doesn't help just continuing to try to open the file is the only way to get it to fix and it continues through the whole movie/TV show I am watching this is happening on my 2010 Macbook Pro while trying to watch through PS4

Having major issues trying to do the .zip file for the logs so here is a link from the website provided in the support instructions- uploaded.net/file/q2ag77qv

**Comment by SubJunk** [comment]
@serenads can you please try previous versions of UMS to see if there is a version this didn't happen with? I think it might be a newer bug

**Comment by serenads** [comment]
I think it may have to do with my computer. I've tried a different computer and it hasn't been doing it at all

**Comment by ngoldbaum** [comment]
I'm seeing this behavior as well. I'll try with 5.2.0 when ps4 support was added.

**Comment by ngoldbaum** [comment]
I'm seeing video interruptions about a little while in 5.2.2 as well.

Also it looks like the Java8 version of UMS isn't able to connect to my ps4. The Java6 version works, haven't tried the Java7 version.

**Comment by Nadahar** [comment]
Could this be related to the netty downgrade?

**Comment by SubJunk** [comment]
Closing because it's stale, feel free to reopen if the problem still exists
