### ISSUE TITLE
What is the indended use of DLNAMediaDatabase.1?

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#680]
I've been asked to provide context for:

```
DLNAMediaDatabase.1=A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
```

on crowding. I've looked in the code, and it's used to create the regex rules in the database that I haven't really figured out how is being applied. It seems to be used for sorting in some way, but as far as I can tell it's not. The Norwegian version of the alphabet is like this:

```
DLNAMediaDatabase.1=A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,Æ,Ø,Å
```

and thus is used in the Norwegian language file. However, when I test to rename some files to start with the extra (`Æ`, `Ø`, `Å`) letters they are not sorted correctly. They are sorted before `A` like they were some kind of special character like `#` or `-`. 

My question is therefor, how is the intended purpose of this, and if it's what I think why is it needed (there's better ways to sort by alphabeth) and why doesn't it work (I've seen one thing that could make it fail, that `\W` is used to filter out non characters and sort them first. `\W = [^A-Za-z0-9_]` so that will fail. Something like `\P{L}` would probably work better, but I still don't understand why native sorting can't just be used.

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk Should I conclude that the silence means that nobody knows?

**Comment by Sami32** [comment]
@Nadahar I don't know if you found the answer already, but since @SubJunk recently worked on the database perhaps he know about ?

**Comment by Nadahar** [comment]
Sure
