### ISSUE TITLE
HTTP Engine v1/v2

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#685]
@UniversalMediaServer/developers @SubJunk 
I'm wondering why we have two different HTTP engines, and in what way they behave different. What I do understand is that v1 uses the API restricted Oracle only `com.sun.net.httpserver.HttpServer` and that v2 uses netty. 

What I don't understand is why both solutions are kept. The version numbers seems to suggest that `com.sun.net.httpserver.HttpServer` is the original solution. Was there any problems with this except that it's not compatible with non Oracle Java VMs? Why was v2 created?

When v2 was created for whatever reason, why was v1 kept? That seems to indicate to me that some things never properly was solved with v2. Was this done in PMS or UMS? What is the remaining issues with v2/netty? To me it seems like the parallell processing of requests it tied to v2 (haven't done extensive testing), and I consider this a quite serious bug/problem. If that assumption is correct, why don't we either solve it or default to v1? It's hard for me to believe that this really is a problem with netty, it's probably rather how we use it. I've already noticed that everything isn't closed properly, could that be the cause?

**Comment by skeptical** [comment]
@Nadahar I don't know the history because it predates my involvement (ca. 2011) but I imagine like many other issues here the judgement was to split the baby (or duplicate it, rather). I personally haven't noticed any real shortcomings to v1, though I suppose in theory under stress it would collapse sooner than v2.

**Comment by Nadahar** [comment]
@skeptical That means PMS era, right? Chances are there's nobody left with the project that really knows then?

If anyone else has information to any of my questions, please reply.

**Comment by skeptical** [comment]
@Nadahar this is a question for @SubJunk, who's been here since early days.

**Comment by SubJunk** [comment]
@nadahar good question. It first appeared in r335 in the PMS Google Code repository, https://code.google.com/p/ps3mediaserver/source/detail?r=335 and it looks like my first official commit was r415, and my first unofficial build was on top of r410 in 2010 so I think it's before even my time on the project :)

We have had reports from forum users that their bugs have been fixed by switching from v2 to v1, but I'm not sure whether that was because of old bugs in v2 that have since been fixed.

**Comment by ExSport** [comment]
@SubJunk @Nadahar I spotted similar weird behavior about disconnections, hangs etc. with any engine used so I am sure there are some bugs in network code globally, independent on engine used.
Some detalis I also mentioned in other issue (OT) as I was unable find this one and wanted to not forgot about it:-)
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/708
Btw. PanTV and PS3 mainly used. 1Gbit stable network. Quad Core PC.

**Comment by Nadahar** [comment]
@ExSport "Engine" can be a confusing term as it is used about so many different things. With "engine" here we're not talking about which program does the transcoding, but about which code that run the HTTP server serving DLNA clients. There are two versions in UMS, v1 which uses a Java inernal ```HttpServer``` component and v2 that uses ```Netty```. v2/netty is the default, but you'll always use either v1 or v2. You can choose it on the ```General``` tab. You should try v1 and see if the problems are the same.

**Comment by ExSport** [comment]
@Nadahar
I am not native English speaker but I am sure I described engines exactly in the way that everybody understand it as http v1 and v2 network engines as also I mentioned Netty in another  linked post.
I  can say about myself I am strong in UMS terminology:))

**Comment by ExSport** [comment]
Because of that I marked this part as little bit off topic (OT) but wanted to mark that networking problems are also outside transcoding engines  as direct streaming is.
Maybe it confused you:))
