### ISSUE TITLE
[SUGGESTION] add more options for profile selector

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#688]
right now i start up with `UMS.exe profiles`
will be nice if we can have more behind it maby the config file so it will load in with the startup icon
somthing like `UMS.exe" profiles -profile:Location to UMS.conf`
sins when i load in that file it gives the profile will be nicer to auto start my costume profiles with startup with my pc

**Comment by Nadahar** [comment]
@Goten87 I think that sounds like a good idea, and I've made a pull request for it in #690. Time will show if the others approve of it.

**Comment by Nadahar** [comment]
I've merged #690 so I'm closing this as implemented.
