### ISSUE TITLE
New Media feature not working

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#698]
It seems that the "New Media" folder feature isn't working for me - on my PS3 if I watch a video to the end, it's not marked as watched and the file "UMS.mon" still doesn't exist.
The ".resume" files are created if I watch halfway through, and not created if I watch the whole video, so I think the overall logic is still working but it's just not recording the watched status in the file. That is how it used to work, didn't it? @SharkHunter ?

**Comment by SubJunk** [comment]
The check in MediaMonitor.java:130 (if (monitorClass(tmp)) is failing when the video has finished playing

**Comment by SubJunk** [comment]
Playing the "Clear All" video makes the PS3 display an error but correctly adds all files to UMS.mon

**Comment by SubJunk** [comment]
Oh I had forgotten that it only works if you played the file via the New Media folder, duh. Closing this ticket now.

**Comment by Nadahar** [comment]
@SubJunk This seems relevant to #806. I can't get this to work - what do you mean that it has to be played from the New Media folder? It this special folder found anywhere else?
