### ISSUE TITLE
Can't restore main window from system tray in Gnome 3.18.1

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#704]
After minimalising main window in system tray with "X" button in Gnome 3.18.1, it cant be again restored.
UMS is running in background anyway.
If i want to exit it or see main windows again, u must kill it viac System monitor and run it again.

Using 64bit Arch Linux with JRE8-openjdk

**Comment by Nadahar** [comment]
@prescott66 Gnome has a very bad implementation of system tray. You can show it with ```<super>```+```m```, but I don't think clicking on it will do anything. I don't think there's any solution to this except not to "close" UMS with "X".

**Comment by polygirl** [comment]
@prescott66 closing as this seems out of UMS' control as Nadahar suggested in his workaround.
