### ISSUE TITLE
Shared Folders control renders incorrectly on high-DPI display in Windows 10

### ISSUE THREAD

**Issue by johnddx** [UniversalMediaServer/UniversalMediaServer#709]
On a 4k monitor, with DPI scaling at 200% to compensate, the Shared folder view compresses each item in the list to half-height.
![capture](https://cloud.githubusercontent.com/assets/15313197/10717222/31dd1796-7b0e-11e5-9736-047109bd0933.PNG)

**Comment by Nadahar** [comment]
@johnddx I don't think UMS' GUI has been tested/adapted for DPI scaling at all. Is that the only issue you get?

**Comment by johnddx** [comment]
There are others, but not as bad.  In several places the text is quite tiny, especially Logs and the Help tab.  

The Shared folders tab is the only place that's actually hard to use as a result (due to clipping).

**Comment by Nadahar** [comment]
@johnddx I've made a suggested fix in #712. It won't make it for the next release though, as that's already in the pipeline.

**Comment by Nadahar** [comment]
#712 is merged now, so this should be in the next release.
