### ISSUE TITLE
Is Reviewable something for UMS?

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#710]
@UniversalMediaServer/developers @SubJunk 
I often feel that the code review process can be a bit messy, I don't really know how long I have to wait for response. I don't know if you've looked at it and have nothing to say about it or if it's unseen, and it's often somewhat unclear to me what's been agreed upon.

I looked quickly at [Reviewable](https://github.com/integrations/reviewable) and think it looks interesting. Maybe you guys think it's to much formalities, too much "bureaucracy", but I feel that more structure around this could be helpful. What do you think?

**Comment by SubJunk** [comment]
It looks promising. I don't want it to create more work for us, but it looks like it will involve less work so that's good.

**Comment by Nadahar** [comment]
It's hard to know before we've tried, but it's free for open source and we can just leave if it doesn't make things easier so I think it's worth a shot.

**Comment by SubJunk** [comment]
It should be linked now

**Comment by valib** [comment]
Agree it looks good.

**Comment by Sami32** [comment]
Sure, but having the 2 together is perturbating, isn't it ?

@Nadahar Feel free to re-open it you see a purpose, that we all know about ;-)

**Comment by Nadahar** [comment]
@Sami32 This was before GitHub introduced its own review tools - even though as we've seen they aren't as good.
