### ISSUE TITLE
Edge Browser Misidentified as Safari Browser

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#721]
Here is the User-Agent that shows for Edge Browser on Windows 10 x64:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by SubJunk** [comment]
Hopefully fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/d8f8e17fd268aee21e8a3a543c41b59f91b9e79e
Thanks!
