### ISSUE TITLE
Transcoding failure on PS4

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#725]
Reported on [the forum] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5607&sid=9ac46a446a7a7bdcd46865297c84defe). It's transcoding to ```MPEGTS-H264-AC3```. Shouldn't that be compatible with the PS4?

**Comment by Sami32** [comment]
@Nadahar Did the latest UMS version, with all the subtitles improvements done since, solved this issue ?
