### ISSUE TITLE
play audio file  for shorter   time  of total

### ISSUE THREAD

**Issue by anthraxs** [UniversalMediaServer/UniversalMediaServer#726]
i tryed  multichannel  flac  and wav    L16 format 

multichannel  flac   total time 5:25   played   for only 1:48    

other   multichannel  flac   total time 2:21    played  for only 47 seconds 

DEBUG 2015-11-10 10:46:34.207 [main] 

TRACE 2015-11-10 10:48:03.813 [New I/O worker #8] net.pms.formats.FormatFactory Matched format FLAC to "E:\Bittorrent\1997-Depeche Mode - Ultra-flac\01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac"
TRACE 2015-11-10 10:48:03.815 [New I/O worker #8] net.pms.dlna.DLNAResource Adding new child "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac" with class "net.pms.dlna.RealFile"
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.formats.FormatFactory Getting player for resource "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac"
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.formats.FormatFactory Player "FFmpeg" is incompatible
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.formats.FormatFactory Player "MEncoder" is incompatible
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.encoders.TsMuxeRVideo tsMuxeR cannot determine compatibility based on audio track for E:\Bittorrent\1997-Depeche Mode - Ultra-flac\01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.formats.FormatFactory Player "tsMuxeR" is incompatible
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.formats.FormatFactory Returning compatible player "FFmpeg Audio"
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:mpegps|mpegts   v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm|aac|mpa   m:video/mpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:atrac   n:2                            m:audio/x-oma
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:mp3     n:2                            m:audio/mpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:wav     n:2                  s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:wav     n:6   a:dts|lpcm     s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:jpg    m:image/jpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.dlna.DLNAResource File "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac" will not be streamed because it is not supported by the renderer
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:mpegps|mpegts   v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm|aac|mpa   m:video/mpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:atrac   n:2                            m:audio/x-oma
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:mp3     n:2                            m:audio/mpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:wav     n:2                  s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:wav     n:6   a:dts|lpcm     s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "lpcm" failed to match supported line f:jpg    m:image/jpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.dlna.DLNAResource Final verdict: "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac" will be transcoded with player "FFmpeg Audio" with mime type "audio/L16;rate=48000;channels=2"
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:mpegps|mpegts   v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm|aac|mpa   m:video/mpeg
TRACE 2015-11-10 10:48:03.816 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:atrac   n:2                            m:audio/x-oma
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:mp3     n:2                            m:audio/mpeg
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:wav     n:2                  s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:wav     n:6   a:dts|lpcm     s:48000   m:audio/L16
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.configuration.FormatConfiguration Format "flac" failed to match supported line f:jpg    m:image/jpeg
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.dlna.DLNAResource Adding "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p.flac" to transcode folder for player: "FFmpeg Audio"
TRACE 2015-11-10 10:48:03.817 [New I/O worker #8] net.pms.dlna.DLNAResource Adding new child "01 - Depeche Mode - Barrel Of A Gun-d2p-p2p" with class

**Comment by Nadahar** [comment]
@anthraxs I'm not sure I quite understand what you mean, but there is a bug in UMS where high sample rate files will be played back too fast / with a high pitch if you're transcoding to LPCM. The solution for now is to transcode to WAV (or MP3 if you accept the lowered quality) instead.

I've reported this issue myself in #588.

**Comment by anthraxs** [comment]
i play   multichannel  wav   is  just  LPCM  96 khz 24 bit   and  no  need conversion
 flac   multichannel   24 bit 88.2 khz  and work  well   but  UMS  wrong to calculate  the  size  of  file   so  it  play   only  a bit not all the file 

for high pitch  problem  is   simply  to solve  need only to deselect  resample   to  44.1 or  48

**Comment by Nadahar** [comment]
@anthraxs Ok, I struggle a bit with interpreting, but I understand that this is a different bug then.

I know that LPCM and WAV is the same, but it isn't quite the same as WAV has a little header with information about sample rate etc, while LPCM is just the raw stream. That makes the difference some times.

I have files where deselecting resample to 44.1 or 48 doesn't help, simply because UMS sends the wrong sample rate in the HTTP headers if I remember it right.

Can you come up with a link to a file where this happens, so I can reproduce the problem?

**Comment by anthraxs** [comment]
i  made that  file  from dsd  with saracom  if  u have a sacd iso 

 or can use  foobar2000

**Comment by anthraxs** [comment]
i try  to download a trace  log  but don't have permissions

what i need to change ?

**Comment by anthraxs** [comment]
now  i try again   to send  the zip  file  Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF
why ????

**Comment by Nadahar** [comment]
@anthraxs You can't upload zip files to github, you must [post it on the forum] (http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556).

**Comment by anthraxs** [comment]
http://www100.zippyshare.com/v/Xd3hlWeR/file.html    

 open  with chrome for download  is the  trace log.zip

**Comment by anthraxs** [comment]
http://www82.zippyshare.com/v/gNeyxG0i/file.html
open  with  chrome 
   here   there is  a multichannell  flac   total  length  2:21  played   for only 47 sec

**Comment by Nadahar** [comment]
@anthraxs Thanks, I'll take a look at it.

**Comment by Nadahar** [comment]
@anthraxs I think this is due to the same bug as #588. On my renderer the file plays full length, but at wrong pitch. It probably depends on how the renderer handles the missing information (the sample rate) what the outcome is.

I've made a fix for the issue which I'd like you to test to see if it fixes it for you. You can download the test version here: http://superbum.org/downloads/UMSSnapshot-setup.exe

Another solution that probably would solve it is to add ```TranscodeAudio = WAV``` to you renderers configuration ```Vizio-SmartTV.conf```. I'd appreciate if you could try both options and report the outcome.

**Comment by anthraxs** [comment]
the problem  still the same  same  error 

 now i use  sony  bluray (2013) renderer

**Comment by anthraxs** [comment]
have installed ums 5.3.1  but  same    error   no fixed

**Comment by anthraxs** [comment]
the  sile  is   5.1 pcm  8467.2 kbps   88.2 khz

**Comment by Nadahar** [comment]
@anthraxs I used fobar2000 as renderer (it has DLNA support), and it playes the whole file. Can you try that, so we are sure we are talking about the same thing? You have to make sure that whatever renderer profile is used to foobar2000 is transcoding the file, if it is streamed it obviously works fine.

Did you try to change the renderer config to ```TranscodeAudio = WAV```?

**Comment by Sami32** [comment]
@SubJunk @valib Can this issue be closed ? without feedback anymore or full log...
