### ISSUE TITLE
Stuttering during playback on LG WebOS 2.0 TV

### ISSUE THREAD

**Issue by porst17** [UniversalMediaServer/UniversalMediaServer#738]
I have the issue that almost all my videos are heavily stuttering (every second or so) on my LG Web OS 2.0 TV. First, there is no proper profile for this particular TV, but this doesn't seem to be the issue. For testing, I created a new profile which just streams all media supported by the TV without transcoding. The videos I tested are encoded in formats supported by the TV (e.g. .mkv h.264/ac3).

I also shared the movies via a simple webserver that runs on my box (I can watch all of them in the web browser of my TV without any problems) and via minidlnad (not all videos are listed, but those that are listed are playing well).

Today, I connected my smart phone to UMS using the transcoding-disabled renderer profile I used for testing my TV and magically, the movies are also playing without any stuttering on my smartphone via UMS.

Can anyone please advice me how to debug this issue? It's not a wifi issue and not a codec issue in my opinion. I looks like a buffering issue to me, but I can not find any setting in UMS related to that.

The debug files can be found here: https://gist.github.com/porst17/ad84e0061795bb5b71de
(this is only for the TV connected, not for my smart phone)

**Comment by porst17** [comment]
I just took a look onto the status page of UMS while streaming the files to my TV. The peak bitrate is at about 40Mbps when I start the video, but then goes down to 2Mbps on average. However, when I stream to my smart phone, the bitrate is about a factor of 10 to 20 higher (same router, same network). Since minidlnad streams fine to the TV and the TV plays 1080p on youtube without noticeable lag, I doubt that the bitrate limitation is due to my wifi.

**Comment by valib** [comment]
@porst17 your tested video is not streamed but transcoded because you need to add ac3 audio to the Supported line. Try to change in your LG-UF85.conf line ```Supported = f:mkv v:h264|mp4|vp9 a:aac``` to
```Supported = f:mkv        v:h264|mp4|vp9                  a:aac|aac-he|ac3           m:video/x-matroska```

**Comment by porst17** [comment]
Thanks for your prompt reply. Sorry, I overlooked the missing `ac3` part. Your suggestion does not work either, but when I remove ` m:video/x-matroska` the movies play well.

But does audio transcoding cause such problems usually? Should be pretty lightweight compared to video transcoding. The questions remains: Why is the transcoding to my smart phone fast enough? I used the same (wrong) renderer profile for it.

**Comment by yesoos** [comment]
I have the same issue with LG WebOS TV (2.0), could you provide a working profile?

**Comment by Sami32** [comment]
@yesoos Did you tried that http://www.universalmediaserver.com/forum/viewtopic.php?t=5724 ?
If it's not working i guess that https://developer.lge.com/webOSSignage/discover/specification/platform-spec/media-support/supported-format-webos-2-0/ will help do the job ;-)

**Comment by yesoos** [comment]
This config doesn't seem to work, problem is that I need transcoding for
subtitles? Whenever It is transcoded playback pauses every second to
buffer? This does not happen on Xbox.

sob., 16.07.2016 o 18:21 użytkownik Samuel <notifications@github.com>
napisał:

**Comment by valib** [comment]
@yesoos we need the log. Please follow the http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by yesoos** [comment]
@valib Here is the log in zip. Did 3 runs, 1st ffmpeg - did not even start, 2nd mencoder - starts buffering every second (which stop if you kill UMS process, tv starts playing normally but stops after buffer is out of data), 3rd tun - no transcoding, works just fine (but no subtitles).
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/368572/ums_dbg.zip)

**Comment by valib** [comment]
@yesoos you set `encoded_audio_passthrough = true` which forces transcoding. The default value is false. Please disable the option Encoded audio passthrough ... at the Transcoding Settings page the Audio Settings subpage and test it again and please send the log.
You can also delete in the conf the line `SupportedSubtitlesFormats = SUBRIP,TEXT,VOBSUB,PGS,ASS` which is no longer used.

**Comment by yesoos** [comment]
@valib Disabled encoded_audio_passthrough, and indeed it does not format encoding. Though it doesn't show subtitles either. (though in title it shows { External subtitles: Text File})

**Comment by valib** [comment]
@yesoos I need check the log but I think that your TV doesn't support to stream external subtitles and they must be always transcoded. Please provide the log.

**Comment by yesoos** [comment]
@valib Log attached. Why is there a problem with transcoded video - transcoded video is very smooth on xbox one.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/369825/ums_dbg.zip)

**Comment by valib** [comment]
@yesoos now I found something else. Most of your movies have bitrate higher than 10Mb/s and because you enabled `Use automatic maximum bandwidth` and the calculated network speed is `Renderer lgtv has an estimated network speed of 28.845217611324955 Mb/s`  (is it WiFi?) so UMS says `video xy will not be streamed because the bitrate (10515297) is too high (7000000)`. 
To avoid transcoding for high bitrate videos disable the `Use automatic maximum bandwidth` and try to use the default maximum bandwidth 90. 

Anyway to test if video is possible to stream to TV with/without subtitles please use the TRANSCODE folder. There are all possible combinations for engines, audio and subs for testing

**Comment by yesoos** [comment]
@valib Set those, basically whenever I try to play something transcoded on tv it buffers every seccond, without transcoding I don't see the subtitles - but the playback is ok. Transcoded video with subtitles seem to work perfectly fine (though seeking doesn't work on xbox one). I can provide logs if needed.

**Comment by valib** [comment]
@yesoos you wrote
> I doubt that the bitrate limitation is due to my wifi. 

Does it mean that your TV is connected by wifi? If so try to set `mpeg2_main_settings` and `x264_constant_rate_factor` to Automatic (Wireless).

I also found that you set `TranscodeVideo = MPEGTS-H265-AC3`. I recommend to try the standard LG-WebOS setting `TranscodeVideo = MPEGTS-H264-AAC` which should be less CPU demanding. The H265 needs 4 times more computational power.

**Comment by yesoos** [comment]
@valib Did not change a thing, when not transcoded - working perfectly (no subtitles - eventhough it says external subtitles), when transcoded with ffmpeg - ffmpeg crashes (exit with 1 code), mencoder - works but buffering every second or less, tsMuxeR - same as mencoder. Also for xbox one with wifi it's working just fine.

**Comment by ExSport** [comment]
@yesoos It seams you don't understand that there is difference transcoding to XBox (WMV8/ASF?) and to LG with change to h265. 
You can't compare mpeg2 and h264 or h265 in speed so most probably your problem is CPU overload and not Wifi bandwidth.
Listen to Valib and change transcoding format as suggested ;)

**Comment by yesoos** [comment]
The comment I made before is after I changed values to what @valib suggested, there was no change. Computer transcoding is 8 threads@4GHz with 32GB of ram - I don't think performance is the problem here. I've also tested with everything on Gigabit wired connection - the same issue.

**Comment by ExSport** [comment]
Have you tried all options in Transcode folder? So you will see problem is with subs only or also when only transcoding without subs is engaged?
You should also try e.g. MEncoder transcoding and copy paste generated command line from log directly to CMD to see if it works or not and if final file is correctly playable (break process after some minutes). If it works on PC, try this file directly in TV via USB if it works ok. Same you can do with FFmpeg.
You should try general troubleshooting like this to help us.
Thx.

**Comment by yesoos** [comment]
@ExSport 

Tried all in transcode, it will "buffer" or stutter during playback (with or without subtitles, though all of them with AC3 sound). Regarding testing just the transcode, funny thing is, when I kill UMS process during "playback" on tv, stuttering/buffering issue sudenlly stops, tv plays what it has in buffers, and stops the playback when buffer ends.

So this seems like some sort of connection/buffering problem, maybe WebOS 2.0 need some speciall options?

**Comment by ExSport** [comment]
The easiest way is to test it.
Start Transcode without subs. It will stutter as you said. Stop playback after minute. Check log for generated command and replace output file from PIPE to file on disk. Run it in CMD. Wait a minute and break it by e.g. ctrl+c. It should generate file.
Try it if it if playable on PC. Then try it in TV via USB and at last STREAM this generated file directly to TV via UMS.
If generated file will stutter only when streaming by UMS, then there should be buffering/network stack problem in UMS probably.
With these steps you will avoid cases that generated file is incompatible with render or that transcoders generates malformed media file....

**Comment by Sami32** [comment]
@yesoos 
1) When you play the same movie from USB plugged on your TV, do you get subtitle displayed ?
If yes, then
2) From your TV, go in UMS directories where your movie is and go under TRANSCODE folder. From there select the folder with your movie name, and test [No transcoding] and [No transcoding] with subtitle. What happen ?

Just by curiousity, what is your TV model ? LG 65UF850V ?

**Comment by yesoos** [comment]
@ExSport 
I did create a small file with command from UMS (mencoder) and the stream works just fine from USB. This surely seems like something in network stack?

@Sami32 
1) I don't get subtitles displayed - maybe external are not supported in WebOS 2.0 (txt,srt files)
2) tested all possibilities no transcoding works fine, no transcoding with subtitles - subtitles do not show up, rest is problematic (buffering thingie)

It's LG 49UF7707

**Comment by Sami32** [comment]
@yesoos That was i was thinking...i suspected that.
First you need to learn how to do that with your TV from USB, because i saw in your log that some subtitles was correctly streamed by UMS.
So, it's look time to read your TV manual ;-)

**Comment by yesoos** [comment]
@Sami32 I use UMS to transcode with subtitles - I don't care which subtitles are supported by TV and which are not. The problem is that transcoding/network part is not working correctly. Also trying to provide some feedback to developers - so maybe the problem gets resolved.

P.S. it's 49UF7707

**Comment by yesoos** [comment]
Also no transcoding + subtitles work when subtitles are subrip. Still the problem with transcoding is there.

**Comment by SubJunk** [comment]
Closing this as it went stale. If anyone is still interested in this please reopen and I will work to resolve it.
