### ISSUE TITLE
No ISO or VOB Support on PS3 after installing 5.2.x

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#740]
@UniversalMediaServer/developers @SubJunk 

I'm creating this from [this forum thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3857) since it's been like this for a long time now and seems to be completely ignored by all developers.

I this done deliberately? If not, it seems to be a quite serious regression. Doesn't any of you guys have any idea of what could have caused this?

**Comment by SubJunk** [comment]
@Nadahar thanks for posting this. It's helpful to have good bug reports escalated to our issue tracker like this. I'll look into it.

**Comment by Nadahar** [comment]
After almost 3 years I assume that the "looking into" didn't bear fruits. It might have been fixed by #1287.

**Comment by SubJunk** [comment]
No, it was fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/0d81194d944a6d81156b6fcd252cbb8877217309 and I forgot to close the issue. The user confirmed the fix though.
