### ISSUE TITLE
File chooser dialog in Linux

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#741]
Actual file chooser dialog (when you choose files to play/playlist, etc.) is terrible in Linux (i aum using arch with Gnome 3.18). it is not intuitive like file chooser for GTK3 (for example it is terrible to find connected external HDD for example. many not experienced users will not find it).
It would be perfect, if they can look this:

https://developer.gnome.org/gtk3/stable/filechooser.png

**Comment by Nadahar** [comment]
@prescott66 Not that it helps much, but it's terrible under Windows as well. It's not really up to UMS, Java is providing the file chooser. I don't know if it's possible to tweak/find a better component for this, but I've been thinking of looking for it some times, but more pressing issues keep popping up.

**Comment by prescott66** [comment]
Yeah, but windows have different structure of directories

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk For anyone that has the time and urge, it seems like ```java.awt.FileDialog``` could be a better option than ```JFileChooser``` - although it's harder to work with, it's supposed to use the native file selection dialog.

**Comment by SubJunk** [comment]
That sounds like a good change

**Comment by SubJunk** [comment]
The upcoming v12 browser-based settings should fix this
