### ISSUE TITLE
Bad format in debug.log

### ISSUE THREAD

**Issue by taconaut** [UniversalMediaServer/UniversalMediaServer#744]
Lately it happened a few times that when opening the debug.log file by clicking the button from the traces tab, PSPad (my default editor associated with *.log files) showed the log as if it were a file in HEX format.

PSPad:
![pspad_log](https://cloud.githubusercontent.com/assets/275379/11444803/2cf53c76-9527-11e5-957d-d1429a84f56e.png)

Notepad++:
![notepad _log](https://cloud.githubusercontent.com/assets/275379/11444807/35f4a42e-9527-11e5-8b58-345bd18f8021.png)

These NUL values shouldn't be there and seem to confuse PSPad.

I think the issue happens when a second log file is being created, but am not really sure about it as I haven't found a way to consistently reproduce it.

**Comment by Nadahar** [comment]
Very strange. I haven't seen it. Truncating the file is done by logback, so it's a bit strange if we've caused that.

Do you have a custom logback configuration that split the log into multiple files?

**Comment by taconaut** [comment]
It's probably not exactly the same as the UMS one, but I'm only using a FileAppender (see [logback.xml](https://github.com/UniversalMediaServer/UniversalMediaServer/files/45903/logback.xml.txt)).
[Here](https://github.com/UniversalMediaServer/UniversalMediaServer/files/45904/debug.log_NUL.txt)'s the beginning of the log file containing those NUL, if it can be of any use.

**Comment by Nadahar** [comment]
@taconaut The linked logback.xml is identical to the current default UMS file.

**Comment by taconaut** [comment]
Ok, then we can be sure it's not related to a custom logback configuration.
I'll see if it happens again and if I can add some more info then.

**Comment by Nadahar** [comment]
Yes, as it is now there's really not a lot to go on.

**Comment by taconaut** [comment]
The path contained in the file I've attached is weird. `C:\Program Files (x86)\Jenkins\jobs\ums-mlx trunk (nightly)\workspace\core\src\main\external-resources\logback.xml` is my jenkins build from where I've never launch ums. Could unit tests be at cause?

**Comment by Nadahar** [comment]
Hmm... a lot of the tests do reset logback configuration... that could probably be something.

**Comment by Nadahar** [comment]
@taconaut I made ce175f255c4a252a0c2d50cc0d2f5ebf631c1145 yesterday. If fixes some potential synchronization issues with the cachelogger and the logging tests that could have brought strange results under rare circumstances. It shouldn't under normal circumstances though, since the unprotected calls were run from the same thread. But during testing, strange things might have occurred. 

I'd be great if you could report back if you ever see this bug again when this commit is included.

**Comment by taconaut** [comment]
Cheers, I'll let you know if I see this happening again (or not)

**Comment by Sami32** [comment]
@taconaut @SubJunk So, what happened ? No news good news :-)

**Comment by taconaut** [comment]
I didn't notice it again and as it isn't a big issue anyway, you can close it

**Comment by Nadahar** [comment]
It's likely that the concurrency bug fixed in ce175f255c4a252a0c2d50cc0d2f5ebf631c1145 was the culprit. If tests were run in parallel the bug would probably cause problems.

**Comment by Sami32** [comment]
@Nadahar Thanks for the information :-)
