### ISSUE TITLE
3D.ass subtitles not recognized

### ISSUE THREAD

**Issue by SuperDre** [UniversalMediaServer/UniversalMediaServer#745]
At the moment it seems that 3d.ass subtitles only work if the filename has the following specific 'tag':

Half OU versions: '3D-HalfOU' or '3D.HalfOU'
Half SBS versions: '3D-HalfSBS' or '3D.HalfSBS'

it won't work if you have 'Half-SBS' or 'Half-OU' (which is about how most files are named these days).
Just a few examples:
Avengers.Grimm.2015.1080p.3D.BluRay.Half-SBS.x264.DTS-HD.MA.5.1-RARBG.mkv
Alice.in.Wonderland.2010.1080p.3D.BluRay.Half-SBS.x264.DTS-HD.MA.5.1-RARBG.mkv
Jupiter.Ascending.2015.1080p.3D.BluRay.Half-SBS.x264.DTS-HD.MA.7.1-RARBG.mkv
Oz The Great and Powerful 3D 2013 1080p BluRay Half-OU DTS x264-HDMaNiAcS.mkv
Sin.City.A.Dame.to.Kill.For.2014.3D.1080p.BluRay.Half-OU.x264.DTS-HD.MA.5.1-RARBG.mkv

I would suggest to strip all the non digits and letters and then check for 'HalfOU', 'HOU', 'HSBS', 'HalfSBS' and maybe even '3D'

If you don't have 3D.ass subtitles, I can suggest you use the site http://subtitle3d.com/ or use the tool 'srt-2-3d-ass' (which is what I use), you don't need to have a 3D tv to test.

**Comment by SubJunk** [comment]
@SuperDre thanks for the feedback. It was intended to work as you suggested so I guess there's a bug, either @valib or I will look into it

**Comment by rarbg** [comment]
Hey :)
We always labeled them as Half-SBS or Half-OU
But ive seen other groups label them as HSBS and HOU
(\.| )(HalfOU|HOU|HSBS|HalfSBS|Half-SBS|Half-OU)(\.| ) < easy preg
or just \.3d\. as @SuperDre suggested

**Comment by SubJunk** [comment]
Cool to have you here @rarbg :)

Our current code for detecting 3D formats from filenames is:

```
if (upperCaseFileName.matches(".*[\\s\\.](H-|H|HALF-|HALF.)SBS[\\s\\.].*")) {
	LOGGER.debug("3D format HSBS detected for " + file.getName());
	media.setStereoscopy("half side by side (left eye first)");
} else if (upperCaseFileName.matches(".*[\\s\\.](H-|H|HALF-|HALF.)(OU|TB)[\\s\\.].*")) {
	LOGGER.debug("3D format HOU detected for " + file.getName());
	media.setStereoscopy("half top-bottom (left eye first)");
} else if (upperCaseFileName.matches(".*[\\s\\.]SBS[\\s\\.].*")) {
	if (media.getWidth() > 1920) {
		LOGGER.debug("3D format SBS detected for " + file.getName());
		media.setStereoscopy("side by side (left eye first)");
	} else {
		LOGGER.debug("3D format HSBS detected based on width for " + file.getName());
		media.setStereoscopy("half side by side (left eye first)");
	}
} else if (upperCaseFileName.matches(".*[\\s\\.](OU|TB)[\\s\\.].*")) {
	if (media.getHeight() > 1080) {
		LOGGER.debug("3D format OU detected for " + file.getName());
		media.setStereoscopy("top-bottom (left eye first)");
	} else {
		LOGGER.debug("3D format HOU detected based on height for " + file.getName());
		media.setStereoscopy("half top-bottom (left eye first)");
	}
}
```

which should be working but I need to test it with subtitles, I'll do that later

**Comment by Nadahar** [comment]
Is there any other way to recognize these files then by analyzing the filename? Is there e.g a header that could be parsed?

**Comment by SuperDre** [comment]
well, with .ass files one could check if the first 2 dialog lines start at the same time (or the first few pair), but for the rest there is no information in the header to actually tell it's a 3D subtitles..

**Comment by valib** [comment]
Can you download the last build http://universalmediaserver-ci.hopto.org:9999/job/ums%20trunk/lastBuild/net.pms$ums/artifact/net.pms/ums/5.3.2-SNAPSHOT/ums-5.3.2-SNAPSHOT.exe and try it?

**Comment by SuperDre** [comment]
Just tested the snapshot version in regard to 3d subtitles, and it seems to work now, tested 4 movies without changing their original names..
Thanx ;)
