### ISSUE TITLE
Samsung TV suddently unable to see Universal Media Server

### ISSUE THREAD

**Issue by rowdy1961** [UniversalMediaServer/UniversalMediaServer#753]
All of a sudden my Samsung TV cannot see the media server. This happened after the latest Java Update. Any ideas?

**Comment by Nadahar** [comment]
@rowdy1961 We'd need [the debug log] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556) to see what's happening, but we've had other problems with the versions after ```1.8.0_60```. It might be worth reverting to this version until we can figure out what's not playing ball with the latest Java versions.

**Comment by Sami32** [comment]
@SubJunk Since the latest version of Java upgraded, and i guess most of users have automatic upgrade, could this issue stay open ? He didn't give log in 7 months so no news good news, right ?
