### ISSUE TITLE
Play to another renderer web interface / Edge browser issue

### ISSUE THREAD

**Issue by Iamtk421** [UniversalMediaServer/UniversalMediaServer#759]
UMS Version 6.0.0-a1.

When attempting to use MS Edge to play videos to my tv via UMP's web interface, after clicking on 'play to another renderer' MS Edge becomes entirely unresponsive.
Using other browsers (i.e. chrome) works fine.

I've not attached the UMS log/debug files as I don't imagine they'll help in this case, but if need be I can upload them.

**Comment by Nadahar** [comment]
It's not up to me, but I'm not really sure if we care about Edge - it's a lousy browser that I bet will be forgotten very quickly.

**Comment by Iamtk421** [comment]
Yea, well it's not really something I'm concerned about as I don't really use Edge/the web interface very often, but I thought I'd just report it anyway. Whether the fault lies with the UMS implementation or Edge not working as it should, it is an issue and may cause some people problems.

**Comment by SubJunk** [comment]
This is fixed
