### ISSUE TITLE
Service wrapper for Windows doesn't work with 64 bit JVM

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#767]
[This case](http://universalmediaserver.com/forum/viewtopic.php?p=21782&sid=264739a25ce4d97aee6927032d366d0a#p21782) came up. Apparently the `wrapper.exe` we use only works on 32 bit JVM. 32 bits is getting rarer and rarer these days, so this is less than ideal.

I dug a little bit and found out that [Tanuki Software doesn't distribute a 64 bit version of the "community edition" of the wrapper](http://wrapper.tanukisoftware.com/doc/english/download.jsp#downloadNote1). They obviously want people to pay to use the one version that's generally needed. But, I've also found [this](http://www.krenger.ch/blog/java-service-wrapper-3-5-27-for-windows-x64/).

All in all, this needs further investigation. We probably need to install both the 32 bit and 64 bit version of the wrapper, and then determine which one to launch based on the JVM used.

**Comment by ErdnussFlipS** [comment]
Firsty die service option can be grayed out with a hint, that service is not available for 64 bit system (only for 32 bit system).

**Comment by Nadahar** [comment]
From what I understand, there's no interest in running as a service, so this will probably never be fixed.

**Comment by GatesDA** [comment]
Unless there's another way to have UMS run without any users logged in, there's still interest.

It should at least be disabled when it won't work.

**Comment by Nadahar** [comment]
@GatesDA I meant interest from the other developers. I'm fully aware that there's interest from the users..

**Comment by SubJunk** [comment]
It's definitely something I hope will be looked into

**Comment by AndrasJanurik** [comment]
V11.2.0 on a 64 bit windows with the included JRE 64 bit still creates the windows service with wrapper.exe (32 bit). Therefore the service does not start.
Wrapper.log:

```
WrapperManager: ERROR - Unable to load the Wrapper's native library 'wrapper.dll'.
WrapperManager:         The file is located on the path at the following location but
WrapperManager:         could not be loaded:
WrapperManager:           C:\Program Files (x86)\Universal Media Server\win32\service\wrapper.dll
WrapperManager:         Please verify that the file is both readable and executable by the
WrapperManager:         current user and that the file has not been corrupted in any way.
WrapperManager:         One common cause of this problem is running a 32-bit version
WrapperManager:         of the Wrapper with a 64-bit version of Java, or vica versa.
WrapperManager:         This is a 64-bit JVM.
WrapperManager:         Reported cause:
WrapperManager:           C:\Program Files (x86)\Universal Media Server\win32\service\wrapper.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
```
Replacing wrapper.exe and .dll with the included -x64 versions solves the problem.
Maybe the service should be created with wrapper-x64.exe.
