### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#778]
I just noticed that an analytics package I use for websites, Piwik, has a Java API at https://github.com/piwik/piwik-java-tracker

We have discussed gathering data before and decided against it by default. It may be worth having that conversation again given the direction computing has gone in since that conversation.

As with last time, I suggest adding an option to the first-run wizard to allow users to opt-in to the anonymous analytics. It seems that most programs either put that option in the installer or the wizard.

I'm very interested to know what the most common renderers are, since we can guess based on forum users but that's misleading since it will always be skewed to seem like the ones we have the most problems with are the most used. It seems to me we could benefit greatly from knowing which renderers to focus on the most.

We can scramble filenames before they send, along with filesize and any other potentially identifying info, so there's no risk to users.

Thoughts?

**Comment by Nadahar** [comment]
Generally I think there are so many bugs, incomplete implementations and other shortcomings that I think this should have priority until that situation has changed, instead of constantly doing new things and ignoring all the issues. I think all the current Github issues should be deal with and rejected or solved to name one thing. I suspect a lot of the flaws that is in the current version are to be found there. Then there's all the Java warnings and FindBugs, and all the warnings from Threadsafe. I simply think solving all those things, getting the "head above the water" is way more important than something like this.

I'm also skeptical of unneeded gathering of data. I'm generally weary of software that collects data, so just being presented with such an option (especially if it's opt out) make me dislike the software unless there's a very good reason.

 Another factor is that what renderers are most common probably depends very much on what renderers work well with UMS. Most people will test software for their particular need and then move on if it's not satisfactory, so such statistics could easily end up giving focus to those that need it the least, those that already work well.

**Comment by SubJunk** [comment]
@Nadahar I agree we should focus on bugfixes, almost all of what I do is bugfixing and other maintenance things, other than a few features to try to keep the program relevant. I wouldn't spend much time on this. One of the other projects I work on has some cool integration set up so basically if you want an event recorded, you do "new analytics("description of event")" and the rest is automatic.

I agree about being opt-out, although it would be nice from a data perspective I think it would need to be out-in.

It can easily be set up to be able to filter by unique installations, so it would be possible to view how many people have installed it, failed and uninstalled it. I agree it's probably happening and we have no way of knowing about it because such users won't tell anyone about it, we're just on their list of servers to try and we got crossed off the list.

**Comment by skeptical** [comment]
I'm with @Nadahar on this: I automatically dislike software that wants to send data home, especially if I'm just trying it out and have no idea whether I'll keep it (which is precisely the group @SubJunk is most interested in targeting).  As stated before, we could make better use of the data we already have, for instance archive all logs submitted to the forum in a searchable way, and mine it for general statistics too.  To me this would be more in keeping with the (relatively higher) ethical standards of open source.

**Comment by Nadahar** [comment]
@SubJunk @skeptical An idea could be to create an online "collection" of debug files and add that as an option to ```DbgPacker```. The server could then submit the files to a database with full text search capabilities. Ideally an unique ID would exist for every installation/environment, and one for every submit. DbgPacker should return an id or link to that submission that the user could post either on the forum, here on GitHub or elsewhere.

We could then choose if the debug files should be public or require some kind of authentication (I'm a bit worried about all the information that is in the debug files as it is, with file names and user names). 

All I would need is some kind of SQL query made accessible for that database, ideally the submitted link would open a query view of the files with that "submit ID".

Having a web based access to that database would enable things like syntax highlighting, filtering and other ways that we could think of to make it easier to process the files.

We could also mine those debug files for various information, to find how to prioritize our efforts. I think that improve our chances of actually getting some useful priorities out of it.

But, it involves quite a lot of work on that online server, and I'm unsure if the reward would be worth the effort.

**Comment by SubJunk** [comment]
Good suggestions guys, it would probably be fairly easy for me to write a forum mod to pull contents of debug logs into a SQL database when they're uploaded. Sounds like a fun thing to do too

**Comment by DeFlanko** [comment]
I for one would be very interested to see the data that returns and find
any commonalities.

**Comment by Optimusprimeums** [comment]
+1 for the forum mod, anything that makes it easier to find log files.

**Comment by WolfganP** [comment]
I think that if you explain what's the purpose and what anonymized data is sent and then share the stats back to the community via regular posts or live pages; no user would have any problem with it.
ie I use alt firmware Tomato on my router, read the purpose of the data sent (http://tomato.groov.pl/?page_id=314) and happily contribute info back to the community stats page (http://anon.groov.pl/)
