### ISSUE TITLE
Subtitle positioning mencoder vs ffmpeg

### ISSUE THREAD

**Issue by squadjot** [UniversalMediaServer/UniversalMediaServer#781]
When a movie has black bars, FFMPEG seems to put subtitles inside the video area, whereas Mencoder puts the subtitles in the "outside" area (in the black bar)

I think the subtitles should always be in the black area if possible. The only reason i can see to keep subs inside the picture area, would be to save bandwidth, so maybe make it optional for the user?
 
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5878

**Comment by valib** [comment]
@squadjot thanks for the input. Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/762f3b1e4aaaa60481a435a32deac4f4efa8c32e
