### ISSUE TITLE
On Linux filenames with questionmarks could not be parsed

### ISSUE THREAD

**Issue by pstadt** [UniversalMediaServer/UniversalMediaServer#782]
Hi 

I just started with UMS 5.3.1 on a CentOS 6.7 box.
I ran into the problem with ? aka questionmarks in filenames.

For example:
```
INFO  21:22:49.698 [New I/O worker #3] The file /music/Pet Shop Boys/PopArt: The Hits (disc 2: Art)/05-Can You Forgive Her?.mp3 could not be parsed. It will be hidden
INFO  21:23:06.885 [New I/O worker #3] The file /music/Pet Shop Boys/PopArt: The Hits (disc 1: Pop)/04-What Have I Done to Deserve This?.mp3 could not be parsed. It will be hidden
```
Renaming the file to an obscure unicode questionmark "？" (U+FF1F) works around the problem:
```
mv -i 04-What\ Have\ I\ Done\ to\ Deserve\ This\?.mp3 04-What\ Have\ I\ Done\ to\ Deserve\ This"？".mp3
```
The file can be parsed, is no longer hidden and can be seen on the clients.

There is the same effect with wildcard *:
```
INFO  21:50:53.964 [New I/O worker #7] The file /music/CDrip/2K/***k the Millennium/01-***k the Millennium.mp3 could not be parsed. It will be hidden
INFO  21:50:53.975 [New I/O worker #7] The file /music/CDrip/2K/***k the Millennium/02-Acid Brass-What Time Is Love？ (version K) - The Williams Fairey Brass Band.mp3 could not be parsed. It will be hidden
```
Since for file 02- the questionmark is workarounded and the parsing still fails this looks like the problem is caused by the * in the directory name.

**Comment by pstadt** [comment]
This looks like a mediainfo/libzen problem.

test transcript:
```
Here is an simple transcript of a test:
[mi]$ convert -size 100x100 xc:white canvas.jpg
[mi]$ mediainfo canvas.jpg 
General
Complete name : canvas.jpg
Format : JPEG
File size : 203 Bytes

Image
Format : JPEG
Width : 100 pixels
Height : 100 pixels
Color space : Y
Bit depth : 8 bits
Compression mode : Lossy
Stream size : 203 Bytes (100%)

[mi]$ cp canvas.jpg "canvas?.jpg"
[mi]$ mediainfo "canvas?.jpg"

[mi]$ echo $?
1
```
https://sourceforge.net/p/mediainfo/bugs/950/

**Comment by Nadahar** [comment]
@pstadt I suspected that as well, but haven't gotten around to testing it yet. That said, I can't really see why you'd want to use those characters in file names, it can probably bring all kinds of trouble. I violates the [POSIX file name convention] (https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations) that very strictly defines ```A–Z a–z 0–9 . _ -``` as the only valid characters.

**Comment by pstadt** [comment]
@Nadahar Welcome to 2016. :grinning:
We have Unicode accepted on every modern platform.

If you have a look at the libzen code, it checks if the filename contains a * or a ? and then returns "not existant". Wildcards are resolved on shell level, if they exist in a filename inside the library he should just test for the name, not deny them because they exist. If the ? is an unresolved wildcard from shell level the kernel does not try to expand it, the check for existance will just fail.

**Comment by Nadahar** [comment]
@pstadt Yes, but Unicode and wildcards aren't really related. I'm just saying that a lot of software will assume that wildcards aren't part of the file name, so it's much easier to just avoid them.

**Comment by pstadt** [comment]
@Nadahar nearly every software on my system works with these files. Looks like the problem in mediainfo/libzen comes from its windows origin.
