### ISSUE TITLE
Please dump sourceforge

### ISSUE THREAD

**Issue by robertbaker** [UniversalMediaServer/UniversalMediaServer#784]
Sourceforge for downloads are slow, tried several mirrors and it's not my ISP. The site is clunky, etc, etc. There are alternatives that are more user friendly. https://bintray.com

**Comment by SubJunk** [comment]
@robertbaker we like SourceForge and they have been really good to this project. We remain open to looking at options but it would have to be really good. Not sure if bintray is the right one given that the free accounts don't have historical statistics.
