### ISSUE TITLE
Mediainfo.dll not found upon clean install of 6.0.0.b2 over 5.40

### ISSUE THREAD

**Issue by abeklagsbrun** [UniversalMediaServer/UniversalMediaServer#789]
As the title says, the installer throws an error that mediaindo.dll cannot be found when 6.0.0.b2 is clean installed over 5.40.

**Comment by SubJunk** [comment]
@abeklagsbrun which operating system?

**Comment by abeklagsbrun** [comment]
Sorry. OS is Windows 10 x64 latwest insider build (redstone 1)

**Comment by SubJunk** [comment]
Can you upload some logs in TRACE mode please so we can see what's happening? Can you try 5.5.0 too?

**Comment by Nadahar** [comment]
This isn't relevant anymore, in addition to the lack of feedback.
