### ISSUE TITLE
Error when loading a folder with folder names contained in square brackets

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#791]
When entering a folder containing a folder called `[name]` for example, Netty gives us:

`java.lang.StringIndexOutOfBoundsException: String index out of range: 1`

I guess it interprets that folder name as a regex or something. Reproduced on a few renderers.

Names like `[name]a` work.

**Comment by Sami32** [comment]
Just for have an easy link to it next time i check here
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/497

**Comment by valib** [comment]
@SubJunk I can't reproduce that bug.

**Comment by SubJunk** [comment]
This bug was fixed by @Nadahar a while back

**Comment by Sami32** [comment]
@valib @SubJunk Thanks for the cleaning ;-)
Yesterday i saw that so many issues are already solved or don't provide any logs to find the problem.
