### ISSUE TITLE
On initialization: Failed to create a selector. 

### ISSUE THREAD

**Issue by sasilini** [UniversalMediaServer/UniversalMediaServer#792]
On Win10 64
UMS failed to share - updated with beta version then again with 5.5
in logs this occurs..
17:08:57 ERROR A serious error occurred during Universal Media Server initialization: Failed to create a selector.

**Comment by Nadahar** [comment]
@sasilini I answered in your thread, it's most likely a network configuration error on your computer.

**Comment by sasilini** [comment]
Thank you yes it was
Used Fix network
Some spyware must have done this

**Comment by Nadahar** [comment]
@sasilini Ok, glad it's resolved.
