### ISSUE TITLE
Unsafe use of Object.clone()

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#795]
@UniversalMediaServer/developers I just stumbled across the use of `clone()` in [`DLNAResource`](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/dlna/DLNAResource.java#L1718) and `DLNAMediaInfo`. The same may apply to other classes.

I realize that this probably is inherited from PMS, but it's a very unsafe practice. Java's `.clone()` should not be used except on very simple classes (classes that has no classes as fields). `.clone()` performs a ["shallow copy"](http://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy), meaning that any class objects are shared between the original and the clone. I really doubt that is the intention or is indeed safe, when you manipulate any class object you also manipulate that of it's sibling. To make it worse, the default synchronization object (the class) is not shared, but the objects are - so this renders any synchronization locks invalid.

To safely clone a class, all mutable class objects must also be cloned, and they must again clone all their mutable class objects recursively until only primitives are left, which is basically a deep clone. This isn't done here.

It's hard to say what the consequences of this are, but it's bound to create bugs and "weird behaviour".

**Comment by valib** [comment]
@Nadahar I think that clone is implemented well. There are overriden methods clone() in those classes whose perform deep clone as I understand that.

**Comment by Nadahar** [comment]
@valib Maybe I expressed myself badly, I know they are overridden, but they also call ```super()``` seemingly hoping that there's where the magic happens. That's why I referenced ```Object.clone()```, ```super()``` ends up there. But, look at the override DLNAResource  in for example:
```java
	@Override
	protected DLNAResource clone() {
		DLNAResource o = null;
		try {
			o = (DLNAResource) super.clone();
			o.setId(null);

			// Clear the cached display name and suffix
			o.displayName = null;
			o.nameSuffix = "";
			// Make sure clones (typically #--TRANSCODE--# folder files)
			// have the option to respond to resolve events
			o.resolved = false;

			if (media != null) {
				o.media = (DLNAMediaInfo) media.clone();
			}
		} catch (CloneNotSupportedException e) {
			LOGGER.error(null, e);
		}

		return o;
	}
```
The only class instance object that's cloned is ```DLNAMediaInfo```, but if you look at the declarations there are loads of non primitives declared. All the rest of them will be shared between the clone and the original.

**Comment by Nadahar** [comment]
To try to create some interest for this, here's the Javadoc for ```Object.clone()```

>Creates and returns a copy of this object.  The precise meaning
of "copy" may depend on the class of the object. The general
intent is that, for any object ```x```, the expression:

> ```x.clone() != x```

> will be true, and that the expression:

> ```x.clone().getClass() == x.getClass()```

> will be ```true```, but these are not absolute requirements. While it is typically the case that:

> ```
x.clone().equals(x)
```

> will be ```true```, this is not an absolute requirement.

> By convention, the returned object should be obtained by calling ```super.clone```.  If a class and all of its superclasses (except ```Object```) obey this convention, it will be the case that ```x.clone().getClass() == x.getClass()```.

> By convention, the object returned by this method should be independent of this object (which is being cloned).  To achieve this independence, it may be necessary to modify one or more fields of the object returned by ```super.clone``` before returning it.  Typically, this means **copying any mutable objects** that comprise the internal "deep structure" of the object being cloned and replacing the references to these objects with references to the copies.  If a class **contains only primitive fields or references to immutable objects**, then it is usually the case that no fields in the object returned by ```super.clone``` need to be modified.

> The method ```clone``` for class ```Object``` performs a specific cloning operation. First, if the class of this object does not implement the interface ```Cloneable```, then a ```CloneNotSupportedException``` is thrown. Note that all arrays are considered to implement the interface ```Cloneable``` and that the return type of the ```clone``` method of an array type ```T[]```
is ```T[]``` where T is any reference or primitive type. Otherwise, this method creates a new instance of the class of this object and initializes all its fields with exactly the contents of the corresponding fields of this object, as if by assignment; the contents of the fields are not themselves cloned. Thus, this method performs a "shallow copy" of this object, not a "deep copy" operation.

> The class ```Object``` does not itself implement the interface ```Cloneable```, so calling the ```clone``` method on an object whose class is ```Object``` will result in throwing an exception at run time.

> @return     a clone of this instance.
@exception  CloneNotSupportedException  if the object's class does not
			 support the ```Cloneable``` interface. Subclasses
			 that override the ```clone``` method can also
			 throw this exception to indicate that an instance cannot
			 be cloned.
> @see java.lang.Cloneable

**Comment by valib** [comment]
@Nadahar i am aware of it. But as I stated in my previous comment we use clone only to fill up the virtual folders. The changes we make is to change the ```ID```, ```displayName```and```nameSuffix``` whose are the immutable strings and the ```media``` for which is made a :"deep copy" operation. The only problem which I see and could be checked is the setting of the integer  ```resolved``` variable.

**Comment by Nadahar** [comment]
Integers are safe, so that shouldn't be a problem. The problem however, isn't the variables that's changed during clone, it's all those that aren't. Those variables/fields that is references (everything that's not a primitive, who's type is a class), will point to the same object as that of the "original". When these cloned objects are later used (by other parts of UMS that doesn't know if it's a clone or not), the problems start.

**Comment by valib** [comment]
@Nadahar sorry I wrote integer but I change it later on to boolean. Anyway I am not against the changes which could prevent any problems I just want to keep it as simple as it could be.

**Comment by Nadahar** [comment]
boolean is safe too. I'm not actually suggestion a change, I don't know how if could be solved without doing a big job tracking down every object in those classes. At this stage I'm just stating that this is a problem. The question is if it would be easier to create a "copy" method that created a new instance and then copied those values that need to be copied than to make ```clone()``` safe.

**Comment by valib** [comment]
@Nadahar this code is working for several years without any complains of users so why we should rewrite it? I know that it is not 100% safe but for the purpose it is used I think it is safe onough.

**Comment by Nadahar** [comment]
That's the problem with such bugs, you will never, or almost never, be able to track it back to the cause. There is no such thing as "safe enough", it's either safe or unsafe.

**Comment by valib** [comment]
@Nadahar I don't want to start the endless discussion what is safe and what is not because we could end discussed that not only the Java but the OS is not safe enough. :-) Please feel free to make any changes to the clone() implementation to improve it because I am not skilled enough to help you.

**Comment by Nadahar** [comment]
@valib I don't mean safe in that sense. I just mean that when it is done this way, it create the possibility of memory/state/variable corruption and unpredictable sideeffects. It's not how its supposed to be done, and it doesn't take much imagination to see how it could go wrong.

If it actually goes wrong is hard to judge, but we're basicly relying on "luck" and probabilities rather than being "safe" that it can't go wrong.

I have to many things I have to do, so I won't dive into this now. I fear it's a big job to do "safely", but to be sure about that all the class fields/objects must be studied. I think the issue should stay open in any case so this isn't forgotten.

**Comment by Nadahar** [comment]
Consensus is to ignore this.
