### ISSUE TITLE
Commas in the InfoDB break things

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#799]
If there's an episode title or movie name that has commas in it, it throws everything off since the list is comma-delimited. We should probably escape commas in the content to prevent that. @SharkHunter is that an approach you're happy with?

Also please look at https://github.com/UniversalMediaServer/UniversalMediaServer/commit/9bbe9a6c107adbf02910bb88c0e71fd2eb1f1dad to see if you're happy with that @SharkHunter

**Comment by Nadahar** [comment]
@SubJunk What list is comma separated? 

I've just come across another bug concerning commas (probably unrelated) in folder names, it leeds to an NPE in ```MediaMonitor.scanFile()``` in line 99:
```java
		for (File f : files) {
``` 
because ```files``` is null as it comes from ```f.listFiles()``` and since ```f``` is "escaped" with ```&comma;``` the folder isn't found. 

I don't know if this bug has to do with the recent changes "fully played" changes or if it's been there all the time, but I must say that these comma separated config strings really is a terrible idea leading to "hacks" like this.

**Comment by Nadahar** [comment]
Never mind the above NPE (I still think comma separated strings are bad), I've fixed it in fcffd793c047a8b77f350b7e7da5dc04ba5386ee.

**Comment by SubJunk** [comment]
I may have fixed this bug in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/94b43c2346634b257d8eefb51d29125cb8820767 but haven't tested it yet

**Comment by Nadahar** [comment]
@SubJunk Is that what you want? Javadoc for ```StringEscapeUtils.escapeCsv``` states:

```
Returns a String value for a CSV column enclosed in double quotes, if required.

If the value contains a comma, newline or double quote, then the String value is returned enclosed in double quotes.

Any double quote characters in the value are escaped with another double quote.

If the value does not contain a comma, newline or double quote, then the String value is returned unchanged.
see Wikipedia and RFC 4180.Parameters:input the input CSV column String, may be nullReturns:the input String, enclosed in double quotes if the value contains a comma, newline or double quote, null if null string input
```
The comma will still be there, just wrapped in double quotes. I'm not sure how that can help if the string is split on comma.

**Comment by SubJunk** [comment]
Yeah it's not the right choice. I didn't have much time so just threw it in there meaning to come back to it if it didn't work :)

**Comment by Nadahar** [comment]
What you have to do is replace commas with something else, and then replace it back. 

I don't know what's stored in this "filedb" though, and I don't know why this is used when we have a proper database in use already.

**Comment by SubJunk** [comment]
Another common option for CSV files is to escape commas

**Comment by Nadahar** [comment]
Yes, but this isn't CSV...? It's out code that uses 
```java
				String tmp[] = str.split(sep);
				if (tmp.length < minCnt) {
					continue;
				}
				db.put(tmp[0], handler.create(tmp));
```
No amount of escaping will do anything to that, if there's a comma it will split.

**Comment by SubJunk** [comment]
Actually the method used by this method is correct, strings containing commas in CSVs should be enclosed in double quotes, the issue as you've now seen is that we aren't unwrapping the CSV format in a standard way.

**Comment by Nadahar** [comment]
I still don't get it, where does CSV come in? Is this a CSV file, or supposed to be one? If so, a much more sophisticated parsing is needed.

**Comment by SubJunk** [comment]
This is fixed now.

By "CSV" I just mean a comma-delimited file

**Comment by Nadahar** [comment]
> By "CSV" I just mean a comma-delimited file

Yes, but there's a big difference. CSV is a defined format that repects double quoting (and probably some kind of escaping), this isn't - it's just a file with comma separated strings that doesn't care about quotes or escapes.

**Comment by SubJunk** [comment]
Well now we support quotes for that file so it's closer to CSV but call it whatever you want

**Comment by Nadahar** [comment]
@SubJunk How does it handle quotes now then? Same problem or do they have to be escaped somehow?

**Comment by SubJunk** [comment]
https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringEscapeUtils.html#escapeCsv(java.lang.String)
