### ISSUE TITLE
I can't play 4K video

### ISSUE THREAD

**Issue by aminliranzo** [UniversalMediaServer/UniversalMediaServer#811]
Hello, I test my Smart tv with usb and Works fine, but when I try by the media server don't, and by the webserver I can't either. See the error attached.

Can I enable some option for share only, without analyse the file, because my Smart TV support the file format (MKV 4k). Thanks.
![error](https://cloud.githubusercontent.com/assets/16962425/12684220/0242b046-c694-11e5-8023-e8eeb638a6b1.jpg)

**Comment by SubJunk** [comment]
By default, UMS converts 4k to 1080p, so we will need to add support for 4k on your TV profile. Please provide trace logs http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by WolfganP** [comment]
Did you try the "No Transcoding" or "TsMuxer" alternate entries in the TRANSCODE folder?

**Comment by Sami32** [comment]
@SubJunk We can close it, because without log...

**Comment by MitchelFunes** [comment]
Doesn anyone use Universal Media Server?

**Comment by Nadahar** [comment]
@MitchelFunes What do you mean? I doubt there's very many using 4K video with UMS, and the reason nothing happened here is that we were waiting for the debug files that never came.
