### ISSUE TITLE
ZenHub

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#812]
This is probably overkill but I'm interested to try it out even if we barely use it, any objections? https://www.zenhub.io/

**Comment by Nadahar** [comment]
@SubJunk It's not entirely clear to me what it actually does (can't stand to read "mobile" pages where I have to scroll for every other sentence), but I'm all for trying anything that gives better functionality. If it doesn't bring us anything we like, we can just abandon it.

**Comment by Optimusprimeums** [comment]
I like it, and agree with @Nadahar

**Comment by SubJunk** [comment]
I just enabled it, but it relies on browser plugins so if you want to see it you have to install it too

**Comment by Sami32** [comment]
@SubJunk Cool, i didn't know about that. Finally, did you use it ?
Can we close this issue  without offending you ?

**Comment by Nadahar** [comment]
It's still activated for this repo, but it doesn't seem like it's ever been used. It shouldn't need to be an open issue in any case.
