### ISSUE TITLE
WEB.conf defaults

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#816]
The [default `WEB.conf`](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/17da2051a089e3e61f56b697c465a2d9e3816c8b/src/main/external-resources/WEB.conf) is configured with several strange defaults that hardly seems relevant for most people.

It can be confusing for people to understand where those media come from and why. Why do we have these as defaults?

Looking through them, the first one has pictures of japanese girls with very little clothes, the second has what seems to me like random pictures from Taipei. Further there's random pictures of food, more completely random pictures, a broken link, a couple of (broken?) French TV channels and some webcams pictures from Shanghai harbour. The only ones that work for me are the picture links and some of the TED feeds, the rest appears to be broken.

**Comment by skeptical** [comment]
@Nadahar agree, this hasn't been updated since ancient times.

**Comment by Nadahar** [comment]
I guess the question is: Should we come up with new default or just remove them?

**Comment by SubJunk** [comment]
New defaults could be good. We could also make a GUI for adding/removing feeds.

**Comment by WolfganP** [comment]
To be honest, I don't think so many people deals with web streams to dedicate resources to implement a GUI. But an intermediate good step would be to have a button to open web.conf directly from the UMS native / web UI for edition? At the same time maybe document the functions better?
As discussed in some other thread about anonymized analytics, this may be a target for getting stats on actual usage...

**Comment by Nadahar** [comment]
@SubJunk I agree with @WolfganP about the GUI, I'm not sure it's worth it or that it's something we should prioritize, but allowing the file to be edited shouldn't be too much hassle. The documentation is probably the most important part, but as always the problem is that somebody has to write it.

About analytics, my first worry is as said before the alienating of many users this will lead to, but after that what worries me next is how that statistics is used.

Most statistics is used in a dumb manner in my optinion (I'm talking about governments, corporations etc.), in that it's used for "short-term optimization". I believe that "short-term optimization" often equals long-term disaster. If statistics is going to be useful, it must be used in an intelligent manner and one can't just jump to simple cause-effect conclutions. However, using it in an intelligent manner makes it much more difficult to use, so this is usually not the case.

To translate this to UMS, a typical "short-term optimization" way of using it is to prioritize those things that is most used and phase out or ignore the things that's only used by a few. A more intelligent approach would be to ask: Why are these things used a lot and others just a little. In many cases, the likely answer is: The things that are used a lot is used because they work well and vice versa. The result of the short-term/dumb application of statistics is therefore that priority is given to the things that already work well, making changes that isn't needed and might lead to it becoming worse. At the same time the areas that really need attention (and thus isn't much used) will be ignored or phased out. The result is an ever declining product that eventually will become so narrow that it becomes irrelevant. The problem is that the statistics doesn't show WHY something is used or not, if only shows IF. That information is actually useless without the why, but it's so tempting to interpret it as some kind of truth in itself, "that's just how the interest is distributed among the users" which is obviously false if you think about it.

This is happening with a lot of software today already, and we've all seen it. Software that initially was promising but then starts to drop everything that's actually useful and just focuses on reinventing a few things that didn't need reinventing. When I see this, I know what has happened and I know it's time to start looking at alternatives.

I don't want UMS to go down the same route. I believe it is much better that the team discusses what should and should not be a part of the software, and then strive to make everything that's part of it work as good as possible. The usage pattern will be a result of this process.

**Comment by WolfganP** [comment]
My take is that if you're honest on:
- what info you will collect anonymously (ie UMS version, OS & Java platform, used renderers, counters on features -ie webstreams, languages, new media folder, ...-), 
- describe how it will help the project (collect stats on features and platforms to concentrate development on most popular ones, uptake on updates, ...) and 
- allows disabling it (for the extremely paranoid) after explaining how the anonymizing works (ie ID constructed with a hash of X, Y, Z); 

then I don't think it will be a set back from anybody.

As a working project example: http://tomato.groov.pl/?page_id=314 and http://anon.groov.pl/

**Comment by Nadahar** [comment]
@WolfganP I disagree, as soon as I have to opt out of something like this I react negatively. If you have to opt in, hardly noone will use it.

But, your second point completely ignores my above explanation, and confirms that your idea of usage is what I consider to be dumb and contraproductive. Do you really think a product becomes better by focusing on the things it already does well and ignoring those it doesn't do well?

**Comment by WolfganP** [comment]
Data and stats don't (almost) ever hurt, is the decision you take with them what may have unintended consequences.
And I DO think products get better by taking informed decisions, mostly when resources (ie developers' time) is finite.

**Comment by skeptical** [comment]
As noted previously I'm more in the '[Lies, damned lies, and statistics](https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics)' school of thought.  The problem with statistics is that they focus on numbers, and numbers become hypnotic after a while.

**Comment by Nadahar** [comment]
I'm completely in line with @skeptical on this, I believe the unintelligent application of data is a major contributor to much misery in today's society. As explained above, to no avail it seems, the statistics doesn't say anything about WHY, and that's its biggest problem. That is left to the interpretor, and this is where it fails most of the time.

The truth hurts, but the fact is that without the knowledge about cause and effect, the numbers are useless. Since we seem to have a tendency to be hypnotized by the numbers by thinking "These numbers represent great knowledge, I must be able to utilize this somehow" I suppose it's tempting to jump to simple conclusions about cause and effect. It's like we have an inner wish to make the data applicable, so we silence the skeptical voices inside and grab the simplified scenarios with both hands. Sadly, wishing it was simple doesn't make it true, and the result is massive "abuse" of statistics as the example I described above about software development where you risk putting your resources where they are least needed, ignoring where they are most needed.

I've always preferred reason over wishful thinking, and that's what this boils down to for me. Even though there are some things you can objectively learn, there are so many possibilities for misinterpretations of the other data you receive that I believe better results are achieved by not using statistics in many cases, like finding problem areas in software development.

**Comment by SubJunk** [comment]
These are all good points. I think that being aware of the pitfalls of over-reliance on statistics can emancipate us from their hypnotic powers. Gathering them doesn't mean we have to look at them a lot or even draw conclusions based on them, but it can mean that when we aren't sure about a decision using pure logic, we can check the statistics to get a more complete picture and be more grounded in reality.

Personally I have always developed UMS and PMS for myself - when I use the program I'm often struck with an idea of how it could be better, and that's usually the next feature I implement or bug I fix. So from that selfish perspective I don't think it will make much difference to me what statistics say; even if I'm the only one who wants a feature, or I'm the only one affected by a bug, I'll fix it and that's probably my priority. I expect most of us are like that.

However there are times when I'm content with the program and look for something to do based on reports or requests on the forum, and statistics can be useful in verifying the urgency or validity of what they said on the forum, amongst other uses.

**Comment by Nadahar** [comment]
The basic concept is still that you're thinking that it can be useful for prioritizing while my claim is that the usage statistics might be the opposite of what you should look at then. Simplified, I think it's reasonable to expect that those that use the software are those it works reasonably well for. If that argument is accepted, then it follows that this user group or usage pattern is what needs the least attention. The things you should look at are probably those things nobody or very few use, but that could also be because there's no need for that. I quickly end up realizing that usage statistics can't really tell me anything interesting about in which way to take it. A survey would be a little bit more relevant, but surveys are also subject to major error sources. First, your userbase is probably already filtered as a result of what work and what doesn't. Second, a survey's results will to a big degree depend on how you ask the questions.

I have the impression that what you say about "developing for yourself" is mostly the case for you guys, and often the case in OS development in general. I am just the opposite. I don't actually use UMS myself (even though it was originally the plan, there are so many things that doesn't work or that is missing that I've seen no point installing it on a server). My goal is simply to make it work as good as possible for as many as possible, to have general solutions. I often dislike when someone want to force something through simply because it fits their need regardless of the consequences for other people with different needs or use pattern. The difference in approach also goes a long way in explaining why we see the things we do differently.

**Comment by DeFlanko** [comment]
Linking #856 as a possible WEB.conf revision conversation starter?

**Comment by SubJunk** [comment]
Closing this in favour of https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1448 because that is linked to my recent work on it - we are focusing on this functionality for v8.0.0
