### ISSUE TITLE
Issues playing files from "Renderer panel"

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#818]
I've had issues with the same previously, but when I'm testing right now it works for me. I've been trying to search previous issues and pull requests for anything related, but haven't found it (although I think I remember seeing something about this once).

I'm creating this issue hoping it's not a duplicate. There's a user having this issue now, reproducable (for him). I'm guessing @skeptical is the man for the job. Debug files can be found in [this post](http://www.universalmediaserver.com/forum/viewtopic.php?p=22855#p22855).

Here are what seems to be the essence:

``` logtalk
DEBUG 2016-02-01 16:58:27.752 [AWT-EventQueue-0] net.pms.network.UPNPControl Action failed: Error: Illegal MIME-type (HTTP response was: 500 Internal Server Error)
DEBUG 2016-02-01 16:58:27.752 [AWT-EventQueue-0] net.pms.network.UPNPControl Sending upnp AVTransport.Play [Speed, 1] to NICK-TV[0]
DEBUG 2016-02-01 16:58:27.762 [AWT-EventQueue-0] net.pms.network.UPNPControl Action failed: Error: Transition not available (HTTP response was: 500 Internal Server Error)
```

**Comment by Nadahar** [comment]
About the DLNA guidelines - these are free for anyone to download but not share. Downloading them requires registration. You can download them by [filling out the form here] (http://www.dlna.org/guidelines/).

**Comment by skeptical** [comment]
@Nadahar I could have sworn I still have a copy of those, but apparently not.  Not being a big fan of headaches, I don't think I ever when beyond skimming it over.

Just added 5b2c67fb, not as a solution, but just for the capability of turning metadata off if absolutely necessary.  It's hard to imagine that there's anything actually wrong on our side here, or what we could change to satisfy the viera. Maybe the problem will go away when firmware gets updated, who knows.

**Comment by Nadahar** [comment]
@skeptical I'm surprised that it even works without metadata.

I'm not surprised that it won't accept those we send, they break several rules and if the parsing of those are written thinking that they can follow the rules and not deal with a lot of variations beyond the standard, I can easily see how the parsing can fail. What I am surprised about is the fact that these same "broken" metadata seems to be accepted when delivered as an answer to a browse request. I would think, given that they are supposed to follow the same rules, that they would use the same parsing for both.

Are you sure that these metadata are supposed to be equal to those sent as a response to a browse request?

Sitting down and actually reading those guidelines must be for masochist only, but I think they can be quite useful for looking up things (IF you can find what you're looking for and follow the endless references to other documents).

**Comment by skeptical** [comment]
@Nadahar with this kind of stuff for me it's often the case that by the time I follow the maze of references and find the answer I've forgotten what the question was (true with some code too, e.g. cling which is very atomized).

But speaking of cling, there's [DIDLObject](http://4thline.org/projects/cling/support/apidocs/org/fourthline/cling/support/model/DIDLObject.html) with presumably spec-compliant properly structured/delimited subclasses (AudioItem, ImageItem, PlaylistItem, TextItem, VideoItem, etc) which might be a good alternative to the one-size fits all ```getDidlString()```, or at least worth looking at for hints.  Here's [an example](https://github.com/trishika/DroidUPnP/blob/master/src/main/java/org/droidupnp/model/mediaserver/ContentDirectoryService.java#L104) of usage.

**Comment by Nadahar** [comment]
@skeptical Hehe, I know what you mean - such standards are a pain to read even when the actual information you're after is quite simple.

To me the DIDLObject seems to be just another way to build the DIDL-Lite content, although probably more compliant than ours. Ideally the result should be the same though. I'm afraid the example doesn't tell me much as long as I don't see the XML it produces, but is seems like a more structured way to build it.

What I was wondering if you know that this metadata is supposed to be DIDL-Lite - or if that is just an assumption.

**Comment by skeptical** [comment]
@Nadahar I've never really looked into this beyond fiddling with the code to get things working. I just re-used our existing metadata in the upnp side, and it seemed to work ok.

**Comment by Nadahar** [comment]
This will probably never be fixed.
