### ISSUE TITLE
Suspicious external connection?

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#823]
Hi

After starting it, this app tries to make an external connection to this ip, 65.23.129.103:80  ...  OK.

Is this an update check ? Why is it making an external conenction? 

If it is just a simple update check I disable it? II do not see an option for it.

thanks

**Comment by Nadahar** [comment]
UMS does several web lookups, all from update check to web streams to cover and open subtitles lookups. WEB.conf is configured by default with some (outdated) web streams.

On the "General" tab you can disable external network.

**Comment by gerroon** [comment]
@Nadahar 

Thanks for the speedy heads up. I will see what I can do with the conf.

**Comment by gerroon** [comment]
How do I disable upgrade check?

**Comment by SubJunk** [comment]
At the bottom of the General Configuration tab, untick "Enable external network"

**Comment by gerroon** [comment]
@SubJunk 

Awesome, thanks

**Comment by SubJunk** [comment]
:)
