### ISSUE TITLE
Rewrite the public variables to private

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#827]
@UniversalMediaServer/developers I asked for this maybe two or more years ago during the PMS era. The answer was that we need them to keep the backward compatibility for plugins. Is it still relevant? I think if some plugins until now don't reflect that those variables were signed as deprecated and didn't implement the changes don't have a right to exist. What do you mean?

**Comment by Nadahar** [comment]
I couldn't agree more, but we've already discussed that and the plugin authors here refuse anything that could mean any changes in the plugins as I understand it. I even went through some of the plugins and replaces all deprecated variables at one stage, but I'm not sure all of those were merged.

**Comment by valib** [comment]
If I remember well there was a warning made by @SubJunk that it will be made in the future so I think the future is now.

**Comment by SubJunk** [comment]
Should be okay to do it now. I think most if not all of the plugins in our installer will work, or can be updated to work.

**Comment by Sami32** [comment]
Now ? ;-D

**Comment by SubJunk** [comment]
Well we all agreed that this should be done but it never was :p

**Comment by valib** [comment]
Mostly done in #1653

**Comment by SubJunk** [comment]
Done
