### ISSUE TITLE
Youtube feeds?

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#830]
Hi

I am trying to get some youtube feeds going but I cant figure out. It is a bit convoluted. The reason is this. Do I need this sharkhunter plugin or not? If so the installation of it on Pms sounds a bit v ague toi me. The author states that tne channel file has to be put somewhere new, but that does not really mean anything if you weel.

Here is a type of fyoutube feed I described in the WEB.conf I also enabled external network

videofeed.Web,Youtube=https://www.youtube.com/feeds/videos.xml?user=someuser

"
Download the plugin jar and place it in the PMS plugins directory.
Download Channel files you need and place them in a new directory.
"

I am trying this on Linux.

**Comment by gerroon** [comment]
Nevermind ;( 

It works without the plugin. I was using the web browser and the youtube web feeds were not showing up under the web server (:9001). I can see the youtube feeds if I use aupnp client on Android.

**Comment by gerroon** [comment]
Ok abit of progress ina  negative way.

The youtube feed shows up with thumbnails but clicking on a video does not play

ERROR 15:11:29.945 [Hanging External Process Stopper] External input stream instance is null... stopping process
ERROR 15:11:43.606 [New I/O worker #8] There is no inputstream to return for xxxxxxxxxxxx
ERROR 15:11:43.613 [Hanging External Process Stopper] External input stream instance is null... stopping process


I tried both ffmpeg and mplayer for web.

**Comment by skeptical** [comment]
@gerroon [jumpy](http://skeptical.github.io/jumpy/readme.html) can also act as a [resolver](http://skeptical.github.io/jumpy/readme.html#RESOLVER) for youtube urls.  Try temporarily removing the channels plugin, install jumpy, and restart UMS. Example WEB.conf entry:
```csv
videofeed.Web,Last Week Tonight=http://www.youtube.com/feeds/videos.xml?user=lastweektonight
```

**Comment by gerroon** [comment]
@skeptical 

Have you tried installing jumpy yourself? I cant get it to work. It does not show up anywhere in the ui.

**Comment by skeptical** [comment]
@gerroon yes, I've tried to install it (having also written it :-). Please start a thread for your jumpy installation issues in the plugins forum and post a set of trace logs, and I'll see if I can help with that.

**Comment by Sami32** [comment]
@gerroon Did your solved your problem now ?

**Comment by gerroon** [comment]
@Sami32 

I have not checked it out. I will reopen this bug when I try it later
