### ISSUE TITLE
opensubtitles.org abuse

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#831]
After looking through some code, I discovered that we're abusing opensubtitles.org in about as many ways as possible. First of all, we're using a user agent specifically reserved for TESTING only, we're calling it IMDb when we're actually using opensubtitles and we're generally not crediting them in any way.

Here are the [rules for using opensubtitles.org] (http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst). I'd say we should stop using it until these things are fixed.

**Comment by SubJunk** [comment]
Good find. I've emailed them to get a user agent and will make the changes necessary to give credit to them.

**Comment by SubJunk** [comment]
Start this at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/832 and I added links to opensubtitles.org on our About and Comparison pages

**Comment by Nadahar** [comment]
:+1:
