### ISSUE TITLE
Problem videos MKV 

### ISSUE THREAD

**Issue by Residentcl** [UniversalMediaServer/UniversalMediaServer#838]
Hello. I have trouble watching videos MKV format.

By selecting the file to the TV, get the error:
The file you selected is not available currently.

I have version 6.1.0 / Java 8.
Java August 73 update.
Windows 10 Update November 10.0.10586.

TV Model: UN32J4303.
Version: 1025

example video
File sub:
https://mega.nz/#!H9REERbL!0TzeiR3lr634hh1thLJo0rF9FT8OufYyb4EdIEtFj84
File video:
https://eztv.ag/ep/141689/arrow-s04e14-720p-hdtv-x264-dimension/
File Debug: 
https://mega.nz/#!zl4BXZQB!NNO5qK3tesLM1udiUfnkhvWsNmeWRbRIB590_ZiGsN4
![img_20160221_130341](https://cloud.githubusercontent.com/assets/1659401/13203979/961e08cc-d8a2-11e5-8277-2977d7e9286a.jpg)
![img_20160221_130524](https://cloud.githubusercontent.com/assets/1659401/13203980/961e1574-d8a2-11e5-89b6-e827c5992fc6.jpg)
![img_20160221_130653](https://cloud.githubusercontent.com/assets/1659401/13203982/961fb1c2-d8a2-11e5-99e9-da0ded02a8fb.jpg)
![img_20160221_130816](https://cloud.githubusercontent.com/assets/1659401/13203981/961f313e-d8a2-11e5-8809-f677186304a5.jpg)

**Comment by Residentcl** [comment]
Problem TV 2:
TV Model: UN40EH53001.
Version: 0002004.

![img_20160221_141012](https://cloud.githubusercontent.com/assets/1659401/13204211/0adc6aa4-d8a9-11e5-9f07-1da50a1dacbc.jpg)
![img_20160221_141040](https://cloud.githubusercontent.com/assets/1659401/13204213/0adf12fe-d8a9-11e5-8717-c29c2bd8317f.jpg)
![img_20160221_141302](https://cloud.githubusercontent.com/assets/1659401/13204212/0adedffa-d8a9-11e5-97a0-3bfdd147dab1.jpg)

**Comment by SubJunk** [comment]
Thanks for the detailed bug report, I'll look into this

**Comment by Residentcl** [comment]
Thus or other problems?

![100](https://cloud.githubusercontent.com/assets/1659401/13205152/aae117e6-d8bf-11e5-9815-3f695fb6a60b.png)

**Comment by Residentcl** [comment]
No problem video MP4, sub and size:

![img_20160221_173926](https://cloud.githubusercontent.com/assets/1659401/13205314/68d424ce-d8c4-11e5-8643-7b8cd543bd1a.jpg)

File Video 720p: 
https://yts.ag/movie/the-33-2015
File sub:
http://www.yifysubtitles.com/subtitles/the3320151080pblurayx264-ytsag-spanish-77864

**Comment by Residentcl** [comment]
No problem AllConnect and BubbleUPnP.![screenshot_2016-02-21-19-13-47](https://cloud.githubusercontent.com/assets/1659401/13205827/cdd234aa-d8cf-11e5-9b1d-1e132cf8c2a8.png)
![screenshot_2016-02-21-19-12-02](https://cloud.githubusercontent.com/assets/1659401/13205834/e8c90b12-d8cf-11e5-98d6-c6c0697d6fa8.png)

**Comment by Residentcl** [comment]
Uninstall, re-install and fixes problem MKV, 
There is a pure problem now, I get the subtitle duplicate.
File debug:
https://mega.nz/#!ywAwTJwT!r-hI1A6s-ro3xYzyVMDUT2ssLG2smhriYAeSZgtho6o

![img_20160224_204316](https://cloud.githubusercontent.com/assets/1659401/13305640/6ddb3ed4-db3b-11e5-8dc0-4b89f9ab45ad.jpg)
![img_20160224_204318](https://cloud.githubusercontent.com/assets/1659401/13305639/6ddb36be-db3b-11e5-9722-538e03cab49b.jpg)

**Comment by Teshiro** [comment]
Hi,

I am having the issue with the file size showing exactly 976,56 kB, and the video is capable of running like 2-4 seconds, then it ends. Uninstal and reinstal didn't help.

Any further info is much appreciated.

**Comment by valib** [comment]
@Residentcl the update hopefully fix the issue with subtitles duplicating.

**Comment by Residentcl** [comment]
@valib Nice. new release date?

**Comment by Residentcl** [comment]
@Teshiro 

Same problem with TV Model: UN32J4303.

**Comment by Teshiro** [comment]
Debug files for my reported issue

https://mega.nz/#fm/MdRCRYTb

**Comment by Residentcl** [comment]
@Teshiro: Error link!

**Comment by Teshiro** [comment]
Mediainfo:

> General
> Unique ID                                : 205056775282847286241311363964313884118 (0x9A447F95F0F629B982EA258683AD55D6)
> Complete name                            : D:\Filmy\Filmy\End of Watch 1080p\End.of.Watch.2012.RETAIL.1080p.bluray.dts.x264-PublicHD.mkv
> Format                                   : Matroska
> Format version                           : Version 4 / Version 2
> File size                                : 11.1 GiB
> Duration                                 : 1h 49mn
> Overall bit rate                         : 14.5 Mbps
> Encoded date                             : UTC 2013-04-08 13:09:54
> Writing application                      : mkvmerge v6.1.0 ('Old Devil') built on Mar  2 2013 14:32:37
> Writing library                          : libebml v1.3.0 + libmatroska v1.4.0
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L4.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 4 frames
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 1h 49mn
> Bit rate                                 : 12.8 Mbps
> Width                                    : 1 920 pixels
> Height                                   : 1 040 pixels
> Display aspect ratio                     : 1.85:1
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 fps
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.267
> Stream size                              : 9.36 GiB (85%)
> Title                                    : Scrat@CzTorrent
> Writing library                          : x264 core 129 r2230 1cffe9f
> Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=16 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=abr / mbtree=1 / bitrate=12800 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> 
> Audio #1
> ID                                       : 2
> Format                                   : AC-3
> Format/Info                              : Audio Coding 3
> Mode extension                           : CM (complete main)
> Format settings, Endianness              : Big
> Codec ID                                 : A_AC3
> Duration                                 : 1h 49mn
> Bit rate mode                            : Constant
> Bit rate                                 : 448 Kbps
> Channel(s)                               : 6 channels
> Channel positions                        : Front: L C R, Side: L R, LFE
> Sampling rate                            : 48.0 KHz
> Compression mode                         : Lossy
> Delay relative to video                  : 35s 200ms
> Stream size                              : 350 MiB (3%)
> Title                                    : Czech AC3 5.1
> Language                                 : Czech
> Default                                  : Yes
> Forced                                   : No
> 
> Audio #2
> ID                                       : 3
> Format                                   : DTS
> Format/Info                              : Digital Theater Systems
> Mode                                     : 16
> Format settings, Endianness              : Big
> Codec ID                                 : A_DTS
> Duration                                 : 1h 49mn
> Bit rate mode                            : Constant
> Bit rate                                 : 1 509 Kbps
> Channel(s)                               : 6 channels
> Channel positions                        : Front: L C R, Side: L R, LFE
> Sampling rate                            : 48.0 KHz
> Bit depth                                : 24 bits
> Compression mode                         : Lossy
> Stream size                              : 1.15 GiB (10%)
> Title                                    : English DTS 5.1
> Language                                 : English
> Default                                  : No
> Forced                                   : No
> 
> Text #1
> ID                                       : 4
> Format                                   : UTF-8
> Codec ID                                 : S_TEXT/UTF8
> Codec ID/Info                            : UTF-8 Plain Text
> Title                                    : Cz forced
> Language                                 : Czech
> Default                                  : Yes
> Forced                                   : Yes
> 
> Text #2
> ID                                       : 5
> Format                                   : UTF-8
> Codec ID                                 : S_TEXT/UTF8
> Codec ID/Info                            : UTF-8 Plain Text
> Title                                    : Cz
> Language                                 : Czech
> Default                                  : No
> Forced                                   : No
> 
> Text #3
> ID                                       : 6
> Format                                   : VobSub
> Codec ID                                 : S_VOBSUB
> Codec ID/Info                            : Picture based subtitle format used on DVDs
> Title                                    : En
> Language                                 : English
> Default                                  : No
> Forced                                   : No
> 
> Menu
> 00:00:00.000                             : en:00:00:00.000
> 00:03:50.188                             : en:00:03:50.188
> 00:08:54.743                             : en:00:08:54.743
> 00:13:32.520                             : en:00:13:32.520
> 00:17:27.463                             : en:00:17:27.463
> 00:24:38.519                             : en:00:24:38.519
> 00:28:11.189                             : en:00:28:11.189
> 00:32:21.231                             : en:00:32:21.231
> 00:36:32.649                             : en:00:36:32.649
> 00:42:52.403                             : en:00:42:52.403
> 00:49:41.729                             : en:00:49:41.729
> 00:56:15.872                             : en:00:56:15.872
> 01:04:31.826                             : en:01:04:31.826
> 01:11:40.421                             : en:01:11:40.421
> 01:18:29.413                             : en:01:18:29.413
> 01:23:40.474                             : en:01:23:40.474
> 01:29:06.925                             : en:01:29:06.925
> 01:36:00.171                             : en:01:36:00.171
> 01:39:46.272                             : en:01:39:46.272
> 01:42:33.939                             : en:01:42:33.939

**Comment by Teshiro** [comment]
After 2 updates this problem still persists

**Comment by Residentcl** [comment]
@Teshiro > 
1: https://github.com/UniversalMediaServer/UniversalMediaServer/commit/9c0aa791a3632ed84f30cbfe42b82f48249441e8#commitcomment-16855760 
2: https://github.com/UniversalMediaServer/UniversalMediaServer/commit/9c0aa791a3632ed84f30cbfe42b82f48249441e8#commitcomment-16855872

**Comment by valib** [comment]
@Teshiro the problem is different than @Residentcl reported in this issue and it was not solved. From your log I see that you want to play an internal VOBSUB subtitles and your TV cancelled connection for streaming but I don't know why the TV is doing that. Maybe other developers can help.

**Comment by Teshiro** [comment]
Uhm, I can play the movie from the Transcoded folder pretty fine, but not from the original folder D:

**Comment by Teshiro** [comment]
@Residentcl I did as mentioned in those posts and the problem is still there

**Comment by Residentcl** [comment]
:/

**Comment by valib** [comment]
@Teshiro please send the log when you try to play the particular video from the TRANSCODE folder and from the "original" folder.

**Comment by Teshiro** [comment]
@valib 
I am sorry it took me so long, wasn't able to pay much time to this issue until now.

Here's the log file from when I play the vid from Transcode folder. It plays perfectly fine.
https://www.dropbox.com/s/5jopd2jygz9ag0j/ums_dbg_transcode.zip?dl=0

Any help is much appreciated.

**Comment by Sami32** [comment]
@valib From his log, i understood that the VOBSUB subtitle, that is specified as not supported by his renderer, is streamed with the trancoded video (it will need to be transcoded anyway, also without subtitles, as his bandwidth is not suffisant for that movie).

So, AFAIU, instead of trancoding the subtitle, UMS stream the unsupported VOBSUB.
Maybe the audio/subtitles preferences, values by default in this case (eng), prevalence on the supported subtitles format configuration ?
I could be wrong though...

An other strange thing in  the recent log while playing from TRANSCODE folder, is that a 4th subtitle was created by UMS as the original file only have 2 SRT and 1 VOBSUB subtitles:
> End.of.Watch.2012.RETAIL.1080p.bluray.dts.x264-PublicHD.mkv: audio: id: 0, lang: cs, audio track title from metadata: Czech AC3 5.1, audio codec: AC3, sample frequency:48000, number of channels: 6, bits per sample: 16, **subtitle: id: -1, type: UNKNOWN, lang: null**

P.S. Nothing to do with his issue, but this message should not be found:
> Invalid action in SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#X_GetFeatureList"

**Comment by Nadahar** [comment]
@Sami32 When UMS decides to stream the subtitles, is that because of an error in the renderer configuration or are you saying that the renderer configuration is correct and UMS decides to stream these anyway?

**Comment by Sami32** [comment]
@Nadahar His renderer configuration is fine but UMS doesn't respect it.

**Comment by SubJunk** [comment]
Stale, If it is still a problem please reopen
