### ISSUE TITLE
Playback to Xbox One unreliable over gigabit ethernet to on 6.1.0

### ISSUE THREAD

**Issue by johnddx** [UniversalMediaServer/UniversalMediaServer#841]
**Prior to 6.1.0**
Prior to upgrading and resetting defaults (from a recent build), I was able to start playback on an .mkv, and it would play the movie well until it was stopped or fast-forwarded, audio intact.  However, I could not get this or any mkv to resume from a bookmark... it would inevitably start skipping video and desyncing video with audio, and would never recover.  Moreover, if I tried to fast-forward from the beginning to a point 10 minutes into the move, it would have the exact same effect.
This is the main reason I upgraded, to see if the issue had been improved.

**On 6.1.0**
After the upgrade today (at which point I reset UMS settings to default using the wizard), it won't play the video for more than 10s before video gets into a repeat loop, while audio continues.  About half the time at video start, the video is completely blank, while audio proceeds.  So the current build is actually worse.

**Comment by SubJunk** [comment]
@johnddx can you please follow these instructions to give us logs for 6.0.0 and 6.1.0, then we can see what went wrong http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by SubJunk** [comment]
Never got logs
