### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by oz-tangles** [UniversalMediaServer/UniversalMediaServer#842]
When installing a new version of UMS I get an error message about MediaInfo.dll (see attachment).  If I click IGNORE UMS appears to install correctly.  This has happened more than once.
Currently installed version: 6.1.0
Operating system: Windows 10 64-bit (version 1511 build 10586.104)

![img_0065](https://cloud.githubusercontent.com/assets/17422258/13241756/2fd03cf6-da42-11e5-8e32-b228d32aefe2.JPG)

**Comment by SubJunk** [comment]
This means UMS was running at the same time as the installer. We have detection of that but I think it only works if you're using the 64-bit version of Java, so to fix it install that
