### ISSUE TITLE
Universal Media Server does not start with the operating system.

### ISSUE THREAD

**Issue by Residentcl** [UniversalMediaServer/UniversalMediaServer#843]
Universal Media Server does not start with the operating system.

![10](https://cloud.githubusercontent.com/assets/1659401/13263584/e18b975a-da48-11e5-8abf-36a680e7d209.png)
![11](https://cloud.githubusercontent.com/assets/1659401/13263583/e18b57fe-da48-11e5-8eec-1546ab756dfe.png)

I have version 6.1.0 / Java 8.
Java August 73 update 64 bit.
Windows 10 64 bit - Update November 10.0.10586.

File Debug: 
https://mega.nz/#!L9gjxRyJ!XNoSsYOGUtvKjFU8XBauND_afq7rGvxJtLKn0IGZZag

**Comment by valib** [comment]
@Residentcl You can run the UMS either as service or start the UMS with the operating system not both. Once you install it as a service there is not a GUI available.

**Comment by Residentcl** [comment]
I already did, but it still does not go on TV and phones.

![100](https://cloud.githubusercontent.com/assets/1659401/13268177/caa16eb8-da5f-11e5-9f64-56b890d771cb.png)

something happens to the application does not appear in network.

**Comment by valib** [comment]
You need to stop this service and next time when you start the UMS you can uninstall them. Anyway it is not recommended to use the UMS as an service so if you don't know what are you doing don't do it. .

**Comment by Residentcl** [comment]
uninstall, re-install and fixes problem :) 

With the upgrade from 6.0 to 6.1 I was a problem with the application.
