### ISSUE TITLE
Media renderer was not recognized

### ISSUE THREAD

**Issue by pixyonly** [UniversalMediaServer/UniversalMediaServer#847]
I build UMS on my mac and play with VLC.

below is output:
Media renderer was not recognized. Possible identifying HTTP headers:User-Agent: Darwin/15.2.0, UPnP/1.0, Portable SDK for UPnP devices/1.6.18

environment:
System: MacOS 10.11.2
JRE Version: 1.8.0_31-b13

**Comment by Residentcl** [comment]
In Windows 10, VLC comes as Sony Xperia Z.

I have version 6.1.0 / Java 8.
Java August 73 update.
Windows 10 Update November 10.0.10586.

![vlcsnap-2016-02-28-21h04m33s770](https://cloud.githubusercontent.com/assets/1659401/13382935/04b3c260-de5f-11e5-9ce0-173b4c7aa564.png)
![vlcsnap-2016-02-28-21h04m23s490](https://cloud.githubusercontent.com/assets/1659401/13382937/08fecdf6-de5f-11e5-8517-7741e348060d.png)

File debug: 
https://mega.nz/#!T4hnjBqS!mxyBC-gz8a1OpI44hycuFkaCdCV5_H6MlRDEY2ja3K8

**Comment by valib** [comment]
If the renderer is not properly recignized please follow the instruction at https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/faq#my-device-is-not-supported-by-ums-how-can-i-create-a-custom-rendererconf-to-make-ums-recognize-my-device

**Comment by Sami32** [comment]
@pixyonly @Residentcl If you didn't already solved this issue by yourself, a VLC renderer was created in UMS 6.5.1, did this solved your issue ?

If yes, just close this issue, thanks.

**Comment by Residentcl** [comment]
Close and solved :)
thanks!
