### ISSUE TITLE
FORUM enhancements

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#850]
Need to implement Anti SPAM and Anti Bot features into the Forum.  Its virtually impossible to maintain manually without some tools implemented otherwise. 

i have tried to manually add in IP ban ranges. and clean up what i could in one day... only to be undone by the next wave of spam bots. 

the forum is crying for some love and attention.

**Comment by SubJunk** [comment]
I agree and it's a high priority for me this weekend

**Comment by SubJunk** [comment]
I've just installed and enabled the Stop Forum Spam extension from https://www.phpbb.com/customise/db/extension/phpbb_3.1_stop_forum_spam/ so please let me know if it gets better

**Comment by WolfganP** [comment]
It also may be helpful to add mandatory moderation for the first X posts of new users (ie 3 or 5). I don't think there are many registrations daily, so it will should be easy to maintain on a regular basis rather than combat spam waves as the forum suffered lately.

**Comment by DeFlanko** [comment]
Thanks, I'll check it out tonight!

**Comment by DeFlanko** [comment]
Also if you can grant the ability to clean up the ban lists to moderators
that would be helpful too, there is still a single IP address in there that
I accidentally added as exclusion.

**Comment by DeFlanko** [comment]
Ohh wait , I see the ability to remove bans now... Thanks! I'll do some
more clean up tonight to rid of some of the noise so that way we can base
line the newly added acp.

**Comment by valib** [comment]
@SubJunk I think that it is a time to implement the captcha otherwise the Russian spammers will destroy the forum.

**Comment by SubJunk** [comment]
It looks to me like this new thing I added has stopped it for now so we can add more things like captchas if it happens again. There is already a custom captcha on our registration page that asks one of several questions when you register.

**Comment by DeFlanko** [comment]
Yeah i'm with you @SubJunk , i just had an enjoyable moment of forum clean up for about 45 mins, and haven't seen any new registrants and random posts... i think we can call this one resolved. (for now...) :+1:

**Comment by SubJunk** [comment]
@DeFlanko thanks for your work on this! Let me know if it happens again and I'll throw some other things into the mix :)

**Comment by SubJunk** [comment]
I'm updating the forum now from 3.1.6 to 3.1.8. Unfortunately there don't seem to have been any spam-related improvements but I like to keep it up to date anyway. Sometimes plugin modifications get overwritten during updates so let me know if any issues come up or if spammers get through

**Comment by DeFlanko** [comment]
No worries, just trying to do my part, when I can :)

**Comment by WolfganP** [comment]
I don't know when exactly the new forum plugins and measures were enabled, but I'm still seeing spam messages pouring into the forums. As I commented earlier, it's probably also a good tactic to enable Moderation for first X posts of new registered users, that way initial messages are stopped short of being published (and truly interested users will be able to be easily identified).
Found some doc at https://www.phpbb.com/community/viewtopic.php?f=466&t=2337051

**Comment by SubJunk** [comment]
We got more spam so I've enabled reCAPTCHA

**Comment by DeFlanko** [comment]
If it hasent been done so yet, I'll do some clean up when I can this
weekend as well as look around for some possible additional tools or
methods.

**Comment by Sami32** [comment]
@SubJunk You recently did it well ;-) as we can enjoy it on the forum, so i guess this issue can be closed ?
