### ISSUE TITLE
WEB.Conf Enhancement

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#856]
Per the conversation and ide brought up here: http://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=6128&p=25656#p25656

i went a head and uploaded an XML file that Universalmediaserver.com could technically host and have the XML (RSS) file be added the Web.Conf file for Testing Puropses. 

It's a collection of Big Buck Bunny files and formats. 

It would be nice to expand on this idea  to audio and images, would be a helpful tool!

 Thoughts?

**Comment by SharkHunter** [comment]
I think WEB.conf is the best example of something that works on paper but not in practice. I'm only interested in web based content and started using WEB.conf only to discover that didn't work and developed Channels to solve the issues.
Without any sort of resolver (read Channels/Jumpy) the WEB.conf will only contain some "mickey-mouse" links (like big buck bunny).

**Comment by DeFlanko** [comment]
Ohh for sure, i think Web.conf isn't as great at all as jumpy. but it can still serve a purpose such for testing big buck bunny formats on render's -- i think the goal the person in the forum was trying to convey is to make a lightweight install of UMS to test a headend without the personal media residing locally... hence the big buck bunny sources. 

i could be mistaken -- but at least this way the web.conf has a purpose again lol

**Comment by SubJunk** [comment]
Closing this in favour of https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1448 because that is linked to my recent work on it - we are focusing on this functionality for v8.0.0
