### ISSUE TITLE
Does creating thumbs affect resumed position?

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#860]
I never used RESUME feature so don't know how it works but from log below it seems to me resume position is get also from action of thumbs generation?
http://www.universalmediaserver.com/forum/viewtopic.php?p=25644#p25644

```
INFO  2016-03-05 18:39:18.461 [StopPlaying Event] Stopped playing Atash.2004.DVDRip.XviD.Eng.avi on your [TV]Samsung LED50
DEBUG 2016-03-05 18:39:18.470 [StopPlaying Event] The full filename of which is: H:\0FA6~1\ATASH(~1\ATASH2~1.AVI and the address of the renderer is: 10.0.0.6
DEBUG 2016-03-05 18:39:18.471 [StopPlaying Event] Resume stop. This segment 214701 new time 214701
DEBUG 2016-03-05 18:39:18.477 [StopPlaying Event] adding "Atash.2004.DVDRip.XviD.Eng" to playlist "Recently Played"
```

Or maybe I only wrongly interpreted line below as a info that nothing is changed to resume position:

```
This segment 214701 new time 214701
```

So maybe irrelevant bug report:)

**Comment by Sami32** [comment]
While looking at Resume function, see also this issue: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/481

**Comment by ExSport** [comment]
old one, closing...
