### ISSUE TITLE
File size and playback issue on Samsung UA65HU8600

### ISSUE THREAD

**Issue by genwells** [UniversalMediaServer/UniversalMediaServer#861]
I'm using UMS 6.2.0 with Samsung US65HU8500 TV via a wired gigabit connection.
On the TV, a number of large files (i.e. >2GB) only show up as 978KB.  When you play the file, it only has a few seconds in the status bar, but plays for about 30seconds and then cuts out.  Works fine on a Sony Bravia and plays properly on the PC.  Debug/trace files attached.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/170775/ums_dbg.zip)

Please help.

The file I'm testing is an MKV with the following info (from GOM player):
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 42mn 27s
Bit rate                                 : 10.8 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.218
Stream size                              : 3.21 GiB (86%)
Writing library                          : x264 core 148 r2665 a01e339
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=11 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=16 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=17.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No
Matrix coefficients                      : BT.709
DURATION                                 : 00:42:27.462000000
NUMBER_OF_FRAMES                         : 61078
NUMBER_OF_BYTES                          : 3530322099
_STATISTICS_WRITING_APP                  : mkvmerge v8.4.0 ('A better way to fly') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2016-03-07 18:43:40
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

**Comment by WolfganP** [comment]
Go to the TRANSCODE folder for that file and try alternate options (particularly light ones as NO Transcoding or TsMuxer). 
Your TV is matching "Samsung E+ Series" profile, is maybe worthy to create an specific one for your TV and tweak from there (http://www.universalmediaserver.com/faq/#RendererSupport1).

**Comment by genwells** [comment]
Thanks Wolfgang.  I managed to setup my own conf file and it has solved the problem.

When I was creating the conf file, I noticed that you can automatically generate a new conf file within UMS when the device is unknown.  I did find a bug though that if your trying to save the new conf file in the usual directory without running UMS in Admin mode, the file will not be created and no error is thrown, in case anyone has the same issue or the developers wish to fix.

Thanks again, much appreciated.
