### ISSUE TITLE
Discrepancy in the UMS.conf and Wiki

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#864]
@skeptical there is a problem with the Ip_filter description in the Wiki. There you wrote that `IP-filtering is the most restrictive method that UMS provides. To use you supply a comma-separated list of IP-addresses that will simply be blocked.` but in the UMS.conf is written `Use an IP filter (whitelist)
Set the IP address(es) and/or IP address range(s) of the clients permitted
to connect.  When no filter is specified, UMS will allow any IP address to
connect to the service.`
I tested it and it seems to me that the description in the Wiki is wrong. The `ip_filter` works as an whitelist not the restriction to the IP addresses. Can you check it?

**Comment by skeptical** [comment]
@valib thx, I blame @SharkHunter :-) since I just transferred the text from his [forum post](http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=2266&sid=674e1386e345b18c476ee8b7b901ada9) to the wiki. You're right of course, it does appear to be a whitelist. Fixed now.

**Comment by valib** [comment]
@skeptical I was also thinking that it was @SharkHunter who wrote it but I was not sure :smile:
