### ISSUE TITLE
Flv streaming?

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#866]
Hi

I am sorry to post here about this issue but I cant get flv mvies to be streamed. I am on Debian 32 wheezy using java8 branch. 

None of the media players on my tablet seemed to be able to  play through bubbleupnp or upnplay. I tried VLc and Goodplayer on Android.

I am using ffmpeg on the server side now.

I also seem to get this here and there.

"
08:08:04 TRACE Sent to socket: Server: Linux-i386-3.16.1-customkernel, UPnP/1.0, UMS/6.2.0
08:08:04 TRACE Sent to socket: Content-Length: 3433
08:08:05 DEBUG Stopping Unix process 20660: ffmpeg-107
08:08:05 TRACE Killing the Unix process: 20660
08:08:05 TRACE Destroying buffer
08:09:28 DEBUG Sending ALIVE...
08:09:28 TRACE Ignoring self-originating request from /10.8.0.1:57830
08:09:28 TRACE Ignoring self-originating request from /10.8.0.1:57831
08:12:28 DEBUG Sending ALIVE...
08:12:28 TRACE Ignoring self-originating request from /10.8.0.1:57991
08:12:28 TRACE Ignoring self-originating request from /10.8.0.1:57993
08:12:28 TRACE Ignoring self-originating request from /10.8.0.1:57992
08:12:28 TRACE Ignoring self-originating request from /10.8.0.1:57996
08:12:28 TRACE Ignoring self-originating request from /10.8.0.1:57994
08:13:06 DEBUG Connection error: java.io.IOException: Connection reset by peer
08:13:06 DEBUG Connection error: java.io.IOException: Broken pipe
08:13:06 DEBUG Premature end, stopping...

"

And things like these

"
INFO  07:58:22.976 [mencoder-85] Process mencoder has a return code of 1! Maybe an error occurred... check the log file
INFO  07:58:25.485 [StartPlaying Event] Started playing DFI02_ch02.flv on your Safari
INFO  07:58:43.286 [StopPlaying Event] Stopped playing DFI02_ch02.flv on your Safari
INFO  07:58:43.633 [mencoder-90] Process mencoder has a return code of 1! Maybe an error occurred... check the log file
INFO  07:58:49.292 [StartPlaying Event] Started playing DFI02_ch03.flv on your Safari
INFO  07:58:53.299 [StopPlaying Event] Stopped playing DFI02_ch03.flv on your Safari
INFO  07:59:12.442 [mencoder-92] Process mencoder has a return code of 1! Maybe an error occurred... check the log file
INFO  07:59:17.720 [StartPlaying Event] Started playing DFI02_ch04.flv on your Safari
INFO  07:59:21.730 [StopPlaying Event] Stopped playing DFI02_ch04.flv on your Safari
INFO  07:59:24.417 [mencoder-94] Process mencoder has a return code of 1! Maybe an error occurred... check the log file
INFO  07:59:30.174 [StartPlaying Event] Started playing DFI02_ch05.flv on your Safari
INFO  07:59:34.190 [StopPlaying Event] Stopped playing DFI02_ch05.flv on your Safari
INFO  08:00:03.589 [mencoder-102] Process mencoder has a return code of 1! Maybe an error occurred... check the log file
" 

thanks

**Comment by SubJunk** [comment]
@gerroon we need TRACE logs for that to see why MEncoder failed, see https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

Reopen the issue if you come back
