### ISSUE TITLE
Enhancement request - IP Cam Broadcast

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#868]
This might sound odd...

Adding in support to _accept_ IP Camera streams, and re-broadcast them though UMS.

So for example. I have a Wireless camera that always shows up in my Auto-Discovery list, what if UMS sees that it's a Camera that's providing a feed .. this is really a webcam:

![DCS-933L](https://dl.dropboxusercontent.com/u/2669244/UMS/Screenshots/2016-03-27_21-54-16.png)

Inside my CCTV program that it uses to capture the feed:
![DCS-933L_2](https://dl.dropboxusercontent.com/u/2669244/UMS/Screenshots/2016-03-27_22-04-06.png)

If any other information that might be needed to make this possible or worth it... let me know.

**Comment by WolfganP** [comment]
+1 on getting a way to support live streams being discoverable via DLNA thru UMS. 
I tried to configure web videos to accept IPTV streams (rtmp, rstp, or http; IP cams may add other live formats) but I wasn't able to make it reliable as a dedicated IPTV app running on the renderer.
My next intent will be trying via the channels plugin, but having a better support thru UMS core capabilities will be super.

**Comment by Residentcl** [comment]
+1 :)

**Comment by SharkHunter** [comment]
rtmp/rtsp/http/hls streams nowdays run fairly straight out of the box. However, finding the actual stream  AND send all cookies etc. is the problem. Channels tries to solve this (plus it finds the actual streams dynamically). The IPcam situation should work with WEB.conf (or Channels). If your IPcam delivers a url (and most does) you can simply add it to the web.conf . If you need to "mangle"/"resolve" the URL somewhat UMS already have support for this (and Channel and/or Jumpy makes use of it),

I think the main issue here for @DeFlankos web cam is teh login. This _should_ work from WEB.conf but I'm not 100% sure. Through Channels it will most likely work.

**Comment by DeFlanko** [comment]
Interesting, I'll tinker when I get home.

**Comment by WolfganP** [comment]
I'm also very interested on getting this working as well. I think one of the weakness of these features is the lack of documentation and working examples.
@deflanko do you mind to open a thread at the forum so we can share experiences and stays documented for others to follow / contribute?

**Comment by Residentcl** [comment]
It will be also possible to add the webcam?

With cameras with BDA driver it would not be much work to put in UMS.
I have a Microsoft LifeCam HD 3000, I can help with testing.

**Comment by DeFlanko** [comment]
I want to revisit this, @SharkHunter whats a good resource to configuring Channels plugin?
