### ISSUE TITLE
UMS not displaying

### ISSUE THREAD

**Issue by thomaco19** [UniversalMediaServer/UniversalMediaServer#871]
Im currently using a macbook running Mac OS X El Captian, and UMS refuses to display. It asks if I want it to accept incoming connections, but then never displays the program itself. The program does run and stays open, it never crashes.

**Comment by SubJunk** [comment]
Can you please try other versions and let us know when this issue started happening?

**Comment by chiops** [comment]
Same thing is happening to me. UMS will not show on my Samsung smart TV any more. 
The issue started immediately after I installed "Java 8 update 77" on March 31.
Could there be a correlation?

**Comment by Sami32** [comment]
@thomaco19 @chiops So i guess older version did worked for you, right ?
If yes, could you return feedback about the version that you use, please ?

**Comment by chiops** [comment]
@Sami32 : Not long after I made my comment v6.4.0 became available, which seems to have fixed the issue for me. Sorry for not responding here accordingly.

**Comment by SubJunk** [comment]
@chiops thanks for letting us know :)
