### ISSUE TITLE
UMS 6.2.1 not appearing in OPlayer Lite or Ginkgo

### ISSUE THREAD

**Issue by moleyt** [UniversalMediaServer/UniversalMediaServer#872]
SInce upgrading to 6.2.1, UMS stopped appearing on my iphone/ipad using oplayer lite, and on my android device using ginkgo. It did however continue to work on my PS4.

I've now downgraded to 6.2.0 and all appears to be working again.

Looking at the debug logs, UMS was sending a discovery to these devices, but I was then receiving "Ignoring Self Originating Requests" messages, very similar to what was reported here https://github.com/UniversalMediaServer/UniversalMediaServer/search?utf8=%E2%9C%93&q=Ignoring+self-originating+request

Has something changed in the code that checks for cling? Let me know if you want me to re-upgrade and send you the debugs.

**Comment by SubJunk** [comment]
I wonder if it has something to do with external library updates we did in 6.2.1. Debug logs would be good

**Comment by SubJunk** [comment]
Never got logs
