### ISSUE TITLE
24-bit FLAC files parsed as "AudioAsVideo" ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#881]
Hello,

the **24-bit FLAC music files** have a weird displaying on my Panasonic Viera TX-L32E6E, with Windows XP SP3 32 bit, whatever Java version or UMS version, until 6.2.0, used.

![panasonic_ums_flac24](https://cloud.githubusercontent.com/assets/18471069/14614718/39cc74d0-059a-11e6-98a5-f48774b80772.jpg)

It's look like it affect only 24 bit FLAC files streaming.
[FLAC.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/266991/FLAC.txt)
The FLAC second part (write as Music and not the wrong MPEG2-PS) are playing fine without transcoding though. (In an USB key plug on my TV everything is fine)

**P.S.** The log and file sample are there :
[http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=7757](url)
Sorry for double posting but i didn't saw that for bug? from anterior version we need to post here...

**EDIT** : It is streaming and displaying fine with Twonky Server.

**Comment by Sami32** [comment]
TRACE 2016-05-17 00:31:05.734 [New I/O worker #2] Matched support line f:flac          m:audio/flac
TRACE 2016-05-17 00:31:05.734 [New I/O worker #2] File "recit24bit.flac" will be sent with MIME type "audio/flac"
TRACE 2016-05-17 00:31:05.750 [New I/O worker #2] Adding "recit24bit.flac" to transcode folder for player: "null"
TRACE 2016-05-17 00:31:05.750 [New I/O worker #2] Adding new child "recit24bit.flac" with class "net.pms.dlna.FileTranscodeVirtualFolder"
TRACE 2016-05-17 00:31:05.750 [New I/O worker #2] **Detected secondary format "AudioAsVideo" for "recit24bit.flac"**

[ums_dbg_FLAC.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/267333/ums_dbg_FLAC.zip.txt)

**Comment by SubJunk** [comment]
Ah yeah this is something we did for PS3 since it will only support 24-bit FLAC when it's muxed with a video. I guess we need to hide that for other renderers :)

**Comment by Sami32** [comment]
@SubJunk Oh i see...i guess support so many renderers can give you some headaches ;-)
Thank you for answering.

Did i need to close this subject or i leave it to you ?

**Comment by SubJunk** [comment]
I think we should keep it open and hopefully one of us will have time to look into it :) yeah all the renderers have their own quirks, can be interesting working around them

**Comment by SubJunk** [comment]
I think this is fixed for the next release, please confirm after testing it :)

**Comment by Sami32** [comment]
@SubJunk Thank you for the fix :+1: 
You did it !
It's displaying correctly now :-)

**Comment by SubJunk** [comment]
Awesome, thanks for confirming :)
