### ISSUE TITLE
.MPG and .TS records files don't stream without transcoding

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#882]
Hello,

i am **not able to stream .MPG files without transcoding** on my Panasonic TV, but they are playing fine with my USB key.
And **.TS files coming from my recorder (H264-EAC3-Teletext-Audio channels) are not streamed** as well.

LOGs and sample files are there :
[http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=7757](url)

**P.S.** The .TS and .M2TS files make with a converter tools are streaming fine though.
I use UMS 5.5.0 with MediaInfo.dll 0.7.83 and UMS 6.2.0 (but without working Renderer's GUI panel) since the later versions are not working fine for me, so i apologize if these problems was solved in the latest version.

**Comment by valib** [comment]
I have also a Panasonic TV and it seems to me that it supports the .MPG which has the GOP set to the N=5 or something like that (there is not a specification we can check). Your samples have the GOP N=12 so they are also not working for me and have to be transcoded. We need some more investigation to figure out how to set it properly.

**Comment by Sami32** [comment]
Hello Valib,
thank you for you answer.

But i tested with a VOB file, GOP n=12, and it's streaming fine without transcoding.
[http://www.universalmediaserver.com/forum/download/file.php?id=3179](url)

**Comment by valib** [comment]
This is the problem that nobody knows what exactly Panasonic supports. The last file you provided works also for me so the problem is maybe somewhere else. I see that the video MPGE2-AC3-2ch.mpg has resolution 1280x720 which is definitely supported by my TV. The MPEG2-AC3-2ch.vob is working because it has resolution 720x576. But there are several combinations of the video and audio formats which the particular renderer can support or not so is almost impossible to made setting to allow for all. For that cases there are the TRANSCODE folder to try if streaming is working.

**Comment by Sami32** [comment]
Thank you for your comments. You make a point, i will test more with standard sized video MPG and report the results here.
I use TRANSCODE folder first, but i did get same result, sadly.

And for standard .TS file not streaming without transcoding (transcode TS to TS !) while some .TS and .M2TS are working fine, any idea ?

**Comment by valib** [comment]
@Sami32  .TS, .M2TS, .VOB, MKV etc.are only containers. Whether or not the video will be streamed depends on the specific combination of video and audio codecs used for media coding.

**Comment by Sami32** [comment]
Actually, as you can see in my log, it standard TV record from my STRONG recorder, so it is why i am asking...and yes i did know that it is container ;-)

About the MPEG files, no way, i did tried with 1920x1080 and PAL format without success, so the problem need to be somewhere else, since the DLNA formats indicate in the manual are telling it can do it ( on this model the supported formats for DLNA and USB are near the same ).

But i don't desesperate to find a way ;-)

**Comment by valib** [comment]
@Sami32 can you provide the info about files which Twonky streams and UMS not?

**Comment by Sami32** [comment]
Of course. As i don't know what service you like more i will use WeTransfer since it's too big for attachments.
[https://we.tl/agK0V8wgAH](url) ( 8.7 MB until 2 may 2016 )

After some tests i saw that **TS and M2TS** files was streamed "without" problem if they have 188 **Bytes packets**. For the 192 Bytes packets i am again trying to understand why sometimes it's possible to stream them without transcoding and sometimes not ( i saw that the _Continuity Counter_ was set to 0 when it was working but...)

I try to solve TS and M2TS problems first, but **any WAV files will not give any sound at all** :-(
I only tested with _audio/L16_ and _audio/wav_ MIME type, but i fing strange than i am the only one that meet this problem, maybe specific to this model of Panasonic TV ? because i used the default UMS configuration as well as mine with same result on all the UMS version tried.

I saw also that officials .**MTS files (Panasonic container) was transcoded because of the bitrate limitation fixed to 15000000, but Panasonic can support 17200000** without problem as far as i tested on my Panasonic Viera TX-L32E6E with their official "partnership" _Twonky Server_.
[https://we.tl/fCbLVPnXnm](url) (8.69 MB until 2 may 2016 )

**Comment by Sami32** [comment]
Closed #882
MPEG1 and some M2TS files **was simply not supported by my Panasonic TV**.

I didn't know about the bitrate limitation calcul, i mean that i need to divide by 2 the value of the maximum bandwith (30 MB/s by default for a wireless connexion ), that why i was buggering you with that...**my apology**
