### ISSUE TITLE
Vizio M55-C2

### ISSUE THREAD

**Issue by jaruba** [UniversalMediaServer/UniversalMediaServer#883]
A friend ( @KsaRedFx ) tested UMS on a Vizio M55-C2 4K SmartTV. It detected it as Nokia N900.

In `Vizio-SmartTV.conf` you currently have:
```
UserAgentSearch = IPI/1.0 UPnP/1.0 DLNADOC/1.50
```

This TV responded with:
```
User-Agent=GUPnP/0.12.8 UPnP/1.0 DLNADOC/1.50
```

Changing `Vizio-SmartTV.conf` to:
```
UserAgentSearch = GUPnP/0.12.8 UPnP/1.0 DLNADOC/1.50
LoadingPriority = 1
```

Finds the TV correctly. The reason it was detected as Nokia N900 is because `Nokia-N900.conf` is checking for: `UserAgentSearch = GUPnP`

**Comment by KsaRedFx** [comment]
This definitely works for me and my Vizio TVs 

Now it matches my TV instead of a Nokia phone.

**Comment by SubJunk** [comment]
Thanks for the comments guys, this is added in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/c2792b9ec762c3e349a208ce07c90bb6274f8024

**Comment by jaruba** [comment]
@SubJunk Wouldn't it need `LoadingPriority = 1` too? As Nokia will still be found, and we can't be sure which is detected first, but as Nokia is out of production, Vizio should have priority.

**Comment by SubJunk** [comment]
@jaruba we have a fix coming in the next version that will probably make this unnecessary since it will match the UpnpDetailsSearch line, but just in case I'll add the LoadingPriority too
