### ISSUE TITLE
Add KEY_HIDE_SUBS_INFO to NEED_RELOAD_FLAGS 

### ISSUE THREAD

**Issue by edipoReboucas** [UniversalMediaServer/UniversalMediaServer#885]
Hi guys,

I have some bad time configuring the hide_subs_info on my pc, all of this because this is not reloaded at the server restart.

Browsing the code I see to achive this a developer should put the constant `KEY_HIDE_SUBS_INFO`on `NEED_RELOAD_FLAGS` of `PmsConfiguration`  Class.
 
Because this option not have a GUI, I belive that should reloaded at the server restart.

**Comment by valib** [comment]
Thanks for the input I will implement it.

**Comment by valib** [comment]
Fixed in 2ff5e14af9666ead0132bb81fef23fd7eb720ebc
