### ISSUE TITLE
A JPEG thumbnail not displayed

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#886]
Hello,

This time i tested if it was fine with _Twonky Server_ before posting here.
UMS (used different versions with different Java versions), **don't display one ;-) photo thumbnail**.
![lune72](https://cloud.githubusercontent.com/assets/18471069/15025305/8df98046-1230-11e6-8f20-de5fcc91de94.jpg)

Debug files are posted here :
[http://www.universalmediaserver.com/forum/download/file.php?id=3203](url)
It is the kind of photos, as progressive JPEG, that are not widely supported by renderers, so it is nice to have a thumbnail.

**Comment by cdenney9100** [comment]
On May 4, 2016 11:55 AM, "Samuel" <notifications@github.com> wrote:
>
> Hello,
>
> This time i tested if it was fine with Twonky Server before posting here.
> UMS (used different versions with different Java versions), don't display
one ;-) photo thumbnail.
>
> Debug files are posted here :
> http://www.universalmediaserver.com/forum/download/file.php?id=3203

> It is the kind of photos, as progressive JPEG, that are not widely
supported by renderers, so it is nice to have a thumbnail.

**Comment by valib** [comment]
This is a really strange format not supported by Java which makes an error as you can see in your log.

**Comment by Sami32** [comment]
Thank you very much for you answer.
OK, so i understand why Twonky can display a thumbnail if it's a Java problem.

Actually i have only this photo dowloaded from Internet so i don't really mind, but all my photos are mixed up and when i tested UMS i discover what format are supported on my renderer and what are not.
Since i am a newbie i did think that it could be a UMS problem...just trying to help improve :/

Regards
