### ISSUE TITLE
Parsing WAV files give wrong MIME type

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#887]
**With _MediaInfo = false_ :**
Parsing results for file "ChillingMusic.wav": container: null, bitrate: 1411, size: 4834942, audio tracks: 1, video codec: null, duration: 00:00:27.00, width: 0, height: 0, frame rate: null, **mime type: audio/wav**, attached fonts: false
	Audio track id: 0, lang: null, audio codec: wav-riff 16 bits, sample frequency:44100, number of channels: 2, bits per sample: 16

**With _MediaInfo = true_**
Parsing results for file "ChillingMusic.wav": container: wav, bitrate: 1411250, size: 4834942, audio tracks: 1, video codec: und, duration: 00:00:27.00, width: 0, height: 0, frame rate: null, **mime type: audio/mpeg**, attached fonts: false
	Audio track id: 0, lang: und, audio codec: lpcm, sample frequency:44100, number of channels: 2, bits per sample: 16

Whatever, if we didn't look at the LOG file we will never know, since there are playing, streaming fine.

If it could help...
MediaInfo : [Example.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/270262/Example.txt)
[ums_dbg_Freezing.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/287767/ums_dbg_Freezing.zip.txt)

**Comment by Sami32** [comment]
Could this explain why WAV (_x-wav_) are not supported and transcode to MP3, and this special FLV configuration ? Again some tricks for PS3 ?

(**WebRender.java**)
> @Override
> 	public boolean load(File f) {
> 		// FIXME: These are just preliminary
> 		configuration.addProperty(MEDIAPARSERV2, true);
> 		configuration.addProperty(MEDIAPARSERV2_THUMB, true);
> 		configuration.addProperty(SUPPORTED, "f:flv v:h264|hls a:aac m:video/flash");
> 		configuration.addProperty(SUPPORTED, "f:mp4 m:video/mp4");
> 		configuration.addProperty(SUPPORTED, "f:mp3 n:2 m:audio/mpeg");
> **//		configuration.addProperty(SUPPORTED, "f:wav n:2 m:audio/wav")**;
> 		configuration.addProperty(SUPPORTED, "f:jpg m:image/jpeg");
> 		configuration.addProperty(SUPPORTED, "f:png m:image/png");
> 		configuration.addProperty(SUPPORTED, "f:gif m:image/gif");
> 		configuration.addProperty(SUPPORTED, "f:tiff m:image/tiff");
> 		**configuration.addProperty(TRANSCODE_AUDIO, MP3**);
> 		return true;
> 	}

**Comment by valib** [comment]
@Sami32 please don't mix Panasonic Viera and other renderers with the web interface.

**Comment by Sami32** [comment]
@valib https://github.com/UniversalMediaServer/UniversalMediaServer/files/287767/ums_dbg_Freezing.zip.txt

**Comment by Sami32** [comment]
_DLNAMediaInfo.java_ ?
```
} else if (codecA.startsWith("pcm") || codecA.contains("wav")) {
	mimeType = HTTPResource.AUDIO_WAV_TYPEMIME;
}
```
