### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by caluml** [UniversalMediaServer/UniversalMediaServer#889]
With a clean checkout of the project, and .m2/ deleted, I get the following error:
mvn clean verify
<snip>
[ERROR] Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:6.3.0: The following artifacts could not be resolved: jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13, mediautil:mediautil:jar:1.0, sevenzip:jbinding:jar:4.65-1.04-RC, sevenzip-allplatforms:jbinding-allplatforms:jar:4.65-1.04-RC: Could not find artifact jwbroek.cuelib:cuelib:jar:1.2.1-2008-06-13 in google-gson (https://google-gson.googlecode.com/svn/mavenrepo/) -> [Help 1]

$ uname -a
Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
$ java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/maven
Java version: 1.8.0_72-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"

**Comment by SubJunk** [comment]
@caluml did you figure this out? To build it, I run:

```
mvn external:install
mvn -P linux package
```

Feel free to re-open if that doesn't work
