### ISSUE TITLE
WMV9 'weird' videos thumbnails

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#890]
Hello,

About **WMV9 (VC1) videos files** : **with Mplayer i get black thumbnails**, whatever the seeking position are, and **a 'weird' grey one with some black points without using MPlayer**.

I guess that will be the same for all the WMV9 but just in case i leave you the parsing results : ( i didn't test with other kind of WMVs since my TV don't support it)

Parsing results for file "WMV9-VC1-WMAPro-2ch.wmv": container: wmv, bitrate: 1577106, size: 1394359, video tracks: 1, audio tracks: 1, subtitle tracks: 3, video codec: vc1, duration: 00:00:07.00, width: 640, height: 480, frame rate: 29.970, mime type: video/x-ms-wmv, attached fonts: false
	Audio track id: 0, lang: en, audio codec: WMA, sample frequency:44100, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\WMV9-VC1-WMAPro-2ch.srt, external file character set: ISO-8859-1
	Subtitle track id: 101, type: MICRODVD, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\WMV9-VC1-WMAPro-2ch.sub, external file character set: ISO-8859-1
	Subtitle track id: 102, type: TEXT, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\WMV9-VC1-WMAPro-2ch.txt, external file character set: ISO-8859-1

Parsing results for file "WMV9-WMApro-2ch.asf": container: wmv, bitrate: 1577106, size: 1394359, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: vc1, duration: 00:00:07.00, width: 640, height: 480, frame rate: 29.970, mime type: video/x-ms-wmv, attached fonts: false
	Audio track id: 0, lang: en, audio codec: WMA, sample frequency:44100, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\WMV9-WMApro-2ch.srt, external file character set: ISO-8859-1

Nothing to worry about though since the videos are streamed fine, but just letting you know.
Also i notice a **weird thumbnail comportment with video files with @4.1 or @5.1 AVC profile**.
Changing the seeking time to 1s give me all the thumbnails, MPlayer one of them, 2s give only one of them and 4s none of this two (default white arrow in a white circle when they are not)
[AVC_4.1.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/253558/AVC_4.1.txt)
[AVC_5.1.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/253559/AVC_5.1.txt)
[debug.log_TS-H264-B41-AC3-2ch.ts.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/253561/debug.log_TS-H264-B41-AC3-2ch.ts.txt)

N.B. A mix of short seeking time and MPlayer i can get them all, just letting you know about that strange thing...happen to someone else ?
They are streamed correctly without transcoding to my Panasonic TV though.
I agree that WMVs files are not so communs.

**Comment by valib** [comment]
@Sami32 How can you obtain thumbnails for 4s when the duration of video is 2s 2ms for AVC_4.1 and 3s 170ms for AVC_5.1? Also WMV9-VC1-WMAPro-2ch.wmv i  very short. Only 7s.

**Comment by Sami32** [comment]
Thank you very much for your answer.

Yes, all my test files are =< 12s, but this one are much shorter as i used
a free version of converter on the 12s sample i had...

Do you think it's why i cannot obtain a thumnail with 2s seek time on a
2s2ms video file ? It's make sens.

But why *when i choose 1s seek time i don't get thumbnail for the @5.1
profile* ? Since it give thumbnail with 2s seeking time, why not with 1s ?

Regards,
Samuel

2016-05-11 11:20 GMT+01:00 Libor Vala <notifications@github.com>:
