### ISSUE TITLE
Cover Art / Album Art parsing and displaying problem under Windows XP SP3

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#892]
![e1ee5d98-1618-11e6-9abf-fb7d5405806b](https://cloud.githubusercontent.com/assets/18471069/15695518/f50c4fa0-279f-11e6-807f-c0b5e88dea69.gif)

**Audio files** are played fine, but **their thumbnail are not displayed** in the _browser part_, with the latest version of UMS ( i tested MP3, WAV and FLAC only ), but they are in the _player part_.
It could have something to do with parser or Thumbnailator ?

Debug log : 
[UMS-debug_MPEG1.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/286695/UMS-debug_MPEG1.log.txt)

**EDIT** : Many times it can give _Error adding child_ with a Java memory problem in the LOG.
Maybe related to TIFF thumnails not displayed and this error affecting all files with thumbnail included, meaning not only audio files but MP4 as well, as far as i tested.
Do upgrading _Thumbnailator_ to the latest version will solve it ?

**Comment by Sami32** [comment]
I **narrow it to the commits done for the 6.1.0 version, after the 6.0.1 version**.
Maybe the one in _PmsConfiguration.java_ https://github.com/UniversalMediaServer/UniversalMediaServer/commit/4b4d7d20bf88c095974e0aa26df65b9fd4d9bbe6
Or in _DLNAMediaInfo.java ? or in new tables add ?

**Comment by Sami32** [comment]
In fact, downgrade to MediaInfo 0.7.81 did the trick, but it's just a workaround.
But i don't know if it a coding problem or Base64 support problem, maybe specific to Java 7 ? Windows ?

**Comment by Sami32** [comment]
???
```
import org.apache.commons.codec.binary.Base64;
import org.apache.commons.codec.binary.StringUtils;

public String decode(String s) {
    return StringUtils.newStringUtf8(Base64.decodeBase64(s));
}
```

**Comment by valib** [comment]
@Sami32 can you provide the WAV sample with embedded CoverArt? It seems that I am not so familiar with Google to find any. :disappointed:

**Comment by Sami32** [comment]
@valib I didn't found as well, so i created myself for test purpose trying to identify this issue.
I used this free usefull very little Windows extension http://www.softpointer.com/AudioShell.htm.
https://trac.ffmpeg.org/ticket/5700
https://we.tl/WToDrny29u

**Comment by valib** [comment]
@Sami32 thanks. I am not sure if the tag produced by this Windows extension is correct when also Windows 10 doesn't show the Cover Art. But what is funny the MediaInfo read it. Unfortunately the jaudiotagger (not the FFmpeg) used in the UMS has a problem to read the tag for WAV files.

**Comment by Sami32** [comment]
@valib Thanks for confirming that jaudiotagger was used :-) I did a post sometime ago http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=8353 while search about this issue.
So perhaps that what's happen to the others audio files with CoverArt as well ?
This FLAC file was downloaded as it:
[2L-111_15_stereo-44k-16b.flac.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/392433/2L-111_15_stereo-44k-16b.flac.txt)

**P.S.** I can make it with MP3Tag as well if you want.
Some software insert it at the beginnning, and some at the end of the file so maybe that could be why ? AFAIK, the 2 ways are correct but i didn't even though about this issue from that point of view, so your eagle eyes are welcome ;-)

I joint you an other sample made with the lovely russian _TagScanner_ program:
[ChillingMusic.wav.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/392431/ChillingMusic.wav.txt)

**Comment by Sami32** [comment]
@valib I tried with this new WAV file made by TagScanner, the CovertArt don't get displayed as well BUT no more `Error adding child` since the CovertArt is not recognized...
So you remark helped to give a new light on that issue, thanks ;-D

**Comment by Sami32** [comment]
@valib How did you tested with jaudiotagger ? with UMS ? teach me, please.

I found that https://bitbucket.org/ijabz/jaudiotagger/issues?q=WAV+ meaning that the 2.0.3 version from february 2015 used by UMS is anterior to the one beggining WAV and AIF support in november 2015, 2.25 or 2.2.6

**Comment by Sami32** [comment]
It's look like a Windows XP (SP3) issue.

**Comment by Nadahar** [comment]
@Sami32 Why do you close it because it's a XP issue? It's not really an XP issue, it's a MediaInfo issue with Windows XP.

**Comment by Sami32** [comment]
@Nadahar It's look like @valib doesn't like XP, it so i can close it and work for myself when i'll have the motivation to work on it again and find how to make it work.

**Comment by Nadahar** [comment]
@Sami32 In my view an issue should stay open until it's either fixed or definitly dismissed.

**Comment by valib** [comment]
@Sami32 I agree with @Nadahar that this is not a WIN XP problem. And WIN XP itself is only my problem please take it easy. To this project I am only contribution and it is on @SubJunk to decide how we continue. Anyway thanks for the finding but you a little bit confused me by pointing to the "bliss" which is not free project. That's why I missed  https://bitbucket.org/ijabz/jaudiotagger which can be used in version 2.2.5 (officially supported version is 2.2.3) and it seems to me it solve this issue when `MediaInfo=false` and in this case the jaudiotagger is used. Committed in 6b82f5c

**Comment by Sami32** [comment]
@valib I admit that I overreact, your commercial speach for the second time just pissed me off.

Thanks for the update, now that i saw how you did it i will be able to do it the next time.
Btw, now WAV coverart are displayed as expected :-)

**P.S.** Honestly i use UMS few times and very simply to see one movie sometime, that's all.
So, if i do these testings it's really not for my myself.

**Comment by valib** [comment]
@Sami32 OK. I promise that I will no longer comment the unsupported OS's. :smile:

**Comment by Sami32** [comment]
Should be solved by that PR: https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1061
