### ISSUE TITLE
WMV2 and WMV3 are not distinctly parsed

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#894]
Hello,

i just discovered that the **parsing was not making any difference when the codec, as indicate by MediaIfo, was WMV3 or WMV2 in WMV video files**.

The consequence are that when some TV, like my Panasonic, are able to support WMV 9 (WMV3) only, we need to make choice between transcode all the WMVs files or don't transcode them at all.

Regards,

**N.B.** Maybe it is possible but not documented ? like VC1|WMV2|WMV3 ?

**Comment by valib** [comment]
@Sami32 VC1 is supported for video format and it is used for WMV9 and WMV3. WMV is used for WMV1, WMV2, WMV7 and WMV8. So simply delete the WMV  in the video setting like 
`Supported = f:wmv|asf       v:vc1             a:aac|aac-he|ac3|eac3|lpcm|mp3|wma                 m:video/x-ms-wmv`

**Comment by Sami32** [comment]
@valib I didn't know about that...
Thank you very much for your help :-D

**Comment by SubJunk** [comment]
We should add this info to our DefaultRenderer.conf if it's not there already
