### ISSUE TITLE
Error writing to ffmpeg.exe

### ISSUE THREAD

**Issue by rlwieneke** [UniversalMediaServer/UniversalMediaServer#895]
I was installing universal media server and ran into this problem repeatedly. Tried the same installation file on another XP machine and had no problem. This is XP embedded on a thin client if that makes any difference. I've installed lots of software on thin clients and never ran into any problems before this.

![error writing to file ffmpeg_exe](https://cloud.githubusercontent.com/assets/19426131/15353138/15c6c8b8-1cad-11e6-8289-07f7ac3b0742.JPG)

**Comment by SubJunk** [comment]
Can you run the installer as administrator?

**Comment by rlwieneke** [comment]
this is logged in as Administrator. I disable hp Logon Manager on all my thin clients so I can log on as Administrator every time and have full access to operating system resources that are denied to User.
