### ISSUE TITLE
FFmpeg doesn't use the -qmax and -qmin

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#897]
FFmpeg is using the quantizer 2-31 instead of the -qmin and -qmax for the MPEG-PS transcoding. For the video I tested to transcode the FFmpeg set the quantizer to 31 which is out of bounds we set. Does anybody knows what was changed in FFmpeg?

**Comment by Sami32** [comment]
@valib Could this be related to your problem ?
https://trac.ffmpeg.org/ticket/5642

**Comment by valib** [comment]
Wrong reading of the FFmpeg manual.
