### ISSUE TITLE
disconnect and slow

### ISSUE THREAD

**Issue by ShipShap3** [UniversalMediaServer/UniversalMediaServer#898]
Just got UMS on my new W10 PC and I use it with my PS4.
Sometimes UMS does not show when I'm in the Media Player on PS4.  I restart the server via the app on my PC and sometimes it works.  Other times it doesn't.
During install I went with all the default settings except for hiding the transcode folder and recently viewed folder.
Any settings on either device I should be looking at?

My roommate has a tablet that shows up on devices in the app on my PC.  How do I set it up so it only looks for/uses the PS4?

Some videos don't play.  It starts and the sound is there with only the circle rotating in the middle.  Then after about 15 seconds it says file cannot be played.
They are episodes from a TV show I have on my PC and some of them do play but most don't.  I believe they are all the same format.
Any suggestions?

**Comment by valib** [comment]
@ShipShap3 please follow the instruction at http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by ShipShap3** [comment]
I will do as advised tomorrow and send you the file or screen shots, but as one of my problems is that I can't get UMS to connect to my PS4 at times I'm not sure what the log would show as the error would not happen.
Please Know that my main problem is that UMS disconnects from my PS4 while I'm watching a movie from my PC.

**Comment by valib** [comment]
` My roommate has a tablet that shows up on devices in the app on my PC. How do I set it up so it only looks for/uses the PS4?`

You can set the PS4 IP address in "Use an IP filter (whitelist)" at the General Configuration tab. Addresses listed there are only allowed to see and connect to the UMS.

**Comment by ShipShap3** [comment]
> You can set the PS4 IP address in "Use an IP filter (whitelist)" at the General Configuration tab. Addresses listed there are only allowed to see and connect to the UMS.

Thank You that worked.  Now ONLY the PS4 is showing up.  I'm still going to do the log but I wonder if that might be why it was disconnecting.

**Comment by ShipShap3** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/280761/ums_dbg.zip)

I hope this is how I was supposed to do it.
*note at the 19:21 mark the media I was playing froze.  It eventually said cannot play media.  When I went back to the screen with the list of videos every other one was marked as unplayable.  I closed media player on PS4 and started it back up and it all plays fine.

So I'm thinking UMS restarted or whatever it does sometime during packing or zipping the files because it was about then that the video froze.

**Comment by ShipShap3** [comment]
I just got D/C again while watching a movie.  Trace stuff was still on so I just copy and pasted the last bit here.
22:47:36 DEBUG Sending ALIVE...
22:47:36 TRACE Access denied for address /192.168.1.6 based on IP filter
22:48:06 DEBUG Sending ALIVE...
22:48:07 TRACE Access denied for address /192.168.1.6 based on IP filter
22:48:32 TRACE Calling SetThreadExecutionState ES_CONTINUOUS
22:48:36 DEBUG Matched media renderer "PlayStation 4" based on address /192.168.1.15
22:48:36 INFO  Stopped playing Neighbors 2.mkv on your PlayStation 4
22:48:36 DEBUG The full filename of which is: C:\Users\Scott\Desktop\New Downloads\Neighbors 2.mkv and the address of the renderer is: 192.168.1.15
22:48:36 DEBUG Resume stop. This segment 275287 new time 275287
22:48:36 TRACE    final decision: not fully played
22:48:36 DEBUG Sending ALIVE...
22:48:36 TRACE Access denied for address /192.168.1.6 based on IP filter
22:49:06 DEBUG Sending ALIVE...

FULL FILE here:
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/280965/ums_dbg.zip)

**Comment by valib** [comment]
@ShipShap3 to you comments 7 hours ago. It seems to me that PS4 was playing media from its buffer and didnt recognize that UMS was off. When you started UMS again the PS4 was requesting not existed media ID see e.g. 

TRACE 2016-05-24 19:20:28.125 [New I/O worker #12] net.pms.network.RequestHandlerV2 Request: HTTP/1.1 : GET : get/439/Over+There+-S1+Ep1.avi
DEBUG 2016-05-24 19:20:28.125 [New I/O worker #12] net.pms.configuration.RendererConfiguration Matched media renderer "PlayStation 4" based on address /192.168.1.15
TRACE 2016-05-24 19:20:28.125 [New I/O worker #12] net.pms.network.RequestHandlerV2 Received on socket: Range: bytes=207994864-
TRACE 2016-05-24 19:20:28.125 [New I/O worker #12] net.pms.network.RequestHandlerV2 Received on socket: Host: 192.168.1.14:5001
TRACE 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.network.RequestHandlerV2 Received on socket: User-Agent: MediaPlayer/1.50 libhttp/3.50 (PlayStation 4)
TRACE 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.network.RequestHandlerV2 Received on socket: Connection: Keep-Alive
TRACE 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.network.RequestHandlerV2 HTTP User-Agent: MediaPlayer/1.50 libhttp/3.50 (PlayStation 4)
TRACE 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.network.RequestHandlerV2 Recognized media renderer: PlayStation 4
TRACE 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.network.RequestHandlerV2 HTTP: get/439/Over+There+-S1+Ep1.avi / 207994864--1
DEBUG 2016-05-24 19:20:28.126 [New I/O worker #12] net.pms.dlna.GlobalIdRepo **GlobalIdRepo: id not found: 439`**

**Comment by ShipShap3** [comment]
I don't know what that means.  If you're referring to when the video froze then OK.

My last post before this one is the main problem that I keep having where all of a sudden the video stops playing and my PS4 kicks me out to the Media Player screen indicating that nothing is attached to it.  No USB or Media server detected.
When this happens, sometimes closing the Media Player app on PS4 and restarting it will work but other times UMS is still not detected.  When THIS happens, on the PC it still shows the PS4 but when I exit UMS and restart it I am told that no renderers are found.
Let me also note that ALL of these problems occurred AFTER there was an update to UMS installed.  I do not know how to revert back to the version or get logs from the previous version.  When I get home from work tonight I'm going to uninstall and reinstall UMS to see if that helps.  If it doesn't then I'm done with UMS.

**Comment by valib** [comment]
@ShipShap3 you can download previous versions at https://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Windows/ Can you please try the version 6.3.0 or 6.2.2 ? We rely on the users support to be able to recognize what is going on.

**Comment by ShipShap3** [comment]
@valib I have been using version 6.3 and it has been since then that this issue of disconnecting has been happening so I'm going to try an earlier version.  The one I was using before the update that actually let me watch an entire show for more 15 minutes.

I have attached the latest log which did capture the disconnect which is at the end of the log and I also would like to note that it took quite a bit of time and several restarts of UMS before it even located my PS4 as a renderer which I have isolated as the only device that it will look for based on the IP settings (whitelist) in the General Tab.


[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/285608/ums_dbg.zip)

**Comment by SubJunk** [comment]
This finally happened to me tonight, I got this in the logs:

```
DEBUG 2016-06-08 21:12:47.299 [New I/O worker #9] Connection error: java.io.IOException: An established connection was aborted by the software in your host machine
DEBUG 2016-06-08 21:12:47.299 [New I/O worker #9] Premature end, stopping...
TRACE 2016-06-08 21:12:47.300 [New I/O worker #9] Calling SetThreadExecutionState ES_CONTINUOUS
DEBUG 2016-06-08 21:12:47.300 [UPNP-VIERA VT60 Series] Action failed: Error: Current state of service prevents invoking that action. Connection error or no response received.
DEBUG 2016-06-08 21:12:48.248 [UPNP-VIERA ST50 Series] Action failed: Error: Current state of service prevents invoking that action. Connection error or no response received.
INFO  2016-06-08 21:12:50.360 [UPNPHelper] No IP filter specified, access granted to /192.168.20.28
TRACE 2016-06-08 21:12:50.361 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
TRACE 2016-06-08 21:12:53.601 [UPNPHelper] Sending discovery [192.168.20.28:63028]: HTTP/1.1 200 OK<CRLF>CACHE-CONTROL: max-age=1200<CRLF>DATE: Wed, 08 Jun 2016 09:12:53 GMT<CRLF>LOCATION: http://192.168.20.38:5001/description/fetch<CRLF>SERVER: Windows_7-amd64-6.1, UPnP/1.0, UMS/6.3.3-SNAPSHOT<CRLF>ST: urn:schemas-upnp-org:device:MediaServer:1<CRLF>EXT: <CRLF>USN: uuid:088584e0-681e-47f8-ae4b-a269a4d3ec54::urn:schemas-upnp-org:device:MediaServer:1<CRLF>Content-Length: 0<CRLF><CRLF>
TRACE 2016-06-08 21:12:56.652 [UPNPHelper] Resending last discovery [192.168.20.28:63028]
TRACE 2016-06-08 21:13:04.667 [UPNPHelper] Sending discovery [192.168.20.28:56495]: HTTP/1.1 200 OK<CRLF>CACHE-CONTROL: max-age=1200<CRLF>DATE: Wed, 08 Jun 2016 09:13:04 GMT<CRLF>LOCATION: http://192.168.20.38:5001/description/fetch<CRLF>SERVER: Windows_7-amd64-6.1, UPnP/1.0, UMS/6.3.3-SNAPSHOT<CRLF>ST: upnp:rootdevice<CRLF>EXT: <CRLF>USN: uuid:088584e0-681e-47f8-ae4b-a269a4d3ec54::upnp:rootdevice<CRLF>Content-Length: 0<CRLF><CRLF>
TRACE 2016-06-08 21:13:04.667 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:04.674 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:04.675 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:04.676 [UPNPHelper] Receiving a NOTIFY from [192.168.20.28:56501]
TRACE 2016-06-08 21:13:06.762 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
TRACE 2016-06-08 21:13:08.247 [UPNPHelper] Receiving a NOTIFY from [192.168.20.28:56501]
TRACE 2016-06-08 21:13:09.762 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
DEBUG 2016-06-08 21:13:12.402 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2016-06-08 21:13:12.407 [UPNP-AliveMessageSender] Error sending ALIVE message
java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.DatagramSocket.bind(Unknown Source)
	at java.net.MulticastSocket.<init>(Unknown Source)
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:265)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:192)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:367)
	at java.lang.Thread.run(Unknown Source)
TRACE 2016-06-08 21:13:14.762 [UPNPHelper] Receiving a NOTIFY from [192.168.20.28:56501]
TRACE 2016-06-08 21:13:15.786 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
TRACE 2016-06-08 21:13:19.565 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:19.566 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:19.566 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:19.566 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:32.888 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:13:32.889 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
DEBUG 2016-06-08 21:13:42.408 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2016-06-08 21:13:42.408 [UPNP-AliveMessageSender] Error sending ALIVE message
java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.DatagramSocket.bind(Unknown Source)
	at java.net.MulticastSocket.<init>(Unknown Source)
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:265)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:192)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:367)
	at java.lang.Thread.run(Unknown Source)
TRACE 2016-06-08 21:13:44.777 [UPNPHelper] Receiving a NOTIFY from [192.168.20.28:56501]
TRACE 2016-06-08 21:13:46.280 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
DEBUG 2016-06-08 21:14:12.408 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2016-06-08 21:14:12.408 [UPNP-AliveMessageSender] Error sending ALIVE message
java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.DatagramSocket.bind(Unknown Source)
	at java.net.MulticastSocket.<init>(Unknown Source)
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:265)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:192)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:367)
	at java.lang.Thread.run(Unknown Source)
TRACE 2016-06-08 21:14:14.791 [UPNPHelper] Receiving a NOTIFY from [192.168.20.28:56501]
TRACE 2016-06-08 21:14:27.233 [UPNPHelper] Receiving a M-SEARCH from [192.168.20.28:63028]
TRACE 2016-06-08 21:14:32.902 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
TRACE 2016-06-08 21:14:32.903 [UPNPHelper] Resending last discovery [192.168.20.28:56495]
DEBUG 2016-06-08 21:14:42.409 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2016-06-08 21:14:42.409 [UPNP-AliveMessageSender] Error sending ALIVE message
java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.TwoStacksPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.DatagramSocket.bind(Unknown Source)
	at java.net.MulticastSocket.<init>(Unknown Source)
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:265)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:192)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:367)
	at java.lang.Thread.run(Unknown Source)
```

It will be good when we figure out what has caused this.
Some users have reported it has been fixed for them by reinstalling Java, I hope that's not the fix.

**Comment by SubJunk** [comment]
@ShipShap3 do you have any updates on this issue? Is it still happening for you?

**Comment by SubJunk** [comment]
It may be too soon to tell, but since I rolled back JRE on my machine to 8u77 I haven't had any disconnections. I'll keep testing.
