### ISSUE TITLE
MP4S parsing

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#901]
UMS **don't differentiate MP4 formats : MP43** (unsupported as well as MP42 and MP41) **and MP4S** (supported by Panasonic Viera) codec ID. ( I read that Microsoft MP4 codec identified as M4S2 is also supported but i don' have converter for test this codec )
MediaInfo datas :
[MP43.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/284937/MP43.txt)
[MP4S.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/284938/MP4S.txt)

It's a minor issue, but just letting you know about.
If it's too cumbersome or slow the scanning process, just close this issue.

**Comment by valib** [comment]
@Sami32 I couldn't find any MP43 or MP4S video samples for testing. Can you provide some?

**Comment by Sami32** [comment]
@valib You are welcome.
I used _AVS converter_ for testing purpose to determinate why the manual tell that MP4 codec is supported with WMV/ASF and i was not able to do it...
https://we.tl/fHzFSvqKUg
https://www.wetransfer.com/downloads/34a3504df613597125993fb49f54e15b20160527112847/be833accde43d95aef5cdd21e03df6c420160527112847/1797f4
