### ISSUE TITLE
MPEG1 incorrectly parsed

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#903]
@valib Sorry, i didn't know how to reopen this issue...https://github.com/UniversalMediaServer/UniversalMediaServer/issues/900

It didn't solved the problem that **MPEG1 video codec is recognized as MPEG2** in UMS.

> TRACE 2016-05-27 15:32:28.281 [New I/O worker #2] Matched support line f:mpegps        v:mpeg2                   a:ac3|lpcm|mpa                                     m:video/mpeg

[UMS-debug_MPEG1.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/286661/UMS-debug_MPEG1.log.txt)

**Comment by SubJunk** [comment]
@Sami32 you might need to reset your cache on the "Navigation / Share Settings" tab for the fix to work

**Comment by Sami32** [comment]
@SubJunk @valib Yes it worked correctly now ;-)
I didn't know about this _cache_ side, thanks for teaching me.

**Comment by SubJunk** [comment]
@Sami32 great, thanks for confirming :)
