### ISSUE TITLE
TIF/TIFF problems

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#910]
[123.tif.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/300947/123.tif.txt)

1) **Thumbnails are not displayed** for TIF/TIFF images.

> TRACE 2016-06-07 01:40:42.421 [Library Scanner] Matched format TIF to "C:\Program Files\Universal Media Server\win32\FFMPEG_Fix\123-f.tif"
> TRACE 2016-06-07 01:40:42.468 [Library Scanner] Creating (temporary) thumbnail: 123-f.tif
> ERROR 2016-06-07 01:40:42.656 **[Library Scanner] Error adding child: "123-f.tif"
> java.lang.NullPointerException: Image cannot be null**.

**EDIT** : This error was fixed by @valib in PR #911

 Still this kind of problem occur in LOG :
> TRACE 2016-06-11 02:55:18.296 [New I/O worker #1] Creating (temporary) thumbnail: 123.tif
> DEBUG 2016-06-11 02:55:18.312 [New I/O worker #1] **Caught exception: Image cannot be null**.
> TRACE 2016-06-11 02:55:18.328 [New I/O worker #1]
> **java.lang.NullPointerException: Image cannot be null**

https://github.com/UniversalMediaServer/UniversalMediaServer/files/310036/UMS-debug_TIFF-Thumbnails.txt

TIFF thumbnails in Web interface are not displayed either :
```
<li>
                    <a class="webdisabled" href="javascript:notify('warn','This item isn't playable via browser but can be sent to other renderers.')" 
title="123.tif (NOT PLAYABLE IN BROWSER)"><img class="thumb" src="/thumb/1410" alt="123.tif"></a>
                    <a class="bumpIcon" href="javascript:bump.start('//192.168.1.28:9001','/play/1410','123.tif')" title="Play on another renderer"></a>
<a class="playlist_add" href="#" onclick="umsAjax('/playlist/add/1410', false);return false;" title="Add to playlist"></a>
                    <span class="webdisabled caption">123.tif</span>
                </li>
```
Could this be related to https://github.com/UniversalMediaServer/UniversalMediaServer/issues/576 ?

2) **TIF/TIFF are parsed incorrectly** in the Web Interface and UMS; same for GIF, PNG...
**EDIT** : This problem was fixed with the @valib commit https://github.com/UniversalMediaServer/UniversalMediaServer/pull/911/commits/c18e7a216b589b5996df7f1071bdfc6ccd447312
> TRACE 2016-06-09 14:22:42.062 [Library Scanner] Matched format TIF to "C:\Program Files\Universal Media Server\win32\FFMPEG_Fix\123.tif"
> TRACE 2016-06-09 14:22:42.078 [Library Scanner] Could not parse bitrate "": 
> TRACE 2016-06-09 14:22:42.078 [Library Scanner] Parsing results for file "123.tif": container: tiff, bitrate: 0, size: 102266, images: 1, video codec: und, duration: 00:00:00.00, width: 149, height: 171, frame rate: null, mime type: image/jpeg, attached fonts: false

[UMS-debug_TIFF.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/300932/UMS-debug_TIFF.txt)
[ums_dbg_TIFF.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/301134/ums_dbg_TIFF.zip.txt)

**Comment by Sami32** [comment]
Fixed with the latest commits of @valib  in Parsing_Image branch :+1:

**Comment by atamariya** [comment]
Just for record, TIF thumbnail is not supported by ffmpeg in archive files. https://trac.ffmpeg.org/ticket/5561
