### ISSUE TITLE
Re : Parsing WAV files give wrong MIME type

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#913]
See https://github.com/UniversalMediaServer/UniversalMediaServer/issues/887

@valib Half done ;-) but better than me anyway :-)
Now only **WAV files with DTS** give again wrong parsing.

> TRACE 2016-06-11 14:52:49.937 [Library Scanner] Matched format WAV to "C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\TESTS\SURROUNDTEST_DTS-6ch.wav"
> TRACE 2016-06-11 14:52:49.984 [Library Scanner] Parsing results for file "SURROUNDTEST_DTS-6ch.wav": container: wav, bitrate: 1411204, size: 22347820, audio tracks: 1, video codec: und, duration: 00:02:06.00, width: 0, height: 0, frame rate: null, **mime type: audio/mpeg**, attached fonts: false **Audio track id: 0**, lang: und, **audio codec: DTS**, sample frequency:44100, number of channels: 6, bits per sample: 24

[UMS-debug_WAV.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/310274/UMS-debug_WAV.txt)
[WAV_DTS.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/310277/WAV_DTS.txt)

**EDIT** : Do this change in _DLNAMediaInfo.java_ will be correct ?
`} else if (codecA.contains("pcm") || codecA.contains("dts") || codecA.contains("wav")) {`

**Comment by valib** [comment]
@Sami32 yes it works but the question why is it used? The mime type can be parsed simply from the container some lines above.

**Comment by Sami32** [comment]
@valib Since i doesn't understand 1/10 of this Java code, i feel like not confortable...

Do you mean add something like that ?
```
case "wav":
					mimeType = HTTPResource.WAV_TYPEMIME;
					break;
```

Do these DTS change will be more correct ?
```
public boolean isMuxable(String filename, String codecA) {
		return codecA != null && (codecA.contains("dts") || codecA.equals("dca"));
	}
public boolean isLossless(String codecA) {
		return codecA != null && (codecA.contains("pcm") || codecA.contains("dts") || codecA.equals("dca") || codecA.contains("flac")) && !codecA.contains("pcm_u8") && !codecA.contains("pcm_s8");
	}

```

**Comment by valib** [comment]
@Sami32 exactly what I mean :+1:  I think that there is not any difference between both ways. The result always will be the same. The current way seems to be a little bit less efficient :-)

**Comment by Sami32** [comment]
@valib Thanks for your teaching :-) Actually i learn reading your commits ;-)
Since one of your commit concern this line of code i don't want make trouble, so i leave it to you if you want delete this line and add these container lines of code.
I agree that the code will be more clean with this container add.
So, if you do it feel free to close my PR as well.

**Comment by valib** [comment]
@Sami32 you are not making an trouble :-) Your questions are forced me to check the old code from the PMS era whose are also understandable for me.
