### ISSUE TITLE
"Cache" browsing problem

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#915]
I tried to browse the "cache" on my _Panasonic Viera_TV  for the first time and discover that **if more than 20 entries need to be browse by scrolling (including repertories) the displaying become empty and stuck to it** until i use _Return_ on my remote to go up in the tree of repertories.
If i choose to browse up, using up arrow, to go directly to the end of the directory, i get same result : empty displaying.
It give me the **bigger LOG file** ever, 31MB, in few time, so i don't know if it's normal when using "cache" ?
https://www.wetransfer.com/downloads/46f02d07969f40ecf738abb66ed8038c20160612125705/17985dbfcc0ad9eefc3e6b832eb94cdb20160612125705/d78d94
https://we.tl/ckQg9NI7Y2

I hope that i make it understandable...but feel free to ask if not.

**P.S.** I can't remember wich developper suggest to change the name of "cache" in the forum, but i second that :+1: 
Because i discovered that it is well structured, like a "Media Library" or "DataBase" what ever customers like more, and "cache" don't suggest it, do honor to this...Only my opinion.

**Comment by SubJunk** [comment]
There's an issue for this with a lot of discussion at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/653 so please use that one instead. Any help is very appreciated!
I agree that the whole cache browsing feature needs work, it could be much better

**Comment by Sami32** [comment]
@SubJunk Thanks to point me there :-) i missed it...
