### ISSUE TITLE
Problem with Sony TV - Action failed: Error: Action SetAVTransportURI failed  (HTTP response was: 500 Internal Server Error)

### ISSUE THREAD

**Issue by adsoftdd** [UniversalMediaServer/UniversalMediaServer#929]
Hi 

After updating to version 6.3.2 my TV Sony BRAVIA HX700 stop working with UMS

UMS recognizes it in the network, but on the TV server does not appear.

I wanted to run the file directly at the TV from the UMS, but I get an error (in the Annex)
[debug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/324287/debug.zip)

**Comment by cloon77** [comment]
Having same issue with my bravia 42w650

**Comment by adsoftdd** [comment]
Hi

I decided to remove all java in my computer, all copy of UMS and I installed new versions.
Now, I have java 32-bit 1.8.0_91 and UMS 6.3.2 and everything works o.k.


INFO  2016-06-23 16:10:25.256 [main] Starting Universal Media Server 6.3.2
INFO  2016-06-23 16:10:25.257 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  2016-06-23 16:10:25.257 [main] http://www.universalmediaserver.com
INFO  2016-06-23 16:10:25.258 [main] 
INFO  2016-06-23 16:10:25.258 [main] Build: 306b6227d (2016-05-27)
INFO  2016-06-23 16:10:25.258 [main] Java: Java HotSpot(TM) Client VM 1.8.0_91 32-bit by Oracle Corporation
INFO  2016-06-23 16:10:25.258 [main] OS: Windows 10 64-bit 10.0
INFO  2016-06-23 16:10:25.259 [main] Encoding: UTF-8
INFO  2016-06-23 16:10:25.259 [main] Memory: 742 MB
INFO  2016-06-23 16:10:25.267 [main] Language: Polish
INFO  2016-06-23 16:10:25.267 [main]
