### ISSUE TITLE
FFmpeg "-an" parameter put in double while getting video thumbnails

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#937]
When i was inspecting my LOG, i discovered that "-an" parameter was put in double while getting video thumbnails, and since it look weird to me, i report to you just in case...
Is it really a choice, a necessity ? It's doen't affect anything at my knowledge, except in the LOG.
> DEBUG 2016-06-23 15:14:06.718 [Library Scanner] Starting "C:\Program Files\Universal Media Server\win32\ffmpeg.exe" -ss 2 -i C:\DOCUME~1\Philippe\MESDOC~1\TÉLÉCH~1\UMSVID~1\TESTS\data1.wmv **-an -an** -vf scale='if(gt(a,1.78),320,-1)':'if(gt(a,1.78),-1,180)' -vframes 1 -f image2 pipe:

_DLNAMediaInfo.java_

**EDIT** : It's an other subjet, but i am wondering if it's mean that video thumbnails are generate with default values, 320*180, and not the renderer conf values ?

**Comment by SubJunk** [comment]
@Sami32 yeah that sometimes happens but it's okay. I think it respects the renderer conf values
