### ISSUE TITLE
Video files with subtitles get always transcoded

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#938]
**While subtitles are existing, UMS ignore user's renderer conf and transcode the files**.

> TRACE 2016-06-25 22:32:04.453 [Library Scanner] Parsing results for file "TS-AC3-2ch.ts": container: mpegts, bitrate: 5634692, size: 8031360, video tracks: 1, audio tracks: 1, subtitle tracks: 3, video codec: mp4, duration: 00:00:11.00, width: 1920, height: 1080, frame rate: , mime type: video/mp4, attached fonts: false Audio track id: 257, lang: und, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16 Subtitle track id: 100, type: SUBRIP, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\M2TS\TS-AC3-2ch.srt, external file character set: ISO-8859-1
> Subtitle track id: 101, type: MICRODVD, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\M2TS\TS-AC3-2ch.sub, external file character set: ISO-8859-1 Subtitle track id: 102, type: TEXT, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\M2TS\TS-AC3-2ch.txt, external file character set: ISO-8859-1
...
> TRACE 2016-06-25 22:32:05.218 [Library Scanner] Found subtitles track: id: 100, type: SUBRIP, lang: fr, externalFile: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite (20150121)\M2TS\TS-AC3-2ch.srt, external file character set: ISO-8859-1
> TRACE 2016-06-25 22:32:05.218 [Library Scanner] Found external file: C:\Documents and Settings\Philippe\Mes documents\Téléchargements\UMS Video Testing Suite  (20150121)\M2TS\TS-AC3-2ch.srt
> TRACE 2016-06-25 22:32:05.218 [Library Scanner] **This video has external subtitles that should be transcoded**

[UMS-debug_SUBTITLES.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/333305/UMS-debug_SUBTITLES.txt)
[Panasonic-VieraTXL32E6E.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/333310/Panasonic-VieraTXL32E6E.conf.txt)
[UMS.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/333335/UMS.conf.txt)

Same with UMS 6.4.0
[ums_dbg_Subtitles.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/356157/ums_dbg_Subtitles.zip.txt)

It's look like ```
SupportedExternalSubtitlesFormats = SUBRIP,MICRODVD,TEXT
SupportedInternalSubtitlesFormats = SUBRIP,MICRODVD
``` are not taken in consideration in _DLNAResource.java_

**Comment by valib** [comment]
@Sami32 it works for me normally. Your debug.log is strange. You are using the Java version 1.7.0_101 but the latest supported by Oracle is 1.7.0_80. Where did you find that version? There must be something wrong with the Java or UMS installation. The UMS versions are official released or you compile your own?

In both your logs there are much wrong statements `Matched support line f:.+` and e.g. `Final verdict: "TS-AC3-2ch.ts" will be transcoded with player "FFmpeg" with mime type "MIMETYPE_AUTO"` which means that UMS doesn't properly recognized which format is supported by renderer. The propper result must be `Matched support linef:mpegts        v:mp4                      a:aac|aac-he|ac3|eac3|mpa                         m:video/mp4"` in your case.

Recommendation: reinstall Java and use the supported version 1.7.0_80 or for the testing purpose REM the line `Supported = f:aac           m:audio/x-m4a              a:(?!alac).+` in the Panasonic-VieraET60.conf and test it.

**Comment by Sami32** [comment]
@valib Sorry, i didn't updated this issue yet but planned to do it ;-)
Don't worry for the Java version, it is the official correct one. You can download it, but it is delivered mainly for enterprise secutity update.
I found it strange as well and reinstalled UMS, and it was fine.
It's was coming from an other bug that i didn't report yet, that change configuration parameters !

Thanks for looked at it ;-) Give me until tomorrow before closed it, ok ?

**Comment by valib** [comment]
@Sami32 to test our code don't use the officially unsupported Java versions otherwise you make an issues which doesn't exists.

**Comment by Sami32** [comment]
@valib OK i will downgrade, but i strongly suspect that the other bug have nothing to do with Java...but never know.
Maybe you're just jalous about my Java version ! Just kidding ;-)

**Comment by valib** [comment]
@Sami32 for testing we need don't use the Java versions which the standard users are not able to download. Whose other bugs are you speaking about?

**Comment by Sami32** [comment]
@valib I will retest tomorrow with Java 7u80, before report this fucking bug that made that problem and make me do a UMS clean install.
But like you told, better to have the UMS official supported version before reporting this, just in case.

**Comment by Sami32** [comment]
@valib If i compile UMS with Java 7u101 and get no error, will that mean that it is fully compatible ?
I didn't tried yet, but have a skilled advice can help me get a better understanding.

**Comment by valib** [comment]
@Sami32 it is fine but for standard users the only officially supported Java version is available. Please don't use the that officially unsupported versions or you can make a mess.

**Comment by Sami32** [comment]
@valib Thanks for your wise advice ;-)
