### ISSUE TITLE
Canceling scan... ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#945]
I cannot call that a bug though...so like usual feel free to closed this issue if not appropriate.
![capture_07142016_183010](https://cloud.githubusercontent.com/assets/18471069/16849110/e5f994fa-49f0-11e6-9891-39c406ca23ff.jpg)
When **canceling the scan**, it get greyed icon telling "Canceling scan..." for ever until we restart UMS or disable and enable again the "cache".
```
} else {
							int option = JOptionPane.showConfirmDialog(
								looksFrame,
								Messages.getString("FoldTab.10"),
								Messages.getString("Dialog.Question"),
								JOptionPane.YES_NO_OPTION);
							if (option == JOptionPane.YES_OPTION) {
								database.stopScanLibrary();
								looksFrame.setStatusLine(null);
								setScanLibraryEnabled(false);
								but5.setToolTipText(Messages.getString("FoldTab.41"));
							}
						}
```
What i expected ? something like "Scan canceled" because "Canceling scan" make me thinking i need to wait something, and that after some secondes delay the icon greened itself and become automatically ready for an eventual new scan.

I usually do that when i test different renderer's configurations and check the result in the log, so i am interested by what you guys are thinking about that, because maybe i had misused it.

**Comment by valib** [comment]
@Sami32 thanks for this finding.

**Comment by Sami32** [comment]
@valib Lightning fast..as usual :-)
Thanks for this fixing :+1:
