### ISSUE TITLE
UMS website improvement ideas

### ISSUE THREAD

**Issue by polygirl** [UniversalMediaServer/UniversalMediaServer#958]
**Supported OS panel**
- There's an expand arrow on the OS panel, but no contract option to close it again
![screen shot 2016-07-21 at 12 45 08 pm](https://cloud.githubusercontent.com/assets/20376562/17007950/fde86406-4f40-11e6-84ca-b3ae6c9e7aa3.png)

**Support submenu**
- Hovering over the support menu item opens a submenu that obscures the Plugins menu item.  It only closes when you hover over the RSS feed icon which isn't intuitive.  Suggestion to open the item when you click support and close it when you click support again.  At the moment clicking support takes you to a high level support page with the same submenu options.
- The submenu could be repositioned to slide out horizontally from "Support" so it doesn't obscure Plugins at all

![screen shot 2016-07-21 at 12 44 42 pm](https://cloud.githubusercontent.com/assets/20376562/17007942/ee683c9a-4f40-11e6-81c9-a30743eedc1d.png)

**Product screenshot**
- The screenshot opens as an image in a new tab.  Suggest to open in a lightbox with a close X or change to an image carousel.

**Comment by SubJunk** [comment]
@polygirl these are all good suggestions, thanks

**Comment by SubJunk** [comment]
This is all done now
