### ISSUE TITLE
FileChooser not visible when filenames are large

### ISSUE THREAD

**Issue by rghose** [UniversalMediaServer/UniversalMediaServer#960]
![screenshot-ums](https://cloud.githubusercontent.com/assets/5793339/17085212/f5554b62-51a0-11e6-9b6e-3df42f8c77aa.png)
 as you can see in the screenshot. the window is not resizable, thus the file chooser is not accessible.

This seems to be an UX issue more than anything else.

**Comment by SubJunk** [comment]
This will be better on the new web interface
