### ISSUE TITLE
Ugly icon in status bar

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#965]
As you can see on screenshot, icon in status bar, is terrible.i dont know what for a resolution this icon have, but other apps have 24x24px PNG format and looks well.
I can confirm this issue on more linux distros using MATE, GNOME, XFCE.
![scrnshot](https://cloud.githubusercontent.com/assets/735265/17177499/fd5afb18-5411-11e6-8503-56015c47b112.png)

**Comment by DeFlanko** [comment]
I believe the icon size for the systray is 16x16 which would explain why it looks they way it does when it should be 24x24

![image](https://cloud.githubusercontent.com/assets/5233969/17901617/03ff4eb2-6919-11e6-8996-310b70b638c1.png)

**Comment by DeFlanko** [comment]
ohh i didn't capture the whole code to show what the setting is for Mac.

```
private Image resolveTrayIcon() {
		String icon = "icon-16.png";

		if (Platform.isMac()) {
			icon = "icon-22.png";
		}
		return Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resources/images/" + icon));
	}
```

**Comment by DeFlanko** [comment]
@Subjunk it's been so long since i have done a pull request to push new files, i made a icon-24.png and attached it here to possibly resolve this issue. 
![logo-24](https://cloud.githubusercontent.com/assets/5233969/17902129/e9a9469c-691a-11e6-9981-b5d2bfd88fcf.png)
