### ISSUE TITLE
Add Atmos detection

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#969]
We should detect Atmos and add the option for renderer support.

From MediaInfo:
```
Format                      : Atmos / TrueHD
Codec ID                    : A_TRUEHD
Bit rate mode               : Variable
Maximum bit rate            : 8 199 kb/s
Channel(s)                  : Object Based / 8 channels
Channel positions           : Object Based / Front: L C R, Side: L R, Back: L R, LFE
Sampling rate               :  / 48.0 kHz
Frame rate                  : 1 200.000 FPS (40 spf)
Compression mode            : Lossless
```

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/735/commits/3a9ca5d06f498d61e3dbdd1d80cf90826a5eba38

**Comment by Sami32** [comment]
@SubJunk I'm not sure it's relevent, but since i know your own a PS3 i would just mention that i read that in _IEC61937AudioOutputStream.java_:
> * As of today (2011/07/15), only AC3 and DTS are working on my receiver, Denon AVR-1910
>  * DTS-HD cannot work because it needs a LPCM stream of 2 channels sampled at 192kHz = 6.1Mbits/s. (8 channels for TrueHD, 24Mbit/s)
>  * But PS3 seems to limit the HDMI output's samplerate at 48kHz for Non-HDCP content,
>  * so a downsample of an LPCM encoded audio track destroy the embedded data, alas.
>  *
>  * I disabled it for the time being (see variable skip_dtshd)

**Comment by Sami32** [comment]
I just discovered this nice link to get samples ;-)
http://www.demo-world.eu/2d-demo-trailers-hd/

**Comment by valib** [comment]
done in e6d1a11
