### ISSUE TITLE
Warn users when install new UMS version that first browsing could be slow.

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#973]
When the database version is changed in the new UMS version the database is reset and populated during browsing and when there are a lot of medias in folders for users it seems like the UMS is frozen. Reported in http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=8527&p=27812#p27812. @SubJunk what about in this case to show an info window which warns users that the database was changed and they should be patient during browsing until the database will be restored or to recommend  them to hit the button "Scan all shared folders" to speed up browsing?

**Comment by Sami32** [comment]
Everything that can be able to avoid complain is fine ;-D
Because i remember seen this kind of remarks in  others place on the forum as well.

**Comment by SubJunk** [comment]
@valib good idea. That will be a timely addition for 7.0.0 since we are enhancing the Media Library (Cache) folder a lot in that release.

I've also been thinking about a feature where if a user has selected the "Monitor played status of files" checkbox for the folder (it can maybe be renamed), we have a process that monitors for newly added files to that folder and processes them ahead of time.

I think we can do this without adding a concerning amount of wear to the hard drive if we do it when the file is added since then that operation will be in the hard drive cache and the arm will already be close to the data.

**Comment by atamariya** [comment]
A good idea would be to only scan the current folder and scan the complete library only when asked to do so via console URL. I already run it that way ;-)

**Comment by atamariya** [comment]
A good idea would be to only scan the current folder and scan the complete library only when asked to do so via console URL. I already run it that way ;-) #987

**Comment by ExSport** [comment]
By default it scans only browsed folders if user will not start scanning all library manually.
Because of that it will be slow for the first time as DB is empty after major UMS update.

**Comment by atamariya** [comment]
I was talking about this piece of code. If you have multiple children folders, this increases the scan time significantly.
`
ArrayBlockingQueue<Runnable> queue = new ArrayBlockingQueue<>(count);

					int nParallelThreads = 3;
					if (dlna instanceof DVDISOFile) {
						nParallelThreads = 1; // Some DVD drives die with 3 parallel threads
					}

					ThreadPoolExecutor tpe = new ThreadPoolExecutor(
						Math.min(count, nParallelThreads),
						count,
						20,
						TimeUnit.SECONDS,
						queue
					);

					for (int i = start; i < start + count; i++) {
						if (i < dlna.getChildren().size()) {
							final DLNAResource child = dlna.getChildren().get(i);
							if (child != null) {
								tpe.execute(child);
								resources.add(child);
							} else {
								LOGGER.warn("null child at index {} in {}", i, systemName);
							}
						}
					}`


I've just below code and am fine with scan speed.
`if (dlna != null && searchStr == null) {
			dlna.refreshChildren();
//			TaskRunner.getInstance().submit(resource);
			if (returnChildren) {
				if (count == -1 || (start + count) > dlna.getChildren().size()) {
					count = dlna.getChildren().size();
				}
				if (start > dlna.getChildren().size()) {
					start = dlna.getChildren().size();
				}
				resources.addAll(dlna.getChildren().subList(start, count));
			} else {
				resources.add(dlna);
			}
		}`

**Comment by SubJunk** [comment]
I have been avoiding bumping db versions because of this but it's still a good idea

**Comment by SubJunk** [comment]
We have been doing fast and targeted database updates lately, and there are code changes to prevent freezing too (UMS will prioritize the user browse request above the scan) so I don't think this is needed anymore
