### ISSUE TITLE
[UMS security] filtering devices by uuid / MAC

### ISSUE THREAD

**Issue by squadjot** [UniversalMediaServer/UniversalMediaServer#980]
Now that i have the need for some device filtering, i find out that my network assign new IP's to my devices now and then, and filtering by IP becomes unhandy.

It's possible to some extent to filter by using render conf based on uuid, but it's not perfect, and becomes a bit of a hack.
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=8558.

Could it be implemented so you can use a uuid instead of IP? like: 

00000000-0000-1010-8000-0024BECDE232.folders = c:\child_safe
00000000-0000-1010-8000-0024BECDE232.plugins = SafePlugin
00000000-0000-1010-8000-0024BECDE232.hide_set = true
00000000-0000-1010-8000-0024BECDE232.recent = true

I'd like to hear your thoughts on this.. thumbs up, thumbs down..

**Comment by Nadahar** [comment]
I think that would be problematic simply because the http requests (for serving media) doesn't contain uuid. uuid's are used for UPnP handshakes and capabilities exchange only, and there's no real tie from that to the media requests. That's why "detecting" the correct renderer isn't always reliable either, UMS is trying to make a link that isn't really there. Those that made the standard wasn't very security oriented to say it mildly. 

UMS keeps a "in memory uuid to IP translation table" but it isn't always correct for various reasons. One such reason is that sometimes the http request comes before the UPnP exchange is done. In such instances a uuid based filter would fail completely. In short, it could be implemented but wouldn't be reliable.

When it comes to your home network renewing IP addresses that is normal behaviour and it's also normally very easy to solve. You probably have some device (most likely a router) running a DHCP server. In the DHCP server configuration there should be something called lease time. Buff lease time as much as possible. Lease time is the time each device will keep the same IP.

**Comment by ExSport** [comment]
Or using MAC addresses instead.
Try in cmd on Win:
```
arp -a
```
It will give you "matrix" of IP<->MAC. It should be quite easy to implement this check to MAC instead of IP. I am sure there already exists some class which can be re-used.

**Comment by Nadahar** [comment]
MAC address would be much more viable yes. I haven't looked at the details, but that should be doable.

**Comment by ExSport** [comment]
Edited post about different OSI level communication = MAC not visible from different broadcast domain/network. But this part is secured already by credentials:)

**Comment by squadjot** [comment]
Thank you for commenting. Filtering by MAC sounds like it would solve the problem. I hope it's some thing that you'll consider implementing. :)

**Comment by squadjot** [comment]
I see how uuid and ip can not be compared in terms of how they are obtained. But, in my mind, uuid is still a pretty good way to determine a specific device, right?

My way of making a render conf that catches all devices, and then allow device by creating a render conf based on uuid basically does the job.  Only, there's no renderer variables that allows me to hide/show folders like "Web, Recently Played, New Media". 

Could also just be a simple renderer variable **BlockDevice=true** (default false).

**Comment by valib** [comment]
@squadjot you can try to use the https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Creating-a-custom-device-configuration feature. When the renderer reports the unique UUID than it doesn't matter if the IP address would change. I hope. In the renderer specific configuration you can specify the folders restrictions described in https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/UMS-and-Security

**Comment by squadjot** [comment]
Hi Valib

Yeah, that's what i've done.  http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=8558
As i wrote, no i don't know how to hide "Web, Recently Played, New Media" this does not seem possible.

For an example how would the syntax be for hiding recently played?
recent = false <- wont work

**Comment by valib** [comment]
@squadjot try `hide_recently_played_folder = true`. I know it is not clearly documented but in the renderer specific configuration you can use also settings from the UMS.conf

**Comment by squadjot** [comment]
Ah... okay, thanks! Maybe settings that are also valid in render configs could be marked with a asterisk or something 

hide_new_media_folder =
hide_recently_played_folder =
web_path = <-- ? (If i want to hide "Web" folder)

**Comment by valib** [comment]
@squadjot all settings from the UMS.conf should valid in this case. So we should point out it in the Wiki. Regarding the hiding the Web folder it must be investigated and rewritten.

**Comment by squadjot** [comment]
Oh okay, i can hide the Web folder by using **web_conf=;**
Thanks valib. I'll probably put together a little guide on this.

**Comment by squadjot** [comment]
`UserAgentSearch=.*
UpnpDetailsSearch=.* 
RendererName=Unwanted
LoadingPriority=2
Video=false
Audio=false
Image=false
folders=;
hide_new_media_folder=true 
hide_recently_played_folder=true
hide_video_settings=true
web_conf=;`

This seems to disable everything.

**Comment by valib** [comment]
@squadjot yes you are right but it be simplify to `Video=false Audio=false Image=false` :smile:

**Comment by squadjot** [comment]
Do you mean i don't need those? Because if so then you are right.

**Comment by valib** [comment]
@squadjot I am lost. If you need to prevent some renderer no to access to the UMS you can follow instruction described in https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/UMS-and-Security

**Comment by squadjot** [comment]
Preventing renders seems to be based on IP
I wanted to avoid IP filtering since my router assigns new IP's to my devices regularly.

So i looked into filtering on uuid, as you mentioned.
So the idea was to have a unwanted.conf that contained the settings above. That would basically "disable" all devices. Then to allow a device, you'd create a "custom" config (based on uuid), and that way you have some kind of "uuid whilelist" functionality.

The only thing i was struggling with, was hiding those "extra" folders.. but you helped me with that.

**Comment by squadjot** [comment]
I guess you guys have seen Serviio? The software itself never really worked for my devices but i think some of the interface parts are quite nice and a simple. 

I like how you can easily deal with access for devices, screenshot: http://cordcutting.com/wp-content/uploads/2016/03/serviio-status.png

**Comment by SubJunk** [comment]
This is done in v14
