### ISSUE TITLE
Request option for overlay (when completed)

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#993]
When a ep is complete it will get the overlay that was implanted
Now I watch a lot of anime and never watch the ending title with who worked on it
So it will be nice to have a option for how to set the overlay
For example:
On complete (how it is now)
On time (set minutes like for me like 15 min will set the overlay to the ep
On start when I start a ep it wil right away get the overlay

Hope this can be done sins I think a lot more people will like it

**Comment by Nadahar** [comment]
There's already a configuration setting for this, it's just not documented. If you add ```resume_back = <n>``` to you ```UMS.conf``` file and replace ```<n>``` with a number between 0 and 100, this will be the percentage of a file that has to be played to count as "completed". The default is 92, that is you have to watch 92% of the frames of the given file. 

The same setting affect both the "completed" overlay and the removal of the resume file. When this threshold is reached, the resume file is deleted.

**Comment by Sami32** [comment]
@Goten87 Can this issue be closed ?
https://github.com/UniversalMediaServer/UniversalMediaServer/commit/769e99b61aec344a23b9d76259eab8c24221f062

**Comment by Goten87** [comment]
yeah it can i fixed it with your way ty for that
