### ISSUE TITLE
WMA with CoverArt are not correctly recognized

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#996]
@SubJunk @valib Can i commit this in _DLNAMediaInfo.java_ in the `if (codecV != null)` section ?
```
} else if (codecA.contains("wma")) {
					mimeType = HTTPResource.AUDIO_WMA_TYPEMIME;
```
Because i discovered why this WMA file was not correctly recognized, when WMA files have a coverart they add a video frame, as indicated by MediaInfo: [WMA_CoverArt.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/452590/WMA_CoverArt.txt)
[semesta.wma.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/453017/semesta.wma.txt)

**EDIT**: As commented by @Nadahar it missed something to make it identified as audio.
Maybe adding something like this ?
```
public boolean isWMA() {
		return getCodecA() != null && getCodecA().startsWith("wm") && videoTrackCount == 0;
          }
```
Or add something like that ?
```
if (codecA.contains("wma")) {
				return videoTrackCount == 0;
			}
...

**Comment by Nadahar** [comment]
@Sami32 I think there will be further problems, since it fails [this check](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/dlna/DLNAMediaInfo.java#L337). I don't get why it's registered as a video not an image, but it might have something to do with the ```Windows Media``` format? Remember that ```WMA``` is just the extension, the file itself is a ```Windows Media``` file and as far as I can see there's no way to tell an audio file with cover art from a video file. It would have to be some special treatment if the extension/format was ```WMA```.

**Comment by Sami32** [comment]
@Nadahar Yes, special status for WMA only :wink: 
Why ask ? because they are more skilled than me and could tell me fastly if i'm wrong or do it themself.

Nice catch by the way ;-) Thanks.
So i will need to search more how to do that.

**Comment by Nadahar** [comment]
@Sami32 If you make a PR you can compile and run that version as well, to test what's happening. I use Eclipse and when it's installed and configured it's really easy to do. Being on that branch, you can just debug/run it, and you can place breakpoints and watch variable values in a normal debugging fashion. It makes it much easier to see if things work as intended. The great thing about Eclipse is that you don't have to do the Maven build to test it, you can just run the code after editing it and Eclipse will build what needs rebuilding only.

**Comment by Sami32** [comment]
@Nadahar Thanks...but just don't forget my very old computer have few disk space and memory, too slow.
I would like try though...for now i use @infidel script. The hard and long way ;-)
Only Eclipse can test the code without buiding or any other tools as well ?

**Comment by Nadahar** [comment]
I don't have any overview over all the tools for Java, but Netbeans is an obvious alternative. I haven't used Netbeans for Java (only PHP), but from what I understand running the program isn't that slick there. What makes it so easy in Eclipse is that is has a Maven plugin built in so that it "understands" and handles all the Maven stuff itself.

**Comment by Sami32** [comment]
I tried at the beginning since it was mentioned in the Wiki and need to upgrade perhaps the Maven plugin but i get a compilation error...
So since it was making my computer slow for nothing i deleted it.
I admit that using 45 mn for make a built it's not that enjoying but for now...

**Comment by Nadahar** [comment]
I have only used Eclipse for UMS and I must say this I find it brilliant. It can be a bit tricky to get it configured properly with all the paths to JDK's, project, workspace etc, but once that's done it works great. @valib also uses Eclipse like me, while I think @SubJunk uses Netbeans.

**Comment by Sami32** [comment]
If i'm not wrong he use Eclipse.

**Comment by atamariya** [comment]
@Sami32 Did you create the file or got it from somewhere? It's pretty weird. It's not pure audio as it has a video stream. It's not video either since it fails conversion to mp4 using ffmpeg!!!

**Comment by Sami32** [comment]
@atamariya I agree, i never saw that before.
I created with a great little free extension called "AudioShell" for cover displaying testing purpose, but i will try with MP3Tag and TagScanner as well to verify that point, since i don't really know what the WMA standard need to be for CoverArt/AlbumArt.
That's said the covers are correctly displayed ;-)

**EDIT**: You are right, i downloaded one official WMA file with cover and no video frame inside.
And none of them was able to save CoverArt correctly !
Thanks  :-)
