### ISSUE TITLE
Missing audio Mime-types for 3GA and 3GPPA

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#997]
3GA and 3GPPA will be recognized as video by default.

**audio/3gpp** and **audio/3gpp2** are missing in https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e637a81cd604353938eaf9a3d40039b0d7949a5d/src/main/java/net/pms/network/HTTPResource.java

http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by Nadahar** [comment]
@Sami32 They are probably covered by #735.

**Comment by Sami32** [comment]
@Nadahar No there are missing as well. DTS in WAV is already done.
Btw _audio/3ga_ look wrong to me, since there are not officially referenced or i don't know where...
