### ISSUE TITLE
Renderer discovery issues

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#999]
When I try to test things with the latest snapshot, neither Kodi nor foobar2000 is able to find UMS. UMS sees them, and looking quickly in the log indicates that contentdirectory is queried (and replied) - so my guess is that something is broken in the answer making the renderers discard it.

The last version I tested was around 6.0.0, so it could have happened anywhere in between.

I doubt this only applies to these two renderers, so I'm a bit surprised if that bug has made it in a release without being reported. My Onkyo and PS3 can still see UMS.

As these are software renderers it's easy for anyone to test, so any log files can be generated by those interested.

**Comment by atamariya** [comment]
@Sami32 And I thought I introduced this defect in my version!!

**Comment by SubJunk** [comment]
@Nadahar I wonder if the fix for this will also fix VLC or if that's a different thing. It would be useful if you could install old versions to see when the bug was introduced

**Comment by Sami32** [comment]
@atamariya I saw that issue and didn't report it yet, as it have a positive impact on that issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/880 (Making the timer working correctly and streaming MKV for the few that i tested accidentally some days ago)
I think that 6.3.2, 6.4 or 6.5.0 version will narrow that to recent commit, i suspect one used for Panasonic Viera.

But i didn't do relation with you work...so if it's correct that would be one issue less :wink:

**Comment by Nadahar** [comment]
@SubJunk After 2 hours of constant checking out and building different commits I've narrowed it down to 98b2e8a1fcce4caf071200a4b1bd6b27cbd50bb2. I'm not sure if the commit text ```Makes us more compliant with DLNA standards``` is accurate.

**Comment by Nadahar** [comment]
There's no reason why I should have to test this any further, anyone can install foobar2000 or Kodi since they are software renderers and are both triggered by this bug.

**Comment by SubJunk** [comment]
@Nadahar ah cool, in that case it hasn't been released yet - our last release was a week before this commit - so that's good. I think all of the changes in that commit are taken straight from the standards documentation so it's good to have another example of why it's not good to blindly implement standards.

As for not testing any further, it depends how much it matters to you, and whether you're speaking as a developer or a user ;) I'm happy to look into this issue when I have time and we shouldn't release the next version until this is fixed.

**Comment by SubJunk** [comment]
@Nadahar I installed foobar2000 and don't see a media server part for it, is there a plugin you use?

**Comment by SubJunk** [comment]
@Nadahar I installed Kodi but again I'm not sure how to get to the section that would display UMS - tried with old versions of UMS as well and I couldn't find it. I enabled the UPnP/DLNA options in the settings.
So more details on how you use both of those pieces of software would be helpful :)

**Comment by ExSport** [comment]
@SubJunk If I remember well in KODI you should add new SOURCE and choose DLNA..oh wait I have it installed here but without UMS:-)
VIDEOS --> FILES --> ADD VIDEOS --> BROWSE --> UPnP Devices --> OK --> OK
![image](https://cloud.githubusercontent.com/assets/1260408/18264903/2be2e1e6-7413-11e6-9672-4a11160b60de.png)

**Comment by SubJunk** [comment]
@ExSport thanks, I've reproduced the issue now :)

**Comment by Nadahar** [comment]
@SubJunk In foobar2000 you have to open the ```View``` menu and select ```UPnP Brower```.

**Comment by SubJunk** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/commit/1cd99be792726e7ca79f18eba2deac71c94c72e0 fixes it for me with Kodi, can you test and confirm @Nadahar ?

**Comment by Nadahar** [comment]
1cd99be792726e7ca79f18eba2deac71c94c72e0 fixed it for both foobar2000 and Kodi.

**Comment by SubJunk** [comment]
@Nadahar thanks for confirming

**Comment by Sami32** [comment]
@SubJunk I don't want open an issue for that but in the master branch something is again broken.
Cling Workbench is not usable anymore (i mean that UMS is not detected by Cling).
[debug.log_SUBJUNK_VIERA_CONNECTION_PROBLEM_AVANT_TV.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/459057/debug.log_SUBJUNK_VIERA_CONNECTION_PROBLEM_AVANT_TV.txt)

**Comment by atamariya** [comment]
@Sami32 I think @SubJunk made a fix in 7.0 branch. The change in the commit is not there in master branch. So it couldn't have fixed the issue.

**Comment by Sami32** [comment]
@atamariya Yes, it did in 7.0.0 concerning the Viera detection, just make sure he doesn't forget before build the new version that could not be the 7.0.0. And my report is for Cling problem, but i don't know if it's related to Viera problem.

As i accidentaly discover the Cling problem yesterday while testing for an other issue, i prefer that he verify and remember that before the next build. I'm not sure my log could help him on that though...

As the saying goes: "Prevention is better than cure" (thank you Google translate ;-))

Thanks, i will test that with the 7.0.0 as well.

**Comment by Sami32** [comment]
@SubJunk @atamariya Tested with latest 7.0.0 version and Cling recognized UMS correctly.
I discovered one other connection issue though...
